### ISSUE TITLE
Add LibreOffice to Build Servers (Trac #927)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1009]
We have established the viability of using !LibreOffice Writer 'flat XML' (.fodt) files with !GitHub version control as a platform for writing the new !SasView Tutorials.

Users will want these Tutorials in easily accessible, portable, formats. Certainly html, pdf (so they can print them), and possibly eBook.

We therefore need to be able to build these formats from the .fodt

Our initial idea had been to do this with !PanDoc... until we discovered that whilst !PanDoc supports the !OpenDocument Text (.odt) format, it doesn't support .fodt! So we might just as well do the delivery format conversions with !LibreOffice.

!LibreOffice can be run from the command line. Invoke as {pathto}soffice.

See also: https://help.libreoffice.org/Common/Starting_the_Software_With_Parameters

Migrated from http://trac.sasview.org/ticket/927
```json
{
    "status": "closed",
    "changetime": "2017-10-29T18:42:32",
    "_ts": "2017-10-29 18:42:32.961126+00:00",
    "description": "We have established the viability of using !LibreOffice Writer 'flat XML' (.fodt) files with !GitHub version control as a platform for writing the new !SasView Tutorials.\n\nUsers will want these Tutorials in easily accessible, portable, formats. Certainly html, pdf (so they can print them), and possibly eBook.\n\nWe therefore need to be able to build these formats from the .fodt\n\nOur initial idea had been to do this with !PanDoc... until we discovered that whilst !PanDoc supports the !OpenDocument Text (.odt) format, it doesn't support .fodt! So we might just as well do the delivery format conversions with !LibreOffice.\n\n!LibreOffice can be run from the command line. Invoke as {pathto}soffice.\n\nSee also: https://help.libreoffice.org/Common/Starting_the_Software_With_Parameters",
    "reporter": "smk78",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Admin",
    "time": "2017-04-06T14:00:20",
    "component": "SasView",
    "summary": "Add LibreOffice to Build Servers",
    "priority": "major",
    "keywords": "",
    "milestone": "Admin Tasks",
    "owner": "trnielsen",
    "type": "task"
}
```

**Comment by smk78** [comment]
Trac update at `2017/04/08 14:58:37`: **smk78** commented:

Also see #1014

**Comment by smk78** [comment]
Trac update at `2017/04/11 07:49:28`: 
* **smk78** changed description from:

> We have established the viability of using Libre Office Writer 'flat XML' (.fodt) files with GitHub version control as a platform for writing the new !SasView Tutorials.
> 
> Users will want these Tutorials in easily accessible, portable, formats. Certainly html, pdf (so they can print them), and possibly eBook.
> 
> We therefore need to be able to build these formats from the .fodt
> 
> The obvious package to use to do this is !PanDoc.
> 
> NB: !PanDoc builds pdf via LaTeX, adding impetus to fixing #510
> 

to:

> We have established the viability of using !LibreOffice Writer 'flat XML' (.fodt) files with !GitHub version control as a platform for writing the new !SasView Tutorials.
> 
> Users will want these Tutorials in easily accessible, portable, formats. Certainly html, pdf (so they can print them), and possibly eBook.
> 
> We therefore need to be able to build these formats from the .fodt
> 
> Our initial idea had been to do this with !PanDoc... until we discovered that whilst !PanDoc supports the !OpenDocument Text (.odt) format, it doesn't support .fodt! So we might just as well do the delivery format conversions with !LibreOffice.
> 
> !LibreOffice can be run from the command line. Invoke as {pathto}soffice.
> 
> See also: https://help.libreoffice.org/Common/Starting_the_Software_With_Parameters


* **smk78** changed summary from "Add PanDoc to Build Servers" to "Add LibreOffice to Build Servers"

**Comment by butlerpd** [comment]
Trac update at `2017/10/29 18:41:38`: 
* **butler** changed owner from "" to "trnielsen"
* **butler** changed status from "new" to "assigned"

**Comment by butlerpd** [comment]
Trac update at `2017/10/29 18:42:32`: 
* **butler** commented:

fixed at code camp - closed on JIRA board


* **butler** changed resolution from "" to "fixed"
* **butler** changed status from "assigned" to "closed"
