### ISSUE TITLE
Allow user to define order of models/fit pages for batch fitting (Trac #933)

### ISSUE THREAD

**Issue by wpotrzebowski** [SasView/sasview#1013]
There is no control over the fit pages that go into batch/chain fitting. The current batch fitiing decides the order based on data file names (suposedly). 

Migrated from http://trac.sasview.org/ticket/933
```json
{
    "status": "assigned",
    "changetime": "2018-11-29T12:58:17",
    "_ts": "2018-11-29 12:58:17.363242+00:00",
    "description": "There is no control over the fit pages that go into batch/chain fitting. The current batch fitiing decides the order based on data file names (suposedly). \n",
    "reporter": "wojciech",
    "cc": "",
    "resolution": "",
    "workpackage": "SasView Bug Fixing",
    "time": "2017-04-08T09:17:56",
    "component": "SasView",
    "summary": "Allow user to define order of models/fit pages for batch fitting",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 5.0.0",
    "owner": "wojciech",
    "type": "defect"
}
```

**Comment by wpotrzebowski** [comment]
Trac update at `2017/04/08 11:38:39`: 
* **wojciech** changed owner from "" to "wojciech"
* **wojciech** changed status from "new" to "assigned"

**Comment by butlerpd** [comment]
Trac update at `2017/10/26 20:01:25`: **butler** changed milestone from "SasView 4.2.0" to "SasView 5.0.0"

**Comment by rozyczko** [comment]
Trac update at `2018/11/29 12:58:17`: **piotr** commented:

Added the following functionality:
for batch fitting and with chain fits selected, a new tab shows up in the Batch Fit page.
This tab contains a simple list of all datasets included in the batch. The sets can be moved around and rearranged freely (internal drag and drop).
This order is then used in the batch fit run.
Changes currently in ESS_GUI_ordering branch.

**Comment by rozyczko** [comment]
Merged into ESS_GUI
