### ISSUE TITLE
Slurp tutorial repo for tutorials (Trac #934)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1014]
The new tutorial .fodt files in https://github.com/SasView/tutorials need to be slurped into /sasview/docs/pandoc-docs/source prior to conversion with !PanDoc.

Also see #1009 and #643.

Migrated from http://trac.sasview.org/ticket/934
```json
{
    "status": "closed",
    "changetime": "2017-10-29T18:40:06",
    "_ts": "2017-10-29 18:40:06.130872+00:00",
    "description": "The new tutorial .fodt files in https://github.com/SasView/tutorials need to be slurped into /sasview/docs/pandoc-docs/source prior to conversion with !PanDoc.\n\nAlso see #927 and #510.",
    "reporter": "smk78",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Documentation",
    "time": "2017-04-08T14:55:59",
    "component": "SasView",
    "summary": "Slurp tutorial repo for tutorials",
    "priority": "critical",
    "keywords": "",
    "milestone": "SasView 4.2.0",
    "owner": "ajj",
    "type": "task"
}
```

**Comment by smk78** [comment]
Trac update at `2017/04/10 15:32:38`: 
* **smk78** changed owner from "" to "ajj"
* **smk78** changed status from "new" to "assigned"

**Comment by butlerpd** [comment]
Trac update at `2017/10/29 18:40:06`: 
* **butler** commented:

Andrew says this is done (closed on JIRA board)


* **butler** changed resolution from "" to "fixed"
* **butler** changed status from "assigned" to "closed"
