### ISSUE TITLE
Build new tutorials as PDF (Trac #935)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1015]
To build the new tutorials as PDF they need to be converted from .fodt to PDF with !LibreOffice.

!LibreOffice can be run from the command line. Invoke as {pathto}soffice.

See also: https://help.libreoffice.org/Common/Starting_the_Software_With_Parameters

soffice --convert-to pdf tutorial-file.fodt

Also see #643, #1009, and #1014

Migrated from http://trac.sasview.org/ticket/935
```json
{
    "status": "closed",
    "changetime": "2017-10-29T19:00:56",
    "_ts": "2017-10-29 19:00:56.912240+00:00",
    "description": "To build the new tutorials as PDF they need to be converted from .fodt to PDF with !LibreOffice.\n\n!LibreOffice can be run from the command line. Invoke as {pathto}soffice.\n\nSee also: https://help.libreoffice.org/Common/Starting_the_Software_With_Parameters\n\nsoffice --convert-to pdf tutorial-file.fodt\n\nAlso see #510, #927, and #934",
    "reporter": "smk78",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Documentation",
    "time": "2017-04-08T15:10:46",
    "component": "SasView",
    "summary": "Build new tutorials as PDF",
    "priority": "critical",
    "keywords": "",
    "milestone": "SasView 4.2.0",
    "owner": "",
    "type": "task"
}
```

**Comment by smk78** [comment]
Trac update at `2017/04/11 08:02:47`: **smk78** changed description from:

> To build the new tutorials as PDF they first need to be converted from .fodt to LaTeX with !PanDoc, then shipped to Sphinx for conversion from LateX to PDF.
> 
> Also see #510, #927, and #934

to:

> To build the new tutorials as PDF they need to be converted from .fodt to PDF with !LibreOffice.
> 
> Also see #510, #927, and #934

**Comment by smk78** [comment]
Trac update at `2017/04/11 08:06:47`: **smk78** changed description from:

> To build the new tutorials as PDF they need to be converted from .fodt to PDF with !LibreOffice.
> 
> Also see #510, #927, and #934

to:

> To build the new tutorials as PDF they need to be converted from .fodt to PDF with !LibreOffice.
> 
> !LibreOffice can be run from the command line. Invoke as {pathto}soffice.
> 
> See also: https://help.libreoffice.org/Common/Starting_the_Software_With_Parameters
> 
> soffice --convert-to pdf tutorial-file.fodt
> 
> Also see #510, #927, and #934

**Comment by butlerpd** [comment]
Trac update at `2017/10/29 19:00:56`: 
* **butler** commented:

This is I think a bit of a duplicate ticket but at this point any .fodt file pushed to the tutorial repo will triger a PDF build of the tutorial documentation on an Ubuntu build machine.  The PDF artifact at this points needs to be delivered manually to whatever location it is desired.  Closing this ticket.


* **butler** changed resolution from "" to "fixed"
* **butler** changed status from "new" to "closed"
