### ISSUE TITLE
Single configuration file (Trac #946)

### ISSUE THREAD

**Issue by ricleal** [SasView/sasview#1023]
We need to have a single configuration file for the whole !SasView. See ticket #343 as well

INI or YAML look good options.
If INI format is chosen there's a lot of INI editors that can be embedded in !SasView

Something like this would be useful:

```text
[General]

[Models]
path=/home/.../sasmodels

[Logging]
...
```

Migrated from http://trac.sasview.org/ticket/946
```json
{
    "status": "new",
    "changetime": "2017-10-23T14:34:39",
    "_ts": "2017-10-23 14:34:39.105025+00:00",
    "description": "We need to have a single configuration file for the whole !SasView. See ticket #195 as well\n\nINI or YAML look good options.\nIf INI format is chosen there's a lot of INI editors that can be embedded in !SasView\n\nSomething like this would be useful:\n\n\n{{{\n[General]\n\n[Models]\npath=/home/.../sasmodels\n\n[Logging]\n...\n}}}\n",
    "reporter": "ricardo",
    "cc": "",
    "resolution": "",
    "workpackage": "SasView Framework Enhancements",
    "time": "2017-04-10T14:55:18",
    "component": "SasView",
    "summary": "Single configuration file",
    "priority": "minor",
    "keywords": "",
    "milestone": "SasView 5.0.0",
    "owner": "",
    "type": "enhancement"
}
```

**Comment by ricleal** [comment]
Trac update at `2017/04/10 15:01:55`: 
* **ricardo** commented:

See: https://wiki.python.org/moin/ConfigParserShootout


* **ricardo** changed type from "defect" to "enhancement"
* **ricardo** changed workpackage from "SasView Bug Fixing" to "SasView Framework Enhancements"

**Comment by butlerpd** [comment]
Trac update at `2017/10/23 14:34:39`: **butler** changed description from:

> We need to have a single configuration file for the whole SasView.
> 
> INI or YAML look good options.
> If INI format is chosen there's a lot of INI editors that can be embedded on SasView
> 
> Something like this would be useful:
> 
> 
> {{{
> [General]
> 
> [Models]
> path=/home/.../sasmodels
> 
> [Logging]
> ...
> }}}
> 

to:

> We need to have a single configuration file for the whole !SasView. See ticket #195 as well
> 
> INI or YAML look good options.
> If INI format is chosen there's a lot of INI editors that can be embedded in !SasView
> 
> Something like this would be useful:
> 
> 
> {{{
> [General]
> 
> [Models]
> path=/home/.../sasmodels
> 
> [Logging]
> ...
> }}}
>

**Comment by lucas-wilkins** [comment]
Done! #2164
