### ISSUE TITLE
Include sasmodels api docs in sasview developer documentation (Trac #947)

### ISSUE THREAD

**Issue by ajj** [SasView/sasview#1024]
The developer docs build for sasview should pull in the sasmodels docs.

Migrated from http://trac.sasview.org/ticket/947
```json
{
    "status": "closed",
    "changetime": "2019-03-26T10:25:28",
    "_ts": "2019-03-26 10:25:28.011143+00:00",
    "description": "The developer docs build for sasview should pull in the sasmodels docs.",
    "reporter": "ajj",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Documentation",
    "time": "2017-04-10T15:03:24",
    "component": "SasView",
    "summary": "Include sasmodels api docs in sasview developer documentation",
    "priority": "minor",
    "keywords": "",
    "milestone": "SasView Next Release +1",
    "owner": "ajj",
    "type": "defect"
}
```

**Comment by ajj** [comment]
Trac update at `2017/07/11 13:27:32`: **ajj** changed milestone from "SasView 4.2.0" to "SasView Next Release +1"

**Comment by smk78** [comment]
Trac update at `2019/03/26 10:25:14`: **smk78** commented:

The developer docs accessed through dev.html do now include the !SasModels docs so am closing this ticket.

**Comment by smk78** [comment]
Trac update at `2019/03/26 10:25:28`: 
* **smk78** changed resolution from "" to "fixed"
* **smk78** changed status from "new" to "closed"
