### ISSUE TITLE
mathjax CDN is going away (Trac #948)

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#1025]
According to this announcement:

    https://www.mathjax.org/cdn-shutting-down/

we will all soon be reading raw latex in the help documents, even when we are not on a plane.  Short term solution is to host a copy ourselves, updating the sphinx build appropriately.  

Longer term, need to replace mathjax with katex, which is faster and smaller and easier to bundle with the application.  This is closer to working on Qt than it is in wx.

Migrated from http://trac.sasview.org/ticket/948
```json
{
    "status": "closed",
    "changetime": "2017-07-11T13:01:37",
    "_ts": "2017-07-11 13:01:37.342842+00:00",
    "description": "According to this announcement:\n\n    https://www.mathjax.org/cdn-shutting-down/\n\nwe will all soon be reading raw latex in the help documents, even when we are not on a plane.  Short term solution is to host a copy ourselves, updating the sphinx build appropriately.  \n\nLonger term, need to replace mathjax with katex, which is faster and smaller and easier to bundle with the application.  This is closer to working on Qt than it is in wx.",
    "reporter": "pkienzle",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2017-04-10T21:31:10",
    "component": "SasView",
    "summary": "mathjax CDN is going away",
    "priority": "blocker",
    "keywords": "",
    "milestone": "SasView 4.1.1",
    "owner": "",
    "type": "defect"
}
```

**Comment by ajj** [comment]
Trac update at `2017/05/16 13:34:43`: **ajj** commented:

Temporary change to URL for CDN has been implemented in 4.1.1 branch.

**Comment by ajj** [comment]
Trac update at `2017/05/16 13:39:02`: 
* **ajj** commented:

Moving to next version +1 as the temporary fix is in - longer term solution will be shipped in longer term.


* **ajj** changed milestone from "SasView 4.1.1" to "SasView Next Release +1"

**Comment by ajj** [comment]
Trac update at `2017/05/17 12:12:18`: 
* **ajj** commented:

Closing as long term solution is discussed more in #771


* **ajj** changed resolution from "" to "fixed"
* **ajj** changed status from "new" to "closed"

**Comment by butlerpd** [comment]
Trac update at `2017/05/27 22:46:04`: 
* **butler** commented:

The fix does not seem to be working from the distributable binary downloadable from Jenkins.  Reopening the ticket till it is resolved


* **butler** changed resolution from "fixed" to ""
* **butler** changed status from "closed" to "reopened"

**Comment by butlerpd** [comment]
Trac update at `2017/05/30 12:49:53`: **butler** changed milestone from "SasView Next Release +1" to "SasView 4.1.1"

**Comment by butlerpd** [comment]
Trac update at `2017/05/30 12:52:30`: **butler** commented:

In changeset 36303eefe73e177645ea229e4a1ef4fbe7e465dc:

```text
#!CommitTicketReference repository="sasview" revision="36303eefe73e177645ea229e4a1ef4fbe7e465dc"
Try to fix rendering using new CDN link. addresses #1025
```

**Comment by butlerpd** [comment]
Trac update at `2017/07/11 13:01:37`: 
* **butler** commented:

Fixing for now by launching web browser page (same as for wx<3.0) closing th 4.1.1 ticket but 4.2 ticket #771 is still open.


* **butler** changed resolution from "" to "fixed"
* **butler** changed status from "reopened" to "closed"
