### ISSUE TITLE
Consider releasing new tutorial in 4.1.1 (Trac #955)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1031]
It would be nice to release the revamped tutorials in 4.1.1 as these are now in master.

As the NEW tutorial isn't being auto-built yet, we would be talking about a manual munge, the gist of which SHOULD be:

Replace the following in 4.1.1 with these from master

/sasview/sasview/media/README.txt
/sasview/sasview/media/Tutorial.pdf
/sasview/docs/sasview/Tutorial.pdf
/sasview/docs/sphinx-docs/source/user/tutorial.rst
/sasview/docs/sphinx-docs/source/user/working.rst

and add in

/sasview/sasview/media/getting_started_with_sasview.pdf

Migrated from http://trac.sasview.org/ticket/955
```json
{
    "status": "closed",
    "changetime": "2017-07-14T14:19:18",
    "_ts": "2017-07-14 14:19:18.689233+00:00",
    "description": "It would be nice to release the revamped tutorials in 4.1.1 as these are now in master.\n\nAs the NEW tutorial isn't being auto-built yet, we would be talking about a manual munge, the gist of which SHOULD be:\n\nReplace the following in 4.1.1 with these from master\n\n/sasview/sasview/media/README.txt\n/sasview/sasview/media/Tutorial.pdf\n/sasview/docs/sasview/Tutorial.pdf\n/sasview/docs/sphinx-docs/source/user/tutorial.rst\n/sasview/docs/sphinx-docs/source/user/working.rst\n\nand add in\n\n/sasview/sasview/media/getting_started_with_sasview.pdf\n\n",
    "reporter": "smk78",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Documentation",
    "time": "2017-04-11T10:05:21",
    "component": "SasView",
    "summary": "Consider releasing new tutorial in 4.1.1",
    "priority": "blocker",
    "keywords": "",
    "milestone": "SasView 4.1.1",
    "owner": "ajj",
    "type": "task"
}
```

**Comment by ajj** [comment]
Trac update at `2017/07/14 14:19:18`: 
* **ajj** commented:

In changeset 9a76292ee475e6a8f00857d85188e7a561a1d8cf:

```text
#!CommitTicketReference repository="sasview" revision="9a76292ee475e6a8f00857d85188e7a561a1d8cf"
New tutorial pdf and updated rst files to point to it from master. Closes #1031
```


* **ajj** changed resolution from "" to "fixed"
* **ajj** changed status from "new" to "closed"
