### ISSUE TITLE
Namespace clash for sasgui if shipped as separate package (Trac #957)

### ISSUE THREAD

**Issue by ajj** [SasView/sasview#1033]
sasgui is an already taken name on !PyPi

as part of the code reorg, sasgui will have to become sasview so we have:

sasview - gui parts
sascalc - calculation parts 
sasmodels - model calculations

We have all those names reserved on PyPi

Migrated from http://trac.sasview.org/ticket/957
```json
{
    "status": "new",
    "changetime": "2017-10-23T15:32:48",
    "_ts": "2017-10-23 15:32:48.025319+00:00",
    "description": "sasgui is an already taken name on !PyPi\n\nas part of the code reorg, sasgui will have to become sasview so we have:\n\nsasview - gui parts\nsascalc - calculation parts \nsasmodels - model calculations\n\nWe have all those names reserved on PyPi",
    "reporter": "ajj",
    "cc": "",
    "resolution": "",
    "workpackage": "SasView GUI Enhancements",
    "time": "2017-04-26T15:01:24",
    "component": "SasView",
    "summary": "Namespace clash for sasgui if shipped as separate package",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 5.0.0",
    "owner": "piotr",
    "type": "defect"
}
```

**Comment by rozyczko** [comment]
Trac update at `2017/04/26 15:20:11`: **piotr** commented:

This has already been considered.
The current GUI is developed in src/sas/qtgui with the goal of being completely independent on src/sas/sasgui eventually. Then, we can replace 'qtgui' with say, 'sasview' as the module name and delete sasgui (or make/mark it obsolete without actually deleting the old code...)

**Comment by butlerpd** [comment]
Trac update at `2017/10/23 15:32:48`: **butler** changed description from:

> sasgui is an already taken name on PyPi
> 
> as part of the code reorg, sasgui will have to become sasview so we have:
> 
> sasview - gui parts
> sascalc - calculation parts 
> sasmodels - model calculations
> 
> We have all those names reserved on PyPi

to:

> sasgui is an already taken name on !PyPi
> 
> as part of the code reorg, sasgui will have to become sasview so we have:
> 
> sasview - gui parts
> sascalc - calculation parts 
> sasmodels - model calculations
> 
> We have all those names reserved on PyPi

**Comment by rozyczko** [comment]
Since Wojtek is assigned as the sascalc/sasview maintainer, I am reassigning this task to him.
