### ISSUE TITLE
Inconsistent chi2 reporting (Trac #966)

### ISSUE THREAD

**Issue by mdoucet** [SasView/sasview#1040]
If you fit data with any model, the expectation is the following:
 
1- The parameters update to the fitted parameters
2- The chi2 updates to the value for the updated model
 
But after the fit is complete and you press enter (not changing any value) in any of the model parameters, you will notice that the chi2 will change.
It usually drops by a significant amount. I assume that the updated value is the correct one.
 
I had !SasView 4.0 on my laptop so I tested it and it has the same issue.
So:
  1- The problem dates back to at least 4.0
  2- The problem exists for both DREAM and LM (didn’t test the other engines)
 3- The problem exists for both built-in models and plug-in models

Migrated from http://trac.sasview.org/ticket/966
```json
{
    "status": "closed",
    "changetime": "2017-10-27T08:29:23",
    "_ts": "2017-10-27 08:29:23.283671+00:00",
    "description": "If you fit data with any model, the expectation is the following:\n \n1- The parameters update to the fitted parameters\n2- The chi2 updates to the value for the updated model\n \nBut after the fit is complete and you press enter (not changing any value) in any of the model parameters, you will notice that the chi2 will change.\nIt usually drops by a significant amount. I assume that the updated value is the correct one.\n \nI had !SasView 4.0 on my laptop so I tested it and it has the same issue.\nSo:\n  1- The problem dates back to at least 4.0\n  2- The problem exists for both DREAM and LM (didn\u2019t test the other engines)\n 3- The problem exists for both built-in models and plug-in models",
    "reporter": "mathieu",
    "cc": "",
    "resolution": "invalid",
    "workpackage": "SasView Bug Fixing",
    "time": "2017-05-19T19:22:28",
    "component": "SasView",
    "summary": "Inconsistent chi2 reporting",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.2.0",
    "owner": "",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2017/10/27 08:29:23`: 
* **butler** commented:

As documented in ticket #1012 and in some of the user list discussions this has been determined to in fact be the correct behavior.  The documentation (and GUI information) needs to be fixed.  The reason this is correct behavior is that what is being reported is the proper reduced chi2: (sum of residuals squared)/ DOF (degrees of freedom).  For a fit the DOF = Npts-#fitted parameters.  When hitting compute the #fitted parameters = 0 and therefore DOF=Npts.

Thus compute will always show a SMALLER chi2 than the fit value.  the correct fitted value.

This ticket is therefore being closed at this point.  Ticket #1012 is still open pending updates listed there.


* **butler** changed resolution from "" to "invalid"
* **butler** changed status from "new" to "closed"
