### ISSUE TITLE
About Box not picking up dls_logo.png (Trac #969)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1043]
Testing Jenkins build http://trac.sasview.org/ticket/702 on W10

About box not picking up dls_logo.png and is causing an error to be thrown.

Migrated from http://trac.sasview.org/ticket/969
```json
{
    "status": "closed",
    "changetime": "2017-07-13T11:24:45",
    "_ts": "2017-07-13 11:24:45.521296+00:00",
    "description": "Testing Jenkins build #702 on W10\n\nAbout box not picking up dls_logo.png and is causing an error to be thrown.\n",
    "reporter": "smk78",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2017-05-31T13:19:58",
    "component": "SasView",
    "summary": "About Box not picking up dls_logo.png",
    "priority": "blocker",
    "keywords": "",
    "milestone": "SasView 4.2.0",
    "owner": "Piotr Rozyczko <rozyczko@gmail.c",
    "type": "defect"
}
```

**Comment by smk78** [comment]
Trac update at `2017/05/31 14:19:42`: 
* **smk78** changed resolution from "" to "invalid"
* **smk78** changed status from "new" to "closed"

**Comment by smk78** [comment]
Trac update at `2017/05/31 14:20:10`: **smk78** commented:

Non-issue. Had installed wrong version. Sorry

**Comment by rozyczko** [comment]
Trac update at `2017/07/13 11:24:45`: **piotr** commented:

images should go to sasview/images, not src/sas/sasgui/guiframe/images.
The latter should only be used for GUI sourced icons
The content of src/sas/sasgui/guiframe/images will get copied to images/icons on installation.

Fixed in 969_about_box_logo branch
