### ISSUE TITLE
blacklist Intel HD 620/630 for double precision (Trac #974)

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#1048]
Double precision models are failing for the new Kaby Lake processor series from Intel (HD 620/630). Until the drivers are fixed we need to avoid using this GPU for double precision.  

We cannot reliably identify the GPU device from OpenCL; on Ubuntu it identifies only as Intel HD Graphics, not the particular model number. Instead we will need to to extend sasmodels.kernelcl so that we can indicate which device should be used for single precision and which should be used for double precision, and extend sas.sasgui.perspectives.fitting.gui_options so that we can indicate which device to use for single precision and which device to use for double precision.

We could use the code from the following to identify processor:

    https://github.com/pydata/numexpr/blob/master/numexpr/cpuinfo.py

which has Win32CPUInfo, DarwinCPUInfo, LinuxCPUInfo; from there we can get family/model/stepping for intel processors, and by knowing the Kaby Lake processor family, exclude them by default from double precsion devices.

Migrated from http://trac.sasview.org/ticket/974
```json
{
    "status": "closed",
    "changetime": "2018-03-04T17:23:56",
    "_ts": "2018-03-04 17:23:56.134114+00:00",
    "description": "Double precision models are failing for the new Kaby Lake processor series from Intel (HD 620/630). Until the drivers are fixed we need to avoid using this GPU for double precision.  \n\nWe cannot reliably identify the GPU device from OpenCL; on Ubuntu it identifies only as Intel HD Graphics, not the particular model number. Instead we will need to to extend sasmodels.kernelcl so that we can indicate which device should be used for single precision and which should be used for double precision, and extend sas.sasgui.perspectives.fitting.gui_options so that we can indicate which device to use for single precision and which device to use for double precision.\n\nWe could use the code from the following to identify processor:\n\n    https://github.com/pydata/numexpr/blob/master/numexpr/cpuinfo.py\n\nwhich has Win32CPUInfo, DarwinCPUInfo, LinuxCPUInfo; from there we can get family/model/stepping for intel processors, and by knowing the Kaby Lake processor family, exclude them by default from double precsion devices.\n",
    "reporter": "pkienzle",
    "cc": "",
    "resolution": "obsolete",
    "workpackage": "SasView Bug Fixing",
    "time": "2017-06-06T21:15:25",
    "component": "SasView",
    "summary": "blacklist Intel HD 620/630 for double precision",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.2.0",
    "owner": "",
    "type": "defect"
}
```

**Comment by pkienzle** [comment]
Trac update at `2017/06/07 21:47:41`: **pkienzle** commented:

Don't need to identify the processor just yet.  For now reject fp64 on a GPU device if the vendor is Intel.  That will get around the problems on HD 620/630 but won't address the problems with Iris 6100, HD 4400 and HD 5500 identified in OpenClTest.

Kaby Lake CPU IDs extracted from http://browser.geekbench.com/v4/cpu
||Family-model-stepping|| Processor ||
|| 6-142-9|| Intel Core i3-7100U @ 2.40 GHz ||
|| 6-142-9|| Intel Core i5-7200U @ 2.69 GHz ||
|| 6-142-9|| Intel Core i5-7300U @ 2.69 GHz ||
|| 6-142-9|| Intel Core i7-7600U @ 2.89 GHz ||
|| 6-158-9|| Intel Core i3-7100  @ 800 MHz  ||
|| 6-158-9|| Intel Core i5-7400 @ 2.99 GHz  ||
|| 6-158-9|| Intel Core i5-7600 @ 3.50 GHz  ||
|| 6-158-9|| Intel Core i7-7700  @ 3.60GHz  ||
|| 6-158-9|| Intel Core i7-7700K @ 4.20 GHz ||
|| 6-158-9|| Intel Core i7-7700HQ @ 2.79 GHz ||
|| 6-158-9|| Intel Xeon E3-1505M v6 @ 2.99 GHz ||

**Comment by butlerpd** [comment]
Trac update at `2017/10/27 16:06:13`: **butler** changed milestone from "SasView 4.2.0" to "SasView 4.3.0"

**Comment by pkienzle** [comment]
Trac update at `2018/01/16 03:17:17`: **pkienzle** commented:

Newer Intel OpenCL drivers may have fixed the problem (at least it did on a HD 6100 GPU).

**Comment by butlerpd** [comment]
Trac update at `2018/03/04 17:23:56`: **butler** changed milestone from "SasView 4.3.0" to "SasView 4.2.0"
