### ISSUE TITLE
CanSas HDF reader will not read all valid CanSas HDF (NXcanSAS) files (Trac #976)

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#1049]
The current canSAS reader is interpreting fields by name even when the name of the field is not specified in the canSAS spec:

    http://download.nexusformat.org/doc/html/classes/applications/NXcanSAS.html

For example, the mask information is being read from the "Mask" field, but the spec says that the mask field name given by the required @mask attribute of the !SasData group.  It may happen to work since "Mask" is a likely field name for the mask data, but "mask" is equally likely and HDF is case sensitive.

It may be that the reduction software is not writing the required attribute names, but the reader should at least check prior to looking for the default names such as "mask" or "Mask".

Migrated from http://trac.sasview.org/ticket/976
```json
{
    "status": "closed",
    "changetime": "2019-01-02T20:57:50",
    "_ts": "2019-01-02 20:57:50.531067+00:00",
    "description": "The current canSAS reader is interpreting fields by name even when the name of the field is not specified in the canSAS spec:\n\n    http://download.nexusformat.org/doc/html/classes/applications/NXcanSAS.html\n\nFor example, the mask information is being read from the \"Mask\" field, but the spec says that the mask field name given by the required @mask attribute of the !SasData group.  It may happen to work since \"Mask\" is a likely field name for the mask data, but \"mask\" is equally likely and HDF is case sensitive.\n\nIt may be that the reduction software is not writing the required attribute names, but the reader should at least check prior to looking for the default names such as \"mask\" or \"Mask\".\n",
    "reporter": "pkienzle",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2017-06-07T22:46:37",
    "component": "SasView",
    "summary": "CanSas HDF reader will not read all valid CanSas HDF (NXcanSAS) files",
    "priority": "blocker",
    "keywords": "",
    "milestone": "SasView 4.2.1",
    "owner": "krzywon",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2017/06/11 18:20:17`: **butler** changed description from:

> The current CanSas reader is interpreting fields by name even when the name of the field is not specified in the CanSas spec:
> 
>     http://download.nexusformat.org/doc/html/classes/applications/NXcanSAS.html
> 
> For example, the mask information is being read from the "Mask" field, but the spec says that the mask field name given by the required @mask attribute of the SasData group.  It may happen to work since "Mask" is a likely field name for the mask data, but "mask" is equally likely and HDF is case sensitive.
> 
> It may be that the reduction software is not writing the required attribute names, but the reader should at least check prior to looking for the default names such as "mask" or "Mask".
> 

to:

> The current canSAS reader is interpreting fields by name even when the name of the field is not specified in the canSAS spec:
> 
>     http://download.nexusformat.org/doc/html/classes/applications/NXcanSAS.html
> 
> For example, the mask information is being read from the "Mask" field, but the spec says that the mask field name given by the required @mask attribute of the !SasData group.  It may happen to work since "Mask" is a likely field name for the mask data, but "mask" is equally likely and HDF is case sensitive.
> 
> It may be that the reduction software is not writing the required attribute names, but the reader should at least check prior to looking for the default names such as "mask" or "Mask".
>

**Comment by smk78** [comment]
Trac update at `2017/06/14 14:26:33`: **smk78** commented:

Whose reduction software are we talking about here?

**Comment by butlerpd** [comment]
Trac update at `2017/06/14 14:46:45`: **butler** commented:

We are not talking about anybody's specific writer.  The point is that because it is hard to get agreement on nomenclature sometimes, many fields are defined by an attribute tag that gives the name of the field as in the mask example given.  Basically if your writer uses "Mask" as the field name then our reader will read it but that is INCORRECT implementation -- we SHOULD be looking not for "Mask" but for the @mask to get the name of the field we are to look for (which COULD be "steve" instead or "mask" instead of "Mask")

Our reader should follow the spec if we are going to claim it is a standard and we read anybody's file who adheres to said spec :-)

**Comment by smk78** [comment]
Trac update at `2017/06/14 14:57:08`: **smk78** commented:

Ahh, ok. I read 'It may be that the reduction software is not writing the required attribute names' and wondered what reduction software that meant.

**Comment by butlerpd** [comment]
Trac update at `2017/10/27 12:32:09`: **butler** changed milestone from "SasView Next Release +1" to "SasView 4.3.0"

**Comment by smk78** [comment]
Trac update at `2018/07/05 09:43:29`: 
* **smk78** changed _comment0 from:

> Transferred from #1127:
> 
> Jan !Ilvasky/Pete Jemian have noted several issues with how !SasView handles NXcanSAS:
> 
> i) !SasView expects NXcanSAS to have the .h5 extension, however such enforcement actually breaks the NeXus standard which doesn't specify an extension (Tim Snow notes that .h5, .nxs, .nexus, .hdf, even .nx.hdf are in use!);
> 
> ii) the .h5 example files in the !SasView /test folder are actually incompatible with the NXcanSAS standard, they use the attributes “uncertainty” and “I_uncertainty" instead of the plural “uncertainties”.
> 
> Separately, Brian Pauw would now really like !SasView to start loading NXcanSAS containing @Mask_indicies (which rather spookily goes to the original reason this ticket was opened).

to:

> 1530783846433216


* **smk78** commented:

Transferred from #1168:

Jan !Ilvasky/Pete Jemian have noted several issues with how !SasView handles NXcanSAS:

i) !SasView expects NXcanSAS to have the .h5 extension, however such enforcement actually breaks the !NeXus standard which doesn't specify an extension (Tim Snow notes that .h5, .nxs, .nexus, .hdf, even .nx.hdf are in use!);

ii) the .h5 example files in the !SasView /test folder are actually incompatible with the NXcanSAS standard, they use the attributes “uncertainty” and “I_uncertainty" instead of the plural “uncertainties”.

Separately, Brian Pauw would now really like !SasView to start loading NXcanSAS containing @Mask_indicies (which rather spookily goes to the original reason this ticket was opened).

**Comment by smk78** [comment]
Trac update at `2018/07/05 09:44:49`: **smk78** changed summary from "CanSas HDF reader will not read all valid CanSas HDF files" to "CanSas HDF reader will not read all valid CanSas HDF (NXcanSAS) files"

**Comment by smk78** [comment]
Trac update at `2018/07/05 09:45:33`: **smk78** commented:

Added NXcanSAS to ticket title so it can be found easier in ticket searches.

**Comment by smk78** [comment]
Trac update at `2018/07/05 09:46:45`: **smk78** commented:

Transferred from #1168:

@butler writes:

The bottom line is we know that we are in fact not fully compliant with the NXcanSAS standard and need to fix that.... but we cannot necessarily use all the things that a specific NXcanSAS file gives us. What the reader should do is accept any NXcanSAS standard compliant file that contains the information needed by !SasView. 

This means:

* Check for an NXcanSAS format beyond its extension (as required by the spec)
* Read all the !SasView relevant information as long as it is provided in a way that conforms to the standard -- meaning we must look at the attribute tags first
* In the absence of an attribute tag we should look for common names we expect (but this is an extra so don't need to guess everybody's naming)
* accept any file we can extract the appropriate information from even if it contains a lot of extra guff we don't understand (said guf being discarded by !SasView)

**Comment by smk78** [comment]
Trac update at `2018/07/05 09:47:33`: 
* **smk78** commented:

As this has become a more pressing matter I'm making it a blocker for 4.3.


* **smk78** changed priority from "minor" to "blocker"

**Comment by butlerpd** [comment]
Trac update at `2018/10/30 21:54:50`: 
* **butler** commented:

As agreed at the Tuesday meeting we are now planning a 4.2.1 version for which this will be the main feature.  Moving ticket to that milestone.


* **butler** changed milestone from "SasView 4.3.0" to "SasView 4.2.1"
