### ISSUE TITLE
Don't use \text in equations (Trac #977)

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#1050]
The \text environment renders with a different font in mathjax and in latex, and should be avoided.  Furthermore, latex fails if the text contains an underscore and mathjax fails if the the text contains \_.  Use \mathrm instead.  

Mathjax treats this as expected behaviour and will not fix: https://github.com/mathjax/MathJax/issues/1770.

See also #643: build PDF documentation along with HTML.

Migrated from http://trac.sasview.org/ticket/977
```json
{
    "status": "new",
    "changetime": "2017-10-27T17:09:41",
    "_ts": "2017-10-27 17:09:41.159266+00:00",
    "description": "The \\text environment renders with a different font in mathjax and in latex, and should be avoided.  Furthermore, latex fails if the text contains an underscore and mathjax fails if the the text contains \\_.  Use \\mathrm instead.  \n\nMathjax treats this as expected behaviour and will not fix: https://github.com/mathjax/MathJax/issues/1770.\n\nSee also #510: build PDF documentation along with HTML.",
    "reporter": "pkienzle",
    "cc": "",
    "resolution": "",
    "workpackage": "SasView Bug Fixing",
    "time": "2017-06-16T13:54:06",
    "component": "SasView",
    "summary": "Don't use \\text in equations",
    "priority": "minor",
    "keywords": "",
    "milestone": "SasView 4.3.0",
    "owner": "",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2017/10/27 17:09:41`: 
* **butler** commented:

So the ticket here is to go back and replace all instances of \text I guess.


* **butler** changed milestone from "SasView 4.2.0" to "SasView 4.3.0"

**Comment by butlerpd** [comment]
I have not seen any problems in documentation so wondering if all we need to do now @pkienzle is to add some instructions on the wiki somewhere on instructions for writing docs?  Meanwhile I will move this to 5.0.3

**Comment by pkienzle** [comment]
I'll close it.  If it is a problem later then we should be able to get back here via web search.

**Comment by smk78** [comment]
There are 15 uses of \text in 5.x:

```
/qtsasviewdocumentation/docs/sphinx-docs/source/conf.py (1 match)
/qtsasviewdocumentation/src/sas/qtgui/Calculators/media/resolution_calculator_help.rst (4 matches)
/qtsasviewdocumentation/src/sas/qtgui/Calculators/media/sas_calculator_help.rst (5 matches)
/qtsasviewdocumentation/src/sas/qtgui/Perspectives/Corfunc/media/corfunc_help.rst (5 matches)
```

and considerably more in 4.x
