### ISSUE TITLE
Windows x64 versions not installing to correct folder (Trac #993)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1064]
At present the x86 (32-bit) and x64 versions of !SasView are both installing to C:\Program Files (x86) by default. The x64 should install to C:\Program Files.

Aside from being 'poor form', it also means you currently can't install both versions in parallel without manual intervention. Shortcuts also get overwritten.

Migrated from http://trac.sasview.org/ticket/993
```json
{
    "status": "closed",
    "changetime": "2018-01-15T23:12:00",
    "_ts": "2018-01-15 23:12:00.323003+00:00",
    "description": "At present the x86 (32-bit) and x64 versions of !SasView are both installing to C:\\Program Files (x86) by default. The x64 should install to C:\\Program Files.\n\nAside from being 'poor form', it also means you currently can't install both versions in parallel without manual intervention. Shortcuts also get overwritten.",
    "reporter": "smk78",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2017-09-06T12:43:56",
    "component": "SasView",
    "summary": "Windows x64 versions not installing to correct folder",
    "priority": "critical",
    "keywords": "",
    "milestone": "SasView 4.2.0",
    "owner": "piotr",
    "type": "defect"
}
```

**Comment by rozyczko** [comment]
Trac update at `2017/12/14 15:57:22`: 
* **piotr** changed owner from "" to "piotr"
* **piotr** changed status from "new" to "assigned"

**Comment by rozyczko** [comment]
Trac update at `2017/12/15 10:00:49`: **piotr** commented:

Fixed.
Added a 64bit specific directive to the INNO setup file.
Pull request:
https://github.com/SasView/sasview/pull/133
