### ISSUE TITLE
OpenCL required on Linux even if turned off in GUI (Trac #995)

### ISSUE THREAD

**Issue by ajj** [SasView/sasview#1066]
There seems to be an issue on linux that OpenCL is assumed even if there is no driver. There needs to be a fallback to compiling without OpenCL as per windows.

Migrated from http://trac.sasview.org/ticket/995
```json
{
    "status": "closed",
    "changetime": "2017-12-19T10:06:58",
    "_ts": "2017-12-19 10:06:58.586941+00:00",
    "description": "There seems to be an issue on linux that OpenCL is assumed even if there is no driver. There needs to be a fallback to compiling without OpenCL as per windows.",
    "reporter": "ajj",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2017-09-18T08:28:01",
    "component": "SasView",
    "summary": "OpenCL required on Linux even if turned off in GUI",
    "priority": "critical",
    "keywords": "",
    "milestone": "SasView 4.2.0",
    "owner": "awashington",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2017/10/27 16:13:42`: **butler** changed milestone from "SasView 4.2.0" to "SasView 4.3.0"

**Comment by butlerpd** [comment]
Trac update at `2017/12/12 14:47:13`: 
* **butler** changed milestone from "SasView 4.3.0" to "SasView 4.2.0"
* **butler** changed owner from "" to "awashington"
* **butler** changed priority from "major" to "critical"
* **butler** changed status from "new" to "assigned"

**Comment by rprospero** [comment]
Trac update at `2017/12/19 10:06:42`: **awashington** commented:

Fixed in pull request http://trac.sasview.org/ticket/132

**Comment by rprospero** [comment]
Trac update at `2017/12/19 10:06:58`: 
* **awashington** changed resolution from "" to "fixed"
* **awashington** changed status from "assigned" to "closed"
