### ISSUE TITLE
save points as file from graph loses precision (Trac #997)

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#1068]
When using the graph menu option to save points from graph to a file, it is only saving about 6 digits of precision rather than full 15 digits available.  Should use %.15g or maybe %.15e rather than %g for the number format.

Migrated from http://trac.sasview.org/ticket/997
```json
{
    "status": "new",
    "changetime": "2017-10-27T08:31:56",
    "_ts": "2017-10-27 08:31:56.079152+00:00",
    "description": "When using the graph menu option to save points from graph to a file, it is only saving about 6 digits of precision rather than full 15 digits available.  Should use %.15g or maybe %.15e rather than %g for the number format.\n\n",
    "reporter": "pkienzle",
    "cc": "",
    "resolution": "",
    "workpackage": "SasView Bug Fixing",
    "time": "2017-09-19T14:50:53",
    "component": "SasView",
    "summary": "save points as file from graph loses precision",
    "priority": "minor",
    "keywords": "",
    "milestone": "SasView 5.0.0",
    "owner": "",
    "type": "defect"
}
```

**Comment by pkienzle** [comment]
Trac update at `2017/09/19 14:51:10`: **pkienzle** changed priority from "major" to "minor"

**Comment by pkienzle** [comment]
Trac update at `2017/09/19 14:52:10`: **pkienzle** commented:

The datainfo window shows 12 digits.

**Comment by butlerpd** [comment]
Trac update at `2017/10/27 08:31:56`: **butler** changed milestone from "SasView 4.2.0" to "SasView 5.0.0"

**Comment by RichardHeenan** [comment]
Precision is still limited in 5.0 (note check with a theory, not experimental data, which may have been supplied with limited precision anyway).

Also "save points as a file" (from a plot) or "save as" from data tree, is in 5.0 not remembering the previous save to directory name, which would be nice.

**Comment by rozyczko** [comment]
Fixed precision - changed to %.15e as suggested.
Fixed corresponding <X>, <Y> etc. marker locations
Fixed the 'memory' of the Save As... widget, so it remembers the last save location.

**Comment by RichardHeenan** [comment]
Tested, issues fixed, thank you. Closing issue.
