### ISSUE TITLE
Should we use Dispersity instead of Polydispersity/Monodispersity? (Trac #1003)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1072]
pkienzle has discovered that IUPAC formally deprecated use of the terms polydispersity and monodispersity as long ago as 2009! They advocate the use of dispersity. See:

http://www.freepatentsonline.com/article/Pure-Applied-Chemistry/195013012.html

https://en.wikipedia.org/wiki/Polydispersity

They further advocate the use of a 'stroke-D' symbol (Ð, unicode U+0110) for dispersity (https://tex.stackexchange.com/questions/85546/why-cant-i-get-a-d-with-stroke)

The question for us, therefore, is whether we should update all our documentation (and, in some cases, model parameters and GUIs)?

Discuss!

Migrated from http://trac.sasview.org/ticket/1003
```json
{
    "status": "closed",
    "changetime": "2019-03-26T09:50:12",
    "_ts": "2019-03-26 09:50:12.425647+00:00",
    "description": "pkienzle has discovered that IUPAC formally deprecated use of the terms polydispersity and monodispersity as long ago as 2009! They advocate the use of dispersity. See:\n\nhttp://www.freepatentsonline.com/article/Pure-Applied-Chemistry/195013012.html\n\nhttps://en.wikipedia.org/wiki/Polydispersity\n\nThey further advocate the use of a 'stroke-D' symbol (\u00d0, unicode U+0110) for dispersity (https://tex.stackexchange.com/questions/85546/why-cant-i-get-a-d-with-stroke)\n\nThe question for us, therefore, is whether we should update all our documentation (and, in some cases, model parameters and GUIs)?\n\nDiscuss!\n",
    "reporter": "smk78",
    "cc": "",
    "resolution": "wontfix",
    "workpackage": "SasView Documentation",
    "time": "2017-09-29T14:01:53",
    "component": "SasView",
    "summary": "Should we use Dispersity instead of Polydispersity/Monodispersity?",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.3.0",
    "owner": "",
    "type": "task"
}
```

**Comment by butlerpd** [comment]
Trac update at `2017/10/01 18:38:53`: **butler** commented:

Discussion:

I think most users still think in terms of poly and mono dispersity, so a change would mainly be for the purpose of helping disseminate/enforce a new standard. I would argue that if that is the case, we have way too much more important work that needs to get done with our very small resources to make this a priority?

As for the symbol I suspect 90+% of our users would have NO idea what that meant so as a symbol it is not very helpful, where I measure a symbol's utility in its ability to provide a '''recognizable''' short hand for the concept.

**Comment by butlerpd** [comment]
Trac update at `2017/10/27 16:40:43`: **butler** changed milestone from "SasView 4.2.0" to "SasView 4.3.0"

**Comment by smk78** [comment]
Trac update at `2019/03/26 09:49:56`: **smk78** commented:

There are (at the time of writing) 1608 instances of words containing the root "dispersity" across !SasView and !SasModels. Whilst a global search and replace could be employed, the view at Code Camp IX is that would not be a professional approach. The decision therefore is that we will not address this ticket.

**Comment by smk78** [comment]
Trac update at `2019/03/26 09:50:12`: 
* **smk78** changed resolution from "" to "wontfix"
* **smk78** changed status from "new" to "closed"
