### ISSUE TITLE
spherical_sld model freezes SasView (Trac #1007)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#1076]
Loading the spherical_sld model (sometimes it requires multiplying by SQ but not always) freezes the !SasView GUI.

Migrated from http://trac.sasview.org/ticket/1007
```json
{
    "status": "closed",
    "changetime": "2017-12-10T00:30:01",
    "_ts": "2017-12-10 00:30:01.637122+00:00",
    "description": "Loading the spherical_sld model (sometimes it requires multiplying by SQ but not always) freezes the !SasView GUI.",
    "reporter": "butler",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2017-10-03T17:09:37",
    "component": "SasView",
    "summary": "spherical_sld model freezes SasView",
    "priority": "blocker",
    "keywords": "",
    "milestone": "SasView 4.2.0",
    "owner": "",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2017/10/28 13:17:46`: **butler** commented:

The traceback error is the following


```text
Traceback (most recent call last):
  File "C:\Users\paperspace\git\sasview\src\sas\sasgui\perspectives\fitting\fitpage.py", line 1174, in _on_select_model
    self.set_model_param_sizer(self.model)
  File "C:\Users\paperspace\git\sasview\src\sas\sasgui\perspectives\fitting\fitpage.py", line 2860, in set_model_param_sizer
    self._set_fun_box_list(fun_box)
  File "C:\Users\paperspace\git\sasview\src\sas\sasgui\perspectives\fitting\fitpage.py", line 1735, in _set_fun_box_list
    for key, val in list.items():
AttributeError: 'tuple' object has no attribute 'items'
08:50:26 - INFO : sas.sasgui.guiframe.gui_manager:2019:  --- SasView session was closed --- 

```

This suggests that the other multiplicity models don't go through this code? but why?

**Comment by butlerpd** [comment]
Trac update at `2017/10/28 21:55:02`: **butler** changed _comment0 from "I was looking to this and made a try to fix the problem in the branch ticket1007. SasView is freezing because the model has a combo box to select the shape of each interface and the possible values are stored in a tuple (self.model.fun_list), but the function _set_fun_box_list tries to access fun_list as a dictionary.  With the changes I did, now the model works. However, self.model.fun_list is still used like a dictionary in several places in basepage.py, so I expect similar problems in other cases. I guess that someone with a better understanding of the different uses of fun_list should finish the work before making the pull request." to "1509303394125122"

**Comment by gonzalezma** [comment]
Trac update at `2017/10/28 21:55:02`: **gonzalezm** commented:

I was looking to this and made a try to fix the problem in the branch ticket1007. !SasView is freezing because the model has a combo box to select the shape of each interface and the possible values are stored in a tuple (self.model.fun_list), but the function _set_fun_box_list tries to access fun_list as a dictionary.  With the changes I did, now the model works. However, self.model.fun_list is still used like a dictionary in several places in basepage.py, so I expect similar problems in other cases. I guess that someone with a better understanding of the different uses of fun_list should finish the work before making the pull request.

**Comment by butlerpd** [comment]
Trac update at `2017/11/28 14:57:25`: **butler** commented:

Miguel to put comments in front of the three other places this is done so it can be checked easily by a reviewer and then make pull request.

**Comment by butlerpd** [comment]
Trac update at `2017/12/10 00:30:01`: 
* **butler** commented:

Miguel put the fix in all places and Paul and he tested generally -- not clear we know what the other places were linked to but they should work better than before at any rate.  Code was approved and merged by PK but without the close ticket notation, so closing the ticket now. 


* **butler** changed resolution from "" to "fixed"
* **butler** changed status from "new" to "closed"
