### ISSUE TITLE
plugin model scaling not working? (Trac #1008)

### ISSUE THREAD

**Issue by RichardHeenan** [SasView/sasview#1077]
In my local build of current (5th Oct, 2017) "master" of 4.1.2

I have a plugin version of the same model that I have in the normal place, if I for example fit only the scale and background the fitted values are WRONG for the plugin version.

Also for the plugin version the plot is not being updated unless I do "compute" after "fit".

(Yes I have renamed the .c and .py files for the plugin version of core_shell_bicelle_elliptical so there should not be a conflict of names.)

As I am trying to write a new plugin model to give to a user, this is rather worrying. Has anyone else seen similar?

Migrated from http://trac.sasview.org/ticket/1008
```json
{
    "status": "closed",
    "changetime": "2018-01-16T16:36:56",
    "_ts": "2018-01-16 16:36:56.401280+00:00",
    "description": "In my local build of current (5th Oct, 2017) \"master\" of 4.1.2\n\nI have a plugin version of the same model that I have in the normal place, if I for example fit only the scale and background the fitted values are WRONG for the plugin version.\n\nAlso for the plugin version the plot is not being updated unless I do \"compute\" after \"fit\".\n\n(Yes I have renamed the .c and .py files for the plugin version of core_shell_bicelle_elliptical so there should not be a conflict of names.)\n\nAs I am trying to write a new plugin model to give to a user, this is rather worrying. Has anyone else seen similar?",
    "reporter": "richardh",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2017-10-05T14:19:45",
    "component": "SasView",
    "summary": "plugin model scaling not working?",
    "priority": "blocker",
    "keywords": "",
    "milestone": "SasView 4.2.0",
    "owner": "richardh",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2017/10/05 14:24:40`: **butler** commented:

There seem to be some issues with the models interface in general (see #1075 and #1076) but have not heard of this one yet.  However regarding name space I think you also have to change the name string in the python file

```text
name = "new_name"
```

**Comment by RichardHeenan** [comment]
Trac update at `2017/10/05 14:27:32`: **richardh** commented:

Yes, I did that too.

**Comment by smk78** [comment]
Trac update at `2017/12/12 14:40:01`: **smk78** commented:

Possibly related? Steve Parnell was using 4.1.2 to fit a plugin and spotted some odd behaviour that I could replicate:


```text
I just created a mass fractal + dab plugin and tried fitting a couple of data sets from the test folder. It does seem to work, but the first time you click fit it updates the parameters but NOT the plot. To make the plot update that first time you need to click compute. Thereafter the plot moves with the fit button. This, I concede, would appear to be a bug.
```

**Comment by mdoucet** [comment]
Trac update at `2018/01/09 20:48:03`: **mathieu** commented:

I could not reproduce this. The only odd behavior I saw was that if I fit the same data set in two fitting tabs, only the plot from the last tab I created is updated. 

To test this, I copied the sphere.py model into my plug-in directory and fit a single data using both models (the original and the plug-in versions). I got the same results in both cases.

**Comment by RichardHeenan** [comment]
Trac update at `2018/01/16 16:36:56`: 
* **richardh** commented:

As with Mathieu last week, I cannot now reproduce the original bug, the plugin and built in models give the same fit results as expected.

Will close this ticket as no-one else has seen issues.


* **richardh** changed resolution from "" to "fixed"
* **richardh** changed status from "new" to "closed"
