### ISSUE TITLE
Add information in fit report about the polydispersity distribution used (Trac #1009)

### ISSUE THREAD

**Issue by gonzalezma** [SasView/sasview#1078]
When using polydispersity in the fit, the information about the type of distribution selected, and the number of points and sigmas should be given in the fit report.

Migrated from http://trac.sasview.org/ticket/1009
```json
{
    "status": "new",
    "changetime": "2018-10-02T23:40:38",
    "_ts": "2018-10-02 23:40:38.733945+00:00",
    "description": "When using polydispersity in the fit, the information about the type of distribution selected, and the number of points and sigmas should be given in the fit report.",
    "reporter": "gonzalezm",
    "cc": "",
    "resolution": "",
    "workpackage": "Reporting Enhancements",
    "time": "2017-10-10T08:15:50",
    "component": "SasView",
    "summary": "Add information in fit report about the polydispersity distribution used",
    "priority": "minor",
    "keywords": "",
    "milestone": "SasView 4.3.0",
    "owner": "gonzalezm",
    "type": "enhancement"
}
```

**Comment by butlerpd** [comment]
Trac update at `2017/10/27 17:19:15`: **butler** changed milestone from "SasView 4.2.0" to "SasView 4.3.0"

**Comment by pkienzle** [comment]
Trac update at `2018/09/28 21:38:02`: **pkienzle** commented:

sascomp formats polydisperse and magnetic parameters as follows (for cylinder):

  scale: 1
  background: 0
  sld: 6  M0:8.000  mtheta:0.0  mphi:0.0
  sld_solvent: 1
  radius: 20 +/- 4  (9 points in [-3,3] sigma gaussian)
  length: 300 +/- 60  (10 points in [-3,3] sigma gaussian)
  up:frac_i=0.0 up:frac_f=0.0 up:angle=0.0


The code for this is in `sasmodels/compare.py` in the `parlist()` and `_format_par()` functions.  This could be used with some mods from the sasview model wrapper.

**Comment by RichardHeenan** [comment]
Trac update at `2018/10/01 14:49:31`: **richardh** commented:

Hijacking this ticket slightly, but still relevant .... Why are the fit reports in the format below? Is this related, for convenience of the coding?, to what is in "save project"? Should we in 5.0 simply output screen shots of all the active tabs in the Fit Page? Else should we produce a table that is more easily pulled into a spreadsheet or word processor, as done for batch fits? Has anyone asked our users what they would really like?

File name:richard_test6.txt
Model name:ellipsoid@hardsphere
Q Range: min = 0.001, max = 1.0
Chi2/Npts:7.7548e+08
scale = 6.3816e+06 ± 0.0068054
background = 0 (fixed) cm-1
structure_factor_mode = 1 (fixed)
radius_effective_mode = 0 (fixed)
ellipsoid = (fixed)
sld = 4 (fixed) 10-6/Å2
sld_solvent = 1 (fixed) 10-6/Å2
radius_polar = 20 (fixed) Å
radius_equatorial = 10 (fixed) Å
hardsphere = (fixed)
radius_effective = 13.1353356684 (fixed) Å
volfraction = .3 (fixed)

**Comment by butlerpd** [comment]
Trac update at `2018/10/02 23:40:38`: **butler** commented:

Short answer is yes and no.  I don't believe the basic structure format has changed since the first implementation in the early days of !SansView when it was put together as quickly as possible to have *something*?  I believe that there has long been discussion that reports need a full rethink (in fact I believe there is an old ticket that says almost exactly that). The only issue has been bandwidth issues and that it has not been viewed as a priority over many of the other bit issues.  With 5.0 redoing the GUI completely the reporting has to be rewritten so seems like a good time to rethink to me?

Maybe the best thing would be to start by putting together a figure of how it should look and what information should be included?

**Comment by RichardHeenan** [comment]
Question for Richard: Do you think it is worthy to add also the number of points and sigmas? E.g.:
radius.width (gaussian, points=35, sigmas=3) = 0.1 +- 0.03.

yes please, if it is not too difficult (it all helps for users to be able to reproduce a fit later, or for others to spot a mistake ).
