### ISSUE TITLE
Finalise user mailing list move and close old mailing lists (Trac #1023)

### ISSUE THREAD

**Issue by ajj** [SasView/sasview#1090]
Followup from ticket #439

1) After end November 2017, set alias for user mailing list to point to users@sasview.org
2) Ensure copies of archives are downloaded
  a) De-obfuscate email addresses
  b) Find way to publish old archives (merge with new?)
3) Kill off Sourceforge lists

Migrated from http://trac.sasview.org/ticket/1023
```json
{
    "status": "closed",
    "changetime": "2019-03-26T14:46:19",
    "_ts": "2019-03-26 14:46:19.410926+00:00",
    "description": "Followup from ticket #304\n\n1) After end November 2017, set alias for user mailing list to point to users@sasview.org\n2) Ensure copies of archives are downloaded\n  a) De-obfuscate email addresses\n  b) Find way to publish old archives (merge with new?)\n3) Kill off Sourceforge lists",
    "reporter": "ajj",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "Support Infrastructure",
    "time": "2017-10-28T07:23:40",
    "component": "SasView",
    "summary": "Finalise user mailing list move and close old mailing lists",
    "priority": "critical",
    "keywords": "",
    "milestone": "Admin Tasks",
    "owner": "",
    "type": "enhancement"
}
```

**Comment by butlerpd** [comment]
Trac update at `2019/02/26 14:34:52`: 
* **butler** changed priority from "major" to "critical"
* **butler** changed workpackage from "SasView Admin" to "Support Infrastructure"

**Comment by ajj** [comment]
Trac update at `2019/03/26 14:46:19`: 
* **ajj** commented:

Copies of archives are downloaded and deployed on mailman server. Sourceforge lists deleted.


* **ajj** changed resolution from "" to "fixed"
* **ajj** changed status from "new" to "closed"
