### ISSUE TITLE
Deleting trac wiki pages fails (Trac #1026)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#1093]
Trying to figure out how to build tree structures I made some incorrect pages.  Trying to delete them throws an error page ... interestingly with the old theme back... and does not seem to delete the page.

Migrated from http://trac.sasview.org/ticket/1026
```json
{
    "status": "closed",
    "changetime": "2017-10-29T10:52:54",
    "_ts": "2017-10-29 10:52:54.785014+00:00",
    "description": "Trying to figure out how to build tree structures I made some incorrect pages.  Trying to delete them throws an error page ... interestingly with the old theme back... and does not seem to delete the page.",
    "reporter": "butler",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Admin",
    "time": "2017-10-29T10:22:36",
    "component": "SasView",
    "summary": "Deleting trac wiki pages fails",
    "priority": "major",
    "keywords": "",
    "milestone": "Admin Tasks",
    "owner": "ajj",
    "type": "defect"
}
```

**Comment by ajj** [comment]
Trac update at `2017/10/29 10:25:14`: 
* **ajj** changed _comment0 from "Seems to be the result of of a bug in SlackNotificationPlugin, which also seems to be an obsolete plugin and needs replacing with SlackIntegrationPlugin." to "1509273050646211"
* **ajj** commented:

Seems to be the result of of a bug in SlackNotificationPlugin (SlackIntegration)

https://github.com/wagnerpinheiro/trac-slack-plugin.git


* **ajj** changed description from "Trying to figure out how to build tree structures I made some incorrect pages.  Trying to delete them throws an error page ... interestingly with the old theme back... and does not seem to delete the page" to "Trying to figure out how to build tree structures I made some incorrect pages.  Trying to delete them throws an error page ... interestingly with the old theme back... and does not seem to delete the page."
* **ajj** changed owner from "" to "ajj"
* **ajj** changed status from "new" to "assigned"
* **ajj** changed summary from "Deleting incorrect track pages fails" to "Deleting trac wiki pages fails"

**Comment by ajj** [comment]
Trac update at `2017/10/29 10:52:54`: 
* **ajj** commented:

Used bug fix from PR that is open on the plugin github. Now works. 


* **ajj** changed resolution from "" to "fixed"
* **ajj** changed status from "assigned" to "closed"
