### ISSUE TITLE
clean up sesans examples in sasmodels (Trac #1038)

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#1105]
There are a number of sesans example datasets and fits in sasmodels.  These should be moved to a sesans subdirectory along with a README.rst indicating how to use them.

Most of the ses files do not load in the current version of sasview.
[https://github.com/SasView/sasview/pull/129 Sasview PR http://trac.sasview.org/ticket/129] fixes the infinite loop so they at least fail gracefully, but the files that don't load should be updated or removed. 

Migrated from http://trac.sasview.org/ticket/1038
```json
{
    "status": "closed",
    "changetime": "2018-03-27T09:17:57",
    "_ts": "2018-03-27 09:17:57.648462+00:00",
    "description": "There are a number of sesans example datasets and fits in sasmodels.  These should be moved to a sesans subdirectory along with a README.rst indicating how to use them.\n\nMost of the ses files do not load in the current version of sasview.\n[https://github.com/SasView/sasview/pull/129 Sasview PR #129] fixes the infinite loop so they at least fail gracefully, but the files that don't load should be updated or removed. ",
    "reporter": "pkienzle",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2017-11-29T14:14:08",
    "component": "SasView",
    "summary": "clean up sesans examples in sasmodels",
    "priority": "minor",
    "keywords": "",
    "milestone": "sasmodels 1.0",
    "owner": "awashington",
    "type": "defect"
}
```

**Comment by rprospero** [comment]
Trac update at `2018/03/12 14:19:14`: 
* **awashington** changed owner from "" to "awashington"
* **awashington** changed status from "new" to "assigned"

**Comment by rprospero** [comment]
Trac update at `2018/03/13 09:56:30`: **awashington** commented:

I've submitted a pull request (sasmodels 65) which updates the files to the standard format.

**Comment by rprospero** [comment]
Trac update at `2018/03/27 09:17:57`: 
* **awashington** commented:

Fixed in sasmodels pr number 65


* **awashington** changed resolution from "" to "fixed"
* **awashington** changed status from "assigned" to "closed"
