### ISSUE TITLE
Improve progress notification for slow calculations (Trac #1058)

### ISSUE THREAD

**Issue by RichardHeenan** [SasView/sasview#1114]
When doing long slow calculations, it is irritating to keep having to open the console to try to work out whether sasview has finished or not, or indeed whether I have really have clicked on "fit" or "compute".

There may be several things that could be done such as:

Grey out, change colour, or disable the "fit" and "compute" buttons after they are clicked.

Change the previous message at bottom left of screen to "calculating"

Preface the "Computation completed!" message at bottom left with time in "hh:mm:ss" 

Migrated from http://trac.sasview.org/ticket/1058
```json
{
    "status": "new",
    "changetime": "2018-02-13T02:03:09",
    "_ts": "2018-02-13 02:03:09.965604+00:00",
    "description": "When doing long slow calculations, it is irritating to keep having to open the console to try to work out whether sasview has finished or not, or indeed whether I have really have clicked on \"fit\" or \"compute\".\n\nThere may be several things that could be done such as:\n\nGrey out, change colour,\u00a0or disable the \"fit\" and \"compute\" buttons after they are clicked.\n\nChange the previous message at bottom left of screen\u00a0to\u00a0\"calculating\"\n\nPreface the \"Computation completed!\" message at bottom left with\u00a0time in \"hh:mm:ss\"\u00a0",
    "reporter": "richardh",
    "cc": "",
    "resolution": "",
    "workpackage": "SasView GUI Enhancements",
    "time": "2018-01-08T12:50:00",
    "component": "SasView",
    "summary": "Improve progress notification for slow calculations",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.3.0",
    "owner": "",
    "type": "enhancement"
}
```

**Comment by butlerpd** [comment]
Trac update at `2018/02/13 02:03:09`: 
* **butler** changed milestone from "SasView 4.2.0" to "SasView 4.3.0"
* **butler** changed priority from "trivial" to "major"

**Comment by butlerpd** [comment]
There is a bigger issue of having some progress bar/estimate being fed back to the user, much as DREAM does but for all optimizers.  However the simple fix seems to be implemented already with the Fit button turning to a red STOP button while fitting (going back to black Fit button when completed); though I'm not sure how robust that is? Maybe whoever implemented forgot to close the ticket?  I am going to close this now @RichardHeenan on the grounds that the more detailed progress estimates will be a lot of work that would probably best be spent on the 5.1 GUI version? I'm not moving this as I think a more appropriate issue should be submitted there for "better fit progress reporting" or some such.
