### ISSUE TITLE
minor isue with simultaneous / constrained fits (Trac #1061)

### ISSUE THREAD

**Issue by RichardHeenan** [SasView/sasview#1117]
Trying to break constrained simultaneous fit between 3 data sets (see attached project) with different models in current master for 4.2

Save project and load project worked fine, twice around, though each time the fit pages appeared in a different order the data and models still matched (hooray).

However, having hit "fit" from the constraints page, if I then hit "fit" on an individual fit page gets error message:

2018-01-15 13:04:33 : Traceback (most recent call last):
  File "C:\sasview42\sasview\src\sas\sasgui\perspectives\fitting\fit_thread.py", line 78, in compute
    result = map(map_apply, inputs)
  File "C:\sasview42\sasview\src\sas\sasgui\perspectives\fitting\fit_thread.py", line 14, in map_apply
    return apply(arguments![0], arguments[1:])
  File "C:\sasview42\sasview\src\sas\sasgui\perspectives\fitting\fit_thread.py", line 11, in map_getattr
    return  getattr(classInstance, classFunc)(*args)
  File "C:\sasview42\sasview\src\sas\sascalc\fit\!BumpsFitting.py", line 279, in fit
    result = run_bumps(problem, handler, curr_thread)
  File "C:\sasview42\sasview\src\sas\sascalc\fit\!BumpsFitting.py", line 379, in run_bumps
    'uncertainty': getattr(fitdriver.fitter, 'state', None),
!AttributeError: '!FitDriver' object has no attribute 'fitter'
 
 None 

Turning off and back on any parameters with red NaN in their error bar fields (ie the parameters that were constrained), then hit "stop", gets the "fit" button back to normal and you can then do a fit on a single data set.

Migrated from http://trac.sasview.org/ticket/1061
```json
{
    "status": "new",
    "changetime": "2018-02-13T02:15:37",
    "_ts": "2018-02-13 02:15:37.040974+00:00",
    "description": "Trying to break constrained simultaneous fit between 3 data sets (see attached project) with different models in current master for 4.2\n\nSave project and load project worked fine, twice around, though each time the fit pages appeared in a different order the data and models still matched (hooray).\n\nHowever, having hit \"fit\" from the constraints page, if I then hit \"fit\" on an individual fit page gets error message:\n\n2018-01-15 13:04:33 : Traceback (most recent call last):\n\u00a0 File \"C:\\sasview42\\sasview\\src\\sas\\sasgui\\perspectives\\fitting\\fit_thread.py\", line 78, in compute\n\u00a0\u00a0\u00a0 result = map(map_apply, inputs)\n\u00a0 File \"C:\\sasview42\\sasview\\src\\sas\\sasgui\\perspectives\\fitting\\fit_thread.py\", line 14, in map_apply\n\u00a0\u00a0\u00a0 return apply(arguments![0], arguments[1:])\n\u00a0 File \"C:\\sasview42\\sasview\\src\\sas\\sasgui\\perspectives\\fitting\\fit_thread.py\", line 11, in map_getattr\n\u00a0\u00a0\u00a0 return\u00a0 getattr(classInstance, classFunc)(*args)\n\u00a0 File \"C:\\sasview42\\sasview\\src\\sas\\sascalc\\fit\\!BumpsFitting.py\", line 279, in fit\n\u00a0\u00a0\u00a0 result = run_bumps(problem, handler, curr_thread)\n\u00a0 File \"C:\\sasview42\\sasview\\src\\sas\\sascalc\\fit\\!BumpsFitting.py\", line 379, in run_bumps\n\u00a0\u00a0\u00a0 'uncertainty': getattr(fitdriver.fitter, 'state', None),\n!AttributeError: '!FitDriver' object has no attribute 'fitter'\n\u00a0\n\u00a0None \n\nTurning off and back on any parameters with red NaN in their error bar fields (ie the parameters that were constrained), then hit \"stop\", gets the \"fit\" button back to normal and you can then do a fit on a single data set.",
    "reporter": "richardh",
    "cc": "",
    "resolution": "",
    "workpackage": "SasView Bug Fixing",
    "time": "2018-01-15T13:10:24",
    "component": "SasView",
    "summary": "minor isue with simultaneous / constrained fits",
    "priority": "minor",
    "keywords": "",
    "milestone": "SasView 4.3.0",
    "owner": "krzywon",
    "type": "defect"
}
```

**Comment by RichardHeenan** [comment]
Trac update at `2018/01/15 13:11:31`: 
* **richardh** changed attachment from "" to "sasview_proj_6constraints_15Jan18.svs"
* **richardh** commented:

Project with 3 data sets, 6 constraints, two different models

**Comment by RichardHeenan** [comment]
Trac update at `2018/02/01 10:34:47`: **richardh** commented:

I also had a look for further mention of parameter error values from constraints, but only found ticket #575 which mentions other obscure behaviour from the constraints. 

The underlying assumption in sasview is (alas) that all the base parameters in a constraint are adjusting, if they are then fixed it is not clear (I need to check this again now) that constraints are actively applied.

Looks like we need to find out why the parameter errors on constrained parameters turn into red NaN. Paul K has previously said that the red indicates sasview has seen a "problem". (Which indeed should be the case as the constrained parameter is neither fixed nor has any proper error information from the least squares or other fit method.)

In principle the error values can be calculated, from the errors on the base  parameters that are fitting, via some partial derivatives of the  constraint formula, which would have to be computed numerically.

Alternatively, and perhaps simpler for a quick fix for the error initially reported in this ticket, the red NaN in the errors column ought not to cause an upset if you hit "fit" on an individual fit page, as the values in that column should not actually matter to starting a fit.

**Comment by butlerpd** [comment]
Trac update at `2018/02/13 02:15:37`: **butler** changed milestone from "SasView 4.2.0" to "SasView 4.3.0"

**Comment by butlerpd** [comment]
This should be part of a more general constrained fitting refactoring. Perhaps @m2cci-NMZ might want to take a look?  In any event moving this to 5.1 for now and tagging as "constraints"

**Comment by m2cci-NMZ** [comment]
I think this was partially corrected in 5.x as when fitting individual fit pages constraints are removed. The errors on constrained parameters still read nan though, I'll check how this is handled by the fit engine and see if I can implement a calculation on the errors of constrained parameters. I was also thinking of adding a mechanism that allows the GUI to catch exceptions raised from the fit thread so the user gets some feedback when something has gone wrong with the fit engine.

**Comment by butlerpd** [comment]
Ok .. since you are the main person working in the constraints code at the moment feel free to close this @m2cci-NMZ if you think it is done or close and open more uptodate and targeted ones.
