### ISSUE TITLE
"Fitting did not converge!!!" error with a Sum|Multi plugin model (Trac #1064)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1119]
Reported by User alessandra.delgiudice@uniroma1.it:

Dear SASview developer,

I found problems making fits with Sum|Multi plugin models in the 4.1.2 version. In brief:

In the 4.1.2 version I got a "Fitting did not converge!!!" error, whereas trying with the 4.1 version (installed on the same pc in a different folder) the fit worked.

I did a test with simulated data:

I created a Sum|Multi model with the dedicated tool: sphere_plus_hollowcylinder.py

I saved a calculated curve with parameters:
p1_scale 0.5
p1_background 0
p1_sld 9.45
p1_sld_solvent 9.4
p1_radius 100
p2_scale 0.5
p2_background 0
p2_radius 50
p2_thickness 20
p2_length 1000
p2_sld 9.45
p2_sld_solvent 9.4
scale_factor 1

and 1400 points as sphere_and_hollow_cylinder_out.txt

I loaded this file as a data file to be fitted. I changed the sphere radius value from 100 to 50, and then clicked to "Fit". Nothing happened and I got a "Fitting did not converge!!!" error in the console.

I had an older installation file for SASview 4.1 and I installed it on my laptop in the folder SasView_4_1 instead of !SasView (where the 4.1.2 version is)

The same test worked in this case.

When trying a similar test with a simpler model (sphere with default parameters), the fit starting from a different value of the sphere radius (100 instead of 50) worked with the 4.1.2 version.

I attach the sasview log as sasview_20180112.log. What I described starts with the line "2018-01-12 11:50:05,181 INFO  --- !SasView session started ---"

Migrated from http://trac.sasview.org/ticket/1064
```json
{
    "status": "closed",
    "changetime": "2018-02-13T10:52:08",
    "_ts": "2018-02-13 10:52:08.370158+00:00",
    "description": "Reported by User alessandra.delgiudice@uniroma1.it:\n\nDear SASview developer,\n\nI found problems making fits with Sum|Multi plugin models in the 4.1.2 version. In brief:\n\nIn the 4.1.2 version I got a \"Fitting did not converge!!!\" error, whereas trying with the 4.1 version (installed on the same pc in a different folder) the fit worked.\n\nI did a test with simulated data:\n\nI created a Sum|Multi model with the dedicated tool: sphere_plus_hollowcylinder.py\n\nI saved a calculated curve with parameters:\np1_scale 0.5\np1_background 0\np1_sld 9.45\np1_sld_solvent 9.4\np1_radius 100\np2_scale 0.5\np2_background 0\np2_radius 50\np2_thickness 20\np2_length 1000\np2_sld 9.45\np2_sld_solvent 9.4\nscale_factor 1\n\nand 1400 points as sphere_and_hollow_cylinder_out.txt\n\nI loaded this file as a data file to be fitted. I changed the sphere radius value from 100 to 50, and then clicked to \"Fit\". Nothing happened and I got a \"Fitting did not converge!!!\" error in the console.\n\nI had an older installation file for SASview 4.1 and I installed it on my laptop in the folder SasView_4_1 instead of !SasView (where the 4.1.2 version is)\n\nThe same test worked in this case.\n\nWhen trying a similar test with a simpler model (sphere with default parameters), the fit starting from a different value of the sphere radius (100 instead of 50) worked with the 4.1.2 version.\n\nI attach the sasview log as sasview_20180112.log. What I described starts with the line \"2018-01-12 11:50:05,181 INFO  --- !SasView session started ---\"\n",
    "reporter": "smk78",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2018-01-24T09:46:08",
    "component": "SasView",
    "summary": "\"Fitting did not converge!!!\" error with a Sum|Multi plugin model",
    "priority": "critical",
    "keywords": "",
    "milestone": "SasView 4.2.0",
    "owner": "",
    "type": "defect"
}
```

**Comment by smk78** [comment]
Trac update at `2018/01/24 09:46:33`: 
* **smk78** changed attachment from "" to "sasview_20180112.log"
* **smk78** commented:

Alessandras log file

**Comment by smk78** [comment]
Trac update at `2018/01/24 09:48:40`: **smk78** commented:

Alessandras PC was Windows 10 Home on a Dell XPS 9360 with processor Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz, 2901 Mhz, 2 cores, 4 processors.

I am also using a W10 PC and managed to reproduce this behaviour.

**Comment by smk78** [comment]
Trac update at `2018/01/24 09:49:27`: **smk78** commented:

Wojtek has now reproduced this behaviour on a Mac using 4.1.2

**Comment by butlerpd** [comment]
Trac update at `2018/02/04 18:10:25`: **butler** commented:

What is the status of this ticket?  Does the problem still exist in 4.2 (i.e. master build?) or can we close this as fixed in 4.2?

**Comment by smk78** [comment]
Trac update at `2018/02/13 10:47:23`: 
* **smk78** changed attachment from "" to "ticket1064fixed.png"
* **smk78** commented:

Screenshot of SasView Master pulled 13/02/2018 10:30GMT

**Comment by smk78** [comment]
Trac update at `2018/02/13 10:51:27`: **smk78** commented:

Have just pulled from master, built locally (32 bit, tinycc=no64) on Win 7, and re-tried Alessandra's instructions. !SasView fitted the model data it had just created. Screen shot attached. The problem seems to be fixed.

**Comment by smk78** [comment]
Trac update at `2018/02/13 10:52:08`: 
* **smk78** changed resolution from "" to "fixed"
* **smk78** changed status from "new" to "closed"
