### ISSUE TITLE
2d data (from NG7) not loadiing - strange format? (Trac #1068)

### ISSUE THREAD

**Issue by RichardHeenan** [SasView/sasview#1123]
User Yuyin Xi reports issue with attached 2d data file.

it is 2d data (from NG7), but not in any of the formats that I could find in our test folder, so over to the NIST guys to work out whether this is an omission or perhaps not fully reduced data? Sasview “successfully” reads it as 1d data, but then throws an error on sending it to fit.

 

Migrated from http://trac.sasview.org/ticket/1068
```json
{
    "status": "closed",
    "changetime": "2018-04-10T12:01:17",
    "_ts": "2018-04-10 12:01:17.354991+00:00",
    "description": "User Yuyin Xi reports issue with attached 2d data file.\n\nit is 2d data (from NG7), but not in any of the formats that I could find in our test folder, so over to the NIST guys to work out whether this is an omission or perhaps not fully reduced data? Sasview \u201csuccessfully\u201d reads it as 1d data, but then throws an error on sending it to fit.\n\n\u00a0",
    "reporter": "richardh",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2018-02-01T13:43:08",
    "component": "SasView",
    "summary": "2d data (from NG7) not loadiing - strange format?",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.2.0",
    "owner": "krzywon",
    "type": "defect"
}
```

**Comment by RichardHeenan** [comment]
Trac update at `2018/02/01 13:44:01`: **richardh** changed attachment from "" to "TQT P3HT 200V Pulse Static_13m_Perp_2D.ASC"

**Comment by butlerpd** [comment]
Trac update at `2018/04/02 22:34:39`: **butler** changed priority from "minor" to "major"
