### ISSUE TITLE
GUI problem when using polydispersity/orientation distributions (Trac #1069)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#1124]
After Choosing a model and clicking yes on polydispersity, choosing a new distribution function pops up a floating input box in the parameter list. playing around with different options can lead to a number of such orphan looking boxes in the GUI. 

If one then clicks on a different resolution option, forcing a redraw of the panel, those boxes appear to be the +/- error box which should appear when fitting that distribution.  However this happens even without data (so no fit).  Clearly that whole logic is broken.

Another issue is the fact that the reported uncertainty is given in an editable box rather than an uneditable box but that is a separate ticket.

Migrated from http://trac.sasview.org/ticket/1069
```json
{
    "status": "closed",
    "changetime": "2018-06-26T02:42:43",
    "_ts": "2018-06-26 02:42:43.792553+00:00",
    "description": "After Choosing a model and clicking yes on polydispersity, choosing a new distribution function pops up a floating input box in the parameter list. playing around with different options can lead to a number of such orphan looking boxes in the GUI. \n\nIf one then clicks on a different resolution option, forcing a redraw of the panel, those boxes appear to be the +/- error box which should appear when fitting that distribution.  However this happens even without data (so no fit).  Clearly that whole logic is broken.\n\nAnother issue is the fact that the reported uncertainty is given in an editable box rather than an uneditable box but that is a separate ticket.",
    "reporter": "butler",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2018-02-05T02:47:40",
    "component": "SasView",
    "summary": "GUI problem when using polydispersity/orientation distributions",
    "priority": "critical",
    "keywords": "",
    "milestone": "SasView 4.2.0",
    "owner": "butler",
    "type": "defect"
}
```

**Comment by RichardHeenan** [comment]
Trac update at `2018/02/05 17:41:29`: **richardh** commented:

Just built from master on Win7. The gui for polydispersity is mostly working fine for me, with error boxes appearing in the correct place. However I did once get the error box still there, with a value in it, after turning off the fitting on that parameter and running a fit, but I have not yet reproduced this.

**Comment by butlerpd** [comment]
Trac update at `2018/02/13 14:49:56`: 
* **butler** changed owner from "" to "butler"
* **butler** changed status from "new" to "assigned"
