### ISSUE TITLE
Parameter error boxes should not be editable (Trac #1070)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#1125]
When a fit is executed, all fit parameters return not only their value but an uncertainty which is reported in a newly created text entry box.  As these are reported values they should not be editable.

Migrated from http://trac.sasview.org/ticket/1070
```json
{
    "status": "closed",
    "changetime": "2018-06-26T02:45:41",
    "_ts": "2018-06-26 02:45:41.753157+00:00",
    "description": "When a fit is executed, all fit parameters return not only their value but an uncertainty which is reported in a newly created text entry box.  As these are reported values they should not be editable.",
    "reporter": "butler",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2018-02-05T03:29:50",
    "component": "SasView",
    "summary": "Parameter error boxes should not be editable",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.2.0",
    "owner": "butler",
    "type": "defect"
}
```

**Comment by RichardHeenan** [comment]
Trac update at `2018/02/05 17:43:20`: **richardh** commented:

I agree, I think the parameter error values in editable boxes appeared some while ago, likely after fixing an earlier issue.

**Comment by butlerpd** [comment]
Trac update at `2018/02/13 03:04:47`: 
* **butler** changed owner from "" to "butler"
* **butler** changed status from "new" to "accepted"

**Comment by butlerpd** [comment]
Trac update at `2018/02/13 14:47:08`: 
* **butler** changed milestone from "SasView 4.2.0" to "SasView 4.3.0"
* **butler** changed priority from "critical" to "major"

**Comment by butlerpd** [comment]
Trac update at `2018/06/26 02:45:41`: 
* **butler** commented:

This was also fixed in !SasView pull request 156 so can close it now (should have done so on merging the branch but forgot there was another associated ticket)


* **butler** changed milestone from "SasView 4.3.0" to "SasView 4.2.0"
* **butler** changed resolution from "" to "fixed"
* **butler** changed status from "accepted" to "closed"
