### ISSUE TITLE
Remove save button in report dialog on Mac (Trac #1079)

### ISSUE THREAD

**Issue by ajj** [SasView/sasview#1131]
The Mac produces blank reports when save is used. This problem will go away when 5.0 comes out.

The interim solution is to remove the save button and have users press "Print" and then use "Save as PDF" from the Mac print dialog.

Migrated from http://trac.sasview.org/ticket/1079
```json
{
    "status": "closed",
    "changetime": "2018-04-17T13:29:28",
    "_ts": "2018-04-17 13:29:28.262252+00:00",
    "description": "The Mac produces blank reports when save is used. This problem will go away when 5.0 comes out.\n\nThe interim solution is to remove the save button and have users press \"Print\" and then use \"Save as PDF\" from the Mac print dialog.",
    "reporter": "ajj",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2018-03-06T14:31:44",
    "component": "SasView",
    "summary": "Remove save button in report dialog on Mac",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.2.0",
    "owner": "wojciech",
    "type": "defect"
}
```

**Comment by wpotrzebowski** [comment]
Trac update at `2018/03/19 13:02:49`: **wojciech** commented:

Unfortunately this may not solve a problem. Figures are not printed to pdf file (only red crosses are visible). I've tested it on local build and from installer. We will probably need to tackle PIL issuses

**Comment by ajj** [comment]
Trac update at `2018/03/20 14:31:32`: 
* **ajj** changed owner from "" to "wojciech"
* **ajj** changed status from "new" to "assigned"
