### ISSUE TITLE
GUI problem with new orientation distribution (Trac #1081)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#1132]
when changing the angles when using distribution of orientation one can pretty quickly get to a point where one or more of the angle entry boxes no longer update internally leading to some confusing (and wrong) results.  May be related to 1004 and 1069 GUI problems.

Migrated from http://trac.sasview.org/ticket/1081
```json
{
    "status": "closed",
    "changetime": "2018-04-30T20:00:16",
    "_ts": "2018-04-30 20:00:16.447202+00:00",
    "description": "when changing the angles when using distribution of orientation one can pretty quickly get to a point where one or more of the angle entry boxes no longer update internally leading to some confusing (and wrong) results.  May be related to 1004 and 1069 GUI problems.",
    "reporter": "butler",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2018-03-20T14:34:22",
    "component": "SasView",
    "summary": "GUI problem with new orientation distribution",
    "priority": "blocker",
    "keywords": "",
    "milestone": "SasView 4.2.0",
    "owner": "",
    "type": "defect"
}
```

**Comment by pkienzle** [comment]
Trac update at `2018/04/17 13:29:42`: **pkienzle** commented:

Seems to be related to uniform distribution.  Once uniform is selected as the distribution for phi then changes to the phi angle no longer work, and phi is stuck at the value present when uniform was first selected.  Maybe because of the NaN for Nsigs?

**Comment by pkienzle** [comment]
Trac update at `2018/04/30 20:00:16`: 
* **pkienzle** changed resolution from "" to "fixed"
* **pkienzle** changed status from "new" to "closed"
