### ISSUE TITLE
fit page is missing from SASentry for simultaneous fits to the same file (Trac #1090)

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#1141]
The current .svs file format does not have enough information to determine which model (M1, M2, etc) is associated with which SASentry when interpreting constraints in a simultaneous fit.  Currently the filename is used, but that fails when using different models on different parts of the same file.  Saving the fit page id with the SASentry will be enough to resolve the ambiguity.

Migrated from http://trac.sasview.org/ticket/1090
```json
{
    "status": "new",
    "changetime": "2018-06-15T13:44:55",
    "_ts": "2018-06-15 13:44:55.076834+00:00",
    "description": "The current .svs file format does not have enough information to determine which model (M1, M2, etc) is associated with which SASentry when interpreting constraints in a simultaneous fit.  Currently the filename is used, but that fails when using different models on different parts of the same file.  Saving the fit page id with the SASentry will be enough to resolve the ambiguity.",
    "reporter": "pkienzle",
    "cc": "",
    "resolution": "",
    "workpackage": "SasView Bug Fixing",
    "time": "2018-04-12T19:35:27",
    "component": "SasView",
    "summary": "fit page is missing from SASentry for simultaneous fits to the same file",
    "priority": "minor",
    "keywords": "",
    "milestone": "SasView 4.3.0",
    "owner": "",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2018/06/15 13:44:55`: 
* **butler** commented:

This is not going to make it for release 4.2 so moving to 4.3.


* **butler** changed milestone from "SasView 4.2.0" to "SasView 4.3.0"

**Comment by butlerpd** [comment]
This seems to be clearly a 5.x issue now so moving to 5.1

**Comment by gonzalezma** [comment]
After recent work on constraints, I think this can be closed now.
