### ISSUE TITLE
Problem with plugin models on mac when using ER (Trac #1103)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#1151]
someone from the ESRF is trying to write a new model (in attachment, even
if it is not finished) and we are seeing some strange behaviour,
which becomes blocking in his Mac.

When the function ER in the python file is commented and one loads the
model, the first time the model appears in the list named as nanotube_TZ
(the file name) while the second one is named bilayer_tube (the name used
in the python variable).

If the ER function is uncommented, then the model is loaded as nanotube_TZ
and the P(Q)*S(Q) button appears, but the button to choose the structure
factor is inactive. Reloading once, then the model is named bilayer_tube
and one can use S(Q) normally.

The main issue is than in his Mac, without ER things work as for me, but
when he tries to use ER, the model does not appear at all in the list of
plugin models. And there are no error messages indicating what could be wrong.

Migrated from http://trac.sasview.org/ticket/1103
```json
{
    "status": "closed",
    "changetime": "2018-07-10T09:46:00",
    "_ts": "2018-07-10 09:46:00.669624+00:00",
    "description": "someone from the ESRF is trying to write a new model (in attachment, even\nif it is not finished) and we are seeing some strange behaviour,\nwhich becomes blocking in his Mac.\n\nWhen the function ER in the python file is commented and one loads the\nmodel, the first time the model appears in the list named as nanotube_TZ\n(the file name) while the second one is named bilayer_tube (the name used\nin the python variable).\n\nIf the ER function is uncommented, then the model is loaded as nanotube_TZ\nand the P(Q)*S(Q) button appears, but the button to choose the structure\nfactor is inactive. Reloading once, then the model is named bilayer_tube\nand one can use S(Q) normally.\n\nThe main issue is than in his Mac, without ER things work as for me, but\nwhen he tries to use ER, the model does not appear at all in the list of\nplugin models. And there are no error messages indicating what could be wrong.",
    "reporter": "butler",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2018-05-15T01:49:19",
    "component": "SasView",
    "summary": "Problem with plugin models on mac when using ER",
    "priority": "critical",
    "keywords": "",
    "milestone": "SasView 4.2.0",
    "owner": "",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2018/05/28 15:16:50`: **butler** commented:

Miguel to follow up on this issue.  As the only report so far, we may need to downgrade and punt to next release?

**Comment by gonzalezma** [comment]
Trac update at `2018/07/10 09:46:00`: 
* **gonzalezm** commented:

Tried again on a Mac using SasView 4.2 (beta) and plugin appeared fine, including the S(Q) option.


* **gonzalezm** changed resolution from "" to "fixed"
* **gonzalezm** changed status from "new" to "closed"
