### ISSUE TITLE
qt5 gui - model parameter table not displaying well in Windows (Trac #1114)

### ISSUE THREAD

**Issue by RichardHeenan** [SasView/sasview#1159]
In our Windows installs or builds, it is slightly irritating that the font and/or character sizes in the model parameter tables etc do not line up and can have parts of the characters chopped off. Would be good to fix this before we do lots of development work in the beta approx project.

Migrated from http://trac.sasview.org/ticket/1114
```json
{
    "status": "closed",
    "changetime": "2018-09-09T07:41:34",
    "_ts": "2018-09-09 07:41:34.038277+00:00",
    "description": "In our Windows installs or builds, it is slightly irritating that the font and/or character sizes in the model parameter tables etc do not line up and can have parts of the characters chopped off. Would be good to fix this before we do lots of development work in the beta approx project.",
    "reporter": "richardh",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "Beta Approximation Project",
    "time": "2018-07-01T20:17:32",
    "component": "SasView",
    "summary": "qt5 gui - model parameter table not displaying well in Windows",
    "priority": "trivial",
    "keywords": "",
    "milestone": "SasView Next Release +1",
    "owner": "tcbennun",
    "type": "defect"
}
```

**Comment by RichardHeenan** [comment]
Trac update at `2018/07/05 09:50:49`: 
* **richardh** changed attachment from "" to "qt_win7_a.jpg"
* **richardh** commented:

qt5 Win7 param table

**Comment by RichardHeenan** [comment]
Trac update at `2018/07/05 09:51:17`: 
* **richardh** changed attachment from "" to "qt_win7_b.jpg"
* **richardh** commented:

qt5 win7 polydisp table

**Comment by RichardHeenan** [comment]
Trac update at `2018/07/05 10:33:50`: **richardh** commented:

Win7 screen shot from my desk top in office attached, text shifted and chopped off at bottom edge.

My Win10 at home is like yours, small misalignment.

Perhaps need to look at whether changing default font size etc in windows affects this.

**Comment by RichardHeenan** [comment]
Trac update at `2018/07/05 10:45:45`: **richardh** commented:

In "display" options I changed from default "smaller" 100% text to "medium" 125%, the qt5 parameter table then had larger text, still misaligned but no longer chopped off at bottom.

**Comment by rozyczko** [comment]
Trac update at `2018/07/20 08:18:54`: **piotr** commented:

Also tracked in JIRA: https://jira.esss.lu.se/browse/SASVIEW-889
