### ISSUE TITLE
external calls to sasmodels needing beta(Q) (Trac #1119)

### ISSUE THREAD

**Issue by RichardHeenan** [SasView/sasview#1163]
Do we need to consider how other codes will be able to call sasmodels in such as way as to get beta(Q) and other options in the calculation of I(Q)?

Migrated from http://trac.sasview.org/ticket/1119
```json
{
    "status": "closed",
    "changetime": "2018-10-30T22:09:29",
    "_ts": "2018-10-30 22:09:29.035043+00:00",
    "description": "Do we need to consider how other codes will be able to call sasmodels in such as way as to get beta(Q) and other options in the calculation of I(Q)?",
    "reporter": "richardh",
    "cc": "",
    "resolution": "duplicate",
    "workpackage": "Beta Approximation Project",
    "time": "2018-07-01T21:32:04",
    "component": "SasView",
    "summary": "external calls to sasmodels needing beta(Q)",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 5.0.0",
    "owner": "richardh",
    "type": "enhancement"
}
```

**Comment by butlerpd** [comment]
Trac update at `2018/09/09 07:56:15`: **butler** changed _comment0 from:

> External code can use several methods to run sasmodels, but in the beta_approx branch, the SasviewModel class has an API change in place allowing access to intermediate results from the P(Q)S(Q) calculation.
> 
> SasviewModel.calculate_Iq now returns both I(Q) and a callable; the callable is used to generate a dict of intermediate results. beta(Q) is one of those results, if beta approximation is turned on. If the model in question is not a product model, the callable returns an empty dict.
> 
> This is a breaking change for any existing calls to calculate_Iq, so if/when this is introduced into master, it must be under a new major version number (I recommend).

to:

> 1536480138178319

**Comment by butlerpd** [comment]
Trac update at `2018/09/09 08:02:47`: **butler** changed milestone from "sasmodels Next Release +1" to "SasView 5.0.0"

**Comment by pkienzle** [comment]
Trac update at `2018/10/30 22:09:29`: 
* **pkienzle** commented:


For scripts that use the sasview model wrapper (if any), the first release of beta approximation will be in sasmodels 1.0, so it will be in a new major revision.

Closing this as dup of http://trac.sasview.org/ticket/491.


* **pkienzle** changed resolution from "" to "duplicate"
* **pkienzle** changed status from "new" to "closed"
