### ISSUE TITLE
General documentation for beta(Q) modification of S(Q) (Trac #1122)

### ISSUE THREAD

**Issue by RichardHeenan** [SasView/sasview#1164]
Write some general sasview documentation for the beta(Q) modification of S(Q), and new options for S(Q).

Link to "help" buttons in the qt5 gui.

Migrated from http://trac.sasview.org/ticket/1122
```json
{
    "status": "new",
    "changetime": "2019-03-29T17:30:32",
    "_ts": "2019-03-29 17:30:32.194115+00:00",
    "description": "Write some general sasview documentation for the beta(Q) modification of S(Q), and new options for S(Q).\n\nLink to \"help\" buttons in the qt5 gui.",
    "reporter": "richardh",
    "cc": "",
    "resolution": "",
    "workpackage": "Beta Approximation Project",
    "time": "2018-07-01T21:42:03",
    "component": "SasView",
    "summary": "General documentation for beta(Q) modification of S(Q)",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView Next Release +1",
    "owner": "richardh",
    "type": "enhancement"
}
```

**Comment by smk78** [comment]
Trac update at `2019/03/29 17:30:32`: **smk78** commented:

I have started a new help page /sasview/src/sas/sasgui/perspectives/fitting/media/fitting_sq.rst

Eventually it could be subsumed in to fitting_help.rst, I suppose, but whilst we develop it this seemed the cleaner option.

**Comment by smk78** [comment]
Help page is now located at /sasmodels/doc/guide/fitting_sq.rst
