### ISSUE TITLE
File Loader is not loading valid NXcanSAS (Trac #1127)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1168]
Jan !Ilvasky/Pete Jemian have noted several issues with how !SasView handles NXcanSAS:

i) !SasView ''expects'' NXcanSAS to have the .h5 extension, however such enforcement actually breaks the !NeXus standard which doesn't specify an extension (Tim Snow notes that .h5, .nxs, .nexus, .hdf, even .nx.hdf are in use!);

ii) the .h5 example files in the !SasView /test folder are actually incompatible with the NXcanSAS standard, they use the attributes “uncertainty” and “I_uncertainty" instead of the plural “uncertainties”.

Separately, Brian Pauw would like !SasView to start loading NXcanSAS containing @Mask_indicies

Migrated from http://trac.sasview.org/ticket/1127
```json
{
    "status": "closed",
    "changetime": "2018-11-13T23:55:35",
    "_ts": "2018-11-13 23:55:35.748397+00:00",
    "description": "Jan !Ilvasky/Pete Jemian have noted several issues with how !SasView handles NXcanSAS:\n\ni) !SasView ''expects'' NXcanSAS to have the .h5 extension, however such enforcement actually breaks the !NeXus standard which doesn't specify an extension (Tim Snow notes that .h5, .nxs, .nexus, .hdf, even .nx.hdf are in use!);\n\nii) the .h5 example files in the !SasView /test folder are actually incompatible with the NXcanSAS standard, they use the attributes \u201cuncertainty\u201d and \u201cI_uncertainty\" instead of the plural \u201cuncertainties\u201d.\n\nSeparately, Brian Pauw would like !SasView to start loading NXcanSAS containing @Mask_indicies\n\n",
    "reporter": "smk78",
    "cc": "",
    "resolution": "duplicate",
    "workpackage": "SasView Bug Fixing",
    "time": "2018-07-04T15:53:08",
    "component": "SasView",
    "summary": "File Loader is not loading valid NXcanSAS",
    "priority": "critical",
    "keywords": "",
    "milestone": "SasView 4.2.1",
    "owner": "",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2018/07/04 18:19:31`: **butler** commented:

Actually this looks like a slight extension to #1049? Can we move this info there and close this duplicate ticket? Or bring the other info and close the old as duplicate?

The bottom line is we know that we are in fact not fully compliant with the NXcanSAS standard and need to fix that.... but we cannot necessarily use all the things that a specific NXcanSAS file gives us. What the reader should do is accept any NXcanSAS standard compliant file that contains the information needed by !SasView.  This means:
* Check for an NXcanSAS format beyond its extension (as required by the spec)
* Read all the !SasView relevant information as long as it is provided in a way that conforms to the standard -- meaning we must look at the attribute tags first
* In the absence of an attribute tag we should look for common names we expect (but this is an extra so don't need to guess everybody's naming)
* accept any file we can extract the appropriate information from even if it contains a lot of extra guff we don't understand (said guf being discarded by !SasView)

**Comment by smk78** [comment]
Trac update at `2018/07/05 09:41:14`: 
* **smk78** commented:

Ahh. My bad. I searched on NXcanSAS to check for other tickets but #1049 is titled CanSAS HDF!

Ok. Closing this ticket and updating #1049.


* **smk78** changed resolution from "" to "duplicate"
* **smk78** changed status from "new" to "closed"

**Comment by butlerpd** [comment]
Trac update at `2018/11/13 23:55:35`: 
* **butler** commented:

This is tied to ticket #1049 so should be listed under 4.2.1 - now moving


* **butler** changed milestone from "SasView 4.3.0" to "SasView 4.2.1"
