### ISSUE TITLE
Slit Size Calculator Tool not working (Trac #1132)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1173]
Testing 4.2beta on W10:

Trying to load \test\1d\beam_profile.dat into the Slit Size Calculator does nothing…

Migrated from http://trac.sasview.org/ticket/1132
```json
{
    "status": "closed",
    "changetime": "2018-08-13T20:47:24",
    "_ts": "2018-08-13 20:47:24.883244+00:00",
    "description": "Testing 4.2beta on W10:\n\nTrying to load \\test\\1d\\beam_profile.dat into the Slit Size Calculator does nothing\u2026",
    "reporter": "smk78",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2018-07-16T16:24:01",
    "component": "SasView",
    "summary": "Slit Size Calculator Tool not working",
    "priority": "blocker",
    "keywords": "",
    "milestone": "SasView 4.2.0",
    "owner": "krzywon",
    "type": "defect"
}
```

**Comment by RichardHeenan** [comment]
Trac update at `2018/08/06 15:39:30`: **richardh** commented:

Replying to [ticket:1132 smk78]:

Same failure to load (?) on my Win7 version

> Testing 4.2beta on W10:
> 
> Trying to load \test\1d\beam_profile.dat into the Slit Size Calculator does nothing…

**Comment by butlerpd** [comment]
Trac update at `2018/08/07 14:03:04`: 
* **butler** changed owner from "" to "krzywon"
* **butler** changed status from "new" to "assigned"
