### ISSUE TITLE
Reference in Acknowledging SasView box will need updating for release (Trac #1133)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1174]
In the Acknowledging !SasView box the reference currently reads:

M. Doucet et al. !SasView Version 4.1.2, Zenodo, 10.5281/zenodo.825675

Will need updating when 4.2 is released.

Migrated from http://trac.sasview.org/ticket/1133
```json
{
    "status": "closed",
    "changetime": "2018-09-09T10:19:34",
    "_ts": "2018-09-09 10:19:34.641942+00:00",
    "description": "In the Acknowledging !SasView box the reference currently reads:\n\nM. Doucet et al. !SasView Version 4.1.2, Zenodo, 10.5281/zenodo.825675\n\nWill need updating when 4.2 is released.",
    "reporter": "smk78",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2018-07-16T16:34:12",
    "component": "SasView",
    "summary": "Reference in Acknowledging SasView box will need updating for release",
    "priority": "blocker",
    "keywords": "",
    "milestone": "SasView 4.2.0",
    "owner": "ajj",
    "type": "task"
}
```

**Comment by butlerpd** [comment]
Trac update at `2018/08/07 14:07:40`: 
* **butler** changed owner from "" to "butler"
* **butler** changed status from "new" to "assigned"

**Comment by butlerpd** [comment]
Trac update at `2018/08/07 14:08:02`: **butler** changed owner from "butler" to "ajj"

**Comment by ajj** [comment]
Trac update at `2018/09/09 10:19:34`: 
* **ajj** changed resolution from "" to "fixed"
* **ajj** changed status from "assigned" to "closed"
