### ISSUE TITLE
QT5 GUI - rename FitPage0 to Fitpage1 or rename M1 to M0 (Trac #1136)

### ISSUE THREAD

**Issue by RichardHeenan** [SasView/sasview#1177]
The first !FitPage in the QT gui is FitPage0 but has models M1 and parameters M1.radius etc. This will make constraints very confusing!

Suggest rename one or the other, preferably to my mind start at FitPage1 for backwards compatibility with earlier versions.

(putting this in beta approx project for now, though is not really part of this)

Migrated from http://trac.sasview.org/ticket/1136
```json
{
    "status": "closed",
    "changetime": "2018-08-21T11:15:08",
    "_ts": "2018-08-21 11:15:08.987585+00:00",
    "description": "The first !FitPage in the QT gui is FitPage0 but has models M1 and parameters M1.radius etc. This will make constraints very confusing!\n\nSuggest rename one or the other, preferably to my mind start at FitPage1 for backwards compatibility with earlier versions.\n\n(putting this in beta approx project for now, though is not really part of this)",
    "reporter": "richardh",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "Beta Approximation Project",
    "time": "2018-07-18T16:37:42",
    "component": "SasView",
    "summary": "QT5 GUI - rename FitPage0 to Fitpage1 or rename M1 to M0",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 5.0.0",
    "owner": "richardh",
    "type": "defect"
}
```

**Comment by rozyczko** [comment]
Trac update at `2018/07/20 08:13:46`: 
* **piotr** changed _comment0 from "FittingPerspectiveTest.py will also need to modified" to "1532074491883495"
* **piotr** commented:


`FittingPerspectiveTest.py`  will also need to modified

**Comment by RichardHeenan** [comment]
Trac update at `2018/08/21 11:15:08`: 
* **richardh** commented:

Has been done, so closing this ticket.


* **richardh** changed resolution from "" to "fixed"
* **richardh** changed status from "new" to "closed"
