### ISSUE TITLE
Need to add Release notes for 4.2 (Trac #1146)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#1187]
In particular add what's new as well as Known issues.  As discussed when moving tickets #1137 and #1154 to 4.3 those two issues should be documented under known issues.  A quick check of 4.3 tickets might be helpful to add to known issues?

Migrated from http://trac.sasview.org/ticket/1146
```json
{
    "status": "closed",
    "changetime": "2018-10-04T10:52:58",
    "_ts": "2018-10-04 10:52:58.418256+00:00",
    "description": "In particular add what's new as well as Known issues.  As discussed when moving tickets #1086 and #1109 to 4.3 those two issues should be documented under known issues.  A quick check of 4.3 tickets might be helpful to add to known issues?",
    "reporter": "butler",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2018-07-24T14:15:10",
    "component": "SasView",
    "summary": "Need to add Release notes for 4.2",
    "priority": "blocker",
    "keywords": "",
    "milestone": "SasView 4.2.0",
    "owner": "butler",
    "type": "task"
}
```

**Comment by butlerpd** [comment]
Trac update at `2018/08/07 14:07:10`: 
* **butler** changed owner from "" to "smk78"
* **butler** changed status from "new" to "assigned"

**Comment by smk78** [comment]
Trac update at `2018/08/10 11:39:33`: **smk78** commented:

Mostly complete release notes document sent to @butler to finalise.

Will leave this ticket as a blocker for now so no one forgets to upload them! :-)

**Comment by smk78** [comment]
Trac update at `2018/08/10 13:33:47`: **smk78** commented:

Have updated \sasview\installers\README-next-release.txt with notes for 4.2.0.

**Comment by smk78** [comment]
Trac update at `2018/08/10 13:36:56`: **smk78** commented:

To do:

1. In \sasview\installers\ rename README.txt to README-old-release.txt and README-next-release.txt to README.txt.

2. Go to https://github.com/SasView/sasview/releases/ and create a new release. Paste contents of release notes sent to @butler into it.

NB: Address the questions (search on ???) and edit the Known Issues section in both before making live.

**Comment by smk78** [comment]
Trac update at `2018/08/10 13:37:15`: **smk78** changed owner from "smk78" to "butler"

**Comment by smk78** [comment]
Trac update at `2018/10/02 15:39:47`: **smk78** commented:

In changeset 1d2a4aace4e2d903cb00a2ef59af75e03b0bc42c:

```text
#!CommitTicketReference repository="sasview" revision="1d2a4aace4e2d903cb00a2ef59af75e03b0bc42c"
Updated release notes. Addresses #1187
```

**Comment by smk78** [comment]
Trac update at `2018/10/02 15:41:51`: **smk78** commented:

I have just pushed an update to the Release Notes upto & including ticket 1184. Note, Changes section and bullet list of tickets were updated. In my opinion, now ready for release.

**Comment by butlerpd** [comment]
Trac update at `2018/10/03 03:17:33`: **butler** commented:

Just taken a quick look -- two points:

1. I re-closed ticket 1148 and generated an new ticket for the enhancement you noted.  Ticket 1148 was a bug that I only discovered because of a user complaining about being confused ... and when I checked they were right: the documentation was **wrong** (though you could argue that it described the behavior that we may actually want but that is **not** the current behavior) - so perhaps the correct way to say it is that the documentation was at odds with the code :-)  This I think is quite different from the general improvement that all models could use.  Because it was an actual bug I think it should be added back to the list of fixed bugs
2. We should probably not claim as FIXED tickets which were closed as `won't fix` :-)  such as http://trac.sasview.org/ticket/980,  #1151, #1175 (actually listed as `invalid`) or #1220
3. #1081 is "ESS GUI not updating after fitting" clearly should be against 5.0 .. the fix is **not** part of 4.2.  I have moved the ticket to 5.0
4. Not sure it is helpful to list all the admin tasks such as #1174 or #1187, or even for that matter do we want to list things like #1210 or #1174?

Finally I'm not sure we should promise in the release notes that we will fix the marketplace ... just in case we are slow ... and actually looking at some of them tonight am realizing that maybe we should NOT in fact be changing files people upload as they may be using that as a repo of the code they used in SasView for their paper. Instead we might make a duplicate that works with the new API?

**Comment by smk78** [comment]
Trac update at `2018/10/03 09:21:36`: **smk78** commented:

Replying to @butler in #comment:8

1. Fine by me!
2. Ok. Removed.
3. Agreed. Oddly I found the ticket hadn't been moved to 5.0 so I just did so.
4. Ok. Removed.

I didn't put that note about updating the marketplace in, it was already in the release notes for 4.1.2!!! But I have now removed it.

Have just pushed the updated RELEASE.txt back to master.

**Comment by smk78** [comment]
Trac update at `2018/10/04 10:52:58`: 
* **smk78** commented:

Just done one last update adding in #1223. Should be ready for release now.

Closing this ticket.


* **smk78** changed resolution from "" to "fixed"
* **smk78** changed status from "assigned" to "closed"
