### ISSUE TITLE
QT5 Gui developer environment issue? (Trac #1162)

### ISSUE THREAD

**Issue by RichardHeenan** [SasView/sasview#1201]
On my win7 laptop, I have cloned current sasview & sasmodels and run the yml files for both wx and qt5 gui. 

Though this works fine on my desk top machine, the laptop behaves slightly differently (e.g. makes an environment called qt5_win not qt5). The wx vesrion runs fine, but I cannot get the qt5 one to work, the initial splash image appears briefly, then I get the failed import error below. Any ideas? 

(Would not normally ticket this sort of thing but I want to get the laptop prepared for code camp and also update the developer wiki page on how to make local builds.)

$ python run.py

Traceback (most recent call last):

  File "run.py", line 167, in <module>

    run_sasview()

  File "C:\stfc\sasview42\sasview\src\sas\qtgui\!MainWindow\!MainWindow.py", line 71, in run_sasview

    mainwindow = !MainSasViewWindow()

  File "C:\stfc\sasview42\sasview\src\sas\qtgui\!MainWindow\!MainWindow.py", line 24, in !__init!__

    from .!GuiManager import !GuiManager

  File "C:\stfc\sasview42\sasview\src\sas\qtgui\!MainWindow\!GuiManager.py", line 14, in <module>

    from sas.qtgui.Utilities.!ConnectionProxy import !ConnectionProxy

  File "C:\stfc\sasview42\sasview\src\sas\qtgui\Utilities\!ConnectionProxy.py", line 3, in <module>

    import urllib.request, urllib.error, urllib.parse

!ImportError: No module named request

(qt5_win)

Migrated from http://trac.sasview.org/ticket/1162
```json
{
    "status": "closed",
    "changetime": "2018-09-08T14:59:54",
    "_ts": "2018-09-08 14:59:54.029802+00:00",
    "description": "On my win7 laptop, I have cloned current sasview & sasmodels and run the yml files for both wx and qt5 gui. \n\nThough this works fine on my desk top machine, the laptop behaves slightly differently (e.g. makes an environment called qt5_win not qt5). The wx vesrion runs fine, but I cannot get the qt5 one to work, the initial splash image appears briefly, then I get the failed import error below. Any ideas? \n\n(Would not normally ticket this sort of thing but I want to get the laptop prepared for code camp and also update the developer wiki page on how to make local builds.)\n\n$ python run.py\n\nTraceback (most recent call last):\n\n\u00a0 File \"run.py\", line 167, in <module>\n\n\u00a0\u00a0\u00a0 run_sasview()\n\n\u00a0 File \"C:\\stfc\\sasview42\\sasview\\src\\sas\\qtgui\\!MainWindow\\!MainWindow.py\", line 71, in run_sasview\n\n\u00a0\u00a0\u00a0 mainwindow = !MainSasViewWindow()\n\n\u00a0 File \"C:\\stfc\\sasview42\\sasview\\src\\sas\\qtgui\\!MainWindow\\!MainWindow.py\", line 24, in !__init!__\n\n\u00a0\u00a0\u00a0 from .!GuiManager import !GuiManager\n\n\u00a0 File \"C:\\stfc\\sasview42\\sasview\\src\\sas\\qtgui\\!MainWindow\\!GuiManager.py\", line 14, in <module>\n\n\u00a0\u00a0\u00a0 from sas.qtgui.Utilities.!ConnectionProxy import !ConnectionProxy\n\n\u00a0 File \"C:\\stfc\\sasview42\\sasview\\src\\sas\\qtgui\\Utilities\\!ConnectionProxy.py\", line 3, in <module>\n\n\u00a0\u00a0\u00a0 import urllib.request, urllib.error, urllib.parse\n\n!ImportError: No module named request\n\n(qt5_win)",
    "reporter": "richardh",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2018-08-22T15:08:21",
    "component": "SasView",
    "summary": "QT5 Gui developer environment issue?",
    "priority": "minor",
    "keywords": "",
    "milestone": "SasView 5.0.0",
    "owner": "richardh",
    "type": "defect"
}
```

**Comment by wpotrzebowski** [comment]
Trac update at `2018/08/22 19:49:54`: **wojciech** commented:

I suppose you are trying to run Qt branch with anaconda2. 
ESS GUI branch works with python3 and therefore it requires anaconda3. Once anaconda 3 is installed, create env from most recent yml file in ESS_GUI branch sasview/build_tools/conda_qt5_win.yml. I hope this works.

**Comment by butlerpd** [comment]
Trac update at `2018/09/08 14:59:54`: 
* **butler** commented:

Richard says it has been resolved so closing


* **butler** changed resolution from "" to "fixed"
* **butler** changed status from "assigned" to "closed"
