### ISSUE TITLE
Github services going away (Trac #1165)

### ISSUE THREAD

**Issue by ajj** [SasView/sasview#1204]
https://developer.github.com/changes/2018-04-25-github-services-deprecation/

GitHub is changing the way we have to integrate services. This affects email notifications and Jenkins integration at this point.

Migrated from http://trac.sasview.org/ticket/1165
```json
{
    "status": "closed",
    "changetime": "2019-02-23T19:18:05",
    "_ts": "2019-02-23 19:18:05.295384+00:00",
    "description": "https://developer.github.com/changes/2018-04-25-github-services-deprecation/\n\nGitHub is changing the way we have to integrate services. This affects email notifications and Jenkins integration at this point.",
    "reporter": "ajj",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Admin",
    "time": "2018-09-03T14:10:32",
    "component": "SasView",
    "summary": "Github services going away",
    "priority": "major",
    "keywords": "",
    "milestone": "Admin Tasks",
    "owner": "wojciech",
    "type": "defect"
}
```

**Comment by wpotrzebowski** [comment]
Trac update at `2019/01/10 12:35:41`: 
* **wojciech** changed owner from "" to "wojciech"
* **wojciech** changed status from "new" to "assigned"

**Comment by butlerpd** [comment]
Trac update at `2019/02/23 19:18:05`: 
* **butler** commented:

Services are gone and all changes seem to be working so closing this ticket now 


* **butler** changed resolution from "" to "fixed"
* **butler** changed status from "assigned" to "closed"
