### ISSUE TITLE
Make Release Notes/Known Issues available from Help in Menu Bar (Trac #1176)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1212]
A comment by @butler on another ticket highlighted the relative obscurity of the Known Issues.

This could be partly redressed by making the Release Notes accessible from the Help in the Menu Bar.

Migrated from http://trac.sasview.org/ticket/1176
```json
{
    "status": "closed",
    "changetime": "2018-09-19T13:54:25",
    "_ts": "2018-09-19 13:54:25.657629+00:00",
    "description": "A comment by @butler on another ticket highlighted the relative obscurity of the Known Issues.\n\nThis could be partly redressed by making the Release Notes accessible from the Help in the Menu Bar.",
    "reporter": "smk78",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView GUI Enhancements",
    "time": "2018-09-17T14:21:08",
    "component": "SasView",
    "summary": "Make Release Notes/Known Issues available from Help in Menu Bar",
    "priority": "blocker",
    "keywords": "",
    "milestone": "SasView 4.2.0",
    "owner": "",
    "type": "enhancement"
}
```

**Comment by smk78** [comment]
Trac update at `2018/09/17 16:46:58`: **smk78** commented:

In the Ticket1176 branch I have created a new Help menu option called 'Release notes'. Selecting this brings up a popup window which specifies where the Release Notes (which incorporate Known Issues) can be found.

I'm going to issue a PR for the branch since it at least does something right now. However the 'vision' I had for the popup was that it would ''also'' display the text of the README.txt file in \sasview\installers, but sadly accomplishing that is beyond my abilities. :-)

'''HOWEVER''', in the process I made two observations which should be addressed before the 4.2 Release (and so I am changing the milestone of this ticket to 4.2.0):

1. We do not, as far as my searches can tell, actually bundle the README.txt with the installer downloads! Is this correct? I think we should. Else why do we bother to edit the file!

2. There is a slightly iffy looking 'Current Known Issues' bit at the bottom of https://github.com/SasView/sasview/releases/ which perhaps needs reviewing.

**Comment by smk78** [comment]
Trac update at `2018/09/17 16:47:14`: 
* **smk78** changed milestone from "SasView 4.3.0" to "SasView 4.2.0"
* **smk78** changed priority from "major" to "blocker"

**Comment by smk78** [comment]
Trac update at `2018/09/18 17:28:17`: **smk78** commented:

On the call today it was agreed to:

* do away with \sasview\installers\README-next-release.txt
* move \sasview\installers\README.txt (the detailed release notes) to \sasview\docs\sphinx-docs\user
* convert README.txt to RELEASE.rst
* do away with the popup Release Notes box created yesterday and instead just link Release Notes in the Help menu to a new documentation page \sasview\doc\user\RELEASE.html autobuilt with the documentation

All this is now done in Ticket 1176 branch.

**Comment by smk78** [comment]
Trac update at `2018/09/19 09:41:02`: 
* **smk78** commented:

Ticket1176 branch tested, approved and merged.


* **smk78** changed resolution from "" to "fixed"
* **smk78** changed status from "new" to "closed"

**Comment by RichardHeenan** [comment]
Trac update at `2018/09/19 11:35:45`: **richardh** commented:

In master the new docs look good, have suggested to Steve to add a menu item in the docs to the release notes (as the release notes link to main docs but not vice versa).

If I now build docs in ESS_GUI branch, the docs do not work properly, the navigation panel on the left shuts downs, and I don't get the "allow blocked content". Suspect changes here need to be merged onto ESS_GUI?

**Comment by smk78** [comment]
Trac update at `2018/09/19 13:54:25`: **smk78** commented:

Have pushed a tweak that adds a link to the release notes to index.html to address @richardh's first comment. Available in Build 414.
