### ISSUE TITLE
Add FitPage name to Graph Title (Trac #1181)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1217]
I was just helping a student who had about a dozen fit pages active in his !SasView session and therefore a multitude of graphs, which he glibly minimised...

Once you do this, there is presently no easy way to find a particular graph again. You have to maximise each icon in turn.

It would be great if you could go to the Menu Bar, select Window, and where it presently says Graph1, Graph2, etc, it also said which Graph was associated with which !FitPage.

Migrated from http://trac.sasview.org/ticket/1181
```json
{
    "status": "closed",
    "changetime": "2018-09-25T08:42:02",
    "_ts": "2018-09-25 08:42:02.031640+00:00",
    "description": "I was just helping a student who had about a dozen fit pages active in his !SasView session and therefore a multitude of graphs, which he glibly minimised...\n\nOnce you do this, there is presently no easy way to find a particular graph again. You have to maximise each icon in turn.\n\nIt would be great if you could go to the Menu Bar, select Window, and where it presently says Graph1, Graph2, etc, it also said which Graph was associated with which !FitPage.",
    "reporter": "smk78",
    "cc": "",
    "resolution": "duplicate",
    "workpackage": "SasView GUI Enhancements",
    "time": "2018-09-24T13:42:08",
    "component": "SasView",
    "summary": "Add FitPage name to Graph Title",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 5.0.0",
    "owner": "",
    "type": "enhancement"
}
```

**Comment by RichardHeenan** [comment]
Trac update at `2018/09/24 14:09:18`: **richardh** commented:

Would be very nice if plots from FitPage1 were labelled graph1.1, 1.2 etc or 1a, 1b etc

Will add this to ESS kanban board for 5.0

**Comment by butlerpd** [comment]
Trac update at `2018/09/25 01:42:21`: **butler** commented:

Actually, Laura was looking at this during code camp.  It turns out that this is better than Ingo's ticket #246.... it is ....wait for it ...  ticket #242 :-)  I would recommend putting these specific suggestions for relating the graphs to the fitpage into that ticket and then closing this as duplicate.  I do not know what Laura may have done with respect to posting to kanban boards.

**Comment by smk78** [comment]
Trac update at `2018/09/25 08:42:02`: 
* **smk78** commented:

Copied to #242.


* **smk78** changed resolution from "" to "duplicate"
* **smk78** changed status from "new" to "closed"
