### ISSUE TITLE
documentation for magnetism need update (Trac #1190)

### ISSUE THREAD

**Issue by RichardHeenan** [SasView/sasview#1225]
docs for magnetism need changing as they claim that magnetism only works for 5 models, when in fact they should now work for all discrete particles i.e. all of cylinder, ellipsoid, parallelepiped & sphere categories.

Magnetic sld's are automatically generated for any parameter name starting sld_.

Except need to check whether there are any pure python models - see #1108

Paul K said: The calculation works by setting the effective SLD for each particle SLD based on the spin and scattering angle of the neutron and the angle of the magnetic field for that SLD. The scattering patterns for the different spin states (++, +-, -+, --) are then added proportionally. Assuming uniform magnetism within each particle component, I see no reason that this wouldn't apply to all particle types.

Migrated from http://trac.sasview.org/ticket/1190
```json
{
    "status": "closed",
    "changetime": "2018-10-15T11:13:44",
    "_ts": "2018-10-15 11:13:44.315223+00:00",
    "description": "docs for magnetism need changing as they claim that magnetism only works for 5 models, when in fact they should now work for all discrete particles i.e. all of cylinder, ellipsoid, parallelepiped & sphere categories.\n\nMagnetic sld's are automatically generated for any parameter name starting sld_.\n\nExcept need to check whether there are any pure python models - see #1048\n\nPaul K said: The calculation works by setting the effective SLD for each particle SLD based on the spin and scattering angle of the neutron and the angle of the magnetic field for that SLD. The scattering patterns for the different spin states (++, +-, -+, --) are then added proportionally. Assuming uniform magnetism within each particle component, I see no reason that this wouldn't apply to all particle types.",
    "reporter": "richardh",
    "cc": "",
    "resolution": "invalid",
    "workpackage": "SasView Documentation",
    "time": "2018-10-09T16:28:15",
    "component": "SasView",
    "summary": "documentation for magnetism need update",
    "priority": "minor",
    "keywords": "",
    "milestone": "SasView 4.3.0",
    "owner": "smk78",
    "type": "defect"
}
```

**Comment by smk78** [comment]
Trac update at `2018/10/11 09:54:56`: **smk78** commented:

@richardh, which docs are you referring to please?

The docs just released with 4.2.0 say (this is from Writing a Plugin Model):

```text
Magnetism is supported automatically for all shapes by modifying the effective SLD of 
particle according to the Halpern-Johnson vector describing the interaction between 
neutron spin and magnetic field. All parameters marked as type sld in the parameter 
table are treated as possibly magnetic particles with magnitude M0 and direction 
mtheta and mphi. Polarization parameters are also provided automatically for magnetic 
models to set the spin state of the measurement.

For more complicated systems where magnetism is not uniform throughout the individual 
particles, you will need to write your own models. You should not mark the nuclear sld 
as type sld, but instead leave them unmarked and provide your own magnetism and 
polarization parameters. For 2D measurements you will need (qx,qy) values for the 
measurement to compute the proper magnetism and orientation, which you can implement 
using Iqxy(qx, qy, par1, par2, ...).
```

And !Polarisation/Magnetic Scattering says:

```text
Models which define a scattering length density parameter can be evaluated as magnetic 
models. In general, the scattering length density (SLD = β) in each region where the 
SLD is uniform, is a combination of the nuclear and magnetic SLDs and, for polarised 
neutrons, also depends on the spin states of the neutrons.
```

**Comment by pkienzle** [comment]
Trac update at `2018/10/12 00:27:24`: **pkienzle** commented:

Emphasis on parameter **type** instead of parameter **name**.  So long as has `"sld"` in the fifth column, then the parameter can have a magnetic moment, even if it's name does not start with `sld_`.

**Comment by RichardHeenan** [comment]
Trac update at `2018/10/15 11:13:44`: 
* **richardh** commented:

Apologies for great confusion caused,  somehow I must have been looking at the docs for 4.1.2 where it says only 5 models have magnetism instead of docs for 4.2 as given by Steve above. 

The only 5 models part still needs sorting in 5.0, see Jira issue 1199.

Meanwhile I will close this issue as invalid.


* **richardh** changed resolution from "" to "invalid"
* **richardh** changed status from "new" to "closed"
