### ISSUE TITLE
copy paste parameter copies the form factor name heading as a parameter (Trac #1197)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#1231]
Open a !FitPage and choose a model (I chose core shell sphere). Then open another !FitPage and chose a model (I chose the same model).  Then to to !FitPage 1 and copy parameters and then to !FitPage 2 to paste.

The core_shell_sphere heading for the parameters after scale and background now looks like a fitable parameter with NaN for value and min max.

Migrated from http://trac.sasview.org/ticket/1197
```json
{
    "status": "closed",
    "changetime": "2018-11-21T13:01:44",
    "_ts": "2018-11-21 13:01:44.465434+00:00",
    "description": "Open a !FitPage and choose a model (I chose core shell sphere). Then open another !FitPage and chose a model (I chose the same model).  Then to to !FitPage 1 and copy parameters and then to !FitPage 2 to paste.\n\nThe core_shell_sphere heading for the parameters after scale and background now looks like a fitable parameter with NaN for value and min max.",
    "reporter": "butler",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2018-10-15T02:14:00",
    "component": "SasView",
    "summary": "copy paste parameter copies the form factor name heading as a parameter",
    "priority": "blocker",
    "keywords": "",
    "milestone": "SasView 5.0.0",
    "owner": "",
    "type": "defect"
}
```

**Comment by RichardHeenan** [comment]
Trac update at `2018/10/15 09:27:09`: **richardh** commented:

This is a known issue in 5.0, see JIRA 1183 & 1196, which Laura is I think still working on. There are similar problems when there is an S(Q)in the pasted model. All a follow on effect of adding sub-headings to identify the model or S(Q) names!

**Comment by rozyczko** [comment]
Trac update at `2018/11/21 13:01:27`: **piotr** commented:

I need to be more meticulous with checking 5.0 related bugs on TRAC. This has been fixed a while ago!.
Marking closed, considering RH closed this issue in JIRA.

**Comment by rozyczko** [comment]
Trac update at `2018/11/21 13:01:44`: 
* **piotr** changed resolution from "" to "fixed"
* **piotr** changed status from "new" to "closed"
