### ISSUE TITLE
Copy Params claims it is failing (Trac #1200)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1233]
In 4.2.0 on Win.

Having done a fit, if you then select Edit > Copy Params an error popup appears which says:

```text
Failed to put data on the clipboard (error -2147221040: openClipboard Failed)
```

However, it ''does'' seem to have done the copy because you can still paste the parameters into another !FitPage or text editor, etc.

I specifically remember testing this functionality in pre-release versions of 4.2.0 and this error didn't appear. This suggests it was introduced late in the release cycle.

Migrated from http://trac.sasview.org/ticket/1200
```json
{
    "status": "new",
    "changetime": "2019-01-07T22:53:45",
    "_ts": "2019-01-07 22:53:45.785854+00:00",
    "description": "In 4.2.0 on Win.\n\nHaving done a fit, if you then select Edit > Copy Params an error popup appears which says:\n\n{{{\nFailed to put data on the clipboard (error -2147221040: openClipboard Failed)\n}}}\n\nHowever, it ''does'' seem to have done the copy because you can still paste the parameters into another !FitPage or text editor, etc.\n\nI specifically remember testing this functionality in pre-release versions of 4.2.0 and this error didn't appear. This suggests it was introduced late in the release cycle.",
    "reporter": "smk78",
    "cc": "",
    "resolution": "",
    "workpackage": "SasView Bug Fixing",
    "time": "2018-10-18T15:28:27",
    "component": "SasView",
    "summary": "Copy Params claims it is failing",
    "priority": "critical",
    "keywords": "",
    "milestone": "SasView 4.3.0",
    "owner": "",
    "type": "defect"
}
```

**Comment by smk78** [comment]
Trac update at `2018/10/18 15:29:04`: 
* **smk78** changed attachment from "" to "failing-copy-params.png"
* **smk78** commented:

Screenshot of failing copy params

**Comment by butlerpd** [comment]
Trac update at `2018/10/31 03:34:53`: 
* **butler** commented:

Suggest if this is a simple fix that we think about adding to 4.2.1?


* **butler** changed milestone from "SasView 4.3.0" to "SasView 4.2.1"

**Comment by butlerpd** [comment]
Trac update at `2019/01/07 22:53:28`: **butler** commented:

This is a minor nuisance (it still works despite the message) and hard to fix.  As agreed we won't let this delay a 4.2.1 release of NXcanSAS reader fix.  Moving now to milestone 4.3

**Comment by butlerpd** [comment]
Trac update at `2019/01/07 22:53:45`: **butler** changed milestone from "SasView 4.2.1" to "SasView 4.3.0"

**Comment by smk78** [comment]
Interestingly, in 4.2.2 the error is replaced by a warning:

```
Warning:
Parameter values are pasted from the clipboard...
```

This arises even when you select Copy Params and must be dismissed _twice_!

**Comment by butlerpd** [comment]
In the master branch I get no error popping up and all seems to work fine on windows 10. Guessing this got fixed somewhere but the ticket forgotten.  @smk78 may want to double check but for now am going to close this

**Comment by smk78** [comment]
Agreed. It is fixed in 4.x master.
