### ISSUE TITLE
5.0 not giving same fit results as 4.2 (Trac #1204)

### ISSUE THREAD

**Issue by RichardHeenan** [SasView/sasview#1234]
Load e.g. AOT_microemulsion-shell_contrast.xml
Fit e.g. just scale & length with cylinder model, taking care that all params are at their default values (this may involve switching model category and re-selecting cylinder to get them back if you have done other things first).

4.2 and 5.0 do not give the same fit results for a "poor fit" such as this. They should do if using the same fit engine, and same fit options.
I suspect an initialisation or default for weighting, resolution, fit engine or something else is not working properly but I have not yet managed to find the culprit.

For "good" fits the parameter values and their errors are very close but still not identical as they perhaps ought to be.

Migrated from http://trac.sasview.org/ticket/1204
```json
{
    "status": "assigned",
    "changetime": "2019-03-20T14:43:08",
    "_ts": "2019-03-20 14:43:08.833792+00:00",
    "description": "Load e.g. AOT_microemulsion-shell_contrast.xml\nFit e.g. just scale & length with cylinder model, taking care that all params are at their default values (this may involve switching model category and re-selecting cylinder to get them back if you have done other things first).\n\n4.2 and 5.0 do not give the same fit results for a \"poor fit\" such as this. They should do if using the same fit engine, and same fit options.\nI suspect an initialisation or default for weighting, resolution, fit engine or something else is not working properly but I have not yet managed to find the culprit.\n\nFor \"good\" fits the parameter values and their errors are very close but still not identical as they perhaps ought to be.",
    "reporter": "richardh",
    "cc": "",
    "resolution": "",
    "workpackage": "SasView QA and testing",
    "time": "2018-10-29T12:11:01",
    "component": "SasView",
    "summary": "5.0 not giving same fit results as 4.2",
    "priority": "blocker",
    "keywords": "",
    "milestone": "SasView 5.0.0",
    "owner": "piotr",
    "type": "defect"
}
```

**Comment by RichardHeenan** [comment]
Trac update at `2018/10/29 12:23:39`: **richardh** commented:

PS there are times when 4.2 and 5.0 do give the same results, so there is something intermittent here, I am beginning to suspect the "set weighting" flag in 4.2.

**Comment by RichardHeenan** [comment]
Trac update at `2018/10/29 12:43:02`: 
* **richardh** commented:

The set weighting choice in 4.2 seems to have no effect, whereas it does in 5.0, I am going to close this ticket for now write a new one for 4.2


* **richardh** changed resolution from "" to "invalid"
* **richardh** changed status from "new" to "closed"

**Comment by RichardHeenan** [comment]
Trac update at `2018/11/05 17:18:59`: 
* **richardh** changed attachment from "" to "coil1.png"
* **richardh** commented:

starting parameters

**Comment by RichardHeenan** [comment]
Trac update at `2018/11/05 17:19:23`: 
* **richardh** changed attachment from "" to "coil2.png"
* **richardh** commented:

turn on 2 params

**Comment by RichardHeenan** [comment]
Trac update at `2018/11/05 17:19:57`: 
* **richardh** changed attachment from "" to "coil3.png"
* **richardh** commented:

more params fitting

**Comment by RichardHeenan** [comment]
Trac update at `2018/11/05 17:20:42`: 
* **richardh** changed attachment from "" to "coil4_iQwt.png"
* **richardh** commented:

change from di weights to I(Q) weights

**Comment by RichardHeenan** [comment]
Trac update at `2018/11/05 17:23:46`: 
* **richardh** changed _comment0 from:

> Some more direct comparisons between 4.2 and 5.0, see screen shots of same fits in each giving different answers, 5.0 on left, 4.2 on right. 
> These for AOT_microemulsion shell contrast, fit to mono_gauss_coil
> 
> The initial start up model looks the same, but the residuals plot is rather different!
> None of the fit results are identical, and are very different when change to I(Q) weights.
> 
> Suspect something is perhaps not being initialised properly, or passed properly???

to:

> 1541438754358265


* **richardh** changed _comment1 from:

> Some more direct comparisons between 4.2 and 5.0, see screen shots of same fits in each giving different answers, 5.0 on left, 4.2 on right. 
> These for AOT_microemulsion shell contrast, fit to mono_gauss_coil
> 
> The initial start up model looks the same, but the residuals plot is rather different!
> None of the fit results are identical, and are very different when change to I(Q) weights.
> 
> Suspect something is perhaps not being initialised properly, or passed properly???
> 
> This time I was in the beta_approx branch, not master, of sasmodels, but I don't think that mattters.

to:

> 1541438892984146


* **richardh** commented:

Some more direct comparisons between 4.2 and 5.0, see screen shots of same fits in each giving different answers, 5.0 on left, 4.2 on right. 
These for AOT_microemulsion shell contrast, fit to mono_gauss_coil

The initial start up model looks the same, but the residuals plot is rather different!
None of the fit results are identical, and are very different when change to I(Q) weights.

Suspect something is perhaps not being initialised properly, or passed properly???

This time I was in the beta_approx branch, not master, of sasmodels, but I don't think that mattters.

(Apologies I should not have turned on both scale and I_zero here as they are redundant in this model, however the conclusions are the same).


* **richardh** changed resolution from "invalid" to ""
* **richardh** changed status from "closed" to "reopened"

**Comment by RichardHeenan** [comment]
Trac update at `2018/11/05 17:38:12`: 
* **richardh** changed attachment from "" to "coil5.png"
* **richardh** commented:

same results with default dI weighting IF start at same place

**Comment by RichardHeenan** [comment]
Trac update at `2018/11/05 17:40:39`: **richardh** commented:

In default dI weighting can get 5.0 and 4.2 to give same answer, as per latest attached screen shot, IF start at the same place, but this is not the case in the other weighting schemes.

**Comment by RichardHeenan** [comment]
Trac update at `2018/11/15 12:09:45`: **richardh** commented:

Looks like there was a long standing issue in 4.x (and possibly even 3.x), see #1235
Now need to check weighting scheme effect in 5.0 and 4.2 side by side again

**Comment by RichardHeenan** [comment]
Trac update at `2019/02/27 17:51:17`: 
* **richardh** commented:

I have just downloaded 5.0 beta 2 on my desktop, and 4.2.1 build 493 from Jenkins on my laptop, if I load the same test data and run the same fits I am still not getting identical fit results (especially if the fit is poor) so there is I think still something wrong with the weightings in one or other of the code versions.


* **richardh** changed priority from "critical" to "blocker"

**Comment by RichardHeenan** [comment]
Trac update at `2019/02/27 18:05:28`: **richardh** commented:

Looks like "none" and "use dI data" are getting confused in both 4.2 and 5.0 depending the order in which you hit the buttons. Switching between them may give the same or different answers, so suspect there is an underlying issue in the logic of the code in both??? (sorry got to go home now)

**Comment by RichardHeenan** [comment]
Trac update at `2019/03/11 12:55:18`: 
* **richardh** commented:

(1) Further comparison of 5.0 beta2 against 4.2.1 suggests that 5.0 is starting up with weighting as "none" not the "Use dI data" that the gui claims. So I am going to assign this ticket for Piotr to have a look please. Thus by default 5.0 is not currently giving identical fits.

(2)The value of scale that is fitted in 5.0 is not the same as in 4.2.1 - were we expecting it to change? (In the example I used it was ~44% of the 4.2.1 value)

(3) In 4.2 the values of the reduced chai squared varies hugely with weighting scheme, but remains roughly comparable in 5.0.  In this case I think 5.0 is correct in that our docs only have error squared in the equation for chai squared, thus no dependence on weights.

(4) In the options tab of 5.0, when you change weighting scheme the fit buttons briefly goes red and shows "running" as is it it is doing a fit with the new weights, however it does not actually do a fit, so you do have to hit the fit button on either the options or the model tab. This is consistent with 4.2.1, a new choice of weighting only takes effect on the next fit. Should we change this? Probably not?


* **richardh** changed owner from "richardh" to "piotr"
* **richardh** changed status from "reopened" to "assigned"

**Comment by RichardHeenan** [comment]
Trac update at `2019/03/11 16:21:28`: **richardh** commented:

Ignore (2) above, that was my mistake, scale factor does agree as expected.

**Comment by RichardHeenan** [comment]
Trac update at `2019/03/11 16:45:33`: **richardh** commented:

Regarding (3) above, in 4.2.1 the residuals plot is showing (obs-calc)/weight,  which is what the residuals workspace also contains, whilst in 5.0 the residuals plot and workspace are of simply (obs-calc) without the weight. This likely explains the large numerical differences in chai squared values.

Thus apart from the "none" weights case the residuals plot in 4.2 looks very different to that in 5.0

Do we want 5.0 to keep this behaviour, or to match 4.2.1 ?

**Comment by RichardHeenan** [comment]
Trac update at `2019/03/20 12:51:28`: **richardh** commented:

Repeating parts of previous comments as I was not able to mention this on the call yesterday, what do the science team think regarding (3) below?

(1) Having fixed the non-active weights in 4.2 (see #1235) further comparison of 5.0 beta2 against 4.2.1 suggests that 5.0 is  starting up with weighting as "none" not the "Use dI data" that the gui  claims. So this ticket is assigned to Piotr to have a look  please. Thus by default 5.0 is not currently giving identical fits.

(2) Resolved - my mistake.

(3) In 4.2 the values of the reduced chai squared varies hugely with  weighting scheme, but they remain roughly comparable in 5.0.  In this case I  think 5.0 is correct in that our docs only have error squared in the  equation for chai squared, thus no dependence on weights. 

However in 4.2.1 the residuals plot is showing  (obs-calc)/weight,  which is what the residuals workspace also contains,  whilst in 5.0 the residuals plot and workspace are of simply (obs-calc)  without the weight. This likely explains the large numerical  differences in chai squared values.


Thus apart from the "none" weights case the residuals plot in 4.2 looks very different to that in 5.0


Do we want 5.0 to keep this behaviour, or to match 4.2.1 ? in which case this needs a further 5.0 ticket.

**Comment by butlerpd** [comment]
Trac update at `2019/03/20 13:46:51`: **butler** commented:

I guess the FIRST question really is why did it get changed in 5.0? is it because of an oversight when typing code? a deliberate omission because it was not understood by the person doing that coding? or because there was some discussion that 4.x was behaving incorrectly?

I would argue that in the first instance it should behave "exactly the same" until there is a discussion to argue that the current implementation is wrong. 

Certainly as we all know there are plenty of things in 4.x that were/could be incorrect (or not state of the art).  Regarding this particular question, I will have to read up a bit on "official statistical definitions" of Chi^2^ but I think that If you have a data set with vastly varying uncertainties, any goodness of fit that does NOT somehow account for that (and maybe a simple normalization isn't the perfectly correct answer?) would be meaningless? ... scientifically speaking :-)

**Comment by rozyczko** [comment]
Trac update at `2019/03/20 14:43:08`: **piotr** commented:

Cursory look at 4.2 and 5.0 sources for chi2 calculation doesn't show any discrepancies, so the lack of weight scaling must be a bug elsewhere in the code. It is a bug, since I was trying to achieve numerical equivalency between the two versions. Whether the scaling is correct or not, I will fix the issue in 5.0.

**Comment by RichardHeenan** [comment]
_(1) Having fixed the non-active weights in 4.2 (see #1235) further comparison of 5.0 beta2 against 4.2.1 suggests that 5.0 is starting up with weighting as "none" not the "Use dI data" that the gui claims._  - IS NOW FIXED

_RE (3) In 4.2 the values of the reduced chi squared varies hugely with weighting scheme, but they remain roughly comparable in 5.0. In this case I think 5.0 is correct in that our docs only have error squared in the equation for chi squared, thus no dependence on weights.

However in 4.2.1 the residuals plot is showing (obs-calc)/weight, which is what the residuals workspace also contains, whilst in 5.0 the residuals plot and workspace are of simply (obs-calc) without the weight. This likely explains the large numerical differences in chai squared values.

Thus apart from the "none" weights case the residuals plot in 4.2 looks very different to that in 5.0

Do we want 5.0 to keep this behaviour, or to match 4.2.1 ? in which case this needs a further 5.0 ticket._

**Discussion at code camp** - the residuals workspaces, residuals (normalized) plots, and chi squared need to be changed to be like 4.2. (Though the chi squared values will likely follow if the residuals workspace is correct.)

The docs about chi squared need to be changed to include the weights.

**Comment by rozyczko** [comment]
Fixed in 5.0 - chi2 and residuals update with weight change and coincide with 4.x now.

**Comment by butlerpd** [comment]
Great news! Does this mean the issue can be closed? or is there an outstanding issue on this ticket still?

**Comment by RichardHeenan** [comment]
Yes good news, but before we close the ticket ...  
(a) someone ought to verify results 
(b) The docs about chi squared need to be changed to include the weights.

**Comment by RichardHeenan** [comment]
re (a) just built 4.2 on my laptop, 5.0 ESS_GUI on desktop

When doing the same fit, the parameter values on 5.0 are almost always identical when changing the weighting type, but the chi2 value is very slightly lower in 5.0 (are you sure all the data points are included ??)  I was e.g. fitting cylinder model, set length at 75. turn on scale & radius. 

Looking at the values in the residuals workspace via "show info" the numbers seem the same within rounding errors.

**Comment by pkienzle** [comment]
Check if they differ by DOF correction.  That is, given N data points and k fitted parameters, can you recover one chisq from the other with scaling by (N-k)/(N-1) or by (N-k)/N or the inverse?

**Comment by pkienzle** [comment]
... or N/(N-1).

**Comment by RichardHeenan** [comment]
I think 5.0 is dividing by Ndata instead of (Ndata - Nfitting_params)

**Comment by rozyczko** [comment]
Fixed. The chi2 value from fitting was being overwritten after calculate1D() step.

**Comment by RichardHeenan** [comment]
I strongly suspect that the errors in the normalised residuals are only correct at values of 1.0 for the default weighting of "use dI data", the other cases need a proper error propagation.

**Comment by smk78** [comment]
@RichardHeenan said:
>> The docs about chi squared need to be changed to include the weights.

Have updated /sasview/src/sas/sasgui/perspectives/fitting/media/residuals_help.rst

**Comment by rozyczko** [comment]
I iook a weighted dataset (1D/P123_D2O_30_percent.xml) and applied a simple cylinder model.
Chi2 for None, dI data, |sqrt(I)| and |I| is the same in both 4.2 and 5.0.
What else can I test to assure Chi2 calculations are as expected?

**Comment by RichardHeenan** [comment]
re - What else can I test to assure Chi2 calculations are as expected?
 - The chi2 are fine now - thank you for fixing them,
The remaining issue on this ticket (as far as I can see) is regarding the error bars on the normalised residuals plots.   I strongly suspect that the errors in the normalised residuals are only correct at values of 1.0 for the default weighting of "use dI data", the other cases need a proper error propagation.

**Comment by rozyczko** [comment]
Sorry Richard, I can't find a dataset which would give me unnormalized (not 1.0) error bars for residual plots. Even if a dataset comes with custom dX, the residuals errors are always 1.0 (in 4.2 and in 5.0).
I must be missing something.

**Comment by RichardHeenan** [comment]
Apologies, I thought that I had a version of 4.2 where the errors on normalised residuals did work properly, but it seems that this problem is a long standing one, at least as far back as 3.0, that <dY>, the error, on the normalised residuals is always 1.0, when it should change with different weighting schemes.

**Comment by RichardHeenan** [comment]
Closing this ticket, as I think 5.0 is now producing the same fit results as 4.2 (hooray!)

Have opend a new issues for the values of errors - see - https://github.com/SasView/sasview/issues/1329#issue-439528472
