### ISSUE TITLE
4.2 set weighting choice seems to be ignored. (Trac #1205)

### ISSUE THREAD

**Issue by RichardHeenan** [SasView/sasview#1235]
Comparing fit results between 4.2 and 5.0, noticed (see #1234) that the set weighting option in 4.2 has no effect on the fit results, whereas it does in 5.0

Further investigation required.

Migrated from http://trac.sasview.org/ticket/1205
```json
{
    "status": "closed",
    "changetime": "2019-02-02T22:21:13",
    "_ts": "2019-02-02 22:21:13.613690+00:00",
    "description": "Comparing fit results between 4.2 and 5.0, noticed (see #1204) that the set weighting option in 4.2 has no effect on the fit results, whereas it does in 5.0\n\nFurther investigation required.",
    "reporter": "richardh",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView QA and testing",
    "time": "2018-10-29T12:46:54",
    "component": "SasView",
    "summary": "4.2 set weighting choice seems to be ignored.",
    "priority": "blocker",
    "keywords": "",
    "milestone": "SasView 4.2.1",
    "owner": "mathieu",
    "type": "defect"
}
```

**Comment by smk78** [comment]
Trac update at `2018/10/29 14:40:40`: **smk78** commented:

Changing the weighting option does change the appearance of the residuals plot.

Moreover, if you sub-select and fit a region of the data with poorer error bars you DO find that the fit parameters change markedly depending on the weighting scheme chosen. For example, load the ISIS_Polymer_Blend_RT2 data and limit the fitted region to between 0.15 - 0.254. As you include more and more of the data below 0.15 the fit parameters vary less with the weighting scheme chosen as @richardh describes.

**Comment by RichardHeenan** [comment]
Trac update at `2018/10/29 15:00:23`: **richardh** commented:

In the test I did the cylinder length stayed around 160.5 ang regardless of weighting scheme in 4.2, but in 5.0 was 160.5 (weights dI), 104 (weights none), 148 (sqrtI) and 205 (weights I(Q)) ang. So what is 5.0 doing differently, or is 4.2 acting up?

**Comment by RichardHeenan** [comment]
Trac update at `2018/10/29 16:36:27`: **richardh** commented:

3.1.2 and 4.1.2 behave in same way for me as 4.2, so perhaps the issue lies in 5.0 after all?

**Comment by butlerpd** [comment]
Trac update at `2018/11/13 15:11:26`: **butler** changed priority from "critical" to "blocker"

**Comment by pkienzle** [comment]
Trac update at `2018/11/13 19:41:42`: **pkienzle** commented:

Issue confirmed for current master.

Change the weighting and hit compute and the residuals plot is updated appropriately, however, the fit seems to use the data weights regardless of the GUI setting.

**Comment by pkienzle** [comment]
Trac update at `2018/11/13 21:16:28`: **pkienzle** commented:

Sasview [https://github.com/SasView/sasview/pull/199 PR# 199].

**Comment by butlerpd** [comment]
Trac update at `2019/02/02 22:21:13`: **butler** changed milestone from "SasView 4.3.0" to "SasView 4.2.1"
