### ISSUE TITLE
Incorrect (and confusing) presentation of dQ from data in instrumental smearing section (Trac #1206)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#1236]
Selecting `use dQ Data` currently displays dQ high and dQ low (for pinhole data at least),  However dQ low is not labelled while dQ high is labelled as `dQ[%]`.

Prior to !SasView version 4.1.0, the two values were labeled `dQ high` and `dQ low`. In 4.1.0 a change was made to the custom pinhole to be useful by asking for a dQ/Q in percent (see #941).  The current labels probably were introduced accidentally in that work.  However the proper fix should be to change the values presented to be dQ/Q[%] (as one label suggests) and then fix the labels to make it clear what is presented: `dQ/Q low[%]` and `dQ/Q high[%]`.

Migrated from http://trac.sasview.org/ticket/1206
```json
{
    "status": "closed",
    "changetime": "2019-01-23T02:16:29",
    "_ts": "2019-01-23 02:16:29.513442+00:00",
    "description": "Selecting `use dQ Data` currently displays dQ high and dQ low (for pinhole data at least),  However dQ low is not labelled while dQ high is labelled as `dQ[%]`.\n\nPrior to !SasView version 4.1.0, the two values were labeled `dQ high` and `dQ low`. In 4.1.0 a change was made to the custom pinhole to be useful by asking for a dQ/Q in percent (see #850).  The current labels probably were introduced accidentally in that work.  However the proper fix should be to change the values presented to be dQ/Q[%] (as one label suggests) and then fix the labels to make it clear what is presented: `dQ/Q low[%]` and `dQ/Q high[%]`.",
    "reporter": "butler",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "McSAS Integration Project",
    "time": "2018-10-31T02:59:41",
    "component": "SasView",
    "summary": "Incorrect (and confusing) presentation of dQ from data in instrumental smearing section",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.2.1",
    "owner": "GitHub <noreply@github.com>",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2018/10/31 03:24:14`: **butler** commented:

From @smk78 in ticket #941

The codebase (see basepage.py and fitpage.py) seems to have some infrastructure for computing %dQ.
I think displaying the %dQ is probably of more use to the user, and we could flag "crazy" values by turning the reporting box(es) red or similar. But exactly what we report probably needs some discussion.

**Comment by butlerpd** [comment]
Trac update at `2019/01/06 00:16:02`: **butler** commented:

In changeset bd3a3aeddd7ce76c9a217131f424f1df54ed988b:

```text
#!CommitTicketReference repository="sasview" revision="bd3a3aeddd7ce76c9a217131f424f1df54ed988b"
Fix reporting of pinhole resolution on FitPage when taken from data

GUI now reports dQ/Q as the label suggested.  Also labels were fixed to
be more clear.  Finally a small bit of code cleanup was attempted.  Note
that there is a serious problem with the 2D resolution part of that GUI.
This is a previously unreported problem which may be dealt with in
another ticket or may be done here depending on the effort required.

addresses #1236
```

**Comment by butlerpd** [comment]
Trac update at `2019/01/08 13:01:32`: **butler** commented:

In changeset f6322479fd536fc269f4624681874d3500690e27:

```text
#!CommitTicketReference repository="sasview" revision="f6322479fd536fc269f4624681874d3500690e27"
Fix 2D smearing GUI

Make 2D from data as % of average.  Fix input and message boxes to be
the right ones and fix some logic issues

addresses #1236
```

**Comment by smk78** [comment]
Trac update at `2019/01/21 17:09:18`: **smk78** commented:

Tested https://jenkins.esss.dk/sasview/job/SasView_Win7_64bit_PullRequest/ Build!#295 on W64 and verify that the GUI now shows dQ/Q in % at Qmin and Qmax.

If one wanted to put a big fat cherry on top of this fix, it would be to make the dQ/Q boxes change colour if the value is 'excessive' in order to draw the users attention to it.
