### ISSUE TITLE
don't create .pyc files in ~/.sasview (Trac #1207)

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#1237]
All versions.

Need to load custom config file without create a corresponding pyc file.  The pyc files are dependent on python version, and so may cause problems that custom config is forgotten between releases.  Also, the __pycache__ directories in the ~/.sasview are messy.

Same applies to plugin_models directory, and the weights directory if user defined distributions PR is ever merged.

Migrated from http://trac.sasview.org/ticket/1207
```json
{
    "status": "new",
    "changetime": "2018-11-02T16:21:23",
    "_ts": "2018-11-02 16:21:23.484956+00:00",
    "description": "All versions.\n\nNeed to load custom config file without create a corresponding pyc file.  The pyc files are dependent on python version, and so may cause problems that custom config is forgotten between releases.  Also, the __pycache__ directories in the ~/.sasview are messy.\n\nSame applies to plugin_models directory, and the weights directory if user defined distributions PR is ever merged.",
    "reporter": "pkienzle",
    "cc": "",
    "resolution": "",
    "workpackage": "McSAS Integration Project",
    "time": "2018-11-02T16:21:23",
    "component": "SasView",
    "summary": "don't create .pyc files in ~/.sasview",
    "priority": "minor",
    "keywords": "",
    "milestone": "SasView 4.3.0",
    "owner": "",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Probably not worth the resources for 4.x but should be relevant to 5.x so moving to 5.1

**Comment by butlerpd** [comment]
@rozyczko - I recently was surprised to notice that there were no pyc in the 5.0 plugin directory.  DOes that mean this ticket can be closed rather than wait for 5.1?

**Comment by rozyczko** [comment]
There are still both `.pyc` files and `__pycache__` in `.sasview`. We can easily avoid generating those so let's address this issue in 5.0.x or 5.1

**Comment by butlerpd** [comment]
ah ok ... so still valid then. Will leave in 5.1 and not delete

**Comment by lucas-wilkins** [comment]
ain't no custom config no more, so ain't no .pyc file neither
