### ISSUE TITLE
run.py fails if tinycc isn't built (windows) (Trac #1211)

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#1241]
sasview 4.3 developer windows

run.py fails on windows if tinycc is not built.

If tinycc does not import and the repo does not exist, then tell the user to pip install it or download the repo.  

If repo exists but the build directory does not, then issue the build command in the tinycc repo.  

If it still doesn't import, then remove "--compiler=tinycc" from the command line and hope the user has MSVC installed or mingw32 install and distutils configured.

Migrated from http://trac.sasview.org/ticket/1211
```json
{
    "status": "new",
    "changetime": "2018-11-06T22:38:22",
    "_ts": "2018-11-06 22:38:22.989271+00:00",
    "description": "sasview 4.3 developer windows\n\nrun.py fails on windows if tinycc is not built.\n\nIf tinycc does not import and the repo does not exist, then tell the user to pip install it or download the repo.  \n\nIf repo exists but the build directory does not, then issue the build command in the tinycc repo.  \n\nIf it still doesn't import, then remove \"--compiler=tinycc\" from the command line and hope the user has MSVC installed or mingw32 install and distutils configured.\n",
    "reporter": "pkienzle",
    "cc": "",
    "resolution": "",
    "workpackage": "SasView Bug Fixing",
    "time": "2018-11-06T22:38:22",
    "component": "SasView",
    "summary": "run.py fails if tinycc isn't built (windows)",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.3.0",
    "owner": "",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
@pkienzle - where would such notes go? this is a developer issue? so on the wiki developer corner as part of the instructions on how to get system running? Personally I just comment that line out ... but have to remember to not commit that change back :-)

**Comment by butlerpd** [comment]
also believe this is best as a 5.x issue at this point. Am assuming the issue is the same for both branches? Moving to 5.1 for now

**Comment by butlerpd** [comment]
I believe this can be viewed as obsolete given all the work on streamlining the build process and the developer build documentation etc.
