### ISSUE TITLE
Bug in Iqxqy plotting non rectangular / square matrices? (Trac #1212)

### ISSUE THREAD

**Issue by ricleal** [SasView/sasview#1242]
My users are complaining about SASView giving negative Y Axis for the following dataset:
https://pastebin.com/raw/buBiU5JG

This is what sasviews gives:

[[Image(https://i.postimg.cc/R3TzMjSy/sasview.png)]]
[https://postimg.cc/R3TzMjSy]

This is what I get with Matplotlib:

[[Image(https://i.postimg.cc/nsxJfHJq/matplotlib.png)]]
[https://postimg.cc/nsxJfHJq]

This data is not a squared Maxtrix (looks more a sparse matrix):

```text

In [3]: data = np.genfromtxt(filepath, skip_header=2, names="qx, qy, iqxqy, err"
   ...: )

In [4]: qx, qy, iqxqy, err = data['qx'], data['qy'], data['iqxqy'], data['err']

In [5]: len(np.unique(qx))
Out[5]: 78

In [6]: len(np.unique(qy))
Out[6]: 94

In [7]: len(qx)
Out[7]: 6978

In [8]: len(qy)
Out[8]: 6978

In [9]: 78*94
Out[9]: 7332
```

Migrated from http://trac.sasview.org/ticket/1212
```json
{
    "status": "closed",
    "changetime": "2018-11-13T23:59:29",
    "_ts": "2018-11-13 23:59:29.784026+00:00",
    "description": "My users are complaining about SASView giving negative Y Axis for the following dataset:\nhttps://pastebin.com/raw/buBiU5JG\n\nThis is what sasviews gives:\n\n[[Image(https://i.postimg.cc/R3TzMjSy/sasview.png)]]\n[https://postimg.cc/R3TzMjSy]\n\nThis is what I get with Matplotlib:\n\n[[Image(https://i.postimg.cc/nsxJfHJq/matplotlib.png)]]\n[https://postimg.cc/nsxJfHJq]\n\nThis data is not a squared Maxtrix (looks more a sparse matrix):\n\n\n{{{\n\nIn [3]: data = np.genfromtxt(filepath, skip_header=2, names=\"qx, qy, iqxqy, err\"\n   ...: )\n\nIn [4]: qx, qy, iqxqy, err = data['qx'], data['qy'], data['iqxqy'], data['err']\n\nIn [5]: len(np.unique(qx))\nOut[5]: 78\n\nIn [6]: len(np.unique(qy))\nOut[6]: 94\n\nIn [7]: len(qx)\nOut[7]: 6978\n\nIn [8]: len(qy)\nOut[8]: 6978\n\nIn [9]: 78*94\nOut[9]: 7332\n}}}",
    "reporter": "ricardo",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2018-11-07T22:51:23",
    "component": "SasView",
    "summary": "Bug in Iqxqy plotting non rectangular / square matrices?",
    "priority": "major",
    "keywords": "plot",
    "milestone": "SasView 4.2.1",
    "owner": "ricardo",
    "type": "defect"
}
```

**Comment by ricleal** [comment]
Trac update at `2018/11/07 23:19:34`: **ricardo** changed summary from "Bug in Iqxqy plotting not non rectangular / square matrices?" to "Bug in Iqxqy plotting non rectangular / square matrices?"

**Comment by pkienzle** [comment]
Trac update at `2018/11/08 02:22:05`: **pkienzle** commented:

Confirmed the behaviour in current master.

The bug is in the assignment of qy values in the 2D data, not in the plotting.  Plotting uses equal axes.  Since the qx range of the displayed data is twice the qy range, the image appears horizontally stretched and vertically squashed.

The error is could be in the loader not preserving the qy values correctly, or in the conversion of the data into uniform steps in qx/qy, or most like to the final assignment of the qy axis to the 2D array.

**Comment by ricleal** [comment]
Trac update at `2018/11/08 17:09:15`: **ricardo** commented:

Just did some debugging.

The problem appears to be in `sas/sascalc/dataloader/file_reader_base_class.py` `FileReader::_remove_nans_in_data` (line 218).

Before calling this function (line 273) both `ymin` and `ymax` are good.

**Comment by pkienzle** [comment]
Trac update at `2018/11/09 15:40:39`: **pkienzle** commented:

Look at line 278:

   dataset.**Y**max = np.max(dataset.q**X**_data)

**Comment by ricleal** [comment]
Trac update at `2018/11/09 19:24:56`: 
* **ricardo** changed owner from "mathieu" to "ricardo"
* **ricardo** changed status from "new" to "assigned"

**Comment by ricleal** [comment]
Trac update at `2018/11/09 19:48:40`: **ricardo** commented:

Thanks @pkienzle!

Anyone can merge this?

https://github.com/SasView/sasview/pull/197

**Comment by pkienzle** [comment]
Trac update at `2018/11/13 21:17:43`: 
* **pkienzle** changed resolution from "" to "fixed"
* **pkienzle** changed status from "assigned" to "closed"

**Comment by butlerpd** [comment]
Trac update at `2018/11/13 23:59:29`: **butler** changed milestone from "SasView 4.3.0" to "SasView 4.2.1"
