### ISSUE TITLE
numpy/scipy cause syntax errors in python model builder (Trac #1218)

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#1247]
If the code in your simple python model contains numpy, np or scipy then it will cause a syntax error when you try to run the model. This is because the model builder does not include `\n` when it inserts the numpy import line.

Better would be to place the imports at the top of the template for all models instead of including it dynamically in the function definition. The model reload problems should be fixed, so this should now work.  This will make the code simpler, and we are relying on this fix already for the trig and exponential functions.

Instead of `from math import *`, we should use `from sasmodels.special import *` at the top of the template.  This will define the same set of functions that are available to C models, including functions such as sas_erf, etc, constants such as M_PI and the gaussian quadrature weights for 20, 76 and 150 point quadrature.  It also defines the `np` symbol in case any thing else is needed.

Migrated from http://trac.sasview.org/ticket/1218
```json
{
    "status": "assigned",
    "changetime": "2018-12-12T03:01:22",
    "_ts": "2018-12-12 03:01:22.193668+00:00",
    "description": "If the code in your simple python model contains numpy, np or scipy then it will cause a syntax error when you try to run the model. This is because the model builder does not include `\\n` when it inserts the numpy import line.\n\nBetter would be to place the imports at the top of the template for all models instead of including it dynamically in the function definition. The model reload problems should be fixed, so this should now work.  This will make the code simpler, and we are relying on this fix already for the trig and exponential functions.\n\nInstead of `from math import *`, we should use `from sasmodels.special import *` at the top of the template.  This will define the same set of functions that are available to C models, including functions such as sas_erf, etc, constants such as M_PI and the gaussian quadrature weights for 20, 76 and 150 point quadrature.  It also defines the `np` symbol in case any thing else is needed.",
    "reporter": "pkienzle",
    "cc": "",
    "resolution": "",
    "workpackage": "SasView Bug Fixing",
    "time": "2018-11-16T23:39:31",
    "component": "SasView",
    "summary": "numpy/scipy cause syntax errors in python model builder",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.3.0",
    "owner": "piotr",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2018/11/17 00:10:30`: 
* **butler** commented:

should be trivial enough to fix so would be nice to do.


* **butler** changed milestone from "SasView 4.3.0" to "SasView 4.2.1"

**Comment by butlerpd** [comment]
Trac update at `2018/11/27 14:39:18`: 
* **butler** changed owner from "" to "piotr"
* **butler** changed status from "new" to "assigned"

**Comment by rozyczko** [comment]
Trac update at `2018/11/28 08:59:01`: **piotr** commented:

It appears I already had "\n" added to relevant lines in the Qt version.
The ''sasmodels'' import may be superior but it is hiding information from the user - what are we actually importing? At least with the ''math'' module the user knows exactly what the namespace is.

**Comment by rozyczko** [comment]
Trac update at `2018/11/28 09:21:24`: 
* **piotr** changed _comment0 from "Added the newline characters." to "1543397096302126"
* **piotr** commented:

Added the newline characters. Pull request #348

**Comment by pkienzle** [comment]
Trac update at `2018/11/28 15:06:07`: **pkienzle** commented:

The namespace is documented in the sasmodels manual.

I suggest renaming the ticket: "Make the opencl special function library available to python models".

Maybe add that the template builder should be moved to sascalc rather than living in the GUI tree, or maybe make that a new ticket.

**Comment by butlerpd** [comment]
Trac update at `2018/12/12 03:01:03`: **butler** commented:

Could this not be fixed by just adding a comment line before the import statement explaining what is being imported? The user writing a plugin doesn't see any of this anyway so should not matter?

Replying to [comment:3 piotr]:
> It appears I already had "\n" added to relevant lines in the Qt version.
> The ''sasmodels'' import may be superior but it is hiding information from the user - what are we actually importing? At least with the ''math'' module the user knows exactly what the namespace is.
> 
>

**Comment by butlerpd** [comment]
Trac update at `2018/12/12 03:01:22`: **butler** changed milestone from "SasView 4.2.1" to "SasView 4.3.0"

**Comment by rozyczko** [comment]
Addressed in ESS_GUI
