### ISSUE TITLE
Expand permitted range of transformed data in Corfunc implementation (Trac #1223)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1252]
User Sam Welborn (UPenn) notes that at present the correlation function analysis doesn't permit the viewing or output of the transforms beyond x=200 Ang, which implies you have no features-of-interest in the scattering at Q<0.032 Ang^-1^. This limit was inherited from the original Corfunc program and suited the requirements (and computational resources at the time) of those that developed it. But with hindsight it now restricts the applicability and usefulness of this functionality in !SasView. Sam's data (attached) has a feature at ~600 Ang, for example.

I suggest a two-step approach:

1) Raise the hard=coded output limit to 1000 Ang: as this ''should'' be trivial I've made it a blocker for the 4.2.1 release;

2) In !SasView 5, consider adding editable input boxes to the correlation function GUIs to allow the user to define the transform limit (currently set to 100 x Qmax) and the display range discussed above.

Migrated from http://trac.sasview.org/ticket/1223
```json
{
    "status": "closed",
    "changetime": "2019-01-23T16:09:09",
    "_ts": "2019-01-23 16:09:09.849898+00:00",
    "description": "User Sam Welborn (UPenn) notes that at present the correlation function analysis doesn't permit the viewing or output of the transforms beyond x=200 Ang, which implies you have no features-of-interest in the scattering at Q<0.032 Ang^-1^. This limit was inherited from the original Corfunc program and suited the requirements (and computational resources at the time) of those that developed it. But with hindsight it now restricts the applicability and usefulness of this functionality in !SasView. Sam's data (attached) has a feature at ~600 Ang, for example.\n\nI suggest a two-step approach:\n\n1) Raise the hard=coded output limit to 1000 Ang: as this ''should'' be trivial I've made it a blocker for the 4.2.1 release;\n\n2) In !SasView 5, consider adding editable input boxes to the correlation function GUIs to allow the user to define the transform limit (currently set to 100 x Qmax) and the display range discussed above.",
    "reporter": "smk78",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView GUI Enhancements",
    "time": "2019-01-21T15:00:01",
    "component": "SasView",
    "summary": "Expand permitted range of transformed data in Corfunc implementation",
    "priority": "blocker",
    "keywords": "",
    "milestone": "SasView 4.2.1",
    "owner": "awashington",
    "type": "enhancement"
}
```

**Comment by smk78** [comment]
Trac update at `2019/01/21 15:00:45`: 
* **smk78** changed attachment from "" to "for_horizons_real.txt"
* **smk78** commented:

Example data from Sam Welborn

**Comment by butlerpd** [comment]
Trac update at `2019/01/21 15:06:16`: **butler** commented:

I have never looked at this part of the code base, but assume that by trivial is meant a single line edit? though I guess it will need testing?  One question however: Are we sure the limit is due to computational/use case needs and that there is no inherent limitation of the method or maths that invalidates it beyond a certain length scale?

**Comment by smk78** [comment]
Trac update at `2019/01/21 15:20:04`: **smk78** commented:

I believe that it is straightforward, though it would be good to get Adam's take.

I'm not aware of any inherent limitation, at least, not at the length scales we are talking about here. The !Qmax/Xmin end has a limit, of course, which is technically infinity and zero respectively, but which for practical purposes is limited to be a typical bond length. But going the other way...

**Comment by rprospero** [comment]
Trac update at `2019/01/23 09:48:45`: **awashington** commented:

I've submitted pr 204, which increases the bounds to a micron (640k out to be enough for anybody).  We'll still need to make this customizable in version 5.0, but there's no reason to start changing the wx gui this late in the game, especially on a minor point release.

**Comment by smk78** [comment]
Trac update at `2019/01/23 16:06:20`: **smk78** commented:

Cloned branch, built and tested on W64. Does what it says on the tin! Closes #1252

**Comment by smk78** [comment]
Trac update at `2019/01/23 16:08:53`: 
* **smk78** changed owner from "" to "awashington"
* **smk78** changed status from "new" to "assigned"

**Comment by smk78** [comment]
Trac update at `2019/01/23 16:09:09`: 
* **smk78** changed resolution from "" to "fixed"
* **smk78** changed status from "assigned" to "closed"
