### ISSUE TITLE
Problem reopening saved project .svs file (Trac #1243)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1269]
User Kilian Frank reports:

```text
I have a technical issue with the "Open Project" function. I saved an .svs file 
containing a single dataset, custom model and fit with SasView 4.2.1. Now I try 
to open it on the same machine a day later with the same SasView and get the 
error message

2019-03-08 10:40:21 : DataLoader Error: Encounted Non-ASCII character ('Reader' 
object has no attribute 'sort_one_d_data')

Is there any way I can get get back my project (e.g. by manually fixing the Non-
ASCII character in the file) and what should I avoid when saving my projects in 
the future to prevent this from happening?
```

Migrated from http://trac.sasview.org/ticket/1243
```json
{
    "status": "assigned",
    "changetime": "2019-03-19T02:49:00",
    "_ts": "2019-03-19 02:49:00.992026+00:00",
    "description": "User Kilian Frank reports:\n\n{{{\nI have a technical issue with the \"Open Project\" function. I saved an .svs file \ncontaining a single dataset, custom model and fit with SasView 4.2.1. Now I try \nto open it on the same machine a day later with the same SasView and get the \nerror message\n\n2019-03-08 10:40:21 : DataLoader Error: Encounted Non-ASCII character ('Reader' \nobject has no attribute 'sort_one_d_data')\n\nIs there any way I can get get back my project (e.g. by manually fixing the Non-\nASCII character in the file) and what should I avoid when saving my projects in \nthe future to prevent this from happening?\n}}}\n",
    "reporter": "smk78",
    "cc": "",
    "resolution": "",
    "workpackage": "SasView Bug Fixing",
    "time": "2019-03-08T16:56:00",
    "component": "SasView",
    "summary": "Problem reopening saved project .svs file",
    "priority": "blocker",
    "keywords": "",
    "milestone": "SasView 4.2.2",
    "owner": "krzywon",
    "type": "defect"
}
```

**Comment by smk78** [comment]
Trac update at `2019/03/08 16:56:29`: 
* **smk78** changed owner from "" to "krzywon"
* **smk78** changed status from "new" to "assigned"

**Comment by smk78** [comment]
Trac update at `2019/03/08 16:58:11`: **smk78** commented:

Update:

There were no non-UTF8 characters in the filenames, only underscores.

File path is:

```text
/IRP/AG_Salditt/Messzeiten/2018/extern/ESRF_SC4755_ID02/Analysis/Kilian/PLs_fusion/
anisotropic_fits/22_six_shell_model_SasView/plate2_016_sub.svs
```

**Comment by smk78** [comment]
Trac update at `2019/03/08 16:58:51`: **smk78** commented:

@butlerpd has the offending project file.

**Comment by butlerpd** [comment]
Trac update at `2019/03/08 17:11:30`: 
* **butler** changed attachment from "" to "plate2_016_sub.svs"
* **butler** commented:

Offending project file

**Comment by butlerpd** [comment]
Trac update at `2019/03/08 17:12:11`: 
* **butler** changed attachment from "" to "six_shells_01.py"
* **butler** commented:

Python part of model used in project file

**Comment by butlerpd** [comment]
Trac update at `2019/03/08 17:12:49`: 
* **butler** changed attachment from "" to "six_shells_01.c"
* **butler** commented:

c part of model used in project file

**Comment by butlerpd** [comment]
Trac update at `2019/03/08 17:13:30`: **butler** commented:

I will attache the file and model files.  I can confirm that I got the same error when trying to read the .svs file.  The xml looks straigthforward to me. User should be able to recover the parameters they used fairly easily manually - but the question is why did it happen?

**Comment by butlerpd** [comment]
Trac update at `2019/03/19 02:49:00`: **butler** changed milestone from "SasView 4.3.0" to "SasView 4.2.2"
