### ISSUE TITLE
Migration from Trac to GitHub issues (Trac #1255)

### ISSUE THREAD

**Issue by ajj** [SasView/sasview#1278]
Make and execute plan to move from using trac to using GitHub issues to better integrate tickets with commits and reviews.

Migrated from http://trac.sasview.org/ticket/1255
```json
{
    "status": "assigned",
    "changetime": "2019-03-26T10:18:40",
    "_ts": "2019-03-26 10:18:40.334179+00:00",
    "description": "Make and execute plan to move from using trac to using GitHub issues to better integrate tickets with commits and reviews.",
    "reporter": "ajj",
    "cc": "",
    "resolution": "",
    "workpackage": "Support Infrastructure",
    "time": "2019-03-24T17:38:34",
    "component": "SasView",
    "summary": "Migration from Trac to GitHub issues",
    "priority": "major",
    "keywords": "",
    "milestone": "Admin Tasks",
    "owner": "ricardo",
    "type": "enhancement"
}
```

**Comment by ajj** [comment]
Trac update at `2019/03/24 17:39:21`: **ajj** commented:

Notes from Jeff K:

I've had the same thought recently. So much so, that I went searching for utilities and info on how to do it.

Github recently released an API for this express purpose. https://gist.github.com/jonmagic/5282384165e0f86ef105 - The API allows for

Otherwise, there are other utilities available:
https://github.com/robertoschwald/migrate-trac-issues-to-github - This is a simple, scripted migration tool. Pros: simple to use, direct conversion. Cons: No linking trac login names to github login names, emails are sent for every issue (ugh).
https://github.com/XhmikosR/migrate-trac-issues-to-github - Forked from the same source as the first option, but allows for config files for user names.
https://github.com/tfoote/github-migrate-trac-tickets - One more forked from the same originator, probably the most configurable.
https://github.com/mavam/trac-hub - Uses the GitHub API, but streamlines the process. Pros: Configurable, including custom label mapping, linking trac to github users, etc. No emails sent. Infinitely configurable. Atomic, so no possibility of exterior interruptions. Cons: A bit slower than the above because the API sets purposeful speed limits on issue migration. Infinitely configurable.

Of the options I've found, The last one in my list (mavam/trac-hub) seems like the best option, mostly because it uses the pre-existing API set by GitHub, so emails aren't sent on ticket creation, and linking trac->github is much more configurable, not only for user names, but also for milestones, work packages, and priority.

**Comment by ricleal** [comment]
Trac update at `2019/03/25 14:14:15`: **ricardo** commented:

I'm playing with this and the github part is OK. However the Trac part using !`xmlrpc` is not. It looks like RPC uses port 135 which is blocked for us at the ILL... more news soon.

**Comment by ajj** [comment]
Trac update at `2019/03/26 10:18:40`: 
* **ajj** changed owner from "ajj" to "ricardo"
* **ajj** changed status from "new" to "assigned"

**Comment by ricleal** [comment]
Done
------------------------------------
Migration of TRAC tickets to GitHub finished. Sorry about the emails… Github fires an email every time a ticked is assigned to you.
Ticket creation in TRAC is **frozen**.
Please create new tickets (now called issues) in the appropriate GitHub repo according to the project:
- SasView
- SasModels
- SasModelMarketplace

You can reference tickets from another repo as: `SasView/<repo name>#<issue number>` or change sets `SasView/<repo name>@<SHA>`, e.g.: `SasView/sasview#1286` or `SasView/sasview@9305b463663a5933a89dce367a0dc29fc9d712e8`

If you find any issues let me know!
