### ISSUE TITLE
Migration from trac wiki to GitHub wiki (Trac #1256)

### ISSUE THREAD

**Issue by ajj** [SasView/sasview#1279]
Create and execute plan to move wiki pages to GitHub. 

Migrated from http://trac.sasview.org/ticket/1256
```json
{
    "status": "assigned",
    "changetime": "2019-03-26T10:19:26",
    "_ts": "2019-03-26 10:19:26.443155+00:00",
    "description": "Create and execute plan to move wiki pages to GitHub. ",
    "reporter": "ajj",
    "cc": "",
    "resolution": "",
    "workpackage": "Support Infrastructure",
    "time": "2019-03-24T17:41:20",
    "component": "SasView",
    "summary": "Migration from trac wiki to GitHub wiki",
    "priority": "major",
    "keywords": "",
    "milestone": "Admin Tasks",
    "owner": "ricardo",
    "type": "task"
}
```

**Comment by ajj** [comment]
Trac update at `2019/03/26 10:19:26`: 
* **ajj** changed owner from "ajj" to "ricardo"
* **ajj** changed status from "new" to "assigned"

**Comment by ricleal** [comment]
All the automatic migration should be done.
To check if there are some inconsistency in the migration:
Links pointing to:
- trac wiki should be pointing to GH wiki
- trac ticket number should be pointing to GH issue

**Comment by pkienzle** [comment]
Links to tickets not working.  See for example [CodeCampIX](https://github.com/SasView/sasview/wiki/CodeCampIX).

Trac is using a query to find the tickets on this page.  You might be able to do something similar using filtering on github issues [1]

Need to change ticket references from /ticket/#.  Stackoverflow answer [2] is to use ../issues/# instead.  However, this doesn't work from wiki preview, so use /SasView/sasview/issues/#.  

Also note that some tickets were moved to /SasView/sasmodels/issues/#.

[1] https://help.github.com/en/articles/searching-issues-and-pull-requests#search-by-when-an-issue-or-pull-request-was-created-or-last-updated

[2] https://stackoverflow.com/questions/20097938/github-linking-to-an-issue-from-a-wiki-page

**Comment by ricleal** [comment]
Thanks @pkienzle !
The script didn't get this links: `<a href="/ticket/1259" title="View ticket">#1259</a>`... It was looking for  `<a href="trac.sasview.org/ticket/1259"...`.
It should be fixed now.

**Comment by ricleal** [comment]
Attachements and images migrated. See for example: https://github.com/SasView/sasview/wiki/Tutorials_KU_SAS
More testing needed to find problems.

**Comment by ricleal** [comment]
Anchors that **point to the titles in trac** should be working now.

See for example:
https://github.com/SasView/sasview/wiki/Tutorials_KU_SAS#3-Fitting-SANS-data

**Comment by pkienzle** [comment]
First few links on the example page failed (Introduction, 1. Familiarisation with SasView, 2. ...) because they used underline heading style rather than leading hash marks.  Perhaps want to clean those up by hand rather than trying to automate?

**Comment by ricleal** [comment]
This was a "dirty" job just to fix one more thing. I will do my best to fix more stuff in my free time...

**Comment by ajj** [comment]
Work by @ricleal is complete. Need a clean up pass still on wiki. But in another issue.
