### ISSUE TITLE
Default parameters for RPA model are generating an invalid example plot (Trac #1261)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1283]
The default parameters for the RPA model are generating an invalid example 1D plot in the model documentation.

Migrated from http://trac.sasview.org/ticket/1261
```json
{
    "status": "closed",
    "changetime": "2019-03-27T12:43:36",
    "_ts": "2019-03-27 12:43:36.496431+00:00",
    "description": "The default parameters for the RPA model are generating an invalid example 1D plot in the model documentation.",
    "reporter": "smk78",
    "cc": "",
    "resolution": "duplicate",
    "workpackage": "SasView Bug Fixing",
    "time": "2019-03-26T13:57:01",
    "component": "SasView",
    "summary": "Default parameters for RPA model are generating an invalid example plot",
    "priority": "blocker",
    "keywords": "",
    "milestone": "SasView 4.2.2",
    "owner": "",
    "type": "defect"
}
```

**Comment by smk78** [comment]
Trac update at `2019/03/26 13:57:38`: 
* **smk78** changed attachment from "" to "rpa-plot-release.png"
* **smk78** commented:

RPA 1D example plot 4.2.1

**Comment by smk78** [comment]
Trac update at `2019/03/26 13:58:06`: 
* **smk78** changed attachment from "" to "rpa-plot-master-build.png"
* **smk78** commented:

RPA 1D example plot 4.2.2 Master

**Comment by butlerpd** [comment]
Trac update at `2019/03/26 19:57:01`: **butler** commented:

Is this a duplicate of http://trac.sasview.org/ticket/871?

**Comment by smk78** [comment]
Trac update at `2019/03/27 12:43:18`: **smk78** commented:

It would seem so! :-) My bad. Closing this one.

**Comment by smk78** [comment]
Trac update at `2019/03/27 12:43:36`: 
* **smk78** changed resolution from "" to "duplicate"
* **smk78** changed status from "new" to "closed"
