### ISSUE TITLE
Cannot model Sesans Data in 5.0 gui

### ISSUE THREAD

**Issue by rprospero** [SasView/sasview#1293]
Process:

Load any SESANS file
Send the dataset to fitting
Pick any model
Plot the data and the model
Observe that the model appears as a flat line

The 5.0 GUI does not seem to perform the Hankel transform on the model before plotting it, resulting in a mixture of q-space and real space data.

**Comment by rprospero** [comment]
I've confirmed that the model isn't being transformed.  There are two factors at play here.  First, the current code assumes that data with no uncertainty on the x coordinate cannot be transformed, but that does not apply to SESANS data.  Secondly, the SESANS data is no longer automatically having the transform applied and a smearing must be manually applied in the GUI.

I've found a solution to the first issue and am working on the second.

**Comment by rozyczko** [comment]
Any chance of having this addressed this week, before 5.0 gets released on Monday?

**Comment by butlerpd** [comment]
I think the comment in #1363 was meant to close this ticket but did not.  Can we close it?

**Comment by wimbouwman** [comment]
I have just tested it with old Delft-data. There the new version works! I am very happy.

It would be good to test it also with some recent ISIS-data. Adam, could you also test it or send me a recent ISIS-file?
Best, Wim

**Comment by wimbouwman** [comment]
It works for both ISIS and Delft measurements. It can be closed.
