### ISSUE TITLE
save project error not being shown in GUI

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#1297]
SasView 4.x GUI

Seeing the following on the console when trying to save a project with no data selected, but otherwise it is silently failing.
```
19:05:30 - WARNING : sas.sasgui.guiframe.gui_manager:1950: Error occurred while saving the project: To save, at least one application panel should have a data set and model selected. No project was saved to /Users/pkienzle/Downloads/_PS2.svs
```

**Comment by krzywon** [comment]
This might actually be a bigger than just not displaying the error. The latest build on PR #210 has nothing output to the console log which is tied to warnings and errors being displayed. The errors and logging to sasview.log are still occurring.

**Comment by krzywon** [comment]
I've been doing some analysis and there is some inconsistent behavior in the PR builds.

PR 210 - build 78 - https://jenkins.esss.dk/sasview/job/SasView_Win7_64bit_PullRequest/78/ - Nothing in the console log - The codes changes were extra logging and a try catch block.
PR 210 - build 79 - https://jenkins.esss.dk/sasview/job/SasView_Win7_64bit_PullRequest/79/ - Console logging 100% working. - Change iterator to list to prevent RuntimeErrors.
PR 210 - build 80 - https://jenkins.esss.dk/sasview/job/SasView_Win7_64bit_PullRequest/80/ - Nothing in console log (again) - Merged branch 'release-4.2.2' into ticket-1243

I am running a diff on the console outputs from each of the builds to see what is missing and will update if I find more information.

**Comment by butlerpd** [comment]
@krzywon am guessing this is related to issue #1411 ?If so can we just close this one and move relevant comments over to #1411 (which is much broader than this one?)

**Comment by krzywon** [comment]
@butlerpd you are correct. Closing this now.
