### ISSUE TITLE
Store numpy arrays as lists in saved project json files

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#1306]
The following is a saved project with core, drop & shell microemuslions contrasts, and polydispersity on some of the radii.   Rename .txt to .json.
[3sets_5constraints_polydisp_json.txt](https://github.com/SasView/sasview/files/3084467/3sets_5constraints_polydisp_json.txt)

Looking through the file, there are items marked as type __ndarray__ which have a numpy binary save format.

If these data were instead saved as JSON lists of numbers then you could process the data using a variety of JSON tools and languages rather than specifically python with numpy.

**Comment by rozyczko** [comment]
Addressed. Rather than binary numpy arrays are now saved as lists, then recreated accordingly.

**Comment by rozyczko** [comment]
This, however, means that the old 5.0 project saves arent compatible with this change.
It is OK, as we haven't released yet but I might spend some time on adding backward compatibility so beta users don't get overly annoyed.

**Comment by rozyczko** [comment]
tested/reviewed locally
