### ISSUE TITLE
5.0 radius_effective choice - initialisation issue?

### ISSUE THREAD

**Issue by RichardHeenan** [SasView/sasview#1308]
In local build of 5.0.  Had loaded the AOT microemulsion shell contrast, was then fitting e.g. core_shell_sphere times hardsphere, or sphere times squarewell, with radius & scale fitting, comparing against 4.2 running separately on my laptop (4.2 only gives the constrained results, unless you use a plugin model).

Though the radius_effective drop down in 5.0 was showing "unconstrained" a fit of scale & radius gave the results for "constrained". Changing the drop down to "constrained", doing a fit, then back to "unconstrained" got it working, so there seems perhaps to be an initialisation issue here?

To be more compatible with 4.2, perhaps the default choice for radius_effective should actually be the second on the list (value 1) not the unconstrained (value 0) ?

[Are there any other menus where initialisation in the gui is not as we might expect?]

**Comment by rozyczko** [comment]
<structure_factor_mode> from sasmodels contains property 'default', which needs to be applied to the combobox displayed in SasView. it wasn't, so the original mapping between displayed value and what was in the model was not present. 
Fixed.

**Comment by RichardHeenan** [comment]
Have tested on my local build of 5.0, is working now, so closing issue.
