### ISSUE TITLE
v5.0 scale change doesn't work

### ISSUE THREAD

**Issue by mdoucet** [SasView/sasview#1326]
Once a model and/or data is plotted, right clicking to select "Change scale" properly pops up the scaling option dialog. Once you select a scale and click to confirm your choice, nothing happens.

**Comment by rozyczko** [comment]
This was an issue with 5.0 beta 2, got fixed a while ago. If you see this behaviour with a recent build, please reopen and let me know the build date and steps to reproduce the failure.

**Comment by mdoucet** [comment]
I tested this with the ESS_GUI branch a day before opening the ticket. Can you double check that it works for you before closing it?

**Comment by rozyczko** [comment]
I have double checked and it did work locally. Can you please let me know which scale (x and y) didn't work as expected, which plot (model, data, residual) and possibly the steps to reproduce?
Thanks!

**Comment by mdoucet** [comment]
OK I tested it again and it now works. I must have gotten it in a weird state but I can't reproduce it at the moment.
