### ISSUE TITLE
v5.0 Residual plots are annoying

### ISSUE THREAD

**Issue by mdoucet** [SasView/sasview#1328]
When fitting, there is no convenient way to avoid having the residual plot pop up.

- Closing the residual window will only ensure that it pops up again next time.
- The only viable option is to make it very small and move it in a corner.

Maybe this should be an option. Or there should be a button that pops it up on demand. It's very rare that the first thing you want to see is the residual plot... I would say that most users are happy simply having the data and model together on one plot.

**Comment by rozyczko** [comment]
copy of https://github.com/SasView/sasview/issues/268 (trac issue #40, from way back)

**Comment by lucas-wilkins** [comment]
closing as duplicate
