### ISSUE TITLE
Meaningless error values on Theory and Normalised Residuals

### ISSUE THREAD

**Issue by RichardHeenan** [SasView/sasview#1329]
There is a long standing issue, from at least as far back as Sasview 3

The error values associated with both Theory and Normalised Residual workspaces are all set to 1.0  (This is the dY column in "show info" on a workspace array.)

It happens that the statistical error on the Normalised residual for the default "Use dI" weighting scheme should actually be 1.0 (see below), but I suspect that all these errors are simply being set to 1.0 by default?

Discussion needed please by SAS experts as to what we should do here.

Regarding the Theory workspace - we could attempt to propagate error estimates from the errors on the fit parameters. We could simply not store and save any error value at all.

Regarding the Normalised Residuals - We minimise chi2=sum{ ( (I-C)/W )^2 }, the "normalised residual" is R = (I-C)/W where I is data, C is calculated, and W the weight for each data point.

Default is weight W = dI the error on data I, thus R = (I+-dI)/dI - C/dI, so error on normalised residual, dR = 1

If W=1 (the "none" option), dR = dI

If W=sqrt(I) then dR = dI /sqrt(I),  with the usual headache if I=0

If W =I then dR = dI/I,  with the usual headache if I=0

**Comment by butlerpd** [comment]
Thanks @RichardHeenan. Was on my radar to look at.  Will add to this issue when I have done so.

**Comment by butlerpd** [comment]
Clearly I never really thought much about those error bars on the residuals -- On the other hand I was not even aware that theory calculations generated an error bar!  Thinking about it neither make sense: Theory, by definition, has no uncertainty and normalized residuals **are** the uncertainty... what does "uncertainty on the uncertainty" even mean?  Well I guess we could wax philosophical on that one, but doubt anything we are doing or likely to be able to do would be that.

I have tried to look up normalized residuals but cannot find **anyone** who talks about errors on the residuals.  Instead you should be checking that the distribution of residuals stays within +/- 3 (and that 68% of your points should be withing +/- 1) of zero.  This is also what is described in the docs (our docs say nothing about uncertainty on the residuals).  Can anybody find a reference to what uncertainty on residuals means and why we should be using them?

As for theory, it only really makes sense if you add some statistical information.  I guess that **IF** we have a fit (not always the case) we could try to use the uncertainty on the data (either directly or using the resulting parameter uncertainties) but that doesn't make much sense to me... what would the point be?  It would be useful of course after the theory is run through a MC program like McStass for an instrument as a predictive tool of the noise one gets with an X min measurement at a Y neutron flux  but that is not here. Can anybody think of any reason why this should be a thing?

My guess is that somewhere the intrinsic 1D plottable has to have those 3 columns? or did at one time?  I did find a line in Fitting.py (line 2181 in 4.2.2. version of the code) where the residuals.err_data are set to one but not where that gets used.

My feeling is that we should get rid of these from the plot at least ... preferably from the plottable object? itself?

**Comment by butlerpd** [comment]
also ... normalized residuals would be the residual divided by the square root of the variance (i.e. standard deviation).  While there may be reasons to use other weighting schemes to prevent for example too much weight being put on oversampled data, I'm not sure that dividing by anything other than sigma has any mathematical meaning?

**Comment by butlerpd** [comment]
Final comment regarding residuals:
Indeed it is using the data1D object to plot which has a x, y, dy, "dx" column  dy is set to none for residuals while dy is set to one.  I recommend we fix that for release 5.0 (and 4.3 ... should we for 4.2.2?) with the following two lines in fitting.py (I have tested this for the data1D):
for data2D replace
`2181    residuals.err_data = np.ones(len(residuals.data))`
with
`2181    residuals.err_data = None`

Likewise for data1D replace
`2217    residuals.dy = np.ones(len(residuals.data))`
with
`2217    residuals.dy = None`

**NOTE:**
This calculation is all happening in the GUI ... as is the reported chi^2 from what I can tell.  This should in fact be done in sascalc instead.  For 5.1 we should be moving this code over I think.

**Comment by butlerpd** [comment]
Regarding theory -- it is of course a data1D or data2D object.  Thus for data1D it always includes x,y, dy, "dx"  However, in 4.2.2 dy for theory always seems to be set to none (i.e. zeroes).  This is I think the right answers.  Is the theory dy being set to 1 a 5.0 "feature" or require some permutation I am missing?

**Comment by butlerpd** [comment]
I think the first part (dy=1 for theory curves) has been fixed before 5.0.4. However the residual plot issue remains.  Besides the fix recommended above the residual plot should include (dotted maybe?) lines at -1 and +1 and maybe another (solid? red?) at -3 and +3 to indicate 68% and 95% confidence bands.  This should be a very good first issue

**Comment by drowssap61** [comment]
test comment.

**Comment by drowssap61** [comment]
I see, might also be worth perhaps calculating how many points lie between -1 and 1, and -3 and 3 for example as a check for the user.  But can start with above^^^

**Comment by drowssap61** [comment]
Note:  Line 2217 butlerpd refers to above in fitting.py is located in file: FittingUtilities.py (sasview\src\sas\qtgui\Perspectives\Fitting), Line 545

**Comment by butlerpd** [comment]
Indeed -- Good find @drowssap61 apparently some significant changes in that part of the code between 4.x and 5.x!

**Comment by butlerpd** [comment]
actually this issue was only partly fixed in PR #2354 in that the meaningless error bars were removed. However, the part about replacing them with +/- 1 and 3 sigma lines on the plot was not done. I am therefore re-opening this for now
