### ISSUE TITLE
Issue Closing and Reopening Fit Plots

### ISSUE THREAD

**Issue by krzywon** [SasView/sasview#1336]
When a fit plot is closed and then reopened using 'Show Plot' without closing the residuals plot, the new fit plot has no data associated with it. If both the fit and residuals plots are closed, the plotting works as expected. If only the residuals plot is closed and not the fit plot, the new residuals plot opens as expected.

This was just tested using the latest state of the ESS_GUI branch, run from source on Win10 using an anaconda environment built using the conda_qt5_win.yml file.

**Comment by rozyczko** [comment]
it's reproducible and utterly annoying. Just spent 2 days trying to find the problem and will continue doing so after the release.

**Comment by rozyczko** [comment]
Fixed. It seems.

**Comment by rozyczko** [comment]
Please review

**Comment by krzywon** [comment]
I just tested the functionality after pulling the most recent ESS_GUI and the fit plotting issue looks to be fixed. All plots reopen regardless of which plots are currently opened.
