### ISSUE TITLE
Slicer options are too limiting

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#1344]
Slicers currently always require symmetric + and -  Q and then average the + and - sides.  The first is not helpful in any case (though perhaps makes the data "folding" easier?). However there are a number of circumstances where you would want to see the two sides separately (think Couette tangential measurements or grazing incidence etc.).

Ultimately it would be nice to define arbitrary vertical and horizontal slices (not through zero).

NOTE:  For the "folding" part of the problem, the code seems to already be set up to do this using a flag: self.fold.  Currently this is set to TRUE.  making this settable by the user is all that is needed.  Then for the Gui add a checkbox to go from True to False?

NOTE2: this all seems to reside in sasgui a the moment and should probably be moved to sascalc.

**Comment by krzywon** [comment]
This might be fixed from a computational standpoint, where fold no longer must be True, but is this implemented on the GUI side?

**Comment by butlerpd** [comment]
Oops -- This should have been closed with the slicer PR merge. everything requested and more have been addressed there.
