### ISSUE TITLE
Slicer bug when Q=zero is not part of the data

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#1346]
This is related to issue #1344 in that if x and y are so asymmetric that Q=(0,0) is way out of the data window, the slicer fails completely -- to the point that even the `edit slicer parameter` option does not appear in the dropdown.  This is true for 4.2.2 and believe it is also true for 5.

**Comment by jack-rooks** [comment]
Confirmed fixed with PR #1919 and sasdata PR [#61](https://github.com/SasView/sasdata/pull/61)

**Comment by krzywon** [comment]
Fixed in release_6.0.0 branch. Closing
