### ISSUE TITLE
Version 5 permissions

### ISSUE THREAD

**Issue by ricleal** [SasView/sasview#1348]
When installing from fresh SASView version 5, MAC OS doesn't install it (not even going to settings security). The same does not happen with version 4.2.2. When going to Settings->Permissions one can install it.

**Comment by wpotrzebowski** [comment]
@ricleal: Does the right click also work? I know It is annoying with the entire Gatekeeper business.  Our app is signed with Apple Developer ID but it still need to be packaged in the way Xcode does. I've been trying to resolve it but the progress is slow... It is surprising that 4.2.2 works without a problem. 4.2.2 is not signed at all...

**Comment by ricleal** [comment]
@mdoucet manage to install it (I think he did the right click thing...).
For 4.2.2 we didn't hear any complains so 'i guess everything went smoothly.

**Comment by wpotrzebowski** [comment]
It should be fixed now because I eventually managed to sign it properly. @ricleal or @mdoucet: you may want to try out the latest build: https://jenkins.esss.dk/sasview-beta/job/SasView-OSX1013/604/
