### ISSUE TITLE
Drag Boundary Bars in Corfunc for 5.0

### ISSUE THREAD

**Issue by rprospero** [SasView/sasview#1353]
Version 4 of Sasview allowed the user to control the boundaries of the corfunc extrapolation by dragging the marker lines.  This currently isn't supported in 5.0, due to the change in the graphics toolkit.  Instead, the users are instructed to input the q values in the text boxes.

The ability to drag the lines should be reimplemented.

**Comment by smk78** [comment]
In 5.0.2 the range bars are draggable and link to the Q-range boxes so am closing this ticket.
