### ISSUE TITLE
SasView 5.0 Data with negative values no showing on linear scale

### ISSUE THREAD

**Issue by markzic** [SasView/sasview#1361]
When plotting data that has negative values, the plot is initially in log vs. log scale. This does not plot negative values, as usual. However, when changing the plot to linear scale, the negative data points still do not show up. This makes fittings look deceptive.

![image](https://user-images.githubusercontent.com/22228089/60535908-225c0800-9cd3-11e9-841d-9473494a9e6f.png)
[pol_files209-214_circ_1p7K_4T_rot.txt](https://github.com/SasView/sasview/files/3351742/pol_files209-214_circ_1p7K_4T_rot.txt)

**Comment by rozyczko** [comment]
1. Loaded the included file in SasView
2. Created new data plot
3. The plot is log/log and looks like the one attached to the report above
4. Changed scale to linear x/ linear y
5. All points, including negative values, are shown
![Untitled](https://user-images.githubusercontent.com/8266281/60875121-89307280-a239-11e9-9403-72763bcb84ce.png)
6. Switched to log/log and back to linear/linear
7. All points are shown

Can you please let me know if you see a different behaviour? If so, please describe steps required to reproduce the issue.
Thanks

**Comment by rozyczko** [comment]
OK. I can reproduce the issue for the combined data/model plot. Will fix for 5.0.1

**Comment by rprospero** [comment]
I've run into this as well on the SESANS side (since all of our data is negative and plotted in linear space).  I've fixed it as part of a large commit.  I'll see if I can pull it out and turn it into a PR.

**Comment by rprospero** [comment]
Unfortunately, as I've found that the SESANS problems came from a different route, so I don't have an easy fix for you on the negative values.  I apologize if I got your hopes up.
