### ISSUE TITLE
Cannot install DMG for SasView 5.0.0

### ISSUE THREAD

**Issue by martintb** [SasView/sasview#1377]
I get the following error when I try to install the beta version of v5.0 on MacOS 10.14.6 (Mojave)

![image](https://user-images.githubusercontent.com/6588826/63471876-74511c80-c43e-11e9-9d61-d05441075da3.png)

**Comment by martintb** [comment]
So...opening the DMG via the context menu (right-clicking) adds an extra 'Open' button to the dialog that allows you to continue with the install. This doesn't seem like it's intended , but it works for as a workaround.

**Comment by wpotrzebowski** [comment]
@martintb thank you for reporting this.  Apple's increased requirements for installing applications  with 10.14.6 release and they need to be notarized to pass gatekeeper.  We are aware of this issue and we are currently working on it. It will hopefully be fixed for 5.0.1 version

**Comment by toqduj** [comment]
Still working on it, I just encountered the same issue. You can circumvent it by right-clicking on the DMG file and selecting "open". You'll get the same error message, but an additional "open" button at the bottom.

**Comment by jilavsky** [comment]
This is still problem with version 5.0.1. Luckily, right click and open still works. Still, could this be fixed?

**Comment by smk78** [comment]
Similar issue reported today by user Mike Wier trying to install 5.0.1. on Mojave 10.14.6. Right-click worked for him too.

**Comment by smk78** [comment]
Have updated the note to Mac users on the Liks/Downloads page as an interim measure.

**Comment by timsnow** [comment]
Have we got the certificate sorted for that?

Notarisation should be easy thereafter...

**Comment by toqduj** [comment]
Tested, seems to work on my work MacBook.

**Comment by wpotrzebowski** [comment]
The notarized app is accepted by Gatekeeper though there some issues with C compilation of sasmodels (opencl works fine).

**Comment by wpotrzebowski** [comment]
The issue with C compiler seems to be resolved now. It can be tested by downloading dmg file from 5.0.2 release draft https://github.com/SasView/sasview/releases/. Deployment process is still to be resolved. The most reasonable seems to switch to 10.14 completely and use updated yaml file.

**Comment by wpotrzebowski** [comment]
And notes on notarization can be found here: https://github.com/SasView/sasview/wiki/DevNotes_Processeses_Notarization

**Comment by butlerpd** [comment]
Had forgotten about this issue.  Not sure what version of MacOS my cloud mac is running but I downloaded 5.0.2 on that mac for testing last night and had no signing issues - just a warning that I'd downloaded from the internet and did I want to install. I said yes and off it went.

Can we close this ticket for now then?

**Comment by smk78** [comment]
Is this a different problem to those experienced by Francois Boue on Friday evening (in help@sasview.org)?

```
My Mac (updated recently with Catalina) rejects SASView 5.0 and 4.2.2 because it "cannot verify whether there is no malware inside"/cannot verify the editor.
```

**Comment by wpotrzebowski** [comment]
Yes, it should be closed now.
