### ISSUE TITLE
sasview.org dns resolver is slow

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#1392]
Some browsers on some machines on some networks take a very long time to resolve `sasview.org` but are quick to go directly to `www.sasview.org`.

**Comment by butlerpd** [comment]
Tests as of today indicate no problems. In fact the old `track.sasview.org` which used to be very slow is quite fast as are both `sasview.org` and `www.sasview.org`.  Closing this ticket for now. as resolved
