### ISSUE TITLE
Magnetic model documentation is inconsistent with code

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#1408]
The documentation for magnetic modelling is inconsistent with itself and with the code.

* The [generic scattering calculator](https://www.sasview.org/docs/user/sasgui/perspectives/calculator/sas_calculator_help.html#magnetic-scattering) uses `M_0qy = (M_0y sin φ - M_0y cos φ) sin φ` but the [analytic models](https://www.sasview.org/docs/user/sasgui/perspectives/fitting/magnetism/magnetism.html) uses `M_0qy = (M_0y sin φ - M_0x cos φ) sin φ`.  The code uses the expression from the analytic models.

* The code uses `-M_0` in place of `M_0` relative to the docs. 

* Rather than repeating the polarization theory in the generic scattering docs, it should point to the polarization theory section for the analytic models.

* The code and docs should be consistent with the sasmodels orientation system, which has `+z` in the sample pointed toward the source.

With ticket https://github.com/SasView/sasmodels/issues/253 we would be changing the definition of `M_0`, so best to update the documentation to be consistent with the code rather than changing the definition twice.

**Comment by dehoni** [comment]
The magnetic scattering calculation has been rewritten more abstractly. This should avoid typos like in the description of the magnetic scattering vector component M_0qy. The orientation of magnetization and polarization only has to be defined once in SASview kernel and the choice is carried forward.
