### ISSUE TITLE
Issue with multi-core shell in 5.0.1

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#1410]
Note that these errors seem to be identical to what was reported against SasView 4.0.0 and then fixed (issue #760 and #766 ).  Unfortunately moving of tickets over to Github lost the history of when they were opened and closed. This sounds like it could be a sasmodels issue except that it seems to work properly in 4.2.2 so assuming it is a GUI handling issue at the moment.

Basically reported for 5.0.0 on PC by Anna Sokolova and on Mac by Lionel. Also Lionel reports still a problem in 5.0.1 for both mac and PC
* core-multishell (should also try other multilayer models)  does not recognize changing the number of layers (see also sasmodels issue #369).
* the SLD plot button just provides a blank plot

**Comment by rozyczko** [comment]
Fixed in SASVIEW_5.0.1_fixes

**Comment by smk78** [comment]
Tested in 5.0.1 Build 321 and locally-built from ESS_GUI branch. Now working as expected.
