### ISSUE TITLE
Corfunc is not working well in 5.0.1

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1413]
Testing 5.0.1RC on x64 in W10.

The Corfunc perspective is VERY sluggish in 5.0.1. It takes several seconds to graph any data, most notably when you send the selected dataset to the perspective. But sometimes, you click Transform and no transforms appear for almost a minute, or you have to click on the scattering data window to force the real space window to update.

Two other points:

I would not include the IDF on the correlation function graph. It is confusing, but also, with no way to add/remove datasets to the graph it obscures the CFs.

And I would definitely NOT auto populate the output parameters boxes. These ONLY have meaning if the data being analysed conforms to an idealised lamellar morphology. Implying otherwise is scientifically dangerous. Please bring back the Extract Parameters button (with a suitable warning alongside). And put the Transform button above the Output Parameters.

**Comment by rprospero** [comment]
I'm going to tackle this today and tomorrow hopefully

**Comment by smk78** [comment]
Testing 5.0.1 Build 321 on x64 in W10.
See comment on https://github.com/SasView/sasview/pull/1432

**Comment by smk78** [comment]
PR https://github.com/SasView/sasview/pull/1432 seems to have addressed this issue.
