### ISSUE TITLE
Reset graph range does nothing in 5.0.1

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1416]
Having used Set Graph Range to change the axis limits on a plot, Reset Graph Range does not appear to do anything!

**Comment by smk78** [comment]
Log Explorer reports:

```
12:16:42 - ERROR: SasView threw exception: 'list' object has no attribute 'min'
```

**Comment by rozyczko** [comment]
fixed in ESS_GUI_5.0.1_fixes

**Comment by smk78** [comment]
Tested in 5.0.1 Build 321 and locally-built from ESS_GUI branch. Now working as expected. Closing this issue.
