### ISSUE TITLE
Ambiguous labelling in Resolution tab in 5.0.1

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1417]
In the Resolution tab in a FitPage, if 'Use dQ data' is selected two boxes are shown, labelled:
[dQ/Q]max
[dQ/Q]min

But the values they are assigned are the other way around, that is, the one with the max subscript has a smaller value than the one with the min subscript. So the question that arises is, are the values just assigned to the wrong boxes, or should the labels actually be:

[dQ/Qmax]
[dQ/Qmin]

Which is it?

**Comment by butlerpd** [comment]
I assume you mean is it [dQmax/Qmax] which will usually be the minimum if the [dQ/Q](Q) function (though not sure that is always true)?

Really it is [dQ/Q] evaluated at Qmin or Qmax so maybe that is dQ/Q|_max?

**Comment by smk78** [comment]
I am minded to agree with you, but I think you have shown the need for this issue to clear up the ambiguity! :-)

**Comment by rozyczko** [comment]
interestingly, the same occurs in 4.x, where I took the logic from.
Should it be changed there as well?
![minmax_5 0](https://user-images.githubusercontent.com/8266281/71563386-ea216080-2a8e-11ea-9b1a-eb56d1f8f721.png)
![minmax_4 0](https://user-images.githubusercontent.com/8266281/71563387-eab9f700-2a8e-11ea-93c6-600bc631487c.png)

**Comment by butlerpd** [comment]
Yes -- though the question is the nomenclature to use I guess.  But apparently we cannot make a single issue be against two separate milestones :-)

**Comment by rozyczko** [comment]
Fixed in ESS_GUI_5.0.1_fixes for 5.0 (will merge with ESS_GUI soon)

**Comment by smk78** [comment]
Tested in 5.0.1 Build 321 and locally-built from ESS_GUI branch. Now working as expected.
