### ISSUE TITLE
Freeze functionality doesn't behave as expected in 5.0.1

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1418]
Testing 5.0.1RC on x64 in W10

In 4.x, if you choose to freeze a model calculation it appears in the Theory (as opposed to Data) sub-window of the Data Explorer.

In 5.x:

- data and frozen models only seem to appear in the Data sub-window;
- the Freeze Theory button on the Theory tab in the Data Explorer does nothing.

**Comment by butlerpd** [comment]
Ahh.  good catch. I did not notice that the button on the data explorer did nothing.  This was also one of Lionel's gripes on 5.0.1 but all I found when testing (too quickly apparently) was that it appears in the data tab.  Which might be where it should be once "frozen?" does it become data? but that is just confusing now that the data panel is hidden as a separate tab so looks like even that does nothing - and more so if behavior is different from before.  At any rate I won't make a new ticket for Lionel's comment.

**Comment by rozyczko** [comment]
Data/frozen models are supposed to be shown only in the Data tab, aren't they? The only way to populate the Theory tab is to create a new theory by selecting a model in an empty fit page. Unless I missed something in the workflow?

Freeze Theory button on the Theory tab works as expected and as it does in 4.x. If a theory is selected, it will copy it as Data1/2D and create a new data item in the Data tab. We were considering switching tabs to the Data tab on freeze, to be more explicit on showing the frozen dataset but we decided it was too interrupting - users might need to freeze more datasets from the Theory tab.

Additionally, if a theory is selected in the Data tab, it can be frozen as a separate data item with either Edit/Freeze Fit Results or with Freeze Results in the right click context menu for the selected result

**Comment by butlerpd** [comment]
Is this the same issue as #1851? I note that @ajj says he had to revert to 4.x for his demo because he needed the freeze theory and it was not working for him.  We should probably close this if it is superseded by #1851.

**Comment by smk78** [comment]
Closing this issue on the basis of the discussion in #2042 :
`@smk78 - I believe the answer to https://github.com/SasView/sasview/issues/1418 closure is yes. Note that while it mentioned the failure of the "Freeze theory" in 5.0.4 it was mostly about a difference in behavior between 4.x and 5.x. I think the consensus is that the new behavior is appropriate. Given that, and the fact that I don't believe there will be any more work on 4.x (and if there is one last push as was originally promised, changing that behavior would not seem like something to worry about) and since the Freeze Theory issue is fixed I would vote we close the ticket.`
