### ISSUE TITLE
Could we improve stepping through graph windows in 5.x

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1419]
In 5.x, when selecting Window > Next or Window > Previous, could the drop-down persist so that you can just keep clicking Next/Previous to find the graph you want, rather than having to re-open the drop-down each time?

In 4.x all the graph window titles were listed separately under Window so you could at least go straight to the one you wanted. This is not possible in 5.x (ok, there is Tile/Cascade but this isn't very helpful with lots of graphs!) so Next/Previous is all you have to go searching with.

**Comment by rozyczko** [comment]
Ha! I've never noticed that!
Will implement it in 5.0.2 rather than in 5.1 because this is indeed pretty awesome.

**Comment by rozyczko** [comment]
DIdn't manage to put it in 5.0.2, let's add it now.

**Comment by rozyczko** [comment]
Implemented in ESS_GUI_1419_plot_stepping

**Comment by smk78** [comment]
Tested ESS_GUI Build 357 on Win10/x64. Next/Previous works as expected! The only thing I would add though, is that the drop-down disappears each time you click Next/Previous, which is a bit tedious if you are stepping through lots of plots. Could it stay open until you click away from the drop-down?

**Comment by rozyczko** [comment]
Hmm this actually is **very** difficult to accomplish within the constraints of Qt.
However, I can add small controls (e.g. icons, arrows) which will act as previous/next shortcuts.
The question is where to place these controls?
One option is the icon toolbar (which by default is hidden/folded).
This could look something like here:

![2Untitled](https://user-images.githubusercontent.com/8266281/77110469-e9f98700-6a25-11ea-9839-0f5dfa0ae04f.png)

where the text might be replaced by a meaningful icon

**Comment by smk78** [comment]
I'd be happy with that!

**Comment by rozyczko** [comment]
I added the above functionality with appropriate icons in the toolbar.
Stepping can now be accessed both through the Window menu and the toolbar icon.

**Comment by smk78** [comment]
Locally built the ESS_GUI-Ticket1419 branch on W10/x64. The arrows are there and work as expected. Closing this ticket.
