### ISSUE TITLE
Data Operation tool does not display data in 5.0.1

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1421]
Testing 5.0.1Rc on x64 in W10.

The Data Operation tool does not display the selected data as it does in 4.x

**Comment by rozyczko** [comment]
This got fixed very recently - rogue commit reversing previous fix...
This and other fixes are in ESS_GUI_5.0.1_fixes branch

**Comment by smk78** [comment]
Tested in 5.0.1 Build 321 and locally-built from ESS_GUI branch. Now working as expected.
