### ISSUE TITLE
No output options from Generic Scattering Calculator in 5.0.1

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1424]
Testing 5.0.1RC on x64 in w10.

The plot window that is generated by the Generic Scattering Calculator in 5.0.1 has no output options! In 4.x you can:

- Save the image
- Plot the image
- Copy the image to clipboard

Also, the tooltip on the Load button has a typo: it should say .pdb not .pdf!!!

**Comment by wpotrzebowski** [comment]
@smk78 I cannot reproduce it. It's works fine for me both on OSX and Windows. On what file does it file?

Tooltip's been fixed in ESS_GUI_GenericScatteringCalc_fixes

**Comment by wpotrzebowski** [comment]
<img width="1355" alt="Screenshot 2019-12-12 at 06 28 41" src="https://user-images.githubusercontent.com/4189922/70906858-b31b6b80-2007-11ea-85d6-320d721abe43.png">

**Comment by wpotrzebowski** [comment]
![Screenshot 2019-12-16 at 13 16 41](https://user-images.githubusercontent.com/4189922/70906916-d0e8d080-2007-11ea-8e87-1aebe2d01276.png)

**Comment by butlerpd** [comment]
I can confirm that my new windows 10 also sees the output options above on both the fixed orientation and debye full avg calculation plots.

HOWEVER: I do note that on loading the default file type is given as "All Gen files" but then follows that with *.OMF only!!! it should include *.omf, *.pdb, and *.sld.

Also note the typo in tooltip but that has apparently been fixed?

**Comment by wpotrzebowski** [comment]
I've extended list of "Gen files" to pdb and sld formats (they were available from the file dialog before). I've also changed "Gen" to "supprted" because I don't really know what it means. I will create a PR.

**Comment by smk78** [comment]
Am re-opening this issue because although the tooltip has been corrected, the principle problem remains (tested in both 5.0.1 Build 321 and locally built 5.0.1 from ESS_GUI).
To reproduce, go: Tool > Generic Scattering Calculator > Load > navigate to the \test\coordinate-data folder and select something; eg, dna.pdb. A graph window appears with a rendering of the data. You can rotate the plot (left-click and hold) and zoom (right-click and drag - which I note is not the same behaviour as the normal fitting graph windows) but just right-clicking does not produce a context menu from which you can save/plot/copy the image.

**Comment by butlerpd** [comment]
Ahh.  I think I see the confusion.  You are talking about the 3D "atomic" rendering plot rather than the 2D scattering plot that is generated.  I had never actually noticed that about 4.x but yes, now that I try, that plot has a special pop up that only shows 3 options (Save Image, Print Image, Copy to Clipboard).  Is this a Matplotlib option or a wx/qt options?

**Comment by rozyczko** [comment]
Yes, indeed the 3D plot has no context menu associated with it. Needs fixing.

**Comment by rozyczko** [comment]
Fixed in ESS_GUI.

**Comment by smk78** [comment]
Tested in locally-built ESS_GUI on W10/x64. Now functioning as expected. Am closing this ticket.
