### ISSUE TITLE
error reported when custom config file contains unicode name in DEFAULT_OPEN_FOLDER

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#1435]
An error message such as the following appears when data is loaded from a directory with non-ascii characters in the name:

> ERROR: Error loading C:\Users\testard\.sasview\config\custom_config.py: (unicode error) 'utf-8' codec can't decode byte 0xe9 in position 44: invalid continuation byte (custom_config.py, line 11)"

Reproduce by creating a data directory (e.g., Donnée) and putting data within it.  Start SasView and load data from that directory.  Exit SasView then restart.  The error console and/or the sasview.log file will then contain the error.  I also sent the data to fitting and saved the analysis and the project just to be sure that DATA_OPEN_FOLDER would be set.

**Comment by lucas-wilkins** [comment]
Should be fine in new config.
