### ISSUE TITLE
5.0.1 ESS_GUI branch not reporting effective radius when using S(Q)

### ISSUE THREAD

**Issue by RichardHeenan** [SasView/sasview#1439]
As first reported here|: https://github.com/SasView/sasview/issues/1407

In my local build of the ESS_GUI branch if I choose say sphere or cylinder times hard_sphere, then effective_radius is staying set at the default value of 50.0 regardless of what I ask in the drop down S(Q) choices. (Pretty sure that effective_radius is actually being set properly internally and then just not being reported back to the gui.)  
[This alas seems to also be an issue in the 5.0 release, though I was sure it was working at least in my local builds ???]

**Comment by RichardHeenan** [comment]
I added some prints inside FittingWidget.py, after a while then discovered that
the line that says -
ER_value = scalar_results.get("effective_radius") # note name of key

ought to be 
ER_value = scalar_results.get("radius_effective") # note name of key

We did go through a phase of changing a lot of effective_radius to radius_effective, so it looks like this one slipped through the net.

Please would someone sort this, as I'm not in work again until next week.

**Comment by rozyczko** [comment]
ESS_GUI: Fixed (and checked).

**Comment by RichardHeenan** [comment]
Also checked in ESS_GUI, so closing this issue.
