### ISSUE TITLE
5.0.1 Show SLD profile plot - linear not log please

### ISSUE THREAD

**Issue by RichardHeenan** [SasView/sasview#1441]
onion & core_multishell models seem to be working now, (though I have not made a detail comparison of numerical results with 4.x), minor issue - the "Show SLD profile" plot ought to be linear-linear not log-log axes please.

**Comment by rozyczko** [comment]
fixed in ESS_GUI

**Comment by RichardHeenan** [comment]
checked in ESS_GUI, all OK, closing.
