### ISSUE TITLE
Bizzare behaviour of Choose Files after deleting data from Data Explorer

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1445]
Testing 5.0.1 Build 321 on W10 x64
I've found a situation where the Choose Files dialog hangs for many seconds. I wouldn't say it's a blocker, but is really annoying. To reproduce:

Run SasView 5.0.1
Load a data file
Send to fitting; choose a model
Show Plot
Now delete the dataset in the Data Explorer and confirm the popup (the plots remain)
Then try and load a new dataset. The Choose Files window appears but remains blank for several seconds. If you click on it in this state you get the Windows 'blue wheel'.

It's annoying because once it has happened once, it affects every future use of Load Data in that SasView session.

**Comment by rozyczko** [comment]
Unable to reproduce the failure - Load Files works fine regardless of how many times I delete the dataset.
*However* I noticed incorrect behaviour of the Delete button. It should delete the corresponding plots, similarly to how the context menu (right click on dataset -> click Delete) works. Both should behave the same way.
Will fix that.

**Comment by rozyczko** [comment]
And fixed in ESS_GUI.

Please try to reproduce the Load File hanging, if possible. I tried both the distributable 5.0.1 and local dev copy - both seem to work fine. 
Are you trying to load the files from a remote (mounted) location? Any other I/O intensive processes running on your machine?

**Comment by smk78** [comment]
No, I wasn't trying to load files over the network, but I did have a lot of mapped drives...
Anyway, to test the ESS_GUI branch I had to create an Anaconda3/Qt environment an dthat involved rebooting my PC. As a consequence of which, the Load File is no longer hanging.
I also confirm that the plots are now deleted when the data is deleted.
So am closing this issue.
