### ISSUE TITLE
5.0.1 sending same data to more than one fit page - plotting issues

### ISSUE THREAD

**Issue by RichardHeenan** [SasView/sasview#1454]
In 5.0.1 release candidate, and my current local ESS_GUI build, if I send the same data to more than one fit tab the plots for the second fit tab go wrong, showing either the fit (as blue line) or the data (as blue line) but not the data and fit together as expected.

Even attempting to append the missing data to graph3 does not work (maybe it thinks it is there already??).

**Comment by butlerpd** [comment]
moving to 5.0.2 as per today's conversation.

**Comment by rozyczko** [comment]
1. I was able to reproduce the the issue with missing data plot for cases with more than one tab with the same file/dataset sent. This will get fixed but the workaround is closing the charts and re-plotting from the active fit tab.
2. Appending to the graph should (and does for me) work. Deselect dependent models/residuals keeping only the data checkbox checked and append to the chart with missing data.
If this doesn't work for you, can you please provide a way to reproduce the issue?

**Comment by RichardHeenan** [comment]
Will review if someone can tell me which branch this is in ????

**Comment by rozyczko** [comment]
Err... this is not yet fixed. I must've moved it to the Review column accidentally. sorry.

**Comment by rozyczko** [comment]
fixed in ESS_GUI_1454, pull request out

**Comment by RichardHeenan** [comment]
tested in branch, looks good to me, closing ticket.
