### ISSUE TITLE
5.0.1 load project generates a second FitPage1

### ISSUE THREAD

**Issue by RichardHeenan** [SasView/sasview#1455]
In my local build of ESS_GUI, saved a project, shut down sasview, restart sasview, load the project.

this generates a second instance of a FitPage1, this may be of no particular consequence????
[Actually one tab, sometimes e.g. the constraints one, gets carried over.]

However I did save a larger project involving constraints between several FitPage, this does not load properly - see attachment to  #1456 and notes there.

**Comment by RichardHeenan** [comment]
It may be that the actions of the "This operation will remove all data..." ought to be done on the default FitPage1 that is present in 5.0 on starting sasview ?

**Comment by RichardHeenan** [comment]
this simpler project, no constraints yet, opens OK, but can finish up with two FitPage1 tabs.
[3sets_no_constraints2.txt](https://github.com/SasView/sasview/files/4160453/3sets_no_constraints2.txt)

**Comment by rozyczko** [comment]
Fixed in ESS_GUI - project load now assures only its own pages are shown, no mysterious "Fitpage 1" reappearing.
Order of tabs does not matter, since the tabs are identified by their name, not index.

**Comment by butlerpd** [comment]
So can we close this issue @RichardHeenan or is it still a problem after Piotr's commit?

**Comment by RichardHeenan** [comment]
Just rebuilt ESS_GUI on my Win10
loading the projects saved above is mush better.
e.g. get in order FitPage3, 2, 1 going left to right.
However if I then send one of the data sets to Fitting a second FitPage2 appears on the right (and the existing constraints involving M2 disappear)
Same happens if I load a separate data set and send it to Fitting, a duplicate FitPage is added.

**Comment by butlerpd** [comment]
uh oh ... seems like the PR got merged too quickly during code camp then?  at least it is an improvement.  @rozyczko and/or @wpotrzebowski - I assume we need to move this to 5.0.3 milestone at this point?

**Comment by rozyczko** [comment]
I think this is a separate issue now. Let's create a new ticket for it and assign the new issue to 5.0.3, seeing as it isn't (probably) critical.

**Comment by butlerpd** [comment]
OK.  Sounds right to me. Will do that.

**Comment by butlerpd** [comment]
Have now created the new issue #1513 so closing this issue
