### ISSUE TITLE
5.0.1 constraints between FitPages stop working

### ISSUE THREAD

**Issue by RichardHeenan** [SasView/sasview#1456]
In my local build of ESS_GUI, have been trying my usual constraints between core, shell & drop microemulsion contrast series.
M2:radius=M4.radius
M3:radius=M4.radius+M4.thickness

having added and removed a few constraints, including an M2:sld_solvent=M2.sld_core, these plainly stopped working. Of course I cannot easily reproduce this (but now see #1455 for example which fails), but a project file is attached, renamed from json to txt, with non functioning constraints.
[constraints_not_work_M2M3M4 .txt](https://github.com/SasView/sasview/files/4160238/constraints_not_work_M2M3M4.txt)

but there is now a problem with the save or load of the project, as there is no FitPage3 on load, and the shell contrast appears twice but the drop contrast not at all, so the M3: constraint in the project file does not appear.  See #1455 

In the original session the shell contrast data was I think being used on both FitPage1 (with ellipsoid)  and FitPage2 (with core_shell_sphere), so that might be part of the story. I will try a simpler example.

**Comment by butlerpd** [comment]
As per today's conversation am moving this to a 5.0.3 milestone in preparation for a 5.0.2 release.

**Comment by gonzalezma** [comment]
If I'm not wrong, the accepted PR #1533 should have solved this.

**Comment by butlerpd** [comment]
Cool ... can we close the ticket then?

**Comment by RichardHeenan** [comment]
Yes, I will close it, when a few more PR's have been merged into master or ESS_GUI, I will test all this again.
