### ISSUE TITLE
Odd save/load project behaviour on Mac

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1458]
See https://github.com/SasView/sasview/issues/1457

**Comment by butlerpd** [comment]
This seems to be redundant @smk78 . can it be deleted?

**Comment by smk78** [comment]
What has happened here is that this issue was for the 4.x branch, and https://github.com/SasView/sasview/issues/1457 was for the 5.x branch. But @butlerpd modified the milestone of the latter to 4.x! Both issues require testing on a Mac which I am unable to do.

**Comment by lucas-wilkins** [comment]
Definitely more issues for this than needed
