### ISSUE TITLE
dy = 1 for every point of Freeze theory curves (and saved as data file) in 5.0.1

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#1459]
In 4.x when a theory curve is frozen and/or save as data the data file and 1D data object correctly assigns 0 to dx and dy.  One could try to add root(I) as dy but that is not true for reduced data.  However in 5.x, while dx is assigned 0, every point is assigned 1 for dy. besides making weighting wrong when attempting to fit, the plots are illegible for data whose scattering is mostly below 1 (bio data often tries to go to 0.001 in intensity .. now with an error bar of 1)

The fix should be simple but still needs to be done (just to be clear dy should be set to 0 just like it is in 4.x and the same as dx)

**Comment by rozyczko** [comment]
Fixed in ESS_GUI

**Comment by butlerpd** [comment]
Tested using ESS_GUI build 357 of March 19.  Works fine. Now only outputs 2 columns: Q and I.  Closing as fixed
