### ISSUE TITLE
resolution setting not persistent in theory mode of 5.0.1

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#1460]
start SasView. choose sphere and sphere in fit panel. Compute and show plot. the plot shows a bunch of oscillations as it should.

Now go to the resolution tab which shows None in the dropdown. Choose custom pinhole.  enter 5 in the new box that pops up (i.e. 5% dq/q .. can be anything .. I also used 8 and 10).  the plot updates smearing out the ocillations.  hit compute and the plot flashes but again shows the oscillations being damped. **However** .... the second box showing the amount of smearing is gone and the dropdown again shows "None" hitting compute again will revert to an unsmeared curve.  This is extremely annoying when playing around with parameters of a model after setting the resolution.

**Comment by rozyczko** [comment]
Fixed in ESS_GUI_1460

**Comment by rozyczko** [comment]
This has actually been already merged with ESS_GUI a while back.
Please review

**Comment by butlerpd** [comment]
will look at shortly

**Comment by butlerpd** [comment]
since it is already merged there is no code review to be done but testing of the latest build of ESS_GUI (build 357 of March 19) shows it is now behaving properly so will close the issue.
