### ISSUE TITLE
Dmax explorer: Background units are given as A-1 but should be cm-1

### ISSUE THREAD

**Issue by ajj** [SasView/sasview#1464]
In the Dmax explorer the units for background are listed as A-1 but should be cm-1

This is in both 4.x and 5.x

**Comment by rozyczko** [comment]
Fixed in 5.x

**Comment by smk78** [comment]
Now also fixed in 4.x.
@rozyczko: the same change was also needed for I(q=0) in 4.x. What about 5.x?

**Comment by rozyczko** [comment]
Yes, it was incorrect in 5.x as well. Fixed and merged into ESS_GUI
