### ISSUE TITLE
better handling of qt ui generator in setup.py

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#1467]
`python setup.py --help` triggers the Qt UI generator.  Instead the UI generator should only be triggered when needed.

Maybe something like [setup_qt](https://github.com/xmikos/setup_qt) or [pyqt_distutils](https://github.com/ColinDuquesnoy/pyqt_distutils) would help?  Don't know if either will automatically trigger as part of the build if you don't specifically ask for them.

See also PR #1398.

**Comment by rozyczko** [comment]
I would prefer just spawning a subprocess for UI conversion script. This allows me to be agnostic wrt. underlying conversion command (e.g. PySide vs PyQt, PyQt4.x vs PyQt5.x etc) and allows me to run the conversion from the command line if I choose to.
Instead, I can look at the setup.py arguments and choose the ones which should not trigger the UI build.

**Comment by pkienzle** [comment]
Both packages support the various backends, but it looks like setup_qt is a bit better match to your needs: it lets you override the configuration options on the build command.

I considered doing what you proposed and triggering on the basis of setup.py options, but decided that there were too many of them, and we should try an existing package before rolling our own.

**Comment by lucas-wilkins** [comment]
Can possibly roll this into #2140

**Comment by lucas-wilkins** [comment]
Looks like its actually dealt with, closing. @rozyczko can reopen if I'm wrong
