### ISSUE TITLE
Re-describe Source intensity in model parameter tables

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1468]
Ad van Well pointed out that describing the 'scale' parameter as the 'source intensity' was inaccurate, and misleading. We should change the description.

To 'scale factor or volume fraction', perhaps?

Need to do so in 4.x & 5.x.

**Comment by smk78** [comment]
And at the same time clarify that where scale = volume fraction it is actually phi (1-phi)

**Comment by butlerpd** [comment]
Sorry for my confusion but in what case is scale (or volume fraction) equal to vol frac * (1-vol frac)?  I recognize that as part of the invariant calculation but dont understand the statement here. Can you please clarify?

**Comment by smk78** [comment]
Sorry. Hastily worded as I was heading to lunch. I meant something more like 'And at the same time clarify that _in some models_ where scale = volume fraction it is actually phi (1-phi)'. To be fair, we may already have caught the affected models in the docs. It's going to be those that mostly get used on inhomogeneous systems, right? So we need to check the shape_independent models.

**Comment by RichardHeenan** [comment]
e.g. the Gaussian coil, which happens to be an unusual case, where scale should be phi if applied to a dilute solution of polymer in solvent, but phi(1-phi) if applied to a solid polymer with a mix of D- and H- versions of the same polymer. The current docs for mono_gauss_coil don't even attempt to say what "scale" properly means, so need a ticket to improve them.

**Comment by smk78** [comment]
Changed line 49 in sasmodels modelinfo.py so that instead of 'Source intensity', the description of _scale_ is now 'Scale factor or Volume fraction'.

**Comment by butlerpd** [comment]
I vaguely remember a slack comment or email that suggested this was now considered done based on the commit that @smk78 mentions?  Is this correct? can we close this ticket?

**Comment by smk78** [comment]
Check /sasmodels/sasmodels/modelinfo.py, line 49. I just pulled on sasmodels and the change seems to be there for me...

**Comment by butlerpd** [comment]
And indeed in editing the sasmodels documentation I noticed the change in scale definition as well so a going to call this done and close it ... but not before moving to the done column of course - gota take credit :-)
Note this issue really is a sasmodels issue not a SasView issue and will roll out in the next sasmodels release not SasView.
