### ISSUE TITLE
need to add visual data range bars for fitting

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#1473]
* Patrick Corona and I have discussed the need for adding the visual data range lines when trying to adjust for fitting.  This is actually much more useful than it may seem hence setting it to "major"

**Comment by butlerpd** [comment]
As per today's discussion am moving this to a 5.0.3 milestone in preparation for a 5.0.2 release

**Comment by krzywon** [comment]
Is this the same or similar to the q-range slider bars ticket? Can this be closed now?

**Comment by butlerpd** [comment]
Yes that is correct. We can thus close this.
