### ISSUE TITLE
Need to triage 4.3 issues and finalize release and final transition plan

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#1475]
SasView 4.3 was to be the final release in the 4.x series.  Master has seen quite a few changes since 4.2.2 and there are a few pull requests against master.  However the tickets listed against the 4.3 milestone is legion and probably not appropriate for "getting on with it"
we need:

- [x] Review each ticket carefully. If too hard and/or not vital for 4.3 and can be moved to 5.x then move
- [ ] Review pull requests and merge or kill
- [ ] Decide on target for final release
- [ ] Make release 4.3
- [x] Rename Master branch to 4.x_Master
- [x] Rename ESS_GUI branch to Master

**Comment by butlerpd** [comment]
First pass at this is done and awaiting feedback on which of the remaining tickets can be closed.  Once that is done should probably take another look to decide which of the remaining items are actually worth waiting to fix for a final 4.x release to include all the changes to master to date. But that would be part of the normal 4.3 release process so closing this ticket now (left over from virtual code camp/sprint)

**Comment by butlerpd** [comment]
OOps .. forgot this is a master ticket and should not be closed till the final release. Reopening and checking off the first item

**Comment by lucas-wilkins** [comment]
@butlerpd Close?

**Comment by lucas-wilkins** [comment]
adding discuss at call label

**Comment by butlerpd** [comment]
OK .. going to close this as obsolete. We still need to figure out what we want to do with the branch that does have a lot of commits since 4.2.2 I think? and just close all remaining tickets on 4.3 at this point?
