### ISSUE TITLE
Rationalise Issue Labels

### ISSUE THREAD

**Issue by ajj** [SasView/sasview#1477]
Need to have common labels across repos
Need to have pared down list

- [ ] Inventory existing labels
- [ ] Propose new list
- [ ] Implement new list

**Comment by butlerpd** [comment]
A couple of points.  The simple one -- can we use a checklist for the above three tasks?

Beyond that, aside from the problem of too many labels ... and confusing labels across repos and redundant labels, there is the issue that the labels imported from trac which had several sets of mutually exclusive labels (like importance vs work package vs type -defect/enhancement) which were enforced via dropdowns.  Not sure we can enforce as easily with github (not even sure zenhub or the like would do though worth exploring more).  I was wondering if templates might help but not had a chance to explore those either.  It also would be good to be able to ensure that all labels are in a required category .. like milestone maybe either with an enforcement and/or an easy way to list all that are not in any of items in the category (e.g. not against any milestone). This helps ensure one doesn't completely lose track of issues that accidentally did not get listed against a "milestone"

Those are my thoughts so far .. which does not in fact satisfy even item 1 of the list but maybe suggests ways to look at point 2?

**Comment by ajj** [comment]
Starting wiki page https://github.com/SasView/sasview/wiki/Labels to track info

**Comment by butlerpd** [comment]
I would say it is a work in progress but to the extent that it is being actively worked on (I think there is still a way to go to make things properly useful) I'm happy to close this for now.

**Comment by lucas-wilkins** [comment]
It's done on sasview. I might start elsewhere next time I find tedious-admin-job time.
