### ISSUE TITLE
v5 & v4 TEst that P(Q)S(Q) plugin works

### ISSUE THREAD

**Issue by RichardHeenan** [SasView/sasview#1478]
From https://github.com/SasView/sasview/issues/1470, spawn this ...

P(Q)S(Q) plugin not working ??? - needs test 
https://github.com/SasView/sasview/issues/1301
https://github.com/SasView/sasview/issues/1451 which was merged to master of sasmodels - see https://github.com/SasView/sasmodels/pull/216

**Comment by butlerpd** [comment]
As per today's discussion, moving this to a 5.0.3 milestone in preparation for a 5.0.2 release.
However as I read this it is just a test. passing the test closes the issue and presumably the issue it is tied to while and failing presumably leads to comments on the issue/PR in question?

**Comment by butlerpd** [comment]
Not clear where this should go or be closed but will move to 5.0.4 for now

**Comment by RichardHeenan** [comment]
P(Q)S(Q) plugin It is working in 5.0.3 at least for ellipsoid x hard_sphere which I tested it on,  (though of course radius_effective in S(Q) is not constrained), and I am not concerned re v4, so will close this ticket.
