### ISSUE TITLE
SasView 5 (Ubuntu) - Need to change colors in Data operation combobox

### ISSUE THREAD

**Issue by gonzalezma** [SasView/sasview#1484]
After selecting 2 data sets for the 1st time, the colour of the selecting box is set to white. But the foreground colour of the selected data set is also set to white (only in Ubuntu, no problems on Windows), so the name of the selected dataset becomes invisible. E.g.:

![DataOperation](https://user-images.githubusercontent.com/10974838/77081288-b05f5680-69fa-11ea-8fc5-579cc7eef475.jpg)

A possible solution is to define a 'non-completely white' colour in DataOperationUtilityPanel.py, e.g. BG_LIGHT = "background-color: rgb(230, 230, 230);" and use this one in the final else of def onCheckChosenData(self). This works in Ubuntu and I guess it should not change appearance too much in Windows/Mac, but I prefer to let Piotr check/decide.

**Comment by rozyczko** [comment]
interestingly, on my Ubuntu this shows up fine. However, for some color themes this indeed might not be optimal. This brings up a question - are we expected/supposed to test colour matching for a variety of themes on each platform?

![Untitled](https://user-images.githubusercontent.com/8266281/77083200-6b88ef00-69fd-11ea-8624-e638ee609c23.png)

**Comment by rozyczko** [comment]
Ah! I see, this widget explicitly sets the background color, because it also sets the background to red in case of bad choice.
We should instead query the original background and keep this information for later use.

**Comment by gonzalezma** [comment]
Right. It appears OK the first time, but once that you have selected 2 datasets, it sets the background color to white and the problem appears.

**Comment by rozyczko** [comment]
fixed and pushed to ESS_GUI_1484_bg_colors.

**Comment by rozyczko** [comment]
This, however still doesn't solve the issue. Just tested it on Ubuntu with the same theme as @gonzalezma and the problem still persists.
This happens only after the first color change background->red and back.
Maybe setting the foreground colour to original will help here.

**Comment by rozyczko** [comment]
I reverted the changes and opted for a simple modification of the foreground colour in the stylesheet.
Looks OK on Linux now.

**Comment by gonzalezma** [comment]
Done!
