### ISSUE TITLE
Need to update "How to edit webpages" wiki

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#1488]
The wiki page on how to edit the webpages is very basic git instructions.  It would be very useful to point out the separation between the webpage **content** vs the layout, style, behavior etc which would be **programming**.  It is critical for those providing content to understand NOT to try to edit the html "programs" unless they really mean to change the fundamental behavior and have knowledge of programming that.

**Comment by butlerpd** [comment]
I think it is now complete ... at least for this round, but am leaving this for review before we move it to done.  If Jeff concurs we can move to done and then close

**Comment by krzywon** [comment]
I added how to pin posts using the highlight tag and made a few minor edits. I'm calling this done.

**Comment by butlerpd** [comment]
Ah  .forgot about the pinning. Thanks
