### ISSUE TITLE
Update 5.x documentation for Corfunc

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1501]
In addressing Issue https://github.com/SasView/sasview/issues/1413 and merging SasView PR https://github.com/SasView/sasview/pull/1432 there is a small change to the way Corfunc outputs its results. The help file corfunc_help needs updating:

- clarify new behaviour
- replace final screenshot
- also explain what the Save button does

**Comment by smk78** [comment]
I had to push these changes to ESS_GUI master as the Corfunc perspective in 5.x not only looks different to that in 4.x (obviously) but the way it returns the output is also slightly different. Thus I couldn't use the sasview documentation branch as that is a branch off the 4.x master.

I did build the doc before committing it.

**Comment by butlerpd** [comment]
indeed ... I realized that yesterday which is why I also created yesterday an ESS_documentation branch off of ESS_GUI :-)
