### ISSUE TITLE
Enhancements to Corfunc

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1502]
There were two outstanding enhancement requests to Corfunc when SasView PR https://github.com/SasView/sasview/pull/1432 was merged. This issue captures them:

- there is nothing in the perspective that tells you the IDF has been calculated and that you can write it out by clicking Save. This is addressed in the documentation (Issue https://github.com/SasView/sasview/issues/1501) but it does rely on people clicking the Help button... :-) What about changing the text on the Save button to Save Transforms?

- Can Copy Parameters be made to work with this perspective? Alternatively, what about implementing a "Save Parameters" button that writes all parameters to a text file?

**Comment by smk78** [comment]
Welcome additional enhancements:

- the dataset name is not displayed in the perspective (captured in https://github.com/SasView/sasview/issues/1528)
- the perspective is not scrollable (captured in https://github.com/SasView/sasview/issues/1529)
- the extrapolation range bars need to be different colours to the data and to each other!!! In 4.x the low-Q bar is red and the two high-Q bars are purple.
- in 4.x the experimental data are plotted minus the background value which makes it easier to spot when Iobs - Bg < 0. If that can't be replicated in 5.x without perturbing a lot of the underlying calculation, it would at least be helpful to display a line corresponding to the background.
- it is essentially impossible to use the pan graph function on the data graph because it always selects one of the range bars! Can the region either side of the bars be a bit tighter to allow the graph to be captured and panned?
- the range bars can be crossed over! This should be trapped and prevented.
- implement a way of displaying the IDF _but not_ on top of the Correlation Functions (y axes are too different). Maybe by using a "Display IDF" checkbox that is unchecked by default?
- compute & display the "Average Soft Block Thickness" (= Long Period - Hard Block Thickness)
- compute & display the "Hard Block Volume Fraction"
- nit-picky label changes:
  - Change "Scattering data" to "Scattering Data"
  - Change "Real Space Correlations" to "Real-Space Correlations"
  - Change button for "Calculate" background to "Estimate" background
  - Change "1D Correlation" to Gamma_1(z) (with Greek symbol & subscript 1 if possible)
  - Change "3D Correlation" to Gamma_3(z) (with Greek symbol & subscript 1 if possible)
  - Change "Output parameters" to "Lamellar parameters"
  - Change "Long Period" to "Average Long Period"
  - Change "Local Crystallinity" to "Hard Block Phase Fraction"

**Comment by smk78** [comment]
Also see #1539

**Comment by smk78** [comment]
Also see #1540

**Comment by smk78** [comment]
> the perspective is not scrollable (captured in #1529)

Has been fixed by https://github.com/SasView/sasview/issues/1529 and https://github.com/SasView/sasview/issues/1543

**Comment by lucas-wilkins** [comment]
Closing as outstanding items have been moved to individual issues
