### ISSUE TITLE
ESS_GUI installer - python console fails

### ISSUE THREAD

**Issue by rozyczko** [SasView/sasview#1511]
SasView installed from the installer fails to start the python console.
**Windows only issue**

**Comment by rozyczko** [comment]
Seems to be fixed - relevant PR: ESS_GUI_test_ipython.
Updated to the most recent versions of IPython and dependent modules and removed dead code.

**Comment by butlerpd** [comment]
I see this related PR got merged but this was not linked to that PR so is not closed autmatically. @rozyczko can we close this manually then?

**Comment by rozyczko** [comment]
we sure can.
