### ISSUE TITLE
Get proper DOI from __init__.py rather than have it hardcoded.

### ISSUE THREAD

**Issue by rozyczko** [SasView/sasview#1516]
We include DOI in the Acknowledgements dialog. This DOI is currently hard coded and at each release we need to modify the widget. It would be better if DOI was taken directly from sas/sasview/__init__.py, since it's already there.

**Comment by butlerpd** [comment]
@rozyczko or @krzywon would this be a good first issue do you think?  It seems like it would be?

**Comment by butlerpd** [comment]
@rozyczko This looks like you in fact did implement this? If so this ticket should be closed rather than moved.

**Comment by rozyczko** [comment]
`git blame` blames Wojtek for this, but yes, this is fixed and can be closed.
