### ISSUE TITLE
Issues encountered testing 5.0.2 pre-release

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1519]
**Umbrella issue for things encountered  during testing of 5.0.2 pre-release**

1. ~~Check for updates points to 4.2.2~~ **FIXED IN 5.0.2RC2**
2. ~~About & Welcome boxes need the end year for the (c) updated from 2019 to 2020~~ **FIXED (SEE BELOW)**
3. ~~RELEASE.html needs updating for 5.0.2~~ **FIXED (SEE BELOW)**
4. ~~File Converter: 1D BSL conversion is failing with the message "ERROR: Q-Axis file has multiple frames. Only 1 frame is allowed for the Q-Axis"; I tried both the Z83000 and Z98000 convertible datasets. This _was_ working earlier, and I suspect has been scuppered by later changes to the code to address the 2D BSL multi-frame case? The other conversion types are working ok.~~ **NOT AN ISSUE (SEE BELOW)**
5. ~~Invariant: The invariant help doc is _not_ the final version. Now, I'm not sure what's going on here because if I look at the Kanban board all the invariant tickets (https://github.com/SasView/sasview/issues/1472, https://github.com/SasView/sasview/issues/1434 and https://github.com/SasView/sasview/pull/1461) are still open! Is that just an oversight @butlerpd or has stuff not been pulled in?~~ **FIXED (SEE BELOW)**
 6. ~~Something has gone awry with the last entry in tutorial.html (go Help > Tutorial)~~ **FIXED**
7. ~~The problem discovered with the Invariant Calculation needs adding to Known Issues on both the website and in RELEASE.html.~~ **FIXED (SEE BELOW)**
8. ~~There seems to be a major problem with loading projects which is more serious than that reported in https://github.com/SasView/sasview/issues/1513. See below.~~ **MOVED TO ISSUE https://github.com/SasView/sasview/issues/1526. NOTE ADDED TO KNOWN ISSUES**
9. ~~There is still no ability to change axis labels.~~ **MOVED TO ISSUE #1523**

**Comment by wpotrzebowski** [comment]
@smk78: For the RELEASE.html - I've apparently didn't merge a pull request that contained it... It should be in there now. Anyway it seems there are more things to be fixed.

**Comment by rozyczko** [comment]
4. I cannot reproduce the failure with the 5.0.2 installer (win64). Both Z83000 and Z98000 get properly converted to both xml and h5!

**Comment by smk78** [comment]
@rozyczko 
4. Yes, you are right, it is ok. I had mistakenly put the wrong file in the wrong box! Sorry!

**Comment by rozyczko** [comment]
Should we have an "auto-fill" of the corresponding box with the same name but different extension? E.g. one would have to explicitly choose one file, say `Z83000.QAX` and if there's an intensity file in the same directory with the same filename, it would get automatically selected into the other box? (i.e. `Z83000.I1D` here)

**Comment by smk78** [comment]
The problem is there is no hard and fast rule for what the pairs of extensions would/should be. And, in principle, you could use a Q-axis file from another dataset (as long as it had the same number of data points).

**Comment by smk78** [comment]
Re 5. The reason this didn't get pulled in is because the updated docs _and source code corrections_ were made in the ticket1434 branch which is a branch off the 4x master...

**Comment by smk78** [comment]
Re 6. Fix pushed to ESS_GUI master.

**Comment by smk78** [comment]
Re 5. @butlerpd writes on Slack:

Yes I knew about the invariant but thought (when we were thinking the release was going to happen two weeks ago) that this would have to wait till 5.0.3 and 4.3.  @smk78 did some fixed based on Yun's review but I was supposed to finish them but have just been swamped which is why it has not yet been pulled even into master.

The plan was that once we were happy in 4.x I would work to do it for 5.x because some of it is in sascalc and I made some real changes, not sure it is a direct port to 5.x though it should be reasonable

Part of the reason for 4.x being my target is I was trying to figure things out and doing some ... ahh... blind changes :slightly_smiling_face:

and figured it was better to figure it all out in 4.x first as it would have less impact if I screwed up ... because 5.x is the version we want people to use :slightly_smiling_face:

**Comment by butlerpd** [comment]
oops -- thanks @smk78 was multitasking .... ineffectively as it turns out.

**Comment by butlerpd** [comment]
Regarding #1 .. that is the problem that was on our agenda for a year but we never got to.  Fundamentally it is not a problem with the code and normally gets fixed AFTER the release.  However we were thinking of keeping 4.x and 5.x separate for a short while.  Doing that would in fact require some change to the code here.  Basically we probably would want to change the code than compares its own verstion number with the latest one to check two version numbers and compare to the higher one (so if 4.3 and 5.0.3 compare myself against 5.0.3 for 5.x while 4.2 would compart against 4.3 .. and then to 5.1 after that release).

**Comment by smk78** [comment]
Re 7. Fix pushed to ESS_GUI master.

**Comment by smk78** [comment]
Re 2. Fix pushed to ESS_GUI master.

**Comment by smk78** [comment]
Re 5. Pursuant to Slack discussion, invariant_help.rst from the ticket-1434 branch (the most current invariant docs) has been cherry-picked and copied into ESS_GUI master.

I have then added in the pre-prepared 5x invariant panel screenshots which also necessitated a small change the 'Using Invariant Analysis' text due to different behaviour to 4x.

**Comment by smk78** [comment]
Re 1. This is fixed in 5.0.2RC2. It correctly looks for 5.0.2 and the status bar reports you are up to date.

**Comment by smk78** [comment]
Re 9. I recall a discussion with @rozyczko (but can't find the issue) about putting the Modify Plot Property functionality that allows the user to change, for example, axis labels, back into 5x. This isn't in 5.0.2. Is it slated for a later release?

**Comment by smk78** [comment]
Re 8. Load projects is essential broken in 5.0.2RC2.

If you save a project from 5.0.2RC2, close down SasView, restart it and load in the saved project all you get is the data and a blank FitPage (by blank, I mean it is just grey). This appears to be different, and far more serious, behaviour to that reported in https://github.com/SasView/sasview/issues/1513.

If you try and load in a 4x project file (I created one in 4.2.2 with three datasets and FitPages but only one of which had actually run a fit) all it loads is a fitted dataset. Any unfitted datasets are ignored.

**Comment by butlerpd** [comment]
OH OH!! That is wrong!! number 1 should *never ever* be "correct" until the full and final release. This means that everyone in the world with any version of sasview is being told to update as of 3 days agot tto 5.0.2RC2!! that would mean no more changes!! Is that really what this is?!!

**Comment by butlerpd** [comment]
Assuming this was a test that accidentally left 5.0.2 as a final fully ready release and reverted laterstvesion.json to point to 5.0.1 for now.

**Comment by smk78** [comment]
![image](https://user-images.githubusercontent.com/10938679/79701346-40abe800-8294-11ea-8068-0d5690189e32.png)

**Comment by smk78** [comment]
Just asked it to check again and it's now pointing at 5.0.1.

**Comment by butlerpd** [comment]
But should still say you have the latest version since 5.0.2 is a larger number that 5.0.1?  At least people with previous versions will not be being told that a final 5.0.2 is yet ready for general consumption ... 
doing a few tests myself and will be adding a few more bugs I'm finding.

**Comment by butlerpd** [comment]
Rather than keep adding new bugs here (most of whom predate 5.0.2 I think) making it very hard to keep track of, I am putting the things I find into new 5.0.2 tickets which can be either fixed or moved to 5.0.3 as appropriate.  Will also move point 9 which is I think a new issue that is related to, but not the same as, the pan/zoom functionality being lost in the 4.x to 5.x move.

**Comment by rozyczko** [comment]
**8. Unable to reproduce.** I tried
- loaded several datasets
- sent them all to fitting (separate pages
- ran fit jobs on random models
- saved the project
- restarted SV 5.0.2
- loaded saved project
- all data loaded, with fitted parameters and the whole state loaded correctly

**Comment by smk78** [comment]
Re 8. @rozyczko , the crucial bit in my post above was the update. If you only save a _fitting_ session then save/load works fine. But look what happens if you do a variety of analyses (attached).
[502rc2-testing.pdf](https://github.com/SasView/sasview/files/4503261/502rc2-testing.pdf)

**Comment by rozyczko** [comment]
OK. I see the problem.
Project load/save was not implemented for anything else than fitting perspective.
This should be corrected obviously and I'll do that in 5.0.3/5.1.
For now I'm inclined to disable "Project Save/Load" on all other perspectives so the observed behaviour is not so awful.

**Comment by rozyczko** [comment]
BTW - this update/fix won't break the backward compatibility - we will still be able to load 5.0/5.0.1 projects

**Comment by smk78** [comment]
Have just repeated the same exercise in 4.2.2 and it all works (see attached). But that would tie in with your explanation.

We can also make this another known issue in the RELEASE notes.

My question is then, how will this present to the user? So if someone has done what I've just done, are you going to throw up a box that says 'Only fitting perspectives and plots will be saved to the project file'? What that won't capture, of course, is the user that is just doing non-fitting stuff. How can we make it clear to them at the outset that they won't be able to save their work as a project?
[422release-behaviour.pdf](https://github.com/SasView/sasview/files/4503349/422release-behaviour.pdf)

**Comment by rozyczko** [comment]
We can just simply disable the "Save Project" and "Load Project" menu items for anything but Fitting Perspective open,

**Comment by smk78** [comment]
That will work!

**Comment by butlerpd** [comment]
So .. is this is a "fast and easy" fix for you then Piotr?  Otherwise the question is whether it behaved badly also in 5.0.1?

**Comment by rozyczko** [comment]
it behaved the same since 5.0, unfortunately. But also, the disablement is not as simple as I originally thought. I'd prefer to do it in 5.0.3 not to postpone the current dot release.

**Comment by butlerpd** [comment]
Makes sense @rozyczko.

**Comment by smk78** [comment]
Re 8. This is now added as a Known Issue in the Release Notes.

**Comment by smk78** [comment]
As release 5.0.2 is now being generated and all the points above have either been resolved or moved to 5.0.3 issues I am closing this issue.
