### ISSUE TITLE
When loading data the Data Explorer should revert to the data tab

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#1524]
The Data Explorer starts with the data tab selected.  As soon as a model is chosen in the fit page the selected tab is automatically changed to the Theory tab.  However when the user then loads a data file the Explorer does **not** revert automatically to the Data tab.  It makes sense to automatically change the selected tab to the appropriate tab for what the user is doing but, if that is the plan, it needs to be consistent.

**Comment by rozyczko** [comment]
This is really an enhancement and as such should be moved to 5.0.3/5.1, please

**Comment by butlerpd** [comment]
Agreed - moving now
