### ISSUE TITLE
Project Save/Load functionality of 4.x needs to be restored

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1526]
Currently, and unlike 4.x, 5.x will only save and re-load data used for fitting analyses (ie, if a SasView session also involved correlation function analysis, invariant analysis or P(r) inversion, those data and windows are forgotten).

As of release 5.0.2 the only mitigation we are providing is a Known Issue in the Release Notes.

**Comment by krzywon** [comment]
This isn't 100% complete. Inversion and Corfunc states need to be serialized and able to save/load their states.

**Comment by rozyczko** [comment]
Oops, sorry. I'm a simple man. I see `Merged` I click `Close`. Thanks for being vigilant.

**Comment by butlerpd** [comment]
No worries ... this was confusing.  We agreed at last call to move this to the done column for the purposes of the hackathon as part of the functionality requested (Pr) was added even though all was never something we would have time do to. However the ticket was to remain open to have the rest of the perspectives added at a future date (in a different hackathon?)
