### ISSUE TITLE
ESS_GUI: Something strange with 5.x and the .sasview folder

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1534]
Evidence is mounting of a problem with how 5.x interacts with the .sasview folder. Reports so far (myself & 2 users) implicate 5.0.1 and 5.0.2 running on W10 or MacOS 10.14.6 Mojave.

The symptom is that on trying to start SasView 5.x a popup window announces that it is _unable to start the script sasview_. Failure to start 5.x then persists unless drastic action is taken (see below). So far, 4.x appears unaffected.

Reliably reproducing this issue is proving difficult, but in all known cases usage of SasView has either involved the simultaneous use of 4.2.2 and a 5.x version, and/or the editing/dropping of plugins into the .sasview\plugin_models folder.

The only known workaround at this time to permit SasView 5.x to start up is the deletion of the .sasview folder! Obviously this has implications if the user has a lot of plugins...

However, I also had an instance where, after deleting .sasview, SasView 5.x did not start because it could/would not create a new .sasview folder. The only way I could get 5.x to start in this instance was to run 4.2.2 which created .sasview without any trouble!

As this is clearly not a one-off, we need to consider a resolution.

**Comment by smk78** [comment]
Update from using running Mojave:

> Your suggested fix does solve the problem. I needed to clear out the folders entirely to prevent crashes. It definitely is related to plugin models, as when I created a new plugin, the problems returned. But at least I have a solution if needed!
>

**Comment by smk78** [comment]
Summary of what we know so far:

**User FridaL (Feb 28, 2020):**
PC with W10 Pro 64-bit (version 10.0.18363). Installed _5.0.1_.
SasView installed to default folder by IT Dept. On trying to start SasView a Fatal Error box appeared saying 'Failed to execute script sasview'. However, if IT guy right-clicked to Run as Administrator, then SasView ran ok.
UAC was set 1 level below 'Always Notify' (so level 2 of 4).
Installation folder permissions were all set to Allow.
IT guy finally fixed the problem, but we don't know what he did. @smk78 has asked...

**@smk78 (Mar 24, 2020):**
PC with W10 Enterprise (build 10.01.18362).
Multiple versions of SasView 4.x and 5.x installed.
After using 5.0.2 found that he could not start 4.2.2. Fatal Error box appeared saying 'Failed to execute script sasview'.
On a hunch, deleted .sasview and .sasmodels to let the next SasView session recreate them. That fixed the issue.

**User GregS (May 6, 2020):**
Mac with Mojave 10.14.6. Installed 5.0.2 'after using 4.2.2 for some time'.
Created a sum model in 5.0.2. Thereafter 4.2.2 kept crashing.
Tried removing all plugins from \plugin_models but that made no difference. 4.2.2 kept crashing.
On @smk78's advice, deleted .sasview and .sasmodels folders. That fixed the issue. But hen he created another plugin the same issue returned!

**User FedericaS (May 15, 2020):**
Mac with Mojave 10.14.6
'Long time user of SasView'. 4.2.2 suddenly stopped working on Apr27, 2020. Program starts but as soon as a datafile or saved project was loaded it crashed.
[FedericaS_Problem_Report_for_SasView_422.pdf](https://github.com/SasView/sasview/files/4694077/FedericaS_Problem_Report_for_SasView_422.pdf)
User installed 5.0.2 (but don't know if this was as well as or instead of) but then found a different bug...
@butlerpd suggested she try deleting the .sasview folder which she did, but 4.2.2 continued to crash, whether 5.0.2 was installed or not.

**User AnvayP (May 22, 2020):**
PC with Windows.
First time user of SasView. Installed 5.0.2 ok. But on trying to start it got the Fatal Error popup 'Failed to execute script sasview'.
@butlerpd asked him to try deleting .sasview and report back.
@smk78 asked for more details of the installation/account permissions.
No reply received at this time.

**User ErinC (May 27, 2020):**
PC with W10. New user of SasView.
Installed 5.0.2 _'using an admin password'_ (IT policy). Installed ok, but on trying to run the program got the Fatal Error popup 'Failed to execute script sasview'.
UAC was set 1 level below 'Always Notify' (so level 2 of 4).
At @smk78's suggestion, tried deleting the .sasview folder but it didn't help.
Tried installing 4.2.2 instead and that worked without any problems!!!

**User LilinH (May 27, 2020):**
PC with W10. Existing user updating from 4.2.2.
Installed 5.0.2 _'using an admin password'_ (IT policy). Installed ok, but on trying to run the program got the Fatal Error popup 'Failed to execute script sasview'.

**Comment by smk78** [comment]
@butlerpd notes:
>


that the error ... is coming from a try except where the "try" that is failing is a copy command trying to create a custom_config file in your user directory by copying a default version (template) from the C:\Program Files\asview\....

**Comment by smk78** [comment]
Update from user ErinC (May 28, 2020):
>Version 5 installs and runs with no problems on my personal Windows 10 machine.

>It may be a permissions issue as you suggested, Paul. On our work computers, we do not natively have admin privileges and have to generate a temporary admin user name and password.

**Comment by wpotrzebowski** [comment]
When I logged in as regular user and tried to run 4.2.2 installed by admin user (from shared Application folder) SasView 4.2.2 crashed and generated the following message to sasview.log

2020-05-28 22:10:44,968 : CRITICAL : sas._config (_config.pyc:70) :: Error loading /Applications/SasView 4.2.2.app/Contents/Resources/local_config.py: [Errno 13] Permission denied: '/Applications/SasView 4.2.2.app/Contents/Resources/local_config.pyc'

And then after installing local version of 4.2.2 I've experience the problem with cached models generated by version 5.0.2



2020-05-28 22:38:59,829 : ERROR : sas.sasgui.guiframe.gui_manager (gui_manager.pyc:3277) :: gui_manager.clean_plugin_models:

  [Errno 30] Read-only file system: '/private/var/folders/gm/9tskr47j2xx24gq4b8gst65m0000gp/T/AppTranslocation/8831E191-201A-447B-97DA-78DFF856293A/d/SasView 4.2.2.app/Contents/Resources/plugin_models/__init__.py'

2020-05-28 22:39:13,294 : INFO : sas.sasgui.perspectives.fitting.fitpage (fitpage.pyc:1665) :: 1D Data did not contain recognizable resolution info.

2020-05-28 22:39:13,541 : ERROR : sas.sasgui.perspectives.fitting.fitting (fitting.pyc:1888) :: Traceback (most recent call last):

  File "sas/sascalc/data_util/calcthread.pyc", line 274, in _run

  File "sas/sasgui/perspectives/fitting/model_thread.pyc", line 198, in compute

  File "/private/var/folders/gm/9tskr47j2xx24gq4b8gst65m0000gp/T/AppTranslocation/8831E191-201A-447B-97DA-78DFF856293A/d/SasView 4.2.2.app/Contents/Resources/lib/python2.7/sasmodels/sasview_model.py", line 630, in evalDistribution

  File "/private/var/folders/gm/9tskr47j2xx24gq4b8gst65m0000gp/T/AppTranslocation/8831E191-201A-447B-97DA-78DFF856293A/d/SasView 4.2.2.app/Contents/Resources/lib/python2.7/sasmodels/sasview_model.py", line 692, in calculate_Iq

  File "/private/var/folders/gm/9tskr47j2xx24gq4b8gst65m0000gp/T/AppTranslocation/8831E191-201A-447B-97DA-78DFF856293A/d/SasView 4.2.2.app/Contents/Resources/lib/python2.7/sasmodels/sasview_model.py", line 719, in _calculate_Iq

  File "/private/var/folders/gm/9tskr47j2xx24gq4b8gst65m0000gp/T/AppTranslocation/8831E191-201A-447B-97DA-78DFF856293A/d/SasView 4.2.2.app/Contents/Resources/lib/python2.7/sasmodels/kerneldll.py", line 410, in __call__

AttributeError: 'DllKernel' object has no attribute 'q_input'

I will try to further investigate this issue

**Comment by pkienzle** [comment]
There is also ~/.sasmodels/compiled_models which contains cached versions of the DLL models. 
Unlike the GPU cache, these are not tagged with checksum from the source, but instead only look at the time stamps.

Between 4.2.2 and 5.0 the DLL interface changed to support beta approximation so the compiled kernels are no longer compatible.  It's not surprising that this is causing some crashes.

A work around would be to run sasview from a .bat file which sets the SAS_DLL_PATH environment variable somewhere private to that version of sasview then running the sasview.  Or just clear out the ~/.sasmodels/compiled_models directory before switching versions.

**Comment by smk78** [comment]
SasView logfile from user FedericaS:
[Federica_sasviewlog.txt](https://github.com/SasView/sasview/files/4700495/Federica_sasviewlog.txt)

**Comment by smk78** [comment]
A fullsome response from User AnvayP:

> _Which version of Windows are you running?_
**Windows 10 Pro - Version 1909 - OS Build 18363.836**

> _Is it a new desktop with a fresh copy of Windows, and so you are now reinstalling all your apps? Or is it a desktop you have had for a long time, or one that has been upgraded?_
**This is a new desktop which we custom-built and has a fresh copy of Windows. I have installed all the essential applications that we commonly use like [deleted], etc. All the programs work fine except for SasView 5.0.2.**

> _Have you used SasView before? Eg, any of the previous versions?_
**I have worked with SasView earlier but not on this new desktop. I own a MacBook Pro and have tried working with versions 4.2.1, 4.2.2, 5.0.1, and 5.0.2.** 

> _In fact, have you tried installing SasView 4.2.2? Does that start?_
**Apparently, the SasView version 4.2.2. functions and opens normally. This is surprising!**

> _Do you have access to another desktop/laptop you can try installing SasView on?_
**As I mentioned earlier, I own a MacBook Pro. I have installed the version 5.0.2. and it works fine. I don’t have an access to another Windows machine so cannot really tell if it is just not compatible with the desktop we have.**

> _Do you have local administrator rights on the desktop?_
**Yes, I do have local administrator rights on the desktop.**

> _When you installed SasView, did you do it from your account profile, or did you right-click on the .exe and do ‘Run as administrator’, or did you log in as the administrator account to do the installation?_
**I installed the SasView application by right-clicking on the .exe file and running it as an Administrator.**

> _Did you install to the default folder (C:\Program Files\SasView) or somewhere else?_
**Yes, the file was installed to the default folder.**

**Comment by butlerpd** [comment]
While two PR addressing some of the concerns were merged to ESS_GUI master this issue needs to remain open until it is clear all the issues have been resolved. At present there remains some doubt.

**Comment by butlerpd** [comment]
I would like to suggest we close this ticket and open a fresh one based on the dreaded `failed to execute script sasview` error which is I think the only thing that continues to get reported after the two fixes from the last hackathon? 

From a recent user report on Windows 10 who also sent on the entry from the log file it was clear that SasView was failing to copy the default config file to the `.sasview/config` folder as `custom_config.py`  This is not doubt related to #1640 reported on against the unix OS.

The offending code was from `src/sas/_config.py`

```python
def setup_custom_config(app_dir, user_dir):
    path = make_custom_config_path(user_dir)
    if not os.path.isfile(path):
        try:
            # if the custom config file does not exist, copy the default from
            # the app dir
            shutil.copyfile(os.path.join(app_dir, "custom_config.py"), path)
        except Exception:
            logger.error("Could not copy default custom config.")
```

the reported error was coming from the last line suggesting a failed attempt ad `shutil.copy`. Manually copying the default config.py from the source to the `.sasview` directory fixed the problem.

**Comment by smk78** [comment]
OK by me.

**Comment by smk78** [comment]
Closing this issue in favour of #1672
