### ISSUE TITLE
Constrained fitting doesn't work when setting min/max for polydispersity

### ISSUE THREAD

**Issue by wpotrzebowski** [SasView/sasview#1538]
The issue occurs when using Constrained fit (with set up constraints) and polydispersity set up. If one introduces then reasonable min/max values in Polydispersity tab and then do "Fit" , the fitting results is definitely not correct (flat line). This behaviour is not observed with setting min/max for polydispersity in "Single Fit". This can be reproduced by running "Constrained and SImultaneous Fitting" example from http://www.sasview.org/downloads/simultaneous_1d_fitting_in_sasview_v5.pdf and setting min/max when tackling polydispersity

**Comment by wpotrzebowski** [comment]
Additional comment from Lionel:
"The problem with the polydispersity  is that when you fit, sometime it ignores the polydispersity you put and goes to some default values and the fit goes south…and as you describe, sometime goes to 0. when you click and unclick and do many thing, then SASview is lost or does not care about your wishes.."

**Comment by butlerpd** [comment]
This is probably related to #1521 and even #1522  These should probably be addressed together until they can be separated (if indeed these are unrelated issues -- though that seems doubtful)

**Comment by m2cci-NMZ** [comment]
This could be at least in part related to the fact that the `sasmodel` polydispersity is not updated with the GUI values. The fit is then performed whith the default values (or the values of a previous fit, as fitting effectively updates).

**Comment by butlerpd** [comment]
The linked pull request was merged as part of Hackathon-I but failed to close the issue so closing now
