### ISSUE TITLE
Corfunc requires two shots to populate the data name box

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#1539]
as of 5.0.2, for some reason, when sending to data to corfunc, the dataset name does not get picked up by the GUI unless it is sent a second time (so clicking twice on `Send data to` button). Note that the data itself does seem to be sent and plots appropriately. This is true on both Mac and PC This is not the case for the other perspectives.

Observerd both on mac and PC

**Comment by smk78** [comment]
Also see #1528
