### ISSUE TITLE
Corfunc GUI plot initialization idiosyncrasies

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#1540]
As of 5.0.2, when choosing corfunc as the perspective for the next `Send data to` operation it brings up not only the parameter and input panel but two blank plot pages.  However, while these have default scales on the axes they neither have their plot name (`Scattering data` for the top plot and `Real Space Correlations` for the bottom) nor the axis labels [e.g.  `I(Q)` vs `Q` for the top]

Two other things about these plots that are problematic:
1. They are clearly using a different plotting routine as the rest of SasView as can be seen from the (rather ugly) standard matplotlib toolbar at the bottom of the plot.  That said, there have been other request for better toolbar functionality on regular SasView plots, so this may be a case of needing to have a discussion on GUI design and user needs?
2. Corfunc also is "violating" the standard way perspectives behaves in SasView which is part of what leads to the initial comment.  Basically it seems to be creating a panel with inputs and two plots as a single panel so the plots cannot move around or be stretched independently of each other or the rest of the panel.  it does however have the advantage of preventing the multiplication of random floating plots everywhere which is a huge issue when working on big projects.   Again this may be an opportunity to open a discussion on GUI design and user needs.  In the end though we should strive to maintain some sort of uniformity.

Noted on both PC and mac

**Comment by lucas-wilkins** [comment]
Can we discuss this at meeting, in particular how this would fit with any upcoming changes of the plotting system.

**Comment by lucas-wilkins** [comment]
Corfunc has been changed significantly since this issue. In summary, the plots are now better, they do "violate" the floating plots system, this is perhaps not a bad thing though. There are currently some things to bring up to date still, but there are separate issues for them.
