### ISSUE TITLE
Crosstalk between Corfunc and Invariant perspectives

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#1542]
As of 5.0.2, if one sends data to corfunc and plots it, then sends the same data to the invariant all behaves as expected.  However, if in fact the data is sent to Corfunc and the correlation function plotted (hitting `extrapolate` and then `transform`) so that the second plot (the `Real space data`) before then sending the same data set to the invariant, there are two things wrong:
1. the axis labels have now changed from I(Q) vs Q to gamma vs x(A)
2. The plot not only contains the I(Q) data but also 3 lines whose labels suggest they are the `1D Correlation` the `3D Correlation` and the `Interface Distribution Function` which now, as described in issue #1541 get replicated in every plot every time one updates and recomputed the invariant.

NOTE: This can be fixed by sending the data to some other pesrpective and then sending back to the Invariant.

Seen on both Windows  and Mac

**Comment by smk78** [comment]
Quoting @butlerpd above:
>NOTE: This can be fixed by sending the data to some other pesrpective and then sending back to the Invariant.

Actually, not quite. If you need to use the _Append to_ button you will find _every dataset created in your session gets appended_ to the graph!

**Comment by butlerpd** [comment]
? I think that is another bug @smk78  ... or feature request some might say, which I forgot to enter but was meaning to. Or did I misunderstand your comment?  basically, if you try to plot any dataset that has been used for fitting of various kinds you have to tick the box then create (or append) to plot will plot that data set and ALL the children of that dataset.  That is because when you tick that box the default is to ALSO tick the **hidden** boxes of all the child plots.
Another problem I have is that the number of child plots becomes very unwieldy and not sure we need them all there but that is probably a much bigger and deeper design/logic issue

I will try to create this issue soon. is this the issue? or is it really the cross talk specifically between invariant and corfunc?

**Comment by smk78** [comment]
No it's a general issue. If you use, say, corfunc, then invariant, and then fitting, and then find you want to append to the last graph window, _everything_ SasView seems to know about gets appended, I(q) data, models, correlation functions, IDF's,...

**Comment by butlerpd** [comment]
Good -- that is the other known issue but independent of this one.  I will make it now.  This issue is only a problem with invariant and corfunc and related to fitting in each.  It does not cross talk with fitting in invariant or fitting from my tests.

**Comment by wpotrzebowski** [comment]
ready for testing on OSX
