### ISSUE TITLE
SasView application window needs to be scrollable 

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#1543]
I suspect it was a conscious decision to remove the scrollable nature of the application window as well as most all windows within the application that were implemented in 4.x.  However, despite a lot of work to reduce the infinitely long panels (by adding tabs etc) and some attempts, I think, at clever estimation of real estate, the fact remains, that the number and variety of hardware, and more importantly screen form factors, that people will use is too large to guess so that two problem occur:
1) a new perspective will likely get released unusable by many until enough different users, with different hardware, have tried it (see issue #1332).  One can of course try to have a list of rules for handling the sizing of the perspective under various scenarios but would require quite a lot more effort and discipline that is likely given current resources on the project?
2) In some cases it will always remain unusable. For example running 5.0.2 on my laptop through a browser (I am using Paperspace but our summer schools use amazon's version of virtual desktops and I expect this approach to only grow with time). 4.x can be a bit painful with the scrolling but perfectly functional for quick checks/fits/modeling whereas 5.0.2 is useless: Aside from corfunc not being accessible, even removing the footer bar (never mind the console log) I cannot see anything below the title to the plot box nor can I see any of the buttons on the bottom of the fit page (so cannot show plot, fit or get help). Even inversion I can only reach the calculate button by removing the footer bar. Note that using the same virtual box on my 27" monitor things were perfectly... except of course corfunc.

NOTE that this was not a problem in mac through 4.x because all panels were free and independent. However, now that the mac is also enforcing the entire SasView workflow to remains inside the main SasView window I believe this will also be a problem for the mac

**Comment by butlerpd** [comment]
Have had another, generally very happy user note the problem of not being able to reach the critical buttons (like fit 😄 ) when using their laptop.  As this renders the program literally unusable, and in view of what else we are labeling critical, am raising this to critical.

**Comment by rozyczko** [comment]
What needs to be done (most likely) is adding QScrollArea element between the main canvas and the QDockWidget. This should allow scrolling of the whole main area.

**Comment by butlerpd** [comment]
Will try a quick fix to prevent accidental zooming of graphs
