### ISSUE TITLE
Sasview 5.0.2 "file converter" tool does not open

### ISSUE THREAD

**Issue by toqduj** [SasView/sasview#1548]
OS: Mac OS X 
Opening the Tools > File Converter tool gives the following error:
"ERROR: 'GuiManager' object has no attribute 'image_viewer'"

**Comment by krzywon** [comment]
Running Windows 10 and installed version of 5.0.2, all items in the Tools menu load as expected for me. This might be a Mac specific issue. @wpotrzebowski?

**Comment by wpotrzebowski** [comment]
Yes - it doesn't work on mac. I will try to fix it for 5.0.3 it should rather be easy fix.

**Comment by butlerpd** [comment]
Actually, now that I think about it, given what is being called critical maybe this is more in the major category at present?

**Comment by wpotrzebowski** [comment]
The fix seems to be trivial but using this opportunity to write test for it.
