### ISSUE TITLE
Cancelling Save Project dialog throws

### ISSUE THREAD

**Issue by rozyczko** [SasView/sasview#1551]
A simple case of missing early return on cancelling the Save Project dialog.
Exception is caught and displayed and no other effects are present, just looks bad in the Log Explorer.

**Comment by rozyczko** [comment]
Similarly, Edit/Save Params to File dialog upon cancelling

**Comment by krzywon** [comment]
I think I fixed this issue in #1775 with commit https://github.com/SasView/sasview/pull/1775/commits/a1596b1c954e536b121be091c6d86c7ce919448c

**Comment by butlerpd** [comment]
@krzywon and @rozyczko. My test suggests that the first issue (save project) is fixed but that the second one " Edit>Save Params to File" Still has the issue.  Let me know if I'm wrong and thi should be closed. Meanwhile I will move it to 5.1. If I am correct should this be labeled a good first issue? or is it more complicated?

**Comment by rozyczko** [comment]
You are right, @butlerpd - it has not been fixed for this action (Save Params to File). Considering this involves just looking up the error handling from "Save Params" and copy/pasting it, I would conider it a great first issue bug. Assuming we want to postpone it to the next release, rather than fix on the spot?

**Comment by butlerpd** [comment]
Ok .. moving it back to 5.0.5 and we can discuss whether to fix "on the spot" or not.

**Comment by butlerpd** [comment]
The merge should have closed this but it didn't :-( so closing now
