### ISSUE TITLE
ESS_GUI: annulus slicer not opening

### ISSUE THREAD

**Issue by murphyryanp** [SasView/sasview#1554]
I tried opening the annulus slicer tool from ESS_GUI, but it fails to open and gives the error in Log Explorer: 

> File "C:\Users\murph\sasview\src\sas\qtgui\Plotting\Slicers\AnnulusSlicer.py", line 32, in __init__
    self.xmaxd = self.xmax
> AttributeError: 'AnnulusInteractor' object has no attribute 'xmax'

After looking through the branch history, this error (as well as batch assignment and slicer parameters) was already addressed by Piotr in the branch called "ESS_GUI_1381_slicer" regarding #1381, but this branch was never merged into ESS_GUI.

Should this lost branch be tested and merged for the next release?

**Comment by butlerpd** [comment]
Nice catch @murphyryanp.  I suspect that @rozyczko had bigger plans for this branch? @rozyczko what do you think? should we merge this? or should we make a new branch just for this issue? would be good to fix this bug in 5.0.3.

**Comment by rozyczko** [comment]
We *must* merge this, preferably creating a new branch and cherrypicking relevant changes from `ESS_GUI_1381_slicer`.
This branch was supposed to go into 5.0.2 but at some point we decided to postpone the batch slicer functionality and I missed the fact that the branch contained a critical fix. 
Thank you @murphyryanp for finding it!
This could actually be a good first issue for you, if you don't mind looking at it closer?

**Comment by murphyryanp** [comment]
@rozyczko  Sounds good. I'll create a branch from ESS_GUI and add your relevant changes from the ESS_GUI_1381_slicer branch
