### ISSUE TITLE
wx4: constraints dialog not rendering properly

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#1558]
The constraints dialog is not rendering properly in wx 4 on the mac.

Should probably be fixed if releasing sasview 4.3 with wx4.

**Comment by butlerpd** [comment]
@pkienzle - I believe this was fixed by PR #1573 which was merged in September 1 2020.  Can we close this issue?

**Comment by lucas-wilkins** [comment]
Not using wx anymore
