### ISSUE TITLE
Default Checkboxes in data manager need changing

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#1566]
The biggest problem here relates to the fact that every action that spawns "children" (the two plots from corfunc, the several ones from fitting like P and S and function etc) are **correctly** hidden in the data tree (i.e. the data tree does not unfold automatically).  However checking the top level data also checks **ALL** the children (but that action is completely hidden from the unsuspecting user) so that when the user next clicks on create graph, or append to graph, they are not only sending the plot they meant to send but the sometimes large number of associated plots. 

There could be a few different approaches, but given that most often one does not want to send all the children to a plot (actually almost never is it all of them anyway) I think the correct answer is that the children do not inherit the checking automatically but that the user has to unfold the tree and manually pick those children plots they want to plot.

Separate but on a similar default checkbox issue, I would argue that when loading a series of data, either they are **not** all selected by default (my number one choice) OR the default menu item on the selection drop down si `unselect all` rather than `select all` since that is pointless if they are all already selected by default.

**Comment by rozyczko** [comment]
How about the `tristate`? 
![001-threestate](https://user-images.githubusercontent.com/8266281/83292483-71affe80-a1ea-11ea-93ba-10366f258ab8.png)

Single click -> select only the top level (main) dataset, double-click -> select the top level and all underlying datasets.
This is behaviour similar to what is often used in various installers, which ask which features to install in the form of a tree-like list.

**Comment by rozyczko** [comment]
Manually selecting/deselecting sub-datasets would automatically put the main dataset checkbox in the `indeterminate` state

**Comment by butlerpd** [comment]
so the 90% use case will be in my estimation selecting only the top level data. If the selection box is checked does that mean only it is checked? or that all the hidden ones that most people don't even know about are checked? how do I tell the difference visually? or does the second click unroll the tree for me and shows the others checked?

I have to say that I think the manual unrolling and checking would be safer for users.  It will be very rare when what people want is really all the plots at once.  What will be desired way over 50% of the time is just the parent data and from time to time we will want a couple of the children, sometimes with, sometimes without, the parent plotted together.

So the more I think about it the more I think the tristate will be more confusing than helpful? @smk78 or others .. what do you think?

**Comment by RichardHeenan** [comment]
Agree - let's keep it simple. I would manually unroll the top entry, expect to find all the underlying data sets unchecked, then just check the one(s) that I want to append or send. Most of the time we are just looking to add P(Q) or S(Q), or perhaps a previously frozen theory to compare.

(I'm sure that the same or a similar issue was actually fixed earlier this year ???)

**Comment by smk78** [comment]
I did 'thumbs up' @butlerpd 's comment earlier; but I concur.

**Comment by rozyczko** [comment]
Great! This makes it very easy to fix then.
