### ISSUE TITLE
Changing perspective closes the perspective (ESS_GUI)

### ISSUE THREAD

**Issue by krzywon** [SasView/sasview#1578]
While trying to work through #1526 I came across an issue when changing perspectives. In 5.x when changing between perspectives the current perspective is closed and a new one is opened. This causes any information currently in the perspective to be thrown away. Only the charts are retained. In 4.x, the perspectives are hidden and always present in the background, retaining fit information when going back and forth.

The use case against closing perspectives: A user wants to run a complex, constrained fit on a series of data sets and then, after running the fit, wants to find the invariant for a data set or two. As soon as the user switches to the invariant state, the complex constrained fit is thrown out and won't return when returning to the fitting perspective.

I would suggest in 5.0.3, at the very least, when switching between perspectives, warn the user the information will not be retained.

**Comment by rozyczko** [comment]
Merged so closing.
