### ISSUE TITLE
Generating reports is failing on OSX

### ISSUE THREAD

**Issue by wpotrzebowski** [SasView/sasview#1581]
There are no graphs when one tries to save a report and following error is generated.
Traceback (most recent call last):
  File "site-packages/xhtml2pdf/tags.py", line 347, in start
  File "site-packages/xhtml2pdf/xhtml2pdf_reportlab.py", line 485, in __init__
  File "site-packages/xhtml2pdf/xhtml2pdf_reportlab.py", line 506, in getImage
  File "site-packages/xhtml2pdf/xhtml2pdf_reportlab.py", line 367, in __init__
RuntimeError: <class 'RuntimeError'> Imaging Library not available, unable to import bitmaps only jpegs fileName=<_io.BytesIO object at 0x12af23f10> <traceback object at 0x128f27388>

Print doesn't work either (QPrintDialog: Cannot be used on non-native printers). Therefore it is critcial for OSX. For printer error upgrading pyqt version may solve a problem.

**Comment by wpotrzebowski** [comment]
Interestingly enough, it seems to work from local environment.

**Comment by pkienzle** [comment]
Looking at [the code](https://github.com/xhtml2pdf/xhtml2pdf/blob/3f5af31a630eecfc0ffd020f76b99486c35eac97/xhtml2pdf/xhtml2pdf_reportlab.py#L356-L361) the error message is misleading. It will already have imported `readJPEGInfo` from `reportlab.pdfbase.pdfutils`, and anyway the called function doesn't use external imaging libraries.

Looking into [reportlab](https://bitbucket.org/rptlab/reportlab/src/9bb6ebf1b8473e3dc11740cbdce0d5dc1a1afae2/src/reportlab/pdfbase/pdfutils.py#lines-222), I'm going to assume `PDFError` can be imported, so we are left with there being a file read error or invalid precision or unsupported marker in the jpeg file.

So, yes, very strange that it works from a local environment. Clearly the bundled environment has the required packages.

You could try instrumenting reportlib in the distribution version by monkeypatching `readJPEGInfo` from the console with:
```python
import logging
import traceback
import reportlab.pdfbase.pdfutils
_readJPEGInfo = reportlab.pdfbase.pdfutils.readJPEGInfo
def readJPEGInfo(*args, **kw):
    try: _readJPEGInfo(*args, **kw)
    except Exception:
        logging.error(traceback.format_exc())
        raise
```
This should let you see what the error is in sasview.log.

**Comment by smk78** [comment]
User Ryan C reports:

When I save the report I get the following error from 5.0.3:

RuntimeError: <class 'RuntimeError'> Imaging Library not available, unable to import bitmaps only jpegs fileName=<_io.BytesIO object at 0x7ffd3a843ca8> <traceback object at 0x7ffd34e77608>

When I installed Xcode I installed the bare minimum of the command line tools because installing the full Xcode library was 10GB or so and I didn’t have enough HDD space? Is it that I am missing some libraries or scripts that SasView is trying to call and I just need a full Xcode download? Just in case it matter, it’s a mid 2013 4GB ram macbook air running macOS BigSur 11.0.1.

**Comment by wpotrzebowski** [comment]
Definitely not elegant but working solution is to choose HTML option while saving the report file:
![image](https://user-images.githubusercontent.com/4189922/102265914-0b859180-3f18-11eb-8a30-bdf80b997fd2.png)
Then open HTML in web browser  (or whatever is used to open html files) and save it to pdf.

**Comment by wpotrzebowski** [comment]
It works with 5.0.5

**Comment by lucas-wilkins** [comment]
Do the changes in #2065 solve this, I cleaned a bunch of stuff up that might have?

**Comment by lucas-wilkins** [comment]
Oh, it's already fixed, never mind.
