### ISSUE TITLE
Need to remove obsolete sasgui package from 5.x

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#1582]
when the new 5.x version to be built on qt was forked, the old sasgui was kept intact and a parallel package: qtgui was created instead.  In principle to make it easier/faster to work on porting functionality.

It's utility has long since passed and currently only adds bulk to the 5.x codebase and confusion for new developers trying to locate the gui bits. The entire directory should be removed.

On an aside the PDF intro and overview on the wiki for new developers should be updated as it points to sasgui rather than qtgui as the gui source.

**Comment by rozyczko** [comment]
Please note that `src/sasgui` does not get built nor is it included in the final installer. It's just in the source tree. I agree that it is confusing and might be misleading to new developers, so I'll remove it.
We can always query `sasgui` looking at the (current) `master` branch.

**Comment by butlerpd** [comment]
Good to know it is not getting carried around in the release installables.  Thanks for the clarification. But I agree: the primary reason to remove it is that it mostly confusing to new developers and/or to those of us who are bouncing between 4x (which uses `sasgui`) and 5.x (using `qtgui`) and serves no real purpose anymore. We should be looking at 4.x mostly now for things we might want to still cherry pick not the ancient `sasgui` version as that has not kept up I don't think?

Also to remind again our instructions for new [developers of 5x](https://github.com/SasView/documents/blob/master/CodeCamps/CodeCampIX/SasViewDevIntro.pdf)  implies they should be working in either `sasgui`, or in one case it specifies `sasgui/qtgui` neither of which are now correct (probably too late to revert to sasgui ☹️ .  So we should also fix that pdf documentation.

**Comment by butlerpd** [comment]
@rozyczko ... I believe this was resolved when we merged your PR #1592 was it not? Can we close this ticket?

**Comment by butlerpd** [comment]
sasgui has indeed been removed from main.  However the intro for developers overview remains incorrect.  I will close this ticket and create and admin ticket regarding updating the intro slides posted on the wiki for new developers
