### ISSUE TITLE
Legend + MPL Toolbar

### ISSUE THREAD

**Issue by sl-saxs** [SasView/sasview#1584]
I've just tried running SasView, downloaded from the ESS_GUI branch.
The context menu (right-click into the plot window) now shows the options "Toggle Navigation Menu" and "Toggle Legend".
"Toggle Navigation Menu" gives the MPL toolbar. Zoom, Pan, Home, Back and Forward do work fine. However, choosing "Edit axis, curves and image parameters" from the MPL toolbar opens a window with two tabs "Axes" and "Curves" where one can edit the plot style, legend, etc. So what I did is:
    1) Changed the legend the label from "M1 [flexible_cylinder]" to "mm". This changes don't appear in the legend and they don't appear in the context menu "M1 [flexible_cylinder]" -> "Modify Plot Properties"
    2) Changed the plot style from "Solid line" to "Octagon" -> these changes don't appear in the context menu "M1 [flexible_cylinder]" -> "Modify Plot Properties" where it still says that the curve is plotted as a solid line whereas in the plot window the curve now appears as "Octagon".
    3) Changed plot style in context menu "M1 [flexible_cylinder]" -> "Modify Plot Properties" to be "Red" and "Circles". The curve is now displayed as red circles. But choosing "Edit axis, curves and image parameters" from the MPL toolbar now opens a window with only one tab "Axes" where before it showed two tabs "Axes" and "Curves". It was the "Curves" tab where one could modify the plot style and the legend. But the comboBox in the "Curves" tab only showed one curve to be edited, in that case "M1 [flexible_cylinder]". But more curves were shown in the plot window.
   4) If one goes from the context menu "M1 [flexible_cylinder]" -> "Modify Plot Properties" and deletes the "Legend label" completely, the legend remains unchanged in the plot window. If the "Legend label" is just modified instead of deleted completely, the modifications appear on the plot window.
   5) from the context menu -> "Toggle Legend". Makes the legend disappear if it is visible and makes it appear if it is invisible. If the legend is invisible and another curve is added to the plot or if parameters of the currently plotted curves are changed, the legend pops up again. It seems that the legend invisibility doesn't persist.

**Comment by rozyczko** [comment]
Meh, yeah, that's one issue with the toolbar - the `Edit` functionality has been implemented separately, as right click context menu operations. Toolbar `Edit` options are a bit wonky so I might need to remove the Edit icon after all.

**Comment by sl-saxs** [comment]
And on top of that, the MPL changed the toolbar. I just realised that after updating from version   "3.1.2" to version "3.2.1"

**Comment by smk78** [comment]
6) if you minimise [-] a residuals plot to reduce clutter on your screen real estate, as soon as you do anything that forces a re-draw of the data, the residuals plot pops back up!

**Comment by rozyczko** [comment]
Re 6. I'm pretty sure someone at some point requested this behaviour! I don't remember who and when so will have to search through the issues to find the reasoning. There's quite a lot of logic allowing for raising the windows when needed, so this isn't accidental. However, I agree it is annoying - to me as well. I'll gladly switch it off if nobody complains :)

**Comment by smk78** [comment]
If it was requested, maybe it was before you implemented your neat way of stepping through the windows? :-)

**Comment by butlerpd** [comment]
There was another request that came up in working through examples with @skrueger111 and @Susyana for more plot customization (like grid on off, major and minor ticks on axis etc). Rather than remove the edit from the toolbar could we just make the pop up menu items call the same functions as the toolbar rather than re-implementing? then there should be no conflict anymore?

**Comment by butlerpd** [comment]
As I recall we had similar propblems in 4.x and in the end basically "overwrote" the MPL toolbar so that it could be customized?  my memory is vague but maybe we can look back at that?

**Comment by butlerpd** [comment]
The toolbar issues were reworked significantly to avoid these conflicts. I think I will close this at this point. Any more issues can be documented in a fresh issue
