### ISSUE TITLE
ESS_GUI: plugin editor not updating model

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#1597]
After modifying a model in the plugin editor and replotting, the fitpage appears to show the old version of the model.

Perhaps the models are not being properly cleared from memory by the editor?

**Comment by butlerpd** [comment]
Actually, if the model is currently running, SasView does not notice that a change has been made and reload before computing again. However switching to a different plugin and back DOES reload the model including the changes.

Likewise, if Plugin Models category is chosen, adding a new model does not update the model dropdown menu. However, choosing a different category then switching back to Plugin Models DOES reload the list of models including the newly created one.

**Question:** Do we really want SasView to be constantly scanning the plugin directory for changes ... for all open fitpages?   While it is a bit ugly, I'm not convinced that the current behavior is not the correct one? However, even if we leave this behavior, it would be good to document better AND to include that in a tutorial on model writing?

**Comment by rozyczko** [comment]
It's fixed. I originally didn't want the model to be directly notified about a new plugin, since this can occasionally present visual artefacts with the list briefly vanishing and showing again but it seems this isn't happening in the newest Qt?

**Comment by butlerpd** [comment]
Hummm.... I had the same concern hence the question. I guess you are answering it? 😄 Lets see if it is robust I guess.

**Comment by butlerpd** [comment]
This did not close as the merge was not to the default branch (`main`) and linked keywords therefore ignored. Will close this manually now.
