### ISSUE TITLE
Invariant does not report the total invariant

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#1606]
In 5.x series the invariant appears to only always report the invariant under the actual data on the front panel (under `Invariant Total [Q]` regardless of whether or not extrapolation is chosen. The only way to get the total would be to click the status button and sum the contributions.

Given the value being reported is called "Total" (and would be expected to be the total) I am labeling this as critical.

**Comment by smk78** [comment]
4.x _master_ **is** correctly returning the Invariant Total (ie, the sum of the low-Q integral + data integral + high-Q integral)

**Comment by wpotrzebowski** [comment]
Yes, it seems that 5.x is missing: 
        https://github.com/SasView/sasview/blob/6a2ee0f4409754e896d5293c0756cc67934b6930/src/sas/sascalc/invariant/invariant.py#L803
https://github.com/SasView/sasview/blob/6a2ee0f4409754e896d5293c0756cc67934b6930/src/sas/sascalc/invariant/invariant.py#L804
https://github.com/SasView/sasview/blob/6a2ee0f4409754e896d5293c0756cc67934b6930/src/sas/sascalc/invariant/invariant.py#L805

**Comment by butlerpd** [comment]
I believe this ticket should be closed. I t was addressed in the July hackathon and fixed in 5.0.3 if memory serves.  Part of the problem of conflating issues and PR in the sprint project board I think?

**Comment by krzywon** [comment]
I just checked in release v5.0.3 and this is fixed.
