### ISSUE TITLE
No Q-limit bars in Invariant Perspective

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1608]
Testing 5.0.3 as local build on W10/x64.

Unlike when fitting or using correlation function analysis, for example, when you click on one or other of Min or Max boxes under Total Q Range in the Invariant Perspective, no draggable limit bars appear in the plot window.

**Comment by butlerpd** [comment]
This would be very good both from the utility point of view AND the consistency point of view where one might expect similar behaviors from different perspectives.  We should note however that it would be a new feature not available in 4.x so I think "enhancement" would be a better tag?

**Comment by krzywon** [comment]
Closing in favor of #1728
