### ISSUE TITLE
Chart in Invariant Perspective Status Dialog not displaying the low-Q contribution to Q*

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1610]
It appears that no matter what data you load, or what low-Q extrapolation you perform on it, the percent Q* from Low-Q in the **chart** in the Status > Dialog window is always exactly zero!

In 4.x, even fractions of a percent to 2 dp are shown.

Interestingly, the Dialog window does show a numerical value for the contribution to Q* from Low-Q.

**Comment by butlerpd** [comment]
This is not exactly true (at least not anymore).  The problem I believe is the widget used for this graphical display is rounding down to the nearest integer which is zero in most cased of the data we have if using both low and high extrapolation.  It may be possible to set the a floating point precision but if not I suggest we close this ticket as not worth the effort to rewrite the whole GUI widget given the numerical values are displayed.  At least in the ESS_GUI_174_Invariant branch, using the high q data from the latex xml data set and **only** extrapolating to low Q the low Q chart shows 2%.
