### ISSUE TITLE
Inconsistent behaviour of extrapolation Fit/Fix radio buttons in Invariant Perspective

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1611]
If you Enable High-Q extrapolation, select **_Fix_**, enter a _Power_, and then click _Calculate_, an extrapolation is generated, but the radio button jumps back to **_Fit_**.

This does not happen in 4.x and could catch out the unwary?

**Comment by butlerpd** [comment]
Note this may be the same code (or part of the same code) causing the problem in #1604 which does the same thing if you choose power law instead of Guinier -- though in that case the power law is not calculated but the radio button jumps back to power law.
