### ISSUE TITLE
High-Q extrapolations in Invariant Perspective give different shape extrapolations in 4.x and 5.x

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1614]
In 4.x, these data/parameters/settings

![image](https://user-images.githubusercontent.com/10938679/86371404-c0810600-bc78-11ea-8296-fa20affdbbb8.png)

gave this plot

![image](https://user-images.githubusercontent.com/10938679/86371451-c8d94100-bc78-11ea-86ed-7179057d4f70.png)

In 5.x the same data/parameters/settings gave this plot

![image](https://user-images.githubusercontent.com/10938679/86371582-f32afe80-bc78-11ea-81a0-16ae59679c15.png)

The 5.x extrapolation looks like a Q<sup>-4</sup>, the one in 4.x does not.

**Comment by krzywon** [comment]
In the invariant calculator, the invariant data are modified as in [A] prior to the extrapolation calculations<sup>(1)</sup>. This behavior is in both 4.x and 5.x.
`[A] data_used_to_calculate_extrapolations = (scale * original_data) - bkg`

In 4.x, the extrapolated data have the scale and background reapplied before plotting as in [B]<sup>(2)</sup>. In 5.x, the extrapolated data is plotted without the application of scale or background.
`[B] plotted_data = (extrapolated_data + background) / scale`

My question - **should the scale and background be applied to the extrapolations in this way?** As @smk78 suggested, the 5.x extrapolation looks like a Q<sup>-4</sup>, and I think the invariant calculator is correctly calculating this. If 5.x is correct, this ticket should go to the graveyard. If 4.x is correct, I am already working on other invariant fixes and can easily apply this change to the branch I'm working on.

References:
(1) [Invariant in sascalc lines 427-447 in the main branch (code is the same as in master)](https://github.com/SasView/sasview/blob/main/src/sas/sascalc/invariant/invariant.py#L427-L447) showing the data manipulation used in the invariant calculator
(2) [Invariant perspective lines 317-321 in the master branch](https://github.com/SasView/sasview/blob/master/src/sas/sasgui/perspectives/invariant/invariant.py#L317-L321) showing the scale and background applied to plots

**Comment by krzywon** [comment]
After some discussion with @smk78 and @butlerpd, this seems to be more of a preference issue rather than a bug. I will document the change for 5.x as part of the invariant work I've been doing.
