### ISSUE TITLE
Acknowledgement & Citation section missing from 5.0.2 Release Page

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1615]
Our usual Acknowledgement and, more importantly, the Zenodo DOI, for v5.0.2 needs adding to the 5.0.2 Release Page at https://github.com/SasView/sasview/releases/tag/v5.0.2. Cf with earlier versions for text and style.

The Zenodo record page for 5.0.2 is at https://zenodo.org/record/3752443#.Xv9s9IgZ6yI

**Comment by wpotrzebowski** [comment]
Added
