### ISSUE TITLE
ESS_GUI: Model label on plot keeps being reset

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1616]
Noticed by User EmilyE on Mac. Verified by @smk78 on Windows. Using 5.0.2.

Matplotlib really, really, doesn't like long dataset names. If you display such a dataset the actual graph gets squashed up in favour of displaying the legend! Like this:
![image](https://user-images.githubusercontent.com/10938679/86573418-49938800-bf6c-11ea-80dd-b1e7809ae969.png)
You can use Modify Plot Property for each dataset on the plot to change the label for that data to something more manageable, for example
![image](https://user-images.githubusercontent.com/10938679/86573633-91b2aa80-bf6c-11ea-8d10-2c925e18bcc3.png)
But, if you then change any parameter in the model, forcing a re-draw, the _model label_ gets reset, like this:
![image](https://user-images.githubusercontent.com/10938679/86573851-dcccbd80-bf6c-11ea-9271-e5329e7235d5.png)
Which is very irritating!

Modify Plot Property doesn't seem to give any control of the font size of legend text?

As a more general comment, I think the default font size of legend text could be reduced. Maybe by two font sizes?

**Comment by smk78** [comment]
This foible, together with points 5) & 6) in https://github.com/SasView/sasview/issues/1584, have been driving me mad this week!

**Comment by RichardHeenan** [comment]
> This foible, together with points 5) & 6) in #1584, have been driving me mad this week!

The work-around for the residuals re-plot is to drag the residuals plot down or sideways in the new "expanding screen".

**Comment by butlerpd** [comment]
can @krzywon or @rozyczko verify that the second problem has been fixed? My test with one of our hackathon PR shows that once I change the label from the file name to something else, that new value sticks no matter how many replots are done including a full fit.  The first issue is still an issue but maybe that is also addressed with some file name work @krzywon?

**Comment by wpotrzebowski** [comment]
@butlerpd On OSX it still seems to be resetting whenever I change parameter value or fit. This may be because code for OSX is branched from Windows in the few places (something that we did when we tried to address huge legends issue on Mac). I will take a look at this.
