### ISSUE TITLE
Deal with PyOpenCL on Mac build

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1617]
@pkienzle notes in response to PyOpenCL issues encountered by Mac User EmilyE (failing double precision compilation on Intel):

> The mac build should include a newer version of pyopencl or we should add the following to src/sas/qtgui/MainWindow/MainWindow.py(70):
>
>    \# CRUFT: only needed for versions of PyOpenCL < 2019.1.2 (Nov 7, 2019)
>    if sys.platform == 'darwin':
>        os.environ['PYOPENCL_NO_CACHE'] = '1'

Also see https://github.com/SasView/sasmodels/issues/365

**Comment by pkienzle** [comment]
This was addressed in sasmodels by https://github.com/SasView/sasmodels/pull/415.
