### ISSUE TITLE
5.0.3 RC1 problems with installation/running on Windows

### ISSUE THREAD

**Issue by rozyczko** [SasView/sasview#1622]
**_Some windows 10 64 machines have problems installing and/or running 5.0.3rc1._**

Observed behaviour includes:
- program crashing after displaying splash screen
- program does not start showing ‘unable to execute script sasview’ message
- program would not install to default location (when run as no-admin user)
- installation of 5.0.3 affects existing 5.0.2 installation, which can't start anymore

Some installations have one or more of the above issues present.

**_A separate ticket https://github.com/SasView/sasview/issues/1623 concerns crashes encountered trying to use 5.0.3 RC1 for model-fitting._**

**Comment by rozyczko** [comment]
Steve's report attached
[Report.wer.txt](https://github.com/SasView/sasview/files/4895912/Report.wer.txt)

**Comment by rozyczko** [comment]
Local testing:
Neither of the 4 machines I tried 5.0.3 on experienced any problems with running it, neither on non-admin user accounts nor with elevated UAC.

Bare metal windows 10 64, ver. 2004, build 19041, KernelBase.dll: 2020-07-08, version 10.0.19041.329
Bare metal windows 10 64, ver. 1909, build 18363, KernelBase.dll: 2020-05-13, version 10.0.18362.815
VM 1: windows 10 64 Edu,  ver. 1903, build 18362, KernelBase.dll: 2019-03-19, version 10.0.18362.1
VM 2: windows 10 64 Edu,  ver. 1803, build 17134, KernelBase.dll: 2020-03-31, version 10.0.17134.1425

I don't think it has to do with neither OS or the KernelBase.dll version.

All are running English version of the OS, two of these machines never had SV installed. Two have active GPUs, two don't.
The installer taken directly from the GH page:
https://github.com/SasView/sasview/releases/download/v5.0.3rc1/setupSasView-5.0.3-Win64.exe

**Comment by m2cci-NMZ** [comment]
Tried on Windows 8, SV started, but crashed **specifically** when fitting if I selected more than one parameter for fitting. Enabling/disabling OpenCL had no effect.
I inspected the dump file created by Windows with WinDbg, and it seems that the error is coming from `mkl_intel_thread.dll`
I've attached the dump analysis, unfortunately, my knowledge of Windows is poor so I can't get anything usefull out of it :-(
Hope this helps!
[SV_crash_dump.txt](https://github.com/SasView/sasview/files/4896753/SV_crash_dump.txt)

**Comment by smk78** [comment]
I would suggest we _not_ pollute this ticket with the 'crashing during fitting' issues that @RichardHeenan started flagging yesterday. I'll open another ticket for those and copy @m2cci-NMZ 's comment above over.

**Comment by smk78** [comment]
Summarising the testing I and several of my colleagues did yesterday:

**My experience**
Laptop
Microsoft Windows 10 Enterprise Version 1903 Build 18362.900, KernelBase.dll: 12/06/2020 version 10.0.18362.815
UAC set to highest (upper) setting = least permissive

Downloaded setupSasView-5.0.3-Win64 from https://github.com/SasView/sasview/releases/tag/v5.0.3rc1
On running the installer...
![image](https://user-images.githubusercontent.com/10938679/87045109-668bbd80-c1ef-11ea-9101-5817175d2606.png)
Clicked 'More info'...
![image](https://user-images.githubusercontent.com/10938679/87045176-7c00e780-c1ef-11ea-98a3-d6c352f70daf.png)
And then 'Run anyway' and opted to extend the name of the default (\SasView) installation folder...
![image](https://user-images.githubusercontent.com/10938679/87045290-9fc42d80-c1ef-11ea-971f-1527ae99d5b6.png)
**NB: My \Program Files already contains \SasView-v422, -v500, -v501 and -v502 folders and all those versions run happily.**
This happened...
![image](https://user-images.githubusercontent.com/10938679/87045482-dc902480-c1ef-11ea-845a-96ca58eb432e.png)
![image](https://user-images.githubusercontent.com/10938679/87045525-e74ab980-c1ef-11ea-9c25-b80d935595ea.png)
Tried installing instead to a different logical drive...
![image](https://user-images.githubusercontent.com/10938679/87045621-ffbad400-c1ef-11ea-96fb-48bd281018ae.png)
SasView installed. Tried to run it, the 'splash screen' appeared...
![image](https://user-images.githubusercontent.com/10938679/87045714-18c38500-c1f0-11ea-9189-68052d8e8c7a.png)
But then the process died.

The Event Viewer implicates KernelBase.dll as described in [Report.wer.txt](https://github.com/SasView/sasview/files/4895912/Report.wer.txt)

Tried installing 5.0.3 RC1 on my office desktop instead.
Microsoft Windows 10 Enterprise Version 1903 Build 18362.836, KernelBase.dll: 23/06/2020 version 10.0.18362.815
UAC set to highest (upper) setting = least permissive

Same behaviour.

**Comment by smk78** [comment]
**Colleague 1**
Installed as Administrator _(Q: 'Run as Administrator or by logging in as?)_.
Work PC = Windows 10.0.18362, UAC in top-most setting
Home PC = Windows 10.0.19041, UAC in second setting from top.

Tried installing on both hard-drives but saw the same behaviour as @smk78.
Also notes that the Event Viewer reports a problem with KernelBase.dll.

**Colleague 2**
Windows 10.0.18362 Build 18362, KernelBase.dll: 15/05/2020
Tried to install with normal user account to default C:\Program Files\SasView, it didn't install.

Then tried installing with their admin account _(Q: 'Run as'?),_ it installed with no issues.
Program starts up but stops before opening the main UI, like in the picture below.
![image](https://user-images.githubusercontent.com/10938679/87047581-9d170780-c1f2-11ea-9b93-65adc01d8c92.png)

SasView 4.2 is still working normally, but 5.0.2 was overwritten buy 5.0.3 install.

**Colleague 3**
Private laptop
Win 10 build 18362, KernelBase.dll: 14/05/2020

Installed without problems as a normal user under C:\Program Files\SasView5p03. But crashes after showing the logo....
Also, existing installation of SasView 502 is showing the same behaviour. It was working nicely (on different install path).

Program log stops after:
```
'sasview.exe' (Win32): Loaded 'C:\Program Files\SasView5p03\mkl_vml_avx2.dll
The thread 0x5728 has exited with code 0 (0x0).
Unhandled exception at 0x00007FFEC018A799 (KernelBase.dll) in sasview.exe: 0xC06D007E: Module not found (parameters: 0x00000017F2188500).
```

**Colleague 4**
Windows 10.0.18362 Build 18362
UAC slider is at the top.

In normal user account,  SmartScreen complained, hit the “more info” and then “run anyway”, installed to c:/sasview503.
Program starts the splash screen but then “Sasview has stopped working”

5.0.2 release still runs (phew), which as usual I have not got in “Program Files”

Running the install as admin, still runs splash screen but then “Sasview has stopped working”, 5.0.2 still works.

**Colleague 5**
Windows 10.0.18362 Build 18362, KernelBase.dll: **06/12/2019** _(NB: the oldest yet)_
UAC slider is at the top.

Got the SmartScreen warning when trying to install from normal user account...
![IMG_0378](https://user-images.githubusercontent.com/10938679/87048948-47435f00-c1f4-11ea-9b2f-b7f90a3b8c36.JPG)
So installed with 'Run as Administrator' to C:\Program Files\SasView5
On running the program, sees the same behaviour...
![IMG_0379](https://user-images.githubusercontent.com/10938679/87048807-195e1a80-c1f4-11ea-9b00-12db0c099ad4.JPG)

**Comment by smk78** [comment]
Looking at the dates on the KernelBase.dll files that people have reported, 2 of them go back over a year. Sadly that would tend to suggest that a recent update of this file is not too blame. :-(

**Comment by rozyczko** [comment]
I looked at file version differences between 5.0.2 and 5.0.3rc1 installations.

There are several discrepancies, despite us trying to lock down on module versioning.
The most interesting is ` MKL`. 5.0.2 uses version 2020.0.0.1 while 5.0.3rc1 has 2020.0.1.1
Looks VERY benign but I've seen really weird incompatibilities with MKL libraries...

Another difference is `zmq` - ver. 19.0.1 vs. 19.0.0, `PIL` - ver. 7.2.0 vs. 7.1.1 and `jedi` - ver. 0.17.1 vs 0.17.0

I will try to force the build with the previous versions of the libraries. This might help.

BTW, Installed 5.0.3rc1 on my wife's laptop (Win10 home ed). Opens and runs well, but crashes on nontrivial fitting.
Finally I found a machine where SV crashes!
For Steve, the working ratio is 0/5, for me, 4/5...

**Comment by smk78** [comment]
@rmdalgliesh tried running a debugger. Unfortunately it didn't get far because we don't have the source for KernelBase.dll.

>Unhandled exception at 0x00007FF8A982A839 (KernelBase.dll) in sasview.exe: 0xC06D007E: Module not found (parameters: 
0x0000009691D88330).

**Comment by smk78** [comment]
@rmdalgliesh _also_ tried running 5.0.3 whilst logged in with his Admin account. SasView still fell over.

This suggests it is not a 'permissions problem', per se?

**Comment by rozyczko** [comment]
The debugger won't work since the compiled code has no debugging symbols included (release build, stripped).
I don't think this is a permission issue. I also think that the random crashes are closely related to this issue.
Both started occurring in 5.0.3 and multiple hints of `mkl` seem to point to it being (at least a part of) the culprit.

**Comment by gonzalezma** [comment]
Same problems for me. Could install but not launch 5.0.3 on Windows 8 (error message: SasView stopped working) and Window 10 (I see intro screen, but then nothing else and Event Viewer complains about KERNELBASE.dll)

**Comment by smk78** [comment]
We did have a corporate user (FridaL) back in Feb this year getting the 'failed to execute script sasview' error trying to use 5.0.1. on Microsoft Windows 10 Pro 64-bit - version 10.0.18363.

Her IT did get her going, but I don't know how (I did try asking!).

**Comment by smk78** [comment]
**Copied from the developers list 09/07/2020 16:32**
@gonzalezma notes:
> Same problems for me. Could install but not launch 5.0.3 on Windows 8 (error message: SasView stopped working) and Window 10 (I see intro screen, but then nothing else and Event Viewer complains about KERNELBASE.dll)

**Comment by rozyczko** [comment]
Can someone please check the new build in https://jenkins.esss.dk/sasview-beta/job/SasView-Windows10-ghprb/ 
**build 45**
This seems to work (installation and fitting) on the only machine I have on which 5.0.3 rc1 was failing before.

The difference is, as mentioned, the MKL library version.

**Comment by smk78** [comment]
Yey!

From my normal user account, I first tried installing to the default folder (in C:\Program Files) but permission was denied. I did not try with 'Run as Administrator'.

But I then tried installing to my D: drive. It installed fine and... it runs!
![image](https://user-images.githubusercontent.com/10938679/87093981-ffddc280-c235-11ea-9d87-965d0323c106.png)

Nice one, @rozyczko !

**Comment by m2cci-NMZ** [comment]
Installed on Windows 8, everything was working fine, fixed the crash I mentioned in #1623 :smiley:

**Comment by butlerpd** [comment]
Sorry -- with startup am mostly on radio silence (but am connected to slack) had tested on two windows machines
Desktop Windows 10 Enterprise Version 1099 installed on 6/12/2020.
* Would see splash screen then it dies. Log showed a KernelBase.dll error.
* This PR runs fine including a fit of sphere to drop contrast data fitting 3 parameters, then adding polydispersity as another fit parameter and fitting again.

Cloud Windows machine - Windows server 2016 Datacenter version 1607
* ran OK but fitting of sphere to drop contrast data worked as long as only 1 parameter is fit at a time. Crashed immediately with 2 or more fit parameters as described in #1623 
* This PR runs fine using exact test as on other machine above

So both issues seem fixed - though y machines are 2 for 2 failing @rozyczko . Can we have clones of your magic machines that never fail? 😃

**Comment by butlerpd** [comment]
PS:  I think we all owe you a beer @rozyczko - the big ones like they served in OakRidge at the mexican place 😃

**Comment by rozyczko** [comment]
@butlerpd each rc1 installation I've done was tested with `sphere/sphere` fitting several parameters on `latex_smeared.xml` and `cylinder/cylinder` fitting `scale/background` in `cyl_400_40.txt`.
I used
1. SasView testing VM (at DMSC)
2. Scip++ testing VM (at DMSC)
3. My dev laptop on two accounts, admin and non-admin
4. My workstation on two accounts, admin and non-admin
5. My wife's laptop on admin account.

On all but 5. the rc1 installation ran fine. It seems there's a strong developer bias and machines 1.-4. were just afraid of me, while 5. couldn't care less.

**Comment by smk78** [comment]
As of about 07:00 CET @wpotrzebowski uploaded a signed version of the 'special build' that @rozyczko created and I tested last night to GitHub. I have just downloaded this signed version from https://github.com/SasView/sasview/releases/tag/v5.0.3rc1 and tried installing it on both my W10 laptp and my W10 office desktop.

From a normal user account, the program installs, starts, and runs _so long_ as I do not try installing within C:\Program Files. Installing to a root folder on C:, for example, C:\SasView, worked fine, as did installing to a folder on a different disk/logical drive. The normal user account did not have permission to write to C:\Program Files.

I tried installing to the default path, that is, C:\Program Files\SasView, running the installer 'as Administrator'. It installed, but when I then tried to run SasView without Administrator privileges I got the 'failed to execute script sasview' error.

**Comment by smk78** [comment]
Is it time we abandoned C:\Program Files\SasView as the default installation path? Why not change it to C:\SasView?

**Comment by rozyczko** [comment]
The standard solution is to ask about installing for all users (admin rights, goes to `c:\Program Files`) or for the current user (no admin rights, goes to `c:\Users\<current user>\`
We never did that but maybe it's time to allow users to install/use SV without having to have admin rights on the machine.

**Comment by smk78** [comment]
**Update at 10/07/2020 17:00**
Three of my colleagues who could not get the initial offering of 5.0.3 RC1 for Windows to get beyond the splash screen are reporting that this new installer is allowing them to start and run SasView _so long_ as they do not install to C:\Program Files.

**Comment by butlerpd** [comment]
I have to admit I have never encountered the problem on any of my machines, but then I suspect I probably have admin rights on all my computers (I tend to get cranky if I cannot install what I need 😃 

I think it is clear that for a larger and growing fraction (perhaps the majority of enven?) of our users this may not be the case so a way to resolve would be helpful.  @rozyczko suggestion would be Anna's as well I note but may take more effort to implement than @smk78 suggestion?

**Comment by rozyczko** [comment]
PR #1626 fixes the installer. Users can choose between user mode and admin mode and the default target location is c:\SasView-5.0.3

**Comment by butlerpd** [comment]
it seems like this ticket should also be closed now?
