### ISSUE TITLE
5.0.3 RC1 crashing during fitting

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1623]
**_Some Windows machines are finding that 5.0.3 RC1 crashes without warning whilst doing what would be considered normal operations for model-fitting._**

**_A separate ticket https://github.com/SasView/sasview/issues/1622 concerns problems with installing/starting 5.0.3 RC1 on Windows._**_**

**Copied from developers list 08/07/2020 16:32**
@RichardHeenan notes:
> on my home, personal pc, without any corporate protections …  
> 
> At the 2nd or 3rd press of  “fit” with a few sensible parameters to a test data set with say sphere or cylinder, 5.0.3rc1  very abruptly shuts down, no messages in log
>
> Win 10 Home Version    10.0.18362 Build 18362
>
> I have installed to G:\sasview503cand    (as my C:  is a small solid state device)
>
> V4.2 is working fine.

**Comment by smk78** [comment]
**Copied from developers list 08/07/2020 17:08**
@murphyryanp notes:
> This may be a problem that was present in 5.0.2. I've had a similar problem of abrupt shut down (no log messages) with 5.0.2 after prolonged data fitting. I did not experience this abrupt crash in 4.2.
>
>I just recreated the abrupt shut down when playing around in the downloaded version of 5.0.2. It maybe doesn't crash the first time you try fitting, and seems to abrupt shut down after 3-4 attempts of fine tuning paramters and then trying to fit. 
>
> I've observed that it appears to happen in particular when using structure factors and form factors.
>
>Here's what I did:
>
> 1. Load Ludox 1D data
> 2. Send data to a fit (P*S) of polysdisperse sphere * hayter_MSA
> 3. Adjust parameters manually first to reasonable values, fix PD parameters
> 4. Click fit on radius and scale
> 5. Maybe it fits (maybe it crashes first time, maybe not)
> 6. Keep adjusting parameters and clicking fit on 1 or 2 parameters
> 7. After several iterations, Sasview abrupty closes when fit is clicked
> Windows 10 (Home) with generic install of 5.0.2.
>
> Not sure if this helps, but I thought I would report my observations.

**Comment by smk78** [comment]
**Copied from developers list 08/07/2020 17:36**
@RichardHeenan notes:
> Have just installed 5.0.2 on home pc, have not managed to crash it yet with core_shell_sphere times hard_sphere, with polydipserisy,  task manager shows I’m using 5 of total  8 Gb Memory,.
>
> Ran 5.0.3rc again, loaded same microemulsion shell data set, with just core_shell_sphere model selected scale, bkg, radius, core_sld to fit,  immediate crash on hitting fit !
>
> Ran 5.0.3rc yet again, loaded same microemulsion shell data set, selected scale only, fit works, then selected  bkg, radius, core_sld  to fit,  immediate crash on hitting fit !
>
> So in my case looks like 5.0.3rc is behaving differently ?
>
> Others please test ….

**Comment by smk78** [comment]
**Copied from developers list 08/07/2020 17:39**
@murphyryanp notes:
> After playing around more to see if I could recreate it again under different scenarios. 
I think it may be related to when models are loaded in kernel with OpenCl options. 
>
>Here's what I did:
>1. I tried the above sequence in my previous email WITHOUT OpenCl. It did not abruptly crash after fiddling with the parameters and fitting. I did this for maybe 10 minutes without a crash.
>2. I closed and then reopened 5.0.2 with OpenCl activated, reloaded the same model of polydisperse sphere * hayter_msa, same data loaded. After 3-5 fit iterations, it abruptly crashed upon hitting fit.
>
> Not sure if I'm missing something, but it seems the only difference is activating the OpenCl option that causes the issue. FYI, the GPU passed all tests when I run the "Test" in OpenCl options. 
>
>If it is somehow dependent on the GPU that is being used, that might explain why some people have the issue and others do not?
>
> @RichardHeenan, are you running with OpenCl options activated in 5.0.3?

**Comment by smk78** [comment]
**Copied from developers list 08/07/2020 18:13**
@RichardHeenan notes:
>my current local build of ESS_GUI and Master of sasmodels works fine on my office Win 10 pc.
>
>On my  Win 10 Home, 5.0.3rc,  I was not using OpenCL, typical compiler log is 
>
```
G:\SasView503cand\tinycc-data\tcc.exe -shared -rdynamic -Wall 
C:\Users\DanHome\AppData\Local\Temp\sas64_core_shell_sphere_97DD786B_2ikyytcj.c -o 
C:\Users\DanHome\.sasview\compiled_models\sas64_core_shell_sphere_97DD786B.so
```
> Though I do note that I have “two” gpu’s which is something that has given weird issues on my office pc, so there are 3 buttons, see jpg attached. 
![win10_home_pc](https://user-images.githubusercontent.com/10938679/87042855-21b25780-c1ec-11ea-9e32-b4d758100fcf.jpg)
>
> Trying the 2nd gpu, passed the tests, typical compile :
```
2020-07-08 17:58:50,818 : INFO : root (kerneldll.py:194) :: G:\SasView503cand\tinycc-data\tcc.exe -shared -rdynamic -Wall 
C:\Users\DanHome\AppData\Local\Temp\sas64_vesicle_47464C4C_hypq_a4x.c -o 
C:\Users\DanHome\.sasview\compiled_models\sas64_vesicle_47464C4C.so
```
> But then core_shell_sphere compiled as 
```
2020-07-08 18:01:40,249 : INFO : root (kernelcl.py:309) :: building core_shell_sphere-float32-97DD786B for OpenCL Juniper
2020-07-08 18:01:40,820 : INFO : pyopencl (__init__.py:383) :: build program: kernel 'core_shell_sphere_Iq' was part of a lengthy source build resulting from a binary cache miss (0.53 s)
2020-07-08 18:01:40,828 : INFO : pyopencl (__init__.py:383) :: build program: kernel 'core_shell_sphere_Iqxy' was part of a lengthy source build resulting from a binary cache miss (0.53 s)
2020-07-08 18:01:40,837 : INFO : pyopencl (__init__.py:383) :: build program: kernel 'core_shell_sphere_Imagnetic' was part of a lengthy source build resulting from a binary cache miss (0.53 s)
```
> As before a fit with just “scale” worked, turning 3 more sensible params on ( bkg,  radius, sld_core), hit fit gives immediate crash, the only new thing in log was …
```
2020-07-08 18:03:00,221 : INFO : root (ConsoleUpdate.py:153) :: 2020-07-08 18:03:00
```
> Selecting the first OpenCL option, likewise crashes fit in same way. (Restarted and ran OpenCl tests on first gpu option, whizzed through all compile tests very fast, so as I suspected the two options do the same thing).

**Comment by smk78** [comment]
**Copied from** https://github.com/SasView/sasview/issues/1622
@m2cci-NMZ notes:
> Tried on Windows 8, SV started, but crashed **specifically** when fitting if I selected more than one parameter for fitting. Enabling/disabling OpenCL had no effect.
> I inspected the dump file created by Windows with WinDbg, and it seems that the error is coming from `mkl_intel_thread.dll`
> I've attached the dump analysis, unfortunately, my knowledge of Windows is poor so I can't get anything usefull out of it :-(
> Hope this helps!
> [SV_crash_dump.txt](https://github.com/SasView/sasview/files/4896753/SV_crash_dump.txt)

**Comment by RichardHeenan** [comment]
Working OK now on my WIn10 Home using new installer for https://github.com/SasView/sasview/pull/1627

**Comment by butlerpd** [comment]
can this be closed now?

**Comment by murphyryanp** [comment]
The crashing issue I mentioned above has not occurred when using the latest 5.0.3 build.
