### ISSUE TITLE
Documentation: Links to .py source code from the 5.x model docs are not resolving

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1631]
Discovered by @sylvainprevost, [assumed] using 5.0.2 release:
> In the documentation, the link to "polymer_micelle.py" (bottom of the page) does not work (online or on the PC where sasview is installed). Links to polymer_micelle.c and lib/sas_3j1x_x.c do work. 

On investigation:
- In the case of the polymer_micelle model, the situation is as described by @sylvainprevost in both 5.0.1 and 5.0.2.
- Chrome returns:
  Your file was not found
  It may have been moved or deleted.
  ERR_FILE_NOT_FOUND
- In 5.0.3RC1 even the link to polymer_micelle.py is missing, however the RC tested was a 'special build' to test the new installer

The links are redirecting to:
(Installed 5.0.1)
file:///C:/Program%20Files/SasView-v501/doc/_downloads/9cc5553709b945632498ac949d2d3b65/polymer_micelle.py
file:///C:/Program%20Files/SasView-v501/doc/_downloads/ce199720cac56867e477f787270c0ef4/polymer_micelle.c
file:///C:/Program%20Files/SasView-v501/doc/_downloads/9ce500589cbb2611bcbc70d4dcd67444/sas_3j1x_x.c

(Installed 5.0.2)
file:///C:/Program%20Files/SasView-v502/doc/_downloads/9cc5553709b945632498ac949d2d3b65/polymer_micelle.py
file:///C:/Program%20Files/SasView-v502/doc/_downloads/ce199720cac56867e477f787270c0ef4/polymer_micelle.c
file:///C:/Program%20Files/SasView-v502/doc/_downloads/9ce500589cbb2611bcbc70d4dcd67444/sas_3j1x_x.c

(Online 5.0.2)
http://www.sasview.org/docs/_downloads/9cc5553709b945632498ac949d2d3b65/polymer_micelle.py
http://www.sasview.org/docs/_downloads/ce199720cac56867e477f787270c0ef4/polymer_micelle.c
http://www.sasview.org/docs/_downloads/9ce500589cbb2611bcbc70d4dcd67444/sas_3j1x_x.c

- It seems only to be the .py model source code that is affected. The .c source code appears.

NB: Versions 4.x are unaffected because we never included source code links in those docs. This is a 5.x issue.

**Comment by smk78** [comment]
Checking again after the release of 5.0.3 I find the problem still persists, both in the shipped docs and the online docs.

Somewhat weirdly:

- If the model only has a .py source module, then the link to the model.py file _does_ appear in the docs, but the link fails;

- If the model has .py and .c source modules, then the link to model.py _does not_ appear, though the link(s) to model.c, etc do appear and do work.

**Comment by butlerpd** [comment]
@smk78 and @wpotrzebowski, can this be closed then as having been superceeded by the merged PR https://github.com/SasView/sasmodels/pull/421 and the new issue #1664?

**Comment by smk78** [comment]
The original comment noted that in 5.0.3RC1 the link top the .py files was missing. Just trying this out with the latest (5.0.4) docs I find that the link is now present but:

Clicking the link from the online docs, Chrome attempts to download https://www.sasview.org/docs/_downloads/8f54abf177807180df000df5008ecccf/polymer_micelle.py but says 'Failed - No file'.

Firing up 5.0.4 release, Help > Documentation > User Documentation > Model Documentation > Sphere Functions > Polymer Micelle and clicking the link attempts to download from file:///C:/SasView-v504/doc/_downloads/9cc5553709b945632498ac949d2d3b65/polymer_micelle.py but results in
```
Your file couldn’t be accessed
It may have been moved, edited or deleted.
ERR_FILE_NOT_FOUND
```
So we still have a problem. :-(

**Comment by butlerpd** [comment]
yes but is that not what #1664 is about? I thought the point of #1664 was to take what was left of this ticket and create a new one so we could close this.  Is this problem different from what #1664 is about?

**Comment by smk78** [comment]
Oh I see. Yes, that is what #1664 is about. With the caveat that it doesn't look as if https://github.com/SasView/sasmodels/pull/421 actually did the job...

**Comment by butlerpd** [comment]
I'm assuming that SasView/sasmodels#421 does what it says since I don't think we can test it from the any build version until #1664 also gets fixed.  Is that your understanding @rozyczko. If so let's close this ticket.

**Comment by butlerpd** [comment]
I am going to close this and assume that future conversations on this topic will continue under #1664.
