### ISSUE TITLE
4.x/5.x: Annulus slicer tool phi plot could do with better resolution

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1646]
Affects 4.x and 5.x.

User DiegoAV working on magnetic systems notes that the annulus slicer tool on 2D plots always generates an intensity vs phi plot with 36 points (ie, presumably because it is integrating every 10 degrees) irrespective of the number of Qx/Qy points in the image and the radius of the annulus. This is a little coarse for his requirements.

Maybe we should reduce the interval to every 5, or even 3, degrees? Better still, allow the user to input the interval.

**Comment by krzywon** [comment]
This parameter and the one mentioned in #1647 can be changed by right clicking on chart and selecting "Edit Slicer Parameters." That said, finding this tool isn't 100% obvious. Maybe we could have the slicer parameter window open whenever a slicer is generated?

**Comment by smk78** [comment]
Thank you, @krzywon !

Yes, this is crazy. Who is going to figure that having right-clicked on a 2D plot to initiate the slicer you then have to do the same again to get the slicer parameters. That is just bonkers. Especially since the slicer parameters _also_ lets you hop from slice to slice. It might as well always be in the context menu for a 2D plot!

I will close this issue, and https://github.com/SasView/sasview/issues/1647, and create a new one for this change.

**Comment by smk78** [comment]
Closing this in favour of https://github.com/SasView/sasview/issues/1649
