### ISSUE TITLE
4.x/5.x: Slicer Parameters control only appears in context menu once you have sliced

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1649]
This ticket replaces https://github.com/SasView/sasview/issues/1646 and https://github.com/SasView/sasview/issues/1647.

Affects 4.x and 5.x.

Users have complained that the number of points in the Intensity vs Phi or Intensity vs Q plots returned by the Slicer options were too coarse to be very useful (eg, every 10 degrees for the annulus slicer, or just 15 points for a Sector slice).

It transpires that there is in fact a Edit Slicer Parameters option in the context menu, but it only appears in the menu once a slice has been created, meaning finding it is quite non-intuitive.

![image](https://user-images.githubusercontent.com/10938679/89189624-29b9a900-d598-11ea-828b-261dbc395725.png)

![image](https://user-images.githubusercontent.com/10938679/89189709-4ce45880-d598-11ea-970b-58d61b812906.png)

Since Edit Slicer Parameters _also_ allows toggling between slices, there is no reason for it not to be available on the first context menu or, alternatively, to be opened as a popup window when any slice is created.

![image](https://user-images.githubusercontent.com/10938679/89189953-a77db480-d598-11ea-825f-6f519d5fe6bc.png)

**Comment by rozyczko** [comment]
I would advise against automatic opening of additional windows - this tends to clutter the canvas. 
We may add Slicer Parameters (and Batch Slicing) to the default set of menu items, without necessarily having to have a slicer defined. The widget would come up without any slicer type (`None`) and users could choose a slicer from here.

Going further - do we then need to explicitly list slicers in the context menu at all? We could rename the widget to `Slicers/Batch Slicers` and simplify the context menu.

**Comment by smk78** [comment]
I'd be happy with that.

**Comment by rozyczko** [comment]
I am currently working on adding Batch Slicer to the widget so will modify it accordingly
