### ISSUE TITLE
Add exception content to exception messages

### ISSUE THREAD

**Issue by rozyczko** [SasView/sasview#1668]
Go through the Sasview source and attempt to add exception content to all the important exception messages.
Will be very useful for cases where sasview fails and we need to know why.

**Comment by toqduj** [comment]
I will try to do this, but I'm kinda poking around in the dark here. I'll search for try/except statements, and will add logging warnings when appropriate. I might also add some assert statements. @wpotrzebowski is this approximately the right approach?

**Comment by toqduj** [comment]
logging not available in run.py..

**Comment by toqduj** [comment]
This is an enormous task, suitable for its own code camp.. putting this on hold.

**Comment by rozyczko** [comment]
I think my idea was to just address those exceptions without ANY message attached, which by quickly looking at the grep results aren't that many.

**Comment by toqduj** [comment]
if I search for "except:" in the sasview directory, I get 178 results in 94 files, many don't have any messages to these exceptions but appear to be largely implemented for duck typing. I find it hard to figure out at a glance which ones are for duck typing and which ones genuinely need extra messages. 
(a search for "except Exception" raises another 304 results over 103 files...)

**Comment by rozyczko** [comment]
Yes, many of those are used for flow control, which in Python, as opposed to say, C++, is not frowned upon.
I was thinking about the most obvious cases but this isn't anything pressing. More of a "I've no idea about SasView, let me do something very easy" kind of intro task.

**Comment by lucas-wilkins** [comment]
I have fixed this in a couple of places already (can't remember the PR), probably the most important ones.

**Comment by lucas-wilkins** [comment]
Closing as about as complete as its going to be - @rozyczko feel free to reopen if you disagree.
