### ISSUE TITLE
Checkbox of highlighted row is checked also when clicking another checkbox

### ISSUE THREAD

**Issue by toqduj** [SasView/sasview#1676]
I noticed this when fitting on a Mac: When you have a list of parameters with one (random) row highlighted, and you click on another checkbox, the checkbox of the highlighted row is toggled as well. 

![Screen Shot 2020-09-25 at 10 12 52](https://user-images.githubusercontent.com/5449929/94252506-4e8d2580-ff24-11ea-836f-f8440dd60e2b.png)

**Comment by RichardHeenan** [comment]
It is the same on Windows, have had some discussion about it with Piotr, but seems it is a "feature" that will be hard to get rid of ????

**Comment by rozyczko** [comment]
Yes, this has been implemented as a "feature" - select several rows and click any of the selected checkboxes. This sets the state on all selected.
The problem appears when you don't `select` the row but click on the checkbox only. This action will be understood as 'change the selection status of the clicked checkbox and all the other selected rows', which in this case is clearly incorrect.

I think there was an existing GH issue for this, but can't find it now?

**Comment by toqduj** [comment]
Hm, I don't think this works as a feature, it's very confusing when the highlighted row is no longer visible and you're clicking a checkbox somewhere else. I'm not sure if there's much of a use case selecting many checkboxes.. 
Maybe if the selection is larger than 1 row, it would make more sense?
