### ISSUE TITLE
Need to enable resolution smearing for theory curves

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#1686]
5.0.3 release does not seem to allow for choosing a resolution when using a fitpage with no data attached to it.  I'm pretty sure it used to be possible so not sure when that might have gone south but it needs to be turned.... or implemented if my memory is not serving me correctly

**Comment by rozyczko** [comment]
In order for resolution to work, one needs to calculate the data first. I.e. after you choose a model, click Calculate. Then, the instrumental smearing combobox allows you to modify pinhole or slit parameters.

**Comment by RichardHeenan** [comment]
The whole FitPage with no data is bit weird in that you can only (I think) do it first thing in a fresh sasview session.

In 5.0.3 release on Windows, I set up no data, sphere, smeared 15%, then tried save project, closed sasview, started again, load project comes up with an completely blank FitPage. needs investigation!

**Comment by rozyczko** [comment]
> The whole FitPage with no data is bit weird in that you can only (I think) do it first thing in a fresh sasview session.
> 
> In 5.0.3 release on Windows, I set up no data, sphere, smeared 15%, then tried save project, closed sasview, started again, load project comes up with an completely blank FitPage. needs investigation!

Now THAT's a good find. Probably a side effect of the recent work on perspectives lifetime. This needs a separate ticket.

**Comment by rozyczko** [comment]
Can this then be closed, considering Richard's issue has a separate ticket?
Are you satisfied with the current functionality as described in the above comment @butlerpd ?

**Comment by butlerpd** [comment]
Thanks @rozyczko.  I will try to test this in the next couple of days.

**Comment by butlerpd** [comment]
ah never mind @rozyczko.  The need to hit calculate before adding the resolution is counterintuitive to me but then so is the fact that no data shows when I send data to fitting. I believe the difference with 4.x was that the calculation takes place with default parameters immediately after the selecting a model.  That said, you should be able to select the resolution without having data. The data comes when the calculation is made surely?

So maybe the issue should be changed or maybe closed and a different one opened.  Need to think a bit on that. In the meantime clearly it should be a critical issue so will lower that.  Until we figure out the right answer we should not worry more about this issue I guess?

**Comment by butlerpd** [comment]
This is really a discussion topic at the moment so moving it to the "Discussion Topics" Milestone

**Comment by butlerpd** [comment]
After some thought, I am closing this in favor of the new ticket #2095 submitted during the training workshop in Lund.
