### ISSUE TITLE
Umbrella ticket for SESANS fitting issues

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1697]
This is an umbrella ticket for some issues with the fitting of SESANS data that have been identified in 5.0.3.

1. When you fit conventional SANS data, changing a parameter value followed by {return} causes the calculated model on the data-model plot to update dynamically. This is _not_ happening when the data is .ses data. The model does update if you click Fit. **This needs investigation and fixing**

2. When you introduce an S(Q) into into the model you introduce an effective radius parameter, _radius_effective_ for the S(Q) in addition to the radius from the P(Q). The default behaviour of the model is that these are tied together so that as the radius optimises _radius_effective_ should also change. This happens if you are fitting conventional SANS data but _not_ when the data is .ses data. **This needs investigation and fixing**
   - For the time being, the only workaround is to set _radius_effective_mode_ = _unconstrained_ and update _radius_effective_ manually as fitting proceeds.
   - Also see https://github.com/SasView/sasview/issues/1648

3. Because SESANS fitting is fitting the experimental SESANS data to the Hankel transform of the P(Q)(*S(Q)) function, any model that is selected inherits a set of default parameters whose values may be meaningless, or way off sensible, for SESANS. In particular:
   - the _background_ parameter: this is added to all SasView models and is ascribed a default value of 0.001. However, it actually has no meaning for SESANS (because all instrumental effects are corrected for in the data reduction). Worse, _background_ is added after the transform. The result is that even a value of 0.001 is enough to completely skew a fit. **At the very least, we should set _background_ = 0.000 when the data is .ses data.**
   - size parameters (eg, _radius_): in many instances the defaults for these are just far too small (typically by factors of x100-x1000!) to provide a realistic starting place for any of the optimisers (see the discussion in https://github.com/SasView/sasview/issues/1601). **Could we implement a different set of default model parameters for .ses data?**

**Comment by butlerpd** [comment]
Regarding the second point of 3, that is not unique to SESANS data but to USAS data as well (which covers essentially the same size range).  Unfortunately, we do not have an easy way of distinguishing such data (well we could perhaps by using NXcanSAS data?). Moreover it is also true in a number of other cases so I think we should be careful of putting a bunch of kruft into models to deal specifically with SESANS when it is a more general problem. Something along the lines of what @murphyryanp suggested would seem the more appropriate approach to solve the generic problem?

**Comment by pkienzle** [comment]
Re: Q range, you can set the length scale of the model by the Q range in the data, or for SESANS, the Q range needed to compute the SESANS transform.

Given q_min, use scale factor r = q_min/1e-3 to set all parameters with units of Å to r*value. Round the scale to r = (1, 2 or 5) x 10^k so that the defaults are nicer numbers. If you find there are cases where this does not work, create an optional rescale function in the model that scales the defaults according to the given q_min.

**Comment by butlerpd** [comment]
As an umbrella ticket this probably should not be tied to a release milestone. Moving it instead to the "admin" milestone.  Tickets generated off off of this to be fixed would be more appropriate to be against release level milestones.

**Comment by smk78** [comment]
Would you prefer I just turned this into 3 separate issues?

**Comment by butlerpd** [comment]
Yes - each should have its own ticket so they can get worked on I think. As we know it is highly unusual that somebody can just sit on an umbrella and fix it all. in one go.  Umbrellas are quite useful IMO for helping track multiple related issues, but biven that we are not using any workflow enhancers that can link issue dependencies such as zenhub (that would be exactly what an epic would do for us) the only useful way to use umbrella's that I can think of at the moment is to use the checkbox feature in writing the umbrella and manually checking each item as it is done.  @krzywon has a few like that (see #1728 for example).

**Comment by smk78** [comment]
OK, will do. Just not right now! I'll close this issue when done.

**Comment by smk78** [comment]
This issue is now superseded by:
#1836 
#1837 
#1838
