### ISSUE TITLE
Provide P(Q) separately when fitting

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1698]
Request from a User.

When you fit an I(Q)=P(Q)*S(Q) model the individual contributions of P(Q) and S(Q) are available in the Data Explorer if you expand the + for the dataset.

But when you just fit a I(Q)=P(Q) model we do not provide P(Q).

Could we?

**Comment by RichardHeenan** [comment]
I think that the only difference should be the flat background? Which we might assume that users could work out how to remove if required? Unless they want to remove "scale" so that P(Q=0) = 1.0 ? Suspect this would cause as much confusion as help?

**Comment by smk78** [comment]
So when you do a P(Q)*S(Q) model, what is SasView showing as 'P(Q)'?

**Comment by RichardHeenan** [comment]
Good point, looking at it now I don't understand (again), certainly not what I was expecting!
I though it might be doing I(Q) = scale*volfraction*P(Q)*S(Q) + bkg  but P(Q) is very large, need to compare v4
but that does not currently make sense in v5.
(Sorry I need to go now, perhaps others can dig some more.)

**Comment by krzywon** [comment]
Documentation on how structure factors are applied: https://www.sasview.org/docs/user/qtgui/Perspectives/Fitting/fitting_sq.html

**Comment by smk78** [comment]
Hmm...

Just computing sphere*hardsphere with the default parameters in 4.2.2 (left) and 5.0.3 (right) you get this...
![image](https://user-images.githubusercontent.com/10938679/97574218-cc8c9280-19e2-11eb-9b43-7f9cb9c04cc3.png)
...which I think we can all agree are the same.

**But** when you then plot just the P(Q) contribution for each version you get this...
![image](https://user-images.githubusercontent.com/10938679/97574964-e8446880-19e3-11eb-959a-3cfc6d214ff5.png)
**Note the y-scales!!!** I think this is what @RichardHeenan refers to above. **What is 5.0.3 doing???**

The S(Q) contributions are the same...
![image](https://user-images.githubusercontent.com/10938679/97575377-8801f680-19e4-11eb-8079-52f0791e2443.png)

**Comment by smk78** [comment]
Just for completeness, here are the inputs:
![image](https://user-images.githubusercontent.com/10938679/97576110-a4526300-19e5-11eb-80b4-e8c68ddddde4.png)

**Comment by butlerpd** [comment]
Looks like one of them is including some of the prefactor terms (scale, del Rho^2, etc) while the other is not?  though a 10^6 diff seems odd for del Rho^2?

**Comment by RichardHeenan** [comment]
looking at values in the workspaces,
 v4 is doing      I(Q)= scale.P(Q).S(Q) + bkg

if the fit is good and the sld's correct, then of course scale=1, so P(Q) is what you might "expect". I think that somewhere volfraction from S(Q) is embedded in P(Q), need to check again.

v5 has multiplied P(Q), at least as stored in the data explorer etc,  by the particle volume in Ang^3, which is a bug, so it is doing effectively

                             I(Q) = scale.P(Q).S(Q)/vol

**Comment by pkienzle** [comment]
The difference is in the volume normalization. Changing [sasmodels/product.py](https://github.com/SasView/sasmodels/blob/a947505203cbeda27f18493a607b14e64e0fb1f1/sasmodels/product.py#L523) from
```python
combined_scale = scale*(volfrac if not self._volfrac_in_p else 1.0)
final_result = combined_scale/shell_volume*PS + background
```
to
```python
combined_scale = scale/shell_volume*(volfrac if not self._volfrac_in_p else 1.0)
final_result = combined_scale*PS + background
```
should make them consistent.

The background constant is applied after P*S, so I don't think you want it added to P alone.

**Comment by RichardHeenan** [comment]
I don't think that what Paul K suggested is what is needed to get v5 back to the same as v4. 

The fit in v5 is working as expected and is same as v4, only the saved "intermediate" of P(Q) is wrong, being too large by shell_volume.  Does p_intermediate become P(Q) saved in the data explorer window ? (see around line 295 of the code).

**Comment by pkienzle** [comment]
The correction moves `shell_volume` into `combined_scale`, instead of applying it directly to `final_result`, leaving `final_result` unchanged. This `combined_scale` is multiplied by `Fsq` to produce `P(Q)` as the `scale` parameter in the [`_intermediates`]( https://github.com/SasView/sasmodels/blob/a947505203cbeda27f18493a607b14e64e0fb1f1/sasmodels/product.py#L294) function, so the change will result in P(Q) being scaled by the volume. 

Note: `shell_volume` is the volume of material, which is the entire form volume when you have a solid shape, but only the shell when you have a hollow shape.

**Comment by RichardHeenan** [comment]
OK, sorry, I had not understood the parts["P(Q)"]  and parts["P(Q) parts"]  stuff around lines 294-296.
Someone needs to code this and test it please.

**Comment by pkienzle** [comment]
The "P(Q) parts" is for the case when P itself is composed of parts. For example, if you use `(A+B)@C`, the `A` and `B` parts can be returned separately. I haven't tested whether this works as expected. Whether this is meaningful is a separate question.

**Comment by RichardHeenan** [comment]
For info - copy of comment on the PR -  Have briefly tested the first windows build from this PR. The P(Q) saved in the data explorer is now correctly scaled and I am happy.  
BEWARE the scaling is NOT the same as in v4, as now "scale" is included inside the saved P(Q), this is good as appending the P(Q) to a plot gives what users might expect to see, a line that overlaps the fit when S(Q) goes to unity at higher Q (except without the flat background which is not included), regardless of the value of "scale".

**Comment by RichardHeenan** [comment]
Some appropriate docs changes will be needed!

**Comment by smk78** [comment]
Have just merged https://github.com/SasView/sasmodels/pull/431 and created a doc ticket. Can this be closed now?

**Comment by RichardHeenan** [comment]
Yes, then test to check its still OK.

**Comment by smk78** [comment]
Pulled and tested on W10/x64.

Yes. this is all good. Compare the left image below with https://user-images.githubusercontent.com/10938679/97574964-e8446880-19e3-11eb-959a-3cfc6d214ff5.png above.

![image](https://user-images.githubusercontent.com/10938679/100134262-d7bacd00-2e7f-11eb-978c-60ed62af04c5.png)

And the right-hand image looks sensible too.

Am closing this issue.
