### ISSUE TITLE
Allow check/uncheck of sub-selected data in Data Explorer

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1699]
In 4.x & 5.x, the Data Explorer currently allows one to select (check)/deselect (uncheck) ALL loaded data.

However, in 5.x, the GUI manager _also_ allows you to highlight a sub-selection according to normal OS rules (ie, by holding down the shift or ctrl keys whilst selecting) so that selections like the following are possible:
![image](https://user-images.githubusercontent.com/10938679/97692628-ecca5900-1a97-11eb-9103-72371ec8bf06.png)
But what you cannot then do is check/uncheck just the data in that sub-selection in one go.
Could we implement that?

**Comment by krzywon** [comment]
This was fixed when #1700 was merged.
