### ISSUE TITLE
Update help docs and next release notes to reflect the change in how shell_volume is applied in P scaling

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1708]
https://github.com/SasView/sasview/issues/1698 and https://github.com/SasView/sasmodels/pull/431 detail a change to the P scaling in P@S models in 5.x (where shell_volume is accounted for) which, whilst it means 5.x now gives the result that Users might expect to see, does mean that the scaling is no longer the same as in 4.x.

This change needs to be documented in both 5.x and 4.x, in the help docs and in the next release notes for both.

**Comment by RichardHeenan** [comment]
Need to double check what v4 and v5 have for the stored P(Q) for both normal and the few special "shell" models. (I think any new build of v4 is built against current sasmodels, so v4 will likely change also?)  
If the stored P(Q) plots straight on top of I(Q)=P(Q)S(Q) at high Q, bar the flat background, in all cases, that will be good!  (Make sure 'scale' is NOT 1.0 and background = 0.0 to check.)

**Comment by butlerpd** [comment]
Huummm... @smk78 - is it true that we failed to update the documentation in 5.0.4? I'm assuming yes so moving this to 5.0.5 and adding the critical label.

**Comment by smk78** [comment]
Correct. This didn't make it into 5.0.4.
I had been meaning to talk to @RichardHeenan about it, because it was he who flagged it up.

**Comment by smk78** [comment]
Now PRs above are merged am closing this issue.
