### ISSUE TITLE
sasview fails to open .h5 files using h5py 3.1

### ISSUE THREAD

**Issue by drew-parsons** [SasView/sasview#1710]
h5py v3.1 was recently released.  It's causing some regression in sasview, with test .h5 files no longer able to be opened.
No clear error or Exception is given.  `load_using_generic_loaders` from sascalc/dataloader/loader.py reports `NoKnownLoaderException: Generic readers failed to load`, meaning simply that `cansas_reader_HDF5.read(file)` returns an empty list.

It's not clear to me why cansas_reader_HDF5.read is returning an empty list. Running through each step in `read_children()` in the reader by hand, the .h5 files opens successfully and the elements get read successfully one by one.  I didn't check `add_intermediate()` explicitly.  At some point self.output must be getting blanked, or not assigned values.  The blank value of self.output (returned by `cansas_reader_HDF5.get_file_contents`) is the problem.

The error was reported for Debian at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=974181
Debian test logs using h5py 3.1 can be found at https://ci.debian.net/packages/s/sasview/unstable/amd64/
e.g. https://ci.debian.net/data/autopkgtest/unstable/amd64/s/sasview/8477673/log.gz

Intermediate errors are reported in the log:
```
WARNING  sas.sascalc.dataloader.file_reader_base_class:file_reader_base_class.py:160 SasView cannot load /tmp/autopkgtest-lxc.179sxrt1/downtmp/autopkgtest_tmp/test/sasdataloader/test/test_data/simpleexamplefile.h5.
                                                                                     Invalid XML syntax
WARNING  sas.sascalc.dataloader.file_reader_base_class:file_reader_base_class.py:160 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
```

The reference to XML and 'utf-8' codec sounds as if sasview is trying to handle the .h5 file as an xml file, which of course would be wrong.  I'm not sure this is the real problem though.  The error `Generic readers failed to load` makes sense, if cansas_reader_HDF5.read is returning an empty data list.  The question is why is it doing that?  Why does its `self.output` remain empty for a valid test file like simpleexamplefile.h5?

**Comment by smk78** [comment]
Could this be related to https://github.com/SasView/sasview/pull/1683 ? @krzywon

**Comment by drew-parsons** [comment]
I suspect it might be something else.  I tried with the #1683  patch, but still get the .h5 error. Perhaps there's another patch in master needed to make #1683 active. I applied it to v5.0.3 source.

**Comment by krzywon** [comment]
@smk78 This appears to be a separate issue. H5py overhauled how the package loads data around the end of October. Our build scripts and conda environment files specify v2.8 or v2.9, so any changes will need to push those forward as well.

@drew-parsons Is there a compelling reason the debian build is using the latest h5py release? Can we step it back for now?

**Comment by krzywon** [comment]
Never mind. I already have a fix. Try pointing to the ticket-1710 branch for the debian build to see if the issue persists.

**Comment by drew-parsons** [comment]
Thanks @krzywon, I'll try it.  h5py 3.1 is in Debian experimental not main release yet.

**Comment by drew-parsons** [comment]
PR #1712 passes fine, thanks @krzywon
