### ISSUE TITLE
Allow user to choose default for plot navigation tools

### ISSUE THREAD

**Issue by skrueger111** [SasView/sasview#1726]
The default for the navigation tools at the bottom of a plot was to be toggled "on" in earlier versions of SasView as shown in the plot below.  This is no longer the case.  Users should be allowed to choose the default value for the plot navigation tools if possible since some are used to having the tools there and it isn't immediately obvious how to get them back.
![Screen Shot 2021-01-11 at 2 57 01 PM](https://user-images.githubusercontent.com/20684076/104231989-b016c880-541d-11eb-8296-94257bb83755.png)

**Comment by butlerpd** [comment]
This speaks to adding a preferences menu item to the GUI which presumably would edit the custom_config file?  Should we create a separate ticket for that and make this dependent on that one?

**Comment by juliuskarliczek** [comment]
Close this issue in favor of #2849, users can select the standard option for new plots and the navigation toolbar in the preferences. Also, they can toggle a navigation toolbar for individual plots by the right clicking context menu.
