### ISSUE TITLE
Unit testing of qtgui

### ISSUE THREAD

**Issue by llimeht** [SasView/sasview#1732]
Python particularly rewards unit testing as there's only so much that static checkers such as pylint or mypy will pick up.

`src/sas/qtgui/GUITests.py` exists and has a number of tests that exercise parts of the `qtgui` tree, but those tests do not currently pass and so they are not enabled on PRs.

Some of the errors/failures appear to be errors in the tests, while some are errors in the code being tested.

A summary of the current situation is:

```
Running 56 test cases for calculatorsSuite
......F..F......F..........................FE...E......E

Running 56 test cases for mainSuite
..........................................F............F

Running 114 test cases for fittingSuite
..................................................................F...........E...................................

Running 85 test cases for plottingSuite
FF.EEEEE........Segmentation fault (core dumped)
```
(the segfault stopped the test prior to it getting to `utilitiesSuite` and `perspectivesSuite`)

A bit of work to do.

**Comment by rozyczko** [comment]
I'm working on the `plottingSuite` tests as part of #1721

**Comment by RichardHeenan** [comment]
Are any of these errors suitable for "scientists" (like myself) to investigate, or will they require a software guru?

**Comment by krzywon** [comment]
@RichardHeenan you can check which tests are failing by running `python GUItests.py` from within the `qtgui` directory (make sure you've run setup.py first). Exception tracebacks and failed tests will be listed.

You can run subsections of the tests by adding one of the following arguments:
-  `calculatorSuite` runs the gui tests for the calculator apps like the data operation panel, SLD calculator, etc.
- `mainSuite` runs the tests for the main window and data browser
- `fittingSuite` runs all fitting perspective gui-related tests
- `plottingSuite` test the plotting routines
- `utilitiesSuite` tests things like the python window, logger, results window, etc.
- `perspectivesSuite` tests the corfunc, invariant, and P(r) perspectives

**Comment by krzywon** [comment]
One note - PR #1715 separates the `perspectivesSuite` into `corfuncSuite`, `invariantSuite`, and `inversionSuite` and fixes all tests for the invariant perspective.

**Comment by rozyczko** [comment]
I think this is critical enough to warrant adding to the hackathon list.

**Comment by RichardHeenan** [comment]
I had a quick look at the errors list from GUITEst as was suggested,  a few of them may be due to test data issues, so I may be able to help there.

**Comment by RichardHeenan** [comment]
I have had a look at some of this, after todays big PR's to Main for the Invariant etc.

If I do 
python GUITests.py

I get more detailed and longer output than just choosing one perspective such as
python GUITests.py corfuncPerspectiveSuite

Adding the -v flag as suggested in the py script for verbose output does nothing!

Found one bug so far, file UnitTesting\ISIS_98929.TXT needs to be renamed to .txt to fix one of the corfun test errors.

I am attaching a partly annotated copy of my console output, so maybe someone more clever than myself can deduce further. 

e.g. SlitSizeCalculatorTest is failing to find 2 files, suggesting a path error, but I don't know how to fix that, likely needs a change in qtgui/path_prepare.py ?

[guitests_19Jan2021.txt](https://github.com/SasView/sasview/files/5837813/guitests_19Jan2021.txt)

**Comment by rozyczko** [comment]
I've fixed quite a few of those already (separate branch). Will have a look at Richard's file to see if there's anything I didn't catch on my system

**Comment by RichardHeenan** [comment]
Sorry didn't see you had a branch for this, though my exploration of the test data files did not impinge on the plotting tests.

In WelcomePanelTest and GuiManagerTest, are the version numbers and institutes lists going to fail every time those details are changed? Does/should the release system update the strings in the tests?

Where the tests deliberately load a file that will fail, can the tests hide the warning message, or put out a message to say that this is expected?
e.g. SlitSizeCalculatorTest loads Dec07031.ASC, but that is the wrong file type, so is supposed to fail!

**Comment by lucas-wilkins** [comment]
This blocks #2157

**Comment by llimeht** [comment]
I've started looking at the GUI tests and I've made some progress at morphing them into a more usable form.

Given that lots of these tests are already failing, I propose simply marking the failing tests as `xfail` (expected failure) at present, with the intention that we:

1. get the test suite modernised and runnable
2. get the test suite passing (with liberal use of xfails) so that CI can start gating on it to prevent further regression
3. revisit the xfails and either fix the code or fix the test so that they pass

Decoupling the steps of getting the tests to run and fixing the tests to pass makes the task much more tractable. That these tests have remained failing for several years now is reasonable indication that hoping someone will fix both the test suite and the individual tests is overly wishful thinking.

My approach has been to morph the tests into the standard `pytest` form (rather than relying on pytest's `unittest` compatibility layer) and use fixtures to more easily manage Qt . To get into the implementation details:
 * We're already using pytest, and there's a nice [pytest_qt](https://pytest-qt.readthedocs.io/en/latest/) plugin that helps deal with the Qt initialisation. It also has an automation framework (`qtbot`) that might be handy for future tests. Doing this incorrectly is most likely the source of the segfaults noted above.
 * To get the most out of pytest and, in particular, pytest_qt, we should use [pytest fixtures](https://docs.pytest.org/en/7.1.x/explanation/fixtures.html) to manage the test environment (e.g. [qtbot](https://pytest-qt.readthedocs.io/en/latest/reference.html#module-pytestqt.qtbot), [qapp](https://pytest-qt.readthedocs.io/en/latest/reference.html#module-pytestqt.plugin), [tmpdir](https://docs.pytest.org/en/7.1.x/how-to/tmp_path.html), etc); it's not easy to mix paradigms for managing the test harness, with pytest fixtures and unittest `setUp`/`tearDown` functions in classes being rather different and somewhat incompatible.
 * To better use pytest fixtures, we need to remove the use of classes of test functions and stop using `self.assert*` functions. We can use [unittest2pytest](https://github.com/pytest-dev/unittest2pytest/) to rewrite all the `self.assert*` calls; other uses of `self` need to be dealt with manually. Doing this makes the diffs enormous while actually changing very little.
 * With pytest, there's no need for a helper script like `GUITest.py` as we can just test pytest to find and select sets of tests on its own. It's easy to replace `cd src/sas/qtgui; python GUITest.py mainSuite` with `pytest src/sas/qtgui/MainWindow`.

As a test of the plan, I've worked through this process on two sets of tests so far:

- `src/sas/qtgui/MainWindow/UnitTesting/AboutBoxTest.py` was a simple conversion and all tests pass
- `src/sas/qtgui/MainWindow/UnitTesting/DataExplorerTest.py` was a simple conversion, but lots of tests currently fail. Most of these are the same issue (not finding the test data files. I suspect that a test data file helper to locate the test data will solve all these fairly easily

The changes associated with this work are at: https://github.com/llimeht/sasview/compare/1ac260e..tmp/guitests (Note that this branch is necessarily built on top of the changes in #2213, #2214, #2216). As mentioned above, converting the unittest classes to pytest functions and converting unittest `self.assert*` calls to simple `assert` calls generates large diffs that make this look more complex than it really is. The tests were run on CI so [the output can be seen too](https://github.com/llimeht/sasview/actions/runs/3120787774/jobs/5061637348#logs).

Before sinking additional time into this, I'd be grateful for some feedback on the approach. Comments? Suggestions?

I anticipate that there will be some collisions with other work around config objects, preferences windows etc and that care and coordination will be needed.

**Comment by pkienzle** [comment]
I've already gone from unittest to nose to pytest. Is pytest the current defacto standard?  Is there a new one on the horizon? A quick search shows [hypothesis](https://github.com/HypothesisWorks/hypothesis/tree/master/hypothesis-python) which is a fuzz tester. I don't know if it supersedes pytest.

Can you do the conversion in stages?

1. pytest seems to support unittest tests, so the first step is to use pytest as a driver.
2. You should be able to mark the failing tests in a small diff. Ideally this would use the pytest api to mark them so you don't need to later convert unittest skips to pytest skips.
3. You may be able to replace the asserts within unittest with normal asserts plus `pytest.raises` and `pytest.warns`. This will keep down the size of the diffs and make checking the PR easier.
4. The final step moving from classes and methods to fixtures and functions will still be a big diff.

**Comment by llimeht** [comment]
> I've already gone from unittest to nose to pytest. Is pytest the current defacto standard? Is there a new one on the horizon? A quick search shows [hypothesis](https://github.com/HypothesisWorks/hypothesis/tree/master/hypothesis-python) which is a fuzz tester. I don't know if it supersedes pytest.

pytest appears to be where everyone is congregating, yes. There's some 1600 packages in Debian using pytest for build-time testing and 132 using hypothesis. 

> Can you do the conversion in stages?

I tried to do more or less what you described to begin with, but as the test suite is currently causing the python interpreter to segfault on me, it's hard to make any progress down that path. From what I can see, the segfaults are due to the Qt application lifecycle not being done quite right and fixing that seems best to want using pytest fixtures to ensure correct creation and destruction of the PyQt resources. Switching to fixtures (such as `qapp` form pytest_qt), unfortunately means point 4 in that list has to come first :( 

I'll see if I can feasibly run the tests in a way that avoids the segfaults to make this possible. Making the big diff for step 4 approximately-whitespace-only is attractive; however, I'm not sure if it's attractive enough to justify the extra overhead in the process given.
