### ISSUE TITLE
Conflicting definition of displayData()

### ISSUE THREAD

**Issue by mdoucet** [SasView/sasview#1738]
There are two definitions of `displayData()` in the `DataExplorerWindow` class.

https://github.com/SasView/sasview/blob/304b40b238d60e1e2daf0df116927adefec8b207/src/sas/qtgui/MainWindow/DataExplorer.py#L998

https://github.com/SasView/sasview/blob/304b40b238d60e1e2daf0df116927adefec8b207/src/sas/qtgui/MainWindow/DataExplorer.py#L1033

I believe the first one is the intended one. Removing the second one breaks `GuiUtils.plotsFromDisplayName()`
because its first argument is expected to be a string but is now a list:

https://github.com/SasView/sasview/blob/304b40b238d60e1e2daf0df116927adefec8b207/src/sas/qtgui/Utilities/GuiUtils.py#L508

**Comment by krzywon** [comment]
This is fixed in PR #1709 that I'm about to merge into main.
