### ISSUE TITLE
nokogiri vulnerability in Gemfile.lock

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1740]
On pushing a commit to the website GitHub informed me of this:

https://github.com/SasView/sasview.github.io/security/dependabot/Gemfile.lock/nokogiri/open

As we seem to use gem for the website, can someone more knowledgeable than I evaluate its importance.

**Comment by wpotrzebowski** [comment]
I've upgraded package on sasview.github.io

**Comment by wpotrzebowski** [comment]
@smk78 can you take a look if the website works as expected? It is not obvious to me that we use nokogiri functionality at all (maybe for creating posts?). It may well be something somethin that comes with jekyll theme by defualt.

**Comment by smk78** [comment]
I'm not getting the vulnerability warning when I commit to the website repo anymore, @wpotrzebowski , and the website is still updating! Thanks!
