### ISSUE TITLE
Invariant not extrapolating over listed high-q

### ISSUE THREAD

**Issue by krzywon** [SasView/sasview#1749]
The invariant perspective does not extrapolate over the entire high-q range listed in the GUI (default 10 Angstrom<sup>-1</sup>). The total number of points in the extrapolated data is always 500. The low-q extrapolation goes to the expected low-q value, but often using fewer points.

Example: load test\1d_data\AOT_Microemulsion-Drop_Contrast.xml into the the invariant perspective, with the extrapolation limit at the default and the extrapolation ends at 0.843 Angstrom<sup>-1</sup> over 500 points.

This issue has been present since at least release v4.2.2.

More comments and examples can be found in PR #1718.

**Comment by butlerpd** [comment]
I think this was resolved in your last commits on the topic @krzywon?

**Comment by krzywon** [comment]
No, this is still outstanding, unfortunately.

**Comment by butlerpd** [comment]
Thanks ... moving from 5.0.4 to 5.0.5 for now then.

**Comment by krzywon** [comment]
Looking into this during the training course today, there is a display limit of `3 * max(Q) ` that is being applied, not only in v5.x, but also v4.x. The backend calculator is still extrapolating over the expected values, and this only affects what is plotted. Does anyone know a good reason why we would have added a display limit to this?

Pertinant line of code: https://github.com/SasView/sasview/blob/5c21a95c45e13add27be8dc078422ae6d5273768/src/sas/qtgui/Perspectives/Invariant/InvariantPerspective.py#L27

**Comment by butlerpd** [comment]
It seems to go back quite a ways.  I suspect it was initially thought to keep users from hurting themselves? and 3*qmax seemed reasonable? Maybe because if it is too big the amount of real estate for the actual data could get negligeable? But It just seems wrong to me that if the calculation is doing it to now show it?   I vote we eliminate that.
