### ISSUE TITLE
Graph range reset to default values when replot

### ISSUE THREAD

**Issue by Susyana** [SasView/sasview#1750]
I used 'Change Scale' to view the data as a Guinier plot. The plot automatically adjusts the scale, which looks as shown on the image for data with large error bars:
![image](https://user-images.githubusercontent.com/53537909/104824249-1afd4080-581e-11eb-8f72-5e5a4508a411.png)

I can re-adjust the scale, but I can only do that if I close the Linear Fit window, which forces me to start the fit again. When I restart the fit, the scale is again reset to inconvenient values. 
The Linear Fit would be much easier to use if the option to change the graph range (or use the zoom tool) remains active while the fit window is open.

**Comment by krzywon** [comment]
This appears to be more wide-spread than the original submission suggests.

Issue:
 1. Run any type of analysis on any 1D data set
 2. Change the graph range of the plot
 3. Rerun the same analysis
 4. The graph range is now back to the original values

Plot after a fit, followed by graph range change:
![plot_range_changed](https://user-images.githubusercontent.com/10947925/107280352-3f67c980-6a26-11eb-95de-ebb127422aa9.png)

Plot after 2nd fit:
![plot_range_after_refit](https://user-images.githubusercontent.com/10947925/107280350-3ecf3300-6a26-11eb-9d40-44db69aa7068.png)

Ideally, the graph range would be retained between replots, regardless of the type of analysis.

**Comment by butlerpd** [comment]
Note in image of initial submission, the Min value of `Fit range of x^2` is negative which causes the redraw.  Simply deleting the minus sign in the text box prior to pressing fit will prevent the initial problem. However, pressing Fit a second time will indeed still reset to the full range

**Comment by krzywon** [comment]
This should have been closed with the PR was merged
