### ISSUE TITLE
why does github assignees list stop at letter D

### ISSUE THREAD

**Issue by RichardHeenan** [SasView/sasview#1752]
Is this just my browser, but the "assignees" list stops at letter D in alphabet, so a lot of us are missing???

**Comment by smk78** [comment]
If you mean Chrome, yes, it does look that way. But if you type a letter in the assignee search box it will change the offering.

**Comment by smk78** [comment]
BTW. Checking this issue, I notice that GitHub no longer supports Microsoft Edge.

**Comment by rozyczko** [comment]
> BTW. Checking this issue, I notice that GitHub no longer supports Microsoft Edge.

I use Edge and have no problems with GH. The list stops at "D" as well with Edge, I guess there is a limit on how many entries are shown. As @smk78 says, starting to type the name helps.

**Comment by smk78** [comment]
See the yellow bar!
![image](https://user-images.githubusercontent.com/10938679/104928294-5fade680-599a-11eb-8a81-4cf519f9b5dc.png)

**Comment by rozyczko** [comment]
bizarre... I don't see the yellow message on my edge.
Also, https://docs.github.com/en/github/getting-started-with-github/supported-browsers shows they still support it...
Maybe you're spoofing your browser string for some reason?

**Comment by smk78** [comment]
I have Microsoft Edge 44.18362.449.0. But opening a new tab presented me with this nugget:
https://support.microsoft.com/en-us/microsoft-edge-legacy?ui=en-US&rs=en-US&ad=US

It would appear that the version of Edge I have, that came bundled with W10, will become a legacy app on Mar 9 this year!

**Comment by rozyczko** [comment]
so you do have an older version, not the "New" Edge. Mine's 87.0.664.75

**Comment by smk78** [comment]
Yeah. So I just took up the 'offer' to upgrade and now have Version 87.0.664.75 (Official build) (64-bit). I like the logo better too! And I confirm I no longer get the yellow bar visiting GitHub!

**Comment by RichardHeenan** [comment]
re my original "issue", maybe we now have too many members, so rather than seeing the whole list as previously we get just ourselves and 10 others, as has been said, typing in the box searches the rest ...

closing this as non-issue
