### ISSUE TITLE
Implement the Orientation Viewer in 5x

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1763]
https://github.com/SasView/sasview/issues/1271 noted that the Orientation Viewer present in 4x needed to be implemented in 5x. However, until now, that requirement does not appear to have been ticketed.

**Comment by rozyczko** [comment]
Hmm we had the Orientation Viewer implemented at some point...

**Comment by rozyczko** [comment]
ah.

     # orientation viewer set to invisible SASVIEW-1132
     self._workspace.actionOrientation_Viewer.setVisible(False)


this points to the bug report in JIRA
https://jira.esss.lu.se/browse/SASVIEW-1132

> On Mac, only the following error message is displayed in the Log explorer:
> "ERROR: Unknown property axisbg"

> matplotlib > 3.0 doesn't have axisbg property for Axes. it is now 'facecolor'. The orientation viewer runs from sasmodels.
> We will downgrade matplotlib on linux/mac until proper rewrite of sasmodels is done. mpl 3.0 is not yet available for windows on conda, so we didn't see the issue before.

So I think this means we need to check if sasmodels is now MPL 3 compliant and if so, just enable the viewer.

**Comment by rozyczko** [comment]
This needs some work now. When no plots are shown, the orientation viewer performs as expected. When a plot is shown, it gets replotted in a separate window, and the original plot canvas turns blank.

![jitter](https://user-images.githubusercontent.com/8266281/107615951-60f6ca00-6c4d-11eb-9b49-c8a0f19a273d.png)
