### ISSUE TITLE
P(r) does not respect setting of manual background

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#1765]
The P(r) defaults to automatically estimating the background subtraction needed. It is critical to have the background properly subtracted from the data in order for the inversion to work.  For many users and cases that subtraction is not done and thus the automatic estimation is appropriate.  But sometimes the estimate is wrong and one would like to set it manually.

Currently there is a radio button feature to choose either "automatic" or "manual" subtraction. However, if one chooses manual and inputs a number, that number is ignored and reset to the estimated value. Note that the radio button continues to indicate "manual"

**Comment by smk78** [comment]
Noted during testing of 5.0.4 RC1 (See #1772)
8. In the Inversion perspective, estimating the background doesn't seem to do anything, at least, the background level box never displays anything but 0.0, but when you click Calculate the radio button swaps to Manual Input.

In 5.0.4 RC2 a plausible estimated background is now displayed. But if you switch to Manual, enter a background value, and click Calculate, the background level reverts to the estimated value.

**Comment by smk78** [comment]
Curiously, using release 5.0.4 it doesn't seem that this fix got applied. You can have a manual background or 0. No estimated background is displayed or used.

However, trying 5.0.5a1 build 555, all is hunky-dory.
