### ISSUE TITLE
Issues noted during testing of 5.0.4 RC1 & RC2

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1772]
1. The Installer is still labelled as 5.0.3
![image](https://user-images.githubusercontent.com/10938679/105989900-a6d26080-6099-11eb-932c-5e4bbbef5504.png)

2. The installer is not offering a choice of installation path, but worse, instead of creating a sensible folder name with 5.0.4 in it, it is overwriting 5.0.3!

**Comment by smk78** [comment]
3. Documentation is still tagged as 5.0.3.
 Did the version number not get updated during the release process?

**Comment by rozyczko** [comment]
I guess we have not done that... 

https://github.com/SasView/sasview/pull/1773

**Comment by smk78** [comment]
4. Are we happy with the behaviour of Change Name in the Data Explorer? Data in plots is always being labelled with whatever SasView is storing internally as the 'Title', completely irrespective of what you ask Change Name to do. So you can have datasets in the Data Explorer called one thing, but if you plot the data it is called something else.

5. Also, if you load a dataset, then delete it. Then load it again, it gets labelled as [1], [2], etc,...

6. And when you delete a dataset this appears in the Log Explorer:
```
  File "site-packages\sasview-5.0.4-py3.6.egg\sas\qtgui\Perspectives\Inversion\InversionPerspective.py", line 475, in check_q_high
ValueError: max() arg is an empty sequence
```

**Comment by smk78** [comment]
7. If you send data to Fitting and do Show Plot, the first time you grab a slider and drag it, it moves smoothly. Thereafter, or the other slider, does nothing until you unclick, at which point it jumps to the new position.

**Comment by butlerpd** [comment]
to @smk78 point 7, it is already itemized in #1762 as left to do (along with quite a few things) with the sliders.  It actually updated the q range numbers in the box on the panel but will not move until you release the mouse. at which point a recalculation and replot is done which takes some time. There is an underlying behavior question that is larger than the slider that is at play there I think.

**Comment by smk78** [comment]
These may already be known issues (in fact, I'm pretty certain I've seem at least one of these mentioned in an issue thread), but:

8. In the Inversion perspective, estimating the background doesn't seem to do anything, at least, the background level box never displays anything but 0.0, but when you click Calculate the radio button swaps to Manual Input.

9. There is some very weird stuff going on with editing the Total Q Range Min/Max boxes.

**Comment by smk78** [comment]
10. @rozyczko , on Quick Plots, eg the SLD profile in the Onion Model, was there not a way to allow the user to output the data displayed, rather than just the image?

**Comment by smk78** [comment]
11. Copy/Paste parameters from one model to a new FitPage with the same model works fine with one exception: if polydispersity is enabled in the model being copied from, paste will enable it in the new model and copy the PD value (great!). But the distribution type is _not_ copied. The new model defaults to Gaussian.

**Comment by smk78** [comment]
12. In the FitPage parameter table, why are the _Error_'s displayed in a larger font size than all other entries?

**Comment by smk78** [comment]
13. Having done a P(Q*S(Q) fit, then sent the same data to P(r), then flipped back to Fitting, I tried saving the session to a project. A json project file was created, but the Log Explorer said:
```
15:57:25 - INFO: data cannot be serialized to json: <class 'PyQt5.QtWidgets.QLineEdit'>
15:57:25 - INFO: data cannot be serialized to json: <class 'PyQt5.QtWidgets.QLineEdit'>
```
Closing the session, restarting SasView and opening the saved project loaded all the Fitting side of things (data, models, P(Q), S(Q), residuals) and the I(Q) _fit_ for P(r) and the P(r) itself, but did generate any plots. However, the Log Explorer reported:
```
16:03:33 - INFO:  --- SasView session started ---
16:03:33 - INFO: Python: 3.6.12 (default, Dec  9 2020, 00:11:44) [MSC v.1916 64 bit (AMD64)]
16:03:56 - ERROR: Traceback (most recent call last):
  File "site-packages\sasview-5.0.4-py3.6.egg\sas\qtgui\Perspectives\Inversion\InversionPerspective.py", line 459, in check_q_low
ValueError: min() arg is an empty sequence
16:03:56 - ERROR: Traceback (most recent call last):
  File "site-packages\sasview-5.0.4-py3.6.egg\sas\qtgui\Perspectives\Inversion\InversionPerspective.py", line 475, in check_q_high
ValueError: max() arg is an empty sequence
16:03:56 - ERROR: Traceback (most recent call last):
  File "site-packages\sasview-5.0.4-py3.6.egg\sas\qtgui\Perspectives\Inversion\InversionPerspective.py", line 459, in check_q_low
ValueError: min() arg is an empty sequence
16:03:56 - ERROR: Traceback (most recent call last):
  File "site-packages\sasview-5.0.4-py3.6.egg\sas\qtgui\Perspectives\Inversion\InversionPerspective.py", line 475, in check_q_high
ValueError: max() arg is an empty sequence
```
JSON file: [504rc1_testing.zip](https://github.com/SasView/sasview/files/5881747/504rc1_testing.zip)

**Comment by RichardHeenan** [comment]
13) has already been noted here https://github.com/SasView/sasview/issues/1689

**Comment by krzywon** [comment]
@smk78, with RC2 out now, can you recheck these issues? I believe issues 1, 3, 6, 7, 9, and 13 are fixed.

Other notes:
5. This has been around since the original 5.0 release and is similar to #1757. I'll update that ticket to be more general.
8. This is similar to #1765. Should we note the issue there as well?

**Comment by krzywon** [comment]
14. The values set in the Slicer Parameters window are not applied to data that is saved, but the values set by manipulating the slicer in the 2D plot are. This becomes obvious when changing the number of points, which can only be modified in the window.

**Comment by smk78** [comment]
> @smk78, with RC2 out now, can you recheck these issues? I believe issues 1, 3, 6, 7, 9, and 13 are fixed.

Re 1. No the 504RC2 **Windows** installer still overwrites the 503 default installation folder and no option to specify a different installation path is offered.

Re 3. Fixed in 504RC2.

Re 6. Seems fixed in 504RC2.

Re 7. Fixed in 504RC2.

Re 9. The original weirdness is fixed in 504RC2. However, I note that if you use the sliders the Min/Max boxes update dynamically (nice!), but if you edit the Min/Max boxes the sliders do not update until the plot is redrawn by Calculate.

Re 13. The two sets of error messages noted above are fixed in 504RC2. But now, when the project is opened again, there is no knowledge of the P(r) or the I(q) fit for the P(r). Checking a local build of the release_5.0.4 branch I find the same.

> 8. This is similar to #1765. Should we note the issue there as well?

So noted.

In 5.0.4 RC2 a plausible estimated background is now displayed. But if you switch to Manual, enter a background value, and click Calculate, the background level reverts to the estimated value.

**Comment by krzywon** [comment]
Oof... Yes, you're correct. This is related to points 1 and 2.
> Re 1. No the 504RC2 **Windows** installer still overwrites the 503 default installation folder and no option to specify a different installation path is offered.
> 

I've updated your comments and crossed these issues out for record keeping.
> Re 3. Fixed in 504RC2.
> 
> Re 6. Seems fixed in 504RC2.
> 
> Re 7. Fixed in 504RC2.
> 

The sliders also update when the plot gets focus again, for me at least. I haven't been able to figure this out and is a minor (in my opinion) visual bug, so I might punt this to post-5.0.4.
> Re 9. The original weirdness is fixed in 504RC2. However, I note that if you use the sliders the Min/Max boxes update dynamically (nice!), but if you edit the Min/Max boxes the sliders do not update until the plot is redrawn by Calculate.
> 

I just tested this and the P(r) data is loaded. The plots aren't opened on load (which needs to be fixed), but they exist. I just want to be sure you are seeing the same behavior before I dive into this.
> Re 13. The two sets of error messages noted above are fixed in 504RC2. But now, when the project is opened again, there is no knowledge of the P(r) or the I(q) fit for the P(r). Checking a local build of the release_5.0.4 branch I find the same.
>

**Comment by smk78** [comment]
> The sliders also update when the plot gets focus again, for me at least. I haven't been able to figure this out and is a minor (in my opinion) visual bug, so I might punt this to post-5.0.4.

I concur. It's not worth holding up the release for.

The installer issue (Point 2) however is a blocker. Should it have it's own ticket?

**Comment by butlerpd** [comment]
Can this ticket be closed for 5.04? do we need to generate any tickets for remaining items?

**Comment by smk78** [comment]
Testing release 5.0.4:

4 is still current. Probably needs @krzywon to ticket.
5 is still current but noted in #1757 .
8 is partially current (the background estimation still doesn't seem to do anything) but see #1765 .
10 is ticketed under #1669 .
11 is still current but may be related to #1587 & #1689 .
13 is still current but noted in #1689 .

**Comment by krzywon** [comment]
4 is now ticketed in #1817
