### ISSUE TITLE
"Save points as a file" does not accept freeform file extensions

### ISSUE THREAD

**Issue by toqduj** [SasView/sasview#1780]
When I want to save a fit, I click on the graph, go to the model, select "save points as a file". When I then select "text files", but want to save my file with a different extension, e.g. "my_beautiful_fit.csv", it seems to work, the file selection window is closed, but no file is written. 

This can be very annoying to find out that there are no files after exporting the fits of several optimizations. 

OS: Mac OS X, SasView 5.0.3

**Comment by rozyczko** [comment]
this seems to work on Windows so is potentially a MacOS porting issue?

**Comment by toqduj** [comment]
Could be, any other Mac user can verify?

**Comment by smk78** [comment]
Having locally built release_5.0.4 branch on x64/W10.

@toqduj is correct. The 'Save Points as File' dialog only saves the points if the file name specified is either a) missing a descriptor (ie, no .txt/.xml/.h5 is specified as part of the file name string) or b) if a file descriptor is specified but matches that in the 'Files of type' dropdown. You cannot, for example, specify 'Files of type' = Text (.txt) and then specify 'File name' = saved_points.iq If you do, no file is written. However, you _can_ specify 'Files of type' = CanSAS1D (.xml) and 'File name' = saved_points.txt This saves a text file, not an xml file! So there is some slightly weird processing of the two boxes going on.

On a separate point, I would agree with @toqduj that it would be nice to be able to save text files with a descriptor _other_ than .txt (eg, .dat, .q, .iq, etc). _However_, I do not think it would be good practice to allow a file to be called .csv which is patently not CSV.

**Comment by smk78** [comment]
Should we add CSV output?

**Comment by krzywon** [comment]
> Should we add CSV output?

That would be a good feature to have.

**Comment by rozyczko** [comment]
Ah, got it wrong! I thought you meant the non-txt files would not save at all... I agree the issue is as described above also on Windows.
