### ISSUE TITLE
cannot add/multiply using a plugin model

### ISSUE THREAD

**Issue by toqduj** [SasView/sasview#1781]
I tried making a modified power-law function that includes a high-Q cut-off using an error function. If I make this as a plugin model, it finds this fine, and this function works. 

However, then I want to add this to another model (e.g. fractal), using the add/multiply models functionality. This gives me the following error in the log when I click "apply" after selecting my plugin model and the fractal model:
18:57:51 - INFO: Model function (Test) has been set!
18:57:51 - ERROR: Error building model: No module named 'sasmodels.models.power_law_cutoff'
18:57:51 - ERROR:   File "/Applications/SasView5.app/Contents/MacOS/sasmodels/generate.py", line 1153, in load_kernel_module
    __import__('sasmodels.models.'+model_name)
ModuleNotFoundError: No module named 'sasmodels.models.power_law_cutoff'

This combination works again if I replace the original power-law function in the base sasview models with my modified function. Seems to be something with how the plugin models are loaded by sasmodels?

**Comment by smk78** [comment]
I think this is a duplication of https://github.com/SasView/sasview/issues/1451 ? Can we close this ticket?

@toqduj : basically you cannot make a plugin of a plugin using add|multiply; the workaround is to edit the .py and combine them there.

**Comment by toqduj** [comment]
Ah ok, @timsnow and I were not familiar with the prior art ;). Can close this ticket if it doesn't bring anything new to the table..
