### ISSUE TITLE
Rg*Qmax and Rg*Qmin are inverted in the Gunier linear fit

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#1782]
Rg*qmax is an important quantity for verifying the validity of the linearized Rg calculation.  Roughly it should be less than 1 though for a sphere it can be much as high as 2.

The linear fit for the Rg reports Rg*qmin in the box labelled Rg*qmax and the Rg*qmax value is reported in the Rg*qmin box. 

This should be very simple fix but is quite confusing at first.

**Comment by krzywon** [comment]
This was fixed when the PR was merged. Closing.
