### ISSUE TITLE
graph scale carries over to other pespectives 

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#1783]
This is part of a long standing issue of the intertwining of graphs, data, and the perspectives that use the data and create the graphs. There has been a lot of improvement but some issues remain.

In particular start by loading a 1D data set. Then create a new plot with this data.  Next change the scale of that plot to something like a Guinier (or Kratky or Porod etc) so lnI vs Q^2.  Next click send to fitting (with the same data set checked). Pick a model (I used a core shell sphere with an apoferritin data set). Now either fit or just show plot.  Two new plots show up: the residual plot and the I vs Q plot.  This I vs Q plot is properly labelled as such BUT is in fact the same lnI vs ^2 scale as the other plot with that data set.  Resetting the scale on this plot to log10x vs log10y correctly displays the data (with the correct labels).  One can continue by not changing the scale. Instead, while keeping the same data set clicked, send to inversion or invariant etc. now you have many plots all with the lnI vs Q^2 scale

Interestingly the corfunc perspective seems to be the only one that is immune to this.  probably because it does not use plots but is all in a self contained window?

**Comment by rozyczko** [comment]
Yes, corfunc's plots are perspective-centric rather than tracked in the main canvas, so their behaviour is different. I don't really like it, since it breaks the way we do plotting but rewriting this would be too costly.

Fixing the title issue seems reasonably easy, we already store the view scale in the Data object, so we just need to check it before plotting like we do with other properties. I thought it was already being done and I vaguely remember it working at some point?

**Comment by butlerpd** [comment]
I am thinking the same thing about corfunc needing a refactor so it behaves more similarly now that it works correctly.  But probably should wait till we sort out how best to handle the various interdependency issues we have... and anyway it is not the top priority probably for anybody at the moment given the amount of work and the fact that it "gets the job done" ?

**Comment by butlerpd** [comment]
This was also identified as very painful for actual use of linearized plots in real usage situations during the NIST CNR summer school however as noted in #3021 this probably cannot be added to 6.0.0 release.

Also another consequence identified is related to the linearized plots themselves. Consider a common workflow:
* load a series of data to be analyzed (for example a contrast match point series).
* Create a new plot with all data
* Scale the plot. For example a Porod plot which will show the incoherent background
* Now send each of those data to a new plot by itself
* The plot looks like it is in the right scale and checking the change scale panel suggests the data is Porod scaled.
* However, starting a linearized fit, the panel does not recognize that the plot is Porod and has the generic interface.
* Hitting the `Fit` buttons suggests that it is fitting the original log I vs log q data with the linear fit which does not fit the data on the  plot at all.
