### ISSUE TITLE
Batch fitting in 5.x returns different parameters to single fits in 5.x

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1794]
User Y-CC reports:

_We recently encountered confusing fitting outcomes when we are using the batch mode to fit our data in SasView. Our data came from an operando measurement, so there are several SAXS datasets along the measuring time. We first tried to fit some of them individually (single fit) and we decided that only a certain Q-range (0.015 – 0.3 Å-1) is of our interest and got a reasonable fit within that range. However, when we switched to the batch mode and tried to fit several datasets with the same model and initial parameters copied from the single fit, the fitting results are quite different from the single fit for the same dataset. It seems like SasView fitted a much larger Q-range than the range that we assigned but it is unclear which Q-range that was. We wonder if you have come across similar issues or we are missing some critical steps here. Please find the log file as attached. I performed again the single and batch fitting right before writing this email, so hopefully you can find the latest activities at the bottom of the log._ 

[sasview.log](https://github.com/SasView/sasview/files/6023127/sasview.log)

**Comment by smk78** [comment]
I have conducted comparative tests of 4.2.2 and several 5.0.x versions as follows:

**1. Run 4.2.2**
2. Load the 3 AOT_Micromulsion datasets in \test\1d_data
2. Select only the Core_Contrast & send to Fitting
3. Select a Sphere model
4. Set Qmax for fitting to 0.181
5. Check the parameters _scale_, _background_, and _radius_
6. Fit

![image](https://user-images.githubusercontent.com/10938679/108733335-51696200-7526-11eb-8840-02b60c1b59bb.png)
![image](https://user-images.githubusercontent.com/10938679/108733392-60e8ab00-7526-11eb-899d-52fec18eab9f.png)

7. Select all 3 datasets
8. Select Batch Mode
9. Send to Fitting
10. In the BatchPage data source dropdown select the Core_Contrast
11. Select a Sphere model
12. Set Qmax for fitting to 0.181
13. Check the parameters _scale_, _background_, and _radius_
14. Fit

![image](https://user-images.githubusercontent.com/10938679/108734338-482cc500-7527-11eb-9404-b40fe695ee63.png)
![image](https://user-images.githubusercontent.com/10938679/108734398-58dd3b00-7527-11eb-816e-b811c3dbfdba.png)

**Observe that the _Chi-squared_, _background_, _radius_, and _scale_ for the Core_Contrast dataset are the same for the Single Fit case and for the Batch Fit case.**

**15. Run 5.0.4**
16. Repeat the Single Fit exercise

![image](https://user-images.githubusercontent.com/10938679/108738391-77453580-752b-11eb-8c46-173bd981789d.png)
![image](https://user-images.githubusercontent.com/10938679/108738473-8926d880-752b-11eb-8bf3-3bcf99b84fa0.png)

As we would expect/hope, this returns the same _Chi-squared_, _background_, _radius_, and _scale_ for the Core_Contrast dataset as for the Single Fit exercise in 4.2.2. 

17. Now repeat the Batch Fit exercise.

![image](https://user-images.githubusercontent.com/10938679/108739179-444f7180-752c-11eb-8cf4-485a22b8a8a0.png)
![image](https://user-images.githubusercontent.com/10938679/108739214-516c6080-752c-11eb-92b4-68edc7814ec1.png)

**Observe that we now have a completely different set of parameter values, although they are not unbelievable (except perhaps the chi-squared).**

I've also tried 5.0.0 and 5.0.3 with the same outcome. NB: the 5.0.x versions are mutually consistent in their output.

Q: what is going on here?

**Comment by krzywon** [comment]
Do you think this might be related to batch fitting not using `dI` outlined in #1446?

Testing your same setup in 4.2.2, but with `dI == No Weighting` I get these results which are similar to your 5.0.x results.
![422-no-dI](https://user-images.githubusercontent.com/10947925/108746451-57514a00-750a-11eb-9034-e790dc8e4316.png)

**Comment by smk78** [comment]
Nice spot, @krzywon !

I would say so. I just did a Single Fit in 5.0.4 with dI = None and got this:
![image](https://user-images.githubusercontent.com/10938679/108747576-7ca77d80-7535-11eb-9fb5-73a865dbbb4d.png)

Which are **_exactly_** the same values as in the Batch Fitting Results Table. Even the parameter uncertainties are the same.

**Comment by smk78** [comment]
I just checked our Release Notes. We have never made Users aware of this! Whoops! There goes disciplined and professional...

**Comment by smk78** [comment]
Have pushed an update to the release notes in the release_504 branch.

NB: the update is sitting under the v5.0.3 Known Issues so will not need revisiting if this issue is fixed for 5.0.4

**Comment by butlerpd** [comment]
I don't understand how @krzywon keeps DOING that!!  🤣

**Comment by krzywon** [comment]
I have some local changes that are nearly finished with fixes for this issue, #1446, #1795, and #1796 so I've taken them all as my own. It's a pretty small fix (8 lines changed so far), so this might be all make 5.0.4 final, but I will keep the plotting issue commits separate from the `dI` and Q range commits in case we want to separate them.
