### ISSUE TITLE
No Check Model functionality in 5.x

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1800]
In 4.x, the Advanced Plugin Model Editor incorporates functionality to check the validity of the code in the selected plugin (Run > Check Model):

![image](https://user-images.githubusercontent.com/10938679/109783959-75056a00-7c02-11eb-9c7e-e03806dc7a8f.png)

The output is extremely valuable for debugging plugin models:

![image](https://user-images.githubusercontent.com/10938679/109783895-5f904000-7c02-11eb-9240-698911dde17c.png)

In this instance, for example, highlighting that the User had used _define random():_ instead of _def random():_

In 4.x this output **is not** duplicated in either the Console or _sasview.txt_.

Unfortunately there is no equivalent Check Model functionality in 5.x (the following screenshots are from 5.04 RC3):

![image](https://user-images.githubusercontent.com/10938679/109785331-ee518c80-7c03-11eb-9068-ed8c019d50e1.png)

![image](https://user-images.githubusercontent.com/10938679/109785526-1ccf6780-7c04-11eb-8410-ccdde4f602db.png)

The issue here is that if 5.x cannot compile a plugin then it simply passes over it. Nothing to say it could not compile a plugin is output to the Log Explorer or _sasview.txt_. This actually makes 5.x pretty much useless for developing or tweaking a plugin by editing the code.

Can the Check Model functionality be reinstated in 5.x?

**Comment by rozyczko** [comment]
Yes, this is indeed missing. `Wx` had a nice python editor/syntax checker built in, but `Qt` has nothing like that so far.
Reimplementing this functionality in Qt will be a pretty hefty effort, unless there is a ready component out there we can reuse.

**Comment by rozyczko** [comment]
QScintilla2 might be a solution to that... investigating

**Comment by rozyczko** [comment]
using `ast` along with showing the results with `traceback` seems to be doing the trick.

**Comment by butlerpd** [comment]
Just did a quick search on ast -- that does seem promising!!

**Comment by rozyczko** [comment]
Added a syntax check for the edit model window.
Also, added support for line numbers and current row highlighting

branch: `improved_model_check`

**Comment by krzywon** [comment]
This was fixed with #1875
