### ISSUE TITLE
update date in sphinx-docs and update release deployment instructions on the wiki

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#1813]
In reviewing the final release 5.0.4 the sphinx docs had correctly listed the version as 5.0.4 but the copyright date showed 2019 (significantly behind).  Reviewing the release deployment notes on the wiki it appears that those notes only mention the need to change the `release = x.x.x` variable but failed to mention the need to change the `copyright = u'xxxx, The SasView Project'` variable, both in the `docs/sphinx-docs/source/conf.py` file
TODO:
* Add note to the wiki about the need to change the `copyright` variable
*  Change the `docs/sphinx-docs/source/conf.py` to 2021.

**Comment by smk78** [comment]
Also note in the wiki that the `Copyright` year also needs to be updated in:

`/build_tools/release_automation.py` (NB: but this picks up datetime.datetime.now().year)

`/installers/license.txt`

`/src/sas/qtgui/Utilities/LocalConfig.py`

`LICENSE.TXT`

**Comment by smk78** [comment]
On pulling the release_5.0.4 branch it seems:

* persons unknown _have_ already updated `docs/sphinx-docs/source/conf.py` to 2021
* `/installers/license.txt` is already updated to 2021
* `/src/sas/qtgui/Utilities/LocalConfig.py` _requires_ updating to 2021
* `LICENSE.TXT` is already updated to to 2021

**Comment by smk78** [comment]
Updated copyright in `/src/sas/qtgui/Utilities/LocalConfig.py` to 2021

**Comment by smk78** [comment]
Updated http://trac.sasview.org/wiki/DevNotes/Processeses/DeploymentProcess

**Comment by butlerpd** [comment]
*ahem* I'm afraid that a git blame will reveal that indeed  after identifying that the date in `docs/sphinx-docs/source/conf.py` had not been updated, and that it was not in fact listed as a todo in the deployment instructions, I did both and being undisciplined made the 2019 -> 2021 change directly to the 5.0.4 release branch. 

I note that the date in LocalConfig.py is also not listed as a todo in the deployment process and probably should be ... though I'm not sure where it gets used.  The one in `docs/sphinx-docs/source/conf.py` is what is listed at the bottom of every page of the documentation.  We really do need to consolidate all of these into one place ☹️

**Comment by smk78** [comment]
:-)

Fear not. As noted above, LocalConfig.py and the deployment notes have both now been updated.
