### ISSUE TITLE
In 5.0.4 release: Reset Q limits button has no effect

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1814]
Reported by user GregS at ISIS:

_I was using the newly released 5.0.4 today, and I noticed a bug when adjusting the Q limits on some fitting._
 
_If you adjust the limits, you cannot reset to the data Q_min and Q_max using the “reset” button. Pressing the button doesn’t do anything. You can revert to a Q limit by choosing a value that is much bigger or smaller than the one from the data._
 
_This was not the behaviour in previous versions of SasView 4 or 5. Pressing the reset button restored the data Q limits._

**Comment by krzywon** [comment]
This is now fixed in v5.0.5. @smk78 can you verify and close this if so?

**Comment by smk78** [comment]
Testing release 5.0.5 on W10/x64.
Clicking the Reset button does indeed reset the range values in the Fit Options tab. The range bars themselves then reset on the next plot update.
