### ISSUE TITLE
orientation average in scattering calculator

### ISSUE THREAD

**Issue by dehoni** [SasView/sasview#1824]
Typically one does not measure a well oriented system, but one has a random orientation distribution of particle axis around a symmetry axis like the applied magnetic field. To obtain scattering cross section relatable to measured quantities the simulation box should be allowed to rotate with respect to the instrument/lab coordinate system. This would also be helpful if the simulation data come with a different orientation that expected for the scattering geometry.

**Comment by butlerpd** [comment]
This I think refers to the general scattering calculator?  If so this is probably a general architecture need as this would be useful/important even for just nuclear scattering for anisotropic shapes

**Comment by dehoni** [comment]
In the documentation, we provide a script that demonstrates how to do orientational averages: https://github.com/SasView/sasview/pull/1974/files#diff-6825133a3d2ef3f786d4f9f5f62aa70071a146400edebe3926b1396609de7bcb. Similiarly, this will work for other cases, e.g. rocking scans etc. It will be custom-made solutions depending on what exact system has been measured and what the measurement protocol was.
