### ISSUE TITLE
Graph Range resets to default on replot

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#1830]
This was supposedly addressed by PR #1779 which was merged into release 5.0.4.  However, Elliot Gilbert of ANSTO recently pointed out that when in the fitting perspective, every manual parameter change reset the graph range back to the default, making it impossible to work with when the parameter he was trying to optimize affected mostly small features at high Q necessitating zooming into that region while changing the parameter.

It is not clear how this got reverted but a quick test suggests that this is not an issue with linearized plots (the area where this general replot issue was originally identified in issue #1750.

This clearly needs to be fixed but it would also be useful to understand how this change got partially reverted before the 5.0.4 release so as to be try and prevent such from happening in the future.

**Comment by smk78** [comment]
So far this afternoon I've been using the 5.0.4 release and doing some 'custom' plots in the process. TBH, plot operations are not so bad, and a _WHOLE__ lot better than in 5.0.3. There is something though - haven't quite put my finger in it yet - which resets my custom axis labels to Intensity and Q, even though I'd changed them both to something completely different...

**Comment by smk78** [comment]
Re my comment above. If you have changed your X & Y axis labels - which you do by bringing up _Toggle Navigation Menu_ and clicking _Edit axis, curve and image parameters_ and editing the labels - and **then** use the right-click context menu to _Modify Plot Property_ for a particular dataset, simply opening the _Modify_ dialog and then exiting it is enough to reset the axis labels to Q and Intensity!

**Comment by butlerpd** [comment]
Ah ... I believe that is a completely separate issue that was documented a while back.... looks like in issue #1584? (I am soooo proud of myself finding it on my own 😄 The issue as I understand it is the conflict between the matplotlib widget (the navigation tool bar) and the sasview menu item which bypasses said widget.

**Comment by krzywon** [comment]
I tested this from the main branch and the graph range is maintained after replotting a plot for any reason (fitting, linear fits, P(r), etc.).

The fix for this, similar to #1841, was not included in the v5.0.4 release and I think figuring out why is the real issue.

**Comment by butlerpd** [comment]
This is indeed quite troubling!  Specially seeing that it is more than just one issue.  Is the difference to do with something missing on the release build machine?  Maybe we should check the jenkins build of the main branch?

**Comment by butlerpd** [comment]
@krzywon I believe this is now resolved but most of the discussion was moved from this issue to the PR itself - and this was not linked to that?  As far as I'm concerned this is resolved but leaving it open for now in case you know something I don't. Otherwise please go ahead and close this if you agree with my assessment.

**Comment by krzywon** [comment]
Correct me if I'm wrong, @butlerpd, but I believe the majority of this ticket is now fixed. The only outstanding part of it is documented in #1982.

**Comment by butlerpd** [comment]
Done then ... Let's close it.Thanks @krzywon
