### ISSUE TITLE
radius_effective does not update when using S(Q) with SESANS model

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1837]
This issue replaces umbrella issue https://github.com/SasView/sasview/issues/1697

The following behaviour was identified in 5.0.3.

When you introduce an S(Q) into into a model you introduce an effective radius parameter, _radius_effective_, for the S(Q) in addition to the radius from the P(Q). The default behaviour of the model is that these are tied together so that as the _radius_ optimises _radius_effective_ should also change. This happens if you are fitting conventional SANS data but not when the data is .ses data. **This needs investigation and fixing**.

For the time being, the only workaround is to set _radius_effective_mode = unconstrained_ and update _radius_effective_ manually as fitting proceeds.

Also see #1648

**Comment by butlerpd** [comment]
Hummm... testing in 5.0.5RC2 on windows, it seems that for "normal" sans size objects the constraint works but fitting USANS data of spheres or even desmeared USANS (i.e. SANS like data) the radius effective is not constrained.  This needs more investigating and may be related to the beta approximation not working if resolution is included in the data?

**Comment by butlerpd** [comment]
Also see #1525.

**Comment by butlerpd** [comment]
I cannot remember this and am sure I've never worked on the sesans issue but I guess there was the question of it also not working for USANS. I notice that @caitwolf has self-assigned this a week ago so assuming she was going to look at this during code camp?

**Comment by caitwolf** [comment]
@butlerpd @smk78 I just tested this for both SESANS and USANS data and the problem seems to be resolved so I think this issue can be closed.
