### ISSUE TITLE
Simple file issue negates Use dQ for resolution without warning

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1841]
Quite by chance today, whilst helping a beamline User, I discovered that there are instances where SasView will _not_ use the dQ data in your datafile for resolution smearing. The cause is not the fault of SasView (in my case it is a Mantid issue), but the problem is SasView handles the problem totally silently: there are no pop-ups, no messages in the Log Explorer, nor, so far as I can see, anything in sasview.log. Thus you could easily analyse a bunch of runs and be completely oblivious to the fact that they have not all been treated equally in terms of the resolution smearing applied.

The issue is exemplified by the two datasets in this zip file: 
[data.zip](https://github.com/SasView/sasview/files/6446055/data.zip)

The only difference between them is that the _not_ok_ file contains this final line of Idata:
```
<Idata><Q unit="1/A">0.250664</Q><I unit="1/cm">0</I><Idev unit="1/cm">1e+06</Idev><Qdev unit="1/A">0</Qdev></Idata>
```
The zero for Qdev causes SasView to set Instrumental Smearing to nothing. Not even to None.

At the very least a message should be output to the Log Explorer.

The issue applies to .txt, .xml, and .h5 data files carrying Qdev information.

**Comment by RichardHeenan** [comment]
This has already been dealt with in v5, which version were you running?

( I will close this, but please re-open if you think there is still an issue)

https://github.com/SasView/sasview/issues/1804

https://github.com/SasView/sasview/pull/1807

**Comment by smk78** [comment]
Ok, so as usual I failed to find the previous issues on this! :-) However, though those issues are closed, I'm afraid they haven't fully resolved the issue as my finding/data above demonstrate. I was running release 5.0.4 on W10/x64. Re-opening this issue for now, though in all likelihood one of those @RichardHeenan mentions above probably needs reopening.

**Comment by krzywon** [comment]
I just tested this on the main branch and the dQ options are available when loading both data sets in the zip file provided my @smk78. I'm not sure why this did not made the release, but #1830, where the graph range resets, is another item like this, where everything works as expected when running from the main branch, but does not work in v5.0.4 release.

I think the bigger issue is figuring out how these two fixes were omitted.

**Comment by smk78** [comment]
Testing 5.0.5rc1 on W10/x64 with zip file above this issue is now handled gracefully and both datasets load with dQ.

So am closing this issue.
