### ISSUE TITLE
Unhook travis

### ISSUE THREAD

**Issue by wpotrzebowski** [SasView/sasview#1844]
Can we unhook travis now even though we are not putting commits on the slack channel?

Τravis builds are failing because scipy/numpy dropped support for python 3.6.

**Comment by llimeht** [comment]
The GitHub Actions are already running SasView against Python 3.7 and 3.8 with the latest versions of the wheels for numpy and scipy for those versions. It might not be as difficult as it might first seems.

**Comment by lucas-wilkins** [comment]
Pretty sure this is now irrelevant.
