### ISSUE TITLE
Update python and dependent modules - the pyinstaller step.

### ISSUE THREAD

**Issue by rozyczko** [SasView/sasview#1855]
Python version and external modules we rely on needs updating.
Currently we freeze the versioning of most modules for stability but it has been a while since we upgraded the major components like MPL, numpy, pyopencl etc.

I tested SasView with the most up-to-date versions and the dev build works perfectly well.
However, packaging it with pyinstaller fails, so fixing this is the main task here.

**Comment by butlerpd** [comment]
@rozyczko can you update? with github actions and other things going on is this still a thing even? or should we close the ticket?

**Comment by rozyczko** [comment]
Indeed, GH actions solved this problem. Closing.
