### ISSUE TITLE
Update links on sasview.org

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#1857]
[Links & Downloads](https://www.sasview.org/download/) page points to trac for the project wiki instead of the [github sasview wiki](https://github.com/SasView/sasview/wiki).

Other links should be checked.

**Comment by butlerpd** [comment]
Note that wiki.sasview.org now points to github wiki.  Probably best to replace all direct links to trac by links to wiki.sasview.org so that if we move it in the future the links won't break.

**Comment by smk78** [comment]
Link on Links&Downloads updated. Old link moved down to 'Historical Information'.

**Comment by smk78** [comment]
Other locations requiring attention are:

- sesans_fitting.rst
- RELEASE.rst
- about.md (x2)
- faq.md
- getting_started_with_sasview tutorial (.fodt & .pdf)
-

**Comment by butlerpd** [comment]
the links noted by smk78 still need updating.  This should be straightforward? so maybe see if somebody will do at codecampX?

**Comment by smk78** [comment]
Searching across *.* in all our repos for instances of 'trac.sasview' only finds occurrences:
 - in old versions of SasView (eg, in README's)
 - in old versions of the SasView documentation
 - on the website download page (and that is a deliberate link to trac.sasview.org)
 - some circa 2018 CLI instructions and notebooks in \documents
 
I am therefore going to close this issue as resolved.
