### ISSUE TITLE
Resolution function help does not explain how to include resolution information in a datafile

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1858]
User AdrianR points out that resolution.rst does not actually include any information about how to include dQ information for slit-smeared data in a data file. We do, however, provide some information in invariant_help.rst !

resolution.rst should be updated.

**Comment by pkienzle** [comment]
File formats are described in  `sasview/src/sas/qtgui/MainWindow/media/data_formats_help.rst`. You could document it there, and maybe reference it from `resolution.rst`. 

The problem is that `resolution.rst` is in sasmodels, which nominally doesn't know anything about sasview or data file formats. That's also why `sasview_model.py` isn't part of the sasmodels package.😐

**Comment by butlerpd** [comment]
OK that formats is a bit rudimentary and not totally accurate.  SasView recognizes quite a few special extensions which are legacy special formats. Also the ISIS 1D format PDF sends to an ISIS "front page" of a website (not a pdf) which I cannot find a format on.

That said the particular issue brought up by Adrian is a bit more subtle and not clear what is actionable there as it is really about co-opting the NIST USANS format (*.ABS) to use for another purpose.  That is documented in the linked to site. We'll have to think more about that, but certainly we could spend some time improving the formats page (and a lot of others too :-)

**Comment by smk78** [comment]
> Also the ISIS 1D format PDF sends to an ISIS "front page" of a website (not a pdf) which I cannot find a format on.

Yes. Our website was re-engineered (again). Does this link to the PDF work: https://www.isis.stfc.ac.uk/Pages/colette-ascii-file-format-descriptions.pdf (it's not easy for me to tell from the 'inside'!)

**Comment by smk78** [comment]
> That said the particular issue brought up by Adrian is a bit more subtle and not clear what is actionable there as it is really about co-opting the NIST USANS format (*.ABS) to use for another purpose. 

Copying here excepts from an email thread so the issue is not lost:

>(AdrianR): A question for which I did not find an answer in the Help documentation is a definition of the input format for data that is slit smeared (I am particularly interested in Bonse-Hart data): in the case of simple ASCII data I understand that SASview will read 4 columns of numbers and if the value in the last column is negative it will take this as a value of dQ for slit height smearing.   Is this correct?   Is there a way to set the slit width if one wanted to do that?

>(@butlerpd): Basically you need to mimic the BT5 format because historically that is what we had.  The preferred method is to use NXcanSAS of course.

>(AdrianR): I had indeed been looking at BT5 data as examples.  In the attached columns 4, 5 and 6 (from the Igor reduction) are identical although the documentation under 'Invariant' implies that column 5 must duplicate column 1 and not column 4.  
An experiment with just 4 columns had also populated just the slit height in SASview 5.03 and seems to show similar calculations to the six column file that is attached.  This was the reason to ask about the specification.
[A1dry_6500.cor.txt](https://github.com/SasView/sasview/files/6521277/A1dry_6500.cor.txt)

>(@butlerpd): Speaking to @krzywon this afternoon during the workshop, he looked at the code and apparently the reader DOES look for BT5 in the header.  If it is there then Q is taken from column 1 as usual but if not it is taken from column 5.  This is the NIST format which is being read.  So it turns out that not copying Q into column 5 still works. I will have to revisit my kludge for the invariant.  I'm not sure why it works with just a four column format, but maybe somebody decided that making the assumption that a negative sigmaQ should indicate slit height (technically it should be length according to canSAS nomenclature :-) rather than a Gaussian width in pinhole resolution of q was generally reasonable?  Technically with 4 columns It should be read by the generic default reader ... I think? though @krzywon may know different.

**Comment by butlerpd** [comment]
Update from conversation between @krycket @butlerpd and Adrian Rennie:
* Adrian believes there will be an increasing number of lab slit smeared USAXS sources.
* Adrian suggests that manufacturers don't seem ready to produce canSAS compliant datafiles (yet) but might be willing to do something simple to make their data compatible with SasView.
* SasView probably does not want to go down the path of undercutting the canSAS standardization efforts and create new formats on its own, as standard formats makes long term support and sustainability of SasView also much less complicated.
* It seems that the legacy NIST reader (*.COR or *.ABS files) will accept 4 column data if the 4th column contains a negative number.  The absolute value of that negative number being interpreted as the slight length of an "infinite slit" collimation. 

**AGREED:** See if his USAXS manufacturer is willing to use a 4 column ASCII in this way, probably using *.COR nomenclature.

**Comment by smk78** [comment]
PRs above are now merged so am closing this issue.
