### ISSUE TITLE
Unable to find/load NXcanSAS reader using Development Builds

### ISSUE THREAD

**Issue by krzywon** [SasView/sasview#1879]
Greg Smith and Jan Ilavsky have both reported an issue with the NXcanSAS reader in MacOS. The release version works in Mojave, but not in BigSur and possibly not in Catalina.

Both had similar tracebacks to this, suggesting the `cansas_reader_HDF5.py` reader cannot be found.
> 13:27:23 - INFO: --- SasView session started ---
> 13:27:23 - INFO: Python: 3.6.6 | packaged by conda-forge | (default, Jul 26 2018, 09:55:02)
> [GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]
> 13:27:35 - ERROR: No module named 'sas.sascalc.dataloader.readers.cansas_reader_HDF5'No module named 'sas.sascalc.dataloader.readers.cansas_reader_HDF5'
> 13:27:35 - ERROR: The data file you selected could not be loaded.
> Make sure the content of your file is properly formatted.

**Comment by gnsmith** [comment]
I am running Catalina and not Big Sur, so I can confirm that this is something in the update from Mojave to Catalina.

**Comment by krzywon** [comment]
New information: This is happening on the latest Windows development builds as well! This looks like a package dependency issue.

**Comment by jilavsky** [comment]
In my case I do not use development build on Mac - it is release for Mac, version 5.04. And it worked fine when I reinstalled the release, at least for short time I used it. After my Mac died I am now running on loaner from external SSD with clone of the old operating system from dead mac. Not sure if this has any impact, but it may be important. In summary: worked freshly installed, then stopped working for some reason. Either reboot, move to different location, move to different drive,... Something broke the library reader loading.

**Comment by krzywon** [comment]
Just a follow-up to this, I've run more tests, and more than just the HDF5 reader is broken, but there is no obvious pattern to what is working and what is not. Since release v5.0.4, I updated associations.py to use importlib and I think that might be related.

Good:
cansas_reader (xml)
ascii_reader (txt)
red2d_reader (dat)

Failing:
csv_reader (csv)
abs_reader (abs/cor)
cansas_reader_HDF5 (h5/hdf/hdf5/nxs)
anton_paar_saxs_reader (pdh)
sesans_reader (ses/sesans)
danse_reader (sans)

**Comment by smk78** [comment]
@krzywon just emailed you a thread that might jog your memory.

**Comment by smk78** [comment]
If it helps, in my local build of SasView main and Sasmodels master all formats are loaded and display.
