### ISSUE TITLE
Don't show SLD Profile button for models without a profile

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1897]
Using Release 5.0.4, clicking the Show SLD Profile button in the unified_power_rg model returns
```
ERROR: SLD profile calculation failed.
```

It works in the onion model...

**Comment by smk78** [comment]
Replaced by https://github.com/SasView/sasmodels/issues/475

**Comment by pkienzle** [comment]
The program is correctly not showing the profile because it is not a shape-based model.

I'm changing the title to reflect that the profile button should be disabled or hidden in sasview for models that do not have an associated profile.

**Comment by butlerpd** [comment]
I think this is related to the RPA issue https://github.com/SasView/sasmodels/issues/396 (SLD also fails for RPA of course) in that it is misusing the "control" parameter.  SLD seems to be attached to each model with a control parameter (and shown on the control parameter linked in the GUI interface).  In other words all "multiplicity" models and only "multiplicity" models get the button.

We should decouple the show SLD from any parameter on the interface and provide that button only when a query to the model returns that an SLD function is available (`hasSLD = True` for example). Further that button should not be part of the parameter table IMO

At any rate this clearly cannot be done for 5.0.5 so moving it to 5.1

**Comment by rozyczko** [comment]
Not having the `Show SLD` button part of the table would simplify quite a lot of logic inside the table. I am for it.

**Comment by butlerpd** [comment]
This should have closed with the merge of #2647. Doing it manually
