### ISSUE TITLE
Matplotlib qt-based backends require an external pyqt4, pyqt5, or pyside package to be installed, but it was not found

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1905]
User TimT was unable to start 4.2.2 on a machine that had been running 5.x. None of the workarounds listed in https://www.sasview.org/faq/#why-will-sasview-no-longer-start would remedy the problem.

In support exchanges Tim found the following error message in SasViewCom (?):
>Matplotlib qt-based backends require an external pyqt4, pyqt5, or pyside package to be installed, but it was not found

When the PyQt5 file was manually added to the parent folder SasView started.

NB: I asked Tim to check if his machine had a HOME environment variable set (see https://github.com/SasView/sasview/issues/1904), but it did not.

**Comment by smk78** [comment]
@wpotrzebowski commented on the developers list:

>Looking at all this magic I am wondering if setting up developers environment wouldn’t make more sense?
And now when we showed with GH actions that we can get rid of conda (we use only pip there) one can even consider putting sasview on pypi (to be able to do “pip install sasview”).  Any thoughts?

**Comment by andyfaff** [comment]
`pip` installing a package is always nice. If you use an entry point then one should be able to type `sasview` (or something like that) to start it up.

**Comment by lucas-wilkins** [comment]
Seems this is resolved in a sense, and will be decreasing relevant if not.

**Comment by lucas-wilkins** [comment]
Since there has not been any update on whether or not this has been satisfactorily resolved, I'm closing.
