### ISSUE TITLE
Easy Add/Multiply Editor overwrites an existing plugin model even if Overwrite box is unchecked

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1906]
While testing https://github.com/SasView/sasview/pull/1901 I noticed a bug **which is also present in the current release**: if you use add/multiply and specify an existing plugin model plugin name, and then change the model selection, clicking Apply overwrites the existing plugin model even if the 'Overwrite' box is unchecked!

**Comment by rozyczko** [comment]
This indeed is a serious issue.
Fixed.

**Comment by smk78** [comment]
Testing 5.0.5rc1 on W10/x64 this seems to be fixed:
![image](https://user-images.githubusercontent.com/10938679/150002121-81a9a790-50f5-4d88-a114-773b1ac467f1.png)

So am closing this issue.
