### ISSUE TITLE
Add uncertainties to requirements in setup.py

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1910]
@pkienzle notes:

This commit from last October added a dependence on uncertainties, but didn't update setup.py to include it in the package requirements.
 
https://github.com/SasView/sasview/commit/f6b7c9900b7210a3ca162a6b8b5434aaf5bafbdb

It needs adding.

**Comment by butlerpd** [comment]
This only affects local builds for developers so not relevant to the release.

**Comment by lucas-wilkins** [comment]
@pkienzle @smk78 @butlerpd This looks like it can be closed, is this right?

**Comment by butlerpd** [comment]
I believe so but it was @smk78 who was trying to run things locally that was not working so I'll let him say whether it was fixed.

**Comment by smk78** [comment]
Yes, is fine now I think.
