### ISSUE TITLE
Fitting in GUI has become impossibly slow

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#1922]
I have been noticing recently that often fits seem to be taking way longer than I think they should. In testing a PR today I discovered an example that demonstrates that clearly is a real problem: running a "simple" fit using the Oct 13 Jenkins build of the main branch was 25 times slower than when doing the same fit using the release version 4.2.2.  The test was performed on a windows 10 non-GPU computer using the LM optimizer.  The default starting values were used and verified to be identical between the two versions

**Steps Taken**
* Load SasView GUI
* Load appoferritin.txt data from the test/1D folder
* Send data to fitting
* Choose sphere and core_shell_sphere
* Click to fit: scale, background, radius, thickness, sld_shell

**Outcome:**
* Calculated parameters are the same
* The uncertainty on sld_shell was 1E5 larger for version 5.0.5a1 than for 4.2.2 (all others are roughly the same)
* Time:
  * SasView 4.2.2 ~1s
  * SasVIew 5.0.5a1 ~25s
 
This seems unacceptable so for now am labelling this a blocker

**Comment by smk78** [comment]
As I just happened to have my laptop on... Trying the above with 5.0.5a1 installer build 559 from Aug 20 on W10/x64 it fitted in ~1s (using LM, no GPU).

**Comment by smk78** [comment]
And just for you @butler I just installed todays Jenkins build 569 installer and it also took ~1s.
![image](https://user-images.githubusercontent.com/10938679/137235276-8fafdff4-308a-4dcf-bb8c-bfcdba5fdaae.png)

**Comment by smk78** [comment]
Well, in GPU Options 'No OpenCL' was checked... but I've tried enabling/unenabling and resetting and get ostensibly the same times.

**Comment by butlerpd** [comment]
This was noted on a very slow windows machine and may have been related to the high CPU usage that was recently noted and fixed. At any rate, as there have been no other complaints I am going to close this issue.
