### ISSUE TITLE
mpl and context menu conflict over control of the "graph range"?

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#1925]
If the plot range is set using `Set Graph Range` from the plot context menu that range can only be reset by using the context menu `Reset Graph Range` menu item.  However, if the range is set from the mpl toolbar using the graphical mouse dragging, then both the mpl `home` button and the `Reset Graph Range` seem to behave the same.
This may in fact be linked to issue #1924 - perhaps a clue?

**Comment by lucas-wilkins** [comment]
Is this fixed @butlerpd @rozyczko @krzywon - if so, please close!

**Comment by butlerpd** [comment]
I believe this was fixed in 5.0.4 but @krzywon would be the better judge as the person who worked on the problem?

**Comment by butlerpd** [comment]
probably can be deleted -- but again - need to wait for @krzywon

**Comment by krzywon** [comment]
This was fixed in #1884. Closing until someone tells me otherwise
