### ISSUE TITLE
Fitting details panel not displaying correct information when SESANS data loaded

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1932]
The fitting details panel at the bottom of the FitPage normally displays the minimum and maximum values of the data range, and whether the data contains dI uncertainties from smearing.

When SESANS (.ses) data is loaded, there are some oddities:

- though the data is real space, the min/max values still show inverse units;
- the min value remains unchanged at the FitPage default (0.0005 Ang-1), though if the min value is altered in Fitting Options it does change;
- the max value is set to the largest spin-echo length in the data file;
- Smearing is announced as 'Use dQ Data', possibly because the file contains more than 3 columns so the third column is being interpreted as dI (it is actually dP).

Prior to loading data:
![image](https://user-images.githubusercontent.com/10938679/138767025-2a5ebbeb-f02a-4b67-9904-bd1078aba617.png)

After loading sphere2micron.ses:
![image](https://user-images.githubusercontent.com/10938679/138767132-68f4a23b-4d9d-43e0-9a75-35b68d2abaec.png)

Suggestions:
The min spin-echo length in the file should be displayed when the file is loaded.
The .ses format does actually carry the units of spin-echo length and this could be used to ensure that whatever value is read is correctly converted to Angstroms.
If dP is read this should be stated.

**Comment by wpotrzebowski** [comment]
@caitwolf can this issue be closed now?

**Comment by caitwolf** [comment]
@wpotrzebowski Not yet, there are some more defaults that need to be updated on the fitting details panel upon loading of SESANS data. I'm working on this now, I've figured out the issue with the min range not updating for SESANS but I'm still working on the unit label and dP label.

**Comment by butlerpd** [comment]
@caitwolf, @gnsmith, @rmdalgliesh, @smk78  Is this sesans fix something that we want to have in 6.0? If so should we make a PR from the branch (1932-fitting-details-panel-not-displaying-correct-information-when-sesans-data-loaded), redirect it to release_6.0.0 and call it a draft? It would have to move beyond a draft before the end of contributor camp though to be viable.
