### ISSUE TITLE
Unable to save extrapolation in Corfunc in 5.x

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1936]
Highlighted by User LeideC.

When using Corfunc in 4.x you can save the extrapolated I(Q) prior to transform to file. This is not possible in 5.x (there is a Save button which saves the real-space distance and transforms, but _not_ the input to the transform routine).

**Comment by smk78** [comment]
Apologies for being a bit late to the party. I have just built _main_ locally and tested the functionality added by PR #2055 with the 1d dataset ISIS_98929.TXT and have some comments:

The PR added a Save Extrapolation button
![image](https://user-images.githubusercontent.com/10938679/173963600-4560aa52-050f-4a47-921e-36b02f8d681c.png)
which brings up a pop-up dialog
![image](https://user-images.githubusercontent.com/10938679/173963645-d82d7d38-970e-4f91-a524-776ee2726eda.png)

Selecting Use Input Q Values does not appear to save any extrapolation, only the original data values. I was expecting it to save low-Q extrap + original data values + high-Q extrap.

The only available output file format from this dialog is tab-separated values (.tsv) which I do not believe we use anywhere else in SasView. The Save Transformed button writes space-separated, and elsewhere in SasView we write comma-separated, CanSAS1D and NXcanSAS. We should be consistent.

The default values for Resample Q Values are the min/max of the original data, not the min/max of the extrapolations and over which we transform (I presume?).

It is possible to enter a Lowest Q of 0.00. Is this sensible?

The input fields for all three boxes are fixed at 2 d.p. Is there a reason for this? It means the actual Qmin of the data (0.007) is rounded up to 0.01. This also becomes an issue for the Delta Q values: the input data is binned at 0.002 but this cannot be replicated in the dialog.

**Comment by lucas-wilkins** [comment]
All done
