### ISSUE TITLE
Global variable for q slicer may lead to circular imports

### ISSUE THREAD

**Issue by dehoni** [SasView/sasview#1972]
Paul Kienzle remarked to the use of global variable here
https://github.com/SasView/sasview/blob/d3c75fe3958ad0a22b7f20ee9838e663d99696cf/src/sas/qtgui/MainWindow/GuiManager.py#L63-L64
and 
https://github.com/SasView/sasview/blob/d3c75fe3958ad0a22b7f20ee9838e663d99696cf/src/sas/qtgui/Plotting/QRangeSlider.py#L145-L147

Global variables are contraindicated, especially in this case where they lead to circular imports.
One must be able to find the graph associated with the model (otherwise you wouldn't be able to update the theory plot when parameters change in the fitting perspective). Can you use this mechanism to find the plot associated with the perspective that needs a Q range? Then you can call the Q range selector on the specific plot with a callback to adjust low/high values when the interactors are moved. In particular, the Q range slider code won't need to rummage through the perspective tabs to find the associated perspective and it won't need to know anything about the structure of the perspective to set up the associated getter/setter/input. It should also work well with a linear fit tool, which wants to use the data for selecting the range but not the associated perspective.

**Comment by butlerpd** [comment]
As this was introduced 4 months ago and merged from PR #1891, if it is a bug it is a new one since 5.0.4 and thus appropriate to consider for 5.0.5

**Comment by krzywon** [comment]
Fixed in #1984
