### ISSUE TITLE
Plotting issue with fitting when using github action builds

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#1982]
Github Action builds use different versions of packages from the Jenkins servers.  For example python 3.8 vs 3.6 and most likely at issue here matplotlib 3 vs 2. Testing PR #1884 the difference in builds (from the exact same code base) is stark: Jenkins builds are rock solid while the Github Actions I would say is completely unusable.

At heart the new behavior seems to originate from a clearing (deleting) of the fitpage plot whenever something changes (or may change): changing the value of a parameter and hitting return, clicking `Compute/Plot` or clicking `Fit`. The plot window thus flashes what seems to be a default blank plot: linear scale from 0 to 1 on both axes, with no axes labels and no date or fits (basically an entirely blank plot except for the 2 axes).  This does not occur in the Jenkins build.

The real problem, is that once that resetting/Deleting path is engaged, after a change is made (as defined above .. such as a fit) and the cursor is moved over the fitting plot again, within seconds the new fit disappears and the plot is "permanently" reset to the default blank plot.  This can be fixed by clicking "reset range" or hitting "Compute/Plot" again.

Two ways I have found to circumvent that behavior (mostly) seem to be:
1. start a fit panel and choose a model then compute and show.   Once this has been done going back to a previous fit panel, or even sending data to this fit panel and changing parameters or doing a fit etc will usually no longer cause the resetting/deleting of the fit window.  This however is short lived: as soon as any range is changed (zoom in or out or changing the fitting range) the problem seems to be back.
2. If the last graph that was in focus was the residuals plot rather than the fitting plot (I did not test other plots) then no resetting occurs
3. NOTE: It is hard to reproduce exactly as none of the release builds or the latest main build will run. trying quickly on some other PR installers made with github actions exhibits the same reset/deletion of fit plots but the details of when and how to avoid them seems to vary and after quite a few hours of sleuthing I have not yet found a common behavior. 

NOTE. 
Clearly we cannot release from github actions with this issue hence marking it a blocker. Of course falling back to releasing from Jenkins would make this not a blocker for 5.0.5.

**Comment by butlerpd** [comment]
Having just tested the Release_5.0.5 Github installer (created Dec 3) pinning mpl version did *not* fix this problem which remains a serious blocker.  It looks like my dream of using this version for a tutorial will not be possible.

**Comment by butlerpd** [comment]
actually ... I think this was also resolved @krzywon but I'll have to test I guess before closing - or do you know for a fact it has not been fixed?

**Comment by krzywon** [comment]
I'm not sure. Let's both test and see

**Comment by butlerpd** [comment]
RC2 sees to be quite solid so I am going to close this as having been fixed

**Comment by smk78** [comment]
I've so far not seen the problem with 5.0.5 on Windows, however.

**Comment by wpotrzebowski** [comment]
After ~45min I've managed to reproduce this bug... In my case it only happens when I create multiple fit pages and then remove one and then fit on the some with higher number than removed (it is not easy to reproduce so I will work out exact sequence and provide video). I will be suprised though if this is bug related to packages/builds. It seems to me to rather programatic.
