### ISSUE TITLE
Version tagging for dependencies in release builds

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#1986]
Looking at the [installers](https://github.com/SasView/sasview/blob/main/.github/workflows/installers.yml) and [release](https://github.com/SasView/sasview/blob/main/.github/workflows/release.yml) workflows, it appears that  SasView is not using any version tagging on third-party dependencies. This will make reproducible builds impossible since it is pulling the latest versions of all packages.

_Originally posted by @pkienzle in https://github.com/SasView/sasview/issues/1973#issuecomment-985758590_

**Comment by lucas-wilkins** [comment]
This seems to be superseded by many of the recent discussions on requriements.txt etc

**Comment by butlerpd** [comment]
Partly. I think the "informal" agreement from Tuesday meetings is that the release.txt should fix version numbers though not clear which packages or all (which would be a real chore).  A discussion with an eventual final decision should probably be had with said final decision documented?

The other part of this is the work done by @Caddy-Jones to add a button in the help menu that prints out a list (a json file actually) of each package and its version number being used.  That code is in 5.0.5 (and main) but the menu button removed as it was still glitchy when he had to move on.

**Comment by lucas-wilkins** [comment]
I'm closing this because I've made a more emphatic plea for it in #2177.
