### ISSUE TITLE
5.0.5rc1: KeyError saving Easy Add/Multiply Plugin

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1996]
5.0.5rc1 on W10/x64

Creating a simple plugin throws this error:
![image](https://user-images.githubusercontent.com/10938679/148691342-02e16cc5-79de-483f-a937-b4d2901d0e27.png)
However, the plugin _is_ created and can be loaded.

But this error does not appear in 5.0.4:
![image](https://user-images.githubusercontent.com/10938679/148691506-54f33cb4-df6b-471a-a684-ffe8392fc932.png)

**Comment by butlerpd** [comment]
again this was not closed by the PR merge for some reason so closing manually
