### ISSUE TITLE
5.x: Changing parameter in FitPage does not update plot when fitting SESANS data

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#1998]
5.0.4 on OSX Big Sur 11.6.2 & 5.0.5rc1 on W10/x64

Reported by User GregS. Verified by @smk78.

When fitting SESANS data, manually changing parameters in the Fit Page does _not_ update the plot as it does when fitting normal SAS data. The plot _does_ update when the SESANS data are fitted however.

Before:
<img width="1792" alt="Screenshot 2021-12-09 at 12 06 24" src="https://user-images.githubusercontent.com/10938679/149182507-466581e5-d31f-4d92-8b10-abb38b0803eb.png">

After changing radius and hitting <return>:
<img width="1792" alt="Screenshot 2021-12-09 at 12 06 32" src="https://user-images.githubusercontent.com/10938679/149182627-d3a73a24-97d3-4d3d-9cb5-7addb423ff9b.png">

**Comment by krzywon** [comment]
This seems related to #1836. As an aside, no updates when changing parameters will become the norm as of 5.0.5 due to the changes made in #1798 which removes the recalculation when modifying a parameter. The `ENTER` key press not triggering an update will still need to be fixed.

**Comment by smk78** [comment]
So I think this issue can be closed once the `ENTER` key sub-issue mentioned in #1798 is sorted?

**Comment by caitwolf** [comment]
> So I think this issue can be closed once the `ENTER` key sub-issue mentioned in #1798 is sorted?

@smk78 It appears that the tasks in #1798 were accomplished, although @krzywon or @butlerpd might be able to confirm this or if the `ENTER` key issue is still being worked out? Either way, the behavior of the `ENTER` key and the `Compute/Plot` buttons differ between normal SAS data and SESANS data and so the fixes from #1798 seemed to have only applied to SAS data.

After an initial fit of the SESANS data, neither the `ENTER` key nor the `Compute/Plot` button can be used to recalculate and update the plot when any of the parameters are changed. This is possible with normal SAS data should one need to modify parameters and/or the fit after the initial fit. I'm currently looking into why this behavior didn't seem to translate to the SESANS data but wanted to note that closing #1798 may not completely solve the present issue.
