### ISSUE TITLE
Issue in using constrained fitting

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#2004]
In testing Release Candidate 5.0.5RC1, user Greg Smith reports a logical issue in behavior when selecting "add all constraints."  It appears this not only sets every single parameter that is the same to be constrained to be the same, but selects them for fitting in the relevant Fitpage even when they were not selected by the user.  report follows:

> I tried fitting some slit smeared data loaded as NXcanSAS files. Kudos to you for fixing the importing of these on https://github.com/SasView/sasview/issues/1879! When fitting the added files, I wanted to check their simultaneous fit (two measurements of the same thing). On the constrained/simultaneous fit page, I selected to “add all” constraints, and it selected parameters, even those I hadn’t selected to fit. I can untick them, but I had expected only the parameters I originally wanted to be fit would be selected. If I then fit from the simultaneous window, it does not select the SLDs for one but does for the other. 

In a followup report

> My anticipated workflow was:
Load files for simultaneous fitting, select parameters that I wanted to fit.
Go to simultaneous/constrained fitting tab, add constraints. Select “add all” constraints to save time. Untick the ones that I didn’t to constrain, as these were fixed and not being fit.
Fit data, which would vary only the parameters that I had previously ticked. Those that were constrained would be constrained, those that were not constrained would vary independently on their FitPage.
<img width="1748" alt="contrainedFitPage" src="https://user-images.githubusercontent.com/10955478/149939254-f93fc52a-f507-467b-90cd-67e6056f954a.png">
<img width="1792" alt="FitPage1" src="https://user-images.githubusercontent.com/10955478/149939270-ca482e40-189c-43bd-a553-f47c7b257081.png">
<img width="1792" alt="FitPage2" src="https://user-images.githubusercontent.com/10955478/149939294-2bd54480-0c09-475f-92cd-ee934284a311.png">

**Comment by smk78** [comment]
In another follow up email Greg writes:
>See attached the *.json files for my two attempts at this, saved at the point after I had run the simultaneous fit, so you can see the behaviour I was describing.
[project_files_from_505rc1.zip](https://github.com/SasView/sasview/files/7890605/project_files_from_505rc1.zip)

>What seems to be happening is that the clicking the “add all” button selects all parameters to be fit on the subordinate data set (for instance, M1 if M1=M2). That may be logical for the algorithm but wasn’t what I was expecting.

**Comment by smk78** [comment]
And when asked if the 5.0.4 release did the same thing, Greg reports:
>I just checked, and yes, 5.0.4 does the same as I described. If you select “add all”, then all the parameters in the subordinate (M1, when M1=M2) set are selected.

>The fit in v5.0.4 is different and better than in 5.0.5rc. I have attached the project file from 5.0.4 for the D22 data. I could see how it fit (from when the plots changed), and the fit routine updated FitPage2 first and then FitPage1. FitPage1 is the subordinate data set.
[project_file_from_504.zip](https://github.com/SasView/sasview/files/7890645/project_file_from_504.zip)

>The behaviour is the same for the USAXS data as well, but v5.0.4. was before the fix to import smearing from NXcanSAS, and this made importing the slit smearing a bit more tricky… If you need it, I can do it, but I figured the attached project showed the behaviour well enough.

**Comment by wpotrzebowski** [comment]
I've found possibly related issue. The constraint setup dialog shows truncated name of model ("M") and doesn't allow to select all parameters (it depends on what has been set in the single page fit).
<img width="495" alt="Screenshot 2022-10-29 at 12 21 01" src="https://user-images.githubusercontent.com/4189922/198826256-1e0b27bd-e026-4afd-87de-58d51c6ee1f3.png">

**Comment by wpotrzebowski** [comment]
The limitted selection of parameters is fine (I didn't quite understand logic at the begining...), howver truncated names and "All" is still the bug.

**Comment by wpotrzebowski** [comment]
The issue with truncated name seems to be related to PyQt=5.13. It disappears with 5.15, which is available and installers can be adapted to build against.

**Comment by gonzalezma** [comment]
Agree that behaviour is not intuitive. I re-reported this in issue #2356, which reports also another issue with the Add All button related to the polydisperse parameters (not available until now). I'll try to fix both problems.

**Comment by lucas-wilkins** [comment]
@gonzalezma Did your change fix this, should this be closed?

**Comment by gonzalezma** [comment]
@lucas-wilkins No, this is not yet fixed. "Add all constraints" modifies the status of all the parameters in the corresponding FitPage to "fittable", which I agree with the user report that it is not intuitive. I did not come back to work on SasView since the code camp, so this is still pending. I should be able to work back on that in June, once the summer students are here, unless you want to look to the issue before.

**Comment by gonzalezma** [comment]
Fixed now by PR #2728
