### ISSUE TITLE
Issues not always closing when pull request is merged

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#2007]
As has been discussed on several calls, linking issues to PR will often close the issue when the PR is merged but not always.  We have not yet figured out the pattern to reproduce this effect. It is however causing some problems with many fixed issues remaining open and cluttering up the list of issues.  A solution would be very useful.

Note that @krzywon found the following article on the GitHub blog
https://github.blog/2013-05-14-closing-issues-via-pull-requests/

This however is almost 10 years old and seems like it has probably been superseded with the "linked pull requests" option now on the GUI?

**Comment by butlerpd** [comment]
I thought I'd updated this ticket.. but maybe it was another? or maybe it was just a conversation where I said I would and then decided I had 😄

As pointed out in the docs linked to by @pkienzle, the problem is that this **only** works when the pull request in question is against the "default" branch (currently main for sasview and master for sasmodels). Doing so manually with the above keywords or through the GUI shouldn't matter. if it is merged instead into another branch  ... such as a release branch, linked issues will **not** be closed and the link will in fact be ignored! From what I can tell this is also true of the commit message approach.  However if the `closes` or `resolves` etc keyword is used in the commit message, it should in fact close the issue once that commit is finally merged into the default branch (as it should eventually be) - see for example this very github old blog post which I think is still valid: https://github.blog/2013-01-22-closing-issues-via-commit-messages/. It is not clear that happens when linking to a PR.

**Comment by lucas-wilkins** [comment]
Bug exists between between keyboard and chair.
