### ISSUE TITLE
iPython Console unable to import from bumps.names (and thereby execute example scripts)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#2026]
_Created from a thread on the Deveopers list_
User RobD notes:

>I’m running 5.0.4 on windows 10.
>I’ve been trying to follow the bumps scripted running example.
 >
>https://www.sasview.org/docs/user/qtgui/Perspectives/Fitting/scripting.html
> 
>A couple of things…
>Using the SasView IPython shell this line fails
``` 
from bumps.names import *
``` 
>Having reread the scripting page it there are comments about appending things to the python path but it’s not clear if this is something that needs to be added on top of the default windows install.
>It almost reads like you are expected to have installed from source.
>Some hints would be good.

I've verified this on another PC without a source installation of SasView. Whilst
```
import bumps
```
completes successfully
```
from bumps.names import *
```
returns
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-5-01641ee2af2e> in <module>
----> 1 from bumps.names import *

ModuleNotFoundError: No module named 'bumps.names'
```

@wpotrzebowski responded:
>Sorry to hear you’ve run into this issue. 
>We are aware of the issues with running from Python Shell. The current workaround is indeed to install sasview from source.
>If you have pip and git installed ((e.g. through anaconda). It should be enough to run commands from the notebook: https://github.com/wpotrzebowski/sasview_scripting/blob/master/Installer.ipynb.
>And then you should be able to run sasmodels with bumps as shown here https://github.com/wpotrzebowski/sasview_scripting/blob/master/sasmodels_fitting.ipynb. 
>I know this is far from user friendly instructions but hope they are helpful. If you run into problems let me know.

**Comment by smk78** [comment]
I also note the opening sentence in https://www.sasview.org/docs/user/qtgui/Perspectives/Fitting/scripting.html should be removed or commented out.

**Comment by rozyczko** [comment]
Seems to be importing fine in 5.0.5 rc , at least on Windows?

![Untitled](https://user-images.githubusercontent.com/8266281/155965459-c5e911c8-7098-4eb5-91c5-a3d1c8678c70.png)

**Comment by smk78** [comment]
Just installed 5.0.5rc2 on the same machine I did the check with 5.0.4 above. @rozyczko is correct: the import works in 5.0.5.
