### ISSUE TITLE
ReportDialog: replace xhtml2pdf with WeasyPrint.

### ISSUE THREAD

**Issue by drew-parsons** [SasView/sasview#2034]
qtgui/Utilities/ReportDialog.py uses xhtml2pdf to generate reports in pdf format.

xhtml2pdf is deprecated (no longer supported) and has operational problems, most egregiously it fails to handle non-latin1 characters, see https://github.com/xhtml2pdf/xhtml2pdf/issues/11 . This places a bad restriction on the usability of sasview reports.

The xhtml2pdf [documentation](https://github.com/xhtml2pdf/xhtml2pdf/blob/master/README.rst) itself says to use [WeasyPrint](http://weasyprint.org/) instead.

**Comment by butlerpd** [comment]
@drew-parsons, just to clarify - By "deprecated" do you mean that xhtml2pdf is no longer going to be packaged in future Debian releases?  Or that you have inside knowledge that the developer community has abandoned it (granted it seems quite small at the moment).

I note that the latest release was only 17 days ago (March 31, 2022) with no evidence on github or PyPi that the project is no longer supported?

**Comment by drew-parsons** [comment]
My comment was based mainly on the comment that one of the xhtml2pdf upstream contributors themselves made, "xhtml2pdf is a very stale project",  then going on to say "if you are doing something new, start off with WeasyPrint instead as suggested in the README". https://github.com/xhtml2pdf/xhtml2pdf/issues/11#issuecomment-442834709

Apart from that, https://github.com/xhtml2pdf/xhtml2pdf/issues/11 was filed in 2011, eleven years ago and still not fixed.  Why would you use a library that fails to render in chinese, or arabic, or, thai ? (it will fail unless you explicitly hack the font used). Especially when there is an alternative recommended by xhtml2pdf authors which does not have that same problem.

As for Debian support, the new version of xhtml2pdf switched to PyPDF3, which is not ([yet](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=935175)) packaged for Debian.

**Comment by lucas-wilkins** [comment]
Weasyprint looks good. Its pretty big (I guess it needs to be to actually work well) and took a couple of minutes to download using anaconda.

**Comment by lucas-wilkins** [comment]
Hmmm, the default install on anaconda is broken too. I'm going to look for a more minimal option.

**Comment by lucas-wilkins** [comment]
pdfkit requires an external application

**Comment by lucas-wilkins** [comment]
however, xhtml2pdf does not support svg images.

**Comment by lucas-wilkins** [comment]
After playing with this a bit, I think xhtml2pdf is fine, will re-open if it becomes an issue.

**Comment by jergus48** [comment]
> After playing with this a bit, I think xhtml2pdf is fine, will re-open if it becomes an issue.

Hi I have really big problems with slavic characters when using xhtml2pdf. I think I tried everything and nothing worked. Could you please help me lol?
