### ISSUE TITLE
Unable to select LM (scipy:leastsq) optimizer despite it is default optimizer

### ISSUE THREAD

**Issue by wpotrzebowski** [SasView/sasview#2036]
I am not able to select LM (scipy:leastsq) optimizer from Fit Algorithm menu:

<img width="736" alt="Screenshot 2022-04-26 at 08 14 30" src="https://user-images.githubusercontent.com/4189922/165234060-9d7530c3-e8fd-47c1-b4b4-b6d484e1eacd.png">

even tough it is default optimizer

**Comment by wpotrzebowski** [comment]
I observed this on Mac but I guess it may be the same issue on other platforms too.

**Comment by rozyczko** [comment]
This requires adding a new page for `scipy.leastsq` minimizer (Perspectives/UI/FittingOptions.ui) identical to that for `page_lm`.
Also, the name will have to be internally changed to `scipy_leastsq` so the widget can be properly called.

**Comment by wpotrzebowski** [comment]
This issue came out after merging bumps=0.9.0 and it is not vissible in 5.0.5rc2 (which uses standard LM).

**Comment by smk78** [comment]
> I observed this on Mac but I guess it may be the same issue on other platforms too.

Yes, same on Windows.

**Comment by krzywon** [comment]
Places that need changing for the default to show up properly on the fitting perspective:

> sas.sascalc.fit.BumbsFitting.py, line 17 -> change `fitters.LevenbergMarquardtFit.id` to `fitters.MPFit.id`
> sas.qtgui.Perspectives.Fitting.FittingPerspective.py, line 80 -> change `fitters.LevenbergMarquardtFit.id` to `fitters.MPFit.id`

**Comment by butlerpd** [comment]
fixed by merging of #2037
