### ISSUE TITLE
Font scaling becomes irregular when using multiple screens on windows

### ISSUE THREAD

**Issue by lucas-wilkins** [SasView/sasview#2043]
When using multiple monitors the GUI gets confused about font size, and the dialogs become unreadable.

![image](https://user-images.githubusercontent.com/9784906/167890267-b2344f88-66cf-4c71-a485-cdd9a5c4dca7.png)

Its currently unclear to me what extent this is a general Qt issue, and how much is specific to SasView.

V5.0.4, Tested on windows 10 enterprise.

**Comment by butlerpd** [comment]
This has been noted for OSX but not for windows before. Wonder if it is related?

**Comment by lucas-wilkins** [comment]
I've just had the same issue with Qt designer. I take it that this means that it's a general Qt problem, and therefore something that is not something that we'll fix within sasview.

Close as wont fix
