### ISSUE TITLE
Conda yml outdated 

### ISSUE THREAD

**Issue by lucas-wilkins** [SasView/sasview#2046]
None of the relevant conda .yml files is correct for an install onto a clean windows python install.

In my local install I have modified `conda_qt5_win_commercial.yml` to reference standard `PyQt5` and added reportlab 3.4 manually (note SasView makes references to functions that are no longer supported in the newest versions).

`conda_qt5_win.yml` and `conda_py3_qt5_env.yml` both have a significant quantity of reported dependency conflicts.

We should be looking into an automatic test system for this (see also #1869)

**Comment by lucas-wilkins** [comment]
Perhaps this is not how people are setting things up now? 

The corresponding docs need updating too.

**Comment by rozyczko** [comment]
Indeed `conda..yml` files seem to have fallen out of sync. They were used when building on Jenkins but since moving to GitHub we neglected updating them.
Since these files are probably the most convenient way of creating local dev environment, we
 should probably keep them up to date.

**Comment by butlerpd** [comment]
I will add that this has been the source of many problems (forgetting to update requirements in all the files) and discussions over the years.  In fact we have had some fairly recent discussions as I recall at the fortnightly meeting about the fact that it would be really useful to ensure that we have everything in one place instead of the dozen (or so it seems between the requirements.txt, all the flavors of conda.yml and all the flavors of github action ymls) we currently have. Given our resources, keeping all of them up to date is not sustainable.

Just for historical context I note #811 and #457 (found by @krzywon of course 😄 mention this problem. Note that the actual issue date is much older than the github issue date since that latter is the date of the transfer from Trac to github issues.

It is not clear what the answer is but clearly maintaining all of them is not sustainable, nor is "disciplined and professional" to carry around a bunch of such files that are actually wrong. A solution to this perennial problem would be really great IMO!

**Comment by butlerpd** [comment]
Interestingly, I just found these notes from the May 10, 2022 fortnightly meeting

> Developers environment set up instructions:
> * Conda yml files are obsolete
> * Should we move completely to pip installable packages?
>   * requirements.txt file… 
>   * Conda repository license is becoming an issue
> 
Sadly I cannot remember the details of the discussion or what conclusions were reached if any.

**Comment by rozyczko** [comment]
Going pip only would probably make sense, as it can also be done on a standalone python installation and in a virtenv, like conda.
Conda license only applies to the main channel - we are using conda-forge so no limitations so far.
Obviously it is cleaner to use a separate environment but conda update and dependency checks are very slow - some groups here moved over to [mamba ](https://github.com/mamba-org/mamba)- a much faster package manager which can pull from e.g. conda-forge. Maybe we can look at it closer?

**Comment by wpotrzebowski** [comment]
@butlerpd I don't think we reach any conclussion other than something that needs to be addressed and ideally before SasView camp in June. 
I am running conda enviroment with pip installed dependencies. Maybe not most obvious way but seems to work fine with other conda installed envs.

**Comment by smk78** [comment]
Adding a new conda environment today (in the hope it would pull in newer versions of dependencies and thus alleviate a build oddity I encountered with one of @lucas-wilkins branches) by following the instructions in https://github.com/SasView/sasview/wiki/DevNotes_CondaDevEnviroment I note that pip install -r build_tools/requirements.txt falls over in my W10 console window:
```
dev) D:\SasViewCodeDev\sasview-main>pip install -r build_tools/requirements.txt
Ignoring matplotlib: markers 'sys_platform == "windows" or sys_platform == "linux"' don't match your environment
Ignoring PyQt5: markers 'sys_platform == "windows" or sys_platform == "linux"' don't match your environment
Ignoring PyQt5: markers 'sys_platform == "darwin"' don't match your environment
Ignoring matplotlib: markers 'sys_platform == "darwin"' don't match your environment
```
When I then attempted to manually pip install matplotlib==2.2.5 to satisfy the line in the requirements.txt that says:
```
matplotlib==2.2.5; sys_platform == 'windows' or  sys_platform == 'linux'
```
I got:
```
ERROR: No matching distribution found for matplotlib==2.2.5
```

**Comment by wpotrzebowski** [comment]
@smk78 indeed, we figured out last week that conditionals don't work and I updated `requirements.txt` file, so it installs same packages for all platforms (seems to be working). You need to pull the latest changes to the branch and re-run `pip install ...`.

**Comment by smk78** [comment]
> @smk78 indeed, we figured out last week that conditionals don't work and I updated `requirements.txt` file, so it installs same packages for all platforms (seems to be working). You need to pull the latest changes to the branch and re-run `pip install ...`.

@wpotrzebowski , so which branch has the requirements.txt I am supposed to be using? @lucas-wilkins has pulled main into his branch, but that requirements file is the same as the one I ran yesterday (except that dominate is now added). My problem is that the requirements files I'm looking at all specify an MPL which is not installable...
```
ERROR: No matching distribution found for matplotlib==2.2.5
```

**Comment by butlerpd** [comment]
I'm thinking it is the one in the env_setup branch used to help create a
new environment and tested at the "SasView Camp" ?

**Comment by smk78** [comment]
Thanks @butlerpd . I've just created a dev environment with that requirements file (though I've added dominate to it) and all went fine. And more importantly it fixes the problem I had building @lucas-wilkins 1992 branch!

**Comment by lucas-wilkins** [comment]
This has been resolved.
