### ISSUE TITLE
User feedback for negative intensity after background subtraction

### ISSUE THREAD

**Issue by lucas-wilkins** [SasView/sasview#2105]
Migrated from #1502 

1) in 4.x the experimental data are plotted minus the background value which makes it easier to spot when Iobs - Bg < 0. If that can't be replicated in 5.x without perturbing a lot of the underlying calculation, it would at least be helpful to display a line corresponding to the background.

2) Error/warning/other indication that there are negative values

**Comment by smk78** [comment]
Screenshot from 4.2.2
![image](https://user-images.githubusercontent.com/10938679/175566906-9486c8d8-b2e8-4bee-88d0-e252dbdafa76.png)
The plot background reaches ~0 at high Q as teh background has been subtracted. But the estimated background is also flagged as producing negative intensities after background subtraction.
