### ISSUE TITLE
Allow longer real space output (for USANS/SAX)

### ISSUE THREAD

**Issue by lucas-wilkins** [SasView/sasview#2112]
Migrated from #1502

user YoungjuK wanted to compute the transforms out to 20000 Ang, at present this is hard-coded to 1000 Ang (in part for historical reasons, in part to dissuade USAS users from trying to use the analysis without first Lorentz-correcting); we should make this limit adjustable. NB: that will likely also require some adjustment of the integration step size.

@smk78 will provide some USANS test data sets soon

**Comment by smk78** [comment]
Here's some fake long length scale data...

![image](https://user-images.githubusercontent.com/10938679/175577218-8371a803-51bc-400a-862d-a793cc953d15.png)
![image](https://user-images.githubusercontent.com/10938679/175577274-fba8c459-26d6-4edf-8c9f-f91392d1aa63.png)
[fake_long_period.txt](https://github.com/SasView/sasview/files/8977655/fake_long_period.txt)

Corfunc does something with it, but the perspective also has a few issues with it...

**Comment by smk78** [comment]
Discussed this request with @lucas-wilkins yesterday. There are methodological and computational problems with extending the range over which the correlation function is computed to smaller Q (larger z). If we persist in using an FFT for the transform then the requirement for equally-spaced data over 4 or more decades in Q means the number of points is dominated by the low-Q step size which must, of necessity, be small meaning you have to process maybe >10^6 points and everything becomes very slow. If we switch to implementing a true FT then we need to be able to accurately integrate under the extrapolated dataset at which point the form of the high-Q extrapolation becomes crucial, as does the nature of the background removal (currently assumed to be Q-independent). Whichever route is chosen, some development would be needed. Given we do not have a swathe of Users demanding this extended capability we are minded to park this issue for now.

@lucas-wilkins is that a reasonable summary? And can you confirm the current range the program allows, please?

**Comment by lucas-wilkins** [comment]
There's currently no absolute limit on the range, it is selected based on the input data
