### ISSUE TITLE
Comparative polydispersity measure

### ISSUE THREAD

**Issue by lucas-wilkins** [SasView/sasview#2113]
Migrated from #1502

> Output a comparative measure of the Polydispersity calculated from the Local Crystallinity, v, via Eqn 8.68 in the Stribeck reference in the Correlation Function help docs/tutorial notes: GammaMin = - v / (1 - v)

This should be another calculated parameter.

**Comment by smk78** [comment]
Corfunc references are at https://www.sasview.org/docs/user/qtgui/Perspectives/Corfunc/fdr-pdfs.html#fdr

SasView Corfunc documentation is at https://www.sasview.org/docs/user/qtgui/Perspectives/Corfunc/corfunc_help.html

The 1994 ref explains that the current polydispersity parameter is calculated according to a 'suggestion' by a knowledgeable User: PD = Gamma_min/Gamma_max. However Stribeck suggests an alternative calculation based on the local crystallinity v, which is in turn computed from the Lc & Lp values.
