### ISSUE TITLE
UI compiler not found

### ISSUE THREAD

**Issue by lucas-wilkins** [SasView/sasview#2126]
**Describe the bug**

The packages PyQt5.uic.pyuic doesn't appear to exist with the current requirements.txt. Note that this did work before - it's probably a missing package or something path related. Looking through my Qt installation, the file does not appear to be there.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a new conda environment, python 3.8.13
2. pip install -r requirements.txt
3. Try and run

**Expected behavior**
Finds package

**SasView version (please complete the following information):**
Current main branch

**Operating system (please complete the following information):**
 Windows 10

**Additional context**

The problematic imports are from the recent #2117 PR

**Comment by rozyczko** [comment]
Seems that the requirements file needs to have this added: `pip install pyqt5-tools`

**Comment by lucas-wilkins** [comment]
Seems it was the missing its also missing bumps, html2text, and the conditional stuff didn't work

**Comment by butlerpd** [comment]
Hummm... I thought we worked on fine tuning that at the Lund workshop?  How did this get missed? or were the changes made in a branch that was not merged. @wpotrzebowski would be the one to ask I guess?

**Comment by wpotrzebowski** [comment]
Somehow older version of requirements file got merged to main... What we did in Lund at the end is here https://github.com/SasView/sasview/blob/env_setup/build_tools/requirements.txt. Please note that platform specific conditionals didn't work so they were removed but it seemed to work on both Mac and Windows.
