### ISSUE TITLE
Change file format for Save Transformed in Corfunc

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#2137]
In Corfunc, 'Save Extrapolated' currently writes a 2-column CSV file whilst 'Save Transformed' writes a 4-column space-delimited file with a Corfunc-specific extension: there should be some consistency!

**Describe the solution you'd like**
I would suggest we standardise on CSV for both for now.

**Additional context**
Ideally, of course, we should also offer the transformed data as CanSAS1D and NXcanSAS with separate SASdata blocks for the 1D, 3D & IDF. But this is less urgent.

**Comment by lucas-wilkins** [comment]
> Ideally, of course, we should also offer the transformed data as CanSAS1D and NXcanSAS with separate SASdata blocks for the 1D, 3D & IDF. But this is less urgent.

This sounds like an additional feature request within a feature request, a matryoshka request if you will. Can you make a separate request for that.
