### ISSUE TITLE
A more maintainable setup.py

### ISSUE THREAD

**Issue by lucas-wilkins** [SasView/sasview#2140]
After forgetting to add a new directory I created to setup.py, and looking at the issues it has if package names are not properly entered, I wonder if would it make more sense to just recursively search the source tree and add everything automatically, rather than having to explicitly maintain a list of the packages we want to include?

Is this something that should be done? Perhaps there a reason why it is currently done the way it is.

**Comment by krzywon** [comment]
In the same regard, we should talk about bundling our workflow ymls so we don't miss dependencies. The html2text dependency (adding it to #2139 shortly) is currently only in the release yml.

**Comment by krzywon** [comment]
To add to my previous comment, most of the workflow steps overlap each other. We should be able to combine installers, test, and docs into a single workflow.

**Comment by lucas-wilkins** [comment]
> The html2text dependency (adding it to https://github.com/SasView/sasview/pull/2139 shortly) is currently only in the release yml.

I thought we decided to only maintain release.yml  - am I wrong about this? - anyway, I think this highlights the issue quite well.

**Comment by krzywon** [comment]
> I thought we decided to only maintain release.yml - am I wrong about this? - anyway, I think this highlights the issue quite well.

I don't know, TBH. What I do know is installers.yml is what generates the test executables for branches and PRs. release.yml is what is used to generate the executables attached to releases. Releases typically use a pinned version of sasmodels, and often for bumps as well, instead of master branches.

**Comment by lucas-wilkins** [comment]
> I don't know, TBH. What I do know is installers.yml is what generates the test executables for branches and PRs. 

o_O 

> release.yml is what is used to generate the executables attached to releases. Releases typically use a pinned version of sasmodels, and often for bumps as well, instead of master branches.

Yeah

**Comment by lucas-wilkins** [comment]
This has been done via #2419
