### ISSUE TITLE
Update installer_generator

### ISSUE THREAD

**Issue by lucas-wilkins** [SasView/sasview#2151]
installer_generator needs some TLC, also delete installer_generator64 as unused.

**Comment by krzywon** [comment]
This is an extension of #1636. Maybe close the older ticket?

**Comment by lucas-wilkins** [comment]
Ah, OK

**Comment by lucas-wilkins** [comment]
Also, add the .iss to .gitignore and remove from repo

**Comment by lucas-wilkins** [comment]
Blocked by #2164

**Comment by lucas-wilkins** [comment]
It's hard to sort out the installer generator when the config files are in a mess

**Comment by lucas-wilkins** [comment]
I've rolled this into #2168
