### ISSUE TITLE
Clean up sas.sasview VII: Offspring

### ISSUE THREAD

**Issue by lucas-wilkins** [SasView/sasview#2160]
The `conda` subdirectory in `build_tools` is outdated. as are most of the conda_* files. Remove.

**Comment by lucas-wilkins** [comment]
@wpotrzebowski @butlerpd etc Are we supporting conda at all now?

**Comment by rozyczko** [comment]
We did use conda and relied on it when building on Jenkins. On GH we seem to only use `pip` and all dependencies come from pypi rather than `conda-forge`. We lost some package management/analysis with conda, but since pip is so much quicker, maybe let's get rid of conda entirely?

**Comment by wpotrzebowski** [comment]
Currently, entire conda package development is done by @mrakitin/NSLS-II (https://github.com/conda-forge/sasview-feedstock). As mentioned by @rozyczko conda folders in the sasvie repo are obsolete and can be removed.
