### ISSUE TITLE
GUITests failing

### ISSUE THREAD

**Issue by lucas-wilkins** [SasView/sasview#2162]
**Describe the bug**
Many of the Qt GUI tests fail, this makes executing #2157 difficult

**To Reproduce**
1. Run GUITests.py

**Expected behavior**
Not failing tests

**Comment by krzywon** [comment]
Duplicate of #1732?

**Comment by lucas-wilkins** [comment]
@krzywon cool. I searched for an existing issue and didn't see it. Close as duplicate of #1732
