### ISSUE TITLE
Create Centralized Preferences Window

### ISSUE THREAD

**Issue by krzywon** [SasView/sasview#2166]
**Is your feature request related to a problem? Please describe.**
Many options and defaults are changed and set in different places throughout SasView.

**Describe the solution you'd like**
There should be a single, cohesive window that handles all preferences and options. This panel should tie into the config file(s) to set defaults as needed.

**Additional context**
This is related to #258, #268, and #1726. There are likely more issues that I wasn't able to find in a 2-minute search.

**Comment by butlerpd** [comment]
maybe #2164 just created by @lucas-wilkins? I was actually going to comment that originally that was part of what `local_config` was supposed to do (a looooong time ago - back in the times of middle earth I believe)

**Comment by krzywon** [comment]
> maybe #2164 just created by @lucas-wilkins? I was actually going to comment that originally that was part of what `local_config` was supposed to do (a looooong time ago - back in the times of middle earth I believe)

He and I have been in contact about this. We plan to combine his config work with my panel work once both are ready. For now, I've created a draft PR so people can look at the panel and how it works.
