### ISSUE TITLE
Compatibility with newer matplotlib (3.5.x)

### ISSUE THREAD

**Issue by llimeht** [SasView/sasview#2170]
**Describe the bug**
SasView is not compatible with currently supported versions of matplotlib such as the current 3.5.4 release. One symptom of this is seen in #1981 where the GUI closes during initialisation. There are others. Some of these might be picked up by `GUITests.py` but as they don't pass (#1732) their failures on CI don't help spot these issues in advance.

**To Reproduce**
1. Install matplotlib ≥ 3.5 and sasview from source (version 5.0.5 or current git main)
2. Start SasView
3. It crashes

SasView's attempts to handle the exceptions obfuscate where it is from:
```
14:06:41 - ERROR: Application failed with: 'Arrow3D' object has no attribute 'do_3d_projection'
14:06:41 - ERROR: Traceback (most recent call last):
  File "/usr/bin/sasview", line 33, in <module>
    sys.exit(load_entry_point('sasview==5.0.5', 'console_scripts', 'sasview')())
  File "/usr/lib/python3/dist-packages/sas/qtgui/MainWindow/MainWindow.py", line 119, in run_sasview
    mainwindow.guiManager.showWelcomeMessage()
AttributeError: 'MainSasViewWindow' object has no attribute 'guiManager'
```
While the error looks to be in `MainWindow.py` the issue is actually that `sas/qtgui/Plotting/Arrow3D.py` needs to be updated to the new 3.5 API.

Poking matplotlib compatibility further, `sas/qtgui/Plotting/Plotter2D.py` also seems to need an update for the matplotlib API as `colorbar.update_bruteforce` [has now been removed](https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.5.0.html) (and had been deprecated for some years). 

**SasView version (please complete the following information):**
 - Version: 5.0.5; relevant files are the same in git main.

**Operating system (please complete the following information):**
 - OS: above tests done on Linux, but also an issue on Windows as seen in #1981.

**Additional context**

The following patch at least allows sasview to run with mpl 3.5.4. I can't attest to the correctness of what it is doing to the Arrow3D class beyond (a) it let the main GUI actually render, and (b) the general scattering calculator, which is where this class is used, still displayed some arrows on the plots.
```
diff --git a/src/sas/qtgui/Plotting/Arrow3D.py b/src/sas/qtgui/Plotting/Arrow3D.py
index 2c58bc2..2adf919 100644
--- a/src/sas/qtgui/Plotting/Arrow3D.py
+++ b/src/sas/qtgui/Plotting/Arrow3D.py
@@ -2,6 +2,7 @@
 Module that draws multiple arrows in 3D coordinates
 """
 
+import numpy as np
 from matplotlib.patches import FancyArrowPatch
 from mpl_toolkits.mplot3d import proj3d
 import time
@@ -21,7 +22,7 @@ class Arrow3D(FancyArrowPatch):
         :Params colors: [[R0, G0, B0], [R1, G1, B1], ...]
         where R, G, B ranges (0,1)
         """
-        FancyArrowPatch.__init__(self, (0, 0), (0, 0), *args, **kwargs)
+        super().__init__(self, (0, 0), (0, 0), *args, **kwargs)
         self.leftdown = False
         self.realtime = False
         self.t_click = 0
@@ -62,7 +63,7 @@ class Arrow3D(FancyArrowPatch):
         self._verts3d = xs, ys, zs
         self.base.canvas.draw()
 
-    def draw(self, renderer, rasterized=True):
+    def do_3d_projection(self):
         """
         Drawing actually happens here
         """
@@ -70,12 +71,12 @@ class Arrow3D(FancyArrowPatch):
         if self.leftdown and not self.realtime:
             return
         xs3d, ys3d, zs3d = self._verts3d
+        zmins = []
         for i in range(len(xs3d)):
-            xs, ys, _ = proj3d.proj_transform(xs3d[i], ys3d[i], zs3d[i], renderer.M)
+            xs, ys, zs = proj3d.proj_transform(xs3d[i], ys3d[i], zs3d[i], self.axes.M)
             self.set_positions((xs[0], ys[0]), (xs[1], ys[1]))
             self.set_color(self.colors[i])
-            FancyArrowPatch.draw(self, renderer)
+            zmins.append(np.min(zs))
 
         self.leftdown = False
-
-
+        return min(zmins)
diff --git a/src/sas/qtgui/Plotting/Plotter2D.py b/src/sas/qtgui/Plotting/Plotter2D.py
index 2e82332..0de858c 100644
--- a/src/sas/qtgui/Plotting/Plotter2D.py
+++ b/src/sas/qtgui/Plotting/Plotter2D.py
@@ -539,7 +539,7 @@ class Plotter2DWidget(PlotterBase):
             else:
                 cb = self.figure.colorbar(self.im, cax=cbax)
 
-            cb.update_bruteforce(self.im)
+            cb.update_normal(self.im)
             cb.set_label('$' + self.scale + '$')
 
             self.vmin = cb.vmin
```

**Comment by lucas-wilkins** [comment]
Since SasView explicitly specifies matplotlib 3.4.3 I wouldn't consider this a bug. That said, if the changes you suggest make it 3.5 compatible it would be a good thing. There was some discussion about matplotlib versions before I joined the project, and I'm not 100% about the decisions made. Maybe post your suggested changes as a pull request?

**Comment by smk78** [comment]
Coincidentally 4 days ago I was made aware that the colour map widget on 2D plots was not working in the version of 5.0.5 on our IDAaaS system (running on CentOS). The following is reported:
```
15:28:07 - ERROR: Traceback (most recent call last):
  File "/opt/sasview5/lib/python3.10/site-packages/sas/qtgui/Plotting/Plotter2D.py", line 431, in onColorMap
    color_map_dialog = ColorMap(self, cmap=self.cmap,
  File "/opt/sasview5/lib/python3.10/site-packages/sas/qtgui/Plotting/ColorMap.py", line 48, in __init__
    self.initRangeSlider()
  File "/opt/sasview5/lib/python3.10/site-packages/sas/qtgui/Plotting/ColorMap.py", line 159, in initRangeSlider
    self.slider.setMinimum(self.vmin)
TypeError: setMinimum(self, int): argument 1 has unexpected type 'numpy.float64'
```
I suspect this may be a MPL version issue too.

Unfortunately I'm struggling to unambiguously identify which version of 5.0.5 is installed on the IDAaaS production server (and even the Support Team are now confused!), the rc2 pre-release or the 5.0.5 release. The About box just says Git Commit, but that may be a red herring?

Anyone got a bright idea?

**Comment by rozyczko** [comment]
> Anyone got a bright idea?
Not really bright but I don't think we support python 3.10 yet? At least we should try running the dev version on 3.10 and seeing how much effort it takes to port/update it.

**Comment by smk78** [comment]
Update: Ok, so IDAaaS Support are now sure that the widget traceback above was from the release version of 5.0.5 installed from conda-forge.

**Comment by butlerpd** [comment]
the git commit in the "about" should probably be removed now that we are using versioning better? It was originally meant to be followed by the commit hash but only worked I think on one OS? and maybe only way way back at the dawn of time?  As far as I know it has not worked for yonks and is thus useless -- unless somebody knows how to fix it.

**Comment by lucas-wilkins** [comment]
> Coincidentally 4 days ago...

You should be making a new issue for things that are only tangentially related to the issue at hand.

**Comment by llimeht** [comment]
@lucas-wilkins #2213 now exists; with it applied I was at least able to start sasview with mpl 3.5 which meant that I then found some Qt-related problems that are #2214.

I can't promise that's all of the problems with making sasview run with up-to-date versions of those packages, but it's a start that at least gets it as far as being testable. In the testing I did, it was now on a par with mpl 3.4.

**Comment by lucas-wilkins** [comment]
Cool, thanks, I'll take a look when I'm back at work
