### ISSUE TITLE
check_packages bonks

### ISSUE THREAD

**Issue by dsclassen** [SasView/sasview#2182]
I'm trying to install sasview into an existing conda env.

```
(ssp-2.1) [user@machine sasview]# python check_packages.py 
Traceback (most recent call last):
  File "check_packages.py", line 37, in <module>
    with open(file_location, 'r') as stream:
FileNotFoundError: [Errno 2] No such file or directory: './build_tools/conda_qt5_ubuntu.yml'
```

This machine is running Rocky Linux 8.6

Looks like ./build_tools/conda_qt5_ubuntu.yml is missing?

or maybe the check_packages script knows nothing about Rocky Linux?

**Comment by lucas-wilkins** [comment]
Hi, conda_qt5_ubuntu.yml has been removed, and it looks like check_packages.py needs to be updated or removing outright.

Packages are now managed through pip and requirements.txt, i.e. by running
```
pip install -r requirements.txt
```
