### ISSUE TITLE
Pandoc?

### ISSUE THREAD

**Issue by lucas-wilkins** [SasView/sasview#2184]
docs/pandoc-doc can be deleted, right?

**Comment by lucas-wilkins** [comment]
@wpotrzebowski @rozyczko @smk78 @butlerpd @krzywon

**Comment by smk78** [comment]
It could be deleted without consequence.
The intention, dare I say aspiration, was that slurped .fodt files (like tutorials) would get put here and then Pandoc'ed into other formats, in an analogous way to what Sphinx does with .rst, etc. But I wasn't clever enough to do the scripting and the resource that championed this approach (@ajj) no longer has the bandwidth. So the question is how to proceed. Sounds like another discussion...

**Comment by lucas-wilkins** [comment]
OK, well there's little there that can't be easily redone should it be re-attempted.
