### ISSUE TITLE
Clean __init__.py

### ISSUE THREAD

**Issue by lucas-wilkins** [SasView/sasview#2185]
There seems to be a few unused methods in sas/__init__.py. Some I have already removed for #2164, but there are still some mentioning app_dir. These should probably be removed? @wpotrzebowski @krzywon @rozyczko  @butlerpd

**Comment by lucas-wilkins** [comment]
Should be closed by #2164

**Comment by butlerpd** [comment]
Sorry @lucas-wilkins for slow response. Though I actually have no insights on this one I'm afraid so no help anyway ☹️

**Comment by lucas-wilkins** [comment]
@butlerpd no worries, I have ended up deleting nearly all of it in in #2168

**Comment by lucas-wilkins** [comment]
Basically as done as it will be any time soon.
