### ISSUE TITLE
Suppress debug info for third party packages.

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#2230]
The sasview logger setup has a blacklist of packages where level is changed to WARN. Instead we should set reasonable defaults for all third-party packages and have a whitelist of those where we want more debug information.

The problem is likely in `logging.ini:[logger_root]` which has `level=DEBUG`.

We should either leave the root logger untouched (leaving it to python and/or library defaults) or set it to a higher level (WARN or ERROR). We can then whitelist packages with level=INFO or level=DEBUG (e.g., sasview, sasdata, sasmodels, bumps, tinycc, periodictable).

**Comment by lucas-wilkins** [comment]
This didn't work out for us. See #2349.
