### ISSUE TITLE
Weird Scaling on Some Windows Installations

### ISSUE THREAD

**Issue by lucas-wilkins** [SasView/sasview#2249]
![image](https://user-images.githubusercontent.com/9784906/195374443-fafec342-e6c5-4134-88cb-f703800f8193.png)

This ^

**Comment by smk78** [comment]
This is what I just got on a x64/W10 local build (pulling repos at 16:15 on CodeCamp Thu):
![image](https://user-images.githubusercontent.com/10938679/198309463-2bfb43cf-1783-4683-a919-c52bd8242ff6.png)
The **Load data**, **Send data to** and **Fitting** buttons seem to have abnormal fonts?

The display resolution is 1920x1080.
pip list shows: matplotlib 3.4.3, PyQt5 5.15.7, QtPy 2.1.0; python 3.9.12

**Comment by lucas-wilkins** [comment]
As fixed as it is ever going to be in Qt5
