### ISSUE TITLE
move to Qt6

### ISSUE THREAD

**Issue by rozyczko** [SasView/sasview#2257]
Qt6 is slowly maturing, and it is probably good time to start looking at switching versions.
I don't expect it to be much more troublesome than the previous qt4->qt5 transition.
More details:
https://www.pythonguis.com/faq/pyqt5-vs-pyqt6/

Also, we might want to think about switching to PySide2.

**Comment by andyfaff** [comment]
There are a few issues with moving to Qt6 at the moment.

- on pip there are wheels for PyQt6 and PySide6 for most arches. However there are no Qt6 (and PyQt6 and PySide6) currently available on conda-forge. So if you move to Qt6 immediately conda-forge users are going to be left hanging.
- for pyqt5/pyside2 there are no `macosx_arm64` wheels available. So if you don't move to Qt6 then one leaves `macosx_arm64` users hanging.

Which is the lesser of two evils?

**Comment by rozyczko** [comment]
Agreed with point 2) - PySide2 is not actively being developed for more modern architectures, apparently.
However, I think we can get PySide6 on all archs from conda-forge:

https://anaconda.org/conda-forge/pyside6

![conda](https://user-images.githubusercontent.com/8266281/198576352-25dd1a59-3d53-4278-8ab8-ce94d051bb27.png)

**Comment by rozyczko** [comment]
The PySide2 conversion step is meant to be transitory, so as soon as the conversion is complete, I'll upgrade to Qt6 and this will be PR-ed.
