### ISSUE TITLE
Handle kill signals better

### ISSUE THREAD

**Issue by lucas-wilkins** [SasView/sasview#2270]
**Describe the bug**
Killing SasView, rather than using the exit functionality will stall it, rather than close it.

**To Reproduce**

Stop with IDE signal.

Alternatively, run from console and ctrl-C.

**Expected behavior**
Sasview closes

**Comment by llimeht** [comment]
Classic PyQt behaviour. 

https://machinekoder.com/how-to-not-shoot-yourself-in-the-foot-using-python-qt/ talks about some of what is needed.

**Comment by pkienzle** [comment]
A note on bumps: it will intercept KeyboardInterrupt and use it to stop the current fit in a controlled fashion.  If a fit is running you may not see Ctrl-C. I believe it works for all fitters but I've used it most with DREAM.

I use this to catch a signal 5 min before the end of the allocation when running on a slurm queue:
```sh
 sbatch --signal=INT@60 -t0:4:0 batch.sh
```
`batch.sh`:
```sh
#!/bin/bash
srun python3 work.py 9 23
```
`work.py`:
```python
# work.py n t
#    Run for n steps with a wait of t seconds between steps.
import time
import sys

t0 = time.time()
def main():
    n = int(sys.argv[1]) if len(sys.argv) > 1 else 6
    t = int(sys.argv[2]) if len(sys.argv) > 2 else 10
    print("Running for {n} steps of length {t}s:".format(**locals()))
    sys.stdout.flush()
    for k in range(n):
        try:
            time.sleep(t)
            dt = time.time() - t0
            print(f"- step {k} of {n} after {dt:.1f}s")
            sys.stdout.flush()
            if stop: break
        except KeyboardInterrupt:
            break
    if k < n:
        print("Stopped early.")
    else:
        print("Stopped normally.")
    sys.stdout.flush()

main()
```

**Comment by lucas-wilkins** [comment]
Piotr has done this.
