### ISSUE TITLE
Refactoring of preferences

### ISSUE THREAD

**Issue by lucas-wilkins** [SasView/sasview#2316]
The following things need to be done to the preferences panel

* Cancel button -> #2358
* #2313 -> #2358
* #2312 -> #2358
* #2317 -> #2381

This can mostly be achieved through:
1) Modifying the preferences dialog system to have a more formal class structure
2) Better integration with config

**Comment by krzywon** [comment]
#2312: The `PreferencesWidget` class has a `restoreDefaults` attribute that houses a callable that is when the button is clicked. This just hasn't been implemented in any of the child classes yet. This should really change to a class method that child classes override. Update child classes to use this method. Question: should this reset the defaults in the current panel or in all panels?

#2313: Changes to make: Add a `Cancel` button, remove (most) connections from GUI elements, and update everything when the `OK` button is clicked. Would an `Apply` button be useful, too?

**Comment by pbeaucage** [comment]
#2313 another, potentially easier solution would be to change the underlying config class to have some method set like `beginStagingChanges()`, `commitStagedChanges()` and `discardStagedChanges()`.  begin would be called on dialog open and basically `copy()` the structure to a backup place.  Then `commit...()` would replace main copy with the edited copy and `discard...()` would replace the stored version with the editable copy.

**Comment by pbeaucage** [comment]
Not in general, depends on the config items.  The `Plotting` ones all take effect immediately.

**Comment by lucas-wilkins** [comment]
Also, probably need to have a "your changes will not be applied untl you restart sasview" message for the display settings

**Comment by krzywon** [comment]
Comments from #2306 that I am documenting here:

- [ ] `preferences.rst` word-smithing
- [ ] Potential performance improvements if one of `bumps.fitting` -or- `bumps.options` imports was removed from FittingPerspective.py (maybe needs it's own issue)
- [ ] Better handling of `name` passed when adding widgets
- [ ] Add `NotImplementedError` to `PreferencesWidget._addAllWidgets` and planned `PreferencesWidget.restoreDefaults`
- [ ] Better separation of GUI and logic for 'PreferencesWidget' children
- [ ] Move fitting options window back into fitting perspective to retain the perspective-as-plugin framework

**Comment by krzywon** [comment]
> Also, probably need to have a "your changes will not be applied untl you restart sasview" message for the display settings

See #2317 - Tracking what is changed, we could better handle when a restart is required and only prompt the user when necessary.

**Comment by lucas-wilkins** [comment]
Think this is done now.
