### ISSUE TITLE
Testing needs to be hermetic against user config

### ISSUE THREAD

**Issue by llimeht** [SasView/sasview#2325]
As more things go into the user config file, the user's config ability to break the test suite, generating either false positives (as seen in #2294) or false negatives.

The test harness needs to grow a means of ensuring that the tests are run with an empty or non-existent config files for sasview, sasmodels, matplotlib etc.

It's likely that a pytest fixture for the config can be employed for this. Popping it in `conftest.py`, making it class-scoped, and auto-used is probably enough. Making it automatic enough that we don't need to add hundreds of fixture uses to the functions would be worthwhile. Rather than creating (or emptying) the config file each time, just moving to a new empty temporary directory and pointing `HOME` at it each time might work.

**Comment by lucas-wilkins** [comment]
OK, I'll have a think about this. There are various ways of doing it.

**Comment by lucas-wilkins** [comment]
Now there is a config method in this branch that sets it to defaults and wont save
