### ISSUE TITLE
Check (correct?) how uncertainties are computed when a parameter is constrained using a formula

### ISSUE THREAD

**Issue by gonzalezma** [SasView/sasview#2374]
It is not fully clear how the uncertainties for constrained parameters are computed when we have a formula instead of a single direct constraint of the form M2.p = M1.p.

To test this I created a set of 4 core-shell models where the radius of each model is equal to the sum of radius + thickness of the previous model, so I need to define 3 constraints of the form M2:radius = M1.radius + M1.thickness (and similarly for M3=M2 & M4=M3).

The simultaneous fit works fine and the returned parameters are reasonable and respect the constraints. But this is less clear for the error estimates. For example, for M1 (not constrained) I have radius = 147.91 (error = 0.23099) and thickness = 42.411 (error = 0.35439). Therefore I expect for M2 to have radius = 147.91 + 42.411 = 190.321, with error = sqrt(0.23099**2+0.35439**2) = 0.42302. But the error given in SasView interface is 0.17023.

Note that checking directly in a python shell with the uncertainties package, I get the expected result:
>>> from uncertainties import ufloat
>>> r = ufloat(147.91, 0.23099)
>>> t = ufloat(42.411, 0.35439)
>>> r + t
190.321+/-0.4230232289130232

**Comment by lucas-wilkins** [comment]
If there is correlation between parameter estimates you should get a different (smaller if positively correlated) error. Your test using uncertainties assumes statistical independence, Probably SasView is right in this case.

**Comment by gonzalezma** [comment]
Good point. That's absolutely right, so this can be closed.
