### ISSUE TITLE
Add multiprocessor support for Mac (Trac #9)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#238]
We are currently using openmp which works for windows.  Apparently it is unstable on the mac with the 32 bit version of packages we are using.  This is a HUGE limitation for the large mac base in Europe (and grwowing mac base in the us) 

Migrated from http://trac.sasview.org/ticket/9
```json
{
    "status": "closed",
    "changetime": "2015-11-22T02:03:33",
    "_ts": "2015-11-22 02:03:33.172985+00:00",
    "description": "We are currently using openmp which works for windows.  Apparently it is unstable on the mac with the 32 bit version of packages we are using.  This is a HUGE limitation for the large mac base in Europe (and grwowing mac base in the us) ",
    "reporter": "butlerpd",
    "cc": "",
    "resolution": "obsolete",
    "workpackage": "SasView Bug Fixing",
    "time": "2012-03-29T00:00:54",
    "component": "SasView",
    "summary": "Add multiprocessor support for Mac",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.0.0",
    "owner": "",
    "type": "enhancement"
}
```

**Comment by butlerpd** [comment]
Trac update at `2012/05/06 16:11:37`: **butlerpd** changed milestone from "" to "WishList"

**Comment by ajj** [comment]
Trac update at `2015/01/14 12:01:14`: 
* **ajj** changed component from "SansView" to "SasView"
* **ajj** changed workpackage from "" to "SasView Bug Fixing"

**Comment by butlerpd** [comment]
Trac update at `2015/02/21 14:45:51`: 
* **butler** commented:

This is part of the sasmodel which will move us to opencl -- see those tickets.


* **butler** changed resolution from "" to "obsolete"
* **butler** changed status from "new" to "closed"

**Comment by butlerpd** [comment]
Trac update at `2015/11/22 02:03:33`: **butler** changed milestone from "WishList" to "SasView 4.0.0"
