### ISSUE TITLE
UI elements are shifted

### ISSUE THREAD

**Issue by elindgren** [SasView/sasview#2380]
**Describe the bug**
All UI elements are shifted to the right relative to where they are drawn. For instance, one needs to click to the left of a checkbox to toggle it.

**To Reproduce**
1. Go to Fit Panel.
2. Load a model.
3. Click on the checkboxes under "Parameter".

This is one example. The same thing goes for all buttons and fields in the UI. 

**Expected behavior**
Elements should respond to clicks/interaction where they are actually drawn.

**Screenshots**
![Screenshot from 2022-11-09 14-47-19](https://user-images.githubusercontent.com/27208255/200846676-781d5180-e767-4de2-bffc-710654f1fb7e.png)

![Screenshot from 2022-11-09 14-47-00](https://user-images.githubusercontent.com/27208255/200846687-fcfd86c4-a81e-4c53-85d5-77346aec6ef8.png)

**SasView version (please complete the following information):**
 - Version: 5.0.5

**Operating system (please complete the following information):**
 - OS: Linux/Ubuntu 22.04
 - Built SasView from source using the guide under Developer guide.
 - Commit: b0bd59344c6ef0c0653e5589d3ca3708544eb3b9
 - Python 3.10, installed in a Python venv (note! not conda).

Dump of environment from `pip freeze`

```python
alabaster==0.7.12
appdirs==1.4.4
arabic-reshaper==2.1.4
asn1crypto==1.5.1
astroid==2.12.12
asttokens==2.1.0
attrs==22.1.0
Automat==22.10.0
Babel==2.11.0
backcall==0.2.0
bumps==0.9.0
certifi==2022.9.24
cffi==1.15.1
charset-normalizer==2.1.1
click==8.1.3
constantly==15.1.0
contourpy==1.0.6
cryptography==38.0.3
cssselect2==0.7.0
cycler==0.11.0
Cython==0.29.32
debugpy==1.6.3
decorator==5.1.1
dill==0.3.6
docutils==0.19
dominate==2.7.0
entrypoints==0.4
exceptiongroup==1.0.1
executing==1.2.0
fonttools==4.38.0
future==0.18.2
h5py==3.7.0
html2text==2020.1.16
html5lib==1.1
hyperlink==21.0.0
idna==3.4
imagesize==1.4.1
importlib-resources==5.10.0
incremental==22.10.0
iniconfig==1.1.1
ipykernel==6.17.0
ipython==8.6.0
ipython-genutils==0.2.0
isort==5.10.1
jedi==0.18.1
Jinja2==3.1.2
jsonschema==4.17.0
jupyter_client==7.4.4
jupyter_core==4.11.2
kiwisolver==1.4.4
lazy-object-proxy==1.8.0
llvmlite==0.39.1
lxml==4.9.1
Mako==1.2.3
MarkupSafe==2.1.1
matplotlib==3.5.3
matplotlib-inline==0.1.6
mccabe==0.7.0
more-itertools==9.0.0
nest-asyncio==1.5.6
numba==0.56.4
numpy==1.22.4
oscrypto==1.3.0
packaging==21.3
parso==0.8.3
periodictable==1.5.0
pexpect==4.8.0
pickleshare==0.7.5
Pillow==9.3.0
platformdirs==2.5.3
pluggy==0.13.1
prompt-toolkit==3.0.32
psutil==5.9.4
ptyprocess==0.7.0
pure-eval==0.2.2
py==1.11.0
pybind11==2.10.1
pycparser==2.21
Pygments==2.13.0
pyHanko==0.15.1
pyhanko-certvalidator==0.19.6
pylint==2.15.5
pyparsing==3.0.9
PyPDF2==2.11.1
PyPDF3==1.0.6
PyQt5==5.15.7
PyQt5-Qt5==5.15.2
PyQt5-sip==12.11.0
pyrsistent==0.19.2
pytest==5.4.3
pytest-mock==3.10.0
pytest-qt==4.2.0
python-bidi==0.4.2
python-dateutil==2.8.2
pytools==2022.1.12
pytz==2022.6
pytz-deprecation-shim==0.1.0.post0
PyYAML==6.0
pyzmq==24.0.1
qrcode==7.3.1
qt5reactor==0.6.3
qtconsole==5.4.0
QtPy==2.3.0
reportlab==3.6.6
requests==2.28.1
sasdata==0.8.1
sasmodels==1.0.6
sasview==5.0.5
scipy==1.7.3
six==1.16.0
snowballstemmer==2.2.0
Sphinx==5.3.0
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==2.0.0
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.5
stack-data==0.6.0
superqt==0.3.8
svglib==1.4.1
tinycc==1.1
tinycss2==1.2.1
tomli==2.0.1
tomlkit==0.11.6
tornado==6.2
tqdm==4.64.1
traitlets==5.5.0
Twisted==22.10.0
typing_extensions==4.4.0
tzdata==2022.6
tzlocal==4.2
uncertainties==3.1.7
unittest-xml-reporting==1.10.0
uritools==4.0.0
urllib3==1.26.12
wcwidth==0.2.5
webencodings==0.5.1
wrapt==1.14.1
xhtml2pdf==0.2.8
xmlrunner==1.7.7
zope.interface==5.5.1
```

**Additional context**

**Comment by lucas-wilkins** [comment]
A couple of questions:
1) What is your display configuration like (laptop, external screen etc)?
2) Does messing with the display settings that are now in preferences make a difference?

Thanks

**Comment by elindgren** [comment]
> A couple of questions:
> 
>     1. What is your display configuration like (laptop, external screen etc)?
> 
>     2. Does messing with the display settings that are now in preferences make a difference?
> 
> 
> Thanks

1. Laptop with a 4K screen, with 200% resolution scaling.
2. Disabling resolution scaling (i.e. setting it to 100%) seems to resolve the issue. 

So it seems like this is a scaling issue.

**Comment by lucas-wilkins** [comment]
Qt high DPI scaling issues are a constant problem. Hopefully they are better with Qt6, which we'll be moving to soon.

I'm just going to flag this as related for now, and see if other people think it might be fixed when we move.

@rozyczko @pbeaucage 

See #2257

**Comment by pbeaucage** [comment]
One hopefully-easy way to test is try to run from the release_5.0.5 branch (which doesn't have scaling) and see if this reproduces there.  If it's fine there, this is definitely a Qt high DPI problem to me.  Let me know if you need more detailed instructions.

**Comment by lucas-wilkins** [comment]
@pbeaucage I wonder if it might be related to the Qt High DPI rounding option you found?

**Comment by rozyczko** [comment]
Just looked at 200% scaling on **Windows** with 5.0.5 release and current main.
Both behave as expected, with no shift

**Comment by lucas-wilkins** [comment]
Guessing this is resolved now? Will close, but @elindgren feel free to reopen if its still a problem.
