### ISSUE TITLE
Empty Numerical Preference Values Throw Errors

### ISSUE THREAD

**Issue by krzywon** [SasView/sasview#2389]
**Describe the bug**
See the comment in [#2381](https://github.com/SasView/sasview/pull/2381#issuecomment-1323804696). Empty numerical values throw an error when coercion is attempted. The value should be coerced to something sensible or reset to the previous value.

**Screenshots**
See the comment

**Comment by lucas-wilkins** [comment]
@krzywon Did you fix this?
