### ISSUE TITLE
Icon redesign

### ISSUE THREAD

**Issue by lucas-wilkins** [SasView/sasview#2411]
Like with many other neutron software projects, the icon non-descript, and quite dated.

It needs a better one.

A colleague and I have been bouncing ideas around for quite a while now, and we think we have a better one.

**Comment by rozyczko** [comment]
![Untitled](https://user-images.githubusercontent.com/8266281/210577408-6338ca5e-45b6-4ae1-9b74-75be62ae24ea.png)

Are you referring to this app icon? It is indeed dated and I think we got used to it enough to not see the need of redesign.
We have quite recently revised the SV logo so maybe it is time to address the icon now?

**Comment by lucas-wilkins** [comment]
![sasview-icon](https://user-images.githubusercontent.com/9784906/210602948-7032a385-1d34-4ac5-aeca-b2cd4544ffe5.png)

**Comment by lucas-wilkins** [comment]
Closing as wont do.
