### ISSUE TITLE
Revisit Corfunc Save Transformed output

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#2454]
Copied from PR https://github.com/SasView/sasview/pull/2450

We need to have a think about the action of the Save Transformed button. I appreciate it is currently writing the same output that @rprospero implemented, namely a 4-column CSV (X, 1D CF, 3D CF & IDF). But as @butlerpd pointed out on another issue, if you then try and use this file in SasView it loads X vs 1D CF and applies the 3D CF values as uncertainties! And the IDF is ignored. I can think of two ways around this. One is to always simply write 3 files, appending to the user-provided filename _1D, _3D and_IDF for X vs 1D CF, X vs 3D CF and X vs IDF, respectively. The other is to have a radio button to select what transform you want to output. I think I lean towards the former solution.

**Comment by lucas-wilkins** [comment]
If only there was a structured file format the supports this.

**Comment by smk78** [comment]
> Another solution is just call it "Export Transformed", then there's no expectation that SasView should be able to read it unproblematically.

No. I don't think that is a solution! And I'm really sure a User wouldn't.

If we write something out of SasView there must surely be an expectation that SasView will read it back in at least semi-sensibly!

Why can't we just output 3 files for now (until the loader supports something more holistic)?

**Comment by smk78** [comment]
Copied from https://github.com/SasView/sasview/pull/2463:

>> How has #2454 been addressed in this PR? The export transformed output seems to be the same?

> I renamed save to export.

Reasoning that 'export' means there is no expectation the program should re-read the output? Hmm...

I have remitted this debate to a discusison-poll: https://github.com/SasView/sasview/discussions/2470. Please vote!
