### ISSUE TITLE
Ubuntu 20 CI keeps hanging during "build sasmodels and docs"

### ISSUE THREAD

**Issue by lucas-wilkins** [SasView/sasview#2460]
Ubuntu 20 CI keeps hanging during "build sasmodels and docs". There's no obvious reason why in the CI output.

**Comment by butlerpd** [comment]
It looks like it is in the model rst files that it eventually fails? so guessing that is where it hangs? Still doesn't say why it randomly hangs there...

**Comment by lucas-wilkins** [comment]
I have made a PR on sasmodels that should give more insight into the issue. I hope it makes a difference, because the only thing worse than debugging the CI, is having to debug it via a different repository.

PR is https://github.com/SasView/sasmodels/pull/553

**Comment by lucas-wilkins** [comment]
Probably resolved by SasView/sasmodels#555
