### ISSUE TITLE
Fitting magnetic data: add a second model box to separate nuclear and magnetic models

### ISSUE THREAD

**Issue by rozyczko** [SasView/sasview#2487]
As requested during the magnetic SANS meeting (Lund, Apr 20, 2023)

Magnetic structure can be different than nuclear structure and therefore we need an ability to separately fit mag and nucl data.

GUI potential improvement: add a second model box to separate nuclear and magnetic models

The models should return amplitudes.
This requires some involvement with `sasmodels` - we need a magnetic composite.

Remember that the magnetic component should allow for using polydispersity.

This functionality relies on having simplified constraint generation for magnetic datasets, specified in #2490

**Comment by butlerpd** [comment]
One question that came up based on the very nice model by @dehoni that is currently on the marketplace https://marketplace.sasview.org/models/136/ (Superparamagnetic Core-Shell Spheres with 3D field orientation) is:

Is in fact this generalized separation approach the best for achieving the above or can all the permutations needed be captured in a handful of such specialized models?

**Comment by dehoni** [comment]
As an expansion, one could allow to select different basic form factors (spheres, cubes, etc) from a drop-down list also for the magnetism tab in the SASview GUI. This would already create some flexibility. 
To describe the magnetic response with field, you need some information/or sophisticated guess about the system. 
The above-mentioned model is IMHO the simplest problem with analytical known solutions. One might change to superball (continuous transition from cube to sphere).

**Comment by butlerpd** [comment]
This has been superseded by #2486. I have copied over the comment from @dehoni so this should be good to close now.
