### ISSUE TITLE
Simplified constraint access to magnetic SANS

### ISSUE THREAD

**Issue by rozyczko** [SasView/sasview#2490]
As requested during the magnetic SANS meeting (Lund, Apr 20, 2023)

We don't know what this entails exactly yet - needs more discussion and requirements...

Parameters between the nuclear and magnetic shapes e.g nuclear radius = core mag radius+ mag shell thickness

**Comment by butlerpd** [comment]
Can we now close this?

**Comment by butlerpd** [comment]
closing as being superseded by #2496
