### ISSUE TITLE
Allow multiple slicers on a data set

### ISSUE THREAD

**Issue by krzywon** [SasView/sasview#2503]
**Is your feature request related to a problem? Please describe.**
A sector average might only be pertinent within a small annular q range. Ideally, the ability to use both sector and annular averaging would help helpful.

**Describe the solution you'd like**
The ability to apply any number of slicers to a plotted data set would be helpful. An option to perform the slices either independently or in the overlap region should be an option. Adding a checkbox to each slicer to define if it is independent or not would be a useful GUI feature.

**Comment by butlerpd** [comment]
@krzywon and @astellhorn --Can we close this out in favor of the new one put in by Annika.  I realize it is not exactly the same, but I think that the new one has all of what is in this one that is reasonable given the way things have progressed? And allow us to keep our ever growing pile of issues to a dull roar 😄.

**Comment by krzywon** [comment]
I think this issue has a broader scope and I suggest it stay open for now until someone can analyze what is needed to implement either or both. Both might be possible in one go, but that isn't certain.

**Comment by astellhorn** [comment]
Isnt #2503 basically mentioned here except for the comment “Adding a checkbox to each slicer to define if it is independent or not would be a useful GUI feature.”? I can add this comment!

In general: can one still look on the comments if you have their issue number even if they are closed?

**Comment by krzywon** [comment]
After some discussion with @astellhorn, this issue and #2503 overlap enough, so this issue can be closed.
