### ISSUE TITLE
User web pages need a complete overhaul (Trac #24)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#253]
The user web pages at danse.chem.utk.edu have two issues which need to be addressed:

1)The DANSE part of the project is over and the DANSE branding needs to go as does the flavor of an ongoing NSF funded project at UTK. One aspect is probably to point something like sasview.smallangles.net to the pages. However, we need to be very sensitive the NSF investment that delivered a product we can work with.

2)Much of what is on these pages is old and/or wrong even for the DANSE project

Migrated from http://trac.sasview.org/ticket/24
```json
{
    "status": "closed",
    "changetime": "2017-01-18T00:22:35",
    "_ts": "2017-01-18 00:22:35.277073+00:00",
    "description": "The user web pages at danse.chem.utk.edu have two issues which need to be addressed:\n\n1)The DANSE part of the project is over and the DANSE branding needs to go as does the flavor of an ongoing NSF funded project at UTK. One aspect is probably to point something like sasview.smallangles.net to the pages. However, we need to be very sensitive the NSF investment that delivered a product we can work with.\n\n2)Much of what is on these pages is old and/or wrong even for the DANSE project\n",
    "reporter": "butlerpd",
    "cc": "",
    "resolution": "fixed",
    "time": "2012-03-29T11:47:45",
    "component": "SansView",
    "summary": "User web pages need a complete overhaul",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 2.2",
    "owner": "butler",
    "type": "task"
}
```

**Comment by butlerpd** [comment]
Trac update at `2012/04/03 21:49:28`: 
* **butlerpd** changed owner from "butlerpd" to ""
* **butlerpd** changed status from "new" to "assigned"

**Comment by butlerpd** [comment]
Trac update at `2012/04/03 21:50:26`: **butlerpd** changed owner from "" to "butlerpd"

**Comment by butlerpd** [comment]
Trac update at `2012/04/03 21:50:58`: **butlerpd** changed status from "assigned" to "accepted"

**Comment by butlerpd** [comment]
Trac update at `2012/04/04 11:50:40`: **butlerpd** commented:

Part 2 of the ticket is fixed.  The DANSE/SANS web pages are now updated and cleaned up and announce the version 2.1 availability.  Also they are more or less prepared to be sunsetted with a view to point to new pages which need to be developed for the SasView project - the plan is the next major release will both rebrand the software to SasView and debut the new webpages.

**Comment by butlerpd** [comment]
Trac update at `2012/05/06 16:02:36`: **butlerpd** changed milestone from "" to "SansView 2.2"

**Comment by butlerpd** [comment]
Trac update at `2012/12/05 13:13:45`: 
* **butlerpd** commented:

This was done for the release of SasView (rather than sansview) 2.2


* **butlerpd** changed resolution from "" to "fixed"
* **butlerpd** changed status from "accepted" to "closed"

**Comment by ajj** [comment]
Trac update at `2016/02/28 11:49:43`: **ajj** changed owner from "butlerpd" to "butler"
