### ISSUE TITLE
Impossible right-click on parameters in Fit Panel

### ISSUE THREAD

**Issue by lozanodorian** [SasView/sasview#2530]
**Describe the bug**
It is impossible to right-click on a parameter in `Fit panel > Model`
The error message is : 
```
11:39:37 - sas.qtgui.Perspectives.Fitting.FittingWidget - ERROR - Traceback (most recent call last):
  File "sasview/src/sas/qtgui/Perspectives/Fitting/FittingWidget.py", line 691, in showModelContextMenu
    menu = self.showModelDescription() if not rows else self.modelContextMenu(rows)
  File "sasview/src/sas/qtgui/Perspectives/Fitting/FittingWidget.py", line 714, in modelContextMenu
    self.actionSelect = QtWidgets.QAction(self)
AttributeError: module 'PySide6.QtWidgets' has no attribute 'QAction'
```

**To Reproduce**
1. Choose a model (Category and Model name) in `Fit Panel > Model`
2. Right-click on the name of one of the parameters
3. See error

**Expected behavior**
A panel should appear with the options:
- "Select parameter for fitting", "De-select parameter from fitting", "Constrain parameter to its current value"
or
- "Select parameter for fitting", "De-select parameter from fitting", "Remove constraint", "Edit constraint"

**SasView version:**
 - 5.0.5 (commit b98020f on main)

**Operating system:**
 - OS: Linux

**Comment by rozyczko** [comment]
QAction in Qt6 is on QtGui, not QtWidget as in Qt5.
Fixed
