### ISSUE TITLE
Log spacing for Generic Scattering Calculator

### ISSUE THREAD

**Issue by smalex-z** [SasView/sasview#2537]
**Is your feature request related to a problem? Please describe.**
The Generic Scattering Calculator currently evaluates Q-Bins with Linear Spacing, despite being plotted on a Log scale. Furthermore, there is no option for the user to choose the minimum Q -  The minimum Q is just automatically set to the Q-Max * .001.

**Describe the solution you'd like**
Adding the option for Log Spacing as well as a Minimum Q input.

**Additional context**
Custom Plugin Models from Generic Scattering Calculator will use a Log Spacing .

**Comment by krzywon** [comment]
Fixed in release_6.0.0 branch. Closing
