### ISSUE TITLE
Need scripts to autogenerate Sphinx documentation (Trac #25)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#254]
Jessica Tumarkin, a DANSE intern in the summer of 2011 set up and then generated Sphinx developer documentation which can be accessed as static web pages on the UTK DANSE site.  However, they are already getting obsolete and will continue to do so unless people update them every time a new commit is made to the repo (probably not sustainable) or we build some scripts into the system that auto-generate (and then post appropiately) the appropriate documentation when things are committed.

Mathieu Doucet has agreed to take a first look at what might be involved 

Migrated from http://trac.sasview.org/ticket/25
```json
{
    "status": "closed",
    "changetime": "2017-02-28T23:28:38",
    "_ts": "2017-02-28 23:28:38.056592+00:00",
    "description": "Jessica Tumarkin, a DANSE intern in the summer of 2011 set up and then generated Sphinx developer documentation which can be accessed as static web pages on the UTK DANSE site.  However, they are already getting obsolete and will continue to do so unless people update them every time a new commit is made to the repo (probably not sustainable) or we build some scripts into the system that auto-generate (and then post appropiately) the appropriate documentation when things are committed.\n\nMathieu Doucet has agreed to take a first look at what might be involved ",
    "reporter": "butlerpd",
    "cc": "",
    "resolution": "fixed",
    "time": "2012-03-29T11:55:55",
    "component": "SansView",
    "summary": "Need scripts to autogenerate Sphinx documentation",
    "priority": "major",
    "keywords": "",
    "milestone": "SansView 2.1.1",
    "owner": "mathieu",
    "type": "task"
}
```

**Comment by butlerpd** [comment]
Trac update at `2012/05/06 22:36:11`: **butlerpd** changed milestone from "" to "SansView 2.1.1"

**Comment by ajj** [comment]
Trac update at `2016/02/28 11:52:42`: **ajj** changed owner from "m-doucet" to "mathieu"
