### ISSUE TITLE
Upgrading python and pyintsaller in CI scripts 

### ISSUE THREAD

**Issue by wpotrzebowski** [SasView/sasview#2546]
The current CI build uses python 3.8 and pyinstaller 5.7.0. It would be good to upgrade them to higher versions. 
As a part of https://github.com/SasView/sasview/pull/2544 I did upgraded to 3.9 and pyintsaller 5.13.0, however, it has been decided that it should be addressed separately. I think it would be worth trying even with python=3.10.

**Comment by llimeht** [comment]
CI is already passing with 3.10 which is a good sign, although no GUI tests are being run so there is no coverage there.

It would be reasonable to add 3.11 and 3.12 to the test matrix with a view to landing on 3.12 for a new release (and 3.8/3.9/3.10 being removed shortly). There will be things that fail with the newer Python but there are already patches for python 3.11 and the newer numpy/scipy that will require.

**Comment by andyfaff** [comment]
FWIW scipy wheels get built against specific versions of numpy, https://github.com/scipy/scipy/blob/main/pyproject.toml#L30.  You can use more recent versions of numpy with those wheels, but you wouldn't want to use an older version. scipy/numpy follow this [specification](https://scientific-python.org/specs/spec-0000/) of support for various Python versions. As such, we're coming to the end of the support window for 3.9 (being dropped in October of this year).

The spec contains motivations behind the whole support process.

**Comment by krzywon** [comment]
This is now implemented in release_6.0.0. Closing
