### ISSUE TITLE
Syntax highlighting is throwing errors in PySide

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#2555]
Syntax highlighting is throwing errors in PySide:

```
16:32:49 - sas.qtgui.Perspectives.Fitting.FittingWidget - ERROR - Traceback (most recent call last):
  File "…/sasview/src/sas/qtgui/Utilities/PythonSyntax.py", line 134, in highlightBlock
    index = expression.indexIn(text, 0)
AttributeError: 'PySide6.QtCore.QRegularExpression' object has no attribute 'indexIn'
```

The `indexIn` method is a holdover from the `QRegExp` which is not available in the replacement `QRegularExpression`.

Code is here:
https://github.com/SasView/sasview/blob/90735cf133ba6722d2580d69318b2e2f3b291eef/src/sas/qtgui/Utilities/PythonSyntax.py#L129-L141

Presumably this needs to be replaced:
```python
for expression, nth, format in self.rules:
    match = expression.match(text, offset=0)

     while match.hasMatch():
        # We actually want the index of the nth match
        index = expression.capturedStart(nth)
        length = expression.capturedLength(nth)
        self.setFormat(index, length, format)
        match = expression.match(text, offset=match.capturedEnd(0))
```

Expression initialized as a `QRegularExpression` here:
https://github.com/SasView/sasview/blob/90735cf133ba6722d2580d69318b2e2f3b291eef/src/sas/qtgui/Utilities/PythonSyntax.py#L124-L126

Incidentally, the comment on L124 is now wrong 8-)

**Comment by krzywon** [comment]
Fixed by merging of #2562
