### ISSUE TITLE
Data name is not changed for constraints when swapping

### ISSUE THREAD

**Issue by lozanodorian** [SasView/sasview#2564]
**Describe the bug**
When using the `Swap data` option, the name of the dataset is not changed in Const. Simul. Fit.

**To Reproduce**
1. Load two datasets
2. Send one dataset to Fitting and choose a model
3. Open the Const. Simul. Fit. panel
4. Replace the first dataset of the first model by sending the second dataset to Fitting with the `Swap data` option checked 
5. See error : the name of the dataset in the `Data` column of the `Const. Simul. Fit.` is not changed.

**Expected behavior**
The name of the second dataset in the `Data` column (in place of the name of the first dataset).

**SasView version (please complete the following information):**
 - Version: 5.0.6

**Operating system (please complete the following information):**
 - OS: Linux

**Comment by rozyczko** [comment]
fixed in `2564-data-name-is-not-changed-for-constraints-when-swapping`
