### ISSUE TITLE
Need a simplified interface for constraining fit on one data set (Trac #29)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#257]
basically being able to relate two parameters within the model such as thickness of layer 1 and 3 of a core + 3 shell model are the same, and/or 1/2 the thickness of layer 2 etc.  If this is available (without making a dummy second fit) within "simultaneous fitting" then the name should be changed to constrained and simultaneous fitting.  Otherwise will not be intuitive to a user.

Migrated from http://trac.sasview.org/ticket/29
```json
{
    "status": "new",
    "changetime": "2017-10-26T09:45:42",
    "_ts": "2017-10-26 09:45:42.750270+00:00",
    "description": "basically being able to relate two parameters within the model such as thickness of layer 1 and 3 of a core + 3 shell model are the same, and/or 1/2 the thickness of layer 2 etc.  If this is available (without making a dummy second fit) within \"simultaneous fitting\" then the name should be changed to constrained and simultaneous fitting.  Otherwise will not be intuitive to a user.",
    "reporter": "butlerpd",
    "cc": "",
    "resolution": "",
    "workpackage": "SasView GUI Redesign",
    "time": "2012-03-29T17:55:26",
    "component": "SasView",
    "summary": "Need a simplified interface for constraining fit on one data set",
    "priority": "minor",
    "keywords": "",
    "milestone": "SasView 5.1.0",
    "owner": "",
    "type": "enhancement"
}
```

**Comment by butlerpd** [comment]
Trac update at `2012/05/06 15:57:16`: **butlerpd** changed milestone from "" to "WishList"

**Comment by butlerpd** [comment]
Trac update at `2015/01/30 02:33:54`: **butler** changed workpackage from "" to "SasView GUI Redesign"

**Comment by ajj** [comment]
Trac update at `2017/01/17 13:05:47`: **ajj** changed component from "SansView" to "SasView"

**Comment by butlerpd** [comment]
Trac update at `2017/10/26 09:45:42`: **butler** changed milestone from "SasView WishList" to "SasView 5.1.0"

**Comment by lucas-wilkins** [comment]
@gonzalezma What's the status of this?

**Comment by gonzalezma** [comment]
Closed as done.
