### ISSUE TITLE
category management problems

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#2584]
**Describe the bug**

The category manager panel allows a category to be repeated multiple times which causes the model to appear multiple times in the model dropdown on the fitting page.

The model enable/disable flags do not seem to be maintained when editing categories. Somehow I managed to get one to appear as false in the saved categories.json but I don't know how to reproduce it.

Model enable/disable flags are ignored for the model dropdown on the fitting page.

Model enable/disable flags will likely reset when a new model is added to the standard set (guessing from looking at the code).

The GUI is deleting rpa from every category when building the model dropdown options. It would be better to honour the enable/disable flag and default it to disabled. Or remove it from sasmodels if it is not considered production quality.

**To Reproduce**
1. Go to 'Fitting> Category Manager'
2. Try operations above
3. Restart sasview to see if they are preserved.

**SasView version (please complete the following information):**
 - Version: 2023-08-08 9855cde8d

**Operating system (please complete the following information):**
 - OS: Mac 13.5

**Comment by pkienzle** [comment]
There seems to be a lot of duplicated code in category management. Best to create a set of functions (in sas.system, in sas.sascalc.fitting or in sasmodels) so that categories are handled consistently.

**Comment by rozyczko** [comment]
addressed in https://github.com/SasView/sasview/tree/2584-category-management-problems

**Comment by butlerpd** [comment]
I think most if not all of these have now been fixed in PR#2649 above with the exception of the RPA comment. However the current behavior is correct and should **not** be removed from sasmodels. the model is correct. Only qtgui does not know how to handle it so that it will give completely bogus results ... when it even works, when called from the gui rather than the CLI.
