### ISSUE TITLE
Documentation needs to be reviewed and updated (Trac #32)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#260]
All the documentation needs to be reviewed and updated:

* Many things are now dated - particularly true of Tutorial
* Many new things are not documented - particularly true of tutorial
* Some things are not documented (slipped through the cracks) such as the residual plot and how it is calculated.
* We need to provide some documentation of how some 3rd party modules work such as PARK
* English could be improved in all cases

Migrated from http://trac.sasview.org/ticket/32
```json
{
    "status": "closed",
    "changetime": "2017-02-27T17:27:16",
    "_ts": "2017-02-27 17:27:16.694953+00:00",
    "description": "All the documentation needs to be reviewed and updated:\n\n* Many things are now dated - particularly true of Tutorial\n* Many new things are not documented - particularly true of tutorial\n* Some things are not documented (slipped through the cracks) such as the residual plot and how it is calculated.\n* We need to provide some documentation of how some 3rd party modules work such as PARK\n* English could be improved in all cases\n",
    "reporter": "butlerpd",
    "cc": "",
    "resolution": "obsolete",
    "workpackage": "SasView Documentation",
    "time": "2012-03-29T22:30:47",
    "component": "SasView",
    "summary": "Documentation needs to be reviewed and updated",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 3.1.0",
    "owner": "",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2012/03/29 23:18:05`: 
* **butlerpd** changed description from:

> Much of the tutorial is obsolete; New features missing; and the English could be improved.

to:

> All the documentation needs to be reviewed and updated:
> 
> * Many things are now dated - particularly true of Tutorial
> * Many new things are not documented - particularly true of tutorial
> * Some things are not documented (slipped through the cracks) such as the residual plot and how it is calculated.
> * We need to provide some documentation of how some 3rd party modules work such as PARK
> * English could be improved in all cases
> 


* **butlerpd** changed summary from "Tutorial needs to be reviewed and updated" to "Documentationl needs to be reviewed and updated"
* **butlerpd** changed type from "enhancement" to "defect"

**Comment by butlerpd** [comment]
Trac update at `2012/05/06 16:16:34`: **butlerpd** changed milestone from "" to "SansView 2.2"

**Comment by butlerpd** [comment]
Trac update at `2012/12/05 14:38:48`: **butlerpd** changed milestone from "SasView 2.2" to "SasView 3.0.0"

**Comment by butlerpd** [comment]
Trac update at `2012/12/05 15:01:04`: 
* **butlerpd** changed component from "SansView" to "SasView"
* **butlerpd** changed owner from "" to ""

**Comment by butlerpd** [comment]
Trac update at `2013/09/24 11:18:55`: **butler** changed milestone from "SasView 3.0.0" to "SasView Next Release"

**Comment by butlerpd** [comment]
Trac update at `2013/09/24 11:19:41`: **butler** commented:

No more work will be done on this ticket for this release.  Moved it to "next release"

**Comment by ajj** [comment]
Trac update at `2015/01/14 12:46:59`: **ajj** changed workpackage from "" to "SasView Documentation"

**Comment by butlerpd** [comment]
Trac update at `2015/03/22 16:49:31`: **butler** changed summary from "Documentationl needs to be reviewed and updated" to "Documentation needs to be reviewed and updated"

**Comment by butlerpd** [comment]
Trac update at `2015/03/22 17:23:28`: 
* **butler** commented:

This is an old ticket covering a lot of ground, some of which is obsolete, some fixed, some in other tickets.  Have made a couple of more specific tickets for current issues. Am now closing this as obsolete.


* **butler** changed resolution from "" to "obsolete"
* **butler** changed status from "new" to "closed"

**Comment by butlerpd** [comment]
Trac update at `2015/11/22 01:56:48`: **butler** changed milestone from "SasView Next Release +1" to "SasView 3.1.0"
