### ISSUE TITLE
Smearing documentation could be improved (Trac #33)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#261]
Ralph Schweins has indicated that the clarity could be improved and better references provided.  Ralph should be consulted as well as David Mildner on this.

Certainly the equations should be redone at higher resolution.

Migrated from http://trac.sasview.org/ticket/33
```json
{
    "status": "closed",
    "changetime": "2017-02-28T23:35:37",
    "_ts": "2017-02-28 23:35:37.180595+00:00",
    "description": "Ralph Schweins has indicated that the clarity could be improved and better references provided.  Ralph should be consulted as well as David Mildner on this.\n\nCertainly the equations should be redone at higher resolution.",
    "reporter": "butlerpd",
    "cc": "",
    "resolution": "obsolete",
    "workpackage": "SasView Documentation",
    "time": "2012-03-29T22:35:23",
    "component": "SasView",
    "summary": "Smearing documentation could be improved",
    "priority": "minor",
    "keywords": "",
    "milestone": "SasView Next Release +1",
    "owner": "",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2012/05/06 16:00:27`: **butlerpd** changed milestone from "" to "SansView 2.2"

**Comment by butlerpd** [comment]
Trac update at `2012/09/13 17:39:30`: 
* **butlerpd** commented:

Will move this to 3.0 for now.  Probably should be part of the larger documentation issue so may want to merge this ticket with something else.


* **butlerpd** changed milestone from "SansView 2.2" to "SansView 3.0.0"

**Comment by butlerpd** [comment]
Trac update at `2012/12/05 15:12:27`: 
* **butlerpd** changed component from "SansView" to "SasView"
* **butlerpd** changed owner from "" to ""

**Comment by butlerpd** [comment]
Trac update at `2013/08/31 18:11:51`: 
* **butler** commented:

Clearly lacking manpower for this so moving to whislist for now


* **butler** changed milestone from "SasView 3.0.0" to "WishList"

**Comment by ajj** [comment]
Trac update at `2015/01/14 12:46:59`: **ajj** changed workpackage from "" to "SasView Documentation"

**Comment by butlerpd** [comment]
Trac update at `2015/08/14 20:25:20`: **butler** changed milestone from "WishList" to "SasView Next Release +1"

**Comment by butlerpd** [comment]
Trac update at `2017/02/28 23:35:37`: 
* **butler** commented:

Am going to close this very old (and probably forgotten) ticket even though the spirit of the ticket probably is still relevant.  However the documentation has already been heavily rewritten and the equations redone in latex. Other tickets (700 and 800 series) address a number of specific issues and reviews of how smearing is handled.


* **butler** changed resolution from "" to "obsolete"
* **butler** changed status from "new" to "closed"
