### ISSUE TITLE
plot context menu is broken in 6.0.0a1

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#2668]
**Describe the bug**
Using the latest build of 6.0.0a1, right clicking on most plots to get the context menu throw an error instead:
```
2023-10-26 11:09:38,405 : ERROR : sas.qtgui.Perspectives.Fitting.FittingWidget (FittingWidget.py:173) :: Traceback (most recent call last):
  File "sas\qtgui\Plotting\PlotterBase.py", line 272, in showContextMenu
  File "sas\qtgui\Plotting\Plotter.py", line 316, in createContextMenu
  File "sas\qtgui\Plotting\Plotter.py", line 397, in addPlotsToContextMenu
ValueError: operands could not be broadcast together with shapes (395,) (0,) 
```
Interestingly, the "extra plots" (i.e. residual and polydispersity) do not throw an error but pop up the context menu just fine. Could this be something to do with "role?"

**To Reproduce**
1. Load some data
2. click on `Create New` - alternatively click on `Send to Fitting` choose a model and hit calculate/plot
3. on the plot that pops up right click to get the context menu
4. Nothing happens! but if you look in the Log Explorer you will see an error like:
```
11:18:30 - ERROR: Traceback (most recent call last): File "sas\qtgui\Plotting\PlotterBase.py", line 272, in showContextMenu File "sas\qtgui\Plotting\Plotter.py", line 316, in createContextMenu File "sas\qtgui\Plotting\Plotter.py", line 397, in addPlotsToContextMenu ValueError: operands could not be broadcast together with shapes (66,) (0,)
```

**Expected behavior**
I expect the pop menu of course

**Screenshots**
NA

**SasView version (please complete the following information):**
 - Version: 6.0.0a1 uploaded to github at 5AM GMT on October 26

**Operating system (please complete the following information):**
 - OS: Windows 10

**Additional context**
I did not test plots from other perspectives

**Comment by rozyczko** [comment]
switching to new numpy made checks like `!=[]` not just deprecated but removed. Fixing here.
No other occurrences of
