### ISSUE TITLE
Unable to save fitting reports

### ISSUE THREAD

**Issue by jules-marcone** [SasView/sasview#2675]
**Describe the bug**
After fitting some experimental data and trying to do a report (with the built-in report function), attempting to send the report (either with the regular "save" function or trying to print to a pdf file), it just returns an error.

**To Reproduce**
1. Click on 'Report Results'
2. Click on 'Save'
3. Enter any name and save in any folder.
4. See error : Traceback (most recent call last): File "sas\qtgui\Utilities\Reports\ReportDialog.py", line 118, in onSave File "sas\qtgui\Utilities\Reports\ReportDialog.py", line 143, in save_pdf File "", line 1176, in _find_and_load File "", line 1147, in _find_and_load_unlocked File "", line 690, in _load_unlocked File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module File "xhtml2pdf\pisa.py", line 26, in File "", line 1176, in _find_and_load File "", line 1147, in _find_and_load_unlocked File "", line 690, in _load_unlocked File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module File "xhtml2pdf\document.py", line 25, in File "", line 1176, in _find_and_load File "", line 1147, in _find_and_load_unlocked File "", line 690, in _load_unlocked File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module File "xhtml2pdf\context.py", line 33, in File "", line 1176, in _find_and_load File "", line 1147, in _find_and_load_unlocked File "", line 690, in _load_unlocked File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module File "xhtml2pdf\parser.py", line 44, in File "", line 1176, in _find_and_load File "", line 1147, in _find_and_load_unlocked File "", line 690, in _load_unlocked File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module File "xhtml2pdf\tables.py", line 21, in File "", line 1176, in _find_and_load File "", line 1147, in _find_and_load_unlocked File "", line 690, in _load_unlocked File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module File "xhtml2pdf\tags.py", line 26, in File "", line 1176, in _find_and_load File "", line 1147, in _find_and_load_unlocked File "", line 690, in _load_unlocked File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module File "reportlab\graphics\charts\textlabels.py", line 20, in File "", line 1176, in _find_and_load File "", line 1147, in _find_and_load_unlocked File "", line 690, in _load_unlocked File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module File "reportlab\graphics\utils.py", line 260, in File "reportlab\graphics\utils.py", line 63, in __makeTextPathsCode__ File "", line 1176, in _find_and_load File "", line 1147, in _find_and_load_unlocked File "", line 690, in _load_unlocked File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module File "freetype\__init__.py", line 24, in File "", line 1176, in _find_and_load File "", line 1147, in _find_and_load_unlocked File "", line 690, in _load_unlocked File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module File "freetype\raw.py", line 201, in File "ctypes\__init__.py", line 389, in __getattr__ File "ctypes\__init__.py", line 394, in __getitem__ AttributeError: function 'FTC_CMapCache_Lookup' not found

Alternatively:
1. Click on "Report results"
2. Click "Print"
3. Select "Print to PDF"
4. Save anywhere with any name
5. Error: Print report failed with: 'PySide6.QtGui.QTextDocument' object has no attribute 'print'

**Expected behavior**
For the report to be saved in pdf format

**SasView version (please complete the following information):**
 - Version:  alpha-6.0.0

**Operating system (please complete the following information):**
 - OS: Windows 10

**Comment by krzywon** [comment]
Thanks for the report, @jules-marcone.

@rozyczko, this looks related to the `PyQt` -> `PySide` transition. Can you take a look?
