### ISSUE TITLE
Constraining parameters in combined fits of multiple data sets

### ISSUE THREAD

**Issue by adrianrrennie** [SasView/sasview#2685]
**Describe the bug**
We are trying to constrain polydisperse parameters and the polydispersity to be equal when fitting multiple data sets with a single core-shell sphere model.   It looked as though this problem should be fixed according to 'Handling of constraints for polydisperse parameters (fix #1588) #2348' in the SasView 6.0.0a1 and tried to test on Windows 10.   The test still shows problems even without adding polydispersity (perhaps something else is broken).  When we try to add constraints  the 'Complex Constraint' window remains in the foreground and we cannot close it to try any fit.  There is also a warning message about polydispersity when trying to set a constraint for multiple fits even without setting any polydispersity in the model.

**To Reproduce**
1. Send 2 separate data sets to fitting
2. Select  sphere core_shell_sphere model for each data set
3. set parameters and allow e.g. radius and thickness to be fittable
4. select Constrained or Simultaneous Fit from fitting menu add
M1:radius = M2.radius
M1:thickness = M2.thickness
6. See error

**Expected behavior**
It is not possible to fit or even close the window with the constraints.  Note this behavior is not seen in Version 5.0.5 but warnings about polydispersity are seen.

**Screenshots**

**SasView version (please complete the following information):**
 - Version: 6.0.0a1 

**Operating system (please complete the following information):**
 - OS: Windows 10

**Additional context**

**Comment by adrianrrennie** [comment]
We are aware that this is a test on an alpha release but wanted to try whether the original problem of constraining polydispers parameters had been fixed.

**Comment by gonzalezma** [comment]
I confirm. At least on Windows there has been an involution (related to the passage to PySide?). The close button of the Complex Constraint window is not active, implying that pressing the Add Constraints button blocks SasView completely, as one remains stuck in the Complex Constraint interface.

**Comment by gonzalezma** [comment]
I built in Linux and works fine, so it seems like a Windows problem. For the moment, I am not able to build in Windows, so I cannot check further.

**Comment by gonzalezma** [comment]
I noticed the following in Windows 10: The X button is inactive in the windows corresponding to Category Manager, Add Custom Model, Edit Custom Model, Manage Custom Model, Add/Multiply Models and Complex Constraint. Except for the last window, it is still possible to close the windows using the OK, Cancel or Close button, respectively. But as there is not such alternative in the Complex Constraint window, once that this one is called SasView becomes non-operational. It is not even possible to close it normally. This is not the case in Linux, where the expected behaviour (window closes when X is pressed) is observed.

**Comment by adrianrrennie** [comment]
We have tried the Mac version but at the moment cannot get any fit to run as there seem to be a lot of Python errors.

**Comment by rozyczko** [comment]
Tested with most recent `release_6.0.0` build on Win10
- generating constraints based on the original comment succeeds without error
- running fitting on this set also works fine
- the `X` button in the right upper corner of the `Complex Constraints` widget is indeed disabled - needs fixing
- pressing Esc button closes this dialog

**Comment by rozyczko** [comment]
What fails, though, is trying to constrain polydisperse parameters.
I get now
```
13:17:15 - ERROR: Traceback (most recent call last): File "C:\projects\sasview\src\sas\qtgui\Perspectives\Fitting\ConstraintWidget.py", line 1129, in onAcceptConstraint constrained_tab.addConstraintToRow(constraint, constrained_row, model_key=model_key) File "C:\projects\sasview\src\sas\qtgui\Perspectives\Fitting\FittingWidget.py", line 957, in addConstraintToRow assert 0 
```

Before, when the polydisp functionality was tested (at the last code camp), this worked fine.

**Comment by rozyczko** [comment]
I made the non-working `X` button a separate issue (#2688 )
