### ISSUE TITLE
Improve documentation for SLD calculator

### ISSUE THREAD

**Issue by krzywon** [SasView/sasview#2689]
**Is your feature request related to a problem? Please describe.**
The documentation for the SLD calculator is a bit thin and could benefit with more use cases that are allowed by the `periodictable` package.

**Describe the solution you'd like**
The [NIST Activation and Scattering Calculator](https://www.ncnr.nist.gov/resources/activation/) has extensive documentation that would be easy to integrate.

**Additional context**
A few useful cases not covered in our documentation but covered in the online calculator:

- Mass and isotopic densities in the chemical formulas (**_H2O@1_** -or- **_D2O@1n_**)
- Mole and mass fractions (**_78.2H2O[16] + 21.8H2O[18]_** -or- **_50%wt Co // Ti_**)
- Biomacromolecules ("code:sequence" where code can be 'aa', 'dna', or 'rna' e.g. **_aa:RELEELNVPGEIVESLSSSEESITRINKKIEKFQSEEQQQTEDELQDKIHPFAQTQSLVYPFPGPIPNSLPQNIPPLTQTPVVVPPFLQPEVMGVSKVKEAMAPKHKEMPFPKYPVEPFTESQSLTLTDVENLHLPLPLLQSWMHQPHQPLPPTVMFPPQSVLSLSQSKVLPVPQKAVPYPQRDMPIQAFLLYQEPVLGPVRGPFPIIV_**)

This came from a discussion with @katieweigandt

**Comment by butlerpd** [comment]
It may be useful to point to the online `periodictable` documentation on `readthedocs.io` https://periodictable.readthedocs.io/en/latest/. 

Also do these get too esoteric? and would it be useful to eventually provide a better GUI interface for some of the most common use cases such as mass fraction compositions?

This originated from a discussion with David Amelemah at the University of Sydney
