### ISSUE TITLE
Fitting Help Sometimes Displays Previous Model Documentation

### ISSUE THREAD

**Issue by krzywon** [SasView/sasview#2692]
**Describe the bug**
When the model category changes, the fitting Help button will continue to display the previous model until a new model is selected.

**To Reproduce**
1. Go to fitting and select a model category and then a model.
2. Change the category to a different category, clearing the model selection.
3. Click the 'Help' button.
4. The help for the previous model is displayed.

**Expected behavior**
When no model is selected, the fitting help should be displayed.

**SasView version (please complete the following information):**
 - Version: 5.0.6

**Operating system (please complete the following information):**
 - OS: Windows 10

**Comment by rozyczko** [comment]
self.kernel_module wasn't properly cleaned on category change. It is now.
