### ISSUE TITLE
Generate list of Official package versions (Trac #43)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#271]
A list of the exact version of every package used to generate the sansview release bundles, including the python version, needs to be generated and then kept updated.  all developments should be tested against this standard as that is what the user will actually get.

Migrated from http://trac.sasview.org/ticket/43
```json
{
    "status": "closed",
    "changetime": "2017-03-23T01:56:47",
    "_ts": "2017-03-23 01:56:47.368531+00:00",
    "description": "A list of the exact version of every package used to generate the sansview release bundles, including the python version, needs to be generated and then kept updated.  all developments should be tested against this standard as that is what the user will actually get.",
    "reporter": "butlerpd",
    "cc": "",
    "resolution": "fixed",
    "time": "2012-03-30T00:40:11",
    "component": "SansView",
    "summary": "Generate list of Official package versions",
    "priority": "minor",
    "keywords": "",
    "milestone": "SasView 2.2",
    "owner": "butler",
    "type": "task"
}
```

**Comment by butlerpd** [comment]
Trac update at `2012/05/06 14:55:16`: 
* **butlerpd** commented:

This is done for the Windows build.  We need to do the same thing for the Mac build (and maybe REL6 build?) before closing this ticket.


* **butlerpd** changed priority from "major" to "minor"

**Comment by butlerpd** [comment]
Trac update at `2012/05/06 15:38:30`: **butlerpd** changed milestone from "" to "SansView 2.2"

**Comment by butlerpd** [comment]
Trac update at `2012/06/11 11:41:15`: 
* **butlerpd** changed owner from "" to "butlerpd"
* **butlerpd** changed status from "new" to "accepted"

**Comment by butlerpd** [comment]
Trac update at `2012/08/16 00:34:25`: 
* **butlerpd** commented:

Believe this has been done.  A new exercise at some point (sooner than later might be good) of verifying that all packages are needed (and what exactly each is necessary for) would be good.  Meanwhile we will close this ticket.


* **butlerpd** changed resolution from "" to "fixed"
* **butlerpd** changed status from "accepted" to "closed"

**Comment by ajj** [comment]
Trac update at `2016/02/28 11:49:44`: **ajj** changed owner from "butlerpd" to "butler"
