### ISSUE TITLE
Need to review all uses of pop-up information and the information bar (Trac #44)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#272]
A full review of the use of pops for information/warning and the information bar needs to be made, and a consistent policy developed on when to use which venue (or when/if to use both). Items showing up in the info bar currently get recorded in a log.  Do the popups?  Pop ups can be annoying, but in many cases, if the user is expecting something to happen but nothing is because of some error, a popup is the correct solution.  extra information should be put on the info bar rather than constantly popping stuff at the user.

Migrated from http://trac.sasview.org/ticket/44
```json
{
    "status": "new",
    "changetime": "2017-01-17T13:05:47",
    "_ts": "2017-01-17 13:05:47.560664+00:00",
    "description": "A full review of the use of pops for information/warning and the information bar needs to be made, and a consistent policy developed on when to use which venue (or when/if to use both). Items showing up in the info bar currently get recorded in a log.  Do the popups?  Pop ups can be annoying, but in many cases, if the user is expecting something to happen but nothing is because of some error, a popup is the correct solution.  extra information should be put on the info bar rather than constantly popping stuff at the user.",
    "reporter": "butlerpd",
    "cc": "",
    "resolution": "",
    "workpackage": "SasView Admin",
    "time": "2012-03-30T00:44:23",
    "component": "SasView",
    "summary": "Need to review all uses of pop-up information and the information bar",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView WishList",
    "owner": "",
    "type": "task"
}
```

**Comment by butlerpd** [comment]
Trac update at `2012/05/06 16:01:24`: **butlerpd** changed milestone from "" to "WishList"

**Comment by butlerpd** [comment]
Trac update at `2015/01/30 01:09:40`: **butler** changed workpackage from "" to "SasView Admin"

**Comment by ajj** [comment]
Trac update at `2017/01/17 13:05:47`: **ajj** changed component from "SansView" to "SasView"

**Comment by ajj** [comment]
Is this still relevant for 5.0?

**Comment by lucas-wilkins** [comment]
> Is this still relevant for 5.0?

Indeed! Marked as stale.

**Comment by butlerpd** [comment]
agreed -- lets close it. Since I'm the author I'll just do that 😄
