### ISSUE TITLE
SasView setup error for developers 

### ISSUE THREAD

**Issue by AnitaZhang0526** [SasView/sasview#2724]
**To Reproduce**
1. Put the sasview repo in any path that has a folder name with more than two words (ex. a path like 'C\Users\Anita Zhang\sasview' will create the problem)
2. run `pip install -r build_tools/requirements.txt`
3. Error says "While generating .\src\sas\qtgui\Calculators\UI\DataOperationUtilityUI.py... Error: Could not create output file"
4. If you run as the administrator, the erorr turns tell you that it cannot find a file named "C\Users\Anita'
5. Issue can be worked around if the sasview folder is moved to a path with no compound folder name

**Expected behavior**
Should run the setup. Unfortunately, I didn't take screenshots of the actual error message, but hopefully there's enough info to figure out why this is happening.

**SasView version (please complete the following information):**
 - 6.0.0.a1

**Operating system (please complete the following information):**
 - OS: Windows 11

**Comment by jack-rooks** [comment]
Please also use this command to install the required packages (I have guessed where your anaconda folder is located as well as your environment name, please correct before using if it is wrong):
`pip install -r build_tools/requirements.txt --target="C:\Users\Anita Zhang\Anaconda3\envs\sasview_dev\Lib\site-packages"`

**Comment by jack-rooks** [comment]
From our discussion and my limited testing, it seems that this is not a problem with SasView, but with pip or a dependency (multiple occurrences of similar issues over the past 15+ years with various causes).
