### ISSUE TITLE
Version number is incorrect on Sasview 6.0.a1

### ISSUE THREAD

**Issue by Susyana** [SasView/sasview#2725]
**Describe the bug**
When installing Sasview 6.0a1 using the .exe file, the installer creates a folder named version 5.0.5.  When launching Sasview itself, the version it reports on the GUI is 5.0.6 (see printscreen)

![Capture](https://github.com/SasView/sasview/assets/53537909/102f8b95-da7b-4001-8708-720361707023)

**To Reproduce**
1. Go to https://github.com/SasView/sasview/releases/download/v6.0.0-alpha
2. Download the setupSasView-6.0.0-alpha-Win64.exe
3. Install on a Windows PC
4. The 'installation complete' message reports that version 5.0.5 is installed. 
5. When launching Sasview, the GUI reports that version 5.0.6 is installed.

**SasView version (please complete the following information):**
 - Version: [e.g. 5.0.4]

**Operating system (please complete the following information):**
 - OS: Windows 10 Pro

**Comment by krzywon** [comment]
Superseded by https://github.com/SasView/sasview/issues/2732
