### ISSUE TITLE
Sector slicer doesn't update properly when parameters changed

### ISSUE THREAD

**Issue by jack-rooks** [SasView/sasview#2726]
**Describe the bug**
Trying to update the number of bins used in the sector slicer for 2D data gives an error and does not function.

```Traceback (most recent call last): File "C:\Users\Jack\GitRepos\sasview\src\sas\qtgui\Plotting\SlicerModel.py", line 66, in setParamsFromModelItem self.setParams(params) File "C:\Users\Jack\GitRepos\sasview\src\sas\qtgui\Plotting\Slicers\SectorSlicer.py", line 275, in setParams self.right_line.update(phi=phi, delta=None, mline=self.main_line, File "C:\Users\Jack\GitRepos\sasview\src\sas\qtgui\Plotting\Slicers\SectorSlicer.py", line 384, in update self.theta = mline.alpha + self.phi AttributeError: 'LineInteractor' object has no attribute 'alpha'```

**To Reproduce**
1. Open SasView and look at the fitting panel that is open by default
2. Select a category and model (cylinder and cylinder was used for this)
3. Enable "2D view" in the options section at the bottom left of the fitting panel
4. Click "Calculate" then "Show Plot" at the bottom right of the window
5. Right click the 2D plot that was generated and click "Edit Slicer Parameters" and select the "Sector" slicer type from the dropdown
6. Change nbins to any value
7. See error

**Expected behavior**
The number of bins used for the slicer should update

**SasView version:**
 - 6.0.0a1 (main branch)

**Operating system:**
 - OS: Windows 10 Version 10.0.19045 Build 19045

**Comment by jack-rooks** [comment]
Note: new bug, not present in 5.0.5

**Comment by jack-rooks** [comment]
Also doesn't work when phi and delta_phi are changed in the slicer parameters, but not when done in the graph by dragging the lines

**Comment by jack-rooks** [comment]
May be related to #2636

**Comment by jack-rooks** [comment]
Fixed by [2100_2726_2752_Slicer-bugfixes](https://github.com/SasView/sasview/tree/2100_2726_2752_Slicer-bugfixes). Leaving this open for now as it has not been merged

**Comment by butlerpd** [comment]
All has now been merged so closing this ticket
