### ISSUE TITLE
Provide access to sub and superscripts and some symbols on plots (Trac #45)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#273]
It would be really good to be able to use super and sub scripts as well as some symbols such as angstom when typing labels on plots, including the axis labels in Batch plots

Migrated from http://trac.sasview.org/ticket/45
```json
{
    "status": "closed",
    "changetime": "2018-03-04T16:53:23",
    "_ts": "2018-03-04 16:53:23.368917+00:00",
    "description": "It would be really good to be able to use super and sub scripts as well as some symbols such as angstom when typing labels on plots, including the axis labels in Batch plots",
    "reporter": "butlerpd",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "Plotting/Graphing Enhancements",
    "time": "2012-03-30T00:46:20",
    "component": "SasView",
    "summary": "Provide access to sub and superscripts and some symbols on plots",
    "priority": "minor",
    "keywords": "",
    "milestone": "SasView 4.1.1",
    "owner": "butler",
    "type": "enhancement"
}
```

**Comment by butlerpd** [comment]
Trac update at `2012/05/06 15:54:22`: **butler** changed _comment0 from "it looks like this is possible with LaTex commands? or close to it?  If so need to verify and document -- including with a quick pop up help on the GUI?" to "1491656662446942"

**Comment by butlerpd** [comment]
Trac update at `2012/05/06 15:54:22`: 
* **butlerpd** commented:

it looks like this is possible with !LaTex commands? or close to it?  If so need to verify and document -- including with a quick pop up help on the GUI?


* **butlerpd** changed milestone from "" to "WishList"

**Comment by butlerpd** [comment]
Trac update at `2015/01/30 01:12:59`: **butler** changed workpackage from "" to "Plotting/Graphing Enhancements"

**Comment by ajj** [comment]
Trac update at `2017/01/17 13:05:47`: **ajj** changed component from "SansView" to "SasView"

**Comment by butlerpd** [comment]
Trac update at `2017/04/08 13:17:06`: 
* **butler** changed owner from "" to "butler"
* **butler** changed status from "new" to "accepted"

**Comment by butlerpd** [comment]
Trac update at `2017/04/08 13:17:38`: 
* **butler** commented:

This is not perfect but more or less works in many places now - certainly in the axis labels.  There are a few glitches but not worth fixing since it will be completely superceeded by the new Qt interface.  Thus am closing this one.  Once the new interface is up and running, new tickets will not doubt be generated.


* **butler** changed resolution from "" to "fixed"
* **butler** changed status from "accepted" to "closed"

**Comment by butlerpd** [comment]
Trac update at `2018/03/04 16:53:23`: **butler** changed milestone from "SasView WishList" to "SasView 4.1.1"
