### ISSUE TITLE
Fill in What's New boxes for release 6.0.0

### ISSUE THREAD

**Issue by lucas-wilkins** [SasView/sasview#2732]
The What's New box needs filling in for the 6.0.0 release.

**Comment by lucas-wilkins** [comment]
What's going in it?

**Comment by rozyczko** [comment]
This should possibly be automated by some action gathering info already present in the repo, possibly added during the pull request phase.

**Comment by lucas-wilkins** [comment]
Preferences, GSC changes, corfunc - anything else

**Comment by krzywon** [comment]
Items I would suggest to add for v6.0.0:

- Settings window
- New plotting features
- Corfunc refactor
- Generic Scattering Calculator features

Other potential items:

- Documentation window
- Orientation viewer
- (if included) Batch and 2D P(r)
- (if included) Custom fit models in GSC
