### ISSUE TITLE
Npts and Nsigma issue in polydisperse distributions

### ISSUE THREAD

**Issue by AnitaZhang0526** [SasView/sasview#2741]
**Describe the bug**
Parameters npts and nsigma do not seem to be used correctly. Only the default values (npts=35, nsigma=3) produce the expected results. Overriding those values currently creates wrong distributions and in turn results in wrong fittings on data. 
See examples in the screenshots below. It seems like if the last parameter changed is PD[ratio] instead of npts or nsigma, the distribution will just be plotted with default values (like in Figure 5), but if the last parameter changed is npts or nsigma, a completely wrong distribution with a seemingly random number of points will be generated.

**To Reproduce**
1. Go to any shape-dependent model with polydispersity option checked 
2. Changing npts and nsigma will produce errors in the shape of the distribution and the number of points used to plot the distribution. 
3. Click 'Compute/plot'

**Expected behavior**
The distribution should appear correctly based on nsigma with the number of points specified by npts.

**Screenshots**
Figure 1:
<img width="1127" alt="Screenshot 2024-01-18 104911" src="https://github.com/SasView/sasview/assets/90064279/4793297a-2807-4d5f-a614-ce23976649d5"> 
Figure 2:
<img width="1128" alt="Screenshot 2024-01-18 105124" src="https://github.com/SasView/sasview/assets/90064279/e2cae753-9f1a-4682-98ec-87aace8fb8f2">
Figure 3:
<img width="1128" alt="Screenshot 2024-01-18 105221" src="https://github.com/SasView/sasview/assets/90064279/76c30e80-94a8-4917-b00a-997fe0cec4a3">
Figure 4:
<img width="1128" alt="Screenshot 2024-01-18 105649" src="https://github.com/SasView/sasview/assets/90064279/355bd08c-ce67-48af-b8ed-bd99fac54148">
Figure 5:
<img width="1128" alt="Screenshot 2024-01-18 105843" src="https://github.com/SasView/sasview/assets/90064279/a786c254-084d-4304-898b-7ddd1672eb70">

**SasView version (please complete the following information):**
 - Version:6.0.0a1 

**Operating system (please complete the following information):**
 - OS: Windows 11

**Additional context**
@murphyryanp discovered this issue initially. We think the problem could be in the sasview repo or the sasmodels repo. In sasview, the most recent updates that can affect this are in FittingWidget.py. In sasmodels, it seems like there's an update to the direct_model.py that changes how npts is calculated, but unclear if it's really any different from the older version.

**Comment by caitwolf** [comment]
@butlerpd @krzywon I just ran across this bug myself in version 6.0.0b2 (Windows 10) during summer school. I was in the process of making a new issue then realized there was an existing one from Anita on the alpha version. I confirmed that this issue did not appear in 5.0.6.

**Comment by krzywon** [comment]
I think I finally found the issue. Any change to any polydispersity parameter (ratio, min, max, npts, nsigs) modifies the `width`/`PD[ratio]` value of the underlying model. The other values remain as the default values, regardless of what is shown in the table.

I hope to have a fix for this soon.
