### ISSUE TITLE
CORFUNC throws on data item deletion

### ISSUE THREAD

**Issue by rozyczko** [SasView/sasview#2757]
**Describe the bug**
The Corfunc perspective is incorrectly responding to the data deletion signal, even if the perspective is not active.

**To Reproduce**
1. Load a dataset while Fitting Perspective is up
2. Delete the dataset loaded
3. See error:

```
22:39:21 - ERROR: Traceback (most recent call last): File "C:\projects\sasview\src\sas\qtgui\Perspectives\Corfunc\CorfuncPerspective.py", line 279, in 
model_changed 
self.slider.extrapolation_parameters = self.extrapolation_parmameters
File "C:\projects\sasview\src\sas\qtgui\Perspectives\Corfunc\CorfuncSlider.py", line 221, in extrapolation_parameters
if self.find_parameter_problems(params) is None:
File "C:\projects\sasview\src\sas\qtgui\Perspectives\Corfunc\CorfuncSlider.py", line 84, in find_parameter_problems if params.data_q_min >= params.point_1:
AttributeError: 'NoneType' object has no attribute 'data_q_min'
```

**Expected behavior**
No exception shown

**SasView version (please complete the following information):**
 - Version: 6.0.0

**Operating system (please complete the following information):**
 - OS: Win10

**Comment by lucas-wilkins** [comment]
This is resolved.
