### ISSUE TITLE
Perspective changes leaving phantom windows

### ISSUE THREAD

**Issue by krzywon** [SasView/sasview#2789]
**Describe the bug**
When the active perspective is not in focus when switching from one perspective to another, the main widget window remains in the GUI.

**To Reproduce**
1. Load a data set and plot it.
2. Open a plot and give the plot focus.
3. Switch perspectives form any perspective to any other perspective.
4. The new perspective opens, but the outline of the previous widget remains open with no content.

**Expected behavior**
The previous perspective window should close.

**Screenshots**
![Screenshot 2024-01-22 at 21 50 19](https://github.com/SasView/sasview/assets/10947925/c7e3b1dc-b7c3-4585-8660-6d5a2f9e5d7f)

**SasView version (please complete the following information):**
 - Version: branches main and release_6.0.0

**Operating system (please complete the following information):**
 - OS: MacOS and Windows confirmed

**Comment by rozyczko** [comment]
Hasn't this been fixed already? `main` has the necessary line and according to git it's been there for 4 years, when Jeff fixed it.

**Comment by krzywon** [comment]
I think #2808 will close this, but I'm closing just to be sure.
