### ISSUE TITLE
SLD Calculator: Allow user to finish typing

### ISSUE THREAD

**Issue by krzywon** [SasView/sasview#2800]
**Describe the bug**
The SLD Calculator attempts to run a calculation with every keystroke in the formula box, regardless if the user is finished typing. This creates a lot of calls to the periodictable package, which throws an error everytime it recieves an invalid formula. This error is throw **with every keystroke**, causing a lot of error messages in the log file and console.

Error traceback:

> ERROR : sas.qtgui.Perspectives.Fitting.FittingWidget (FittingWidget.py:177) :: Traceback (most recent call last):
  File "src\sas\qtgui\Calculators\SldPanel.py", line 194, in recalculateSLD
    results = neutronSldAlgorithm(str(formula), float(density), float(neutronWavelength))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "src\sas\qtgui\Calculators\SldPanel.py", line 57, in neutronSldAlgorithm
    neutron_scattering(
  File "periodictable\periodictable\util.py", line 96, in _require_kwds
    return function(*args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^
  File "periodictable\periodictable\nsf.py", line 872, in neutron_scattering
    compound = formulas.formula(
               ^^^^^^^^^^^^^^^^^
  File "periodictable\periodictable\formulas.py", line 262, in formula
    chem = parse_formula(compound, table=table)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "periodictable\periodictable\formulas.py", line 882, in parse_formula
    return _PARSER_CACHE[table].parseString(formula_str)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyparsing\util.py", line 256, in _inner
    return fn(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyparsing\core.py", line 1197, in parse_string
    raise exc.with_traceback(None)
pyparsing.exceptions.ParseException: Expected end of text, found '0wt'  (at char 0), (line:1, col:1)

**To Reproduce**
1. Open the SLD Calculator Tool.
2. Type in the formula box.
3. With every key stroke, the formula is checked.
4. The above error is thrown every time the formula is invalid.

**Expected behavior**
One of two things should happen:
1. Catch the ParseException, and outline the box in red when the formula is invalid. This will outline the box even while the user is typing, which can be confusing.
2. Wait for the user to stop typing before running the calculator by [adding a timer that resets on user interaction](https://wiki.qt.io/Delay_action_to_wait_for_user_interaction). Not perfect, but will suppress some of the error messages.
3. Add a button to run the calculation. This changes existing behavior, which might cause confusion, but would also be more in line with the behavior of [the NIST activation calculator](https://www.ncnr.nist.gov/resources/activation/).

**SasView version (please complete the following information):**
 - Version: v5.0.6, v6.0.0a1, `main` branch

**Additional context**
This was found while testing https://github.com/pkienzle/periodictable/pull/65

**Comment by butlerpd** [comment]
I vote for option 3 and strongly oppose option 1 (lots of useless calls is something we should avoid like the plague IMO). I would add that it follows a similar changes made to the fitting page where changes are not registered till the user hits return to avoid lots of pointless calls.

**Comment by rozyczko** [comment]
`textEdited()` -> `editingFinished()`?

just change slots

**Comment by juliuskarliczek** [comment]
I tested a version with ui.editingFinished instead of ui.textEdited. I find it a little counter intuitive that the results are only calculated if one exits the molecular formula text box by clicking into another text box without having a dedicated calculate button. I think it is not possible to leave the text box without clicking another one. Clicking the rest of the gui panel will remain the cursor inside the text box.

Maybe a solution is, that there is a dummy calculation button? It would have no functionality in itself but it serves the purpose of leaving the text field, so that the results are calculated?

**Comment by rozyczko** [comment]
Hitting Enter or just tabbing out also triggers the signal and is a pretty common scenario. We use it in the Fitting parameters table and elsewhere

**Comment by juliuskarliczek** [comment]
Okay, good to know. In this case enter closes the sld calculator, because close is the pre selected button. Maybe remove the pre selection then?

**Comment by rozyczko** [comment]
Yes, this makes sense, since one would not necessarily expect Enter to close a widget. Good point.

**Comment by rozyczko** [comment]
The original idea for this design was to have the "simple" calculators behave similarly. SLD, Density/Volume, Slit Size, Kiessing - all of them use `textEdited` to provide immediate feedback to the user. This was OK, since the functionality is pretty obvious and the calculation time is negligible.

Only the more complex calculators/tools have a separate `Compute` button.

I agree that the constant calls to an external module (`periodictable`) and especially the verbosity of failure messages coming from it warrants a different approach for the SLD calculator.

Maybe adding a working `Compute` button would then be more sensible? Otherwise, we have not two but three different ways of interacting with the tools: `textEdited`, `editingFinished` and `onClick`.

**Comment by juliuskarliczek** [comment]
There is already a recalculate button implemented, but it is invisible right now

**Comment by rozyczko** [comment]
Ah! I see now.

When moving from Qt4 to Qt5, the validator used to check the chemical formulas got disabled,
```python
        # TODO: GuiUtils.FormulaValidator() crashes with Qt5 - fix
        #self.ui.editMolecularFormula.setValidator(GuiUtils.FormulaValidator(self.ui.editMolecularFormula))
```

So another option is to have a look at the FormulaValidator (we've now moved to Qt6) and see if it can be resurrected.
This would solve the original issue of querying `periodictable` with incorrect formulas.

**Comment by rozyczko** [comment]
> This means that all events, for which the sld is calculated here, should be disabled and only the recalculate button would stay?

I would say this is correct. Remove the `textEdited` signalling and only recalculate the values on `onClick`

**Comment by rozyczko** [comment]
Fixing the validator is probably of lesser importance now that the `Calculate` button is going to be enabled.

The Formula validator from GuiUtils is using `periodictable`, so no need to write our own regex :)

https://github.com/SasView/sasview/blob/a8253a9288ac2c1df0ae7af7bb192147bc5211bd/src/sas/qtgui/Utilities/GuiUtils.py#L737

**Comment by rozyczko** [comment]
It seems that ucommenting the validator in the SLD calculator + uncommenting the code in the validator itself in GuiUtils works very well, when `textChanged` signals are all disabled and the `Recalculate` button enabled...

**Comment by juliuskarliczek** [comment]
When activating the FormulaValidator, upon every key input the Error message
`QValidator::validate: Second tuple element is not convertible to unicode.`
is displayed.
I am not sure why this happens

**Comment by rozyczko** [comment]
Probably QValidator changed signatures. Try removing `pos` from return arguments on lines 749 and 753

**Comment by juliuskarliczek** [comment]
That fixed it, thanks
