### ISSUE TITLE
How to construct a model with DAB + HardSphere*Sphere*Polydispersity in sasview easily

### ISSUE THREAD

**Issue by isaxs** [SasView/sasview#2801]
**Is your feature request related to a problem? Please describe.**
To whom it may concern,
The sasview is helping us a lot in solving our sas data. 
We are evaluating the nanostructure of organic solar energy materials measured by GISAXS that is very similar as the model in the attached documents. Thanks to the SASview, we can simply use many independent models and their summings. 
In the attahed model, the authors used an added model by summing a DAB and a hard sphere model. I tried to construct this composite model with sasview as this model also can be used to interpret our data. But I failed. Herein, I can interpte how I constructed this model. First, I went to sasview "Fitting->Add/Multiply models"-->I multiply the sphere and hard sphere. The next step I should repeat the same operations to involve the polydispersity, but I failed as the polydispersity is not in the list. If we donot involve the polydisperisty, we also have to add the DAB mode. However, the user-defined sphere*hard sphere cannot be found in the list in "Add/Multiply models". Thus, I cannot combine the model sphere*hardsphere*polydispersity  and DAB.
How to solve this issue in the SASview easily. The only way is by programming in script in sasview? 
Thanks very much.

**Comment by smk78** [comment]
Dealt with via help@sasview.org
