### ISSUE TITLE
sasview release_6.0.0 does not start

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#2820]
**Describe the bug**
a bug was introduced when merging without proper testing by yours truly. "it is only a 2 line change what can possibly go wrong". the second line was missing a comma in line 37 of `src/sas/qtgui/convertUI.py` as pointed out by @krzywon in #2819.  The other problem was the missing import statement (insert line 7 presumably).

**Comment by lucas-wilkins** [comment]
I assume this can be closed @butlerpd - reopen if I'm wrong
