### ISSUE TITLE
new bugs introduced into GSC since 5.0.6

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#2831]
**Describe the bug**
as noted by @wpotrzebowski and @butlerpd in PR #2824 all the changes to the GSC seem to have introduce stability issues when using the drawing functionality. These were not visible until #2824 fixed the problem with draw not initializing so not clear how long this has been the case.  Moreover, the orientation graphic only shows the z or w vector not the other 2. 

**To Reproduce**
In order to see the second issue, just start any version of 6.0.0a1 and load the GSC. Only the blue arrow will show up in the sample, environment and beamline boxes.

For the second issue, one must use a version of 6.0.0a1 post merging of PR #2824.  Then load some data and start changing the orientation, move the box, load more data. At some point the data won't draw or will no longer rotate and eventually the whole of SasView could crash.  This seems to happen on both mac and OSX

**Screenshots**
![GSCPanelOrientations](https://github.com/SasView/sasview/assets/10955478/5114df1b-2dfb-435d-9a89-a5f3ebc8735d)

**SasView version (please complete the following information):**
 - Version: 6.0.0a1

**Operating system (please complete the following information):**
 - OS: Win10 and OSX

**Comment by lucas-wilkins** [comment]
I've also managed to crash it, but through the 3D plotting.
