### ISSUE TITLE
Additions to corfunc docs

### ISSUE THREAD

**Issue by lucas-wilkins** [SasView/sasview#2835]
From PR #2823 - @smk78 requested the following additions that go beyond typo fixing

*In corfunc-technical:*
**In Transformation:**

Could give the equation for Q*, I guess?

**In Interpretation:**
Can we give the definition of the Stribeck polydispersity

**Comment by smk78** [comment]
These 'enhancements' need to go in the docs for 6.0.0!

**Comment by lucas-wilkins** [comment]
This is done in 6.0.0
