### ISSUE TITLE
No OpenGL Radiobutton can be deselected

### ISSUE THREAD

**Issue by juliuskarliczek** [SasView/sasview#2841]
**Describe the bug**
No OpenCL Radiobutton under Toolbar/Fitting/GPU Options can be deselected. After deselecting it and clicking the test button, an error occurs

**To Reproduce**
1. Deinstall pyopencl package (if installed)
2. Open SasView
3. Open Toolbar/Fitting/GPU Options
4. Deselect No OpenCL Radiobutton
5. Click Test

**Expected behavior**
No OpenCL button stays selected even if you click it

**Screenshots**
![image](https://github.com/SasView/sasview/assets/165785299/4e5dffa5-7cc1-4b78-bafa-588a071fda93)
![image](https://github.com/SasView/sasview/assets/165785299/34caedb0-1482-4076-9b0e-63acdad7ca08)
![image](https://github.com/SasView/sasview/assets/165785299/8e68a118-7a7a-4259-93ee-0865a8374103)

**SasView version (please complete the following information):**
branch release_6.0.0
**Operating system (please complete the following information):**
 - OS: Win10

**Comment by butlerpd** [comment]
I believe that the tests you run are specifically to call the OpenCL driver selected. If so, then when no driver is selected that will obviously fail?  In which case the fix should be to no enable the test button unless a driver is selected?

**Comment by gonzalezma** [comment]
From what @juliuskarliczek showed me, I think this is simply a bad choice of the type of Qt button. According to the Qt doc: "Radio buttons typically present the user with a "one of many" choice", which is what we wanted in the GPU options menu in SasView 5.0.6 (choose between one or more GPU cards and No OpenCL). But as now we can have a single "No OpenCL" option in the Preferences --> GPU options menu, should the type of the button be changed to a QCheckBox ("Checkboxes are typically used to represent features in an application that can be enabled or disabled without affecting others")? Possible @rozyczko can confirm/complete/correct. Question: Is it possible to have more than one option in the GPU menu depending on the hardware (e.g. a list of GPU cards found)?

**Comment by rozyczko** [comment]
This radio button should NOT be deselectable.
Needs fixing.

**Comment by rozyczko** [comment]
Fixed in [2841-no-opengl-radiobutton-can-be-deselected](https://github.com/SasView/sasview/tree/2841-no-opengl-radiobutton-can-be-deselected)

**Comment by lucas-wilkins** [comment]
I'm sure I fixed this before...

**Comment by krzywon** [comment]
Fixed in release_6.0.0 by PR #2848. Closing
