### ISSUE TITLE
Need to compile a list of new contributors in version 6.0 to add to zenodo and the website for the release

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#2874]
To help ensure we don't miss anybody please add names that you think even **might** be appropriate to add.

* Kristian Lytje
* Brayden Miller
* Alex Zhang
* Lazono Dorian
* Jack Rooks
* Karolina Mothander
* Katie Weigandt (move from support)
* Yun Liu (move from support)
* Anika Stelhorn (move from support)

**Comment by lucas-wilkins** [comment]
To add, Ruben and Ellis

**Comment by lucas-wilkins** [comment]
Andrew Nilson

**Comment by smk78** [comment]
Has https://www.sasview.org/people/ been scraped?

**Comment by lucas-wilkins** [comment]
> Has https://www.sasview.org/people/ been scraped?

No. But it does need to be backed by something that can read by a computer easily and is version controlled with the sasview release.

**Comment by lucas-wilkins** [comment]
We probably need a "grants" file as well.

**Comment by gonzalezma** [comment]
Corrected in #2883, but just in case:
Lazono Dorian above should be Dorian Lozano
Nouhaila Agouzal
Julius Karliczek

**Comment by krzywon** [comment]
It's not clear to me this is 100% complete, despite #2943. I'm leaving it open for now

**Comment by wpotrzebowski** [comment]
build_tools/contributors.csv seems to be updated. However, the changes don't seem to be incorporated either with zenodo record or website. @krzywon, @lucas-wilkins  if I remember correctly the idea was to use csv file for automatic generation of zenodo record but I think we never managed to go that far? I think at this stage we should focus on updating zenodo record.
