### ISSUE TITLE
Drop Logger level required to force Log Explorer to pop up from Error to Warning

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#2875]
Currently, when the expected behavior is blocked because of an invalid user action the logger generates a warning level log message that goes to the log explorer as all log messages do.  This is not really an error in the program but since only error level log messages force the log explorer to pop up, the user may be confused.  Rather than make the warnings "errors," it was agreed to lower the level which will force the log explorer to pop up.  This should be done for 6.0 since there are several features depending on this.

**Comment by rozyczko** [comment]
Maybe adding this as a settings item would be better?
A list of checkboxes where the user selects which type of messages should trigger the Log Explorer visibility
By default it would be only Errors.

**Comment by gonzalezma** [comment]
But then we are almost back to the original behaviour. Most user will not change that and therefore will not be aware of any warning?

**Comment by butlerpd** [comment]
Probably the right answer is to **default** to include warnings but allow the user to opt out by changing the threshold. Then the fact the user is confused is their own fault not ours. Of course that doesn't mean they won't email us anyway...

In principle the point of the warning is to **warn** the user and I would argue at some level these are more important than popping up an error. If there is an error we know something went wrong and start hunting for the problem. Warnings are there to point out something did not go as expected even though we may not be aware of that.

**SUGGESTED PATH FORWARD**
For 6.0 we only fixt the installed default level for the log explorer to pop up to `warning`. This I believe is a trivial fix. We then ticket adding an option for the user to choose the level of message that triggers the log explorer popping up -- including "never"

**Comment by krzywon** [comment]
Now fixed in release_6.0.0 - closing
