### ISSUE TITLE
Splash and Icon for 6.0.0

### ISSUE THREAD

**Issue by lucas-wilkins** [SasView/sasview#2878]
Here's the splash screen and icon I've made for 6.0.0

![minimal_with_color_4](https://github.com/SasView/sasview/assets/9784906/cdfabdd3-9a21-4279-a97f-8ed149851ff4)

Icon will appear a little big here, its supposed to be small, hence the simplicity

![idea5-small](https://github.com/SasView/sasview/assets/9784906/7c36018d-5983-416e-8eda-3b74ad974b56)

**Comment by smk78** [comment]
Quite like the splash screen, but feel it lacks a 'scattering' element? Perhaps something like a beam scattering off one of the rhombohedra?

How will the icon appear when an icon? Will it be a white square with that inside?

**Comment by lucas-wilkins** [comment]
@smk78 that was meant to be a quote reply, must have mis-clicked on edit.

**Comment by wpotrzebowski** [comment]
Alternative ideas for splash screen. These are mock-ups (not final graphics) to be discussed at the developers call. 

The first one follows the concept of previous splash screens (4.x and 5.x)
![SasViewSplash](https://github.com/SasView/sasview/assets/4189922/297134a8-3553-4f4c-84d3-6698204f2aa5)

The second one is a completely different idea with minimalism being main driving force
![sasview_splash](https://github.com/SasView/sasview/assets/4189922/6adc3449-52d8-4ccc-90f0-2af3633f8cfe)

**Comment by lucas-wilkins** [comment]
The second one's OK, the first inherits all the problems of the previous ones.

**Comment by krzywon** [comment]
Here is a quick mock-up of an icon based off the minimalist splash screen by @wpotrzebowski. This also incorporates some of the color palatte of the existing icon.

![ball](https://github.com/SasView/sasview/assets/10947925/c59aa2fe-b2c6-44cf-a6b1-bbb9f25ba456)

**Comment by lucas-wilkins** [comment]
That's really not going to work well on most task bars. Needs to not be dark grey.

**Comment by lucas-wilkins** [comment]
I get that everyone hates my design ideas, but I did think quite a lot about what the requirements should be. If you look at other icons on your task bar, you'll see they nearly all have a small number of reasonably bold colours, and the ones that don't are hard to "read".

**Comment by wpotrzebowski** [comment]
To follow up splash screen and icons here are few ideas. 

Movie with splash screen
https://github.com/SasView/sasview/assets/4189922/bab51616-d3ea-4f6c-924c-cddfc64ddcf6

And few icon designs
![icon3](https://github.com/SasView/sasview/assets/4189922/fc8cd10e-f04e-41e9-b422-662e500598f0)
![icon4](https://github.com/SasView/sasview/assets/4189922/79c5b7b7-04bf-4dc4-88a2-b2531108b04c)
![icon5](https://github.com/SasView/sasview/assets/4189922/9ad801eb-1319-48d1-b5ff-22c3811a3ae5)

And this how the icons look at Mac
<img width="1512" alt="Screenshot 2024-05-31 at 08 02 23" src="https://github.com/SasView/sasview/assets/4189922/6f00ca90-ac29-4954-b05f-e323ab977cd8">

I am aware that on Windows taskbar is darker and therefore will try with lighter colors. My plan is to create PR with new splash screen and icon, so we can see them in action. 

On related note, it would nice to add a progress bar or some indication that something happens on splash screen.

**Comment by lucas-wilkins** [comment]
Here's some thoughts, big blocks of colour, high contrast, no thin lines. I wouldn't replace the line art with solid in splash screen, instead just make them match, would probably be pretty trivial with the last one here.

![render1](https://github.com/SasView/sasview/assets/9784906/3eb3c423-af46-4e61-92e5-fb08e87d4479)
![render2](https://github.com/SasView/sasview/assets/9784906/68d42a2a-2157-4129-b41e-575e6d52e908)
![render3](https://github.com/SasView/sasview/assets/9784906/645572bb-ab13-4371-aa6f-367841b98ed9)

**Comment by lucas-wilkins** [comment]
@wpotrzebowski How about this... go with the the top, more complex of splash screens, but use the font from the other one instead of the nasty monospace one and put the the text in the top left. Use the one of green/blue icons above, as they pick up some of the same colours.

**Comment by krzywon** [comment]
@lucas-wilkins, I think these are the best so far. I think the first one would be best from an icon point of view, but the last one would retain an element of the gray ball we currently have.

**Comment by lucas-wilkins** [comment]
![render4](https://github.com/SasView/sasview/assets/9784906/de02ff70-7e96-40b5-854b-9216b15fabdd)

Just trying to make it appear a bit flatter like the current icon...

**Comment by lucas-wilkins** [comment]
@krzywon I feel the green is very windows XP. Might try some more blue/purple variants

**Comment by lucas-wilkins** [comment]
"Flattened" version, a bit more modern graphically.

![render5](https://github.com/SasView/sasview/assets/9784906/2028553c-5267-4b90-8ae1-a6aecaa43f69)

**Comment by lucas-wilkins** [comment]
needs a bit of colour balancing still though.

**Comment by lucas-wilkins** [comment]
![render6](https://github.com/SasView/sasview/assets/9784906/b68a8914-bd76-43fd-9c24-7218cba9f925)

**Comment by smk78** [comment]
Personally I like the two-shades-of-blue variant (might be football related :-) ) but I could be persuaded by this last one above...

**Comment by krzywon** [comment]
My only concern with the blue icons are the similarities, especially in color scheme, to certain web browser icons.

**Comment by lucas-wilkins** [comment]
Subtly different...

![render7](https://github.com/SasView/sasview/assets/9784906/997e1ef7-5bee-4a79-b2aa-5194dc0a0b7d)

**Comment by wpotrzebowski** [comment]
I also like the latest and it looks ok on the Mac toolbar. Would it also work with inverse colors (gray outside, blue inside)?

**Comment by butlerpd** [comment]
Agreed to leave splashscreen as last shown but with slight change in the blue of the "icon" to be finalized at next meeting.  And Icon will be changed to the last one above.

**Comment by wpotrzebowski** [comment]
@lucas-wilkins  for me this looks ok. Do you think we should still go with vector graphics for the splash screen?
![splash_screen_med_lucas_icon](https://github.com/SasView/sasview/assets/4189922/66001448-0bc3-4de5-b7ff-e4897fc89c01)

**Comment by lucas-wilkins** [comment]
> @lucas-wilkins for me this looks ok. Do you think we should still go with vector graphics for the splash screen?

@wpotrzebowski Looks better than I thought it would. I'm happy if you are. 

I noticed you changed the background gradient to linear from radial, I think the original one looked better.

**Comment by wpotrzebowski** [comment]
@lucas-wilkins  thanks for spotting the issue with the background. I think I will submit PR with this one.
![splash_screen_med_lucas_icon](https://github.com/SasView/sasview/assets/4189922/a8d2f641-0093-41bf-898a-4d63f964917a)
