### ISSUE TITLE
Cannot change fitting optimizer

### ISSUE THREAD

**Issue by wpotrzebowski** [SasView/sasview#2889]
**Describe the bug**
The optimizer can be changed in dialog (either from the Preferences or Fit Algorithms tab) but it has no effect. It still runs the same optimizer as SasView started. 

**To Reproduce**
1. Run some fitting
2. Change Fit Algorithm
3. Check if anything changed in for example Fit Results 

**SasView version (please complete the following information):**
 - Version: 6.0.0a1

**Operating system (please complete the following information):**
 - OS: Mac OSX

**Comment by rozyczko** [comment]
Seems to be working on Windows - `release_6.0.0` branch

**Comment by butlerpd** [comment]
I will note that, as for @smk38, on my windows 11 machine it works flawlessly. I tried playing with turning the gpu option on and off as well and cycled through all optimizers but it just seemed to work.  I note the report was also from a windows 11 machine so it seems that the issue would have to be very localized to some specific setup? It will be hard to fix unless somebody can reproduce
