### ISSUE TITLE
DANSE web page needs updating for 2.1.1 release (Trac #61)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#289]
Need to update the DANSE web pages for this release including version number, link to right place, and addition of "new in this release."  This should be close to the last time these pages are used.  Need to figure out whether release 2.2 or 3.0 gets renamed to SasView and the website moved to a non DANSE branded link.

Migrated from http://trac.sasview.org/ticket/61
```json
{
    "status": "closed",
    "changetime": "2012-05-24T00:19:17",
    "_ts": "2012-05-24 00:19:17+00:00",
    "description": "Need to update the DANSE web pages for this release including version number, link to right place, and addition of \"new in this release.\"  This should be close to the last time these pages are used.  Need to figure out whether release 2.2 or 3.0 gets renamed to SasView and the website moved to a non DANSE branded link.",
    "reporter": "butlerpd",
    "cc": "",
    "resolution": "fixed",
    "time": "2012-05-06T15:03:38",
    "component": "SansView",
    "summary": "DANSE web page needs updating for 2.1.1 release",
    "priority": "major",
    "keywords": "",
    "milestone": "SansView 2.1.1",
    "owner": "butler",
    "type": "task"
}
```

**Comment by butlerpd** [comment]
Trac update at `2012/05/06 22:39:18`: 
* **butlerpd** changed owner from "" to "butlerpd"
* **butlerpd** changed status from "new" to "assigned"

**Comment by butlerpd** [comment]
Trac update at `2012/05/21 03:25:23`: **butlerpd** changed status from "assigned" to "accepted"

**Comment by butlerpd** [comment]
Trac update at `2012/05/21 03:25:57`: **butlerpd** commented:

Changes made and committed.  Website should get updated when we go live

**Comment by butlerpd** [comment]
Trac update at `2012/05/24 00:19:17`: 
* **butlerpd** commented:

Jae-Hie made some last minute easthetic changes but also reverted the link to the sphinx documentation.  This needs to be fixed to point to the autogenerated documentation for the version.  But that should be another ticket (target 2.2)


* **butlerpd** changed resolution from "" to "fixed"
* **butlerpd** changed status from "accepted" to "closed"

**Comment by ajj** [comment]
Trac update at `2016/02/28 11:49:43`: **ajj** changed owner from "butlerpd" to "butler"
