### ISSUE TITLE
numpy 2.0 has breaking changes for sasview, sasmodels, bumps etc.

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#2897]
`numpy 2.0` was released on Jun 16 and has a number of breaking changes such as `numpy.NaN` is no longer recognized (causes fatal error) and must be replaced with `numpy.nan`.

`requirements.txt` does not currently pin to a version so the short answer is probably to pin `numpy` to a version <2.0. However we should probably start working on compatibility? Question: How many dependencies will also have this problem?

**Comment by andyfaff** [comment]
See https://hackmd.io/B_zU26JfSI-703Xz85Ie_Q?view and https://github.com/numpy/numpy/issues/26191 for ecosystem compatibility of major packages.

**Comment by lucas-wilkins** [comment]
For the time being, if we pin numpy and leave everything else floating, pip should be able to pick compatible versions of these other dependencies.

**Comment by lucas-wilkins** [comment]
As for when we unpin, it also looks like most things are already updated, or not really numeric, with some questions remaining about:

* periodictable (probably fine)
* uncertainties
* bumps

**Comment by andyfaff** [comment]
Periodictable needs a PR merging, and a release.

**Comment by butlerpd** [comment]
need to check the uncertainties package for compatibility - most other other dependencies seem like they might be updated?

**Comment by butlerpd** [comment]
also check model marketplace.
