### ISSUE TITLE
Installer version number is wrong

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#2898]
A few minor issues:
* ~~the installer window is labelled `Setup SasView-5.0.5`. Not sure what happened to 5.0.6. but the label should be consistent with all the other version numbers. Can it be taken from the same place as other version numbers?~~ (Fixed in #2898)
* The sphinx documentation still shows the alpha1 version
* I do not see the orientation viewer help in the tools documentation (moved to https://github.com/SasView/sasview/issues/2905)
* The acknowledge popup shows version t.o.b1, DOI. Should that DOI be xxx for an alpha and beta? or are we really providing a different doi for these? (moved to https://github.com/SasView/sasview/issues/2906)

**Comment by krzywon** [comment]
> On Mac documentation doesn't seem to work?

#2813 - still not fully working, but I've been looking into it.

**Comment by lucas-wilkins** [comment]
> the installer window is labelled Setup SasView-5.0.5. Not sure what happened to 5.0.6. but the label should be consistent with all the other version numbers. Can it be taken from the same place as other version numbers?

I noticed this while looking at the installer definition files.

**Comment by krzywon** [comment]
> I do not see the orientation viewer help in the tools documentation.

#2660 - this is still an open issue as far as I know.

**Comment by krzywon** [comment]
> The sphinx documentation still shows the alpha1 version

This one is confusing me. The docs bundled with the beta release say 6.0.0b1 in them, but I also saw `6.0.0a1` in the bread crumbs when I first loaded the beta. It seems like there is a conflict with previous versions of docs in the `~/.sasview/doc` directory. I'll investigate more.

**Comment by smk78** [comment]
> * The sphinx documentation still shows the alpha1 version

I don't see this. The Documentation Window shows the correct version number.
![image](https://github.com/SasView/sasview/assets/10938679/d4888bb6-2cb6-4b43-ad3e-e83f985be9ae)

**Comment by krzywon** [comment]
I believe all of the issues here have either been addressed or moved to new issues. I'm closing for now
