### ISSUE TITLE
Email announcement of release needs to be prepared (Trac #62)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#290]
We need to prepare an email announcement for release 2.1.1.  Also need to update our mailing list and probably move it to sourceforge.  Sourceforge has a mailing list app.  Should make sure that we can control who can send to that list.  We could create another list for those who want a forum type list. 

Migrated from http://trac.sasview.org/ticket/62
```json
{
    "status": "closed",
    "changetime": "2012-05-28T16:13:35",
    "_ts": "2012-05-28 16:13:35+00:00",
    "description": "We need to prepare an email announcement for release 2.1.1.  Also need to update our mailing list and probably move it to sourceforge.  Sourceforge has a mailing list app.  Should make sure that we can control who can send to that list.  We could create another list for those who want a forum type list. ",
    "reporter": "butlerpd",
    "cc": "",
    "resolution": "fixed",
    "time": "2012-05-06T15:09:49",
    "component": "SansView",
    "summary": "Email announcement of release needs to be prepared",
    "priority": "major",
    "keywords": "",
    "milestone": "SansView 2.1.1",
    "owner": "butler",
    "type": "task"
}
```

**Comment by butlerpd** [comment]
Trac update at `2012/05/24 13:13:06`: 
* **butlerpd** changed owner from "" to "butlerpd"
* **butlerpd** changed status from "new" to "assigned"

**Comment by butlerpd** [comment]
Trac update at `2012/05/24 16:54:50`: **butlerpd** changed status from "assigned" to "accepted"

**Comment by butlerpd** [comment]
Trac update at `2012/05/28 16:13:35`: 
* **butlerpd** commented:

email done and sent on 5/27/2012 (a bit late but better than never as they say:-)


* **butlerpd** changed resolution from "" to "fixed"
* **butlerpd** changed status from "accepted" to "closed"

**Comment by ajj** [comment]
Trac update at `2016/02/28 11:49:43`: **ajj** changed owner from "butlerpd" to "butler"
