### ISSUE TITLE
Graph is not getting the correct axis 

### ISSUE THREAD

**Issue by XaelShan** [SasView/sasview#2904]
**Describe the bug**
When creating a graph of one of my data sets in the 6.0.0 beta, the y-axis range were not getting correctly scaled. This was before any manipulation of the graph range, zoom, or scale change. Simply creating a new graph/fitting would cause the axis scale to be incorrect. The y-axis is a lot more zoomed in than it should be.

Here is the file that isn't graphing properly:

**To Reproduce**
1. Go to Load data
2. Click on file named "hH_0D2O_20C" (file shared below, unable to upload as it is an ABS file)
https://drive.google.com/file/d/17I1IVp6_P6V05vKwOLX4F81sgXCMsQMq/view?usp=sharing
4. Click on "Create New" plot
5. See error
**The error in Fitting**
6. Send to Fitting
7. Put in any model
8. Press compute/plot or fit
9. See error

**Expected behavior**
A graph that correctly auto scales. 

**Screenshots**
**6.0.0b1** graph, where the issue is:
![image](https://github.com/SasView/sasview/assets/137302583/c8f7e758-3f24-4703-b8cb-59c2afe76d94)
**5.0.6** graph, to give context to what this graph is supposed to look like.
![image](https://github.com/SasView/sasview/assets/137302583/619cc60b-0b4f-4c0c-a12d-d9a7f29e02d0)

**SasView version (please complete the following information):**
 - Version: 6.0.0b1

**Operating system (please complete the following information):**
 - OS: Windows 10

**Additional context**
I went through the files with Paul Kienzle, and we found that in Plotter.py line 284, the default_x_range  #and default_y_range are being set using self.ax.get_xlim() and self.ax.get_ylim(), these are not getting the actual default ranges given by matplotlib. We put a self.ax.relim() and self.ax.autoscale() above line 284-285 and found that the scale is then fixed.

**Comment by lucas-wilkins** [comment]
Sounds like you fixed it. Do you want to push your changes?

**Comment by XaelShan** [comment]
> Sounds like you fixed it. Do you want to push your changes?

I worked with Paul Kienzle, and he argues that this isn't a valid fix. This would reset the plot every time create new or compute/plot was hit, which means any user shifts/zoom (or manual graph range changes) will be lost.

**Comment by lucas-wilkins** [comment]
@XaelShan - I've put in a PR that should fix this.

**Comment by XaelShan** [comment]
@lucas-wilkins Thank you!

**Comment by krzywon** [comment]
[hH_0D2O_20C.txt](https://github.com/user-attachments/files/16363045/hH_0D2O_20C.txt)

Here is the file that triggered this issue. Note - the file was originally had the `abs` file extension. It will still load as-is, but without some of the meta data.
