### ISSUE TITLE
Links in tutorial.rst don't resolve

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#2908]
**Describe the bug**
The links in tutorial.rst from Help > Tutorial don't resolve.

However, https://github.com/SasView/tutorials/pull/15 and https://github.com/SasView/tutorials/pull/14 also need merging and this will change the suffix of some of the filenames to _v6.

**Comment by smk78** [comment]
As an example.

Help > Tutorial. Documentation Viewer appears.

Select _Getting Started with SasView_. Nothing happens.

Right click on hyperlink and copy the address and get:
```
file:///C:/Users/<user>/.sasview/doc/6.0.0b1/build/html/_downloads/23535589a23be03b8dc873da8cc73adf/getting_started_with_sasview_v5.pdf
```

Copy this link into a web browser and hit return. It resolves! The file exists at that location.

NB: the file also exists at:
```
C:\<installation_folder>\doc\build\html\_downloads\23535589a23be03b8dc873da8cc73adf\getting_started_with_sasview_v5.pdf
```

But if you Edit the tutorials page in the DV you see instead:
```
:download:`Getting Started with Sasview <sasview/getting_started_with_sasview_v5.pdf>`
```

**Comment by smk78** [comment]
I suppose a quick-n-dirty fix would be to just add a sentence at the top of tutorial.rst to say "If these links do not appear to work, copy the link address and paste it into a file/web browser"...

**Comment by smk78** [comment]
Just trying the same thing in earlier versions of SasView, so not using the Documentation Viewer, all the way back to v5.0.0, and these links don't resolve when you click on them.

This suggests:
- it's not a Documentation Viewer thing
- it's not the current version of Sphinx

But I cannot believe these links have never worked; surely someone would have spotted that???

Weird!

**Comment by lucas-wilkins** [comment]
If its a built in window, this is probably because following external links needs to be enabled. I'll check.

**Comment by smk78** [comment]
It's a built-in window thing in 6.0.0, but in all v5.x versions a browser would have been spawned.

**Comment by smk78** [comment]
Help > Tutorials is now fixed. And handling the v6 tutorial naming can be done on the website after 6.0.0 is released.
