### ISSUE TITLE
corfunc-technical needs attention

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#2913]
**Describe the bug**
In corfunc-technical.rst:

- the Stribeck polydispersity needs defining
- there are some incorrectly formatted equations at the foot of the page

**Comment by lucas-wilkins** [comment]
Could have sworn I fixed this?

**Comment by smk78** [comment]
![image](https://github.com/SasView/sasview/assets/10938679/9d0ebec0-155a-40e2-952f-f8a4fb21081a)

**Comment by lucas-wilkins** [comment]
OK, so its always been like this. I can have a look.
