### ISSUE TITLE
Not apparent anything is happening when opening a project

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#2914]
**Describe the bug**
Opening a project with a lot of loaded data can take many seconds. During this time there is no indication that anything is happening, other that on Win you get the little revolving blue circle.

**Comment by krzywon** [comment]
Would a message in the status bar be enough, @smk78? You can view what I mean by installing from https://github.com/SasView/sasview/actions/runs/9911509649 once it is complete.

**Comment by lucas-wilkins** [comment]
@krzywon assigning you so its easier to see what is and isn't being worked on.
