### ISSUE TITLE
SasView 6.0.0 beta built with macOS-latest doesn't start on older Macs

### ISSUE THREAD

**Issue by wpotrzebowski** [SasView/sasview#2919]
**Describe the bug**
By default macOS-latest runner on github produces the installer in arm (Silicon architecture). If one tries to open it on the older mac the window below pops up and it doesn't start

![image](https://github.com/SasView/sasview/assets/4189922/0b737dac-1d7d-4b6e-b550-e5d8469562ca)

The currently tested approach to solve it is to bulid installer on macOS-13. However the question arises  if want to have two separate files for OSX (one for arm and one for ix86 release) or just keep x86 one. 

There may be some performace advantages of running arm installer on newer macs (with M* chips) but it needs to be tested.

If one switches from arm to x86 installer one needs to clear the compiled_models folder because otherwise SasView throws an error. (Going from x86 to arm shouldn’t be a problem because standard rosetta emulation should handle this).

**SasView version (please complete the following information):**
 - Version: [e.g. 6.0.0]

**Operating system (please complete the following information):**
 - OS: MacOS

**Additional context**
It may be worth checking if building on macos-13 runner will help with the debeye calculator provided by @klytje.

**Comment by krzywon** [comment]
The initial work seems to have helped, but I think having two separate installers for OSX would be advantageous. The `macos-13` distibution has an issue running on GPU, whereas the `macos-latest` does not suffer the same short-coming. If we can fix the GPU issue, I think a single distro would make sense, but until then we should have both. I have a fix for this locally (running two builds for Mac), but will wait to push to see if others have opinions. his would also remove the need to flush `compiled_models`.

Note - I tested the ausaxs work with this installation and compared it to the beta2 installation. Both run on an M2 and both throw the 'SasView closed unexpectedly closed' error.

**Comment by butlerpd** [comment]
Just to add a note from the NIST CNR summer school, while we did not have many macs, about half were running on an older architecture so there is a clear need for 6.0.0 to be able to run on older macs

**Comment by timsnow** [comment]
Most other macOS programs on the web now have an option for a dedicated Intel or Apple Silicon download (click on the downward arrow on the download link for VLC here: https://www.videolan.org/vlc/download-macosx.en_GB.html) so having two builds might be a bit messy but seems to be the accepted state of play at the moment.
