### ISSUE TITLE
Documentation Viewer - Make more accessible to all of GUI

### ISSUE THREAD

**Issue by krzywon** [SasView/sasview#2952]
The current implementation of the Documentation Viewer requires GuiManager to be in the parent stack for the widget that wants to use it. This can be cumbersome for many of the widgets. Ideally, a helper function should exist in GuiUtils to better enable the functionality that accepts the html Path and launches the Doc View window. This would allow a simple import and function call from within the onHelp (or similar) methods of those particular widgets.

This was highlighted in the following PR: https://github.com/SasView/sasview/pull/2925

**Comment by lucas-wilkins** [comment]
Just a thought, remember it needs to be callable from modal dialogues (which block the main window)
