### ISSUE TITLE
Duplicate content of the installation

### ISSUE THREAD

**Issue by rozyczko** [SasView/sasview#2957]
**Describe the bug**
Installed 6.0 alpha contains duplicated set of files

**To Reproduce**
1. Install 6.0 alpha
2. Go to the installation folder
3. Compare the content of `_internal` with the installation folder
4. See the `_internal` folder contains the same files as the main installation (except actual sasview.exe, uninst.exe etc)

**Expected behavior**
Not have dupes

**SasView version (please complete the following information):**
 - Version: 6.0 alpha

**Operating system (please complete the following information):**
 - OS: Win 10

**Additional context**
SasView directory size is now 2.22GB, of which `_internal` is 1.1 GB, so this effectively doubles the distribution footprint

**Comment by butlerpd** [comment]
This came up somewhere before. My understanding is that was partly due to changes in Pysintaller but has now been addressed in PR #2862 (Pysintaller part deux)?

**Comment by rozyczko** [comment]
Yes. The installer from https://github.com/SasView/sasview/actions/runs/9881138163 seems to fix this issue.
