### ISSUE TITLE
Hayter Penfold model gives incorrect result (Trac #70)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#298]
Isabelle reports some strange results when fitting a cylinder model with hayter penfold interaction using the first release 2.1.1. candidate compared to what she got with release 2.0.1.  Jae-Hie believes it comes from open MP as it acts correctly when that is turned off

Migrated from http://trac.sasview.org/ticket/70
```json
{
    "status": "closed",
    "changetime": "2016-10-08T13:57:35",
    "_ts": "2016-10-08 13:57:35.607607+00:00",
    "description": "Isabelle reports some strange results when fitting a cylinder model with hayter penfold interaction using the first release 2.1.1. candidate compared to what she got with release 2.0.1.  Jae-Hie believes it comes from open MP as it acts correctly when that is turned off",
    "reporter": "butlerpd",
    "cc": "",
    "resolution": "fixed",
    "time": "2012-05-15T12:09:35",
    "component": "SansView",
    "summary": "Hayter Penfold model gives incorrect result",
    "priority": "major",
    "keywords": "",
    "milestone": "SansView 2.1.1",
    "owner": "",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2012/05/16 12:44:12`: 
* **butlerpd** commented:

Mat found the problem which has been a long term problem in the model that multiprocessing just made a lot worse.  He notes that that model FAILS the unit tests about 50% of the time (and is the only one doing so).  With luck this simple fix will also fix that problem.

Jae-Hie says it now works and Isabelle who reported the problem also says it is working so we can now close this ticket 


* **butlerpd** changed resolution from "" to "fixed"
* **butlerpd** changed status from "new" to "closed"

**Comment by smk78** [comment]
Trac update at `2016/10/08 13:57:35`: **smk78** commented:

In changeset 3f9a18aa23905522f7850ed5f0992e7fd860c0fc:

```text
#!CommitTicketReference repository="sasview" revision="3f9a18aa23905522f7850ed5f0992e7fd860c0fc"
Updates to sasview/test/testdata_help.rst and sasview/test/README.txt
following some additional restructuring of /sasview/test by Jeff. See
#298 and #836
```
