### ISSUE TITLE
Fitting fails/hangs on some fits

### ISSUE THREAD

**Issue by tsole0** [SasView/sasview#2994]
**Describe the bug**
On some fits, the fitting will hang--i.e. will not return a fit. The fit button will remain in the red "Stop fit" state, the status bar remains as "Fitting started...", and no plots appear. When the `Stop fit` button is clicked, this error will appear:

```
15:19:38 - sas.qtgui.Perspectives.Fitting.FittingWidget - ERROR - Traceback (most recent call last):
  File "C:\Users\myUser\sasview\src\sas\qtgui\Perspectives\Fitting\FittingWidget.py", line 2111, in fitComplete
    res_list = result[0][0]
               ~~~~~~~~~^^^
IndexError: string index out of range
```

I have done some investigating as to the cause of the bug, and it seems that the Bumps `mpfit` function will hang consistently on step 8 of the fitting process in my specific context (mileage may vary on other data files/fitted parameters). It is unclear to me whether or not fitting parameters are being passed to bumps incorrectly from `FittingWidget.py` or if this is a fundamental error with Bumps. I'll note that this bugged behavior is distinctly different from the normal way Bumps exits a fit, in which the current state of Bumps is returned when the thread is cancelled. In the bug, `None` is returned when the thread exits with an error, which is what causes the visible error message upstream:

(src/sas/sascalc/fit/BumpsFitting.py, `run_bumps` method):
```
try:
    best, fbest = fitdriver.fit()
except Exception as exc:
    best, fbest = None, np.NaN
    errors.extend([str(exc), traceback.format_exc()])
finally:
    mapper.stop_mapper(fitdriver.mapper)
```

The specific reason why `fitdriver.fit()` returns an error turns out to be what I think is a bug in Bumps, but doesn't seem related to the reason as to why the process hangs (if fixed does not fix the underlying problem):

(bumps/mpfit.py)
```
catch_msg = 'calling '+str(fcn)
[self.status, wa4] = self.call(fcn, self.params, functkw)
if (self.status < 0):
    self.errmsg = 'WARNING: premature termination by "'+fcn+'"'
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
TypeError: can only concatenate str (not "method") to str
```

**To Reproduce**
1. Download 
[TMGel_RT4days_30C.txt](https://github.com/user-attachments/files/16418394/TMGel_RT4days_30C.txt)
2. Open SasView and Load data the file above
3. Send to Fitting
4. Category > Sphere
5. Model Name > Sphere
6. Structure factor > hayter_msa
7. Check scale, volfraction, charge, and concentration for fitting
8. Fit
9. Fitting will hang, press `Stop fit` to view error

N.B. The bug can also sometimes be triggered by hitting the 'Fit' and 'Stop fitting' buttons multiple times in rapid succession

NOTE: Only fitting with one parameter selected after selecting the structure factor will result in a correct fit. If you then select the other fitting parameters, fitting will proceed as normal

**Expected behavior**
SasView to run a fit correctly and allow the user to interrupt the fitting process

**Screenshots**
*Fitting hanging:*
![image](https://github.com/user-attachments/assets/e9da7349-da02-478b-82d6-ab9647e4e29f)
*Fitting canceled:*
![image](https://github.com/user-attachments/assets/dac51ec7-d914-4ef2-995c-cca0a73eff00)

**SasView version (please complete the following information):**
 - Version: 6.0.0b2, 5.0.6. From eye-witness accounts seems to have been present in previous versions.

**Operating system (please complete the following information):**
 - OS: Windows 10, also observed on MacOS Ventura

**Additional context | IMPORTANT**
Trying to fit with the same parameters but with a different model such as `core_shell_sphere` from start will cause a similar issue, but instead of hanging will automatically return the `results[0][0]` error.

**Comment by tsole0** [comment]
For anyone trying to investigate--I originally thought that #2751 was related (hence the branch [2751-fitting-errors](https://github.com/SasView/sasview/tree/2751-fitting-errors)), but I now believe that #2751 has the same surface manifestation (the `result` variable isn't returning what it should on a fit) but different underlying errors.

**Comment by butlerpd** [comment]
Identified during NIST CNR summer school hence the 6.0.0 label

**Comment by rozyczko** [comment]
One obvious check to be added is testing for `results` actually having the `[0][0]` item before querying for it.
If the info is not in the `results`, the fitting should be marked as a failure.
This would at least show a proper message about failed fitting and allow subsequent attemtps

**Comment by rozyczko** [comment]
... and addressed in [2994-fitting-failshangs-on-some-fits](https://github.com/SasView/sasview/tree/2994-fitting-failshangs-on-some-fits)
