### ISSUE TITLE
Batch panel output to CSV file broken again? (Trac #73)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#301]
Lionel reports that the 2.1.1 release candidate running on his windows machine (not mac) does not save to exel correctly.  basically he says it all loads into 1 cell (or one row ... not clear from his description but definitely no columns).  Further when he tried to copy and paste directly into excel it went into one cell.

It has been working for us so will need to try on a few more machines and if all good will need to extract more information from him.

Migrated from http://trac.sasview.org/ticket/73
```json
{
    "status": "closed",
    "changetime": "2012-07-13T23:59:14",
    "_ts": "2012-07-13 23:59:14+00:00",
    "description": "Lionel reports that the 2.1.1 release candidate running on his windows machine (not mac) does not save to exel correctly.  basically he says it all loads into 1 cell (or one row ... not clear from his description but definitely no columns).  Further when he tried to copy and paste directly into excel it went into one cell.\n\nIt has been working for us so will need to try on a few more machines and if all good will need to extract more information from him.",
    "reporter": "butlerpd",
    "cc": "",
    "resolution": "wontfix",
    "time": "2012-05-16T12:37:42",
    "component": "SansView",
    "summary": "Batch panel output to CSV file broken again?",
    "priority": "major",
    "keywords": "",
    "milestone": "SansView 2.1.1",
    "owner": "butler",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2012/05/24 16:49:09`: 
* **butlerpd** changed owner from "" to "butlerpd"
* **butlerpd** changed status from "new" to "assigned"

**Comment by butlerpd** [comment]
Trac update at `2012/05/24 16:49:18`: **butlerpd** changed status from "assigned" to "accepted"

**Comment by butlerpd** [comment]
Trac update at `2012/07/13 23:59:14`: 
* **butlerpd** commented:

Am closing this ticket as we still have no evidence there is an actual problem several months later.


* **butlerpd** changed resolution from "" to "wontfix"
* **butlerpd** changed status from "accepted" to "closed"

**Comment by ajj** [comment]
Trac update at `2016/02/28 11:49:43`: **ajj** changed owner from "butlerpd" to "butler"
