### ISSUE TITLE
Deleting data from the data explorer does not actually remove all vestiges thereof

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#3015]
**Describe the bug**
Deleting data from the explorer using the `Delete Data` button loads a pop up stating `This operation will remove the checked data from the data explorer. Do you want to continue?` Hitting yes removes it from the explorer and any plot that contains only that data (though it will not remove it from plots that contain other data as well). However it seems to keep a record in memory somewhere of at least some of at least the data title. But it is not accessible otherwise. Loading that dataset again from disk (since it is no longer retrievable) appends a [1] at the end of the file title.

However, Deleting the data from the explorer by right clicking on the data set name in the explorer (context menu) and then choosing `Delete` loads a pop up stating `This operation will remove the selected data sets and all the dependents from the data explorer. Do you want to continue?` Hitting yes in this case will behave exactly as before (including leaving the data plotted on a plot that contains other data). However, when reloading the data there is no new [x] appended to the title indicating that in this case all vestiges have been removed.  

Finally, loading a new project will load a pop up stating `This operation will remove all data, plots and analyses from SasView before loading the project. Do you wish to continue?`  This of course removes everything as it says and reloading one of the datafiles after this also does not append any [x]

**Expected behavior**
* language in the three modal popups should be normalized: All should say "removed from SasView" and both the delete options should say "and all dependents"
* The `Delete Data` button should behave like the context menu delete.
* All dependents should in fact be removed even it part of a plot that contains other data. 

This last may be harder so a first step could be the first two bullets?

**SasView version (please complete the following information):**
 - Version: 6.0.0b2

**Operating system (please complete the following information):**
 - OS: Windows

**Additional context**
Discovered as part the NIST CNR summer school

**Comment by krzywon** [comment]
The first issue, related to appending the [1] to the data, is new for 6.0 (in fact, it was fixed for some version of 5) and should be fixed for the release. The language in the popups could be fixed at the same time for the release version, but it matches the language used in 5.0.6, so only if it is an easy fix.

**Comment by rozyczko** [comment]
Selecting a dataset and pressing the `Delete Data` button is showing the described problem.
Right-clicking on the dataset and selecting `Delete` works properly (subsequent loads don't append [1])

**Comment by rozyczko** [comment]
Fixed the issue and unified the warning messages.

**Comment by butlerpd** [comment]
Is there a PR to test this with? Happy to review when ready. Sounds like it should be ready?

**Comment by rozyczko** [comment]
> Fixed the issue and unified the warning messages.

Whoops, looks like I forgot to actually make a PR...
Here it is now:

https://github.com/SasView/sasview/pull/3089
