### ISSUE TITLE
Changing polydispersity function also forces the width of that dispersity to be very large.

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#3016]
**Describe the bug**
NOTE: This may be fixed by PR #2991 as it sounds very related? That however needs to be verified before closing this ticket.

When turning on polydispersity (by checking the box in the fit panel) and then changing the polydisperse function to use (e.g. log normal), but touching nothing else (including leaving PD = 0 and NOT fittable) the curve immediately recalculates anyway as if the PD were something very large. Assuming data had already been fit without polydispersity turned on, hitting the fit button again will cause the polydisperse parameter (the whose dispersity function was changed, e.g. radius) to get much smaller as if a HUGE PD is being applied!!  Changing back to Gaussian with a PD of 0 still acts as if it now has a huge PD but now on the Gaussian distribution. However, turning on Polydispersity but doing NOTHING to the default distribution will fit normally,

This was tested with both the SDS, and apoferritin data in the 1D data examples and both the Schulz and Log Normal distributions were tried (besides the Gaussian).

**To Reproduce**
1. Load some data (e.g. apoferritin)
2. choose a model and fit (core shell for apoferritin)
3. Fit the data
4. Turn on polydispersity
5. Got to the polydisperse tab and choose a new distribution from the dropdown (e.g. the radius for apoferritin) - Gaussian is the default distribution
6. See the curve change (note it should NOT change until PD is something >0)
7. Click fit again. The radius will now look MUCH smaller as expected if the radius PD is very large
8. Changing back to a Gaussian distribution and try fitting again
9. The fit still has a huge PD

**Expected behavior**
PD should remain as set independently of choosing a different distribution. This means that visually nothing at all should happen when choosing a new distribution and the fits should not change between no polydispersity and a PD of 0 on the polydispersity. 

**SasView version (please complete the following information):**
 - Version: 6.0.0b2

**Operating system (please complete the following information):**
 - OS: Windows

**Additional context**
Identified during the NIST CNR summer school

**Comment by krzywon** [comment]
This is **not** fixed by #2991 and must remain open.

**Comment by krzywon** [comment]
A bit of debugging tells me the issue seen in #2991 is similar to the one here. The fittable params are setting `<param>.width` to each of the PD values, so the resulting, calculated PD width ends up being the value from the `npts` column, which is typically large.

Working on this now.
