### ISSUE TITLE
Verify that constrained simultaneous fitting provides FISH level constraint options (Trac #74)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#302]
We need to verify that !SansView's constrained simultaneous fitting does allow the type of complex constraints that FISH allows.  It seems that it does but this need to be documented and then perhaps some enhancements made to the !SansView GUI to make the whole exercise more intuitive to the user

Migrated from http://trac.sasview.org/ticket/74
```json
{
    "status": "closed",
    "changetime": "2015-11-22T01:58:03",
    "_ts": "2015-11-22 01:58:03.199736+00:00",
    "description": "We need to verify that !SansView's constrained simultaneous fitting does allow the type of complex constraints that FISH allows.  It seems that it does but this need to be documented and then perhaps some enhancements made to the !SansView GUI to make the whole exercise more intuitive to the user",
    "reporter": "butlerpd",
    "cc": "",
    "resolution": "obsolete",
    "workpackage": "SasView Admin",
    "time": "2012-05-16T13:27:23",
    "component": "SasView",
    "summary": "Verify that constrained simultaneous fitting provides FISH level constraint options",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 3.1.0",
    "owner": "butler",
    "type": "task"
}
```

**Comment by butlerpd** [comment]
Trac update at `2012/06/11 11:39:59`: **butlerpd** changed status from "new" to "accepted"

**Comment by butlerpd** [comment]
Trac update at `2012/08/16 00:29:39`: 
* **butlerpd** commented:

Pretty sure that first part is doable but need to go through exercise.  Do not have enough manpower to do this release.  Move to 3.0


* **butlerpd** changed milestone from "SansView 2.2" to "SansView 3.0.0"

**Comment by butlerpd** [comment]
Trac update at `2012/12/05 15:11:19`: **butlerpd** changed component from "SansView" to "SasView"

**Comment by butlerpd** [comment]
Trac update at `2013/08/31 18:37:13`: **butler** changed milestone from "SasView 3.0.0" to "SasView Next Release"

**Comment by butlerpd** [comment]
Trac update at `2015/01/30 02:00:09`: 
* **butler** commented:

Suspect this is now obsolete and we should move on.  I think we  know that the complex constraints ARE allowed except for the ability to reparameterize the model (e.g. substitute fraction of solvent for SLD).  This later would be nice to have and could be added as a fitting redesing ticket.


* **butler** changed workpackage from "" to "SasView Admin"

**Comment by butlerpd** [comment]
Trac update at `2015/02/01 22:57:50`: 
* **butler** commented:

This is obsolete now that Richard (FISH author) has joined developer team and that so many changes have happened and are planned.  The ability to reparameterize the model is still something to be done -- make a separate ticket


* **butler** changed resolution from "" to "obsolete"
* **butler** changed status from "accepted" to "closed"

**Comment by butlerpd** [comment]
Trac update at `2015/11/22 01:58:03`: 
* **butler** changed description from "We need to verify that SansView's constrained simultaneous fitting does allow the type of complex constraints that FISH allows.  It seems that it does but this need to be documented and then perhaps some enhancements made to the SansView GUI to make the whole exercise more intuitive to the user" to "We need to verify that !SansView's constrained simultaneous fitting does allow the type of complex constraints that FISH allows.  It seems that it does but this need to be documented and then perhaps some enhancements made to the !SansView GUI to make the whole exercise more intuitive to the user"
* **butler** changed milestone from "SasView Next Release +1" to "SasView 3.1.0"

**Comment by ajj** [comment]
Trac update at `2016/02/28 11:49:43`: **ajj** changed owner from "butlerpd" to "butler"
