### ISSUE TITLE
SESANS integration discussion (Trac #75)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#303]
Talk to Rob Dagliesh about possibility of SESANS fitting integration.  This could be a real opportunity as in principle one might want to model SESANS and SANS data simultaneously.  Once we figure out what/how/when (i.e timeline needs) a new enhancement ticket will be made with either a 3.0 release target or higher.

Migrated from http://trac.sasview.org/ticket/75
```json
{
    "status": "closed",
    "changetime": "2013-08-31T02:06:33",
    "_ts": "2013-08-31 02:06:33.340632+00:00",
    "description": "Talk to Rob Dagliesh about possibility of SESANS fitting integration.  This could be a real opportunity as in principle one might want to model SESANS and SANS data simultaneously.  Once we figure out what/how/when (i.e timeline needs) a new enhancement ticket will be made with either a 3.0 release target or higher.",
    "reporter": "butlerpd",
    "cc": "",
    "resolution": "fixed",
    "time": "2012-05-16T13:30:42",
    "component": "SasView",
    "summary": "SESANS integration discussion",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 3.0.0",
    "owner": "butler",
    "type": "task"
}
```

**Comment by butlerpd** [comment]
Trac update at `2012/07/18 13:02:40`: 
* **butlerpd** changed milestone from "SansView 2.2" to "SansView 3.0.0"
* **butlerpd** changed summary from "SESANS integration" to "SESANS integration discussion"

**Comment by butlerpd** [comment]
Trac update at `2012/07/18 13:02:58`: **butlerpd** changed status from "new" to "accepted"

**Comment by butlerpd** [comment]
Trac update at `2012/12/05 15:11:40`: **butlerpd** changed component from "SansView" to "SasView"

**Comment by butlerpd** [comment]
Trac update at `2013/08/31 02:06:33`: 
* **butler** commented:

The next step of this has been taken over by Andrew Jackson who is in touch both with Delft AND ISIS on this.  Is waiting for the change in the C models changes as that would make it MUCH easier to implement. This ticket is closed and we can open a new one when that  becomes appropriate.


* **butler** changed resolution from "" to "fixed"
* **butler** changed status from "accepted" to "closed"

**Comment by ajj** [comment]
Trac update at `2016/02/28 11:49:44`: **ajj** changed owner from "butlerpd" to "butler"
