### ISSUE TITLE
Installer fails to install properly in existing SasView folder

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#3030]
**Describe the bug**
When installing SasView from the installer on windows, the installer suggests a folder to install to.  Currently if that folder already exists the user is given zero warning (see #3029). However if the user chooses a different folder and that one exists, a warning is flagged asking if the user really wants to continue.

**PROBLEM STATEMENT**
In either case, if the exiting folder contains an older SasView version, the new install will not work.
Since 6.0.0b2 has a different icon it can be noticed that the saview.exe icon is the old one not the one for the new purportedly installed version.  It is not clear why this is happening but suspect that instead of deleting the content of the folder only certain files are replaced? or maybe none and only new files (with names that don't already exist) are installed?  Whatever the case it would appear that some mismatch of the old and the new are co-existing making the combination not operational?

**To Reproduce**
See #3029  for an example

**Expected behavior**
It should work in the folder it installed to. I would guess it should delete the contents of the folder (or the whole folder itself) and then install everything?

**SasView version (please complete the following information):**
 - Version: 6.0.0b2

**Operating system (please complete the following information):**
 - OS: Windows 10

**Additional context**
Discovered as part of the NIST CNR summer school. This was a universal problem for all windows students as they were specifically instructed to install both versions.

**Comment by krzywon** [comment]
Do we want to uninstall existing versions if we install in the active directory? That is possible using pyinstaller.

**Comment by butlerpd** [comment]
I would argue that the answer would be yes but only after warning the user this will happen, but it should never install into a directory that is not empty so if the user responds no the install should abort .. or ask for a new directory?
