### ISSUE TITLE
Phi and theta stuck at zero in 2D theory calculations

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#3053]
**Describe the bug**
When plotting oriented 2D scattering patterns from theory models, setting either theta or phi to 0 at any point, disables that parameter. Any additional changes to those angles are not updated in the simulated data images. This makes it difficult to manually fit. It is not clear (and hard to test) if the same would happen if the fitting algorithm sets one of those values to zero which would be extremely problematic.

**To Reproduce**
1. create a theory model for any anisotropic shape (e.g. cylinder) and click the 2D box before plotting
2. change angles theta and phi (and psi for prism models)
3. Now set one to zero
4. Try to move off of zero
5. Pattern does not change from that at 0

**Expected behavior**
the plot (and underlying theory data) should recalculate with the new angel and not use zero as being unchangeble.

**SasView version (please complete the following information):**
 - Version: 6.0.0b2

**Operating system (please complete the following information):**
 - OS: Windows 10

**Additional context**
Identified during the NIST CNR summer school and thus labelled 6.0.0 release as agreed - However, whether this is a longer standing issue has yet to checked

**Comment by krzywon** [comment]
This issue is present in v5.0.6. In order to prevent scope creep, this should not be fixed for v6.0.0.

**Comment by davidnwobi** [comment]
This also happens for other parameters besides the angle. I've seen the same behaviour with the parameters of the cylinder and ellipsoid models in the 1D case. It seems to be a more general issue with all the parameters; in this case: sld, sld_solvent, radius and solvent.

**Comment by smk78** [comment]
Retested using https://github.com/SasView/sasview/actions/runs/10638002500 on W10/x64.
The issue described above appears to be fixed and the 2D pattern changes as you wouuld expect, even after setting one or other of theta or phi to 0.

**Comment by rozyczko** [comment]
If any of the non-magnetic parameters is included in the fit, the magnetic parameters do get optimized. However, the error still remains 1e8, which is concerning.
