### ISSUE TITLE
Full Debye calculator hangs

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#3055]
**Describe the bug**
Probably related to #3054, depending on the PDB file loaded into the GSC, the full Debye computation can either be very fast, or hang (no errors thrown).  Two levels of hanging have been observed: In one case it hangs after it seems to have started in the sense that the compute button changes to an apparently active cancel button, but pressing cancel has no effect. In the other case, the failure happens before the cancel button appears and the window is locked with the compute button grayed out. Note that the hanging has only been seen in files that generated warnings PLUS a traceback error.

**To Reproduce**
Using the data provided in #3054, use the data that throws a single traceback to observe the first behavior. The file that produces two traceback errors will lead to the second behavior. 

**Expected behavior**
If the calculator is fed a malformed file an exception should be raised and clean exit from the code executed. The user should then be provided with the exception error.

**SasView version (please complete the following information):**
 - Version: 6.0.0b2

**Operating system (please complete the following information):**
 - OS: Windows 10

**Additional context**
Identified during the NIST CNR summer school and thus tagged for 6.0.0 release as agreed. However whether this is a pre-existing problem has not yet been verified.

**Comment by butlerpd** [comment]
As discussed in the comment on #3054, this remains a problem for 2 of the examples loaded in that issue but that is because those files don't adhere to the current PDB v3.3 standard.

We could probably be more forgiving if using an industry standard package for PDB reading. In the meantime, the solution to this issue should be to capture the errors (they throw a ton of warnings and errors) and fail to load an SLD object altogether and send a message to the log that the pdb does not match the v3.3 standard definition. This would remove the problem of later hanging when pressing compute while giving more useful (and less verbose) feedback to the user.

**Comment by krzywon** [comment]
Looking at this issue and #3054, both are present in v5.0.6, both are fairly complex and could require a lot of work on the PDB reader. I suggest we not include these issues in the v6.0.0 release unless a clean fix can be found soon.

**Comment by butlerpd** [comment]
Sorry if I didn't wrap back on these. Basically I agree. Best I can tell our current implementation, as fixed by @lucas-wilkins should read  any PDB that conforms to the 3.3 standard (claimed to be what should be used by the PDB folk themselves) without problem, though of course missing atoms, like hydrogens, we say, as I believe we should but biologist would differ, is the user responsibility.  There are tools for adding hydrogens if so desired.

The whole section on `CONECT` however could be removed as we never use that information. We are only interested in atom position and identity (I also checked anyway and was not able to find any place it was used).  Only `ATOM` lines are relevant to the calculator (the whole `HETATM` is another can of worms though my reading of the current standard is again that those should not matter so we should be good - these are "atoms NOT part of the polymer" which I take to mean solvent and salts etc).

It is also not clear to me why the first check in the reader for a number in the first position exists. That should not be possible with the current specifications. It may be a vestige from a previous version of the standard? In which case it might catch some currently "non-compliant" formats? It causes no harm so we could leave that there "just in case."

**Comment by butlerpd** [comment]
However, the hanging is caused by the fact that, for reasons beyond me, failures are all caught by exceptions and send error messages to the console but STILL 
```python
return output
```
instead of 
```python
return None
```
This last is only returned if the top level try except fails. I would argue that adding that after the `except` to the  the to SLD call (after line1242 in sas_gen.py  https://github.com/SasView/sasview/blob/main/src/sas/sascalc/calculator/sas_gen.py)
```python
except Exception
    self.logger.warning("Warning: set the sld of %s to zero"% atom_name)
    sld_n.append(0.0)
```
and also after the fail to read the line `except`
```python
 except Exception as exc:
    self.logger.error(f"Failed to read line: {line}")
    self.logger.exception(exc)
```
would probably fix the hanging problem (or at least the vast majority of them). This should be fairly trivial to implement (adding two lines I think?)

**Comment by krzywon** [comment]
Thanks, @butlerpd, for the suggestions. That is something we might be able to implement for the release.

**Comment by lucas-wilkins** [comment]
Close?

**Comment by krzywon** [comment]
> Close?

The bad files are no longer loadable, so this should be resolved. I think yes at this point. If the issue returns, we can always open a new issue.
