### ISSUE TITLE
The "what's new" page could use a different graphic

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#3058]
In the “preferences” page of the "what's new" window, an image of the new display settings would be much more useful/impactful than the current optimizer image. As mentioned in #3057, that and the GPU options are not new at all ... they have just been collected into the settings.

**Comment by lucas-wilkins** [comment]
The web viewer is pretty finnicky. You have to make sure your images have the right width, or it will alias them. Copy the width from the others.
