### ISSUE TITLE
Link Sphinx doc for ver 2.1.1 to link on web page (Trac #79)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#307]
Thanks to Mat we now autogenerate new sphinx documentation.  However there is the question of how to freeze the release version and make it  the link pointed to by the release pages.  That was left to be resolved later but now should be addressed.

Migrated from http://trac.sasview.org/ticket/79
```json
{
    "status": "closed",
    "changetime": "2013-08-31T02:04:31",
    "_ts": "2013-08-31 02:04:31.818491+00:00",
    "description": "Thanks to Mat we now autogenerate new sphinx documentation.  However there is the question of how to freeze the release version and make it  the link pointed to by the release pages.  That was left to be resolved later but now should be addressed.\n",
    "reporter": "butlerpd",
    "cc": "",
    "resolution": "fixed",
    "time": "2012-05-24T00:22:57",
    "component": "SasView",
    "summary": "Link Sphinx doc for ver 2.1.1 to link on web page",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 3.0.0",
    "owner": "butler",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2012/05/24 16:56:09`: 
* **butlerpd** changed owner from "" to "butlerpd"
* **butlerpd** changed status from "new" to "assigned"

**Comment by butlerpd** [comment]
Trac update at `2012/05/24 16:59:14`: **butlerpd** changed status from "assigned" to "accepted"

**Comment by butlerpd** [comment]
Trac update at `2012/12/05 14:47:49`: 
* **butlerpd** commented:

Have agreed to place release version of sphinx docs in subdirectory of public web pages with move to SasView.  Stub exists but need to put the documentation there.


* **butlerpd** changed component from "SansView" to "SasView"
* **butlerpd** changed milestone from "SasView 2.2" to "SasView 3.0.0"
* **butlerpd** changed priority from "minor" to "major"

**Comment by butlerpd** [comment]
Trac update at `2013/08/31 02:04:31`: 
* **butler** commented:

Andrew Jackson and then Mathieu Doucet fixed this much more elegantly.  Jenkins server now has a build job that builds the docs at the same time as the package.  For release just need to move the same version of the docs to a specific location... if that is desired.


* **butler** changed resolution from "" to "fixed"
* **butler** changed status from "accepted" to "closed"

**Comment by ajj** [comment]
Trac update at `2016/02/28 11:49:44`: **ajj** changed owner from "butlerpd" to "butler"
