### ISSUE TITLE
Need to update SLD documentation

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#3080]
PR #2986 fixes the problem with not respecting the density the user inputs.  This was noted as an issue in the documentation and should now be removed. This should be done as soon as possible after the above PR is merged

**Comment by krzywon** [comment]
Would it make sense to include this in the original PR?

**Comment by butlerpd** [comment]
Hummm ... just reading your changes which actually already include changes to the documentation. I'm reading them now.

**Comment by butlerpd** [comment]
Closing this as something already started in the above PR - though not complete yet I don't think. Still that is where it should be finalized and this is now redundant
