### ISSUE TITLE
Merge README and release_notes (Trac #82)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#310]
We have agreed to move to README.txt rather than release_notes as sourceforge recognizes the readme in a special way and makes it easily availalbe.  We need to make sure that README is uptodate with latest from release_notes and then remove release notes

Migrated from http://trac.sasview.org/ticket/82
```json
{
    "status": "closed",
    "changetime": "2012-06-07T03:01:27",
    "_ts": "2012-06-07 03:01:27+00:00",
    "description": "We have agreed to move to README.txt rather than release_notes as sourceforge recognizes the readme in a special way and makes it easily availalbe.  We need to make sure that README is uptodate with latest from release_notes and then remove release notes",
    "reporter": "butlerpd",
    "cc": "",
    "resolution": "fixed",
    "time": "2012-05-24T16:53:39",
    "component": "SansView",
    "summary": "Merge README and release_notes",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 2.2",
    "owner": "butler",
    "type": "task"
}
```

**Comment by butlerpd** [comment]
Trac update at `2012/05/24 16:53:59`: **butlerpd** changed status from "new" to "accepted"

**Comment by butlerpd** [comment]
Trac update at `2012/06/07 03:01:27`: 
* **butlerpd** commented:

Done -- will only need to be updated for next release


* **butlerpd** changed resolution from "" to "fixed"
* **butlerpd** changed status from "accepted" to "closed"

**Comment by ajj** [comment]
Trac update at `2016/02/28 11:49:44`: **ajj** changed owner from "butlerpd" to "butler"
