### ISSUE TITLE
Possible problems with structure_factor_mode

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#3101]
**Describe the bug**
Testing actions/runs/10638002500 build for @krzywon in reviewing https://github.com/SasView/sasview/pull/3100 I'm seeing some odd behaviour with P@S models. But it looks like the behaviour is there in the 6.0.0b2 release and even the 5.0.6 release, so is likely not introduced by the PR and has (worryingly) been hanging around for a while.

This is with the L-M optimizer (I've not tested other optimizers).

When it happens you will have clicked Fit and then not seen anything happen! You wait a while and then click Stop Fit. This returns focus to you but one or more of the following may be observed:

- a nonsensical radius_effective parameter; eg, nan
- the Log Explorer reports something like ERROR: Fitting failed: Traceback (most recent call last): File "sas\qtgui\Perspectives\Fitting\FitThread.py", line 79, in compute File "sas\qtgui\Perspectives\Fitting\FitThread.py", line 19, in map_apply File "sas\qtgui\Perspectives\Fitting\FitThread.py", line 16, in map_getattr File "sas\sascalc\fit\BumpsFitting.py", line 284, in fit AssertionError
- the Log Explorer reports other parameters as nan

But thereafter, although you can change parameter values, tick/untick boxes, clicking Fit has no effect; in essence, that Fit Page is 'dead'.

I think the structure_factor_mode setting may be implicated?

**To Reproduce**
1. Load some data (eg, the 2% SDS)
2. Create an ellipsoid@hayter_msa model
3. Try fitting it

**Expected behavior**
Fitting should proceed and the Fit Page should not go 'dead' no matter the parameter/combo box settings.

**Screenshots**
![image](https://github.com/user-attachments/assets/6072da02-3139-43b2-91de-ec99249308c5)
Clearly, in this example, that combination of polar & equitorial radii should not generate that equivalent_spherical_radius.

**SasView version (please complete the following information):**
Likely most v5.x and all v6.x

**Operating system (please complete the following information):**
W10/x64

**Comment by krzywon** [comment]
Are you sure this isn't an issue with the heyter-msa? Low concentrations cause an instability in the calculation: https://github.com/SasView/sasmodels/issues/143#issuecomment-478234393

**Comment by smk78** [comment]
Thanks for the reminder about that issue from 5 years ago, @krzywon ! It might explain what I'm seeing but I want to play some more.

Certainly, I am now less convinced that there is an issue with structure_factor_mode, but on the flip side, I have definitely found an issue with radius_effective_mode (see #3108 ).

**Comment by smk78** [comment]
As noted at the start of this issue the behaviour was irreproducible and so it is difficult to pass an opionion with 100% certainty. However, retested using https://github.com/SasView/sasview/actions/runs/10638002500 on W10/x64. Despite using the same data, model, and S(Q) parameter values (incl the tiny _concentration_salt_), and playing around with checking/unchecking parameters and clicking the Fit button in-between, I have not seen any of the bulleted behaviour above. So hopefully it has also been fixed as a consequence of https://github.com/SasView/sasview/pull/3100 too.
