### ISSUE TITLE
Showing a "are you sure" prompt on killing a fitpage

### ISSUE THREAD

**Issue by juliuskarliczek** [SasView/sasview#3107]
Some users here at the ILL told me, that it can be really frustrating when working with a lot of fitpages in a remote work station, that the button for closing a fitpage and navigating through all the fitpages are very close to each other. When trying to navigate to another fitpage, sometimes the "x" button is hit accidentally and then the fitpage is destroyed without asking.

Maybe there could be a settings option that decides if a "are you sure" prompt is opened when trying to kill a fitpage

**Comment by krzywon** [comment]
#2778 addresses this, but in a different way

**Comment by juliuskarliczek** [comment]
Okay, thank you. I will close this then
