### ISSUE TITLE
Bug with radius_effective_mode

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#3108]
**Describe the bug**
Looking into https://github.com/SasView/sasview/issues/3101 in more detail there appears to be a bug with radius_effective_mode **which has been introduced since release 5.0.6**.

Whilst the steps to reproduce might seem very niche, they are a set of steps that reliably reproduce the bug. There may be other sequences of steps that cause the same thing.

**To Reproduce**
1. Run SasView
2. Load some data (eg, 2% SDS); send to fitting
3. Create an ellipsoid @ hayter_msa model
4. Set radius_equitorial = 40
5. Tick background, radius_equitorial, volume_fraction & charge
6. Fit
7. Set radius_effective_mode = unconstrained
8. Fit
9. Set radius_effective_mode back to something other than unconstrained
10. Fit.

The radius_effective drops to zero!

And nothing you can do will recover it to a computed value based on the setting on radius_effective_mode, and the S(Q) remains frozen in subsequent fits.

**Expected behavior**
radius_effective should always take the value determined by the setting of radius_effective_mode. 

**SasView version (please complete the following information):**
 - 6.0.0b2

**Operating system (please complete the following information):**
 - W10/x64

**Comment by krzywon** [comment]
This might be fixed with #3100. I tested your process in that branch and release_6.0.0. I can reproduce the issue in the release branch, but the issue seems to be solved in the PR branch.

**Comment by smk78** [comment]
Retested using https://github.com/SasView/sasview/actions/runs/10638002500 on W10/x64.
The issue described above appears to be fixed and the expected radius_effective is now updated to match the setting of radius_effective_mode.
