### ISSUE TITLE
RecommendedHashNotFoundWarning from SasView 6.0.0 on W11

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#3152]
**Describe the bug**
The following _warning_ was encountered when running SasView 6.0.0 for the very first time on a W11 Dell Latitude laptop:

![image](https://github.com/user-attachments/assets/5fb1affc-f416-4cf1-945c-109c7b77d844)

The program did however otherwise start normally and function as expected. 

No errors/problems were encountered during the installation process (installing to C:\SasView-6.0.0).

The laptop had never previously had any version of SasView installed, nor any Developer environment.

**Expected behavior**
The warning should not appear.

**Additional context**
This is the sort of dialog that would very easily disturb most SasView users, particularly those installing/using the program for the first time.

**Comment by krzywon** [comment]
Thanks for the report, @smk78. This warning was coming from sasmodels and should be fixed by https://github.com/SasView/sasmodels/pull/613.

**Comment by krzywon** [comment]
This should now be resolved
