### ISSUE TITLE
Create loader for 1D data in seperate single column files (Trac #183)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#331]
Some ESRF and APS SAXS beamlines have reduction programs that output the Q data and the I data as seperate single column data files.

One variant terminates each entry with a comma, the other does not.

Example files are attached.

Migrated from http://trac.sasview.org/ticket/183
```json
{
    "status": "closed",
    "changetime": "2018-03-04T16:50:29",
    "_ts": "2018-03-04 16:50:29.836707+00:00",
    "description": "Some ESRF and APS SAXS beamlines have reduction programs that output the Q data and the I data as seperate single column data files.\n\nOne variant terminates each entry with a comma, the other does not.\n\nExample files are attached.",
    "reporter": "smk78",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Framework Enhancements",
    "time": "2013-04-05T13:42:00",
    "component": "SasView",
    "summary": "Create loader for 1D data in seperate single column files",
    "priority": "minor",
    "keywords": "1D, Load",
    "milestone": "SasView 4.1.0",
    "owner": "",
    "type": "enhancement"
}
```

**Comment by smk78** [comment]
Trac update at `2013/04/05 13:43:45`: 
* **smk78** changed attachment from "" to "5M-q.txt"
* **smk78** commented:

Single column Q data (Type 1)

**Comment by smk78** [comment]
Trac update at `2013/04/05 13:44:17`: 
* **smk78** changed attachment from "" to "5M-I.txt"
* **smk78** commented:

Single column I data (Type 1)

**Comment by smk78** [comment]
Trac update at `2013/04/05 13:44:42`: 
* **smk78** changed attachment from "" to "ptbl-q.txt"
* **smk78** commented:

Single column Q data (Type 2)

**Comment by smk78** [comment]
Trac update at `2013/04/05 13:45:52`: 
* **smk78** changed attachment from "" to "ptbl-i.txt"
* **smk78** commented:

Single column I data (Type 2)

**Comment by smk78** [comment]
Trac update at `2013/04/05 13:47:03`: **smk78** changed keywords from "" to "1D, Load"

**Comment by butlerpd** [comment]
Trac update at `2013/08/31 02:10:18`: 
* **butler** changed milestone from "" to "WishList"
* **butler** changed priority from "major" to "minor"

**Comment by butlerpd** [comment]
Trac update at `2015/01/30 01:27:12`: **butler** changed workpackage from "" to "Saving StateEnhancements"

**Comment by butlerpd** [comment]
Trac update at `2015/01/30 02:20:58`: **butler** changed workpackage from "Saving StateEnhancements" to "SasView Admin"

**Comment by butlerpd** [comment]
Trac update at `2015/01/30 02:23:41`: 
* **butler** changed type from "defect" to "enhancement"
* **butler** changed workpackage from "SasView Admin" to "SasView Framework Enhancements"

**Comment by smk78** [comment]
Trac update at `2016/10/07 19:54:19`: **smk78** commented:

These files are now supported in the File Converter tool from !SasView 4.1 onwards so this ticket can be closed. Also see #641

**Comment by smk78** [comment]
Trac update at `2016/10/07 19:54:31`: 
* **smk78** changed resolution from "" to "fixed"
* **smk78** changed status from "new" to "closed"

**Comment by butlerpd** [comment]
Trac update at `2018/03/04 16:50:29`: **butler** changed milestone from "SasView WishList" to "SasView 4.1.0"
