### ISSUE TITLE
Request for (x,y,e) readback from graph on mouse over (Trac #185)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#333]
"When we plot a graph, it is possible with the cursor to point on a curve to have access to the (x,y) coordinate of a point? I think it is very useful to have a rapid information of the intensity level at a q value."

Arnauld Poulesquen
CEA Marcoule
DEN/DTCD/SPDE/L2ED
Laboratoire de Chimie des Fluides Complexes et d'Irradiation
Bât. 37 - BP 17171
F - 30 207 Bagnols sur Cèze
FRANCE
 
Tél.      : +33 (0)4.66.79.18.01
Fax      : +33 (0)4.66.39.78.71

Response by SMK for !SasView Developers, 14/05/13:

"As far as I know this is not possible at the moment, but I agree it would be a nice feature. The best !SasView can offer is if you right-click on ANY data point and move down the context menu to the name of the data set you are interested in, then follow the chevron to !DataInfo. A window will pop-up and if you scroll down you will get a listing of all the (x,y,e) values for that data set. I will ticket the feature you ask for (but at this juncture I do not know how feasible it may be or how quickly it will be implemented)."

Migrated from http://trac.sasview.org/ticket/185
```json
{
    "status": "closed",
    "changetime": "2016-10-11T16:36:28",
    "_ts": "2016-10-11 16:36:28.927111+00:00",
    "description": "\"When we plot a graph, it is possible with the cursor to point on a curve to have access to the (x,y) coordinate of a point? I think it is very useful to have a rapid information of the intensity level at a q value.\"\n\n\nArnauld Poulesquen\nCEA Marcoule\nDEN/DTCD/SPDE/L2ED\nLaboratoire de Chimie des Fluides Complexes et d'Irradiation\nB\u00e2t. 37 - BP 17171\nF - 30 207 Bagnols sur C\u00e8ze\nFRANCE\n \nT\u00e9l.      : +33 (0)4.66.79.18.01\nFax      : +33 (0)4.66.39.78.71\n\n\nResponse by SMK for !SasView Developers, 14/05/13:\n\n\"As far as I know this is not possible at the moment, but I agree it would be a nice feature. The best !SasView can offer is if you right-click on ANY data point and move down the context menu to the name of the data set you are interested in, then follow the chevron to !DataInfo. A window will pop-up and if you scroll down you will get a listing of all the (x,y,e) values for that data set. I will ticket the feature you ask for (but at this juncture I do not know how feasible it may be or how quickly it will be implemented).\"",
    "reporter": "smk78",
    "cc": "",
    "resolution": "worksforme",
    "workpackage": "SasView GUI Redesign",
    "time": "2013-05-14T09:33:31",
    "component": "SasView",
    "summary": "Request for (x,y,e) readback from graph on mouse over",
    "priority": "minor",
    "keywords": "",
    "milestone": "SasView 4.1.0",
    "owner": "",
    "type": "enhancement"
}
```

**Comment by smk78** [comment]
Trac update at `2013/05/14 15:16:07`: **smk78** changed type from "defect" to "enhancement"

**Comment by ajj** [comment]
Trac update at `2013/07/04 13:45:24`: **ajj** commented:

Clicking anywhere on the graph currently puts the coordinates in the status bar area. It would probably be better to have this functionality such that information is printed in the graph window somewhere.

**Comment by butlerpd** [comment]
Trac update at `2013/08/31 01:54:57`: **butler** changed milestone from "" to "WishList"

**Comment by butlerpd** [comment]
Trac update at `2015/01/29 23:57:47`: **butler** changed workpackage from "" to "SasView GUI Redesign"

**Comment by butlerpd** [comment]
Trac update at `2015/01/31 17:41:19`: **butler** changed priority from "major" to "minor"

**Comment by butlerpd** [comment]
Trac update at `2015/08/14 20:21:29`: **butler** changed milestone from "WishList" to "SasView 4.0.0"

**Comment by butlerpd** [comment]
Trac update at `2016/03/20 22:44:22`: **butler** changed milestone from "SasView 4.0.0" to "SasView Next Release +1"

**Comment by butlerpd** [comment]
Trac update at `2016/09/05 04:21:02`: 
* **butler** commented:

More importantly for 2D plots the intensity is NOT accessible since x and y both are now co-ordinate values.


* **butler** changed description from:

> "When we plot a graph, it is possible with the cursor to point on a curve to have access to the (x,y) coordinate of a point? I think it is very useful to have a rapid information of the intensity level at a q value."
> 
> 
> Arnauld Poulesquen
> CEA Marcoule
> DEN/DTCD/SPDE/L2ED
> Laboratoire de Chimie des Fluides Complexes et d'Irradiation
> Bât. 37 - BP 17171
> F - 30 207 Bagnols sur Cèze
> FRANCE
>  
> Tél.      : +33 (0)4.66.79.18.01
> Fax      : +33 (0)4.66.39.78.71
> 
> 
> Response by SMK for SasView Developers, 14/05/13:
> 
> "As far as I know this is not possible at the moment, but I agree it would be a nice feature. The best SasView can offer is if you right-click on ANY data point and move down the context menu to the name of the data set you are interested in, then follow the chevron to DataInfo. A window will pop-up and if you scroll down you will get a listing of all the (x,y,e) values for that data set. I will ticket the feature you ask for (but at this juncture I do not know how feasible it may be or how quickly it will be implemented)."

to:

> "When we plot a graph, it is possible with the cursor to point on a curve to have access to the (x,y) coordinate of a point? I think it is very useful to have a rapid information of the intensity level at a q value."
> 
> 
> Arnauld Poulesquen
> CEA Marcoule
> DEN/DTCD/SPDE/L2ED
> Laboratoire de Chimie des Fluides Complexes et d'Irradiation
> Bât. 37 - BP 17171
> F - 30 207 Bagnols sur Cèze
> FRANCE
>  
> Tél.      : +33 (0)4.66.79.18.01
> Fax      : +33 (0)4.66.39.78.71
> 
> 
> Response by SMK for !SasView Developers, 14/05/13:
> 
> "As far as I know this is not possible at the moment, but I agree it would be a nice feature. The best !SasView can offer is if you right-click on ANY data point and move down the context menu to the name of the data set you are interested in, then follow the chevron to !DataInfo. A window will pop-up and if you scroll down you will get a listing of all the (x,y,e) values for that data set. I will ticket the feature you ask for (but at this juncture I do not know how feasible it may be or how quickly it will be implemented)."


* **butler** changed milestone from "SasView Next Release +1" to "SasView 4.1.0"

**Comment by butlerpd** [comment]
Trac update at `2016/10/11 16:36:28`: 
* **butler** commented:

Closing this ticket as the feature requested does in fact exist.  getting x,y, AND z in the 2D plots should be a separate ticket but probably should wait for the new GUI


* **butler** changed resolution from "" to "worksforme"
* **butler** changed status from "new" to "closed"
