### ISSUE TITLE
Cannot load SASXML v1.1 data files (Trac #187)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#335]
SasView will not load CanSAS SASXML v1.1 data files; ie, those with the header:

<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="cansasxml-html.xsl" ?>
<SASroot version="1.1"
		 xmlns="urn:cansas1d:1.1"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="urn:cansas1d:1.1 http://www.cansas.org/formats/1.1/cansas1d.xsd">

An immediate problem is this means that SASXML data written from Mantid 2.5.x can no longer be read by SasView!

Looking at /CorFuncPerspective/sansdataloader/src/sans/dataloader/readers/cansas_reader.py the reason may be two-fold:

1) the loader appears to check for the presence of the namespace "cansas1d/1.0"

2) the class reader: includes the line version = '1.0'

Migrated from http://trac.sasview.org/ticket/187
```json
{
    "status": "closed",
    "changetime": "2013-08-31T02:00:10",
    "_ts": "2013-08-31 02:00:10.062581+00:00",
    "description": "SasView will not load CanSAS SASXML v1.1 data files; ie, those with the header:\n\n<?xml version=\"1.0\"?>\n<?xml-stylesheet type=\"text/xsl\" href=\"cansasxml-html.xsl\" ?>\n<SASroot version=\"1.1\"\n\t\t xmlns=\"urn:cansas1d:1.1\"\n\t\t xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n\t\t xsi:schemaLocation=\"urn:cansas1d:1.1 http://www.cansas.org/formats/1.1/cansas1d.xsd\">\n\nAn immediate problem is this means that SASXML data written from Mantid 2.5.x can no longer be read by SasView!\n\nLooking at /CorFuncPerspective/sansdataloader/src/sans/dataloader/readers/cansas_reader.py the reason may be two-fold:\n\n1) the loader appears to check for the presence of the namespace \"cansas1d/1.0\"\n\n2) the class reader: includes the line version = '1.0'\n",
    "reporter": "smk78",
    "cc": "",
    "resolution": "fixed",
    "time": "2013-05-17T11:03:03",
    "component": "SasView",
    "summary": "Cannot load SASXML v1.1 data files",
    "priority": "blocker",
    "keywords": "",
    "milestone": "SasView 2.2.1",
    "owner": "",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2013/08/31 02:00:10`: 
* **butler** commented:

Anders modified cansas reader to accept 1.1 as well as 1.0.  Jeff fixed the last problem with that code change.  Steve King now says it works. PDB


* **butler** changed milestone from "" to "SasView 2.2.1"
* **butler** changed resolution from "" to "fixed"
* **butler** changed status from "new" to "closed"
