### ISSUE TITLE
Can't set fit range for Linear Fits (Trac #188)

### ISSUE THREAD

**Issue by ajj** [SasView/sasview#336]
The fact that you can't set the fit range for a linear fit makes being able to do the fit basically useless.

Migrated from http://trac.sasview.org/ticket/188
```json
{
    "status": "closed",
    "changetime": "2013-10-03T18:20:39",
    "_ts": "2013-10-03 18:20:39.160831+00:00",
    "description": "The fact that you can't set the fit range for a linear fit makes being able to do the fit basically useless.",
    "reporter": "ajj",
    "cc": "",
    "resolution": "fixed",
    "time": "2013-06-21T13:11:22",
    "component": "SasView",
    "summary": "Can't set fit range for Linear Fits",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 3.0.0",
    "owner": "",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2013/09/24 02:25:51`: **butler** commented:

I don't understand this ... it looks to me like the fit range can be set in 2 different ways in fact: in q min and max and in the X axis min max (q^2^, logx etc depending on the type of plot).  Need some clarification or close

**Comment by ajj** [comment]
Trac update at `2013/10/03 18:20:39`: 
* **ajj** commented:

Seems to be working - previously the boxes were not editable. Odd. 

In any case the wording of the labels could be better and perhaps the min/max limits should not be in text boxes as it is a bit confusing.


* **ajj** changed resolution from "" to "fixed"
* **ajj** changed status from "new" to "closed"
