### ISSUE TITLE
Save Project doesn't save state of simultaneous fit panel (Trac #189)

### ISSUE THREAD

**Issue by ajj** [SasView/sasview#337]
Having gone through the pain of setting up a simultaneous fit, that state should be saved with the project.

Migrated from http://trac.sasview.org/ticket/189
```json
{
    "status": "closed",
    "changetime": "2016-12-13T15:42:05",
    "_ts": "2016-12-13 15:42:05.735531+00:00",
    "description": "Having gone through the pain of setting up a simultaneous fit, that state should be saved with the project.",
    "reporter": "ajj",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "Saving State Enhancements",
    "time": "2013-06-21T13:12:12",
    "component": "SasView",
    "summary": "Save Project doesn't save state of simultaneous fit panel",
    "priority": "critical",
    "keywords": "",
    "milestone": "SasView 4.1.0",
    "owner": "krzywon",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2013/08/31 18:06:06`: 
* **butler** commented:

Again no man-power willing to look at the save and report issues so moving to wishlist for now


* **butler** changed milestone from "SasView 3.0.0" to "WishList"

**Comment by butlerpd** [comment]
Trac update at `2015/01/30 01:22:49`: **butler** changed workpackage from "" to "Reporting Enhancements"

**Comment by butlerpd** [comment]
Trac update at `2015/03/15 01:54:17`: **butler** changed workpackage from "Reporting Enhancements" to "Saving State Enhancements"

**Comment by butlerpd** [comment]
Trac update at `2015/08/14 20:20:04`: **butler** changed milestone from "WishList" to "SasView 4.0.0"

**Comment by butlerpd** [comment]
Trac update at `2015/10/25 16:48:32`: **butler** changed priority from "major" to "critical"

**Comment by butlerpd** [comment]
Trac update at `2016/08/07 03:01:53`: 
* **butler** commented:

will need to much of a refactor to do for 4.0


* **butler** changed milestone from "SasView 4.0.0" to "SasView Next Release +1"

**Comment by butlerpd** [comment]
Trac update at `2016/09/05 02:51:42`: **butler** changed milestone from "SasView Next Release +1" to "SasView 4.1.0"

**Comment by smk78** [comment]
Trac update at `2016/12/13 15:42:05`: **smk78** commented:

Fix verified.

Though I do note that the STATE of the model parameters is not saved; so when you re-open the project all parameters in all !FitPages are unchecked by default. The only slight issue with this is that the Open Project also takes you to the Const & Simul Fit page where it is tempting to just click Fit... If you do so the Fit button turns to Stop giving you the IMPRESSION it is fitting when in fact it isn't doing a bean. The first time I did this I felt a bit of a numpty for spending a few mins sat watching !SasView do absolutely nothing! :-)
