### ISSUE TITLE
Ubuntu builds do not produce a usable egg for installation. (Trac #194)

### ISSUE THREAD

**Issue by ajj** [SasView/sasview#342]
The ubuntu builds make the appropriate egg file for sasview, but that does not produce a workable sasview.

Migrated from http://trac.sasview.org/ticket/194
```json
{
    "status": "closed",
    "changetime": "2017-10-27T10:13:29",
    "_ts": "2017-10-27 10:13:29.936184+00:00",
    "description": "The ubuntu builds make the appropriate egg file for sasview, but that does not produce a workable sasview.",
    "reporter": "ajj",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2013-11-05T12:43:56",
    "component": "SasView",
    "summary": "Ubuntu builds do not produce a usable egg for installation.",
    "priority": "minor",
    "keywords": "",
    "milestone": "Admin Tasks",
    "owner": "ajj",
    "type": "defect"
}
```

**Comment by ajj** [comment]
Trac update at `2013/11/05 12:46:04`: 
* **ajj** commented:

The linux builds need to be used as part of a distribution via pypy or build .deb files that can actually be installed and give a working Sasview application (need additional scripts in /usr/local/bin or wherever is appropriate).


* **ajj** changed owner from "" to "ajj"
* **ajj** changed status from "new" to "assigned"

**Comment by butlerpd** [comment]
Trac update at `2014/04/05 20:52:41`: **butler** changed milestone from "SasView 3.0.0" to "SasView Next Release +1"

**Comment by butlerpd** [comment]
Trac update at `2015/01/30 02:13:42`: **butler** changed workpackage from "" to "SasView Admin"

**Comment by butlerpd** [comment]
Trac update at `2015/01/30 02:24:53`: **butler** changed workpackage from "SasView Admin" to "SasView Bug Fixing"

**Comment by butlerpd** [comment]
Trac update at `2015/02/01 23:04:00`: **butler** changed milestone from "SasView Next Release +1" to "SasView 3.1"

**Comment by butlerpd** [comment]
Trac update at `2015/03/10 16:52:50`: 
* **butler** commented:

Somebody needs to check if this is really still true (ticket is 18 months old and we changed build systems).  Certainly not a show stopper for releasing 3.1 so moving to next release +1 


* **butler** changed milestone from "SasView 3.1" to "SasView Next Release +1"

**Comment by butlerpd** [comment]
Trac update at `2015/06/30 17:19:49`: **butler** commented:

From Torben while checking for Release of 3.1

Ubuntu egg has as a minimum of two faults:
a. Docs are not included in python egg
b. Reports can not be generated

**Comment by butlerpd** [comment]
Trac update at `2017/10/27 10:13:29`: 
* **butler** commented:

Tim Snow says it works for him.  This is now a very stale ticket nobody is watching anyway so will close this one.


* **butler** changed milestone from "SasView Next Release +1" to "Admin Tasks"
* **butler** changed resolution from "" to "fixed"
* **butler** changed status from "assigned" to "closed"
