### ISSUE TITLE
Configuration code needs cleaning up (Trac #195)

### ISSUE THREAD

**Issue by ajj** [SasView/sasview#343]
In looking for problems with backwards compatibility of config files, it became clear that the configuration code is a bit of a mess. There seem to be whole swathes of config variables that are set in multiple places, sometimes ones that don't appear to ever be called.

This needs work in with a general code cleanup.

Migrated from http://trac.sasview.org/ticket/195
```json
{
    "status": "closed",
    "changetime": "2018-09-09T07:37:14",
    "_ts": "2018-09-09 07:37:14.492580+00:00",
    "description": "In looking for problems with backwards compatibility of config files, it became clear that the configuration code is a bit of a mess. There seem to be whole swathes of config variables that are set in multiple places, sometimes ones that don't appear to ever be called.\n\nThis needs work in with a general code cleanup.",
    "reporter": "ajj",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Framework Enhancements",
    "time": "2013-11-05T12:48:47",
    "component": "SasView",
    "summary": "Configuration code needs cleaning up",
    "priority": "minor",
    "keywords": "",
    "milestone": "SasView 5.0.0",
    "owner": "",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2015/01/30 01:17:30`: **butler** changed workpackage from "" to "SasView Admin"

**Comment by butlerpd** [comment]
Trac update at `2015/01/30 02:27:07`: **butler** changed workpackage from "SasView Admin" to "SasView Framework Enhancements"

**Comment by butlerpd** [comment]
Trac update at `2015/02/01 23:39:48`: **butler** changed milestone from "WishList" to "SasView Next Release +1"

**Comment by butlerpd** [comment]
Trac update at `2017/10/23 14:29:30`: **butler** changed milestone from "SasView Next Release +1" to "SasView 5.0.0"

**Comment by butlerpd** [comment]
Trac update at `2017/10/23 14:34:28`: **butler** commented:

Look at ticket #1023 as well which relates (is the same as?) this.
