### ISSUE TITLE
License Survey (Trac #200)

### ISSUE THREAD

**Issue by ajj** [SasView/sasview#348]
Go through all code to determine current probably licensing.

Migrated from http://trac.sasview.org/ticket/200
```json
{
    "status": "closed",
    "changetime": "2014-04-05T20:26:41",
    "_ts": "2014-04-05 20:26:41.542051+00:00",
    "description": "Go through all code to determine current probably licensing.",
    "reporter": "ajj",
    "cc": "",
    "resolution": "fixed",
    "time": "2014-01-19T20:51:19",
    "component": "SasView",
    "summary": "License Survey",
    "priority": "minor",
    "keywords": "",
    "milestone": "Admin Tasks",
    "owner": "butler",
    "type": "task"
}
```

**Comment by ajj** [comment]
Trac update at `2014/02/11 13:25:35`: 
* **ajj** commented:

Initial survey has revealed:

Overall DANSE license at: http://danse.us/trac/all/wiki/license

Three files with explicit license:
 - data_utils/odict.py : BSD
 - dataloader/readers/schema/ : cansas schemas with Argonne license - free to use as we wish, must keep copyright notice
 - models/c_extension/libigor/2Y_cpoly.cpp : Henrik Vestermark License (http://hvks.com) - free for non-commercial use 

Now need to check through and see if there are any routines used that are from elsewhere (e.g. numerical recipies) - that will be more effort.


* **ajj** changed status from "new" to "accepted"

**Comment by butlerpd** [comment]
Trac update at `2014/04/01 15:38:14`: **butler** commented:

Some more License "options":

  * in setup.py the license is PSF (Python Software Foundation)
  * Matplot lib “uses BSD compatible code, and its license is based on the PSF license”
  * WxPython; WxWidgets; WxWindows. Essentially L-GPL
  * NumPy/SciPY - BSD

**Comment by ajj** [comment]
Trac update at `2014/04/03 08:18:09`: 
* **ajj** changed owner from "ajj" to "butler"
* **ajj** changed status from "accepted" to "assigned"

**Comment by butlerpd** [comment]
Trac update at `2014/04/03 08:50:18`: **butler** commented:

Have now moved the research on this to a wiki page in the developers corner under "projects in progress" 

Suggest that all licenses that must be attached get added as a page in license.txt after a preamble about copyright sasview developers BSD and statement that we use some packages whose disclaimers and licenses as required by their license are set below. .. or some such
so need to:
* Survey licenses within code
* Survey licenses for ALL packages used
* Agree on OUR license
* Update license.txt appropriately
* Update any internal license references

**Comment by butlerpd** [comment]
Trac update at `2014/04/05 20:26:41`: 
* **butler** changed resolution from "" to "fixed"
* **butler** changed status from "assigned" to "closed"
