### ISSUE TITLE
Mac build failures (Trac #201)

### ISSUE THREAD

**Issue by ajj** [SasView/sasview#349]
Mac builds were failing.

Peter switched jenkins from svn:// to http:// for checkout and that seems to have fixed it for now.

More investigation should be done to determine original cause to avoid future problems.

Migrated from http://trac.sasview.org/ticket/201
```json
{
    "status": "closed",
    "changetime": "2014-04-05T21:00:54",
    "_ts": "2014-04-05 21:00:54.811270+00:00",
    "description": "Mac builds were failing.\n\nPeter switched jenkins from svn:// to http:// for checkout and that seems to have fixed it for now.\n\nMore investigation should be done to determine original cause to avoid future problems.",
    "reporter": "ajj",
    "cc": "",
    "resolution": "fixed",
    "time": "2014-01-19T20:53:14",
    "component": "SasView",
    "summary": "Mac build failures",
    "priority": "minor",
    "keywords": "",
    "milestone": "Admin Tasks",
    "owner": "Peter Parker",
    "type": "task"
}
```

**Comment by butlerpd** [comment]
Trac update at `2014/04/05 21:00:54`: 
* **butler** commented:

a few tweeks -- mostly updating the svn version was required.  Fixed at code camp II


* **butler** changed resolution from "" to "fixed"
* **butler** changed status from "new" to "closed"
