### ISSUE TITLE
Fix auto build of sphinx documentation (Trac #202)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#350]
at the moment only a small subset of modules have their sphinx documentation built.  The rest generate errors during the build.  Paul Kienzle has looked into it.  His analysis is attached

Migrated from http://trac.sasview.org/ticket/202
```json
{
    "status": "closed",
    "changetime": "2015-11-22T01:48:50",
    "_ts": "2015-11-22 01:48:50.104889+00:00",
    "description": "at the moment only a small subset of modules have their sphinx documentation built.  The rest generate errors during the build.  Paul Kienzle has looked into it.  His analysis is attached",
    "reporter": "butler",
    "cc": "",
    "resolution": "duplicate",
    "workpackage": "SasView Documentation",
    "time": "2014-01-19T21:44:08",
    "component": "SasView",
    "summary": "Fix auto build of sphinx documentation",
    "priority": "minor",
    "keywords": "",
    "milestone": "SasView 3.1.0",
    "owner": "",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2014/01/19 21:44:51`: 
* **butler** changed attachment from "" to "SphinxFix.txt"
* **butler** commented:

Paul Kienzle documention for fixing Sphinx builds

**Comment by ajj** [comment]
Trac update at `2015/01/14 12:46:59`: **ajj** changed workpackage from "" to "SasView Documentation"

**Comment by butlerpd** [comment]
Trac update at `2015/01/27 03:30:16`: 
* **butler** commented:

With Peter Parker's work and the move to Wx3.0 this ticket is obsolete so removing as "duplicate" even though that is not exactly true.


* **butler** changed resolution from "" to "duplicate"
* **butler** changed status from "new" to "closed"

**Comment by butlerpd** [comment]
Trac update at `2015/11/22 01:48:50`: **butler** changed milestone from "SasView Next Release +1" to "SasView 3.1.0"
