### ISSUE TITLE
SasView no longer writing CanSAS XML files compliant with the schema (Trac #204)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#352]
CanSAS 1D XML files written from SasView (testing v3.0.0) have the
header:

<?xml version="1.0" ?>
<SASroot version="1.1" xmlns="urn:cansas1d:1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:cansas1d:1.1 http://svn.smallangles.net/svn/canSAS/1dwg/trunk/cansas1d.xsd">

This is not compliant with the v1.1 schema and needs to be changed to,
for example:

<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="cansas1d.xsl" ?>
<SASroot version="1.1"
		 xmlns="urn:cansas1d:1.1"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="urn:cansas1d:1.1 http://www.cansas.org/formats/1.1/cansas1d.xsd"
		>

to reflect the reorganisation of web resources.

Migrated from http://trac.sasview.org/ticket/204
```json
{
    "status": "closed",
    "changetime": "2014-04-04T16:18:28",
    "_ts": "2014-04-04 16:18:28.606169+00:00",
    "description": "CanSAS 1D XML files written from SasView (testing v3.0.0) have the\nheader:\n\n<?xml version=\"1.0\" ?>\n<SASroot version=\"1.1\" xmlns=\"urn:cansas1d:1.1\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"urn:cansas1d:1.1 http://svn.smallangles.net/svn/canSAS/1dwg/trunk/cansas1d.xsd\">\n\nThis is not compliant with the v1.1 schema and needs to be changed to,\nfor example:\n\n<?xml version=\"1.0\"?>\n<?xml-stylesheet type=\"text/xsl\" href=\"cansas1d.xsl\" ?>\n<SASroot version=\"1.1\"\n\t\t xmlns=\"urn:cansas1d:1.1\"\n\t\t xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n\t\t xsi:schemaLocation=\"urn:cansas1d:1.1 http://www.cansas.org/formats/1.1/cansas1d.xsd\"\n\t\t>\n\nto reflect the reorganisation of web resources.\n",
    "reporter": "smk78",
    "cc": "",
    "resolution": "fixed",
    "time": "2014-02-13T11:02:36",
    "component": "SasView",
    "summary": "SasView no longer writing CanSAS XML files compliant with the schema",
    "priority": "critical",
    "keywords": "CanSAS, XML",
    "milestone": "SasView 3.0.0",
    "owner": "King",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2014/04/01 09:58:07`: 
* **butler** changed owner from "krzywon" to "King"
* **butler** changed status from "accepted" to "assigned"

**Comment by butlerpd** [comment]
Trac update at `2014/04/01 09:58:39`: **butler** commented:

Fix was made by Krzywon -- King now to test
