### ISSUE TITLE
Allow for custom integration range in Invariant perspective (Trac #206)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#354]
At present the Invariant perspective integrates over the full range of
the loaded dataset and the only way to change the integration limits
is to edit the data outside of !SasView and reload it.

The Total Q Range dialog in the Invariant perspective should be
augmented with a Integration Q Range dialog.

Migrated from http://trac.sasview.org/ticket/206
```json
{
    "status": "new",
    "changetime": "2017-10-26T09:37:06",
    "_ts": "2017-10-26 09:37:06.542292+00:00",
    "description": "At present the Invariant perspective integrates over the full range of\nthe loaded dataset and the only way to change the integration limits\nis to edit the data outside of !SasView and reload it.\n\nThe Total Q Range dialog in the Invariant perspective should be\naugmented with a Integration Q Range dialog.",
    "reporter": "smk78",
    "cc": "",
    "resolution": "",
    "workpackage": "SasView GUI Redesign",
    "time": "2014-02-14T09:52:14",
    "component": "SasView",
    "summary": "Allow for custom integration range in Invariant perspective",
    "priority": "major",
    "keywords": "Invariant",
    "milestone": "SasView 5.0.0",
    "owner": "",
    "type": "enhancement"
}
```

**Comment by butlerpd** [comment]
Trac update at `2014/04/05 20:50:06`: **butler** changed milestone from "SasView 3.0.0" to "SasView Next Release +1"

**Comment by butlerpd** [comment]
Trac update at `2015/01/30 02:14:38`: **butler** changed workpackage from "" to "SasView GUI Redesign"

**Comment by butlerpd** [comment]
Trac update at `2017/04/30 15:57:54`: **butler** changed description from:

> At present the Invariant perspective integrates over the full range of
> the loaded dataset and the only way to change the integration limits
> is to edit the data outside of SasView and reload it.
> 
> The Total Q Range dialog in the Invariant perspective should be
> augmented with a Integration Q Range dialog.

to:

> At present the Invariant perspective integrates over the full range of
> the loaded dataset and the only way to change the integration limits
> is to edit the data outside of !SasView and reload it.
> 
> The Total Q Range dialog in the Invariant perspective should be
> augmented with a Integration Q Range dialog.

**Comment by butlerpd** [comment]
Trac update at `2017/10/26 09:37:06`: **butler** changed milestone from "SasView Next Release +1" to "SasView 5.0.0"

**Comment by krzywon** [comment]
This was modified a while ago. Closing.
