### ISSUE TITLE
Batch fitting does not display the correct data (Trac #207)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#355]
This defect exists in SasView 2.2.1 and 3.0.0.

After executing a batch fit, if you click on the data source dropdown
in the batch fit perspective SasView shows you a fit to the datasource
selected.

The model data (the Mx calculation) appears to be correct for the
datasource selected, but the experimental data shown is not.

I think SasView is merely showing the initially fitted datasource over
and over again but plotting the new model data, because if you
separately fit the multiple datasets you get the same fit parameters
as in the batch fit grid window (fortunately!!!) but different graphs!

In summary: batch fitting is working, and you can save the correct fit
to your datasource, but the graph SasView shows you is misleading.

Migrated from http://trac.sasview.org/ticket/207
```json
{
    "status": "closed",
    "changetime": "2015-11-22T01:53:07",
    "_ts": "2015-11-22 01:53:07.240481+00:00",
    "description": "This defect exists in SasView 2.2.1 and 3.0.0.\n\nAfter executing a batch fit, if you click on the data source dropdown\nin the batch fit perspective SasView shows you a fit to the datasource\nselected.\n\nThe model data (the Mx calculation) appears to be correct for the\ndatasource selected, but the experimental data shown is not.\n\nI think SasView is merely showing the initially fitted datasource over\nand over again but plotting the new model data, because if you\nseparately fit the multiple datasets you get the same fit parameters\nas in the batch fit grid window (fortunately!!!) but different graphs!\n\nIn summary: batch fitting is working, and you can save the correct fit\nto your datasource, but the graph SasView shows you is misleading.\n\n",
    "reporter": "smk78",
    "cc": "",
    "resolution": "duplicate",
    "workpackage": "SasView GUI Redesign",
    "time": "2014-03-06T13:55:05",
    "component": "SasView",
    "summary": "Batch fitting does not display the correct data",
    "priority": "minor",
    "keywords": "Batch, Fitting, Plotting",
    "milestone": "SasView 3.1.0",
    "owner": "",
    "type": "enhancement"
}
```

**Comment by smk78** [comment]
Trac update at `2014/03/07 16:46:24`: 
* **smk78** commented:

Correction to the above: SasView **is not** displaying/saving the correct fits to the data after batch fitting! Accordingly I am raising this defect from 'major' to 'critical'.

What is happening is that when you display a batch fitted result by clicking on the datasource dropdown you get a graph that shows experimental data and model fit. The legend correctly identifies them (ie, data[1] and M1, data[2] and M2) but this is wrong. I think the data is correct, but despite what the legend says the model is always M1 (or, at least, the first data fitted).

When you then try to save the model fit to a file the context menu correctly identifies the data you are about to save, but what you actually end up saving is M1 every time.



* **smk78** changed priority from "major" to "critical"

**Comment by butlerpd** [comment]
Trac update at `2014/03/11 14:19:31`: **butler** changed milestone from "SasView Next Release +1" to "SasView 3.0.0"

**Comment by butlerpd** [comment]
Trac update at `2014/04/01 11:03:18`: 
* **butler** changed _comment0 from:

> After reviewing this ticket is more about failures of documentation and quirkiness of interface than broken.  The issues is that the dropdown brings up the data file plot useful in setting up the batch but after the batch has run cannot access the results of the batch -- hence all manipulation of results must be done on batch fit page.  However the unsuspecting user, seeing the new plot window pop up with  a fit (which is just the theory curve based on the model parameters on the page) can wrongly assume the "model" line is the fit result.
> 
> Many enhancements to batch have been discussed and would be useful but not appropriate for this ticket.
> 
> ToDo for this ticket:
> MINIMUM - add red warning on batch fit page that the dropdown ONLY related to the data NOT the the resulting fit.  
> 
> Alternatively could also restructure "view fits" on batch page to be more obviously seperate from plotting of data columns AND provide better instructions. For example - could move to the top and/or put box around it.  Longer term one would like to get the results back to the batchpage so could pop up stuff properly.

to:

> 1448157178543598


* **butler** commented:

After reviewing this ticket is more about failures of documentation and quirkiness of interface than broken.  The issues is that the dropdown brings up the data file plot useful in setting up the batch but after the batch has run cannot access the results of the batch -- hence all manipulation of results must be done on batch fit page.  However the unsuspecting user, seeing the new plot window pop up with  a fit (which is just the theory curve based on the model parameters on the page) can wrongly assume the "model" line is the fit result.

Many enhancements to batch have been discussed and would be useful but not appropriate for this ticket.

!ToDo for this ticket:
MINIMUM - add red warning on batch fit page that the dropdown ONLY related to the data NOT the the resulting fit.  

Alternatively could also restructure "view fits" on batch page to be more obviously seperate from plotting of data columns AND provide better instructions. For example - could move to the top and/or put box around it.  Longer term one would like to get the results back to the batchpage so could pop up stuff properly.

**Comment by butlerpd** [comment]
Trac update at `2014/04/01 15:40:45`: 
* **butler** changed priority from "critical" to "minor"
* **butler** changed type from "defect" to "task"

**Comment by butlerpd** [comment]
Trac update at `2014/04/01 15:41:04`: **butler** changed type from "task" to "enhancement"

**Comment by butlerpd** [comment]
Trac update at `2014/04/04 10:10:51`: **butler** changed milestone from "SasView 3.0.0" to "SasView Next Release +1"

**Comment by butlerpd** [comment]
Trac update at `2015/01/30 02:09:56`: 
* **butler** commented:

This ticket has been split into two #382 and #427.  this ticket can now be closed


* **butler** changed resolution from "" to "duplicate"
* **butler** changed status from "new" to "closed"
* **butler** changed workpackage from "" to "SasView GUI Redesign"

**Comment by butlerpd** [comment]
Trac update at `2015/11/22 01:53:07`: **butler** changed milestone from "SasView Next Release +1" to "SasView 3.1.0"
