### ISSUE TITLE
Update trunk to wx 3.0 (Trac #216)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#364]
Current version of sasview is using wx 2.8 which is one of the blockers to 64 bit and is also becoming old and unsupported.  Task is to make sure the code base in trunk will work with wx 3.0 

Migrated from http://trac.sasview.org/ticket/216
```json
{
    "status": "closed",
    "changetime": "2015-11-22T01:17:01",
    "_ts": "2015-11-22 01:17:01.942075+00:00",
    "description": "Current version of sasview is using wx 2.8 which is one of the blockers to 64 bit and is also becoming old and unsupported.  Task is to make sure the code base in trunk will work with wx 3.0 ",
    "reporter": "butler",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView GUI Enhancements",
    "time": "2014-03-31T15:52:19",
    "component": "SasView",
    "summary": "Update trunk to wx 3.0",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 3.1.0",
    "owner": "mathieu",
    "type": "enhancement"
}
```

**Comment by mdoucet** [comment]
Trac update at `2014/04/01 09:15:25`: 
* **mathieu** changed owner from "Doucet" to "mathieu"
* **mathieu** changed status from "new" to "assigned"

**Comment by butlerpd** [comment]
Trac update at `2014/04/01 10:15:53`: **butler** changed type from "defect" to "enhancement"

**Comment by ajj** [comment]
Trac update at `2014/04/03 10:05:55`: **ajj** changed milestone from "SasView 3.0.0" to "SasView Next Release +1"

**Comment by mdoucet** [comment]
Trac update at `2014/04/10 16:09:23`: 
* **mathieu** changed resolution from "" to "fixed"
* **mathieu** changed status from "assigned" to "closed"

**Comment by butlerpd** [comment]
Trac update at `2015/11/22 01:17:01`: 
* **butler** changed milestone from "SasView Next Release +1" to "SasView 3.1.0"
* **butler** changed workpackage from "" to "SasView GUI Enhancements"
