### ISSUE TITLE
Verify Correctness of Shulz Zimm Distribution (Trac #217)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#365]
Klaus Huber and Ralph Schweins believe we are effectively using the weight average distribution rather than the number average in the case of the Shulz-Zimm distribution.  Need to verify.  If wrong should fix.  If correct need to document.

Migrated from http://trac.sasview.org/ticket/217
```json
{
    "status": "closed",
    "changetime": "2015-03-04T13:04:13",
    "_ts": "2015-03-04 13:04:13.710057+00:00",
    "description": "Klaus Huber and Ralph Schweins believe we are effectively using the weight average distribution rather than the number average in the case of the Shulz-Zimm distribution.  Need to verify.  If wrong should fix.  If correct need to document.",
    "reporter": "butler",
    "cc": "",
    "resolution": "invalid",
    "workpackage": "SasView Admin",
    "time": "2014-04-01T11:13:00",
    "component": "SasView",
    "summary": "Verify Correctness of Shulz Zimm Distribution",
    "priority": "trivial",
    "keywords": "",
    "milestone": "Admin Tasks",
    "owner": "gonzales/butler/ajj/heenan",
    "type": "task"
}
```

**Comment by butlerpd** [comment]
Trac update at `2014/04/01 15:01:30`: **butler** changed summary from "Finish code reorg" to "Verify Correctness of Shulz Zimm Distribution"

**Comment by butlerpd** [comment]
Trac update at `2014/04/04 09:59:05`: 
* **butler** changed _comment0 from:

> After lengthy discussions and looking at papers and doing calculations it is clear that:
> SasView assumes the underlying distribution is a number distribution and thereby the reported mean from that distribution is a number average parameter.  It properly weights that distribution by volume when fitting to the scattering data as is required to fit scattering data.  
> 
> However, from the perspective of the Schulz distribution, it is clear that the litterature has conflicting views about what the correct form of the number average Shulz should be. 
> 
> Fundamentally this means that there are TWO different distributions which are being called the Schulz distribution.  These are unfortunately related through the mass. 
> 
> SasView, like FISH and NIST IGOR macros, take their distribution from the M. Kotlarchyk and S-H. Chen (J. Chem. Phys. 79 (1983) 2461-2469) paper which specifically gives the distribution as being by number.  This is the same number Shulz distrbition given by Aragon and Pecora in their 1976 J Chem Phys paperaper as well as in the 1992 J. Chem Phys paper of Bartlett and Ottewill, among others.  On the other hand, the early papers on this distribution were specifically applied to degrees of polymerization but were clear that they viewed the equivalent formula to be a weight average degree of polymerization.  It seems that at least Welch and Bloomfield in their 1973 j. pol sci paper and Klaus Huber 2012 now use Aragon and Pecora's number average formula but call it a weight average formula and compute a new number avarage formula therefrom.
> 
> At the end these are just numerical distributions and can both be used but the question is whether to add another distribution with the same name (which means making sure we distinguish somehow), leave as is based on the fact the the preponderance of usage in scattering seems to be the current SasView version of the distribution, or something else (such as providing different moments of the distribution, or plots of the distribution etc)

to:

> 1396606164123570


* **butler** commented:

After lengthy discussions and looking at papers and doing calculations it is clear that:
SasView assumes the underlying distribution is a number distribution and thereby the reported mean from that distribution is a number average parameter.  It properly weights that distribution by volume when fitting to the scattering data as is required to fit scattering data.  

However, from the perspective of the Schulz distribution, it is clear that the litterature has conflicting views about what the correct form of the number average Schulz should be. 

Fundamentally this means that there are TWO different distributions which are being called the Schulz distribution.  These are unfortunately related through the mass. 

SasView, like FISH and NIST IGOR macros, take their distribution from the M. Kotlarchyk and S-H. Chen (J. Chem. Phys. 79 (1983) 2461-2469) paper which specifically gives the distribution as being by number.  This is the same number Schulz distrbition given by Aragon and Pecora in their 1976 J Chem Phys paperaper as well as in the 1992 J. Chem Phys paper of Bartlett and Ottewill, among others.  On the other hand, the early papers on this distribution were specifically applied to degrees of polymerization but were clear that they viewed the equivalent formula to be a weight average degree of polymerization.  It seems that at least Welch and Bloomfield in their 1973 J. Pol. Sci. paper and Klaus Huber 2012 now use the same equation as Aragon and Pecora's number average formula but define it as a weight average formula and compute a new number avarage formula therefrom.

At the end these are just numerical distributions and can both be used but the question is whether to add another distribution with the same name (which means making sure we distinguish somehow), leave as is based on the fact the the preponderance of usage in scattering seems to be the current SasView version of the distribution, or something else (such as providing different moments of the distribution, or plots of the distribution etc)


* **butler** changed milestone from "SasView 3.0.0" to "Admin Tasks"
* **butler** changed owner from "Gonzalez" to "butler"
* **butler** changed status from "new" to "assigned"

**Comment by butlerpd** [comment]
Trac update at `2014/04/04 10:00:17`: **butler** changed owner from "butler" to "gonzales/butler/ajj/heenan"

**Comment by butlerpd** [comment]
Trac update at `2015/01/30 01:47:17`: **butler** changed workpackage from "" to "SasView Admin"

**Comment by butlerpd** [comment]
Trac update at `2015/02/01 23:43:42`: **butler** changed priority from "major" to "trivial"

**Comment by gonzalezma** [comment]
Trac update at `2015/02/27 11:46:56`: 
* **gonzalezm** commented:

Finally we have concluded that there is no problem with the Schulz distribution. Using the current definition for the z parameter describing the width of the distribution, it results that the weight distribution using the weight average has exactly the same mathematical form than the number distribution using the number average. Therefore there is no need to add an alternative Schulz distribution. The misunderstanding came from the fact that z is defined in some paper in an alternative way, so that z' = z+1, and in that case the weight and number distributions do not have the same mathematical form. Klaus Huber has checked this and agrees.


* **gonzalezm** changed resolution from "" to "invalid"
* **gonzalezm** changed status from "assigned" to "closed"

**Comment by smk78** [comment]
Trac update at `2015/03/04 13:04:13`: **smk78** commented:

Web FAQ updated accordingly.
