### ISSUE TITLE
Finish code reorg including removal of all mention of sans (Trac #218)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#366]
The code reorg cleaned up a number of things but left suff for phase 2.  we are now woant to finish restructuring folders and remove last vestiges of sans (from sansmodels, sans view, etc)

Migrated from http://trac.sasview.org/ticket/218
```json
{
    "status": "closed",
    "changetime": "2015-02-13T11:37:53",
    "_ts": "2015-02-13 11:37:53.614139+00:00",
    "description": "The code reorg cleaned up a number of things but left suff for phase 2.  we are now woant to finish restructuring folders and remove last vestiges of sans (from sansmodels, sans view, etc)\n",
    "reporter": "butler",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Framework Enhancements",
    "time": "2014-04-01T11:17:38",
    "component": "SasView",
    "summary": "Finish code reorg including removal of all mention of sans",
    "priority": "blocker",
    "keywords": "",
    "milestone": "SasView 3.1.0",
    "owner": "krzywon",
    "type": "defect"
}
```

**Comment by ajj** [comment]
Trac update at `2014/04/03 10:08:46`: **ajj** changed milestone from "SasView 3.0.0" to "SasView Next Release +1"

**Comment by butlerpd** [comment]
Trac update at `2015/01/30 01:03:51`: **butler** changed workpackage from "" to "SasView Admin"

**Comment by butlerpd** [comment]
Trac update at `2015/01/30 02:26:01`: **butler** changed workpackage from "SasView Admin" to "SasView Framework Enhancements"

**Comment by butlerpd** [comment]
Trac update at `2015/02/06 16:40:21`: 
* **butler** changed milestone from "SasView Next Release +1" to "SasView 3.1"
* **butler** changed priority from "minor" to "blocker"
