### ISSUE TITLE
Restructure documentation infrastructure - agree technology/plan (Trac #220)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#368]
Want to get model documentation to move to be in each model.  We also need an easy way to edit that and edit usage documentation.  Restructured Text with an editor and Latex editor for equations may be good solution.  Tasks:

1) research and agree on technology to use and implementation pland
2) implement

This ticket is about part 1.  Part 2 will be another ticket

Migrated from http://trac.sasview.org/ticket/220
```json
{
    "status": "closed",
    "changetime": "2015-11-22T01:18:33",
    "_ts": "2015-11-22 01:18:33.953547+00:00",
    "description": "Want to get model documentation to move to be in each model.  We also need an easy way to edit that and edit usage documentation.  Restructured Text with an editor and Latex editor for equations may be good solution.  Tasks:\n\n1) research and agree on technology to use and implementation pland\n2) implement\n\nThis ticket is about part 1.  Part 2 will be another ticket",
    "reporter": "butler",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView GUI Enhancements",
    "time": "2014-04-01T14:28:43",
    "component": "SasView",
    "summary": "Restructure documentation infrastructure - agree technology/plan",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 3.1.0",
    "owner": "Parker/Jackson/King/Butler",
    "type": "enhancement"
}
```

**Comment by smk78** [comment]
Trac update at `2014/04/04 12:45:43`: 
* **smk78** changed resolution from "" to "fixed"
* **smk78** changed status from "new" to "closed"

**Comment by butlerpd** [comment]
Trac update at `2015/11/22 01:18:33`: 
* **butler** changed milestone from "SasView Next Release +1" to "SasView 3.1.0"
* **butler** changed workpackage from "" to "SasView GUI Enhancements"
