### ISSUE TITLE
Restructure documentation infrastructure - implement (Trac #221)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#369]
Want to get model documentation to move to be in each model. We also need an easy way to edit that and edit usage documentation. Restructured Text with an editor and Latex editor for equations may be good solution. Tasks:
1) research and agree on technology to use and implementation pland
2) implement
This ticket is about part 2 after part 1 has been completed

Migrated from http://trac.sasview.org/ticket/221
```json
{
    "status": "closed",
    "changetime": "2015-02-21T14:52:19",
    "_ts": "2015-02-21 14:52:19.949224+00:00",
    "description": "Want to get model documentation to move to be in each model. We also need an easy way to edit that and edit usage documentation. Restructured Text with an editor and Latex editor for equations may be good solution. Tasks:\n1) research and agree on technology to use and implementation pland\n2) implement\nThis ticket is about part 2 after part 1 has been completed",
    "reporter": "butler",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Documentation",
    "time": "2014-04-01T14:32:01",
    "component": "SasView",
    "summary": "Restructure documentation infrastructure - implement",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 3.1.0",
    "owner": "King/Parker",
    "type": "task"
}
```

**Comment by smk78** [comment]
Trac update at `2014/04/04 12:46:34`: 
* **smk78** changed owner from "" to "King/Parker"
* **smk78** changed status from "new" to "assigned"

**Comment by butlerpd** [comment]
Trac update at `2015/01/30 00:11:34`: **butler** changed workpackage from "" to "SasView Documentation"

**Comment by butlerpd** [comment]
Trac update at `2015/02/01 23:21:06`: **butler** changed milestone from "SasView Next Release +1" to "SasView 3.1"

**Comment by butlerpd** [comment]
Trac update at `2015/02/01 23:38:37`: **butler** commented:

Need to integrate sphinx build of documentation with released exe and also provide PDF output for download of documentation from web (as well as html avaialble directly on web)

**Comment by butlerpd** [comment]
Trac update at `2015/02/21 14:52:19`: 
* **butler** commented:

this is now part of the sasmodels project.


* **butler** changed resolution from "" to "fixed"
* **butler** changed status from "assigned" to "closed"
