### ISSUE TITLE
Build System consistency and robustness- wiki pages (Trac #222)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#370]
Need to provide wiki page on how to access the Build systems

Migrated from http://trac.sasview.org/ticket/222
```json
{
    "status": "closed",
    "changetime": "2014-04-01T15:18:34",
    "_ts": "2014-04-01 15:18:34.980657+00:00",
    "description": "Need to provide wiki page on how to access the Build systems",
    "reporter": "butler",
    "cc": "",
    "resolution": "fixed",
    "time": "2014-04-01T14:39:51",
    "component": "SasView",
    "summary": "Build System consistency and robustness- wiki pages",
    "priority": "major",
    "keywords": "",
    "milestone": "Admin Tasks",
    "owner": "Jackson",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2014/04/01 14:48:54`: **butler** changed summary from "Build System consistency and robustness" to "Build System consistency and robustness- wiki pages"

**Comment by ajj** [comment]
Trac update at `2014/04/01 15:18:34`: 
* **ajj** changed resolution from "" to "fixed"
* **ajj** changed status from "new" to "closed"
