### ISSUE TITLE
Provide description of NIST 2D formats read by SasView (Trac #226)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#374]
SasView help states that the only 2D format read is the NIST 2D format (as .ASC or .DAT), but there is no online description of what this format(s) is.

Migrated from http://trac.sasview.org/ticket/226
```json
{
    "status": "closed",
    "changetime": "2015-11-22T01:19:47",
    "_ts": "2015-11-22 01:19:47.537726+00:00",
    "description": "SasView help states that the only 2D format read is the NIST 2D format (as .ASC or .DAT), but there is no online description of what this format(s) is.",
    "reporter": "smk78",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Documentation",
    "time": "2014-04-01T16:49:54",
    "component": "SasView",
    "summary": "Provide description of NIST 2D formats read by SasView",
    "priority": "major",
    "keywords": "2D, NIST",
    "milestone": "SasView 3.1.0",
    "owner": "butler",
    "type": "task"
}
```

**Comment by smk78** [comment]
Trac update at `2014/04/01 16:51:17`: 
* **smk78** changed owner from "" to "butler"
* **smk78** changed status from "new" to "assigned"

**Comment by butlerpd** [comment]
Trac update at `2014/04/04 10:01:29`: **butler** changed milestone from "SasView 3.0.0" to "Admin Tasks"

**Comment by butlerpd** [comment]
Trac update at `2014/04/04 10:02:02`: **butler** changed milestone from "Admin Tasks" to "SasView Next Release +1"

**Comment by butlerpd** [comment]
Trac update at `2014/05/18 19:45:55`: **butler** commented:

The information is on the IGOR/Trac page.  FAQ now links to it.  This should also be added to the help docs at some point.

**Comment by ajj** [comment]
Trac update at `2015/01/14 12:46:59`: **ajj** changed workpackage from "" to "SasView Documentation"

**Comment by smk78** [comment]
Trac update at `2015/02/17 16:54:02`: 
* **smk78** commented:

New help entry added to Sphinx docs build: Data Formats


* **smk78** changed resolution from "" to "fixed"
* **smk78** changed status from "assigned" to "closed"

**Comment by butlerpd** [comment]
Trac update at `2015/11/22 01:19:47`: **butler** changed milestone from "SasView Next Release +1" to "SasView 3.1.0"
