### ISSUE TITLE
Option to send data to fit panel cloned from existing one (Trac #231)

### ISSUE THREAD

**Issue by ajj** [SasView/sasview#379]
It is a pain to have to redo all the model parameters and panel settings for a new fit when you have just done one.

It should be possible to "send data to fit using clone of fit page x"

Migrated from http://trac.sasview.org/ticket/231
```json
{
    "status": "new",
    "changetime": "2017-10-26T09:39:32",
    "_ts": "2017-10-26 09:39:32.006635+00:00",
    "description": "It is a pain to have to redo all the model parameters and panel settings for a new fit when you have just done one.\n\nIt should be possible to \"send data to fit using clone of fit page x\"",
    "reporter": "ajj",
    "cc": "",
    "resolution": "",
    "workpackage": "SasView GUI Redesign",
    "time": "2014-04-03T10:12:22",
    "component": "SasView",
    "summary": "Option to send data to fit panel cloned from existing one",
    "priority": "minor",
    "keywords": "",
    "milestone": "SasView 5.1.0",
    "owner": "",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2014/04/05 20:56:47`: **butler** changed milestone from "SasView 3.0.0" to "SasView Next Release +1"

**Comment by butlerpd** [comment]
Trac update at `2015/01/30 02:14:59`: **butler** changed workpackage from "" to "SasView GUI Redesign"

**Comment by butlerpd** [comment]
Trac update at `2017/10/26 09:39:32`: 
* **butler** commented:

Actually copy paste should do almost all of this except for choosing the model so this should be a very minor issue unless I'm missing something.  Or is this ticket in fact obsolete now?


* **butler** changed milestone from "SasView Next Release +1" to "SasView 5.1.0"

**Comment by butlerpd** [comment]
Also we now have the option of swapping the data in a panel per @RichardHeenan which I think covers everything this issue was requesting so going to close this issue
