### ISSUE TITLE
Add warning about using the dataset drop down on Batch page (Trac #234)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#382]
The dropdown to select different datasets on the BATCH page should only be used for setting STARTING parameters, NOT for viewing the fit results (for which the 'View Fits' button on the Batch Grid window should be used).

Add a red message to the Batch page to this effect to warn users!

Migrated from http://trac.sasview.org/ticket/234
```json
{
    "status": "closed",
    "changetime": "2015-02-18T17:29:17",
    "_ts": "2015-02-18 17:29:17.020728+00:00",
    "description": "The dropdown to select different datasets on the BATCH page should only be used for setting STARTING parameters, NOT for viewing the fit results (for which the 'View Fits' button on the Batch Grid window should be used).\n\nAdd a red message to the Batch page to this effect to warn users!",
    "reporter": "smk78",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2014-04-04T16:15:14",
    "component": "SasView",
    "summary": "Add warning about using the dataset drop down on Batch page",
    "priority": "critical",
    "keywords": "Batch fitting",
    "milestone": "SasView 3.1.0",
    "owner": "",
    "type": "enhancement"
}
```

**Comment by butlerpd** [comment]
Trac update at `2014/04/05 20:47:07`: **butler** changed milestone from "SasView 3.0.0" to "SasView Next Release +1"

**Comment by ajj** [comment]
Trac update at `2015/01/14 12:37:22`: **ajj** changed workpackage from "" to "SasView Bug Fixing"

**Comment by butlerpd** [comment]
Trac update at `2015/02/01 23:06:27`: **butler** changed milestone from "SasView Next Release +1" to "SasView 3.1"
