### ISSUE TITLE
Remove the dataset drop down on single fit pages (Trac #235)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#383]
The dataset selection dropdown on single fit pages has no purpose.

It should be removed.

NB: It IS needed on Batch fit pages to set independent starting conditions.

Migrated from http://trac.sasview.org/ticket/235
```json
{
    "status": "closed",
    "changetime": "2014-04-05T09:39:02",
    "_ts": "2014-04-05 09:39:02.517766+00:00",
    "description": "The dataset selection dropdown on single fit pages has no purpose.\n\nIt should be removed.\n\nNB: It IS needed on Batch fit pages to set independent starting conditions.",
    "reporter": "smk78",
    "cc": "",
    "resolution": "fixed",
    "time": "2014-04-04T16:17:12",
    "component": "SasView",
    "summary": "Remove the dataset drop down on single fit pages",
    "priority": "minor",
    "keywords": "Fitting",
    "milestone": "SasView 3.0.0",
    "owner": "ajj",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2014/04/05 09:38:38`: 
* **butler** changed owner from "" to "ajj"
* **butler** changed status from "new" to "assigned"

**Comment by butlerpd** [comment]
Trac update at `2014/04/05 09:39:02`: 
* **butler** changed resolution from "" to "fixed"
* **butler** changed status from "assigned" to "closed"
