### ISSUE TITLE
Fix License.txt (Trac #240)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#388]
Once agreed on overal license for SasView, need to put license consistently everywhere and then write preamble and license in license.txt followed by all required copyright notices from packages used - see license survey

Migrated from http://trac.sasview.org/ticket/240
```json
{
    "status": "closed",
    "changetime": "2016-10-07T00:04:47",
    "_ts": "2016-10-07 00:04:47.096903+00:00",
    "description": "Once agreed on overal license for SasView, need to put license consistently everywhere and then write preamble and license in license.txt followed by all required copyright notices from packages used - see license survey",
    "reporter": "butler",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Documentation",
    "time": "2014-04-05T07:25:38",
    "component": "SasView",
    "summary": "Fix License.txt",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.1.0",
    "owner": "ajj",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2014/04/05 09:32:01`: 
* **butler** changed owner from "" to "butler"
* **butler** changed status from "new" to "assigned"

**Comment by butlerpd** [comment]
Trac update at `2014/05/31 15:35:03`: **butler** changed milestone from "SasView Next Release +1" to "SasView 3.0.1"

**Comment by ajj** [comment]
Trac update at `2015/01/14 12:46:59`: **ajj** changed workpackage from "" to "SasView Documentation"

**Comment by butlerpd** [comment]
Trac update at `2015/03/10 16:13:15`: 
* **butler** commented:

probably more work than there is time to do for this release and not really critical .. though we DO want to get something done soon.




* **butler** changed milestone from "SasView 3.1" to "SasView Next Release +1"

**Comment by butlerpd** [comment]
Trac update at `2016/09/05 02:59:21`: **butler** changed milestone from "SasView Next Release +1" to "SasView 4.1.0"

**Comment by ajj** [comment]
Trac update at `2016/10/07 00:03:51`: **ajj** changed owner from "butler" to "ajj"

**Comment by ajj** [comment]
Trac update at `2016/10/07 00:04:47`: 
* **ajj** commented:

Added License.txt for BSD 3 clause


* **ajj** changed resolution from "" to "fixed"
* **ajj** changed status from "assigned" to "closed"
