### ISSUE TITLE
Simultaneous Fit panel "easy setup" visually broken with wx 3.0 (Trac #241)

### ISSUE THREAD

**Issue by ajj** [SasView/sasview#389]
With wx 3, the "easy setup" bit on the simultaneous fit panel doesn't look correct until you resize the window.

The problem appears to be the default size of a combo box is different in wx 3.0 from in wx 2.8 and thus the packing in the box sizer doesn't work properly.

Not a functional failure, but it is a bit confusing

Migrated from http://trac.sasview.org/ticket/241
```json
{
    "status": "closed",
    "changetime": "2015-04-05T18:24:49",
    "_ts": "2015-04-05 18:24:49.768560+00:00",
    "description": "With wx 3, the \"easy setup\" bit on the simultaneous fit panel doesn't look correct until you resize the window.\n\nThe problem appears to be the default size of a combo box is different in wx 3.0 from in wx 2.8 and thus the packing in the box sizer doesn't work properly.\n\nNot a functional failure, but it is a bit confusing",
    "reporter": "ajj",
    "cc": "",
    "resolution": "wontfix",
    "workpackage": "SasView Bug Fixing",
    "time": "2014-04-05T08:37:52",
    "component": "SasView",
    "summary": "Simultaneous Fit panel \"easy setup\" visually broken with wx 3.0",
    "priority": "minor",
    "keywords": "",
    "milestone": "SasView 3.1.0",
    "owner": "ajj",
    "type": "defect"
}
```

**Comment by ajj** [comment]
Trac update at `2015/01/14 12:37:24`: **ajj** changed workpackage from "" to "SasView Bug Fixing"

**Comment by butlerpd** [comment]
Trac update at `2015/02/01 23:07:48`: **butler** changed milestone from "SasView Next Release +1" to "SasView 3.1"

**Comment by butlerpd** [comment]
Trac update at `2015/03/10 15:13:41`: **butler** commented:

Ask Andrew -- but could move or maybe just fix if easy

**Comment by butlerpd** [comment]
Trac update at `2015/03/24 14:38:47`: 
* **butler** changed owner from "" to "ajj"
* **butler** changed status from "new" to "assigned"

**Comment by ajj** [comment]
Trac update at `2015/04/05 18:24:49`: 
* **ajj** commented:

Closing as wont fix because this is a cosmetic issue that only appears on relatively low resolution screens (though admittedly that includes the default resolution on Macbook Airs and 13" Macbook pros)

Setting the resolution higher solves the issue. Could perhaps change the scaling for the panel so it uses more screen real estate but then the appearance of other panels would end up being annoying.


* **ajj** changed resolution from "" to "wontfix"
* **ajj** changed status from "assigned" to "closed"
