### ISSUE TITLE
Fix problem with with dire install warnings from OS (Trac #246)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#394]
Currently on newer Windows machines and some macs the operating system gives several dire warnings against installing the executable SasView appliation.  In fact in some cases the default is to not allow install and only by right clicking can one get options to "install anyway".  

Somehow this needs to be fixed.  Should look at what mac and windows will require - do we need to get a certification? how?

Migrated from http://trac.sasview.org/ticket/246
```json
{
    "status": "accepted",
    "changetime": "2019-03-23T14:07:17",
    "_ts": "2019-03-23 14:07:17.533099+00:00",
    "description": "Currently on newer Windows machines and some macs the operating system gives several dire warnings against installing the executable SasView appliation.  In fact in some cases the default is to not allow install and only by right clicking can one get options to \"install anyway\".  \n\nSomehow this needs to be fixed.  Should look at what mac and windows will require - do we need to get a certification? how?\n",
    "reporter": "butler",
    "cc": "",
    "resolution": "",
    "workpackage": "Support Infrastructure",
    "time": "2014-04-19T18:55:05",
    "component": "SasView",
    "summary": "Fix problem with with dire install warnings from OS",
    "priority": "critical",
    "keywords": "",
    "milestone": "Admin Tasks",
    "owner": "piotr",
    "type": "task"
}
```

**Comment by butlerpd** [comment]
Trac update at `2015/01/30 00:38:24`: **butler** changed workpackage from "" to "SasView Admin"

**Comment by rozyczko** [comment]
Trac update at `2016/11/10 08:53:30`: **piotr** commented:

This requires a special certificate - separate for mac and for windows.

To do this, a _legal_ entity (a person with power to sign legal documents on behalf of the institution) needs to register as a developer on the Apple dev site and on MSDN.
The membership is around $100 a year for apple and a one time ~$70 fee for MSDN.
We started this process at DMSC/ESS but due to bureaucratic inertia it will take a while to have it done.

Once we have the certificate, it is trivial to add a step to the build process in which the certificate is used to sign the binary installer.

**Comment by rozyczko** [comment]
Trac update at `2016/11/10 08:54:02`: **piotr** commented:

This will be ready no sooner than in 4.2

**Comment by rozyczko** [comment]
Trac update at `2016/11/10 08:54:22`: 
* **piotr** changed owner from "" to "piotr"
* **piotr** changed status from "new" to "accepted"

**Comment by rozyczko** [comment]
Trac update at `2019/02/05 09:43:11`: **piotr** commented:

This has been solved, at least for Windows. Both 4.x and 5.x installers from daily builds get automatically signed with the ESS binary signature.
It seems to be a tad more complicated for OSX, where an additional license from Apple is required.
We are working on it.

**Comment by butlerpd** [comment]
Trac update at `2019/02/26 14:44:15`: **butler** changed workpackage from "SasView Admin" to "Support Infrastructure"

**Comment by butlerpd** [comment]
Trac update at `2019/03/23 14:07:17`: **butler** changed priority from "major" to "critical"

**Comment by rozyczko** [comment]
This is now only about the macos signing certificate, I assume?
If so, the issue title should probably be changed because the current title is slightly misleading

**Comment by butlerpd** [comment]
Agreed. We should probably close this ticket and open a new one specifically for the  remaining issue.  That said, as we move from jenkins at ESS to git actions will this problem come back?  Perhaps we need a ticket about exploring an independent SasView windows and mac OS certificates?  Just a thought
