### ISSUE TITLE
On Mac with WX 3.0 can kill fitting perspective and can't get it back (Trac #250)

### ISSUE THREAD

**Issue by ajj** [SasView/sasview#398]
WX 3.0, OS X 10.9

Red window kill button is active and once killed you can't get the perspective back.

Migrated from http://trac.sasview.org/ticket/250
```json
{
    "status": "closed",
    "changetime": "2016-10-07T19:40:30",
    "_ts": "2016-10-07 19:40:30.346998+00:00",
    "description": "WX 3.0, OS X 10.9\n\nRed window kill button is active and once killed you can't get the perspective back.",
    "reporter": "ajj",
    "cc": "",
    "resolution": "wontfix",
    "workpackage": "SasView Bug Fixing",
    "time": "2014-04-22T13:46:25",
    "component": "SasView",
    "summary": "On Mac with WX 3.0 can kill fitting perspective and can't get it back",
    "priority": "minor",
    "keywords": "",
    "milestone": "SasView Next Release +1",
    "owner": "ajj",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2014/04/27 02:35:51`: 
* **butler** commented:

assuming this is only the case when using wx3.0-- in other words NOT a bug that needs fixing for this release which is still using wx2.8


* **butler** changed milestone from "SasView 3.0.0" to "SasView Next Release +1"

**Comment by ajj** [comment]
Trac update at `2015/01/14 12:37:24`: **ajj** changed workpackage from "" to "SasView Bug Fixing"

**Comment by butlerpd** [comment]
Trac update at `2015/02/01 23:08:35`: **butler** changed milestone from "SasView Next Release +1" to "SasView 3.1"

**Comment by butlerpd** [comment]
Trac update at `2015/03/24 14:39:10`: 
* **butler** changed owner from "" to "ajj"
* **butler** changed status from "new" to "assigned"

**Comment by ajj** [comment]
Trac update at `2015/04/05 18:34:31`: 
* **ajj** commented:

More testing that you can get the panel back by clicking on the Analysis menu and selecting Fitting even though it is currently checked. Thus downgrading this to Next Release +1. It is still rather annoying but not a fatal problem. Might need to add this to "known issues" section for the release notes.




* **ajj** changed milestone from "SasView 3.1" to "SasView Next Release +1"

**Comment by butlerpd** [comment]
Trac update at `2015/08/14 20:10:23`: **butler** changed milestone from "SasView Next Release +1" to "SasView 4.0.0"

**Comment by butlerpd** [comment]
Trac update at `2016/06/26 17:18:51`: 
* **butler** commented:

As agreed on fortnightly call of June 21, am moving all minor priority tickets to next release (+1) given the resources and time available to get this release out.


* **butler** changed milestone from "SasView 4.0.0" to "SasView Next Release +1"

**Comment by ajj** [comment]
Trac update at `2016/10/07 19:40:30`: 
* **ajj** commented:

Solution exists. New gui will come. Not worth effort fixing.


* **ajj** changed resolution from "" to "wontfix"
* **ajj** changed status from "assigned" to "closed"
