### ISSUE TITLE
Load menu item should be above quit in the file menu (Trac #255)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#403]
With the latest builds (7031 on PC and 7026 on mac) the File menu bar item has the "load file" and "load folder" listed below the quit item.  Expected behavior would have quit as the very last item on the menu.

entered by PDB but first reported by AJJ

Migrated from http://trac.sasview.org/ticket/255
```json
{
    "status": "closed",
    "changetime": "2014-05-07T17:36:22",
    "_ts": "2014-05-07 17:36:22.565434+00:00",
    "description": "With the latest builds (7031 on PC and 7026 on mac) the File menu bar item has the \"load file\" and \"load folder\" listed below the quit item.  Expected behavior would have quit as the very last item on the menu.\n\nentered by PDB but first reported by AJJ",
    "reporter": "butler",
    "cc": "",
    "resolution": "fixed",
    "time": "2014-05-06T13:41:32",
    "component": "SasView",
    "summary": "Load menu item should be above quit in the file menu",
    "priority": "minor",
    "keywords": "",
    "milestone": "SasView 3.0.0",
    "owner": "mathieu",
    "type": "defect"
}
```

**Comment by mdoucet** [comment]
Trac update at `2014/05/07 17:36:17`: 
* **mathieu** changed owner from "" to "mathieu"
* **mathieu** changed status from "new" to "accepted"

**Comment by mdoucet** [comment]
Trac update at `2014/05/07 17:36:22`: 
* **mathieu** changed resolution from "" to "fixed"
* **mathieu** changed status from "accepted" to "closed"
