### ISSUE TITLE
Mac has 2 about boxes and two quit buttons (Trac #256)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#404]
All applications on macs load a new menu item on the top left hand wich is named with the application name.  The top item in that drop down is "about."  Currently that does NOT link to the about which is under help (it goes nowhere).

Also there is a quit in that menu duplicting the quit under "file" but not clear it is doing exactly the same thing (i.e. is it really running the same code?)

Migrated from http://trac.sasview.org/ticket/256
```json
{
    "status": "closed",
    "changetime": "2015-11-22T02:01:46",
    "_ts": "2015-11-22 02:01:46.578869+00:00",
    "description": "All applications on macs load a new menu item on the top left hand wich is named with the application name.  The top item in that drop down is \"about.\"  Currently that does NOT link to the about which is under help (it goes nowhere).\n\nAlso there is a quit in that menu duplicting the quit under \"file\" but not clear it is doing exactly the same thing (i.e. is it really running the same code?)",
    "reporter": "butler",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2014-05-06T13:46:12",
    "component": "SasView",
    "summary": "Mac has 2 about boxes and two quit buttons",
    "priority": "minor",
    "keywords": "",
    "milestone": "SasView 3.1.0",
    "owner": "mathieu",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2014/05/20 14:47:14`: 
* **butler** commented:

This looks to be more difficult that it is worth for now so moving to wishlist as per agreement at conf call on May 20, 2014.


* **butler** changed milestone from "SasView 3.0.0" to "WishList"

**Comment by ajj** [comment]
Trac update at `2015/01/14 12:37:24`: **ajj** changed workpackage from "" to "SasView Bug Fixing"

**Comment by butlerpd** [comment]
Trac update at `2015/03/22 22:42:38`: **butler** commented:

the about problem is not there in latest build on Yosemite.  and quit seems to work both places.  Suggest we close this ticket.

**Comment by butlerpd** [comment]
Trac update at `2015/04/29 02:06:39`: **butler** commented:

actually, the exit is now only on the SasView menu item and not in the file menu.  The about item however appears nowhere at present.  Thinking we should close this ticket and open another one with a more informative name now?

**Comment by mdoucet** [comment]
Trac update at `2015/05/04 13:56:59`: 
* **mathieu** commented:

This has been fixed. The Help menu contains everything needed for the "about" information and there is one "quit" menu item.


* **mathieu** changed resolution from "" to "fixed"
* **mathieu** changed status from "new" to "closed"

**Comment by butlerpd** [comment]
Trac update at `2015/11/22 02:01:46`: **butler** changed milestone from "WishList" to "SasView 3.1.0"
