### ISSUE TITLE
about page on web needs updating (Trac #257)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#405]
The about page is now old and refers to things which have now changed.  This should be cleaned up.  Also we should find a place to put the base feature set for !SasView.  Not sure it is this page but ...  Also should update front page to mark release 2.2.1 prior to code camp

Migrated from http://trac.sasview.org/ticket/257
```json
{
    "status": "closed",
    "changetime": "2015-11-22T03:50:41",
    "_ts": "2015-11-22 03:50:41.950568+00:00",
    "description": "The about page is now old and refers to things which have now changed.  This should be cleaned up.  Also we should find a place to put the base feature set for !SasView.  Not sure it is this page but ...  Also should update front page to mark release 2.2.1 prior to code camp",
    "reporter": "butler",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Documentation",
    "time": "2014-05-12T00:00:23",
    "component": "SasView",
    "summary": "about page on web needs updating",
    "priority": "major",
    "keywords": "",
    "milestone": "Admin Tasks",
    "owner": "butler",
    "type": "enhancement"
}
```

**Comment by ajj** [comment]
Trac update at `2015/01/14 12:46:59`: **ajj** changed workpackage from "" to "SasView Documentation"

**Comment by butlerpd** [comment]
Trac update at `2015/11/22 03:50:41`: 
* **butler** commented:

This has now been done as of November 2015.


* **butler** changed description from "The about page is now old and refers to things which have now changed.  This should be cleaned up.  Also we should find a place to put the base feature set for SasView.  Not sure it is this page but ...  Also should update front page to mark release 2.2.1 prior to code camp" to "The about page is now old and refers to things which have now changed.  This should be cleaned up.  Also we should find a place to put the base feature set for !SasView.  Not sure it is this page but ...  Also should update front page to mark release 2.2.1 prior to code camp"
* **butler** changed resolution from "" to "fixed"
* **butler** changed status from "new" to "closed"
