### ISSUE TITLE
Windows installer problems when previous versions are not uninstalled (Trac #258)

### ISSUE THREAD

**Issue by ajj** [SasView/sasview#406]
First reported as "menu items and desktop shortcut labeled as 2.2.1" during testing of 3.0 release.  However see below for real issue.

Migrated from http://trac.sasview.org/ticket/258
```json
{
    "status": "closed",
    "changetime": "2017-10-27T10:59:53",
    "_ts": "2017-10-27 10:59:53.228543+00:00",
    "description": "First reported as \"menu items and desktop shortcut labeled as 2.2.1\" during testing of 3.0 release.  However see below for real issue.",
    "reporter": "ajj",
    "cc": "",
    "resolution": "duplicate",
    "workpackage": "SasView Bug Fixing",
    "time": "2014-05-18T18:54:53",
    "component": "SasView",
    "summary": "Windows installer problems when previous versions are not uninstalled",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView Next Release +1",
    "owner": "",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2014/05/18 19:43:20`: **butler** commented:

What platforme was this tested on.  The PC version has 3.0 on both the welcome and about page and is the name of the desktop shortcut.  Is this a problem with the mac bundler?  On the other hand it is always build 1 which makes it really annoying to figure out what version is being run from inside the application.  The welcome page used to capture the build number.  What happened and is that still possible?

**Comment by ajj** [comment]
Trac update at `2014/05/18 22:33:45`: **ajj** commented:

As per title, it was windows. Win7

I was mistaken about desktop icon (cluttered desktop), but start menu seemed to have only sasview entry, so can't have two versions in menu? Had to change install path to avoid overwriting previous. Likely not a problem for most users.

Can probably close this?

**Comment by butlerpd** [comment]
Trac update at `2014/05/20 12:52:57`: **butler** commented:

After more experimentation the problem seems to be the following:
1. If you install a new version without uninstalling the previous version but choose to install in the existing sasview directory, the start menu items do not change their name (but point to the new place) and any desktop icons is not removed (so now you have two) but the old one still points to the new version.
2. If you install a new version without unistalling the old BUT use a different directory then most things work as expected (you have two versions) except that the start menu folder is only  one and has the label of the old install.  Also because only one .sasview folder is created the configurations are shared.
3. Interestingly if you uninstall before running anything then .sasview directory is removed when running uninstall.  As soon as one runs sasview a .matplotlib directory is created and neither it nor the .sasview are removed during uninstall.

**Comment by butlerpd** [comment]
Trac update at `2014/05/20 14:51:14`: 
* **butler** commented:

The first issue stated is probably the most problematic but even that is not likely to be a huge problem for our users.  We should think carefully about the install for next release though and how it should behave.  Thus as agreed at fortnightly meeting of May 20, 2014 am moving this to next release tickets.  Meantime we will add this as a known issue.


* **butler** changed milestone from "SasView 3.0.0" to "SasView Next Release +1"

**Comment by butlerpd** [comment]
Trac update at `2014/05/31 15:37:11`: 
* **butler** changed description from "menu items and desktop shortcut labeled as 2.2.1" to "First reported as "menu items and desktop shortcut labeled as 2.2.1" during testing of 3.0 release.  However see below for real issue."
* **butler** changed summary from "Windows installer still installs Sasview as version 2.2.1" to "Windows installer problems whne previous versions are not uninstalled"

**Comment by ajj** [comment]
Trac update at `2015/01/14 12:37:23`: **ajj** changed workpackage from "" to "SasView Bug Fixing"

**Comment by butlerpd** [comment]
Trac update at `2015/02/01 21:56:27`: **butler** changed summary from "Windows installer problems whne previous versions are not uninstalled" to "Windows installer problems when previous versions are not uninstalled"

**Comment by rozyczko** [comment]
Trac update at `2016/11/09 14:24:56`: **piotr** commented:

I would consider this to be a feature of the windows installer. This is how most applications would behave.
1. Installing to the same directory - icons, entries in Start don't change
2. Installing to a new directory - two sets of icons and one entry in Start (duplicate name)
3. The install process creates .sasview and copies a few files in. If subsequently, new files get inside, the uninstaller will not delete those as it doesn't know anything about them.
Not deleting the new files = not deleting .sasview of course.

All this can be changed by modifying the installer configuration. 
Please specify exact requirements - then we can provide the requested functionality.

**Comment by ajj** [comment]
Trac update at `2016/11/09 14:30:25`: **ajj** commented:

I've noticed in my testing that (2) isn't what happens ... you get only one icon, pointing to the new version, but called the same as the old one.

We do need to redo the installer to allow multiple versions alongside each other if that is what the user chooses.

**Comment by butlerpd** [comment]
Trac update at `2017/10/27 10:59:53`: 
* **butler** commented:

This ticket is superseded by ticket #709 so closing this one down


* **butler** changed resolution from "" to "duplicate"
* **butler** changed status from "new" to "closed"
