### ISSUE TITLE
Unselect all data does not include sub-datasets (Trac #259)

### ISSUE THREAD

**Issue by ajj** [SasView/sasview#407]
For example, if you create an azimuthal average from a 2D dataset, that is a sub-dataset in the data explorer tree. Unselect all (and probably select all etc) does not traverse the tree and include such items.

Migrated from http://trac.sasview.org/ticket/259
```json
{
    "status": "closed",
    "changetime": "2016-10-07T00:12:42",
    "_ts": "2016-10-07 00:12:42.072908+00:00",
    "description": "For example, if you create an azimuthal average from a 2D dataset, that is a sub-dataset in the data explorer tree. Unselect all (and probably select all etc) does not traverse the tree and include such items.",
    "reporter": "ajj",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2014-05-18T18:56:17",
    "component": "SasView",
    "summary": "Unselect all data does not include sub-datasets",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.0.0",
    "owner": "lewis",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2014/05/18 19:56:19`: **butler** commented:

yes select also does not work.  However given one can generate a lot of those unknowingly it migt be good to have a nuance here. i.e. maybe if the tree is open (i.e. the subsets are visible in the data manager) then select/unselect all should work on them as well while any that are not visible (rolled back up to parent) do not get the selection?

**Comment by ajj** [comment]
Trac update at `2014/05/18 22:38:44`: **ajj** commented:

Hmm. I would suggest that unselect does all the tree but select only does visible? Or is that too confusing. You can have a lot and so if you've done a plot with lots on, closed them up to see better in explorer and want to plot something new then manually going through all to find the ones that are checked is very annoying....

**Comment by ajj** [comment]
Trac update at `2015/01/14 12:37:23`: **ajj** changed workpackage from "" to "SasView Bug Fixing"

**Comment by butlerpd** [comment]
Trac update at `2016/09/05 02:37:08`: 
* **butler** commented:

Again fixed by Lewis but "close" in the commit does not actually close ticket. Doing so now


* **butler** changed resolution from "" to "fixed"
* **butler** changed status from "assigned" to "closed"

**Comment by butlerpd** [comment]
Trac update at `2016/10/07 00:12:42`: **butler** changed milestone from "SasView Next Release +1" to "SasView 4.0.0"
