### ISSUE TITLE
Provide acknowledgement text from UI (Trac #262)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#410]
To assist SasView users to acknowledge the program, provide a 
link/button from the UI that causes some suitable text to be 
displayed.

Help > Welcome and Help > About don't quite capture what is required.

Migrated from http://trac.sasview.org/ticket/262
```json
{
    "status": "closed",
    "changetime": "2015-02-19T09:39:42",
    "_ts": "2015-02-19 09:39:42.052487+00:00",
    "description": "To assist SasView users to acknowledge the program, provide a \nlink/button from the UI that causes some suitable text to be \ndisplayed.\n\nHelp > Welcome and Help > About don't quite capture what is required.",
    "reporter": "smk78",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Admin",
    "time": "2014-05-22T13:56:00",
    "component": "SasView",
    "summary": "Provide acknowledgement text from UI",
    "priority": "major",
    "keywords": "Acknowledgement, GUI",
    "milestone": "SasView 3.1.0",
    "owner": "",
    "type": "enhancement"
}
```

**Comment by butlerpd** [comment]
Trac update at `2015/01/30 00:38:45`: **butler** changed workpackage from "" to "SasView Admin"

**Comment by butlerpd** [comment]
Trac update at `2015/01/31 17:32:16`: **butler** changed milestone from "Admin Tasks" to "SasView Next Release +1"

**Comment by butlerpd** [comment]
Trac update at `2015/02/01 23:02:04`: **butler** changed milestone from "SasView Next Release +1" to "SasView 3.1"
