### ISSUE TITLE
Running Sasview from the command line on linux fills the current directory with .pyc files (Trac #268)

### ISSUE THREAD

**Issue by ajj** [SasView/sasview#416]
When running Sasview from the command line on linux, all of the custom models (from .sasview/plugin_models) get compiled to .pyc files *in the current directory*.

Sasview should be using the .sasview/plugin_models folder for this.

Migrated from http://trac.sasview.org/ticket/268
```json
{
    "status": "new",
    "changetime": "2015-01-14T12:37:24",
    "_ts": "2015-01-14 12:37:24.291144+00:00",
    "description": "When running Sasview from the command line on linux, all of the custom models (from .sasview/plugin_models) get compiled to .pyc files *in the current directory*.\n\nSasview should be using the .sasview/plugin_models folder for this.",
    "reporter": "ajj",
    "cc": "",
    "resolution": "",
    "workpackage": "SasView Bug Fixing",
    "time": "2014-06-20T13:15:21",
    "component": "SasView",
    "summary": "Running Sasview from the command line on linux fills the current directory with .pyc files",
    "priority": "minor",
    "keywords": "",
    "milestone": "SasView Next Release +1",
    "owner": "",
    "type": "defect"
}
```

**Comment by ajj** [comment]
Trac update at `2015/01/14 12:37:24`: **ajj** changed workpackage from "" to "SasView Bug Fixing"

**Comment by butlerpd** [comment]
@llimeht do you agree that this can be closed as obsolete if not fixed fully?

**Comment by butlerpd** [comment]
actually, rereading this ticket I think it is in fact totally obsolete (from June of 2014) - so I will close it.
