### ISSUE TITLE
Verify that BUMPS is computing reduced chisq correctly (Trac #270)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#418]
The Park optimiser is not computing reduced chisq correctly resulting
in it returning uncertainties that are larger (by a factor 5 - 10) 
than they should be.

See attached files.

Migrated from http://trac.sasview.org/ticket/270
```json
{
    "status": "closed",
    "changetime": "2016-03-20T12:07:58",
    "_ts": "2016-03-20 12:07:58.883340+00:00",
    "description": "The Park optimiser is not computing reduced chisq correctly resulting\nin it returning uncertainties that are larger (by a factor 5 - 10) \nthan they should be.\n\nSee attached files.",
    "reporter": "smk78",
    "cc": "",
    "resolution": "wontfix",
    "workpackage": "SasView QA and testing",
    "time": "2014-07-15T09:35:15",
    "component": "SasView",
    "summary": "Verify that BUMPS is computing reduced chisq correctly",
    "priority": "critical",
    "keywords": "Park, uncertainties, chisq",
    "milestone": "SasView 4.0.0",
    "owner": "",
    "type": "task"
}
```

**Comment by smk78** [comment]
Trac update at `2014/07/15 09:36:03`: 
* **smk78** changed attachment from "" to "RE Error estimates from fits.pdf"
* **smk78** commented:

Initial error report

**Comment by smk78** [comment]
Trac update at `2014/07/15 09:36:37`: 
* **smk78** changed attachment from "" to "RE Error estimates from fits - updated.pdf"
* **smk78** commented:

Evaluation of the promblem by Paul K

**Comment by smk78** [comment]
Trac update at `2014/07/15 09:37:53`: **smk78** commented:

Since the Park optimiser is to be replaced by Bumps, does this error need to be fixed?

**Comment by ajj** [comment]
Trac update at `2015/01/14 12:37:22`: **ajj** changed workpackage from "" to "SasView Bug Fixing"

**Comment by butlerpd** [comment]
Trac update at `2015/02/15 15:19:14`: 
* **butler** changed owner from "" to "smk78"
* **butler** changed status from "new" to "assigned"
* **butler** changed summary from "Park optimiser is not computing reduced chisq correctly" to "Verify that BUMPS is computing reduced chisq correctly"

**Comment by butlerpd** [comment]
Trac update at `2015/02/15 15:21:22`: **butler** commented:

OOps .. should have added the comment when changing title from "PARK does not compute ..." to the current title.  Since we are removing PARK the ticket made no sense.  However Paul suggests we double check that BUMPS is doing it correctly before closing this ticket.  So have renamed.

**Comment by butlerpd** [comment]
Trac update at `2015/03/10 14:32:55`: **butler** commented:

check that LM and the Nelder Mead simplex give similar results using previous set from the PARK ticket.  Steve to submit

**Comment by smk78** [comment]
Trac update at `2015/03/10 16:07:54`: **smk78** commented:

Added email thread with Users SasView 3.0.0 fit uncertainties, and users data set.

**Comment by smk78** [comment]
Trac update at `2015/03/10 16:08:33`: 
* **smk78** changed attachment from "" to "error-estimates-from-fits-email-thread.pdf"
* **smk78** commented:

email thread

**Comment by smk78** [comment]
Trac update at `2015/03/10 16:09:06`: 
* **smk78** changed attachment from "" to "25330_add_var_merged.xml.txt"
* **smk78** commented:

users data (strip .txt from end before use)

**Comment by butlerpd** [comment]
Trac update at `2015/03/22 22:53:39`: 
* **butler** changed type from "defect" to "task"
* **butler** changed workpackage from "SasView Bug Fixing" to "SasView QA and testing"

**Comment by butlerpd** [comment]
Trac update at `2015/04/07 15:02:06`: **butler** changed owner from "smk78" to ""

**Comment by ajj** [comment]
Trac update at `2015/05/06 13:49:43`: **ajj** changed milestone from "SasView 3.1" to "SasView Next Release +1"

**Comment by butlerpd** [comment]
Trac update at `2015/08/14 19:45:40`: **butler** changed milestone from "SasView Next Release +1" to "SasView 4.0.0"

**Comment by ajj** [comment]
Trac update at `2016/03/20 12:07:58`: 
* **ajj** commented:

Too much has changed for this ticket to still be possible to deal with. If we see any issues in future, raise new ticket.


* **ajj** changed resolution from "" to "wontfix"
* **ajj** changed status from "assigned" to "closed"
