### ISSUE TITLE
Install deletes model plugin .py files! (Trac #272)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#419]
Discovered by Richard Heenan; verified by me. Windows build.

Affects release versions 2.2.1 and 3.0.0.

Installing the SasView release versions causes model plugin .py files
to be compiled to .pyc as expected.

However, the .py files are then being deleted!!!

And, counter-intuitively, the .pyc files are ending up in the SasView
top level folder and not in the plugin_models  sub-folder (in fact,
the latter is completely empty!)

Migrated from http://trac.sasview.org/ticket/272
```json
{
    "status": "new",
    "changetime": "2015-02-01T23:19:41",
    "_ts": "2015-02-01 23:19:41.017871+00:00",
    "description": "Discovered by Richard Heenan; verified by me. Windows build.\n\nAffects release versions 2.2.1 and 3.0.0.\n\nInstalling the SasView release versions causes model plugin .py files\nto be compiled to .pyc as expected.\n\nHowever, the .py files are then being deleted!!!\n\nAnd, counter-intuitively, the .pyc files are ending up in the SasView\ntop level folder and not in the plugin_models  sub-folder (in fact,\nthe latter is completely empty!)\n",
    "reporter": "smk78",
    "cc": "",
    "resolution": "",
    "workpackage": "SasView Bug Fixing",
    "time": "2014-10-20T11:20:37",
    "component": "SasView",
    "summary": "Install deletes model plugin .py files!",
    "priority": "minor",
    "keywords": "",
    "milestone": "SasView Next Release +1",
    "owner": "",
    "type": "defect"
}
```

**Comment by ajj** [comment]
Trac update at `2014/10/20 11:33:23`: **ajj** commented:

Can you confirm that the .py files are being deleted from the sasview folder in the users' home directory? When are they deleted - on installation or on running SasView (installation will not compile anything, only running sasview will).

The symptom of deletion from all relevant locations would be that there are no models in the 'Customized models' category within sasview.

The .pyc files are always generated wherever sa(n)sview.py is run from (this is a particular annoyance on linux) and so have probably always been generated in the top level directory.

**Comment by smk78** [comment]
Trac update at `2014/10/20 12:44:45`: 
* **smk78** commented:

Ahh! Ok, our mistake.

The .py (and .pyc) files are in C:\Users\{user}\.sasview\plugin_models, so the .pyc must then be copied from there to C:\Program Files (x86)\SasView. We were looking at C:\Program Files (x86)\SasView\plugin_models. If you put a .py in the latter then what we say is true.

This could be kind of irritating to a user who doesn't know to use the app-specific location in their profile. Maybe we should 'tidy' this behaviour up?

Am downgrading priority from critical to minor.




* **smk78** changed priority from "critical" to "minor"

**Comment by smk78** [comment]
Trac update at `2014/10/22 08:56:35`: **smk78** commented:

We note that when SasView restarts newer .pyc's get generated, as you might expect. But they are generated in C:\Users\{user}\.sasview\plugin_models. Older versions of .pyc's with the same name (perhaps from initial installation compilation???) remain in C:\Program Files (x86)\SasView\plugin_models.

Which .pyc's take priority?

**Comment by ajj** [comment]
Trac update at `2015/01/14 12:37:24`: **ajj** changed workpackage from "" to "SasView Bug Fixing"

**Comment by butlerpd** [comment]
Trac update at `2015/02/01 23:19:41`: **butler** commented:

We should wait till the new model interface is implemented which may change many of these things anyway and then revisit this ticket to see if it is obsolete or still needs "tidying up"

**Comment by krzywon** [comment]
No longer an issue
