### ISSUE TITLE
Save Analysis in File Menu greyed out after fitting a model! (Trac #275)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#422]
Hello!
When trying to “Save Analysis” after fitting a model, the option is grayed out and disappears. I’ve attached a screen shot just to confirm.

If I start with a new model, and before pressing “Fit”, I can “Save Analysis”. Afterwards, I can fit the model and then save the fitted analysis. After that if I change models again, AGAIN I need to “Save Analysis” first, or I can’t save anything if I try to Fit the model first. 

Opening the analyses gave no issues.

Not a major issue, but without finding the loophole, would be annoying. Hope the phrasing wasn’t too confusing.

Thanks!
Happy Thoughts,
Jes

jessie.sun@nist.gov

Migrated from http://trac.sasview.org/ticket/275
```json
{
    "status": "closed",
    "changetime": "2015-11-22T01:21:50",
    "_ts": "2015-11-22 01:21:50.946287+00:00",
    "description": "Hello!\nWhen trying to \u201cSave Analysis\u201d after fitting a model, the option is grayed out and disappears. I\u2019ve attached a screen shot just to confirm.\n\nIf I start with a new model, and before pressing \u201cFit\u201d, I can \u201cSave Analysis\u201d. Afterwards, I can fit the model and then save the fitted analysis. After that if I change models again, AGAIN I need to \u201cSave Analysis\u201d first, or I can\u2019t save anything if I try to Fit the model first. \n\nOpening the analyses gave no issues.\n\nNot a major issue, but without finding the loophole, would be annoying. Hope the phrasing wasn\u2019t too confusing.\n\nThanks!\nHappy Thoughts,\nJes\n\njessie.sun@nist.gov",
    "reporter": "smk78",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2014-12-04T09:44:54",
    "component": "SasView",
    "summary": "Save Analysis in File Menu greyed out after fitting a model!",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 3.1.0",
    "owner": "",
    "type": "defect"
}
```

**Comment by smk78** [comment]
Trac update at `2014/12/04 09:45:21`: 
* **smk78** changed attachment from "" to "JS-ScreenShot-SASview-UnableToSaveAnalysisError-03Dec14.png"
* **smk78** commented:

Screen shot illustrating bug

**Comment by smk78** [comment]
Trac update at `2014/12/11 10:22:47`: **smk78** commented:

Would (2) be an easy interim fix?

**Comment by butlerpd** [comment]
Trac update at `2015/11/22 01:21:50`: **butler** changed milestone from "SasView Next Release +1" to "SasView 3.1.0"
