### ISSUE TITLE
Provide better error message when CanSAS file has invalid units (Trac #276)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#423]
Currently, if a CanSAS file with unsupported units is loaded into 
SasView - for example, <I unit="count"> where "count" is not defined 
in the standard - the following error message is returned when one 
attempts to plot/fit the data:

'Plotting Error: Plottable.View: Given y and x are not of the same 
length'

This is confusing (as it insinuates either Q or I data is missing) 
but also draws attention away from the underlying problem.

Some form of syntactic checking is required and failure should respond 
with a sensible error message.

Migrated from http://trac.sasview.org/ticket/276
```json
{
    "status": "closed",
    "changetime": "2015-02-14T16:56:23",
    "_ts": "2015-02-14 16:56:23.910317+00:00",
    "description": "Currently, if a CanSAS file with unsupported units is loaded into \nSasView - for example, <I unit=\"count\"> where \"count\" is not defined \nin the standard - the following error message is returned when one \nattempts to plot/fit the data:\n\n'Plotting Error: Plottable.View: Given y and x are not of the same \nlength'\n\nThis is confusing (as it insinuates either Q or I data is missing) \nbut also draws attention away from the underlying problem.\n\nSome form of syntactic checking is required and failure should respond \nwith a sensible error message.\n",
    "reporter": "smk78",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2014-12-19T11:47:14",
    "component": "SasView",
    "summary": "Provide better error message when CanSAS file has invalid units",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 3.1.0",
    "owner": "",
    "type": "enhancement"
}
```

**Comment by smk78** [comment]
Trac update at `2014/12/23 09:41:28`: **smk78** commented:

ARR (who reported the above bug) adds:

My real point is there seems to be no strong reason for SasView to reject canSAS data files that do not conform if it could read them.  A warning might help people but rejection if a more useful path is feasible seems to be likely to put off users. 

SMK78 holds the view that:

If the SasView loader is rejecting (leaving aside how gracefully it is doing so) canSAS format data that isn't actually compliant with the agreed standard then it is doing its job! Otherwise, why have a standard?! If people see a need to wrap non-compliant data in the canSAS format then the proper course of action should surely be to discuss possible extensions of the format with canSAS, rather than request arbitrary adaptions of SasView?

**Comment by butlerpd** [comment]
Trac update at `2015/02/01 23:16:11`: **butler** changed milestone from "SasView Next Release +1" to "SasView 3.1"
