### ISSUE TITLE
How does/should SasView handle zero intensities? (Trac #277)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#424]
Zero intensities can arise in a reduced data file as a result of 
'beam blocked' or 'electronic background' measurements, or masking.

Issues arising are:
- how does one discern between genuinely zero intensities and 
intensities that (for whatever reason) are unknown or to be ignored;

- what uncertainty should be assigned to a zero intensity? (The issue 
of zero uncertainties has been previously raised as a problem);

- should SasView have a 'how to handle zeros' option in its View -> 
Startup Setting, for example (AJJ suggestion)?

Migrated from http://trac.sasview.org/ticket/277
```json
{
    "status": "new",
    "changetime": "2014-12-23T09:53:39",
    "_ts": "2014-12-23 09:53:39.528593+00:00",
    "description": "Zero intensities can arise in a reduced data file as a result of \n'beam blocked' or 'electronic background' measurements, or masking.\n\nIssues arising are:\n- how does one discern between genuinely zero intensities and \nintensities that (for whatever reason) are unknown or to be ignored;\n\n- what uncertainty should be assigned to a zero intensity? (The issue \nof zero uncertainties has been previously raised as a problem);\n\n- should SasView have a 'how to handle zeros' option in its View -> \nStartup Setting, for example (AJJ suggestion)?\n",
    "reporter": "smk78",
    "cc": "",
    "resolution": "",
    "workpackage": "SasView Fitting Redesign",
    "time": "2014-12-23T09:53:39",
    "component": "SasView",
    "summary": "How does/should SasView handle zero intensities?",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView Next Release +1",
    "owner": "",
    "type": "enhancement"
}
```

**Comment by lucas-wilkins** [comment]
Looks like this has probably be decided?

**Comment by butlerpd** [comment]
We should close this.  I believe this discussion took place a while ago.  The main issue is when plotting zeros (and negatives) on a log log plot but that I believe has been sorted (they don't plot but don't throw errors).  The issue of uncertainties on zero **reduced** intensities should be given by the data set (i.e. by the reduction process which is the **only** thing that can possibly know.  If the reduction program does not provide an errors than all data, including zero will be treated as not having uncertainties.  @smk78 - can we close?

**Comment by smk78** [comment]
Fair comments are made by @butlerpd . And, having _actually_ checked the behaviour of a dataset with a zero intensity, I can confirm SasView does indeed ignore the affected datapoint. So I will close this issue.
