### ISSUE TITLE
Problem with multishell model - glitches at high Q (Trac #288)

### ISSUE THREAD

**Issue by ajj** [SasView/sasview#425]
The multishell model has artifacts that appear when the dimension of the core is greater than some value (depends on Q range whether the artefacts are within the range).

Same problem appears in IGOR, so it is an underlying model issue. Suspect a problem with either integration or bessel function precision.

This needs fixing ASAP

Migrated from http://trac.sasview.org/ticket/288
```json
{
    "status": "closed",
    "changetime": "2016-10-07T00:09:25",
    "_ts": "2016-10-07 00:09:25.546237+00:00",
    "description": "The multishell model has artifacts that appear when the dimension of the core is greater than some value (depends on Q range whether the artefacts are within the range).\n\nSame problem appears in IGOR, so it is an underlying model issue. Suspect a problem with either integration or bessel function precision.\n\nThis needs fixing ASAP",
    "reporter": "ajj",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2015-01-12T07:55:50",
    "component": "SasView",
    "summary": "Problem with multishell model - glitches at high Q",
    "priority": "critical",
    "keywords": "",
    "milestone": "SasView 4.1.0",
    "owner": "ajj",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2015/03/10 16:21:21`: 
* **butler** commented:

This probably is best worked through as part of new sasmodels.  Since has existed in IGOR code for a while already and will require probably a fair amount of sleuthing that we may not have the bandwidth for we won't hold up the release 3.1 to fix this 


* **butler** changed milestone from "SasView 3.1" to "SasView Next Release +1"

**Comment by butlerpd** [comment]
Trac update at `2015/08/14 19:50:57`: **butler** changed milestone from "SasView Next Release +1" to "SasView 4.0.0"

**Comment by ajj** [comment]
Trac update at `2016/02/28 11:20:13`: **ajj** changed priority from "major" to "critical"

**Comment by butlerpd** [comment]
Trac update at `2016/08/16 14:52:12`: 
* **butler** commented:

once again running out of bandwidth to check this for the upcoming release 4.0 -- moving to next release 


* **butler** changed milestone from "SasView 4.0.0" to "SasView Next Release +1"

**Comment by pkienzle** [comment]
Trac update at `2016/08/30 19:52:54`: **pkienzle** commented:

This ticket needs specific parameter values to check against, as well as a description of the artefacts.  Many of the models have been updated to use more accurate bessel function approximations, at least for small qr, so this may already have been fixed.

**Comment by RichardHeenan** [comment]
Trac update at `2016/10/05 13:42:25`: 
* **richardh** commented:

Symptom - regular glitches in I(Q) at high Q when using polydispersity in any core shell model.

FIX - users should increase number of steps NPTS and/or number of sigmas NSIGS to integrate over, in the polydispersity integral


* **richardh** changed resolution from "" to "fixed"
* **richardh** changed status from "new" to "closed"
* **richardh** changed summary from "Problem with multishell model" to "Problem with multishell model - glitches at high Q"

**Comment by butlerpd** [comment]
Trac update at `2016/10/07 00:09:25`: **butler** changed milestone from "SasView Next Release +1" to "SasView 4.1.0"
