### ISSUE TITLE
Move windows build batch file to repository (Trac #296)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#431]
The windows build batch file should be moved into the repo (as was done with bash script for linux).  Same should be done for every build system supported.

Migrated from http://trac.sasview.org/ticket/296
```json
{
    "status": "closed",
    "changetime": "2016-05-24T14:30:11",
    "_ts": "2016-05-24 14:30:11.836845+00:00",
    "description": "The windows build batch file should be moved into the repo (as was done with bash script for linux).  Same should be done for every build system supported.",
    "reporter": "butler",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Admin",
    "time": "2015-01-31T17:12:06",
    "component": "SasView",
    "summary": "Move windows build batch file to repository",
    "priority": "critical",
    "keywords": "",
    "milestone": "Admin Tasks",
    "owner": "",
    "type": "enhancement"
}
```

**Comment by butlerpd** [comment]
Trac update at `2015/02/01 23:02:52`: **butler** changed milestone from "SasView Next Release +1" to "Admin Tasks"

**Comment by butlerpd** [comment]
Trac update at `2015/02/01 23:44:34`: **butler** changed priority from "major" to "critical"

**Comment by ajj** [comment]
Trac update at `2015/11/25 12:43:33`: **ajj** commented:

The batch file exists in the repo, but doesn't seem to be used by jenkins... Is there a reason for this?
