### ISSUE TITLE
Unit testing infrastructure is broken (Trac #301)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#436]
All unit tests should be running and passing, and all modules should have working unit tests.

Migrated from http://trac.sasview.org/ticket/301
```json
{
    "status": "closed",
    "changetime": "2015-03-02T18:34:25",
    "_ts": "2015-03-02 18:34:25.694101+00:00",
    "description": "All unit tests should be running and passing, and all modules should have working unit tests.",
    "reporter": "butler",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView QA and testing",
    "time": "2015-02-02T00:09:03",
    "component": "SasView",
    "summary": "Unit testing infrastructure is broken",
    "priority": "critical",
    "keywords": "",
    "milestone": "Admin Tasks",
    "owner": "",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2015/02/11 17:45:12`: **butler** changed workpackage from "SasView Admin" to "SasView QA and testing"

**Comment by mdoucet** [comment]
Trac update at `2015/03/02 18:34:25`: 
* **mathieu** commented:

This now works.


* **mathieu** changed resolution from "" to "fixed"
* **mathieu** changed status from "new" to "closed"
