### ISSUE TITLE
Replace pisa with xhtml2pdf (Trac #302)

### ISSUE THREAD

**Issue by ajj** [SasView/sasview#437]
The pisa package seems to be abandoned and has been picked up and continues to be maintained as xhtml2pdf: https://pypi.python.org/pypi/xhtml2pdf

We should drop the dependency on pisa and switch to the new package.

Migrated from http://trac.sasview.org/ticket/302
```json
{
    "status": "closed",
    "changetime": "2015-02-17T16:58:53",
    "_ts": "2015-02-17 16:58:53.054851+00:00",
    "description": "The pisa package seems to be abandoned and has been picked up and continues to be maintained as xhtml2pdf: https://pypi.python.org/pypi/xhtml2pdf\n\nWe should drop the dependency on pisa and switch to the new package.",
    "reporter": "ajj",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView QA and testing",
    "time": "2015-02-11T12:56:07",
    "component": "SasView",
    "summary": "Replace pisa with xhtml2pdf",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 3.1.0",
    "owner": "mathieu",
    "type": "defect"
}
```

**Comment by mdoucet** [comment]
Trac update at `2015/02/17 14:13:15`: 
* **mathieu** changed owner from "" to "mathieu"
* **mathieu** changed status from "new" to "assigned"

**Comment by mdoucet** [comment]
Trac update at `2015/02/17 16:58:53`: 
* **mathieu** changed resolution from "" to "fixed"
* **mathieu** changed status from "assigned" to "closed"
