### ISSUE TITLE
Obtain DOI for Sasview releases (Trac #311)

### ISSUE THREAD

**Issue by ajj** [SasView/sasview#446]
Connect github to zenodo and get DOIs

These can then be used to cite the code.

Migrated from http://trac.sasview.org/ticket/311
```json
{
    "status": "closed",
    "changetime": "2015-02-21T14:42:57",
    "_ts": "2015-02-21 14:42:57.692869+00:00",
    "description": "Connect github to zenodo and get DOIs\n\nThese can then be used to cite the code.",
    "reporter": "ajj",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Admin",
    "time": "2015-02-13T13:56:04",
    "component": "SasView",
    "summary": "Obtain DOI for Sasview releases",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 3.1.0",
    "owner": "ajj",
    "type": "task"
}
```

**Comment by ajj** [comment]
Trac update at `2015/02/13 13:56:09`: 
* **ajj** changed owner from "" to "ajj"
* **ajj** changed status from "new" to "assigned"

**Comment by butlerpd** [comment]
Trac update at `2015/02/21 14:42:57`: 
* **butler** commented:

Andrew set this up on github - next release will have a DOI assigned.


* **butler** changed resolution from "" to "fixed"
* **butler** changed status from "assigned" to "closed"
