### ISSUE TITLE
Python polydispersity (Trac #313)

### ISSUE THREAD

**Issue by ajj** [SasView/sasview#448]
Add polydispersity loop generation for python models 

Migrated from http://trac.sasview.org/ticket/313
```json
{
    "status": "closed",
    "changetime": "2015-11-22T01:26:07",
    "_ts": "2015-11-22 01:26:07.110269+00:00",
    "description": "Add polydispersity loop generation for python models ",
    "reporter": "ajj",
    "cc": "",
    "resolution": "wontfix",
    "workpackage": "SasModels Redesign",
    "time": "2015-02-14T11:02:55",
    "component": "SasView",
    "summary": "Python polydispersity",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 3.1.0",
    "owner": "",
    "type": "task"
}
```

**Comment by butlerpd** [comment]
Trac update at `2015/02/19 22:58:53`: 
* **butler** commented:

move to release 4.0


* **butler** changed milestone from "SasView 3.1" to "SasView Next Release +1"

**Comment by butlerpd** [comment]
Trac update at `2015/02/20 09:58:27`: 
* **butler** changed resolution from "" to "fixed"
* **butler** changed status from "new" to "closed"

**Comment by butlerpd** [comment]
Trac update at `2015/11/22 01:25:55`: 
* **butler** changed milestone from "SasView Next Release +1" to "SasView 3.1.0"
* **butler** changed resolution from "fixed" to ""
* **butler** changed status from "closed" to "reopened"

**Comment by butlerpd** [comment]
Trac update at `2015/11/22 01:26:07`: 
* **butler** changed resolution from "" to "wontfix"
* **butler** changed status from "reopened" to "closed"
