### ISSUE TITLE
Default to GPU when using OpenCL (Trac #314)

### ISSUE THREAD

**Issue by ajj** [SasView/sasview#449]
Set code to default to using the GPU when using OpenCL

Migrated from http://trac.sasview.org/ticket/314
```json
{
    "status": "closed",
    "changetime": "2015-11-22T01:27:36",
    "_ts": "2015-11-22 01:27:36.526509+00:00",
    "description": "Set code to default to using the GPU when using OpenCL",
    "reporter": "ajj",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasModels Redesign",
    "time": "2015-02-14T11:04:21",
    "component": "SasView",
    "summary": "Default to GPU when using OpenCL",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.0.0",
    "owner": "",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2015/02/19 22:59:19`: 
* **butler** commented:

move to release 4.0


* **butler** changed milestone from "SasView 3.1" to "SasView Next Release +1"

**Comment by butlerpd** [comment]
Trac update at `2015/11/22 01:27:14`: 
* **butler** changed milestone from "SasView Next Release +1" to "SasView 3.1.0"
* **butler** changed resolution from "fixed" to ""
* **butler** changed status from "closed" to "reopened"

**Comment by butlerpd** [comment]
Trac update at `2015/11/22 01:27:36`: 
* **butler** changed milestone from "SasView 3.1.0" to "SasView 4.0.0"
* **butler** changed resolution from "" to "fixed"
* **butler** changed status from "reopened" to "closed"
