### ISSUE TITLE
Be able to set choice of device for OpenCL (Trac #315)

### ISSUE THREAD

**Issue by ajj** [SasView/sasview#450]
Allow code to take a user parameter to define which device OpenCL uses.

Migrated from http://trac.sasview.org/ticket/315
```json
{
    "status": "closed",
    "changetime": "2015-11-22T01:29:05",
    "_ts": "2015-11-22 01:29:05.876233+00:00",
    "description": "Allow code to take a user parameter to define which device OpenCL uses.",
    "reporter": "ajj",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasModels Redesign",
    "time": "2015-02-14T11:05:45",
    "component": "SasView",
    "summary": "Be able to set choice of device for OpenCL",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.0.0",
    "owner": "",
    "type": "task"
}
```

**Comment by butlerpd** [comment]
Trac update at `2015/02/19 23:00:06`: 
* **butler** commented:

move to release 4.0


* **butler** changed milestone from "SasView 3.1" to "SasView Next Release +1"

**Comment by butlerpd** [comment]
Trac update at `2015/02/20 10:07:02`: 
* **butler** changed resolution from "" to "fixed"
* **butler** changed status from "new" to "closed"

**Comment by butlerpd** [comment]
Trac update at `2015/11/22 01:29:05`: **butler** changed milestone from "SasView Next Release +1" to "SasView 4.0.0"
