### ISSUE TITLE
Packaging of sasmodels (build scripts etc) (Trac #317)

### ISSUE THREAD

**Issue by ajj** [SasView/sasview#452]
Set up build scripts etc to generate sasmodels package.

Migrated from http://trac.sasview.org/ticket/317
```json
{
    "status": "closed",
    "changetime": "2016-06-06T11:13:05",
    "_ts": "2016-06-06 11:13:05.012139+00:00",
    "description": "Set up build scripts etc to generate sasmodels package.",
    "reporter": "ajj",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasModels Redesign",
    "time": "2015-02-14T11:08:29",
    "component": "SasView",
    "summary": "Packaging of sasmodels (build scripts etc)",
    "priority": "blocker",
    "keywords": "",
    "milestone": "SasView 4.0.0",
    "owner": "trnielsen",
    "type": "defect"
}
```

**Comment by ajj** [comment]
Trac update at `2015/02/14 11:08:43`: 
* **ajj** changed milestone from "SasView Next Release +1" to "SasView 3.1"
* **ajj** changed workpackage from "SasView Bug Fixing" to "SasModels Redesign"

**Comment by butlerpd** [comment]
Trac update at `2015/02/19 23:01:01`: 
* **butler** commented:

move to release 4.0


* **butler** changed milestone from "SasView 3.1" to "SasView Next Release +1"

**Comment by butlerpd** [comment]
Trac update at `2015/08/14 19:51:35`: **butler** changed milestone from "SasView Next Release +1" to "SasView 4.0.0"

**Comment by ajj** [comment]
Trac update at `2016/02/28 11:19:33`: 
* **ajj** changed owner from "" to "ajj"
* **ajj** changed priority from "major" to "blocker"
* **ajj** changed status from "new" to "assigned"

**Comment by ajj** [comment]
Trac update at `2016/03/20 11:44:15`: 
* **ajj** commented:

Need a build of sasmodels that includes generated DLLs for windows so we can ship them.

Mac has OpenCL by default, so can rely on that. Linux we can require pyopencl install.

Primary aim is egg that can be used for the packaging of SasView.

Secondary aim is egg that can be shipped to pypi


* **ajj** changed owner from "ajj" to "trnielsen"

**Comment by rozyczko** [comment]
Trac update at `2016/06/06 11:13:05`: 
* **piotr** commented:

Closing this ticket as all requested functionality is present, apart of sasmodels egg being shipped to pypi.
For that, a new ticket is created: #712




* **piotr** changed resolution from "" to "fixed"
* **piotr** changed status from "assigned" to "closed"
