### ISSUE TITLE
sasmodels unit testing (Trac #319)

### ISSUE THREAD

**Issue by ajj** [SasView/sasview#454]
Unit testing setup for sasmodels package

Migrated from http://trac.sasview.org/ticket/319
```json
{
    "status": "closed",
    "changetime": "2016-03-19T11:42:05",
    "_ts": "2016-03-19 11:42:05.732318+00:00",
    "description": "Unit testing setup for sasmodels package",
    "reporter": "ajj",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasModels Redesign",
    "time": "2015-02-14T11:10:29",
    "component": "SasView",
    "summary": "sasmodels unit testing",
    "priority": "blocker",
    "keywords": "",
    "milestone": "SasView 4.0.0",
    "owner": "",
    "type": "task"
}
```

**Comment by butlerpd** [comment]
Trac update at `2015/02/19 23:01:40`: 
* **butler** commented:

move to release 4.0


* **butler** changed milestone from "SasView 3.1" to "SasView Next Release +1"

**Comment by butlerpd** [comment]
Trac update at `2015/08/14 19:46:32`: **butler** changed milestone from "SasView Next Release +1" to "SasView 4.0.0"

**Comment by butlerpd** [comment]
Trac update at `2016/03/06 18:31:20`: 
* **butler** commented:

part of sasmodels package development core to 4.0 -- moving to blocker


* **butler** changed priority from "major" to "blocker"

**Comment by butlerpd** [comment]
Trac update at `2016/03/19 11:42:05`: 
* **butler** commented:

works says Andrew


* **butler** changed resolution from "" to "fixed"
* **butler** changed status from "new" to "closed"
