### ISSUE TITLE
Error boxes in Fit panel appear and disappear randomly (Trac #320)

### ISSUE THREAD

**Issue by gonzalezma** [SasView/sasview#455]
When fixing/unfixing some of the model parameters in the FitPage and then fitting, the error boxes seem to appear and disappear in a random way. Fixing a parameter and then fitting the error box of this parameter disappears (which is right), but when the parameter is unfixed the error box does not always reappears. And at the same time the error boxes of some other parameters (which have not been fixed) disappear as well. The SphereModel seems quite sensible to this problem (but also observed with other models).

Migrated from http://trac.sasview.org/ticket/320
```json
{
    "status": "closed",
    "changetime": "2015-02-14T17:57:35",
    "_ts": "2015-02-14 17:57:35.919208+00:00",
    "description": "When fixing/unfixing some of the model parameters in the FitPage and then fitting, the error boxes seem to appear and disappear in a random way. Fixing a parameter and then fitting the error box of this parameter disappears (which is right), but when the parameter is unfixed the error box does not always reappears. And at the same time the error boxes of some other parameters (which have not been fixed) disappear as well. The SphereModel seems quite sensible to this problem (but also observed with other models).",
    "reporter": "gonzalezm",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2015-02-14T13:12:12",
    "component": "SasView",
    "summary": "Error boxes in Fit panel appear and disappear randomly",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 3.1.0",
    "owner": "gonzalezm",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2015/02/14 13:49:10`: **butler** changed milestone from "SasView Next Release +1" to "SasView 3.1"

**Comment by gonzalezma** [comment]
Trac update at `2015/02/14 16:52:47`: **gonzalezm** commented:

Finally it turns out that this is not really a GUI problem. The reason for the strange behaviour is that in the function onsetValues the covariance matrix returned by the fitting motor contains occasionally 'nan' values. Whenever this happens, the interface hides the corresponding error box. However the question remains why the fitting motor is behaving in this way, even for simple fits. An easy way to test this is to load the test data file 'sphere_80.txt', select the SphereModel and try to fit directly the data with all the parameters free. Repeating the fit several times, the parameters having 'nan' errors change continuously.

**Comment by gonzalezma** [comment]
Trac update at `2015/02/14 17:57:35`: 
* **gonzalezm** commented:

NaN errors are now shown in the error box instead of hiding completely the box, so the user can see that there is something potentially wrong with the fit.


* **gonzalezm** changed resolution from "" to "fixed"
* **gonzalezm** changed status from "new" to "closed"
