### ISSUE TITLE
Remove references to sourceforge (Trac #321)

### ISSUE THREAD

**Issue by ajj** [SasView/sasview#456]
Migrated from http://trac.sasview.org/ticket/321
```json
{
    "status": "closed",
    "changetime": "2015-06-22T05:27:18",
    "_ts": "2015-06-22 05:27:18.513731+00:00",
    "description": "",
    "reporter": "ajj",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Admin",
    "time": "2015-02-14T13:50:12",
    "component": "SasView",
    "summary": "Remove references to sourceforge",
    "priority": "major",
    "keywords": "",
    "milestone": "Admin Tasks",
    "owner": "",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2015/03/14 01:32:31`: **butler** commented:

Where all were you thinking?  I have finished going through the wiki and the webpage and believe we are up to date there.  We probably need to put something on the front page of Sourceforge? not sure how politic it is to use sourceforge to point to Github? Also How do we get the important statistics that sourceforge gave us regarding downloads?

PDB

**Comment by pkienzle** [comment]
Trac update at `2015/06/03 20:52:34`: 
* **pkienzle** changed _comment0 from:

> setup.py
> sasview/README.txt
> sasview/local_config.py
> sasmodels/setup.py
> src/sas/guiframe/config.py
> 

to:

> 1433365538819023


* **pkienzle** commented:

setup.py
sasview/README.txt
sasview/local_config.py
sasmodels/setup.py
src/sas/guiframe/config.py
docs/sasview/Tutorial.pptx

**Comment by butlerpd** [comment]
Trac update at `2015/06/22 05:16:22`: **butler** commented:

Have fixed README.txt, local_config.py, config.py.

**Comment by butlerpd** [comment]
Trac update at `2015/06/22 05:27:18`: 
* **butler** commented:

Fixed setup.py and sasmodels/setup.py.  Tutorial has a lot of things that need updating and is planned for a future release.  Am closing this ticket as the remainder of this ticke duplicates the tutorial update ticket.


* **butler** changed resolution from "" to "fixed"
* **butler** changed status from "new" to "closed"
