### ISSUE TITLE
Create SasView organanization and resolve ownership issues (Trac #328)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#463]
We are currently running on a variety of individually owned resources (git account, domain name, svn account) and ad hoc support from UT, SNS, and now DMSC (though this latter is probably most formal) for things like web servers, build machines, Jenkins servers.  Morever the code is being worked on making it difficult to answer the question of "who owns it" that companies that want to install want to know (e.g. ExxonMobil emailing questions of who owns and what is the license, etc).

Migrated from http://trac.sasview.org/ticket/328
```json
{
    "status": "new",
    "changetime": "2015-02-15T15:39:22",
    "_ts": "2015-02-15 15:39:22.291366+00:00",
    "description": "We are currently running on a variety of individually owned resources (git account, domain name, svn account) and ad hoc support from UT, SNS, and now DMSC (though this latter is probably most formal) for things like web servers, build machines, Jenkins servers.  Morever the code is being worked on making it difficult to answer the question of \"who owns it\" that companies that want to install want to know (e.g. ExxonMobil emailing questions of who owns and what is the license, etc).\n\n",
    "reporter": "butler",
    "cc": "",
    "resolution": "",
    "workpackage": "SasView Admin",
    "time": "2015-02-15T15:39:22",
    "component": "SasView",
    "summary": "Create SasView organanization and resolve ownership issues",
    "priority": "major",
    "keywords": "",
    "milestone": "Admin Tasks",
    "owner": "",
    "type": "defect"
}
```

**Comment by ajj** [comment]
Need to complete the work on the creation of a Swedish non-profit:
- statutes
- first meeting (@ajj, @butlerpd, and Adrian Rennie)

**Comment by butlerpd** [comment]
Non profit mentioned by @ajj has been established and held 2 general annual meetings. I think we can close this
