### ISSUE TITLE
fit panel not defaulting to min and max from model definition (Trac #329)

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#464]
Since many models have defined limits (e.g., radius must be positive) it would be very convenient if these limits were to appear in the user interface when the model fit is being defined.

Make sure inf/-inf work for limits

Migrated from http://trac.sasview.org/ticket/329
```json
{
    "status": "closed",
    "changetime": "2015-11-22T01:44:35",
    "_ts": "2015-11-22 01:44:35.112067+00:00",
    "description": "Since many models have defined limits (e.g., radius must be positive) it would be very convenient if these limits were to appear in the user interface when the model fit is being defined.\n\nMake sure inf/-inf work for limits\n\n",
    "reporter": "pkienzle",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2015-02-15T17:31:52",
    "component": "SasView",
    "summary": "fit panel not defaulting to min and max from model definition",
    "priority": "minor",
    "keywords": "",
    "milestone": "SasView 3.1.0",
    "owner": "",
    "type": "defect"
}
```

**Comment by pkienzle** [comment]
Trac update at `2015/02/15 18:22:08`: 
* **pkienzle** changed resolution from "" to "fixed"
* **pkienzle** changed status from "new" to "closed"

**Comment by butlerpd** [comment]
Trac update at `2015/11/22 01:44:35`: **butler** changed milestone from "SasView Next Release +1" to "SasView 3.1.0"
