### ISSUE TITLE
allow inf/-inf for model limits (Trac #330)

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#465]
Migrated from http://trac.sasview.org/ticket/330
```json
{
    "status": "closed",
    "changetime": "2015-11-22T01:29:41",
    "_ts": "2015-11-22 01:29:41.929773+00:00",
    "description": "",
    "reporter": "pkienzle",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasModels Redesign",
    "time": "2015-02-15T17:43:22",
    "component": "SasView",
    "summary": "allow inf/-inf for model limits",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.0.0",
    "owner": "",
    "type": "defect"
}
```

**Comment by pkienzle** [comment]
Trac update at `2015/02/15 18:55:32`: 
* **pkienzle** changed resolution from "" to "fixed"
* **pkienzle** changed status from "new" to "closed"

**Comment by butlerpd** [comment]
Trac update at `2015/11/22 01:29:41`: 
* **butler** changed milestone from "SasView Next Release +1" to "SasView 4.0.0"
* **butler** changed workpackage from "SasView Bug Fixing" to "SasModels Redesign"
