### ISSUE TITLE
Remove all references to DANSE from user feedback messages (Trac #331)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#466]
There are some messages that instruct the user to contact the DANSE Team.

These need removing or changing to the SasView Development team.

Migrated from http://trac.sasview.org/ticket/331
```json
{
    "status": "closed",
    "changetime": "2015-11-22T01:31:11",
    "_ts": "2015-11-22 01:31:11.222478+00:00",
    "description": "There are some messages that instruct the user to contact the DANSE Team.\n\nThese need removing or changing to the SasView Development team.",
    "reporter": "smk78",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "Reporting Enhancements",
    "time": "2015-02-16T15:02:40",
    "component": "SasView",
    "summary": "Remove all references to DANSE from user feedback messages",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 3.1.0",
    "owner": "",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2015/02/17 10:53:46`: **butler** changed _comment0 from:

> I found 2 references for contacting the DANSE team within the code and replaced them to suggest contacting the SasView team.
> 
> The two locations:
> src/sas/perspectives/calculator/data_editor.py - In the load_error() method.
> src/sas/guiframe/local_perspectives/data_loader/data_loader.py - In the Plugin.get_data() method.
> 
> There are many other references to DANSE within the code base, but the ones I see all are acknowledgements to the original project.

to:

> 1448155856470606

**Comment by butlerpd** [comment]
Trac update at `2015/11/22 01:31:11`: **butler** changed milestone from "SasView Next Release +1" to "SasView 3.1.0"
