### ISSUE TITLE
write and submit abstract for SAS 2015 (Trac #333)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#468]
as part of outreach and letting people know what we are doing, it would be good to have a presence at the SAS 2015.  For that we need to prepare and submit an abstract by the deadline.

Migrated from http://trac.sasview.org/ticket/333
```json
{
    "status": "closed",
    "changetime": "2015-03-01T18:40:39",
    "_ts": "2015-03-01 18:40:39.070579+00:00",
    "description": "as part of outreach and letting people know what we are doing, it would be good to have a presence at the SAS 2015.  For that we need to prepare and submit an abstract by the deadline.",
    "reporter": "butler",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Admin",
    "time": "2015-02-17T10:34:02",
    "component": "SasView",
    "summary": "write and submit abstract for SAS 2015",
    "priority": "major",
    "keywords": "",
    "milestone": "Admin Tasks",
    "owner": "mathieu",
    "type": "task"
}
```

**Comment by butlerpd** [comment]
Trac update at `2015/02/17 10:37:50`: **butler** commented:

Firs draft was done by Matt and passed to Paul
Paul has made first edit -- next bring up to group during discussion period

**Comment by mdoucet** [comment]
Trac update at `2015/03/01 18:40:39`: 
* **mathieu** changed resolution from "" to "fixed"
* **mathieu** changed status from "new" to "closed"
