### ISSUE TITLE
"Paste" functionality broken (Trac #334)

### ISSUE THREAD

**Issue by mdoucet** [SasView/sasview#469]
The paste functionality fails when you haven't used the "copy" button first.
It should just do nothing and alert you in a nice way.

Migrated from http://trac.sasview.org/ticket/334
```json
{
    "status": "closed",
    "changetime": "2018-09-06T09:45:36",
    "_ts": "2018-09-06 09:45:36.993574+00:00",
    "description": "The paste functionality fails when you haven't used the \"copy\" button first.\nIt should just do nothing and alert you in a nice way.",
    "reporter": "mathieu",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2015-02-17T14:41:45",
    "component": "SasView",
    "summary": "\"Paste\" functionality broken",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 5.0.0",
    "owner": "LauraamForster",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2015/08/14 19:53:30`: **butler** changed milestone from "SasView Next Release +1" to "SasView 4.0.0"

**Comment by butlerpd** [comment]
Trac update at `2016/03/20 22:59:35`: **butler** changed milestone from "SasView 4.0.0" to "SasView Next Release +1"

**Comment by butlerpd** [comment]
Trac update at `2017/10/26 11:15:00`: 
* **butler** commented:

Probably goes away when new GUI comes out.


* **butler** changed milestone from "SasView Next Release +1" to "SasView 5.0.0"
