### ISSUE TITLE
Report print preview is broken (Trac #335)

### ISSUE THREAD

**Issue by mdoucet** [SasView/sasview#470]
Clicking print preview after a report is displayed will pop up a dialog that can't be killed.

Migrated from http://trac.sasview.org/ticket/335
```json
{
    "status": "closed",
    "changetime": "2015-11-22T01:32:21",
    "_ts": "2015-11-22 01:32:21.391800+00:00",
    "description": "Clicking print preview after a report is displayed will pop up a dialog that can't be killed.",
    "reporter": "mathieu",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2015-02-17T15:52:34",
    "component": "SasView",
    "summary": "Report print preview is broken",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 3.1.0",
    "owner": "mathieu",
    "type": "defect"
}
```

**Comment by mdoucet** [comment]
Trac update at `2015/02/17 22:41:05`: 
* **mathieu** changed owner from "" to "mathieu"
* **mathieu** changed status from "new" to "assigned"

**Comment by mdoucet** [comment]
Trac update at `2015/02/17 22:42:54`: 
* **mathieu** commented:

The problem was with the report dialog being modal. When clicking the preview button, a new window pops up, but you can't interact with it if the report dialog is modal. I made it non-modal, which makes more sense for the user.


* **mathieu** changed resolution from "" to "fixed"
* **mathieu** changed status from "assigned" to "closed"

**Comment by butlerpd** [comment]
Trac update at `2015/11/22 01:32:21`: **butler** changed milestone from "SasView Next Release +1" to "SasView 3.1.0"
