### ISSUE TITLE
Refactor report dialog code (Trac #336)

### ISSUE THREAD

**Issue by mdoucet** [SasView/sasview#471]
There are two report_dialog.py files, and they are almost identical.
One is in perspectives/invariant, and the other in perspectives/fitting.
We should have only one.

Migrated from http://trac.sasview.org/ticket/336
```json
{
    "status": "closed",
    "changetime": "2015-11-22T01:33:42",
    "_ts": "2015-11-22 01:33:42.851879+00:00",
    "description": "There are two report_dialog.py files, and they are almost identical.\nOne is in perspectives/invariant, and the other in perspectives/fitting.\nWe should have only one.",
    "reporter": "mathieu",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2015-02-17T16:02:33",
    "component": "SasView",
    "summary": "Refactor report dialog code",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 3.1.0",
    "owner": "",
    "type": "enhancement"
}
```

**Comment by mdoucet** [comment]
Trac update at `2015/02/18 20:46:43`: 
* **mathieu** changed resolution from "" to "fixed"
* **mathieu** changed status from "new" to "closed"

**Comment by butlerpd** [comment]
Trac update at `2015/11/22 01:33:42`: **butler** changed milestone from "SasView Next Release +1" to "SasView 3.1.0"
