### ISSUE TITLE
SESANS data loader (Trac #343)

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#478]
Loader to read in SESANS data in 6 colums: spin-echo length, wavelength and polarisation and the corresponding errors.

Migrated from http://trac.sasview.org/ticket/343
```json
{
    "status": "closed",
    "changetime": "2015-11-22T01:48:07",
    "_ts": "2015-11-22 01:48:07.530254+00:00",
    "description": "Loader to read in SESANS data in 6 colums: spin-echo length, wavelength and polarisation and the corresponding errors.",
    "reporter": "pkienzle",
    "cc": "",
    "resolution": "duplicate",
    "workpackage": "SESANS Integration",
    "time": "2015-02-18T15:06:53",
    "component": "SasView",
    "summary": "SESANS data loader",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 3.1.0",
    "owner": "",
    "type": "enhancement"
}
```

**Comment by pkienzle** [comment]
Trac update at `2015/02/18 15:39:31`: 
* **pkienzle** changed resolution from "" to "duplicate"
* **pkienzle** changed status from "new" to "closed"

**Comment by butlerpd** [comment]
Trac update at `2015/11/22 01:48:07`: **butler** changed milestone from "SasView Next Release +1" to "SasView 3.1.0"
