### ISSUE TITLE
Hankel transform (Trac #344)

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#479]
Write a wrapper with a Hankel transform of the sasmodels present to obtain the corresponding SESANS polarisations.

Migrated from http://trac.sasview.org/ticket/344
```json
{
    "status": "closed",
    "changetime": "2015-11-22T01:35:45",
    "_ts": "2015-11-22 01:35:45.803073+00:00",
    "description": "Write a wrapper with a Hankel transform of the sasmodels present to obtain the corresponding SESANS polarisations.",
    "reporter": "pkienzle",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SESANS Integration",
    "time": "2015-02-18T15:09:11",
    "component": "SasView",
    "summary": "Hankel transform",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.0.0",
    "owner": "",
    "type": "enhancement"
}
```

**Comment by butlerpd** [comment]
Trac update at `2015/02/20 10:02:51`: 
* **butler** changed resolution from "" to "fixed"
* **butler** changed status from "new" to "closed"

**Comment by butlerpd** [comment]
Trac update at `2015/11/22 01:35:45`: **butler** changed milestone from "SasView Next Release +1" to "SasView 4.0.0"
