### ISSUE TITLE
BUMPS fit of SESANS (Trac #345)

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#480]
Connect BUMPS to the SESANS model for fitting.  This will enable users to fit SESANS measurements on the command line with all the available sasmodels with the Hankel transform wrapper.

Migrated from http://trac.sasview.org/ticket/345
```json
{
    "status": "closed",
    "changetime": "2015-11-22T01:36:28",
    "_ts": "2015-11-22 01:36:28.014033+00:00",
    "description": "Connect BUMPS to the SESANS model for fitting.  This will enable users to fit SESANS measurements on the command line with all the available sasmodels with the Hankel transform wrapper.",
    "reporter": "pkienzle",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SESANS Integration",
    "time": "2015-02-18T15:12:52",
    "component": "SasView",
    "summary": "BUMPS fit of SESANS",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.0.0",
    "owner": "",
    "type": "enhancement"
}
```

**Comment by butlerpd** [comment]
Trac update at `2015/02/20 10:03:13`: 
* **butler** changed resolution from "" to "fixed"
* **butler** changed status from "new" to "closed"

**Comment by butlerpd** [comment]
Trac update at `2015/11/22 01:36:28`: **butler** changed milestone from "SasView Next Release +1" to "SasView 4.0.0"
