### ISSUE TITLE
SESANS into GUI Design (Trac #346)

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#481]
In order to include SESANS fully in all parts of the GUI with plotting and fitting need to agree on the design - first visually then code/module wise.  example issue to look into:
1. How to integrate w/ SANS fitting in GUI
2. How to identify if data is SESANS (in correlation space) or SANS (reciprocal space) ... and how to make clear graphically
3. If correlation space models are available how to choose what models to present to user seemlessly -- note that for full power scripting would always be the way to go but for GUI want to make transparent and easy for the user
4. What modules will need to be refactored and what new modules created in order to support above?
5. Should we start by making an independent SESANS perspective in order to explore the possibilities first without breaking trunk?

Once this is done tickets for the actual work will need to be generated

Migrated from http://trac.sasview.org/ticket/346
```json
{
    "status": "assigned",
    "changetime": "2016-06-19T16:10:08",
    "_ts": "2016-06-19 16:10:08.920165+00:00",
    "description": "In order to include SESANS fully in all parts of the GUI with plotting and fitting need to agree on the design - first visually then code/module wise.  example issue to look into:\n1. How to integrate w/ SANS fitting in GUI\n2. How to identify if data is SESANS (in correlation space) or SANS (reciprocal space) ... and how to make clear graphically\n3. If correlation space models are available how to choose what models to present to user seemlessly -- note that for full power scripting would always be the way to go but for GUI want to make transparent and easy for the user\n4. What modules will need to be refactored and what new modules created in order to support above?\n5. Should we start by making an independent SESANS perspective in order to explore the possibilities first without breaking trunk?\n\nOnce this is done tickets for the actual work will need to be generated",
    "reporter": "pkienzle",
    "cc": "",
    "resolution": "",
    "workpackage": "SESANS Integration",
    "time": "2015-02-18T15:19:10",
    "component": "SasView",
    "summary": "SESANS into GUI Design",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView Next Release +1",
    "owner": "ajj",
    "type": "enhancement"
}
```

**Comment by butlerpd** [comment]
Trac update at `2016/03/06 19:49:08`: 
* **butler** commented:

Clearly the start of this is labelled as core task for 4.0.  Could be labelled critical since we don't have to complete, but will mark it blocker as it is the overarching ticket (need subtickets) for this code camp


* **butler** changed milestone from "SasView Next Release +1" to "SasView 4.0.0"
* **butler** changed priority from "minor" to "blocker"

**Comment by butlerpd** [comment]
Trac update at `2016/03/06 23:27:37`: 
* **butler** changed description from:

> Include SESANS fully in all parts of the GUI with plotting and fitting

to:

> In order to include SESANS fully in all parts of the GUI with plotting and fitting need to agree on the design - first visually then code/module wise.  example issue to look into:
> 1. How to integrate w/ SANS fitting in GUI
> 2. How to identify if data is SESANS (in correlation space) or SANS (reciprocal space) ... and how to make clear graphically
> 3. If correlation space models are available how to choose what models to present to user seemlessly -- note that for full power scripting would always be the way to go but for GUI want to make transparent and easy for the user
> 4. What modules will need to be refactored and what new modules created in order to support above?
> 5. Should we start by making an independent SESANS perspective in order to explore the possibilities first without breaking trunk?
> 
> Once this is done tickets for the actual work will need to be generated


* **butler** changed owner from "" to "ajj"
* **butler** changed status from "new" to "assigned"
* **butler** changed summary from "SESANS into GUI" to "SESANS into GUI Design"

**Comment by butlerpd** [comment]
Trac update at `2016/06/19 16:10:08`: 
* **butler** commented:

This ticket was also blocker as it was the subject of one of the team's work at code camp but GUI for SESANS was never intended to be in 4.0 release.  As we are well out of code camp and release 4.0 alpha is out am now moving to next +1

Paul


* **butler** changed milestone from "SasView 4.0.0" to "SasView Next Release +1"
* **butler** changed priority from "blocker" to "major"

**Comment by butlerpd** [comment]
This was done a while back.  We agreed to close this at codecampX. If there are specific new items about the GUI (and there are) they should be the subject of their own new issues (and many are).
