### ISSUE TITLE
lamellarFFHG investigate polydisp integration (Trac #347)

### ISSUE THREAD

**Issue by RichardHeenan** [SasView/sasview#482]
lamellarFFHG investigate polydisp integration

compare.sh on new type models shows small differences (few % at high Q) in polydisp integration when polydisp is large on the h_length variable

Migrated from http://trac.sasview.org/ticket/347
```json
{
    "status": "closed",
    "changetime": "2016-03-16T17:48:33",
    "_ts": "2016-03-16 17:48:33.487977+00:00",
    "description": "\nlamellarFFHG investigate polydisp integration\n\n\ncompare.sh on new type models shows small differences (few % at high Q) in polydisp integration when polydisp is large on the h_length variable",
    "reporter": "richardh",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView QA and testing",
    "time": "2015-02-18T15:26:14",
    "component": "SasView",
    "summary": "lamellarFFHG investigate polydisp integration",
    "priority": "critical",
    "keywords": "lamellarFFHG",
    "milestone": "SasView 4.0.0",
    "owner": "richardh",
    "type": "task"
}
```

**Comment by butlerpd** [comment]
Trac update at `2015/03/10 16:51:09`: 
* **butler** commented:

This is a sasmodels question which is part of next release so moving this ticket there as well


* **butler** changed milestone from "SasView 3.1" to "SasView Next Release +1"

**Comment by butlerpd** [comment]
Trac update at `2015/08/14 20:07:17`: **butler** changed milestone from "SasView Next Release +1" to "SasView 4.0.0"

**Comment by butlerpd** [comment]
Trac update at `2016/03/06 18:34:06`: 
* **butler** commented:

since it seems to "work" but question of precision only this may not be a blocker core task... but still seem part of core work being one hence using critical for now.


* **butler** changed priority from "major" to "critical"

**Comment by butlerpd** [comment]
Trac update at `2016/03/06 21:06:24`: 
* **butler** changed owner from "RichardH" to "richardh"
* **butler** changed status from "new" to "assigned"

**Comment by RichardHeenan** [comment]
Trac update at `2016/03/16 17:48:33`: 
* **richardh** commented:


Some very minor issues at high Q, with polydisp integrals

PAK noted that -offset=0 in compare.sh fixed this, PAK was truncating the integrals at 1e-05 of peak of function, this not quite good enough here.


* **richardh** changed resolution from "" to "fixed"
* **richardh** changed status from "assigned" to "closed"
