### ISSUE TITLE
Proof read Sphinx help docs (Trac #356)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#491]
The new Sphinx help docs need proof reading for content, style, accuracy, compatibility with new/deprecated functionality, typos, grammar, etc.

Migrated from http://trac.sasview.org/ticket/356
```json
{
    "status": "closed",
    "changetime": "2015-06-04T15:47:51",
    "_ts": "2015-06-04 15:47:51.657633+00:00",
    "description": "The new Sphinx help docs need proof reading for content, style, accuracy, compatibility with new/deprecated functionality, typos, grammar, etc.",
    "reporter": "smk78",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Documentation",
    "time": "2015-02-18T22:26:48",
    "component": "SasView",
    "summary": "Proof read Sphinx help docs",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 3.1.0",
    "owner": "smk78",
    "type": "enhancement"
}
```

**Comment by smk78** [comment]
Trac update at `2015/02/18 22:28:10`: **smk78** commented:

All now parsed at 'Level 0', meaning they build in Sphinx.

**Comment by smk78** [comment]
Trac update at `2015/02/18 22:30:52`: **smk78** commented:

Current status of proof reading is indicated by the presence/absence of a Sphinx note in each document (usually at the bottom)

**Comment by smk78** [comment]
Trac update at `2015/02/18 22:41:15`: **smk78** commented:

Proof read so far:

data_explorer_help.rst
data_formats.rst
graph_help.rst
data_operator_help.rst
density_calculator_help.rst
image_viewer_help.rst
kiessig_calculator_help.rst


To do:

model_functions.rst !!! (should be done model-by-model as new model structure implemented)

fitting_help.rst
invariant_help.rst
pr_help.rst
python_shell_help.rst
resolution_calculator_help.rst
sas_calculator_help.rst
sld_calculator_help.rst
slit_calculator_help.rst

**Comment by smk78** [comment]
Trac update at `2015/02/19 14:43:24`: **smk78** commented:

Proof read so far:

data_explorer_help.rst
data_formats.rst
graph_help.rst
data_operator_help.rst
density_calculator_help.rst
image_viewer_help.rst
kiessig_calculator_help.rst
python_shell_help.rst
resolution_calculator_help.rst
sas_calculator_help.rst
sld_calculator_help.rst


To do:

model_functions.rst !!! (should be done model-by-model as new model structure implemented)

fitting_help.rst
invariant_help.rst
pr_help.rst
slit_calculator_help.rst

**Comment by smk78** [comment]
Trac update at `2015/02/19 21:53:34`: **smk78** commented:

Proof read so far:

data_explorer_help.rst
data_formats.rst
graph_help.rst
data_operator_help.rst
density_calculator_help.rst
image_viewer_help.rst
invariant_help.rst
kiessig_calculator_help.rst
pr_help.rst
python_shell_help.rst
resolution_calculator_help.rst
sas_calculator_help.rst
sld_calculator_help.rst
slit_calculator_help.rst


To do:

model_functions.rst !!! (should be done model-by-model as new model structure implemented)

fitting_help.rst

**Comment by smk78** [comment]
Trac update at `2015/03/19 11:13:56`: **smk78** commented:

Noted.

I only just got to start 'proof-reading' this file at Code Camp so it is at present largely untouched.

Leave it with me!

**Comment by butlerpd** [comment]
Trac update at `2015/04/07 14:34:17`: 
* **butler** changed owner from "smk" to "smk78"
* **butler** changed status from "new" to "assigned"

**Comment by smk78** [comment]
Trac update at `2015/05/01 15:36:37`: **smk78** commented:

The following have all been revisited to implement Sphinx sections/subsections and to remove unnecessary html-like internal links (as Sphinx auto builds a navigation tree):

 data_explorer_help.rst
 data_formats.rst
 graph_help.rst
 data_operator_help.rst
 density_calculator_help.rst
 image_viewer_help.rst
 invariant_help.rst
 kiessig_calculator_help.rst
 pr_help.rst
 python_shell_help.rst
 resolution_calculator_help.rst
 sas_calculator_help.rst
 sld_calculator_help.rst
 slit_calculator_help.rst


To do:

 model_functions.rst !!! (should be done model-by-model as new model structure implemented)


In progress:

 What was fitting_help.rst ; this was a very lengthy help file covering both the help for the Fitting Perspective and help on technical/theoretical background matters such as polydispersity, smearing and magnetic scattering. The latter have been extracted to three new help files:

 pd_help.rst
 sm_help.rst
 mag_help.rst

and a new second level toctree created:

 fitting.rst

to provide a much cleaner route to fitting_help, pd_help, sm_help and mag_help, and to allow an EXTERNAL link to Paul Kienzle's Bumps documentation.

**Comment by smk78** [comment]
Trac update at `2015/05/01 15:39:43`: **smk78** commented:

Proof read so far:

 data_explorer_help.rst
 data_formats.rst
 graph_help.rst
 data_operator_help.rst
 density_calculator_help.rst
 image_viewer_help.rst
 invariant_help.rst
 kiessig_calculator_help.rst
 pr_help.rst
 python_shell_help.rst
 resolution_calculator_help.rst
 sas_calculator_help.rst
 sld_calculator_help.rst
 slit_calculator_help.rst
 +
 fitting.rst
 pd_help.rst
 sm_help.rst

To do:

 model_functions.rst !!! (should be done model-by-model as new model structure implemented)
 +
 fitting_help.rst
 mag_help.rst

**Comment by smk78** [comment]
Trac update at `2015/05/02 18:45:25`: **smk78** commented:

Proof read so far:

 data_explorer_help.rst
 data_formats.rst
 graph_help.rst
 data_operator_help.rst
 density_calculator_help.rst
 image_viewer_help.rst
 invariant_help.rst
 kiessig_calculator_help.rst
 pr_help.rst
 python_shell_help.rst
 resolution_calculator_help.rst
 sas_calculator_help.rst
 sld_calculator_help.rst
 slit_calculator_help.rst
 +
 fitting.rst
 pd_help.rst
 sm_help.rst
 mag_help.rst

To do:

 model_functions.rst !!! (should be done model-by-model as new model structure implemented)
 +
 fitting_help.rst

**Comment by smk78** [comment]
Trac update at `2015/06/04 15:47:51`: 
* **smk78** commented:

Proof read so far:

 data_explorer_help.rst
 data_formats.rst
 graph_help.rst
 data_operator_help.rst
 density_calculator_help.rst
 image_viewer_help.rst
 invariant_help.rst
 kiessig_calculator_help.rst
 pr_help.rst
 python_shell_help.rst
 resolution_calculator_help.rst
 sas_calculator_help.rst
 sld_calculator_help.rst
 slit_calculator_help.rst
 fitting.rst
 pd_help.rst
 sm_help.rst
 mag_help.rst
 fitting_help.rst

To do:

 model_functions.rst !!!
 (but this should now be done model-by-model as the new model structure is implemented)

The porting and clean-up of all the old HTML help files into ReST is therefore complete and I am closing this ticket.





* **smk78** changed resolution from "" to "fixed"
* **smk78** changed status from "assigned" to "closed"
