### ISSUE TITLE
Be able to use new models from sasmodels alongside sas.models models (Trac #359)

### ISSUE THREAD

**Issue by ajj** [SasView/sasview#494]
Migrated from http://trac.sasview.org/ticket/359
```json
{
    "status": "closed",
    "changetime": "2015-02-21T14:11:20",
    "_ts": "2015-02-21 14:11:20.749910+00:00",
    "description": "",
    "reporter": "ajj",
    "cc": "",
    "resolution": "obsolete",
    "workpackage": "SasModels Redesign",
    "time": "2015-02-19T09:29:27",
    "component": "SasView",
    "summary": "Be able to use new models from sasmodels alongside sas.models models",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 3.1.0",
    "owner": "ajj",
    "type": "enhancement"
}
```

**Comment by butlerpd** [comment]
Trac update at `2015/02/21 14:11:20`: 
* **butler** commented:

This was to be able to get into immediate release.  New plan is to release with sas models in mid-year with a clean sasmodels package and not try mixing model packages.  This ticket is now obsolete


* **butler** changed resolution from "" to "obsolete"
* **butler** changed status from "new" to "closed"
