### ISSUE TITLE
Several model file docstrings are incorrectly formatted (Trac #360)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#495]
Sphinx is complaining about a number of incorrectly formatted docstrings in model files. See the attached text file.

Migrated from http://trac.sasview.org/ticket/360
```json
{
    "status": "closed",
    "changetime": "2016-09-05T02:39:59",
    "_ts": "2016-09-05 02:39:59.917772+00:00",
    "description": "Sphinx is complaining about a number of incorrectly formatted docstrings in model files. See the attached text file.",
    "reporter": "smk78",
    "cc": "",
    "resolution": "obsolete",
    "workpackage": "SasView Documentation",
    "time": "2015-02-19T14:05:54",
    "component": "SasView",
    "summary": "Several model file docstrings are incorrectly formatted",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView Next Release +1",
    "owner": "",
    "type": "defect"
}
```

**Comment by smk78** [comment]
Trac update at `2015/02/19 14:06:45`: 
* **smk78** changed attachment from "" to "ModelDocStringErrors.txt"
* **smk78** commented:

Sphinx compilation errors and warnings

**Comment by butlerpd** [comment]
Trac update at `2015/03/10 14:52:27`: **butler** commented:

Can move to 4.0 if necessary

**Comment by butlerpd** [comment]
Trac update at `2015/03/24 14:37:19`: **butler** changed milestone from "SasView 3.1" to "SasView Next Release +1"

**Comment by butlerpd** [comment]
Trac update at `2016/09/05 02:39:59`: 
* **butler** commented:

This ticket is now obsolete since we have completely changed how model doc strings are read.  Therefore closing this ticket.  If there are issues in sasmodels we can open a sasmodel ticket.


* **butler** changed resolution from "" to "obsolete"
* **butler** changed status from "new" to "closed"
