### ISSUE TITLE
break OpenCL calculations into smaller chunks. (Trac #363)

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#498]
OpenCL fails if the kernel takes too long to execute.  Need to restructure the kernel so that it does the polydispersity calculation in chunks.

The technique will be similar to what is used in the python kernel: increment through the polydispersity hypercube item by item, and determine the cube coordinates with combinations of div and mod.  Add an offset and length parameter to the kernel call, and put a for loop around the call stepping offset by N with a length of N until you have traversed the entire set of coordinates.  Instead of setting ret[i] each time, increment it with the partial result.  If offset starts with 0, then set ret[i]=0 before the loop.  Each kernel call should be queued to wait_for the previous kernel call so that you don't get collisions when updating ret[i].  Obviously, offset 0 needs to be called first to initialize the result.

Probably an afternoon of programming.

Migrated from http://trac.sasview.org/ticket/363
```json
{
    "status": "closed",
    "changetime": "2016-10-01T15:21:33",
    "_ts": "2016-10-01 15:21:33.477190+00:00",
    "description": "OpenCL fails if the kernel takes too long to execute.  Need to restructure the kernel so that it does the polydispersity calculation in chunks.\n\nThe technique will be similar to what is used in the python kernel: increment through the polydispersity hypercube item by item, and determine the cube coordinates with combinations of div and mod.  Add an offset and length parameter to the kernel call, and put a for loop around the call stepping offset by N with a length of N until you have traversed the entire set of coordinates.  Instead of setting ret[i] each time, increment it with the partial result.  If offset starts with 0, then set ret[i]=0 before the loop.  Each kernel call should be queued to wait_for the previous kernel call so that you don't get collisions when updating ret[i].  Obviously, offset 0 needs to be called first to initialize the result.\n\nProbably an afternoon of programming.",
    "reporter": "pkienzle",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasModels Redesign",
    "time": "2015-02-25T21:52:12",
    "component": "SasView",
    "summary": "break OpenCL calculations into smaller chunks.",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.0.0",
    "owner": "pkienzle",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2015/03/10 15:38:10`: 
* **butler** commented:

This is part of sasmodels project so should move to that release


* **butler** changed milestone from "SasView 3.1" to "SasView Next Release +1"

**Comment by butlerpd** [comment]
Trac update at `2015/08/14 19:44:55`: **butler** changed milestone from "SasView Next Release +1" to "SasView 4.0.0"

**Comment by ajj** [comment]
Trac update at `2016/02/28 11:17:42`: 
* **ajj** changed owner from "" to "pkienzle"
* **ajj** changed status from "new" to "assigned"

**Comment by butlerpd** [comment]
Trac update at `2016/03/05 03:04:00`: 
* **butler** commented:

part of requirements for 4.0 so make blocker


* **butler** changed priority from "critical" to "blocker"

**Comment by pkienzle** [comment]
Trac update at `2016/08/01 03:27:40`: 
* **pkienzle** changed resolution from "" to "fixed"
* **pkienzle** changed status from "assigned" to "closed"

**Comment by pkienzle** [comment]
Trac update at `2016/09/23 17:51:08`: 
* **pkienzle** commented:


Despite feeding only 100 PD steps at a time in sasmodels/kernelcl, the 2-D barbell with 35x35 polydispersity on radius and length caused my macbook pro to reboot.  

sasmodels/kernelcl.py(566) Maybe we could add last_call.wait() at the end of the loop in !GpuKernel.__call__()?



* **pkienzle** changed priority from "blocker" to "major"
* **pkienzle** changed resolution from "fixed" to ""
* **pkienzle** changed status from "closed" to "reopened"

**Comment by pkienzle** [comment]
Trac update at `2016/09/23 21:22:40`: 
* **pkienzle** changed attachment from "" to "large_kernel.patch"
* **pkienzle** commented:

possible fix, but with a 10% performance penalty

**Comment by pkienzle** [comment]
Trac update at `2016/09/23 21:35:37`: **pkienzle** commented:

The above patch sleeps for 50ms every 500ms, leaving time for OS X to deal with other window events.

Checking every 50 steps introduces a 10% performance penalty for the 1D cylinder model with 35x35 polydispersity on my machine (107 ms to 118 ms); when running barbell 2D with this step size, performance is very laggy.  Dropping step to 10 rather than 50 increases the 1D performance penalty to 50% (107 ms to 168 ms), but makes other windows much more responsive.

Would you rather wait 50% less for a fit rather than having responsive behaviour on a model that is otherwise unusable?  The top end gaming card calculates the full model in 500 ms with no problems, even without the built-in naps, so the advice to those doing serious 2-D fitting is to get a better machine.

We could probably make steps a function self.q_input.nq and avoid this problem.  Even better would be to have an estimate of the compute cost of the kernel, so we could tune this value to be close to 100ms without having to check the clock each cycle.

**Comment by pkienzle** [comment]
Trac update at `2016/09/23 21:43:24`: 
* **pkienzle** changed _comment0 from:

> Indeed, setting
> 
>     step = 1000000//self.q_input.nq + 1
> 
> gives the best of both worlds.  The patch needs to be updated.

to:

> 1474743790372227


* **pkienzle** commented:

Indeed, setting

```text
    step = 1000000//self.q_input.nq + 1
```
gives the best of both worlds.  The patch needs to be updated.

**Comment by pkienzle** [comment]
Trac update at `2016/09/25 13:17:54`: **pkienzle** commented:

Turned into a pull request:

    https://github.com/SasView/sasmodels/pull/9

**Comment by ajj** [comment]
Trac update at `2016/10/01 15:21:33`: 
* **ajj** changed resolution from "" to "fixed"
* **ajj** changed status from "reopened" to "closed"
