### ISSUE TITLE
Possible inconsistency in Poly_GaussCoil model (Trac #364)

### ISSUE THREAD

**Issue by gonzalezma** [SasView/sasview#499]
Klaus Huber has noted that the polydisperse Gaussian coil model (in the shape independent category) contains already a model parameter (poly_m) that is related to the polydispersity. Therefore he considers that the user should
not have the option to activate also the polydispersity for the radius of gyration.

Migrated from http://trac.sasview.org/ticket/364
```json
{
    "status": "closed",
    "changetime": "2016-03-19T00:35:14",
    "_ts": "2016-03-19 00:35:14.586969+00:00",
    "description": "Klaus Huber has noted that the polydisperse Gaussian coil model (in the shape independent category) contains already a model parameter (poly_m) that is related to the polydispersity. Therefore he considers that the user should\nnot have the option to activate also the polydispersity for the radius of gyration.",
    "reporter": "gonzalezm",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Documentation",
    "time": "2015-02-27T13:42:33",
    "component": "SasView",
    "summary": "Possible inconsistency in Poly_GaussCoil model",
    "priority": "blocker",
    "keywords": "",
    "milestone": "SasView 4.0.0",
    "owner": "smk78",
    "type": "defect"
}
```

**Comment by smk78** [comment]
Trac update at `2015/03/04 15:54:51`: **smk78** commented:

The poly_m parameter is related to the width of the chain length distribution (if poly_m=0 all chains are the same length). Clearly the chain length has a bearing on Rg since Rg=(n+1)^-2 ^x [SUM(i,j<n) (Rij)^2^] where Rij is the distance between the i'th and j'th atoms in the chain. This is the basis of Klaus' point.

However, the chain length distribution does not specify the conformational freedom of the chains; chains of the same length could have different Rg's (consider swollen vs collapsed coils). So I would argue that you CAN have a distribution of Rg's as well.

**Comment by butlerpd** [comment]
Trac update at `2015/03/07 20:29:03`: **butler** commented:

While I agree that Steve is correct that Rg is affected by more than the Molecular weight distribution, I Think Klaus is correct in the sense that a polydispersity added to Rg would be 100% correlated to the poly_m parameter (and would be like fitting both the scale and sld difference).

That said the question I suppose is whehter we prevent Rg from having polidispersity added or not.  I note that we do not prevent people from letting scale and delta(sld) vary simultaneously.... which in turn goes back to th philosophical discussion of how much you actively prevent people from doing what you think is wrong vs just warning - with respect to "warning" we can add that to the documnentation for sure!

**Comment by butlerpd** [comment]
Trac update at `2015/08/14 19:55:13`: **butler** changed milestone from "SasView Next Release +1" to "SasView 4.0.0"

**Comment by butlerpd** [comment]
Trac update at `2015/12/19 18:51:05`: **butler** changed workpackage from "SasView Bug Fixing" to "SasView Documentation"

**Comment by butlerpd** [comment]
Trac update at `2016/03/06 18:08:46`: 
* **butler** commented:

Suggest we add some notes along these lines to the model documentation and close this ticket.  As such it becomes part of the verify all model documentation core activity of release 4.0 and thus moving to this to blocker.


* **butler** changed priority from "major" to "blocker"

**Comment by butlerpd** [comment]
Trac update at `2016/03/06 20:48:53`: 
* **butler** changed owner from "" to "butler"
* **butler** changed status from "new" to "accepted"

**Comment by butlerpd** [comment]
Trac update at `2016/03/16 22:33:13`: 
* **butler** changed owner from "butler" to "smk78"
* **butler** changed status from "accepted" to "assigned"

**Comment by butlerpd** [comment]
Trac update at `2016/03/19 00:35:14`: 
* **butler** commented:

The sasmodels implementation of this model does not in fact allow for polydispersity on Rg at the moment as it was re-written by Steve King.  If he enables PD on the Rg he will change the documentation to reflect that.  Thus this ticket is essentially addressed for now.


* **butler** changed resolution from "" to "fixed"
* **butler** changed status from "assigned" to "closed"
