### ISSUE TITLE
CanSAS reader error (Trac #365)

### ISSUE THREAD

**Issue by ajj** [SasView/sasview#500]
Odd behaviour from the canSAS reader. It is raising an error because the unit for Lambda is set as "Wavelength" in ISIS data where "A" is expected.

The odd behaviour is:
1) the error is raised after all the files are loaded when a group of files is loaded. This is expected, though it is reported as though only the last file has the error.
2) 4 errors are raised for each file independent of the number of bad lines.

Migrated from http://trac.sasview.org/ticket/365
```json
{
    "status": "closed",
    "changetime": "2015-11-22T01:38:44",
    "_ts": "2015-11-22 01:38:44.692264+00:00",
    "description": "Odd behaviour from the canSAS reader. It is raising an error because the unit for Lambda is set as \"Wavelength\" in ISIS data where \"A\" is expected.\n\nThe odd behaviour is:\n1) the error is raised after all the files are loaded when a group of files is loaded. This is expected, though it is reported as though only the last file has the error.\n2) 4 errors are raised for each file independent of the number of bad lines.\n\n",
    "reporter": "ajj",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2015-02-27T14:38:40",
    "component": "SasView",
    "summary": "CanSAS reader error",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 3.1.0",
    "owner": "krzywon",
    "type": "defect"
}
```

**Comment by ajj** [comment]
Trac update at `2015/02/27 14:38:58`: **ajj** commented:

Example console :

	Errors occurred while loading /Users/andrewjackson/Dropbox/Research/Deep Eutectic Solvents/ISIS March 2014/LOQ March 2014/Apr14 Reduction/sample1_rear.xml
The data file loaded but with errors.
	Error: CanSAS reader: unexpected "Lambda" unit [Wavelength]; expecting [A]
	Error: CanSAS reader: unexpected "Lambda" unit [Wavelength]; expecting [A]
	Error: CanSAS reader: unexpected "Lambda" unit [Wavelength]; expecting [A]
	Error: CanSAS reader: unexpected "Lambda" unit [Wavelength]; expecting [A]

	Loading Data... /Users/andrewjackson/Dropbox/Research/Deep Eutectic Solvents/ISIS March 2014/LOQ March 2014/Apr14 Reduction/sample1_rear.xml

	Loading Data... /Users/andrewjackson/Dropbox/Research/Deep Eutectic Solvents/ISIS March 2014/LOQ March 2014/Apr14 Reduction/sample1_rear.xml

	Loading Data... /Users/andrewjackson/Dropbox/Research/Deep Eutectic Solvents/ISIS March 2014/LOQ March 2014/Apr14 Reduction/sample2_rear.xml

	Errors occurred while loading /Users/andrewjackson/Dropbox/Research/Deep Eutectic Solvents/ISIS March 2014/LOQ March 2014/Apr14 Reduction/sample2_rear.xml
The data file loaded but with errors.
	Error: CanSAS reader: unexpected "Lambda" unit [Wavelength]; expecting [A]
	Error: CanSAS reader: unexpected "Lambda" unit [Wavelength]; expecting [A]
	Error: CanSAS reader: unexpected "Lambda" unit [Wavelength]; expecting [A]
	Error: CanSAS reader: unexpected "Lambda" unit [Wavelength]; expecting [A]
	Error: CanSAS reader: unexpected "Lambda" unit [Wavelength]; expecting [A]
	Error: CanSAS reader: unexpected "Lambda" unit [Wavelength]; expecting [A]
	Error: CanSAS reader: unexpected "Lambda" unit [Wavelength]; expecting [A]
	Error: CanSAS reader: unexpected "Lambda" unit [Wavelength]; expecting [A]

**Comment by butlerpd** [comment]
Trac update at `2015/11/22 01:38:44`: **butler** changed milestone from "SasView Next Release +1" to "SasView 3.1.0"
