### ISSUE TITLE
Data operations tool is broken (Trac #370)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#505]
The graphics of data operations tool does not seem to work.  Instead of showing the plot in the window it makes a blank square.  Apply does seem to work but hard to tell.  Fails on both mac and PC it seems.

Migrated from http://trac.sasview.org/ticket/370
```json
{
    "status": "closed",
    "changetime": "2015-04-24T12:35:39",
    "_ts": "2015-04-24 12:35:39.290659+00:00",
    "description": "The graphics of data operations tool does not seem to work.  Instead of showing the plot in the window it makes a blank square.  Apply does seem to work but hard to tell.  Fails on both mac and PC it seems.",
    "reporter": "butler",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2015-03-01T18:24:10",
    "component": "SasView",
    "summary": "Data operations tool is broken",
    "priority": "blocker",
    "keywords": "",
    "milestone": "SasView 3.1.0",
    "owner": "ricardo",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2015/03/22 16:21:43`: **butler** changed priority from "major" to "blocker"

**Comment by butlerpd** [comment]
Trac update at `2015/03/23 03:28:56`: 
* **butler** changed owner from "" to "butler"
* **butler** changed status from "new" to "accepted"

**Comment by butlerpd** [comment]
Trac update at `2015/04/06 06:59:53`: 
* **butler** commented:

On March 26, 2015 Paul Kienzle added the following note to ticket 390 which really belongs here so copying it over here.

 The drop down box Tool:Data Operation:Data1 doesn't work on mac, but works on windows.

Note that actually the drop down on mac has a fast "jitter" which does not the PC, but the PC is not able to see any data in the box once chosen.


* **butler** changed description from "Check the graphics of data operations tool - does not seem to work.  Instead of showing the plot in the window it makes a blank square.  Apply does seem to work." to "The graphics of data operations tool does not seem to work.  Instead of showing the plot in the window it makes a blank square.  Apply does seem to work but hard to tell.  Fails on both mac and PC it seems."
* **butler** changed summary from "Check on using data operations tool" to "Data operations tool is broken"

**Comment by butlerpd** [comment]
Trac update at `2015/04/06 13:01:11`: **butler** commented:

Some sleuthing seems to indicat that the problem is in add_image method of DataOperPanel in data_operato.py.  The final line is:

```text
  self.subplot.figure.canas.draw()
```

This line does seem to draw the data in the pre code-camp version but does nothing now.

**Comment by butlerpd** [comment]
Trac update at `2015/04/22 01:43:14`: **butler** commented:

Ricardo Notes on April 21, 2015:

The problem seems to lie with the wx.EVT_PAINT. It can’t be used without wx.PaintDC.  Otherwise it creates a stream of events that in this case are calling:

```text
 464    def set_panel_on_focus(self, event)
```
Thus the dropdown flickering in Mac….

In my Ubuntu changing this:

```text
  65         self.Bind(wx.EVT_PAINT, self.set_panel_on_focus)
```
to:

```text
65         self.Bind(wx.EVT_SET_FOCUS, self.set_panel_on_focus)
```
Sorted out the problems

**Comment by butlerpd** [comment]
Trac update at `2015/04/22 01:48:04`: **butler** commented:

Testing this fix it seems that it probably fixes the mac flicker problem and changes the PC failure behavior on redrawing but the data is still not plotted.  It now leaves the panel apparently intact (with a question mark) instead of plotting a blank square.  This however does seem to be an appropriate correction even if it does not completely fix the problem.

**Comment by smk78** [comment]
Trac update at `2015/04/22 09:16:16`: **smk78** commented:

22/04/15 09:36 BST
Just PULLed from the repo and built SasView locally. I no longer have a Tools option in my menu bar!

**Comment by ricleal** [comment]
Trac update at `2015/04/22 21:22:05`: **ricardo** commented:

In ```sas/perspectives/calculator/data_operator.py```: 

```text
        self.Bind(wx.EVT_SET_FOCUS, self.set_panel_on_focus)
```
I guess we still need an event different from ```wx.EVT_PAINT``` because there is no 
```wx.PaintDC``` to catch the stream of events. You can easily see this with prints in

```text
    def set_panel_on_focus(self, event):
```
Not sure if the ```wx.EVT_SET_FOCUS``` is the right one.

Regarding the images not appearing. The problem was in the ```PlotPanel.properties(self, prop)```. It was using the old matplotlib latex format. In my Ubuntu everything appears to work now.

The changes were committed to branch '''ricardo_dev'''.

**Comment by ricleal** [comment]
Trac update at `2015/04/23 15:39:27`: **ricardo** commented:

It looks like matplotlib is smart enough to detect latex and plot the right labels.

The problem was an empty label being rendered as ```r"$$"```. There's test for empty strings now [https://github.com/SasView/sasview/commit/7e0f9b55273843a20a74196a1fed0b9a76b3f411].
No need for ```matplotlib.rc('text', usetex=True)``` which was making thing slow (Don't know why...).

Tested in Ubuntu and Mac:
- Tools -> Data Operations : Working
- Data Explorer -> New Plot : Working

**Comment by butlerpd** [comment]
Trac update at `2015/04/23 16:55:56`: 
* **butler** commented:

Downloaded from ESS Jenkins server and tested on windows - works fine.


* **butler** changed owner from "butler" to "ricardo"
* **butler** changed status from "accepted" to "assigned"

**Comment by ricleal** [comment]
Trac update at `2015/04/24 12:35:39`: 
* **ricardo** changed resolution from "" to "fixed"
* **ricardo** changed status from "assigned" to "closed"
