### ISSUE TITLE
Test invariant state (Trac #372)

### ISSUE THREAD

**Issue by mdoucet** [SasView/sasview#507]
The invariant state code (invariant_state.py) redefined 'list' to store the default state (yup, you read that right). I fixed it but someone should thoroughly test the related functionality.

Migrated from http://trac.sasview.org/ticket/372
```json
{
    "status": "closed",
    "changetime": "2015-04-07T19:06:03",
    "_ts": "2015-04-07 19:06:03.672550+00:00",
    "description": "The invariant state code (invariant_state.py) redefined 'list' to store the default state (yup, you read that right). I fixed it but someone should thoroughly test the related functionality.",
    "reporter": "mathieu",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView QA and testing",
    "time": "2015-03-05T15:10:04",
    "component": "SasView",
    "summary": "Test invariant state",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 3.1.0",
    "owner": "Gonzalezm",
    "type": "task"
}
```

**Comment by butlerpd** [comment]
Trac update at `2015/03/22 22:50:18`: 
* **butler** changed milestone from "SasView Next Release +1" to "SasView 3.1"
* **butler** changed workpackage from "SasView Bug Fixing" to "SasView QA and testing"

**Comment by butlerpd** [comment]
Trac update at `2015/03/24 14:57:34`: 
* **butler** changed owner from "" to "Gonzales"
* **butler** changed status from "new" to "assigned"

**Comment by butlerpd** [comment]
Trac update at `2015/03/25 04:07:37`: **butler** changed owner from "Gonzales" to "Gonzalezm"

**Comment by butlerpd** [comment]
Trac update at `2015/04/07 19:06:03`: 
* **butler** commented:

Miguel and Paul Butler tested.  Functionality seems to be working fine.  Some esthetics could be improved but not deemed enough to add to 3.1 release tasks.  Consequently this ticket is closed.


* **butler** changed resolution from "" to "fixed"
* **butler** changed status from "assigned" to "closed"
