### ISSUE TITLE
HayterMSAsq erratic results at very small Q and needs test on Mac (Trac #377)

### ISSUE THREAD

**Issue by RichardHeenan** [SasView/sasview#511]
HayterMSAsq gives poor reproducibility on different cpu at very small Q.

It likely needs an asymptotic limit in the code. (RichardH will later try to add HayterRMSA as used in FISH, which is in any case better.)
It also needs to be tested on a Mac cpu.

Paul K said: can run a number of different configurations:

    intel-cpu-single-dll
    intel-cpu-single-ocl
    intel-gpu-single-ocl
    nvidia-gpu-single-ocl

    intel-cpu-double-dll
    intel-cpu-double-ocl
    intel-gpu-double-ocl   Not supported
    nvidia-gpu-double-ocl

It fails completely on intel-gpu-single-ocl and it gives invalid results for low q on the other single precision platforms (gpu and cpu). The double precision platforms work fine.

Migrated from http://trac.sasview.org/ticket/377
```json
{
    "status": "closed",
    "changetime": "2016-03-19T12:06:51",
    "_ts": "2016-03-19 12:06:51.215372+00:00",
    "description": "HayterMSAsq gives poor reproducibility on different cpu at very small Q.[[BR]]\nIt likely needs an asymptotic limit in the code. (RichardH will later try to add HayterRMSA as used in FISH, which is in any case better.)\nIt also needs to be tested on a Mac cpu.\n\nPaul K said: can run a number of different configurations:\n\n    intel-cpu-single-dll\n    intel-cpu-single-ocl\n    intel-gpu-single-ocl\n    nvidia-gpu-single-ocl\n\n    intel-cpu-double-dll\n    intel-cpu-double-ocl\n    intel-gpu-double-ocl   Not supported\n    nvidia-gpu-double-ocl\n\nIt fails completely on intel-gpu-single-ocl and it gives invalid results for low q on the other single precision platforms (gpu and cpu). The double precision platforms work fine.\n",
    "reporter": "richardh",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView QA and testing",
    "time": "2015-03-10T10:21:10",
    "component": "SasView",
    "summary": "HayterMSAsq erratic results at very small Q and needs test on Mac",
    "priority": "blocker",
    "keywords": "",
    "milestone": "SasView 4.0.0",
    "owner": "pkienzle",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2015/08/14 20:09:48`: **butler** changed milestone from "SasView Next Release +1" to "SasView 4.0.0"

**Comment by butlerpd** [comment]
Trac update at `2015/12/19 18:55:26`: **butler** changed workpackage from "SasView Bug Fixing" to "SasView QA and testing"

**Comment by butlerpd** [comment]
Trac update at `2016/03/06 18:59:23`: 
* **butler** commented:

This is probably part of the core sasmodels work .. or at least very close.  Think we should make this blocker for now -- though if it "works" but refinement is still desired we can downgrade this a bit?


* **butler** changed priority from "minor" to "blocker"

**Comment by butlerpd** [comment]
Trac update at `2016/03/06 20:57:53`: 
* **butler** changed owner from "Paul K" to "pkienzle"
* **butler** changed status from "new" to "assigned"

**Comment by RichardHeenan** [comment]
Trac update at `2016/03/10 18:50:08`: **richardh** commented:

I now have a better version, having fixed a bug in my Taylor expansion at small Q, this has not been uploaded to |GIT as I want to change its name also, will need help to sort ths at code camp.
Richard

**Comment by butlerpd** [comment]
Trac update at `2016/03/19 12:06:42`: **butler** commented:

This is as finished as it will be.  Main conclusion is it will have to ALWAYS use double precision.  May add a FISH version later which may be more stable. Closing this ticket.

**Comment by butlerpd** [comment]
Trac update at `2016/03/19 12:06:51`: 
* **butler** changed resolution from "" to "fixed"
* **butler** changed status from "assigned" to "closed"
