### ISSUE TITLE
Add documentation for BUMPS usage and integrate rst files to SasView from BUMPS repo (Trac #378)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#512]
We do need to add documentation to explain How to use the BUMPS optimization options including: the meaning of the options (DREAM vs LM vs NMS etc), the meaning of the parameters for each option, and how to interpret the diagnostic plots produced.

Migrated from http://trac.sasview.org/ticket/378
```json
{
    "status": "closed",
    "changetime": "2019-03-26T10:08:09",
    "_ts": "2019-03-26 10:08:09.126789+00:00",
    "description": "We do need to add documentation to explain How to use the BUMPS optimization options including: the meaning of the options (DREAM vs LM vs NMS etc), the meaning of the parameters for each option, and how to interpret the diagnostic plots produced.",
    "reporter": "butler",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Documentation",
    "time": "2015-03-10T16:31:46",
    "component": "SasView",
    "summary": "Add documentation for BUMPS usage and integrate rst files to SasView from BUMPS repo",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView Next Release +1",
    "owner": "pkienzle",
    "type": "enhancement"
}
```

**Comment by butlerpd** [comment]
Trac update at `2015/03/22 22:30:32`: **butler** changed milestone from "SasView Next Release +1" to "SasView 3.1"

**Comment by butlerpd** [comment]
Trac update at `2015/03/24 14:53:05`: 
* **butler** changed owner from "" to "pkienzle"
* **butler** changed status from "new" to "assigned"

**Comment by pkienzle** [comment]
Trac update at `2015/05/08 19:11:08`: **pkienzle** commented:

If the bumps source tree is available, then the doc build can copy in the optimizer info as part of the build process.  This is done in:

    docs/sphinx-docs/build_sphinx.py

Before closing the ticket, update the build machines so that bumps source is available, and update src/sas/perspectives/fitting/media/fitting.rst so that it includes:

    Information on the SasView Optimisers <optimizer>

**Comment by butlerpd** [comment]
Trac update at `2015/05/19 14:36:54`: **butler** changed summary from "Add documentation for BUMPS usage" to "Add documentation for BUMPS usage and integrate rst files to SasView from BUMPS repo"

**Comment by pkienzle** [comment]
Trac update at `2015/06/16 14:25:56`: **pkienzle** commented:

Need a Help button on the optimizer selection form.  This will need to be a parameter to the dialog panel giving the URL for the help page; if the URL is not provided, then no Help button should appear.

**Comment by butlerpd** [comment]
Trac update at `2015/06/21 17:29:41`: **butler** commented:

I have tried the build downloaded from Jenkins on both Mac and PC and the BUMPS docs are "natively" available on both. I thus have removed the web link option as too ugly and unecessary.  The only open question I think now is whether we need to add the help button to the BUMPS option panel.  Since that panel is part of the bumps package it may be a bit more complicated?  Otherwise I vote we close this ticket and open a new one to implement a different approach to getting the bumps documentation into SasView if this would be appropriate.

**Comment by butlerpd** [comment]
Trac update at `2015/06/30 15:29:04`: 
* **butler** commented:

We will not fix the HELP button this release so can now move this ticket to next release


* **butler** changed milestone from "SasView 3.1" to "SasView Next Release +1"
* **butler** changed type from "defect" to "enhancement"

**Comment by butlerpd** [comment]
Trac update at `2015/08/14 20:03:33`: **butler** changed milestone from "SasView Next Release +1" to "SasView 4.0.0"

**Comment by butlerpd** [comment]
Trac update at `2016/03/20 22:49:33`: **butler** changed milestone from "SasView 4.0.0" to "SasView Next Release +1"

**Comment by smk78** [comment]
Trac update at `2019/03/26 10:07:52`: **smk78** commented:

Checked behaviour in 4.2.1 on Windows and OSX, and in 5.0b2 on Windows. All Fit Options (called Fit Algorithms in 5.0b2) panels have a Help button that brings up optimizer.html. This appears to mean this ticket is complete and so closing it.

**Comment by smk78** [comment]
Trac update at `2019/03/26 10:08:09`: 
* **smk78** changed resolution from "" to "fixed"
* **smk78** changed status from "assigned" to "closed"
