### ISSUE TITLE
Starup Error on Windows (Trac #383)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#517]
Starting up the latest build of !SasView on windows the program loads but gives the followin error which needs to be acknowledged before continuing

```text
10:38:23: No image handler for type 25 defined.
10:38:23: Failed to load image from file "C:\Program Files (x86)\SasView\images\icons\ball.ico".
```

This does NOT happen for the current mac version HOWEVER, The log file also has the following error recorded which may or may not be relevant and IS also an error reported by the mac:

```text
2015-03-22 10:53:42,319 INFO using custom_config from C:\Users\Paul\.sasview\config
2015-03-22 10:53:42,466 INFO icon path: C:\Program Files (x86)\SasView\images
2015-03-22 10:53:42,469 ERROR [Error 3] The system cannot find the path specified: 'perspectives/*.*'
2015-03-22 10:53:45,427 INFO pluging model dir: C:\Users\Paul\.sasview\plugin_models
```

Not sure what it actually affects -- visually the ball icon is on all the startup frames at least that I can see and the program runs afterwards (well .. it is very buggy right now but to the extent that it does run ... )  Nonetheless it is clear that we cannot release something that starts up with a dire warning!

Migrated from http://trac.sasview.org/ticket/383
```json
{
    "status": "closed",
    "changetime": "2015-04-01T17:37:28",
    "_ts": "2015-04-01 17:37:28.575914+00:00",
    "description": "Starting up the latest build of !SasView on windows the program loads but gives the followin error which needs to be acknowledged before continuing\n\n{{{\n10:38:23: No image handler for type 25 defined.\n10:38:23: Failed to load image from file \"C:\\Program Files (x86)\\SasView\\images\\icons\\ball.ico\".\n}}}\n\nThis does NOT happen for the current mac version HOWEVER, The log file also has the following error recorded which may or may not be relevant and IS also an error reported by the mac:\n{{{\n2015-03-22 10:53:42,319 INFO using custom_config from C:\\Users\\Paul\\.sasview\\config\n2015-03-22 10:53:42,466 INFO icon path: C:\\Program Files (x86)\\SasView\\images\n2015-03-22 10:53:42,469 ERROR [Error 3] The system cannot find the path specified: 'perspectives/*.*'\n2015-03-22 10:53:45,427 INFO pluging model dir: C:\\Users\\Paul\\.sasview\\plugin_models\n}}}\n\nNot sure what it actually affects -- visually the ball icon is on all the startup frames at least that I can see and the program runs afterwards (well .. it is very buggy right now but to the extent that it does run ... )  Nonetheless it is clear that we cannot release something that starts up with a dire warning!",
    "reporter": "butler",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2015-03-22T15:18:45",
    "component": "SasView",
    "summary": "Starup Error on Windows",
    "priority": "blocker",
    "keywords": "",
    "milestone": "SasView 3.1.0",
    "owner": "butler",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2015/03/22 16:21:00`: **butler** changed description from:

> Starting up the latest build of !SasView on windows (need to test Mac) the program loads but gives the followin error which needs to be acknowledged before continuint
> 
> {{{
> 10:38:23: No image handler for type 25 defined.
> 10:38:23: Failed to load image from file "C:\Program Files (x86)\SasView\images\icons\ball.ico".
> }}}
> 
> Not sure what it actually affects -- visually the ball icon is on all the startup frames at least that I can see and the program runs afterwards (well .. it is very buggy right now but to the extent that it does run ... )  Nonetheless it is clear that we cannot release something that starts up with a dire warning!

to:

> Starting up the latest build of !SasView on windows (need to test Mac) the program loads but gives the followin error which needs to be acknowledged before continuint
> 
> {{{
> 10:38:23: No image handler for type 25 defined.
> 10:38:23: Failed to load image from file "C:\Program Files (x86)\SasView\images\icons\ball.ico".
> }}}
> 
> The log file also has the following error recorded which may or may not be relevant:
> {{{
> 2015-03-22 10:53:42,319 INFO using custom_config from C:\Users\Paul\.sasview\config
> 2015-03-22 10:53:42,466 INFO icon path: C:\Program Files (x86)\SasView\images
> 2015-03-22 10:53:42,469 ERROR [Error 3] The system cannot find the path specified: 'perspectives/*.*'
> 2015-03-22 10:53:45,427 INFO pluging model dir: C:\Users\Paul\.sasview\plugin_models
> }}}
> 
> Not sure what it actually affects -- visually the ball icon is on all the startup frames at least that I can see and the program runs afterwards (well .. it is very buggy right now but to the extent that it does run ... )  Nonetheless it is clear that we cannot release something that starts up with a dire warning!

**Comment by butlerpd** [comment]
Trac update at `2015/03/22 22:20:33`: **butler** changed description from:

> Starting up the latest build of !SasView on windows (need to test Mac) the program loads but gives the followin error which needs to be acknowledged before continuint
> 
> {{{
> 10:38:23: No image handler for type 25 defined.
> 10:38:23: Failed to load image from file "C:\Program Files (x86)\SasView\images\icons\ball.ico".
> }}}
> 
> The log file also has the following error recorded which may or may not be relevant:
> {{{
> 2015-03-22 10:53:42,319 INFO using custom_config from C:\Users\Paul\.sasview\config
> 2015-03-22 10:53:42,466 INFO icon path: C:\Program Files (x86)\SasView\images
> 2015-03-22 10:53:42,469 ERROR [Error 3] The system cannot find the path specified: 'perspectives/*.*'
> 2015-03-22 10:53:45,427 INFO pluging model dir: C:\Users\Paul\.sasview\plugin_models
> }}}
> 
> Not sure what it actually affects -- visually the ball icon is on all the startup frames at least that I can see and the program runs afterwards (well .. it is very buggy right now but to the extent that it does run ... )  Nonetheless it is clear that we cannot release something that starts up with a dire warning!

to:

> Starting up the latest build of !SasView on windows the program loads but gives the followin error which needs to be acknowledged before continuing
> 
> {{{
> 10:38:23: No image handler for type 25 defined.
> 10:38:23: Failed to load image from file "C:\Program Files (x86)\SasView\images\icons\ball.ico".
> }}}
> 
> This does NOT happen for the current mac version HOWEVER, The log file also has the following error recorded which may or may not be relevant and IS also an error reported by the mac:
> {{{
> 2015-03-22 10:53:42,319 INFO using custom_config from C:\Users\Paul\.sasview\config
> 2015-03-22 10:53:42,466 INFO icon path: C:\Program Files (x86)\SasView\images
> 2015-03-22 10:53:42,469 ERROR [Error 3] The system cannot find the path specified: 'perspectives/*.*'
> 2015-03-22 10:53:45,427 INFO pluging model dir: C:\Users\Paul\.sasview\plugin_models
> }}}
> 
> Not sure what it actually affects -- visually the ball icon is on all the startup frames at least that I can see and the program runs afterwards (well .. it is very buggy right now but to the extent that it does run ... )  Nonetheless it is clear that we cannot release something that starts up with a dire warning!

**Comment by butlerpd** [comment]
Trac update at `2015/03/24 14:56:10`: 
* **butler** changed owner from "" to "butler"
* **butler** changed status from "new" to "accepted"

**Comment by smk78** [comment]
Trac update at `2015/03/24 15:14:00`: **smk78** commented:

This may be helpful?
https://forums.wxwidgets.org/viewtopic.php?t=21065

**Comment by pkienzle** [comment]
Trac update at `2015/03/31 19:37:06`: **pkienzle** commented:

Changed file type from BITMAP_TYPE_ICON to BITMAP_TYPE_ICO and that removes the error message on windows.

The other error persists:

    The system cannot find the path specified: 'perspectives/*.*'

**Comment by pkienzle** [comment]
Trac update at `2015/03/31 20:05:23`: **pkienzle** commented:

The perspectives/*.* error is coming from:
 
    File(line): src/sas/guiframe/gui_manager.py(899)
    Method:  sas.guiframe.gui_manager.ViewerFrame._find_plugins
    Statement: file_list = os.listdir(dir)

The perspectives still seem to load, so maybe this is just for user defined perspectives?

If so, it should not give an error if no perspectives are available.
