### ISSUE TITLE
Crashing mostly on Exit (Trac #384)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#518]
The last several builds have been crashing, mostly on exit but not always with the following error popup with title of Microsoft Visual C++ Runtime Library

```text
               Microsoft Visual C++ Runtime Library

Runtime Error!

Program: C:\Program Files (x86)\SasView\SasView.exe

R6025
- pure virtual function call
```

One has to click OK and it pops up again and again.  Eventually clicking Ok a popup indicates !SasView has crashed.  No information is added to the log that can help debug more.

NOTE: this has been verified using windows installer version downloaded from ESS Jenkins builds.

Migrated from http://trac.sasview.org/ticket/384
```json
{
    "status": "closed",
    "changetime": "2015-05-07T00:22:35",
    "_ts": "2015-05-07 00:22:35.911774+00:00",
    "description": "The last several builds have been crashing, mostly on exit but not always with the following error popup with title of Microsoft Visual C++ Runtime Library\n{{{\n               Microsoft Visual C++ Runtime Library\n\nRuntime Error!\n\nProgram: C:\\Program Files (x86)\\SasView\\SasView.exe\n\nR6025\n- pure virtual function call\n}}}\n\nOne has to click OK and it pops up again and again.  Eventually clicking Ok a popup indicates !SasView has crashed.  No information is added to the log that can help debug more.\n\nNOTE: this has been verified using windows installer version downloaded from ESS Jenkins builds.",
    "reporter": "butler",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2015-03-22T15:58:08",
    "component": "SasView",
    "summary": "Crashing mostly on Exit",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 3.1.0",
    "owner": "",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2015/04/07 15:04:44`: **butler** changed milestone from "SasView Next Release +1" to "SasView 3.1"

**Comment by pkienzle** [comment]
Trac update at `2015/05/07 00:22:35`: 
* **pkienzle** commented:

More details:

You don't need to delete the graph; you just need the graph to not have focus.

The crash happens during exit processing, specifically wx._core_.App_Cleanup.

For some reason, the App_CleanUp is triggering PlotPanel.on_set_focus.  I was unable to determine why this was happening, and couldn't remove it.

Instead, I traced the crash to data_panel.set_panel_on_focus, which updates the "Append Plot" dropdown with the list of active panels, and sets the string to the active panel.

The "fix" (aka ugly hack) is to modify the function to check if the "Append Plot" dropdown widget is being deleted before updating the widget.



* **pkienzle** changed resolution from "" to "fixed"
* **pkienzle** changed status from "new" to "closed"
