### ISSUE TITLE
warning logging not consistant (Trac #386)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#520]
a recent comit indicated that warnings were put in console and after some thought were copied also to the sasview log.  Some quick checking with the recent !PrView bug checking indicates this is not quite the case.  For example the warnings that the code was UNABLE to evalutate the number of terms showed up in the console ONLY (not in the log) while the fact that the button press could not update the value showed up ONLY in the log (not in the console).  As long as it gets recoreded somewhere we are ahead of the game but not sure I understand why some go one place and other go elsewhere and seems inconsistant with what the author of the recent warning logging chages seems to think was done.

Migrated from http://trac.sasview.org/ticket/386
```json
{
    "status": "new",
    "changetime": "2015-03-22T16:13:08",
    "_ts": "2015-03-22 16:13:08.661061+00:00",
    "description": "a recent comit indicated that warnings were put in console and after some thought were copied also to the sasview log.  Some quick checking with the recent !PrView bug checking indicates this is not quite the case.  For example the warnings that the code was UNABLE to evalutate the number of terms showed up in the console ONLY (not in the log) while the fact that the button press could not update the value showed up ONLY in the log (not in the console).  As long as it gets recoreded somewhere we are ahead of the game but not sure I understand why some go one place and other go elsewhere and seems inconsistant with what the author of the recent warning logging chages seems to think was done.",
    "reporter": "butler",
    "cc": "",
    "resolution": "",
    "workpackage": "SasView Bug Fixing",
    "time": "2015-03-22T16:13:08",
    "component": "SasView",
    "summary": "warning logging not consistant",
    "priority": "minor",
    "keywords": "",
    "milestone": "SasView Next Release +1",
    "owner": "",
    "type": "defect"
}
```

**Comment by lucas-wilkins** [comment]
I think as long as the logger window has started and the programmer uses the logging package it will go to the logger window.

If there's specific cases where this isn't the behaviour, I suggest making specific issues for them.

Otherwise, I vote to close this.

**Comment by butlerpd** [comment]
I'm not sure this is 100% "fixed" -- likely because there are some old parts of the code that don't use the logger facility.  That said, as an overarching ticket this may now be well past its "use by date."  Agree that new instances that pop up should be flagged individually. As the person reporting the issue I'm going to just close it.
