### ISSUE TITLE
Need new tutorial documentation (Trac #387)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#521]
The old tutorial file is quite dated now and needs a complete rewrite.

Migrated from http://trac.sasview.org/ticket/387
```json
{
    "status": "closed",
    "changetime": "2017-04-06T15:14:10",
    "_ts": "2017-04-06 15:14:10.410784+00:00",
    "description": "The old tutorial file is quite dated now and needs a complete rewrite.",
    "reporter": "butler",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Documentation",
    "time": "2015-03-22T16:54:04",
    "component": "SasView",
    "summary": "Need new tutorial documentation",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView Next Release +1",
    "owner": "smk78",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2016/03/06 18:42:12`: 
* **butler** commented:

Starting this task is a core task for code camp IV/release 4.0 ... but not necessarily finishing it. Thus not sure whether to mark as blocker or critical? For now going to mark it critical.


* **butler** changed milestone from "SasView Next Release +1" to "SasView 4.0.0"
* **butler** changed priority from "major" to "critical"

**Comment by butlerpd** [comment]
Trac update at `2016/03/06 21:10:15`: 
* **butler** commented:

Moving to blocker to make clear distinction between core tasks (blocker) and related tasks (critical) and important wish lists (major).



* **butler** changed owner from "" to "smk78"
* **butler** changed priority from "critical" to "blocker"
* **butler** changed status from "new" to "assigned"

**Comment by butlerpd** [comment]
Trac update at `2016/03/15 17:28:55`: **butler** commented:

Upon review, the current tutorial is not as much a tutorial as a more graphical and slightly more detailed user documentation.  This should be replaced with proper tutorial documentation which actually takes a user thought the steps to getting actual answers at the end, starting from example data sets loaded with !SasView.  These should be modular so that tutorials can be added as we go along but also be bundled into a single PDF or HTML for someone who wants to get the whole lot without having to make sure they've downloaded all the individual tutorial modules.  This will be an ongoing task so this ticket should be considered complete when a starting list of tutorials needed has been generated and tickets created and at least one tutorial has been completed and builds properly for distribution.

**Comment by butlerpd** [comment]
Trac update at `2016/03/18 23:07:53`: 
* **butler** commented:

Only getting started on this project was part of code camp VI. Having established a plan and the critical items for a release beginning to be urgent, this is now done.  Will downgrade to major with the idea that it will move to next release milestone when we are ready for a release.


* **butler** changed priority from "blocker" to "major"

**Comment by butlerpd** [comment]
Trac update at `2016/06/19 02:02:35`: 
* **butler** commented:

It is clear no more will be done for this release on this ticket so moving to next+1 as suggested earlier.



* **butler** changed milestone from "SasView 4.0.0" to "SasView Next Release +1"

**Comment by butlerpd** [comment]
Trac update at `2016/09/05 03:00:00`: **butler** changed milestone from "SasView Next Release +1" to "SasView 4.1.0"

**Comment by smk78** [comment]
Trac update at `2016/10/11 16:37:19`: **smk78** commented:

This ticket is stalled whilst we assess the best technology platform(s) for actually providing the tutorials. Whilst ReST (for Sphinx harmonisation) carries many advantages, from the perspective of those we intend to get to write the tutorials (various SANS instrument team staff) the learning curve is steep and the production overhead (ie, the time spent trying to get content to satisfy ResT/Sphinx/LaTex/MathJax coding rules) is high. Is there anything out there, for example, like Word that generates ReST???

**Comment by smk78** [comment]
Trac update at `2016/10/11 16:37:44`: **smk78** changed milestone from "SasView 4.1.0" to "SasView Next Release +1"

**Comment by smk78** [comment]
Trac update at `2017/04/06 15:14:10`: 
* **smk78** commented:

Superseded by #1010
Ticket closed.


* **smk78** changed resolution from "" to "fixed"
* **smk78** changed status from "assigned" to "closed"
