### ISSUE TITLE
Missing documentation about residual plot (and fit plot) (Trac #389)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#523]
The fitting plot and residual plot have no documentation. In partiular how the "normalized residuals" are calculated or how to interact with the fit plot (to set fit limits for instance) are not documented as far as I can tell

Migrated from http://trac.sasview.org/ticket/389
```json
{
    "status": "closed",
    "changetime": "2015-11-22T01:39:30",
    "_ts": "2015-11-22 01:39:30.258799+00:00",
    "description": "The fitting plot and residual plot have no documentation. In partiular how the \"normalized residuals\" are calculated or how to interact with the fit plot (to set fit limits for instance) are not documented as far as I can tell",
    "reporter": "butler",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Documentation",
    "time": "2015-03-22T17:21:24",
    "component": "SasView",
    "summary": "Missing documentation about residual plot (and fit plot)",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 3.1.0",
    "owner": "",
    "type": "defect"
}
```

**Comment by smk78** [comment]
Trac update at `2015/06/05 10:32:36`: **smk78** commented:

Section on Fitting Limits now added to Fitting Data documentation.

**Comment by smk78** [comment]
Trac update at `2015/06/16 14:43:14`: 
* **smk78** commented:

Section on Assessing Fit Quality now added to Fitting Perspective documentation.

Both points in this ticket would therefore seem to be addressed so it can be closed.


* **smk78** changed resolution from "" to "fixed"
* **smk78** changed status from "new" to "closed"

**Comment by butlerpd** [comment]
Trac update at `2015/11/22 01:39:30`: **butler** changed milestone from "SasView Next Release +1" to "SasView 3.1.0"
