### ISSUE TITLE
Problem with menu and toolbar on mac (Trac #390)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#524]
Two issues identified on the mac:
1. The menu bar on the mac starts up wiht TWO Fitting items.  Fitting is the one menu item which behaves differently from the others in that it belongs to the perspective.  So when switching to P(r) for example that menu item disappears and would be replaced by a P(r) menu item except that neither P(r) nor Invariant define a menu item.  Somehow the mac is confused and has one fitting menu which is permanent and one which disappears as it is meant to. Not that since the optimization engine choice show up on the fitting menu and are used presumably by P(r) at least? this is a problem -- will make separate ticket on that.
2. the label box on the toolbar which is supposed to contain which perspective is active is blank.  Note that that is probably redundant and could be removed since the application frame title seems to show the name of the active perspective both on the PC and the mac

Migrated from http://trac.sasview.org/ticket/390
```json
{
    "status": "closed",
    "changetime": "2015-05-06T13:42:09",
    "_ts": "2015-05-06 13:42:09.697850+00:00",
    "description": "Two issues identified on the mac:\n1. The menu bar on the mac starts up wiht TWO Fitting items.  Fitting is the one menu item which behaves differently from the others in that it belongs to the perspective.  So when switching to P(r) for example that menu item disappears and would be replaced by a P(r) menu item except that neither P(r) nor Invariant define a menu item.  Somehow the mac is confused and has one fitting menu which is permanent and one which disappears as it is meant to. Not that since the optimization engine choice show up on the fitting menu and are used presumably by P(r) at least? this is a problem -- will make separate ticket on that.\n2. the label box on the toolbar which is supposed to contain which perspective is active is blank.  Note that that is probably redundant and could be removed since the application frame title seems to show the name of the active perspective both on the PC and the mac",
    "reporter": "butler",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2015-03-22T23:05:02",
    "component": "SasView",
    "summary": "Problem with menu and toolbar on mac",
    "priority": "blocker",
    "keywords": "",
    "milestone": "SasView 3.1.0",
    "owner": "ajj",
    "type": "defect"
}
```

**Comment by pkienzle** [comment]
Trac update at `2015/03/26 16:50:19`: **pkienzle** commented:

The drop down box Tool:Data Operation:Data1 doesn't work on mac, but works on windows.

**Comment by butlerpd** [comment]
Trac update at `2015/04/06 06:15:27`: **butler** commented:

the Data Operation problem is a known issue and is a problem on both mac and PC and is part of ticket #505.  Am adding this mac comment to that ticket.  Will not address here

**Comment by butlerpd** [comment]
Trac update at `2015/04/06 06:30:02`: 
* **butler** commented:

Andrew Jackson created a new ticket #537 which is really a duplicate of this one.  Am copying his comments here before closing that ticket.  Also significantly raising priority to match his call on it.

  On the Mac (OS X 10.10) two fitting menus appear. This might seem to just be cosmetic, but the menus do not     confer the same functionality - for instance the !Constrained/Simultaneous? Fit option only becomes un-greyed in the "first" menu and not in the second.
  In any case, this is very confusing for the user.


* **butler** changed milestone from "SasView Next Release +1" to "SasView 3.1"
* **butler** changed priority from "major" to "blocker"

**Comment by butlerpd** [comment]
Trac update at `2015/04/06 06:33:48`: **butler** commented:

Did not notice the added comment by AJJ on ticket #537 which I now copy here:

  NB tested on build http://trac.sasview.org/ticket/143 from april 2nd

**Comment by butlerpd** [comment]
Trac update at `2015/04/07 14:32:48`: 
* **butler** changed owner from "" to "ajj"
* **butler** changed status from "new" to "assigned"

**Comment by mdoucet** [comment]
Trac update at `2015/05/05 14:23:39`: **mathieu** commented:

There are apparently two mechanisms to set the default perspective at startup. One was using the "standalone" data member of base_plugin, and the other was through the SasView configuration. The two were clashing. Standalone=True was hard-coded for the fitting perspective. I remove that so that it behaves like a normal perspective.

**Comment by ajj** [comment]
Trac update at `2015/05/06 13:42:09`: 
* **ajj** commented:

This looks like it is fixed on Mac and Windows. Declaring it fixed.


* **ajj** changed resolution from "" to "fixed"
* **ajj** changed status from "assigned" to "closed"
