### ISSUE TITLE
sasview.org should redirect to www.sasview.org (Trac #394)

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#528]
Currently sasview.org redirects to trac.sasview.org, which is not where users should land when they type sasview.org in the url bar.

The front page of trac should include a link to sasview.org

Migrated from http://trac.sasview.org/ticket/394
```json
{
    "status": "closed",
    "changetime": "2016-06-19T01:55:30",
    "_ts": "2016-06-19 01:55:30.910030+00:00",
    "description": "Currently sasview.org redirects to trac.sasview.org, which is not where users should land when they type sasview.org in the url bar.\n\nThe front page of trac should include a link to sasview.org",
    "reporter": "pkienzle",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Admin",
    "time": "2015-03-23T20:40:41",
    "component": "SasView",
    "summary": "sasview.org should redirect to www.sasview.org",
    "priority": "major",
    "keywords": "",
    "milestone": "Admin Tasks",
    "owner": "",
    "type": "defect"
}
```

**Comment by pkienzle** [comment]
Trac update at `2015/03/23 20:51:21`: **pkienzle** commented:

I added the following to trac.sasview.org:

```text
= !SasView Home Page =

Details about SasView can be found on the [https://www.sasview.org/ SasView home page] 
```

The dns record still needs to be updated to forward sasview.org to www.sasview.org.

**Comment by butlerpd** [comment]
Trac update at `2016/06/19 01:55:30`: 
* **butler** commented:

Finally figured out how --- silly in the end.  Disciplined and professional??


* **butler** changed resolution from "" to "fixed"
* **butler** changed status from "new" to "closed"
