### ISSUE TITLE
GelFit model presents an erroneous parameter (Trac #399)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#533]
The !GelFit model has 6 parameters, one of which is called 'scale'.
However, this is NOT a scale parameter! Visiting the model definition 
help file shows this to be a fractal exponent!

Trial fitting suggests the parameter is indeed behaving like a fractal 
exponent and thus all that is needed is for the parameter to be renamed 
in the model.

Migrated from http://trac.sasview.org/ticket/399
```json
{
    "status": "closed",
    "changetime": "2015-11-22T01:14:01",
    "_ts": "2015-11-22 01:14:01.503565+00:00",
    "description": "The !GelFit model has 6 parameters, one of which is called 'scale'.\nHowever, this is NOT a scale parameter! Visiting the model definition \nhelp file shows this to be a fractal exponent!\n\nTrial fitting suggests the parameter is indeed behaving like a fractal \nexponent and thus all that is needed is for the parameter to be renamed \nin the model.\n\n",
    "reporter": "smk78",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasModels Redesign",
    "time": "2015-03-31T16:44:16",
    "component": "SasView",
    "summary": "GelFit model presents an erroneous parameter",
    "priority": "critical",
    "keywords": "",
    "milestone": "SasView 3.1.1",
    "owner": "",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2015/07/26 16:39:50`: **butler** changed description from:

> The GelFit model has 6 parameters, one of which is called 'scale'.
> However, this is NOT a scale parameter! Visiting the model definition 
> help file shows this to be a fractal exponent!
> 
> Trial fitting suggests the parameter is indeed behaving like a fractal 
> exponent and thus all that is needed is for the parameter to be renamed 
> in the model.
> 
> 

to:

> The !GelFit model has 6 parameters, one of which is called 'scale'.
> However, this is NOT a scale parameter! Visiting the model definition 
> help file shows this to be a fractal exponent!
> 
> Trial fitting suggests the parameter is indeed behaving like a fractal 
> exponent and thus all that is needed is for the parameter to be renamed 
> in the model.
> 
>

**Comment by butlerpd** [comment]
Trac update at `2015/07/27 01:10:06`: 
* **butler** changed _comment0 from:

> Done ... new name is FractExp.
> 

to:

> 1448154738487197


* **butler** commented:

Done ... new name is !FractExp.



* **butler** changed resolution from "" to "fixed"
* **butler** changed status from "new" to "closed"

**Comment by butlerpd** [comment]
Trac update at `2015/11/22 01:14:01`: **butler** changed milestone from "SasView Next Release +1" to "SasView 3.1.1"
