### ISSUE TITLE
DAB model equation in model function help file is wrong! (Trac #400)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#534]
There is a typo in the expression for I(q) for the DAB model (which was 
present in the original html model help file)!

The outer set of brackets in the denominator need to be raised to the 
power of 2 so that the limiting behaviour of the function is 1/q^4.

Migrated from http://trac.sasview.org/ticket/400
```json
{
    "status": "closed",
    "changetime": "2015-11-22T01:14:46",
    "_ts": "2015-11-22 01:14:46.871280+00:00",
    "description": "There is a typo in the expression for I(q) for the DAB model (which was \npresent in the original html model help file)!\n\nThe outer set of brackets in the denominator need to be raised to the \npower of 2 so that the limiting behaviour of the function is 1/q^4.\n",
    "reporter": "smk78",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasModels Redesign",
    "time": "2015-03-31T16:50:00",
    "component": "SasView",
    "summary": "DAB model equation in model function help file is wrong!",
    "priority": "critical",
    "keywords": "",
    "milestone": "SasView 3.1.1",
    "owner": "butler",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2015/04/07 13:49:57`: **butler** commented:

once fixed in release move to +1 and check in sasmodels

**Comment by butlerpd** [comment]
Trac update at `2015/04/07 14:33:15`: 
* **butler** changed owner from "" to "smk78"
* **butler** changed status from "new" to "assigned"

**Comment by butlerpd** [comment]
Trac update at `2015/04/07 19:08:47`: **butler** commented:

This needs to be changed TWO places.  Given we are in code freeze and release only mode, only changing the rst files is required now.  Once done the ticket should be so noted and moved to release 4.0 where the changed text will need to move to the sasmodel code which has already been converted with wrong documentation.

**Comment by smk78** [comment]
Trac update at `2015/04/08 12:01:30`: **smk78** commented:

Corrected equation image (image180_corrected.PNG) pushed to repo.

model_functions.rst updated to pick up the new image.

**Comment by smk78** [comment]
Trac update at `2015/04/08 12:05:27`: 
* **smk78** commented:

Model equation in sasmodel file now needs updating. This can wait until release 4.0.


* **smk78** changed milestone from "SasView 3.1" to "SasView Next Release +1"
* **smk78** changed workpackage from "SasView Documentation" to "SasModels Redesign"

**Comment by butlerpd** [comment]
Trac update at `2015/07/26 00:42:06`: 
* **butler** changed owner from "smk78" to "butler"
* **butler** changed status from "assigned" to "accepted"

**Comment by butlerpd** [comment]
Trac update at `2015/07/26 01:39:56`: 
* **butler** commented:

So looks like primary equation in sasmodels had been corrected already.  However the full current documentation had not been properly ported so that was done.  the docs now match the !SasView models documentation.  

However it seems the details string of the current !SasView version (as opposed to the rst file) does not include the L^3^ term so have fixed that as well.  We can now close this ticket 


* **butler** changed resolution from "" to "fixed"
* **butler** changed status from "accepted" to "closed"

**Comment by butlerpd** [comment]
Trac update at `2015/11/22 01:14:46`: **butler** changed milestone from "SasView Next Release +1" to "SasView 3.1.1"
