### ISSUE TITLE
easy sum custom model broken (Trac #401)

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#535]
the dialog for easy sum custom model does not allow name or description to be entered (Windows) or anything to be entered (Mac).

Migrated from http://trac.sasview.org/ticket/401
```json
{
    "status": "closed",
    "changetime": "2015-04-06T07:02:00",
    "_ts": "2015-04-06 07:02:00.901854+00:00",
    "description": "the dialog for easy sum custom model does not allow name or description to be entered (Windows) or anything to be entered (Mac).",
    "reporter": "pkienzle",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2015-03-31T18:38:22",
    "component": "SasView",
    "summary": "easy sum custom model broken",
    "priority": "blocker",
    "keywords": "",
    "milestone": "SasView 3.1.0",
    "owner": "butler",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2015/04/03 02:05:28`: **butler** commented:

Hummm works "fine" for me on both mac and PC.  I used the builds from ESS available 8PM US EDT on April 2, 2015.

However I found 2 other problems:

1) the panel has NO scrollbar - thus on my small laptop I could never reach the "apply" button and thus thwarted from saving the function

2) when applying a nonsense function no error was displayed yet no function was generated -- though this should be tested more thoroughly (only did once then came back and typed reasonable equation and all worked fine.  In fact in that case the apply button generated a message that it was succesful and how to access the function.

**Comment by butlerpd** [comment]
Trac update at `2015/04/03 02:13:45`: **butler** commented:

correction to 2 above.  The problem is when using a space in the function name.  a red "error" appears under the panel on left side but no indication of problem.  Worse, if you hit apply again it now says "name already exists." this logic is probably also wrong on PC but needs to be tested once scroll panel is added.  Actual non functional code generates pop ups describing the problem.

**Comment by butlerpd** [comment]
Trac update at `2015/04/03 02:21:46`: **butler** commented:

Ooops ... was looking at custom model not "sum" above description applies to custom only -- will generate new ticket.  Sum model is broken as described - my bad!

**Comment by butlerpd** [comment]
Trac update at `2015/04/05 12:45:03`: 
* **butler** changed owner from "" to "butler"
* **butler** changed priority from "major" to "blocker"
* **butler** changed status from "new" to "accepted"

**Comment by butlerpd** [comment]
Trac update at `2015/04/06 07:02:00`: 
* **butler** commented:

Fixed the main problem along with some niggles.  Still could use a bit more refactoring but good enough probably till we refactor for new models.


* **butler** changed resolution from "" to "fixed"
* **butler** changed status from "accepted" to "closed"
