### ISSUE TITLE
Missing documentation for custom  model editors (Trac #404)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#538]
None of the model editors accessible from Fitting/edit custom model (i.e. The composite model editor, the simple model editor, and the "advanced" model editors) have any associated documentation. 

Need to create an RST for them then had Help button on the panel to link appropriately. 

Migrated from http://trac.sasview.org/ticket/404
```json
{
    "status": "closed",
    "changetime": "2015-11-22T01:41:18",
    "_ts": "2015-11-22 01:41:18.587351+00:00",
    "description": "None of the model editors accessible from Fitting/edit custom model (i.e. The composite model editor, the simple model editor, and the \"advanced\" model editors) have any associated documentation. \n\nNeed to create an RST for them then had Help button on the panel to link appropriately. ",
    "reporter": "butler",
    "cc": "",
    "resolution": "invalid",
    "workpackage": "SasView Documentation",
    "time": "2015-04-06T06:46:00",
    "component": "SasView",
    "summary": "Missing documentation for custom  model editors",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 3.1.0",
    "owner": "",
    "type": "defect"
}
```

**Comment by smk78** [comment]
Trac update at `2015/06/16 15:04:38`: 
* **smk78** commented:

The documentation for the Fitting Perspective **does** contain subsections on Adding Your Own Models, the Custom Model Editor and Writing a Plugin. There is also information in Appendix XIII of the Tutorial.

Whilst any of our documentation could always be improved, I judge that there is sufficient for a semi-skilled user to implement a custom/plug-in model, pursuant to a later overhaul of the help documentation/tutorial.

Clicking the HELP button on the 'Sum|Multi' sub-panel does bring up the appropriate help documentation.

I will therefore close this ticket.





* **smk78** changed resolution from "" to "fixed"
* **smk78** changed status from "new" to "closed"

**Comment by butlerpd** [comment]
Trac update at `2015/11/22 01:40:58`: 
* **butler** changed milestone from "SasView Next Release +1" to "SasView 3.1.0"
* **butler** changed resolution from "fixed" to ""
* **butler** changed status from "closed" to "reopened"

**Comment by butlerpd** [comment]
Trac update at `2015/11/22 01:41:18`: 
* **butler** changed resolution from "" to "invalid"
* **butler** changed status from "reopened" to "closed"
