### ISSUE TITLE
resolution is being cleared when fit starts (Trac #405)

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#539]
With a 1-D dataset and instrumental smearing set to Use dQ Data, clicking Fit resets instrumental smearing to None.

Migrated from http://trac.sasview.org/ticket/405
```json
{
    "status": "closed",
    "changetime": "2015-04-27T23:39:49",
    "_ts": "2015-04-27 23:39:49.349982+00:00",
    "description": "With a 1-D dataset and instrumental smearing set to Use dQ Data, clicking Fit resets instrumental smearing to None.",
    "reporter": "pkienzle",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2015-04-07T00:02:54",
    "component": "SasView",
    "summary": "resolution is being cleared when fit starts",
    "priority": "critical",
    "keywords": "",
    "milestone": "SasView 3.1.0",
    "owner": "pkienzle",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2015/04/07 03:16:41`: **butler** commented:

I have verified that it is NOT a problem with version 3.1 alpha from just before code camp. It is still a problem on latest (April 6, 2015) jenkins windows build.  It is however NOT a problem on the MAC.  On windows the whole bottom half of the sizer (from smearing to fit) erase and get redrawn ... it seems twice?)

**Comment by butlerpd** [comment]
Trac update at `2015/04/07 03:17:08`: 
* **butler** changed milestone from "SasView Next Release +1" to "SasView 3.1"
* **butler** changed priority from "major" to "critical"

**Comment by butlerpd** [comment]
Trac update at `2015/04/07 14:33:52`: 
* **butler** changed owner from "" to "pkienzle"
* **butler** changed status from "new" to "assigned"

**Comment by pkienzle** [comment]
Trac update at `2015/04/14 23:45:55`: **pkienzle** commented:

The fitting perspective needs to be refactored into proper MVC.  As it stands, when the fit button is clicked the program goes through the fields on the page and pulls out various values such as the smearing to use.  Instead, the fit description should be an independent object which is updated by the GUI whenever anything on the page changes.  This should remove the problem which seems to be that the page is redrawn when the fit button is pressed, and the wrong fit description is sometimes captured.

This large of a change should not be done for 3.1, but I've made no progress on discovering exactly where the page refresh occurs that is causing the bug.

**Comment by pkienzle** [comment]
Trac update at `2015/04/27 23:39:49`: 
* **pkienzle** commented:

For reasons unknown, disabling the Fit button caused the disable_smearer button to fire.  A bug in wx?


* **pkienzle** changed resolution from "" to "fixed"
* **pkienzle** changed status from "assigned" to "closed"
