### ISSUE TITLE
Porod model equation in model function help file is wrong! (Trac #406)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#540]
There is a typo in the expression for I(q) for the Porod model (which 
was present in the original html model help file)! The difference in 
scattering length density needs to be raised to the power of 2 so that 
the resulting I(q) will have dimensions of 1/length (ie, /cm). 

Migrated from http://trac.sasview.org/ticket/406
```json
{
    "status": "closed",
    "changetime": "2015-11-22T01:15:26",
    "_ts": "2015-11-22 01:15:26.555121+00:00",
    "description": "There is a typo in the expression for I(q) for the Porod model (which \nwas present in the original html model help file)! The difference in \nscattering length density needs to be raised to the power of 2 so that \nthe resulting I(q) will have dimensions of 1/length (ie, /cm). ",
    "reporter": "smk78",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasModels Redesign",
    "time": "2015-04-07T14:57:56",
    "component": "SasView",
    "summary": "Porod model equation in model function help file is wrong!",
    "priority": "critical",
    "keywords": "",
    "milestone": "SasView 3.1.1",
    "owner": "smk78",
    "type": "defect"
}
```

**Comment by smk78** [comment]
Trac update at `2015/04/08 12:06:18`: **smk78** commented:

Corrected equation image (image197_corrected.PNG) pushed to repo.

model_functions.rst updated to pick up the new image.

**Comment by smk78** [comment]
Trac update at `2015/04/08 12:07:33`: 
* **smk78** commented:

Model equation now needs to be changed in sasmodels. This can wait until release 4.0.


* **smk78** changed milestone from "SasView 3.1" to "SasView Next Release +1"
* **smk78** changed workpackage from "SasView Documentation" to "SasModels Redesign"

**Comment by butlerpd** [comment]
Trac update at `2015/07/26 04:49:32`: 
* **butler** commented:

This model has not yet been ported to sasmodels so nothing to fix here.  Will therefore close thi ticket


* **butler** changed resolution from "" to "fixed"
* **butler** changed status from "new" to "closed"

**Comment by butlerpd** [comment]
Trac update at `2015/11/22 01:15:26`: **butler** changed milestone from "SasView Next Release +1" to "SasView 3.1.1"
