### ISSUE TITLE
error with raspberry model (Trac #410)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#544]
Lilo Pozzo reports the following problem:

  I tried fitting gold nanoparticle decorated emulsions using both Igor and SASView.     When I placed these parameters (experimental) on to the raspberry model that appears in the IGOR macros (I think it is raspberryV40), the intensity would go negative as shown.

  I could not figure out the problem because the new procedures raspberryV40 were hard to interpret (for me). This is the plot I get when fitting using the raspberryV40 and then compared to the raspberry (original model written by Andrew).

```text
Parameters
vf Large        0.0021
Radius Large (A)        500
SLD Large sphere (A-2)  1.3e-05
vf Small        1.14e-05
Radius Small (A)        57
fraction Small at surface       0.4
SLD Small sphere (A-2)  0.000123
delta   0
SLD solvent (A-2)       9e-06
bkgd (cm-1)     0
```
  Also, I believe the error (if there is one) may have been moved also to SASView since that function also goes negative when I try the same parameters.

Attached are the plots she refers too.

Migrated from http://trac.sasview.org/ticket/410
```json
{
    "status": "closed",
    "changetime": "2016-03-20T16:10:40",
    "_ts": "2016-03-20 16:10:40.116365+00:00",
    "description": "Lilo Pozzo reports the following problem:\n\n  I tried fitting gold nanoparticle decorated emulsions using both Igor and SASView.     When I placed these parameters (experimental) on to the raspberry model that appears in the IGOR macros (I think it is raspberryV40), the intensity would go negative as shown.\n\n  I could not figure out the problem because the new procedures raspberryV40 were hard to interpret (for me). This is the plot I get when fitting using the raspberryV40 and then compared to the raspberry (original model written by Andrew).\n\n{{{\nParameters\nvf Large        0.0021\nRadius Large (A)        500\nSLD Large sphere (A-2)  1.3e-05\nvf Small        1.14e-05\nRadius Small (A)        57\nfraction Small at surface       0.4\nSLD Small sphere (A-2)  0.000123\ndelta   0\nSLD solvent (A-2)       9e-06\nbkgd (cm-1)     0\n}}}\n  Also, I believe the error (if there is one) may have been moved also to SASView since that function also goes negative when I try the same parameters.\n\nAttached are the plots she refers too.",
    "reporter": "butler",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2015-04-25T19:35:48",
    "component": "SasView",
    "summary": "error with raspberry model",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.0.0",
    "owner": "ajj",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2015/04/25 19:36:03`: **butler** changed attachment from "" to "PastedGraphic-1.pdf"

**Comment by butlerpd** [comment]
Trac update at `2015/04/25 19:36:13`: **butler** changed attachment from "" to "PastedGraphic-2.pdf"

**Comment by butlerpd** [comment]
Trac update at `2015/04/25 19:36:34`: **butler** changed attachment from "" to "PastedGraphic-3.tiff"

**Comment by butlerpd** [comment]
Trac update at `2015/10/10 17:52:39`: **butler** commented:

Updated by Lilo Pozzo April 26, 2015

I think I figured out the problem with the model. It was, at some point, modified to fit directly using the fractional surface area covered. This is a more useful parameter to extract. However, it makes the function highly unstable because there are not necessarily enough small particles to fill the surface at any given surface density. I no longer think there is an error in the equations but the fits tend to go crazy in the solvers. The original equations, used in an older igor version, would fit instead to the fraction of total small particles that would adsorb. This is a well-defined parameter between 0-1. It is also independent of all other parameters. In contrast, the fraction area covered is interrelated with the large particle size (how much area is available) and the volume fractions of both large and small particles. There are unstable regions that are really hard to eliminate with constraints and the solver goes crazy.

My question is this. Is there any way we can use or run the old (original) raspberry? I think it is currently of very little use in the current configuration because of the above reasons.

**Comment by ajj** [comment]
Trac update at `2015/10/10 18:08:54`: 
* **ajj** commented:

I sent the old IGOR version of the model to Lilo, so I think from that perspective the problem is dealt with.

If the version parameterised by surface fraction coverage is proving to be unstable, we should remove it. So need to replace the version in !SasView with that version and update the documentation. I will do this when I transfer the model to sasmodels.


* **ajj** changed milestone from "SasView Next Release +1" to "SasView 4.0.0"
* **ajj** changed owner from "" to "ajj"
* **ajj** changed status from "new" to "assigned"

**Comment by butlerpd** [comment]
Trac update at `2015/10/10 18:08:54`: **butler** changed _comment0 from:

> I sent the old IGOR version of the model to Lilo, so I think from that perspective the problem is dealt with.
> 
> If the version parameterised by surface fraction coverage is proving to be unstable, we should remove it. So need to replace the version in SasView with that version and update the documentation. I will do this when I transfer the model to sasmodels.

to:

> 1457287835605777

**Comment by butlerpd** [comment]
Trac update at `2016/03/06 18:13:10`: 
* **butler** commented:

From the last entry his should be a core sasmodels task?  ... though question whether both parameterizations could be included with appropriate explanations in the documentation?  Either way moving to blocker for now as core task.  


* **butler** changed priority from "major" to "blocker"

**Comment by butlerpd** [comment]
Trac update at `2016/03/19 11:44:02`: **butler** changed priority from "blocker" to "major"

**Comment by ajj** [comment]
Trac update at `2016/03/20 16:10:40`: 
* **ajj** commented:

Reverted the model to be exact match to math in paper. Thus it is now using the fraction of small spheres adsorbed, rather than trying to use surface coverage. Seems the surface coverage version had issues due to the circular relation of some values.


* **ajj** changed resolution from "" to "fixed"
* **ajj** changed status from "assigned" to "closed"
