### ISSUE TITLE
No stop button on simultaneous fit (Trac #411)

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#545]
Clicking fit twice on the simultaneous fit panel starts a second fit running in parallel rather than stopping the current fit.

Migrated from http://trac.sasview.org/ticket/411
```json
{
    "status": "closed",
    "changetime": "2016-03-17T17:53:00",
    "_ts": "2016-03-17 17:53:00.751109+00:00",
    "description": "Clicking fit twice on the simultaneous fit panel starts a second fit running in parallel rather than stopping the current fit.",
    "reporter": "pkienzle",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2015-04-27T23:37:48",
    "component": "SasView",
    "summary": "No stop button on simultaneous fit",
    "priority": "critical",
    "keywords": "",
    "milestone": "SasView 4.0.0",
    "owner": "piotr",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2015/08/14 19:56:57`: **butler** changed milestone from "SasView Next Release +1" to "SasView 4.0.0"

**Comment by butlerpd** [comment]
Trac update at `2015/10/25 16:52:36`: **butler** changed priority from "major" to "critical"

**Comment by rozyczko** [comment]
Trac update at `2016/03/16 17:48:23`: 
* **piotr** changed owner from "" to "piotr"
* **piotr** changed status from "new" to "assigned"

**Comment by rozyczko** [comment]
Trac update at `2016/03/17 15:04:17`: **piotr** commented:

Windows - it looks like stopping the fit from the "regular" fit window doesn't work properly either.
There's an option to stop the thread by pressing the 'stop' button, but it doesn't actually terminate the thread. This can be seen in the process explorer or just by waiting and seeing the fit charts.
We should probably fix that.

**Comment by rozyczko** [comment]
Trac update at `2016/03/17 17:52:45`: **piotr** commented:

Added the functioning button. The underlying issue covered in http://trac.sasview.org/ticket/531

**Comment by rozyczko** [comment]
Trac update at `2016/03/17 17:53:00`: 
* **piotr** changed resolution from "" to "fixed"
* **piotr** changed status from "assigned" to "closed"
