### ISSUE TITLE
Do we use libxml2? (Trac #412)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#546]
During the Sphinx doc build for Windows (using Anaconda) the following 
error is thrown:

!RuntimeError: Could not find libxml2 on the system

Anaconda uses the lxml Pythonic binding to libxml2 (& libxslt). But 
this error is being thrown by \sasview\setup_mac.py!

The doc build continues nonetheless.

This raises two questions:
1) Is libxml2 still needed (on any platform)?
2) If libxml2 is only needed on Mac, why is a doc build on Windows 
flagging it as an error?

Migrated from http://trac.sasview.org/ticket/412
```json
{
    "status": "closed",
    "changetime": "2016-10-07T19:56:00",
    "_ts": "2016-10-07 19:56:00.037826+00:00",
    "description": "During the Sphinx doc build for Windows (using Anaconda) the following \nerror is thrown:\n\n!RuntimeError: Could not find libxml2 on the system\n\nAnaconda uses the lxml Pythonic binding to libxml2 (& libxslt). But \nthis error is being thrown by \\sasview\\setup_mac.py!\n\nThe doc build continues nonetheless.\n\nThis raises two questions:\n1) Is libxml2 still needed (on any platform)?\n2) If libxml2 is only needed on Mac, why is a doc build on Windows \nflagging it as an error?\n",
    "reporter": "smk78",
    "cc": "",
    "resolution": "wontfix",
    "workpackage": "SasView Documentation",
    "time": "2015-04-29T17:10:02",
    "component": "SasView",
    "summary": "Do we use libxml2?",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView Next Release +1",
    "owner": "",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2016/03/06 18:45:12`: **butler** changed description from:

> During the Sphinx doc build for Windows (using Anaconda) the following 
> error is thrown:
> 
> RuntimeError: Could not find libxml2 on the system
> 
> Anaconda uses the lxml Pythonic binding to libxml2 (& libxslt). But 
> this error is being thrown by \sasview\setup_mac.py!
> 
> The doc build continues nonetheless.
> 
> This raises two questions:
> 1) Is libxml2 still needed (on any platform)?
> 2) If libxml2 is only needed on Mac, why is a doc build on Windows 
> flagging it as an error?
> 

to:

> During the Sphinx doc build for Windows (using Anaconda) the following 
> error is thrown:
> 
> !RuntimeError: Could not find libxml2 on the system
> 
> Anaconda uses the lxml Pythonic binding to libxml2 (& libxslt). But 
> this error is being thrown by \sasview\setup_mac.py!
> 
> The doc build continues nonetheless.
> 
> This raises two questions:
> 1) Is libxml2 still needed (on any platform)?
> 2) If libxml2 is only needed on Mac, why is a doc build on Windows 
> flagging it as an error?
>

**Comment by ajj** [comment]
Trac update at `2016/10/07 19:56:00`: 
* **ajj** commented:

No longer valid


* **ajj** changed resolution from "" to "wontfix"
* **ajj** changed status from "new" to "closed"
