### ISSUE TITLE
entropy calculation requires scikit learn package (Trac #413)

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#547]
bumps entropy calculation requires scikit learn package that is not being bundled with windows exe, and is not listed as a dependency.

Migrated from http://trac.sasview.org/ticket/413
```json
{
    "status": "new",
    "changetime": "2015-06-21T22:23:50",
    "_ts": "2015-06-21 22:23:50.939932+00:00",
    "description": "bumps entropy calculation requires scikit learn package that is not being bundled with windows exe, and is not listed as a dependency.\n\n",
    "reporter": "pkienzle",
    "cc": "",
    "resolution": "",
    "workpackage": "SasView Fitting Redesign",
    "time": "2015-05-04T16:56:55",
    "component": "SasView",
    "summary": "entropy calculation requires scikit learn package",
    "priority": "minor",
    "keywords": "",
    "milestone": "SasView Next Release +1",
    "owner": "",
    "type": "defect"
}
```

**Comment by smk78** [comment]
Trac update at `2015/05/05 09:37:59`: **smk78** commented:

scikit-learn-0.15.2-np19py27_0.tar.bz2 is distributed with Anaconda, at least, this file appears in /pkgs!

**Comment by pkienzle** [comment]
Trac update at `2015/05/05 12:08:30`: **pkienzle** commented:

Short term I removed the entropy option from the GUI.  We will be working on this feature in Bumps over the summer, and will have a better idea of how to implement it.

Once the bumps version number has been incremented, and the SasView dependencies updated, this ticket can be moved to SasView 4.0.

**Comment by pkienzle** [comment]
Trac update at `2015/05/07 16:11:13`: **pkienzle** changed milestone from "SasView 3.1" to "SasView Next Release +1"

**Comment by butlerpd** [comment]
Trac update at `2015/06/21 22:23:50`: **butler** changed workpackage from "SasView Bug Fixing" to "SasView Fitting Redesign"

**Comment by lucas-wilkins** [comment]
> Short term I removed the entropy option from the GUI. We will be working on this feature in Bumps over the summer, and will have a better idea of how to implement it.

> Once the bumps version number has been incremented, and the SasView dependencies updated, this ticket can be moved to SasView 4.0.

@pkienzle Can we close this now?

**Comment by pkienzle** [comment]
sklearn is an optional dependency. Sasview is not reporting entropy after a bumps fit so it doesn't need it. Even if it were to report entropy, it would probably use entropy from covariance which does not need sklearn.

**Comment by butlerpd** [comment]
I note this is a June 2015 ticket. It sounds like your answer @pkienzle is that we can safely close this. If there is ever a need we can evaluate then and submit an appropriate ticket at that time?
