### ISSUE TITLE
Remove "standalone" option in gui_manager (Trac #414)

### ISSUE THREAD

**Issue by mdoucet** [SasView/sasview#548]
Back in the day when we could build a standalone application with every perspective, there was a "standalone" data member in each plugin perspective. This was used by the gui_manager to pick how to handle a perspective. Since then, another mechanism has been put in place to select the default perspective (which was originally also done through the "standalone" data member). 

Since "standalone" is not longer used, we should get rid of the code that deals with it in gui_manager.

Migrated from http://trac.sasview.org/ticket/414
```json
{
    "status": "assigned",
    "changetime": "2017-10-23T15:06:09",
    "_ts": "2017-10-23 15:06:09.678520+00:00",
    "description": "Back in the day when we could build a standalone application with every perspective, there was a \"standalone\" data member in each plugin perspective. This was used by the gui_manager to pick how to handle a perspective. Since then, another mechanism has been put in place to select the default perspective (which was originally also done through the \"standalone\" data member). \n\nSince \"standalone\" is not longer used, we should get rid of the code that deals with it in gui_manager.",
    "reporter": "mathieu",
    "cc": "",
    "resolution": "",
    "workpackage": "SasView Framework Enhancements",
    "time": "2015-05-05T14:27:13",
    "component": "SasView",
    "summary": "Remove \"standalone\" option in gui_manager",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 5.0.0",
    "owner": "mathieu",
    "type": "enhancement"
}
```

**Comment by mdoucet** [comment]
Trac update at `2015/07/02 16:29:33`: 
* **mathieu** changed owner from "" to "mathieu"
* **mathieu** changed status from "new" to "assigned"

**Comment by butlerpd** [comment]
Trac update at `2017/10/23 15:06:09`: **butler** changed milestone from "SasView Next Release +1" to "SasView 5.0.0"

**Comment by lucas-wilkins** [comment]
Unclear what this means, as no mention of it in gui manager any more. Closing.
