### ISSUE TITLE
problem with pearl necklace model (Trac #420)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#554]
a report by Dan Green of the University of Delaware that if the number of pearls is allowed to float the fit often (always?) crashes with nans.  However if the number of pearls is fixed it works.  He suspects that the non-integer values for number of pearls may be being passed which is quite likely.  Not sure if that would cause the math to go crazy but it could.  Need to look at this issue and figure out how to restrict the number to integers only.

Migrated from http://trac.sasview.org/ticket/420
```json
{
    "status": "closed",
    "changetime": "2015-11-22T01:42:02",
    "_ts": "2015-11-22 01:42:02.511347+00:00",
    "description": "a report by Dan Green of the University of Delaware that if the number of pearls is allowed to float the fit often (always?) crashes with nans.  However if the number of pearls is fixed it works.  He suspects that the non-integer values for number of pearls may be being passed which is quite likely.  Not sure if that would cause the math to go crazy but it could.  Need to look at this issue and figure out how to restrict the number to integers only.",
    "reporter": "butler",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2015-05-20T18:46:28",
    "component": "SasView",
    "summary": "problem with pearl necklace model",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 3.1.0",
    "owner": "",
    "type": "defect"
}
```

**Comment by pkienzle** [comment]
Trac update at `2015/06/04 13:17:17`: 
* **pkienzle** changed resolution from "" to "fixed"
* **pkienzle** changed status from "new" to "closed"

**Comment by butlerpd** [comment]
Trac update at `2015/11/22 01:42:02`: **butler** changed milestone from "SasView Next Release +1" to "SasView 3.1.0"
