### ISSUE TITLE
Docs not showing up on Mac (Trac #421)

### ISSUE THREAD

**Issue by mdoucet** [SasView/sasview#555]
If you use the official build, start SasView, then click the Help button, you'll see a window popping up with nothing in it. 

The doc files are there and you can load them in a browser,  so they are not the problem. The problem seems to be related to the wx.WebView object that is not set up properly.

Migrated from http://trac.sasview.org/ticket/421
```json
{
    "status": "closed",
    "changetime": "2015-06-05T14:57:48",
    "_ts": "2015-06-05 14:57:48.179082+00:00",
    "description": "If you use the official build, start SasView, then click the Help button, you'll see a window popping up with nothing in it. \n\nThe doc files are there and you can load them in a browser,  so they are not the problem. The problem seems to be related to the wx.WebView object that is not set up properly.",
    "reporter": "mathieu",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2015-06-04T17:41:33",
    "component": "SasView",
    "summary": "Docs not showing up on Mac",
    "priority": "blocker",
    "keywords": "",
    "milestone": "SasView 3.1.0",
    "owner": "butler",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2015/06/04 20:28:39`: 
* **butler** changed owner from "" to "butler"
* **butler** changed status from "new" to "accepted"

**Comment by butlerpd** [comment]
Trac update at `2015/06/05 03:06:01`: **butler** commented:

After downloading the build version from jenkins on June 4 onto my mac this works fine.  The previous downloaded version seems to work as well.  Need to figure out why Mathieu has the problem.

**Comment by mdoucet** [comment]
Trac update at `2015/06/05 14:57:48`: 
* **mathieu** commented:

Fixed. The problem was with spaces in the file path of the documentation html file. If the user unzipped the downloaded application file multiple times, OSX would append a number to the app name (example: sasview 2.app). The url needed to be properly encoded before being passed to the browser.


* **mathieu** changed resolution from "" to "fixed"
* **mathieu** changed status from "accepted" to "closed"
