### ISSUE TITLE
Enhance help (non model) documentation (Trac #422)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#556]
The Sphinx help docs for Release 3.1 represent a porting of the pre-
existing HTML help docs to ReSTructured text.

Some restructuring has been conducted. Some (obvious!) equation errors 
have been corrected. Some 'missing' content has been added.

The next steps are:

 - checking that the documentation actually reflects the current
   functionality of the program!

 - updating existing screenshots to match the current functionality
   of the program

 - adding additional screenshots

 NOTE: Model documentation review is addressed separately in Ticket #248.

Migrated from http://trac.sasview.org/ticket/422
```json
{
    "status": "closed",
    "changetime": "2016-10-11T16:29:09",
    "_ts": "2016-10-11 16:29:09.264816+00:00",
    "description": "The Sphinx help docs for Release 3.1 represent a porting of the pre-\nexisting HTML help docs to ReSTructured text.\n\nSome restructuring has been conducted. Some (obvious!) equation errors \nhave been corrected. Some 'missing' content has been added.\n\nThe next steps are:\n\n - checking that the documentation actually reflects the current\n   functionality of the program!\n\n - updating existing screenshots to match the current functionality\n   of the program\n\n - adding additional screenshots\n\n NOTE: Model documentation review is addressed separately in Ticket #19.\n",
    "reporter": "smk78",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Documentation",
    "time": "2015-06-05T16:17:39",
    "component": "SasView",
    "summary": "Enhance help (non model) documentation",
    "priority": "critical",
    "keywords": "",
    "milestone": "SasView 4.1.0",
    "owner": "smk78",
    "type": "task"
}
```

**Comment by smk78** [comment]
Trac update at `2015/06/26 12:24:35`: **smk78** commented:

Also consider, as suggested by Richard, doing away with the 'top level' documentation menu. This would mean moving the links to the Model Functions and the Developer Documentation from Sphinx index.rst to the GUI Help dropdown and reorganising lower toctrees.

**Comment by smk78** [comment]
Trac update at `2015/06/29 09:53:41`: **smk78** commented:

Last suggestion dealt with under Ticket #570

**Comment by butlerpd** [comment]
Trac update at `2015/08/14 19:48:40`: **butler** changed milestone from "SasView Next Release +1" to "SasView 4.0.0"

**Comment by smk78** [comment]
Trac update at `2015/08/17 12:15:14`: **smk78** commented:

Need to add something about using Save Analysis and Save Project (suggestion ported from Ticket #249).

**Comment by smk78** [comment]
Trac update at `2015/08/17 12:18:19`: **smk78** commented:

Also see Ticket #261.

**Comment by butlerpd** [comment]
Trac update at `2016/03/08 03:06:33`: 
* **butler** changed description from:

> The Sphinx help docs for Release 3.1 represent a porting of the pre-
> existing HTML help docs to ReSTructured text.
> 
> Some restructuring has been conducted. Some (obvious!) equation errors 
> have been corrected. Some 'missing' content has been added.
> 
> The next steps are:
> 
>  - checking that the documentation actually reflects the current
>    functionality of the program!
> 
>  - updating existing screenshots to match the current functionality
>    of the program
> 
>  - adding additional screenshots
> 
>  - carefully and critically checking the model documentation which is
>    known to contain many errors! The model documentation currently 
>    resides in model_functions.rst but will be moved to individual 
>    models as the 'sansmodels' upgrade proceeds. Those converting models 
>    should not assume that the model documentation they are copying is 
>    necessarily accurate. Also see Ticket #19.
> 

to:

> The Sphinx help docs for Release 3.1 represent a porting of the pre-
> existing HTML help docs to ReSTructured text.
> 
> Some restructuring has been conducted. Some (obvious!) equation errors 
> have been corrected. Some 'missing' content has been added.
> 
> The next steps are:
> 
>  - checking that the documentation actually reflects the current
>    functionality of the program!
> 
>  - updating existing screenshots to match the current functionality
>    of the program
> 
>  - adding additional screenshots
> 
>  NOTE: Model documentation review is addressed separately in Ticket #19.
> 


* **butler** changed summary from "Enhance help documentation" to "Enhance help (non model) documentation"

**Comment by butlerpd** [comment]
Trac update at `2016/08/16 21:25:31`: 
* **butler** commented:

While some work has been done, we still need an organized start to finish review which is clearly not going to be able to be done in time for release 4.0.  Moving this to +1 but keeping the high priority on it.


* **butler** changed milestone from "SasView 4.0.0" to "SasView Next Release +1"
* **butler** changed type from "enhancement" to "task"

**Comment by butlerpd** [comment]
Trac update at `2016/09/05 02:50:57`: **butler** changed milestone from "SasView Next Release +1" to "SasView 4.1.0"

**Comment by smk78** [comment]
Trac update at `2016/10/11 16:28:30`: **smk78** commented:

After discussions between PaulB & Steve we are closing this ticket as its original intention has now been served. A LOT of good work on the documentation has taken place since Code Camp III and it is now in a far better place than it was, but there will ALWAYS be room for improvement. If there are specific documentation issues/enhancements they should now be noted in specific tickets.

**Comment by smk78** [comment]
Trac update at `2016/10/11 16:29:09`: 
* **smk78** changed resolution from "" to "fixed"
* **smk78** changed status from "new" to "closed"
