### ISSUE TITLE
Loading a project makes a second Fitting top menu appear (Trac #429)

### ISSUE THREAD

**Issue by mdoucet** [SasView/sasview#563]
At some point recently we fixed the issue with having multiple Fitting top menus.
It appears that the problem still appears when loading a saved project.

Migrated from http://trac.sasview.org/ticket/429
```json
{
    "status": "closed",
    "changetime": "2015-11-22T01:16:12",
    "_ts": "2015-11-22 01:16:12.861089+00:00",
    "description": "At some point recently we fixed the issue with having multiple Fitting top menus.\nIt appears that the problem still appears when loading a saved project.",
    "reporter": "mathieu",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2015-06-18T16:18:24",
    "component": "SasView",
    "summary": "Loading a project makes a second Fitting top menu appear",
    "priority": "critical",
    "keywords": "",
    "milestone": "SasView 3.1.0",
    "owner": "",
    "type": "defect"
}
```

**Comment by mdoucet** [comment]
Trac update at `2015/06/18 16:19:31`: **mathieu** changed priority from "major" to "critical"

**Comment by mdoucet** [comment]
Trac update at `2015/06/18 21:31:51`: 
* **mathieu** commented:

This should now be fixed.


* **mathieu** changed resolution from "" to "fixed"
* **mathieu** changed status from "new" to "closed"

**Comment by butlerpd** [comment]
Trac update at `2015/11/22 01:16:12`: **butler** changed milestone from "SasView Next Release +1" to "SasView 3.1.0"
