### ISSUE TITLE
Check for updates does not work on GitHub yet (Trac #433)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#567]
The "check for updates" functionality was pointing at sourceforge.  It now points to the GitHub release repo but the script that does the work needs to be fixed.

Also, for those with any prior release how do we set sourceforge to tell them that there is a new version?

Migrated from http://trac.sasview.org/ticket/433
```json
{
    "status": "closed",
    "changetime": "2015-07-06T14:36:16",
    "_ts": "2015-07-06 14:36:16.163190+00:00",
    "description": "The \"check for updates\" functionality was pointing at sourceforge.  It now points to the GitHub release repo but the script that does the work needs to be fixed.\n\nAlso, for those with any prior release how do we set sourceforge to tell them that there is a new version?",
    "reporter": "butler",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2015-06-23T02:50:32",
    "component": "SasView",
    "summary": "Check for updates does not work on GitHub yet",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 3.1.0",
    "owner": "butler",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2015/06/23 06:05:41`: 
* **butler** changed owner from "" to "butler"
* **butler** changed status from "new" to "assigned"

**Comment by butlerpd** [comment]
Trac update at `2015/06/23 06:09:41`: **butler** commented:

check for updates now works as before on sourceforge.  However it relies on setting the verion in master/sasview.latestversion simultaneously with the official release.  On GitHub we can use


```text
  https://github.com/SasView/sasview/releases/latest
```

which will re-evaluate to:

```text
  https://github.com/SasView/sasview/releases/tag/vx.x.x
```

where x.x.x is the latest taged release.  We should be using this instead. But this may be for the next release?

**Comment by butlerpd** [comment]
Trac update at `2015/06/23 06:26:13`: **butler** commented:

The code we want to use is:


```text
   import urllib2
   req = urllib2.Request('https://github.com/SasView/sasview/releases/latest')
   res = urllib2.urlopen(req)
   print res.geturl()
```

which currently returns (prints)

```text
   https://github.com/SasView/sasview/releases/tag/v3.0.0
```

then just return everthing after tag/v.  Is this where re package would be useful?

**Comment by smk78** [comment]
Trac update at `2015/07/06 12:28:02`: **smk78** commented:

Known Issues section of 3.1.0 Release Notes updated.

Website faq.html also updated with instructions for Win 7 users and committed to repo.  **NB: But this is not currently being pushed to the server at UTK for some reason **.

**Comment by smk78** [comment]
Trac update at `2015/07/06 14:36:16`: 
* **smk78** commented:

Changes now pushed to repo.

Think we can close this ticket now!


* **smk78** changed resolution from "" to "fixed"
* **smk78** changed status from "assigned" to "closed"
