### ISSUE TITLE
Hayter Penfold MSA code needs checking (Trac #439)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#573]
Richard Heenan thinks that the HMSA structure factor may be giving different answer to FISH version.  They have the same origin so should be the same.  This still nees furhter checking and if a real problem will then need to be addressed

Migrated from http://trac.sasview.org/ticket/439
```json
{
    "status": "closed",
    "changetime": "2016-03-19T12:08:28",
    "_ts": "2016-03-19 12:08:28.639906+00:00",
    "description": "Richard Heenan thinks that the HMSA structure factor may be giving different answer to FISH version.  They have the same origin so should be the same.  This still nees furhter checking and if a real problem will then need to be addressed",
    "reporter": "butler",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView QA and testing",
    "time": "2015-06-30T15:34:30",
    "component": "SasView",
    "summary": "Hayter Penfold MSA code needs checking",
    "priority": "blocker",
    "keywords": "",
    "milestone": "SasView 4.0.0",
    "owner": "richardh",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2015/08/14 19:57:34`: **butler** changed milestone from "SasView Next Release +1" to "SasView 4.0.0"

**Comment by butlerpd** [comment]
Trac update at `2015/12/19 18:56:31`: **butler** changed workpackage from "SasView Bug Fixing" to "SasView QA and testing"

**Comment by ajj** [comment]
Trac update at `2016/02/28 11:21:39`: **ajj** changed priority from "major" to "blocker"

**Comment by butlerpd** [comment]
Trac update at `2016/03/06 20:58:51`: **butler** changed status from "new" to "assigned"

**Comment by RichardHeenan** [comment]
Trac update at `2016/03/10 18:47:53`: **richardh** commented:

Replying to [ticket:439 butler]:
> Richard Heenan thinks the HP S(Q) is likely OK (it is not necessarily identical to what is in FISH)
New version, with Taylor expansion at small Q, needs sorting out at code camp, has not been uploaded to GIT as I want to replace present one (which has a bug) with a version having a more sensible name.

**Comment by butlerpd** [comment]
Trac update at `2016/03/19 12:08:28`: 
* **butler** commented:

This is as finished as it will be.  Main conclusion is it will have to ALWAYS use double precision.  May add a FISH version later which may be more stable. However this code looks correct. Closing this ticket.


* **butler** changed resolution from "" to "fixed"
* **butler** changed status from "assigned" to "closed"
