### ISSUE TITLE
Re-position of Add Text in a plot panel is not possible (Trac #445)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#579]
Right clicking in a plot panel brings up a context menu where one choice is to add text.  This brings up a dialog providing some customization of font etc.  HOWEVER, the text is added "somewhere" on the plot and is neither positionable at the start nor movable.  This seems to always have been the case (in 3.0 at least)   

This essentially makes this feature useless..

Migrated from http://trac.sasview.org/ticket/445
```json
{
    "status": "closed",
    "changetime": "2016-10-07T00:13:50",
    "_ts": "2016-10-07 00:13:50.252623+00:00",
    "description": "Right clicking in a plot panel brings up a context menu where one choice is to add text.  This brings up a dialog providing some customization of font etc.  HOWEVER, the text is added \"somewhere\" on the plot and is neither positionable at the start nor movable.  This seems to always have been the case (in 3.0 at least)   \n\nThis essentially makes this feature useless..",
    "reporter": "butler",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "Plotting/Graphing Enhancements",
    "time": "2015-07-04T15:36:49",
    "component": "SasView",
    "summary": "Re-position of Add Text in a plot panel is not possible",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.0.0",
    "owner": "lewis",
    "type": "defect"
}
```

**Comment by smk78** [comment]
Trac update at `2015/07/06 15:06:16`: **smk78** commented:

ESS Win 7 3.1.0 Build http://trac.sasview.org/ticket/121

In actuality, at least in Windows, the text is positioned so the first character is at the tip of the pointer when the right mouse button is clicked. So there is some control, though it would be nice to be able to re-position the text string after adding it to the plot.

**Comment by butlerpd** [comment]
Trac update at `2015/11/22 02:10:49`: 
* **butler** changed summary from "Position of Add Text in a plot panel is not controllable" to "Re-position of Add Text in a plot panel is not possible"
* **butler** changed workpackage from "SasView Bug Fixing" to "Plotting/Graphing Enhancements"

**Comment by butlerpd** [comment]
Trac update at `2016/10/07 00:13:50`: **butler** changed milestone from "SasView Next Release +1" to "SasView 4.0.0"
