### ISSUE TITLE
Saving plot as PGF (not PDF!) format throws error (Trac #446)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#580]
Win 7 Version 3.1.0 Builds 121 & 124 onwards

Attempting to save a plot as PGF (Progressive Graphics File) format results in a file header being created (see attachment) but then the operation fails nicely with the popup message:

Matplotlib backend_wx error. Error starting process xelatex

NB: This needs testing by someone who has Latex installed.

Migrated from http://trac.sasview.org/ticket/446
```json
{
    "status": "closed",
    "changetime": "2018-03-04T17:21:37",
    "_ts": "2018-03-04 17:21:37.950145+00:00",
    "description": "Win 7 Version 3.1.0 Builds 121 & 124 onwards\n\nAttempting to save a plot as PGF (Progressive Graphics File) format results in a file header being created (see attachment) but then the operation fails nicely with the popup message:\n\nMatplotlib backend_wx error. Error starting process xelatex\n\nNB: This needs testing by someone who has Latex installed.",
    "reporter": "smk78",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2015-07-07T10:38:08",
    "component": "SasView",
    "summary": "Saving plot as PGF (not PDF!) format throws error",
    "priority": "critical",
    "keywords": "",
    "milestone": "SasView 4.2.0",
    "owner": "",
    "type": "defect"
}
```

**Comment by smk78** [comment]
Trac update at `2015/07/07 10:38:48`: 
* **smk78** changed attachment from "" to "image.pgf"
* **smk78** commented:

Example PGF file header that is created

**Comment by butlerpd** [comment]
Trac update at `2016/08/16 14:41:25`: **butler** commented:

So does this mean that your system must have one of those compilers installed?  Presumably the only reason to create such a latex raw graphic would be because you have latex and want to embed this in your tex document? 

If so, perhaps a fix would be to capture the error and pop up a window indicating that "this produces a !LaTex command sequence for generating the graphics and requires that one of x, y, z packages be installed none of which are detected on your system - please make sure an appropriate !LaTex compiler is installed and try again"

**Comment by pkienzle** [comment]
Trac update at `2016/08/16 14:55:21`: **pkienzle** commented:

To remove pgf option you can do the following:

    from matplotlib import backend_bases
    backend_bases._default_filetypes.pop('pgf', None)

This could be put into sasview.py

**Comment by smk78** [comment]
Trac update at `2016/08/16 15:31:01`: **smk78** commented:

Have updated /sasview/src/sas/sasgui/guiframe/media/graph_help.rst to say:


```text
The PGF image type option requires a LaTeX compiler: xelatex (default), lualatex, or pdflatex. These are not shipped with SasView.
```

**Comment by butlerpd** [comment]
Trac update at `2016/09/05 02:32:50`: 
* **butler** commented:

This was fixed by Lewis but entering "closes" does not actually close the ticket. Doing so now


* **butler** changed resolution from "" to "fixed"
* **butler** changed status from "new" to "closed"

**Comment by butlerpd** [comment]
Trac update at `2018/03/04 17:21:37`: **butler** changed milestone from "SasView Next Release +1" to "SasView 4.2.0"
