### ISSUE TITLE
Saving plot as Raw RGBA format generates an image-less file (Trac #447)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#581]
Saving a plot as Raw RGBA format generates a file but the file does not appear to contain any image! See attached.

Migrated from http://trac.sasview.org/ticket/447
```json
{
    "status": "closed",
    "changetime": "2016-10-07T00:11:17",
    "_ts": "2016-10-07 00:11:17.602351+00:00",
    "description": "Saving a plot as Raw RGBA format generates a file but the file does not appear to contain any image! See attached.",
    "reporter": "smk78",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2015-07-07T10:48:48",
    "component": "SasView",
    "summary": "Saving plot as Raw RGBA format generates an image-less file",
    "priority": "critical",
    "keywords": "",
    "milestone": "SasView 4.0.0",
    "owner": "smk78",
    "type": "defect"
}
```

**Comment by smk78** [comment]
Trac update at `2015/07/07 10:49:18`: 
* **smk78** changed attachment from "" to "image.raw"
* **smk78** commented:

Raw RGBA format file

**Comment by pkienzle** [comment]
Trac update at `2016/08/16 15:04:46`: **pkienzle** commented:

could remove rgb and rgba formats using:

```text
    from matplotlib import backend_bases
    backend_bases._default_filetypes.pop('raw', None)
    backend_bases._default_filetypes.pop('rgba', None)
```
probably in sasview.py

**Comment by smk78** [comment]
Trac update at `2016/08/16 15:29:58`: **smk78** commented:

Have updated /sasview/src/sas/sasgui/guiframe/media/graph_help.rst to say:


```text
RAW/RGBA (bitmap, stored as 935x635 pixels of depth 8)
```

**Comment by butlerpd** [comment]
Trac update at `2016/10/07 00:11:17`: **butler** changed milestone from "SasView Next Release +1" to "SasView 4.0.0"
