### ISSUE TITLE
Add Print function to DREAM Fit Results Panel (Trac #450)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#584]
It would be nice to be able to print the plots in the DREAM Fit Results Panel (as you can with normal graphs) without having to save them as graphics files first.

Migrated from http://trac.sasview.org/ticket/450
```json
{
    "status": "closed",
    "changetime": "2015-11-22T01:42:58",
    "_ts": "2015-11-22 01:42:58.710175+00:00",
    "description": "It would be nice to be able to print the plots in the DREAM Fit Results Panel (as you can with normal graphs) without having to save them as graphics files first.",
    "reporter": "smk78",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView GUI Enhancements",
    "time": "2015-07-07T16:58:18",
    "component": "SasView",
    "summary": "Add Print function to DREAM Fit Results Panel",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 3.1.1",
    "owner": "",
    "type": "enhancement"
}
```

**Comment by pkienzle** [comment]
Trac update at `2015/07/13 15:57:25`: 
* **pkienzle** changed resolution from "" to "fixed"
* **pkienzle** changed status from "new" to "closed"

**Comment by butlerpd** [comment]
Trac update at `2015/11/22 01:42:58`: **butler** changed milestone from "SasView Next Release +1" to "SasView 3.1.1"
