### ISSUE TITLE
SasView fails to start if not able to connect to github (Trac #457)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#591]
Since release 3.0 SasView now checks for a new version automatically on every startup.  Unfortunately in the change from using sasview.latestversion text file in trunk to using a latestversion json file at www.sasview.org the checking for a connection got messed up.  SasView is supposed to check an if it has no connection should just say "cannot connect ... please try again later".

This needs fixin asap 

Migrated from http://trac.sasview.org/ticket/457
```json
{
    "status": "closed",
    "changetime": "2015-07-26T18:59:54",
    "_ts": "2015-07-26 18:59:54.958600+00:00",
    "description": "Since release 3.0 SasView now checks for a new version automatically on every startup.  Unfortunately in the change from using sasview.latestversion text file in trunk to using a latestversion json file at www.sasview.org the checking for a connection got messed up.  SasView is supposed to check an if it has no connection should just say \"cannot connect ... please try again later\".\n\nThis needs fixin asap ",
    "reporter": "butler",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2015-07-19T01:39:34",
    "component": "SasView",
    "summary": "SasView fails to start if not able to connect to github",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 3.1.1",
    "owner": "mathieu",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2015/07/21 19:17:30`: 
* **butler** commented:

Mathieu has fixed this by moving the reading of the json file into the try block.  Testing indicates it now works fine on mac and pc if no internet is available and on pc even if wireless access point is connected but has no internet connection.  Need to get confirmation from RAL that it works (as in loads and runs sasview even though it cannot connect to the update server) behind their firewall.  Then we can close the ticket.



* **butler** changed owner from "" to "mathieu"
* **butler** changed status from "new" to "assigned"

**Comment by smk78** [comment]
Trac update at `2015/07/22 10:44:15`: **smk78** commented:

Tested ESS Win 7 3.1.0 Build http://trac.sasview.org/ticket/140 on two machines behind site proxy server:

On PC that had NOT been modified as per FAQ:
SasView installs and starts after brief delay. If you then force a Check for Updates nothing appears to happen for several seconds, then the window goes 'Not Responding', then it becomes responsive again and 'Could not connect to application server' appears in the status bar.

On PC that HAD been modified as per FAQ:
SasView installs, starts and Checks for Updates, responding with 'You have the latest version'.

Thus Mathieu's fix would seem to work fine and can be pushed to a point release.

**Comment by ajj** [comment]
Trac update at `2015/07/26 18:59:54`: 
* **ajj** commented:

Ricardo has now added changes that allow SasView to successfully connect from behind a proxy without user modifications, and if that fails still allows SasView to start e.g. if there is no internet connection.



* **ajj** changed resolution from "" to "fixed"
* **ajj** changed status from "assigned" to "closed"
