### ISSUE TITLE
Generic Scattering Calculator Enhancements: make a theory curve (Trac #462)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#596]
Lilo Pozo of the University of Washington suggests that she very much likes the concept of the Generic Scattering Calculator and thing it could be an extremel powerful too for SAS analyis if a few features were added.  These are being broken into 3 tickets.

Currently the calculator is simply a tool and does just that: calculate.  It would be MUCH more powerful if this could be treated as a theory curve and plotted with the data for comparison... and even plot the residuals.

This should be doalbe relatively straightforwardly using the current fitting/plotting infrastructure.

Migrated from http://trac.sasview.org/ticket/462
```json
{
    "status": "new",
    "changetime": "2017-10-23T13:21:06",
    "_ts": "2017-10-23 13:21:06.996746+00:00",
    "description": "Lilo Pozo of the University of Washington suggests that she very much likes the concept of the Generic Scattering Calculator and thing it could be an extremel powerful too for SAS analyis if a few features were added.  These are being broken into 3 tickets.\n\nCurrently the calculator is simply a tool and does just that: calculate.  It would be MUCH more powerful if this could be treated as a theory curve and plotted with the data for comparison... and even plot the residuals.\n\nThis should be doalbe relatively straightforwardly using the current fitting/plotting infrastructure.",
    "reporter": "butler",
    "cc": "",
    "resolution": "",
    "workpackage": "SasView Fitting Redesign",
    "time": "2015-10-10T17:37:29",
    "component": "SasView",
    "summary": "Generic Scattering Calculator Enhancements: make a theory curve",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 5.1.0",
    "owner": "",
    "type": "enhancement"
}
```

**Comment by butlerpd** [comment]
Trac update at `2016/06/19 16:36:33`: 
* **butler** commented:

This would be really nice but given the current resources and amount of work left to get 4.0 final release out this needs to move to +1


* **butler** changed milestone from "SasView 4.0.0" to "SasView Next Release +1"

**Comment by butlerpd** [comment]
Trac update at `2017/10/23 13:21:06`: **butler** changed milestone from "SasView Next Release +1" to "SasView 5.1.0"

**Comment by rjbourne** [comment]
@butlerpd: Within the current code whenever the generic scattering calculator finishes a calculation the data is saved into the 'data' tab of the data explorer.
![image](https://user-images.githubusercontent.com/57537928/130810255-23117c6e-80b1-4e20-a0e9-be7a8513d91d.png)
Along with the small fix in branch https://github.com/SasView/sasview/tree/ticket-596-plot-scattering-calc-as-theory-curve this allows the output to be treated in the same way as any data from a file - e.g. plotting and fitting with residuals, at least as far as I am aware. Are there any further alterations that need to be made for this ticket?

**Comment by butlerpd** [comment]
thanks @rjbourne, that is quite nice!! Ideally I think it would be nice to have the data loaded within the generic scattering calculator but that probably requires refactoring the calculator from a tool to a perspective.  Even if it is not strictly required, the calculator should probably be moved to a perspective before implementing such a thing (otherwise what is the difference between a tool and a perspective :-) And of course ideally ideally we could then put some real space constraints and do actual fitting of the real space model (a person can dream can't he 😄 )

So to answer the question, I agree this does everything we can ask from this ticket which can be closed once the changes are merged to main.  I'll make a new ticket about moving this from a tool to a perspective.
