### ISSUE TITLE
Extend batch functionality to slicer (Trac #467)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#601]
The original intent of batch was to allow applying any !SasView action on a data set to a series of such sets, including Pr, tools, invariant, fitting, and slicer.  However batch fitting was deemed the highest priority and the rest was descoped in order to meet the release deadline.  Probably the next highest priority would be the slicer as evidenced by several request.

Migrated from http://trac.sasview.org/ticket/467
```json
{
    "status": "closed",
    "changetime": "2017-06-13T13:22:18",
    "_ts": "2017-06-13 13:22:18.629055+00:00",
    "description": "The original intent of batch was to allow applying any !SasView action on a data set to a series of such sets, including Pr, tools, invariant, fitting, and slicer.  However batch fitting was deemed the highest priority and the rest was descoped in order to meet the release deadline.  Probably the next highest priority would be the slicer as evidenced by several request.",
    "reporter": "butler",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView GUI Enhancements",
    "time": "2015-10-26T05:52:03",
    "component": "SasView",
    "summary": "Extend batch functionality to slicer",
    "priority": "critical",
    "keywords": "",
    "milestone": "SasView 4.2.0",
    "owner": "krzywon",
    "type": "enhancement"
}
```

**Comment by butlerpd** [comment]
Trac update at `2016/03/20 22:46:22`: **butler** changed milestone from "SasView 4.0.0" to "SasView Next Release +1"

**Comment by butlerpd** [comment]
Trac update at `2016/03/20 22:46:46`: **butler** changed description from "The original intent of batch was to allow applying any SasView action on a data set to a series of such sets, including Pr, tools, invariant, fitting, and slicer.  However batch fitting was deemed the highest priority and the rest was descoped in order to meet the release deadline.  Probably the next highest priority would be the slicer as evidenced by several request." to "The original intent of batch was to allow applying any !SasView action on a data set to a series of such sets, including Pr, tools, invariant, fitting, and slicer.  However batch fitting was deemed the highest priority and the rest was descoped in order to meet the release deadline.  Probably the next highest priority would be the slicer as evidenced by several request."

**Comment by butlerpd** [comment]
Trac update at `2016/09/05 03:25:07`: **butler** changed milestone from "SasView Next Release +1" to "SasView 4.1.0"

**Comment by smk78** [comment]
Trac update at `2016/10/11 16:52:44`: **smk78** changed priority from "major" to "critical"

**Comment by butlerpd** [comment]
Trac update at `2016/11/08 13:48:39`: 
* **butler** commented:

sadly need to move to 4.2 realistically speaking


* **butler** changed milestone from "SasView 4.1.0" to "SasView 4.2.0"
