### ISSUE TITLE
Loading files from the top menu doesn't always work on Mac (Trac #469)

### ISSUE THREAD

**Issue by mdoucet** [SasView/sasview#603]
- Start !SasView on Mac, but do NOT click on the application icon to make it appear. Just wait until the splash screen disappears and the top menu appears.

- Load files from the top menu. The applications windows should appear, but your data is not plotted.

- At this point most of the pull-down menus will be broken.

Migrated from http://trac.sasview.org/ticket/469
```json
{
    "status": "closed",
    "changetime": "2016-06-20T18:51:09",
    "_ts": "2016-06-20 18:51:09.349644+00:00",
    "description": "- Start !SasView on Mac, but do NOT click on the application icon to make it appear. Just wait until the splash screen disappears and the top menu appears.\n\n- Load files from the top menu. The applications windows should appear, but your data is not plotted.\n\n- At this point most of the pull-down menus will be broken.",
    "reporter": "mathieu",
    "cc": "",
    "resolution": "worksforme",
    "workpackage": "SasView Bug Fixing",
    "time": "2015-10-26T20:01:31",
    "component": "SasView",
    "summary": "Loading files from the top menu doesn't always work on Mac",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.0.0",
    "owner": "",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2016/06/19 16:14:39`: 
* **butler** changed _comment0 from "NOte this seems to be a mac specific issue as windows application and menu bar are one window." to "1466352931092769"
* **butler** commented:

**NOTE:** This seems to be a mac specific issue as windows application and menu bar are one window.


* **butler** changed description from:

> - Start SasView on Mac, but do NOT click on the application icon to make it appear. Just wait until the splash screen disappears and the top menu appears.
> 
> - Load files from the top menu. The applications windows should appear, but your data is not plotted.
> 
> - At this point most of the pull-down menus will be broken.
> 

to:

> - Start !SasView on Mac, but do NOT click on the application icon to make it appear. Just wait until the splash screen disappears and the top menu appears.
> 
> - Load files from the top menu. The applications windows should appear, but your data is not plotted.
> 
> - At this point most of the pull-down menus will be broken.


* **butler** changed summary from "Loading files from the top menu doesn't always work" to "Loading files from the top menu doesn't always work on Mac"

**Comment by butlerpd** [comment]
Trac update at `2016/06/20 17:18:58`: **butler** commented:

I tried this with 4.0.0-alpha2 and was not able to reproduce the problem on my macbook pro running Yosemite.  Guessing this shas been fixed at some point in all the majore rewriting this year?  Suggest we close unless reporter still sees the same issue.

**Comment by mdoucet** [comment]
Trac update at `2016/06/20 18:51:09`: 
* **mathieu** commented:

This seems to have been fixed.


* **mathieu** changed resolution from "" to "worksforme"
* **mathieu** changed status from "new" to "closed"
