### ISSUE TITLE
slit smearing is broken in 3.1 (Trac #474)

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#608]
I'm following up on our conversation earlier about the smearing in sasview 3.1.1. I noticed that the slit smearing in 3.1.1 had strange behavior at high-q - namely a sharp drop off at the highest q-values, but I didn't see this behavior in 3.0.0.  To investigate this discrepancy, I calculated the unsmeared and slit smeared scattering intensity for the teubner-strey model with four independent pieces of code:  Jan  Ilavsky's software, sasview 3.0.0, sasview 3.1.1, and my own code. 

All codes reproduce the unsmeared intensity identically. 

Jan's code, my code, and sasview 3.0.0 smear the model nearly identically, but sasview 3.1.1 is far off. 

Migrated from http://trac.sasview.org/ticket/474
```json
{
    "status": "closed",
    "changetime": "2015-11-22T16:19:35",
    "_ts": "2015-11-22 16:19:35.742012+00:00",
    "description": "I'm following up on our conversation earlier about the smearing in sasview 3.1.1. I noticed that the slit smearing in 3.1.1 had strange behavior at high-q - namely a sharp drop off at the highest q-values, but I didn't see this behavior in 3.0.0.  To investigate this discrepancy, I calculated the unsmeared and slit smeared scattering intensity for the teubner-strey model with four independent pieces of code:  Jan  Ilavsky's software, sasview 3.0.0, sasview 3.1.1, and my own code. \n\nAll codes reproduce the unsmeared intensity identically. \n\nJan's code, my code, and sasview 3.0.0 smear the model nearly identically, but sasview 3.1.1 is far off. ",
    "reporter": "pkienzle",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2015-11-13T00:09:42",
    "component": "SasView",
    "summary": "slit smearing is broken in 3.1",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 3.1.2",
    "owner": "Paul Kienzle <pkienzle@nist.gov>",
    "type": "defect"
}
```

**Comment by pkienzle** [comment]
Trac update at `2015/11/13 00:11:23`: **pkienzle** changed attachment from "" to "Slit smearing in sasview.pdf"

**Comment by butlerpd** [comment]
Trac update at `2015/11/22 16:19:35`: **butler** changed milestone from "SasView 4.0.0" to "SasView 3.2.2"
