### ISSUE TITLE
autogenerate theory curves for sasmodels documentation (Trac #476)

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#610]
Rather than using static images for plots in the sasmodels documentation, we could generate the images when we build the documentation.  This means that the images will be consistent across models (same plotting options, same figure size, etc.) and any changes to the model definition will automatically be reflected in the docs.  It is also one less step for users when adding new models to the system.

Migrated from http://trac.sasview.org/ticket/476
```json
{
    "status": "closed",
    "changetime": "2016-03-18T11:52:55",
    "_ts": "2016-03-18 11:52:55.388970+00:00",
    "description": "Rather than using static images for plots in the sasmodels documentation, we could generate the images when we build the documentation.  This means that the images will be consistent across models (same plotting options, same figure size, etc.) and any changes to the model definition will automatically be reflected in the docs.  It is also one less step for users when adding new models to the system.",
    "reporter": "pkienzle",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasModels Redesign",
    "time": "2015-11-20T23:54:49",
    "component": "SasView",
    "summary": "autogenerate theory curves for sasmodels documentation",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.0.0",
    "owner": "",
    "type": "enhancement"
}
```

**Comment by butlerpd** [comment]
Trac update at `2015/11/21 04:36:24`: 
* **butler** changed priority from "minor" to "major"
* **butler** changed type from "defect" to "enhancement"
* **butler** changed workpackage from "SasModels New Model" to "SasModels Redesign"

**Comment by pkienzle** [comment]
Trac update at `2016/03/07 15:36:02`: **pkienzle** commented:

Allow a comparison dataset to be given in the model definition file (q, I(q)), along with the equivalent sasmodels parameters and a legend label.

**Comment by gonzalezma** [comment]
Trac update at `2016/03/18 11:52:55`: 
* **gonzalezm** commented:

Auto generation of images for the documentation done. The option of including 'external' datasets to compare with sasmodels and add this to the doc is discarded for the moment.


* **gonzalezm** changed resolution from "" to "fixed"
* **gonzalezm** changed status from "new" to "closed"
