### ISSUE TITLE
ABS reader (NIST 1D) does not handle negative dx properly (USANS slit smearing) (Trac #489)

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#623]
The NIST (*.ABS) USANS files contain the slit length as a negative entry in the dx column which is not recognized by the reader.  Need to add the case of dx < 0 then dx =NONE and dl = abs(dx).

Migrated from http://trac.sasview.org/ticket/489
```json
{
    "status": "closed",
    "changetime": "2018-01-05T02:03:42",
    "_ts": "2018-01-05 02:03:42.153826+00:00",
    "description": "The NIST (*.ABS) USANS files contain the slit length as a negative entry in the dx column which is not recognized by the reader.  Need to add the case of dx < 0 then dx =NONE and dl = abs(dx).",
    "reporter": "pkienzle",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2015-12-03T17:53:24",
    "component": "SasView",
    "summary": "ABS reader (NIST 1D) does not handle negative dx properly (USANS slit smearing)",
    "priority": "critical",
    "keywords": "",
    "milestone": "SasView 4.2.0",
    "owner": "krzywon",
    "type": "defect"
}
```

**Comment by pkienzle** [comment]
Trac update at `2015/12/03 17:53:52`: **pkienzle** changed attachment from "" to "sam14_cor"

**Comment by butlerpd** [comment]
Trac update at `2015/12/04 04:34:45`: 
* **butler** changed description from "NIST USANS files are loaded as ascii files with no slit information recorded.  This means that the fit page cannot use dQ from the data file." to "The NIST (*.ABS) USANS files contain the slit length as a negative entry in the dx column which is not recognized by the reader.  Need to add the case of dx < 0 then dx =NONE and dl = abs(dx)."
* **butler** changed milestone from "SasView Next Release +1" to "SasView 4.0.0"
* **butler** changed summary from "new reader for NIST Igor USANS format" to "ABS reader (NIST 1D) does not handle negative dx properly (USANS slit smearing)"

**Comment by butlerpd** [comment]
Trac update at `2016/03/06 18:53:06`: 
* **butler** commented:

This is important to the NIST community so we would like to fix it in this release.  Should only impact NIST 1D data (.ABS) so should not be any need for general infrastructure questions discussion making it fairly clean and easy?


* **butler** changed owner from "" to "krzywon"
* **butler** changed priority from "minor" to "critical"
* **butler** changed status from "new" to "assigned"

**Comment by butlerpd** [comment]
Trac update at `2016/03/09 15:49:05`: **butler** commented:

I don't think we should be encouraging changes to general readers to support individual idiosyncrasies.  Ultimately we can dilute our efforts significantly if we try to support all data formats and their idiosyncrasies anyway (that is why I thought we supported standard formats), but those that we do have should be confined to their own reader?

NIST folk should be using NIST or standard formats I would think?

**Comment by butlerpd** [comment]
Trac update at `2016/03/09 15:50:22`: **butler** changed priority from "critical" to "minor"

**Comment by butlerpd** [comment]
Trac update at `2016/06/26 17:19:44`: 
* **butler** commented:

As agreed on fortnightly call of June 21, am moving all minor priority tickets to next release (+1) given the resources and time available to get this release out.


* **butler** changed milestone from "SasView 4.0.0" to "SasView Next Release +1"

**Comment by butlerpd** [comment]
Trac update at `2017/09/05 01:04:10`: 
* **butler** commented:

The regular ASCII reader should not be changed to deal with a NIST idiosyncrasy.  However the .ABS reader, as a NIST reader, and as the ticket title implies should in fact respect the NIST format.  A test with 4.1.2 shows the reader sees the negative fourth column as a pinhole resolution with a negative dq.  Given the cleanup of the readers the ABS reader should be fixed for the next release.


* **butler** changed milestone from "SasView Next Release +1" to "SasView 4.2.0"
* **butler** changed priority from "minor" to "critical"
