### ISSUE TITLE
Assure that the Qt licensing model is valid for SasView (Trac #494)

### ISSUE THREAD

**Issue by rozyczko** [SasView/sasview#627]
!PyQt/Qt requires the code to be licensed with a GPL or GPL-compatible license. 
BSD licensing which !GitHub projects have by default might be too lax in this case so we need to investigate this issue a bit.

Migrated from http://trac.sasview.org/ticket/494
```json
{
    "status": "new",
    "changetime": "2018-04-03T13:00:16",
    "_ts": "2018-04-03 13:00:16.493763+00:00",
    "description": "!PyQt/Qt requires the code to be licensed with a GPL or GPL-compatible license. \nBSD licensing which !GitHub projects have by default might be too lax in this case so we need to investigate this issue a bit.",
    "reporter": "piotr",
    "cc": "",
    "resolution": "",
    "workpackage": "SasView Admin",
    "time": "2016-01-12T15:26:09",
    "component": "SasView",
    "summary": "Assure that the Qt licensing model is valid for SasView",
    "priority": "minor",
    "keywords": "",
    "milestone": "Admin Tasks",
    "owner": "",
    "type": "task"
}
```

**Comment by butlerpd** [comment]
Trac update at `2016/07/17 16:05:04`: 
* **butler** changed description from:

> PyQt/Qt requires the code to be licensed with a GPL or GPL-compatible license. 
> BSD licensing which GitHub projects have by default might be too lax in this case so we need to investigate this issue a bit.

to:

> !PyQt/Qt requires the code to be licensed with a GPL or GPL-compatible license. 
> BSD licensing which !GitHub projects have by default might be too lax in this case so we need to investigate this issue a bit.


* **butler** changed milestone from "WishList" to "Admin Tasks"
* **butler** changed type from "enhancement" to "task"

**Comment by ajj** [comment]
Trac update at `2016/10/07 20:00:31`: **ajj** commented:

Qt is LGPL so not a problem

PyQt is GPL which is a problem. Option for ESS to buy commercial license which might solve problem. Needs more investigation.

**Comment by pkienzle** [comment]
Trac update at `2018/04/03 13:00:16`: **pkienzle** commented:

Commercial license requires one license per active developer.  The number of active developers in not well defined, but presumably would be one per code camp attendee?  

Commercial license must be purchased prior to first release of the proprietary application.  Not sure if this means you can do a GPL release of your application before releasing a non-GPL version.

The entire product must be released as GPL if any part is GPL, but that does not prevent us from having the different licenses on the different files.  In particular, sasmodels and the non-GUI sasview libraries can be released as BSD.

!PySide (Qt4) and PySide2 (Qt5) are LGPL.  Don't know if they work with sasview.  Wheels for PySide2 are available here: 

    http://download.qt.io/snapshots/ci/pyside/5.11/latest/pyside2/

**Comment by ajj** [comment]
Developers are covered by the free license. Only need commercial license for build and release. ESS purchased license for this.
