### ISSUE TITLE
No argument checks in massfractal.cpp cause conversion problems (Trac #497)

### ISSUE THREAD

**Issue by rozyczko** [SasView/sasview#630]
While converting the massfractal model I found that the sasview implementation of it (massfractal.cpp) doesn't check mass_dim allowed range and in effect produces !NaNs for mass_dim <= 1.0.

Migrated from http://trac.sasview.org/ticket/497
```json
{
    "status": "closed",
    "changetime": "2016-03-08T13:45:53",
    "_ts": "2016-03-08 13:45:53.917826+00:00",
    "description": "While converting the massfractal model I found that the sasview implementation of it (massfractal.cpp) doesn't check mass_dim allowed range and in effect produces !NaNs for mass_dim <= 1.0.\n",
    "reporter": "piotr",
    "cc": "",
    "resolution": "wontfix",
    "workpackage": "SasView Bug Fixing",
    "time": "2016-01-22T14:07:03",
    "component": "SasView",
    "summary": "No argument checks in massfractal.cpp cause conversion problems",
    "priority": "blocker",
    "keywords": "",
    "milestone": "SasView 4.0.0",
    "owner": "piotr",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2016/03/06 18:17:23`: 
* **butler** commented:

This has to do with core task of sasmodels.  Should close this ticket once the sasmodels version is fixed.  Meanwhile making this a blocker.


* **butler** changed description from:

> While converting the massfractal model I found that the sasview implementation of it (massfractal.cpp) doesn't check mass_dim allowed range and in effect produces NaNs for mass_dim <= 1.0.
> 

to:

> While converting the massfractal model I found that the sasview implementation of it (massfractal.cpp) doesn't check mass_dim allowed range and in effect produces !NaNs for mass_dim <= 1.0.
> 


* **butler** changed priority from "major" to "blocker"

**Comment by butlerpd** [comment]
Trac update at `2016/03/06 21:00:09`: 
* **butler** changed owner from "" to "piotr"
* **butler** changed status from "new" to "assigned"

**Comment by butlerpd** [comment]
Trac update at `2016/03/08 03:02:59`: **butler** commented:

This is fixed in sasmodels - no point in fixing the old code which is about to be obsolete so closing this ticket.

**Comment by rozyczko** [comment]
Trac update at `2016/03/08 13:45:53`: 
* **piotr** changed resolution from "" to "wontfix"
* **piotr** changed status from "assigned" to "closed"
