### ISSUE TITLE
$HOME/.matplotlib conflicts (Trac #498)

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#631]
Matplotlib's configuration file conflicts can cause exceptions to be thrown on application startup which are not captured in sasview.log.

Within sasview.py we need a try/catch block around the import statements so that we can catch exceptions and output them to sasview.log.

We need to set the MPLCONFIGDIR to a sasview specific directory to avoid conflicts with other versions of python installed on the system.  This directory needs to be removed as part of the uninstall process so we don't conflict with older versions of sasview.  Alternatively, put the sasview install in a directory tagged with version number so that we can have different versions installed at the same time.

Make sure the .matplotlib directory is located in a directory writable by the user; not all users have write access to Program Files.

Migrated from http://trac.sasview.org/ticket/498
```json
{
    "status": "closed",
    "changetime": "2016-03-20T12:48:31",
    "_ts": "2016-03-20 12:48:31.591130+00:00",
    "description": "Matplotlib's configuration file conflicts can cause exceptions to be thrown on application startup which are not captured in sasview.log.\n\nWithin sasview.py we need a try/catch block around the import statements so that we can catch exceptions and output them to sasview.log.\n\nWe need to set the MPLCONFIGDIR to a sasview specific directory to avoid conflicts with other versions of python installed on the system.  This directory needs to be removed as part of the uninstall process so we don't conflict with older versions of sasview.  Alternatively, put the sasview install in a directory tagged with version number so that we can have different versions installed at the same time.\n\nMake sure the .matplotlib directory is located in a directory writable by the user; not all users have write access to Program Files.",
    "reporter": "pkienzle",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2016-02-01T21:38:16",
    "component": "SasView",
    "summary": "$HOME/.matplotlib conflicts",
    "priority": "blocker",
    "keywords": "",
    "milestone": "SasView 4.0.0",
    "owner": "ajj",
    "type": "defect"
}
```

**Comment by ajj** [comment]
Trac update at `2016/02/28 11:23:06`: 
* **ajj** changed owner from "" to "ajj"
* **ajj** changed priority from "major" to "critical"
* **ajj** changed status from "new" to "assigned"

**Comment by butlerpd** [comment]
Trac update at `2016/03/19 12:25:09`: 
* **butler** commented:

Andrew says this needs fixing for 4.0 or many things will break?


* **butler** changed priority from "critical" to "blocker"

**Comment by ajj** [comment]
Trac update at `2016/03/20 12:48:31`: 
* **ajj** commented:

sasview now uses .sasview/,matplotlib


* **ajj** changed resolution from "" to "fixed"
* **ajj** changed status from "assigned" to "closed"
