### ISSUE TITLE
create sin(x)/x, 2*J1(x)/x and 3*j1(x)/x functions (Trac #499)

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#632]
Certain expressions are repeated frequently in sasmodels, such as sin(x)/x, 2*J1(x)/x and 3*j1(x)/x functions.  We should make functions for these so that they handle the case of q=0 and are numerically stable as q->0.  This has already been done for the spherical Bessel function 3*j1(x)/x, using the name sph_j1c.

Once these functions are created, we need to use them whereever they occur in the code.

Migrated from http://trac.sasview.org/ticket/499
```json
{
    "status": "closed",
    "changetime": "2018-03-04T17:08:13",
    "_ts": "2018-03-04 17:08:13.507525+00:00",
    "description": "Certain expressions are repeated frequently in sasmodels, such as sin(x)/x, 2*J1(x)/x and 3*j1(x)/x functions.  We should make functions for these so that they handle the case of q=0 and are numerically stable as q->0.  This has already been done for the spherical Bessel function 3*j1(x)/x, using the name sph_j1c.\n\nOnce these functions are created, we need to use them whereever they occur in the code.",
    "reporter": "pkienzle",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasModels Redesign",
    "time": "2016-02-25T17:48:20",
    "component": "SasView",
    "summary": "create sin(x)/x, 2*J1(x)/x and 3*j1(x)/x functions",
    "priority": "minor",
    "keywords": "",
    "milestone": "SasView 4.2.0",
    "owner": "",
    "type": "defect"
}
```

**Comment by pkienzle** [comment]
Trac update at `2016/02/25 17:49:30`: 
* **pkienzle** changed _comment0 from:

> $ grep J1 *.c
> barbell.c:        const double be = (arg2 == 0.0 ? 0.5 :J1(arg2)/arg2);
> barbell.c:        // lim_{x->0} J1(x)/x = 1/2,   lim_{x->0} sin(x)/x = 1
> barbell.c:        const double be = (arg2 == 0.0 ? 0.5 :J1(arg2)/arg2);
> barbell.c:    // lim_{x->0} J1(x)/x = 1/2,   lim_{x->0} sin(x)/x = 1
> barbell.c:    const double bj = (besarg == 0.0 ? 0.5 : J1(besarg)/besarg);
> capped_cylinder.c:        const double be = (arg == 0.0 ? 0.5 : J1(arg)/arg);
> capped_cylinder.c:        // lim_{x->0} J1(x)/x = 1/2,   lim_{x->0} sin(x)/x = 1
> capped_cylinder.c:        const double bj = (besarg == 0.0 ? 0.5 : J1(besarg)/besarg);
> capped_cylinder.c:    // lim_{x->0} J1(x)/x = 1/2,   lim_{x->0} sin(x)/x = 1
> capped_cylinder.c:    const double bj = (besarg == 0.0 ? 0.5 : J1(besarg)/besarg);
> core_shell_bicelle.c:		be1 = J1(besarg1)/besarg1;
> core_shell_bicelle.c:		be2 = J1(besarg2)/besarg2;
> core_shell_cylinder.c:    const double bj = (besarg == 0.0 ? 0.5 : J1(besarg)/besarg);
> cylinder.c:    const double bj = (besarg == 0.0 ? 0.5 : J1(besarg)/besarg);
> elliptical_cylinder.c:        retval = 2.0*NR_BessJ1(arg)/arg;
> elliptical_cylinder.c:      Be = NR_BessJ1(qr)/qr;
> flexible_cylinder.c:    double crossSect = (2.0*J1(qr)/qr)*(2.0*J1(qr)/qr);
> flexible_cylinder_ex.c:		yyy = pow((2.0 * J1(arg) / arg),2);
> hollow_cylinder.c:    	lam1 = 2.0*J1(arg1)/arg1;
> hollow_cylinder.c:    	lam2 = 2.0*J1(arg2)/arg2;
> stacked_disks.c:    const double be1 = J1(besarg1)/besarg1;
> stacked_disks.c:	const double be2 = J1(besarg2)/besarg2;
> 
> $ grep "sin([^(]*) */" *.c
> barbell.c:        // lim_{x->0} J1(x)/x = 1/2,   lim_{x->0} sin(x)/x = 1
> barbell.c:        const double si = (arg1 == 0.0 ? 1.0 :sin(arg1)/arg1);
> barbell.c:    // lim_{x->0} J1(x)/x = 1/2,   lim_{x->0} sin(x)/x = 1
> barbell.c:    const double si = (siarg == 0.0 ? 1.0 : sin(siarg)/siarg);
> capped_cylinder.c:        // to avoid sin(alpha)/sin(alpha) for alpha = 0.  It is also a teensy bit
> capped_cylinder.c:        // lim_{x->0} J1(x)/x = 1/2,   lim_{x->0} sin(x)/x = 1
> capped_cylinder.c:        const double si = (siarg == 0.0 ? 1.0 : sin(siarg)/siarg);
> capped_cylinder.c:    // lim_{x->0} J1(x)/x = 1/2,   lim_{x->0} sin(x)/x = 1
> capped_cylinder.c:    const double si = (siarg == 0.0 ? 1.0 : sin(siarg)/siarg);
> core_shell_bicelle.c:		si1 = sin(sinarg1)/sinarg1;
> core_shell_bicelle.c:		si2 = sin(sinarg2)/sinarg2;
> core_shell_cylinder.c:    const double si = (siarg == 0.0 ? 1.0 : sin(siarg)/siarg);
> cylinder.c:    const double si = (siarg == 0.0 ? 1.0 : sin(siarg)/siarg);
> elliptical_cylinder.c:            si = sin(arg) * sin(arg) / arg / arg;
> elliptical_cylinder.c:      Si = sin(qL)/qL;
> hollow_cylinder.c:    	t2 = sin(sinarg)/sinarg;
> lamellarPC_kernel.c:	Pbil = (sin(qval*xi)/(qval*xi))*(sin(qval*xi)/(qval*xi));
> linear_pearls.c:  return sin(x)/x;
> parallelepiped.c:    //handle arg=0 separately, as sin(t)/t -> 1 as t->0
> parallelepiped.c:        tmp1 = sin(argA)*sin(argA)/argA/argA;
> parallelepiped.c:        tmp2 = sin(argB)*sin(argB)/argB/argB;
> parallelepiped.c:        tmp3 = sin(argC)*sin(argC)/argC/argC;
> parallelepiped.c:                tmp1 = sin(arg1)*sin(arg1)/arg1/arg1;
> parallelepiped.c:                tmp2 = sin(arg2)*sin(arg2)/arg2/arg2;
> parallelepiped.c:            answer *= sin(arg)*sin(arg)/arg/arg;
> stacked_disks.c:	const double si1 = sin(sinarg1)/sinarg1;
> stacked_disks.c:	const double si2 = sin(sinarg2)/sinarg2;
> 

to:

> 1456422629527323


* **pkienzle** commented:

$ grep J1 *.c
barbell.c:        const double be = (arg2 == 0.0 ? 0.5 :J1(arg2)/arg2);
barbell.c:        // lim_{x->0} J1(x)/x = 1/2,   lim_{x->0} sin(x)/x = 1
barbell.c:        const double be = (arg2 == 0.0 ? 0.5 :J1(arg2)/arg2);
barbell.c:    // lim_{x->0} J1(x)/x = 1/2,   lim_{x->0} sin(x)/x = 1
barbell.c:    const double bj = (besarg == 0.0 ? 0.5 : J1(besarg)/besarg);
capped_cylinder.c:        const double be = (arg == 0.0 ? 0.5 : J1(arg)/arg);
capped_cylinder.c:        // lim_{x->0} J1(x)/x = 1/2,   lim_{x->0} sin(x)/x = 1
capped_cylinder.c:        const double bj = (besarg == 0.0 ? 0.5 : J1(besarg)/besarg);
capped_cylinder.c:    // lim_{x->0} J1(x)/x = 1/2,   lim_{x->0} sin(x)/x = 1
capped_cylinder.c:    const double bj = (besarg == 0.0 ? 0.5 : J1(besarg)/besarg);
core_shell_bicelle.c:		be1 = J1(besarg1)/besarg1;
core_shell_bicelle.c:		be2 = J1(besarg2)/besarg2;
core_shell_cylinder.c:    const double bj = (besarg == 0.0 ? 0.5 : J1(besarg)/besarg);
cylinder.c:    const double bj = (besarg == 0.0 ? 0.5 : J1(besarg)/besarg);
elliptical_cylinder.c:        retval = 2.0*NR_BessJ1(arg)/arg;
elliptical_cylinder.c:      Be = NR_BessJ1(qr)/qr;
flexible_cylinder.c:    double crossSect = (2.0*J1(qr)/qr)*(2.0*J1(qr)/qr);
flexible_cylinder_ex.c:		yyy = pow((2.0 * J1(arg) / arg),2);
hollow_cylinder.c:    	lam1 = 2.0*J1(arg1)/arg1;
hollow_cylinder.c:    	lam2 = 2.0*J1(arg2)/arg2;
stacked_disks.c:    const double be1 = J1(besarg1)/besarg1;
stacked_disks.c:	const double be2 = J1(besarg2)/besarg2;

$ grep "sin([^^(]*) */" *.c
barbell.c:        // lim_{x->0} J1(x)/x = 1/2,   lim_{x->0} sin(x)/x = 1
barbell.c:        const double si = (arg1 == 0.0 ? 1.0 :sin(arg1)/arg1);
barbell.c:    // lim_{x->0} J1(x)/x = 1/2,   lim_{x->0} sin(x)/x = 1
barbell.c:    const double si = (siarg == 0.0 ? 1.0 : sin(siarg)/siarg);
capped_cylinder.c:        // to avoid sin(alpha)/sin(alpha) for alpha = 0.  It is also a teensy bit
capped_cylinder.c:        // lim_{x->0} J1(x)/x = 1/2,   lim_{x->0} sin(x)/x = 1
capped_cylinder.c:        const double si = (siarg == 0.0 ? 1.0 : sin(siarg)/siarg);
capped_cylinder.c:    // lim_{x->0} J1(x)/x = 1/2,   lim_{x->0} sin(x)/x = 1
capped_cylinder.c:    const double si = (siarg == 0.0 ? 1.0 : sin(siarg)/siarg);
core_shell_bicelle.c:		si1 = sin(sinarg1)/sinarg1;
core_shell_bicelle.c:		si2 = sin(sinarg2)/sinarg2;
core_shell_cylinder.c:    const double si = (siarg == 0.0 ? 1.0 : sin(siarg)/siarg);
cylinder.c:    const double si = (siarg == 0.0 ? 1.0 : sin(siarg)/siarg);
elliptical_cylinder.c:            si = sin(arg) * sin(arg) / arg / arg;
elliptical_cylinder.c:      Si = sin(qL)/qL;
hollow_cylinder.c:    	t2 = sin(sinarg)/sinarg;
lamellarPC_kernel.c:	Pbil = (sin(qval*xi)/(qval*xi))*(sin(qval*xi)/(qval*xi));
linear_pearls.c:  return sin(x)/x;
parallelepiped.c:    //handle arg=0 separately, as sin(t)/t -> 1 as t->0
parallelepiped.c:        tmp1 = sin(argA)*sin(argA)/argA/argA;
parallelepiped.c:        tmp2 = sin(argB)*sin(argB)/argB/argB;
parallelepiped.c:        tmp3 = sin(argC)*sin(argC)/argC/argC;
parallelepiped.c:                tmp1 = sin(arg1)*sin(arg1)/arg1/arg1;
parallelepiped.c:                tmp2 = sin(arg2)*sin(arg2)/arg2/arg2;
parallelepiped.c:            answer *= sin(arg)*sin(arg)/arg/arg;
stacked_disks.c:	const double si1 = sin(sinarg1)/sinarg1;
stacked_disks.c:	const double si2 = sin(sinarg2)/sinarg2;

**Comment by pkienzle** [comment]
Trac update at `2016/02/25 17:52:03`: **pkienzle** commented:

Also, remove duplicate function NR_BessJ1.c

**Comment by pkienzle** [comment]
Trac update at `2017/08/02 03:15:33`: 
* **pkienzle** changed resolution from "" to "fixed"
* **pkienzle** changed status from "new" to "closed"

**Comment by butlerpd** [comment]
Trac update at `2018/03/04 17:08:13`: **butler** changed milestone from "SasView Next Release +1" to "SasView 4.2.0"
