### ISSUE TITLE
Support loading of data files from Anton Parr SAXSess (Trac #500)

### ISSUE THREAD

**Issue by ajj** [SasView/sasview#633]
Anton Parr have their own output format for reduced data.

It consists of an multi-column ascii with some metadata in XML stuck on the end. The meta data includes the units, which seem to be nm-1 for Q and um-2 for intensity (counts per area from image plate).

Example is attached.

Migrated from http://trac.sasview.org/ticket/500
```json
{
    "status": "closed",
    "changetime": "2016-10-03T13:48:11",
    "_ts": "2016-10-03 13:48:11.956031+00:00",
    "description": "Anton Parr have their own output format for reduced data.\n\nIt consists of an multi-column ascii with some metadata in XML stuck on the end. The meta data includes the units, which seem to be nm-1 for Q and um-2 for intensity (counts per area from image plate).\n\nExample is attached.",
    "reporter": "ajj",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Framework Enhancements",
    "time": "2016-02-28T11:13:32",
    "component": "SasView",
    "summary": "Support loading of data files from Anton Parr SAXSess",
    "priority": "minor",
    "keywords": "",
    "milestone": "SasView 4.1.0",
    "owner": "krzywon",
    "type": "enhancement"
}
```

**Comment by ajj** [comment]
Trac update at `2016/02/28 11:14:03`: 
* **ajj** changed attachment from "" to "10wtAOT Reline 120 reduced.pdh"
* **ajj** commented:

Example of SAXSess data file (.pdh)

**Comment by ajj** [comment]
Trac update at `2016/02/28 11:14:46`: **ajj** changed workpackage from "SasView Bug Fixing" to "SasView Framework Enhancements"

**Comment by butlerpd** [comment]
Trac update at `2016/09/05 14:39:46`: **butler** changed priority from "critical" to "minor"

**Comment by butlerpd** [comment]
Trac update at `2016/09/09 01:36:22`: 
* **butler** commented:

The reader is now working on the data, but does not pick up header information yet so for example the units of the data are assumed.  Jeff says he has the final part finished but for now what we have should work fine for the user. Given we don't need to introduce any more code into 4.0 that could have unintended consequences this ticket is being moved to 4.1.  In principle the final code can be pushed immediately after release 4.02 and this ticket then closed.


* **butler** changed milestone from "SasView 4.0.0" to "SasView 4.1.0"
