### ISSUE TITLE
Consider moving category "modify" button (Trac #502)

### ISSUE THREAD

**Issue by ajj** [SasView/sasview#635]
In the overhaul of category management, consider moving the "Modify" button to a menu item.

Having the button there tempts users to click it when changing the dropdown for categories. Then much confusion ensues.

Migrated from http://trac.sasview.org/ticket/502
```json
{
    "status": "closed",
    "changetime": "2018-09-05T14:48:20",
    "_ts": "2018-09-05 14:48:20.924342+00:00",
    "description": "In the overhaul of category management, consider moving the \"Modify\" button to a menu item.\n\nHaving the button there tempts users to click it when changing the dropdown for categories. Then much confusion ensues.",
    "reporter": "ajj",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView GUI Enhancements",
    "time": "2016-02-28T15:36:01",
    "component": "SasView",
    "summary": "Consider moving category \"modify\" button",
    "priority": "minor",
    "keywords": "",
    "milestone": "SasView 5.0.0",
    "owner": "butler",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2016/03/20 22:44:55`: **butler** changed milestone from "SasView 4.0.0" to "SasView Next Release +1"

**Comment by rozyczko** [comment]
Trac update at `2017/04/08 20:23:06`: **piotr** commented:

Addressed in the Qt version

**Comment by butlerpd** [comment]
Trac update at `2017/10/26 11:24:32`: 
* **butler** changed milestone from "SasView Next Release +1" to "SasView 5.0.0"
* **butler** changed workpackage from "SasView Bug Fixing" to "SasView GUI Enhancements"
