### ISSUE TITLE
Support loading of a wider variety of data files (Trac #508)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#641]
Related to ticket #633

There are a number of commonly-produced reduced data formats that the SasView loader does not currently support and which would significantly expand the SasView user base if it did:

Single-file 1D Formats
- files of the type exemplified by the ASCII output from DNDCAT (APS)
- files of the type exemplified by the SAXSess PDH ASCII format (ticket #633)
- (also check if the SESANS format is in the loader?)

Multiple-file 1D formats
- files of the type used by FIT2D (ESRF): separate ASCII Q and I files (ticket #331)
- the historic but still-used BSL/OTOKO format (Diamond): separate ASCII header + 1/2/3 binary files 

Single-file 2D formats
- the ISIS 2D ASCII format

Multiple-file 2D formats
- the BerSANS 2D ASCII format (HZB/KWS)

We should up the priority for supporting these.

Migrated from http://trac.sasview.org/ticket/508
```json
{
    "status": "closed",
    "changetime": "2018-03-04T17:17:31",
    "_ts": "2018-03-04 17:17:31.731381+00:00",
    "description": "Related to ticket #500\n\nThere are a number of commonly-produced reduced data formats that the SasView loader does not currently support and which would significantly expand the SasView user base if it did:\n\nSingle-file 1D Formats\n- files of the type exemplified by the ASCII output from DNDCAT (APS)\n- files of the type exemplified by the SAXSess PDH ASCII format (ticket #500)\n- (also check if the SESANS format is in the loader?)\n\nMultiple-file 1D formats\n- files of the type used by FIT2D (ESRF): separate ASCII Q and I files (ticket #183)\n- the historic but still-used BSL/OTOKO format (Diamond): separate ASCII header + 1/2/3 binary files \n\nSingle-file 2D formats\n- the ISIS 2D ASCII format\n\nMultiple-file 2D formats\n- the BerSANS 2D ASCII format (HZB/KWS)\n\nWe should up the priority for supporting these.\n",
    "reporter": "smk78",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Framework Enhancements",
    "time": "2016-03-08T16:43:17",
    "component": "SasView",
    "summary": "Support loading of a wider variety of data files",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.1.0",
    "owner": "krzywon",
    "type": "enhancement"
}
```

**Comment by smk78** [comment]
Trac update at `2016/03/08 17:08:48`: 
* **smk78** changed attachment from "" to "DNDCAT_format.txt"
* **smk78** commented:

DNDCAT format data file

**Comment by smk78** [comment]
Trac update at `2016/03/08 17:09:19`: 
* **smk78** changed attachment from "" to "SAXSess-PDH_format.txt"
* **smk78** commented:

SAXSess format data file

**Comment by smk78** [comment]
Trac update at `2016/03/08 17:09:47`: 
* **smk78** changed attachment from "" to "Anton-Paar_PDH_file_format.pdf"
* **smk78** commented:

Description of SAXSess format

**Comment by smk78** [comment]
Trac update at `2016/03/08 17:10:27`: 
* **smk78** changed attachment from "" to "FIT2D_format-Q.txt"
* **smk78** commented:

FIT2D format data file (Q)

**Comment by smk78** [comment]
Trac update at `2016/03/08 17:10:46`: 
* **smk78** changed attachment from "" to "FIT2D_format_I.txt"
* **smk78** commented:

FIT2D format data file (I)

**Comment by smk78** [comment]
Trac update at `2016/03/08 17:16:14`: 
* **smk78** changed attachment from "" to "OTOKO_I32000.QAX"
* **smk78** commented:

OTOKO/BSL format data file (Q header)

**Comment by smk78** [comment]
Trac update at `2016/03/08 17:16:56`: 
* **smk78** changed attachment from "" to "OTOKO_I32001.QAX"
* **smk78** commented:

OTOKO/BSL format data file (Q data)

**Comment by smk78** [comment]
Trac update at `2016/03/08 17:17:30`: 
* **smk78** changed attachment from "" to "OTOKO_I32000.L1D"
* **smk78** commented:

OTOKO/BSL format data file (I header)

**Comment by smk78** [comment]
Trac update at `2016/03/08 17:17:54`: 
* **smk78** changed attachment from "" to "OTOKO_I32001.L1D"
* **smk78** commented:

OTOKO/BSL format data file (I data)

**Comment by smk78** [comment]
Trac update at `2016/03/08 17:22:04`: 
* **smk78** changed attachment from "" to "OTOKO_I32002.L1D"
* **smk78** commented:

OTOKO/BSL format data file (calibration data)

**Comment by smk78** [comment]
Trac update at `2016/03/08 17:22:33`: 
* **smk78** changed attachment from "" to "ISIS_2D_format.txt"
* **smk78** commented:

ISIS 2D format data file

**Comment by smk78** [comment]
Trac update at `2016/03/08 17:23:50`: 
* **smk78** changed attachment from "" to "ISIS_2D_format_Fortran.TXT"
* **smk78** commented:

Fortran source for r/w ISIS 2D data file formats

**Comment by smk78** [comment]
Trac update at `2016/03/08 17:24:35`: 
* **smk78** changed attachment from "" to "KWS_2D_format-Q.txt"
* **smk78** commented:

KWS 2D data file format (Q data)

**Comment by smk78** [comment]
Trac update at `2016/03/08 17:24:52`: 
* **smk78** changed attachment from "" to "KWS_2D_format-I.txt"
* **smk78** commented:

KWS 2D data file format (I data)

**Comment by smk78** [comment]
Trac update at `2016/03/08 17:25:09`: 
* **smk78** changed attachment from "" to "KWS_2D_format-dI.txt"
* **smk78** commented:

KWS 2D data file format (dI data)

**Comment by smk78** [comment]
Trac update at `2016/03/08 17:25:32`: 
* **smk78** changed attachment from "" to "BerSANS_2D_format.txt"
* **smk78** commented:

BerSANS 2D data file format

**Comment by smk78** [comment]
Trac update at `2016/03/08 17:27:50`: 
* **smk78** changed attachment from "" to "load_otoko.py"
* **smk78** commented:

Peter Parkers Python routine for loading OTOKO format data files

**Comment by smk78** [comment]
Trac update at `2016/03/08 17:28:31`: 
* **smk78** changed attachment from "" to "load_otoko_test.py"
* **smk78** commented:

Peter Parkers Python program for testing loading of OTOKO format data files

**Comment by smk78** [comment]
Trac update at `2016/03/09 15:25:11`: **smk78** commented:

SK can supply more information about the OTOKO/BSL format, and the ISIS 2D format. MG was having a look at the KWS format for Ralf in April 2015.

But in terms of priority, I would say:

- 1st: the FIT2D format (this type of format is remarkably common in the SAXS community)
- 2nd: the ISIS 2D format (it is the only other 2D format written by Mantid)
- 3rd: the SAXSess format (as it should be easy to code & would give us some cudos with A-P)
- 4th: the OTOKO format (would give us traction with Diamond, but is more effort to implement)
- 5th: the remaining formats

NB: the OTOKO format can handle single or multi-frame data. Because the latter can be ''huge'' (SK can provide an example - the attached OTOKO file is single frame) we might want to think about reading the number of frames from the header, and only loading that frame.

**Comment by ajj** [comment]
Trac update at `2016/03/13 23:50:32`: **ajj** changed description from:

> Related to ticket #500
> 
> There are a number of commonly-produced reduced data formats that the SasView loader does not currently support and which would significantly expand the SasView user base if it did:
> 
> Single-file 1D Formats
> - files of the type exemplified by the ASCII output from DNDCAT (APS)
> - files of the type exemplified by the SAXSess PDH ASCII format (ticket #500)
> - (also check if the SESANS format is in the loader?)
> 
> Multiple-file 1D formats
> - files of the type used by FIT2D (ESRF): separate ASCII Q and I files
> - the historic but still-used BSL/OTOKO format (Diamond): separate ASCII header + 1/2/3 binary files 
> 
> Single-file 2D formats
> - the ISIS 2D ASCII format
> 
> Multiple-file 2D formats
> - the BerSANS 2D ASCII format (HZB/KWS)
> 
> We should up the priority for supporting these.
> 

to:

> Related to ticket #500
> 
> There are a number of commonly-produced reduced data formats that the SasView loader does not currently support and which would significantly expand the SasView user base if it did:
> 
> Single-file 1D Formats
> - files of the type exemplified by the ASCII output from DNDCAT (APS)
> - files of the type exemplified by the SAXSess PDH ASCII format (ticket #500)
> - (also check if the SESANS format is in the loader?)
> 
> Multiple-file 1D formats
> - files of the type used by FIT2D (ESRF): separate ASCII Q and I files (ticket #183)
> - the historic but still-used BSL/OTOKO format (Diamond): separate ASCII header + 1/2/3 binary files 
> 
> Single-file 2D formats
> - the ISIS 2D ASCII format
> 
> Multiple-file 2D formats
> - the BerSANS 2D ASCII format (HZB/KWS)
> 
> We should up the priority for supporting these.
>

**Comment by butlerpd** [comment]
Trac update at `2016/03/20 23:06:24`: 
* **butler** changed milestone from "SasView 4.0.0" to "SasView Next Release +1"
* **butler** changed priority from "critical" to "major"

**Comment by smk78** [comment]
Trac update at `2016/10/07 20:09:48`: **smk78** commented:

Of these formats:

- files of the type exemplified by the ASCII output from DNDCAT (APS) are now supported by the ASCII loader in !SasView 4.1 onwards (also see #331)

- files of the type exemplified by the SAXSess PDH ASCII format are now supported by the ASCII loader in !SasView 4.0 onwards (also see #633)

- the SESANS format is now supported in the ASCII loader from !SasView 4.1

- files of the type used by FIT2D (ESRF) with separate ASCII Q and I files are now supported by the File Converter in !SasView 4.1 onwards (also see #331)

- files in the historic but still-used BSL/OTOKO format (Diamond) with separate ASCII header + 1/2/3 binary files are now supported by the File Converter in !SasView 4.1 onwards

- the ISIS 2D ASCII format is now superceded by the NXcanSAS format supported in Mantid and !SasView 4.0 onwards

- **the BerSANS multiple file 2D ASCII format (HZB/KWS) remains unsupported (requirement moved into #845)**

**Comment by smk78** [comment]
Trac update at `2016/10/07 20:10:00`: 
* **smk78** changed resolution from "" to "fixed"
* **smk78** changed status from "assigned" to "closed"

**Comment by butlerpd** [comment]
Trac update at `2018/03/04 17:17:31`: **butler** changed milestone from "SasView Next Release +1" to "SasView 4.1.0"
