### ISSUE TITLE
Build PDF documentation along with HTML (Trac #510)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#643]
Sphinx make file needs to be edited to build PDFs as well as HTML for offline use. Note that expectation is to have tutorials delivered in the same way (PDF and HTML bundled with !SasView and on the web page)

Migrated from http://trac.sasview.org/ticket/510
```json
{
    "status": "closed",
    "changetime": "2017-10-27T13:36:11",
    "_ts": "2017-10-27 13:36:11.354120+00:00",
    "description": "Sphinx make file needs to be edited to build PDFs as well as HTML for offline use. Note that expectation is to have tutorials delivered in the same way (PDF and HTML bundled with !SasView and on the web page)",
    "reporter": "butler",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Documentation",
    "time": "2016-03-15T16:52:49",
    "component": "SasView",
    "summary": "Build PDF documentation along with HTML",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.2.0",
    "owner": "wojciech",
    "type": "enhancement"
}
```

**Comment by butlerpd** [comment]
Trac update at `2016/03/20 23:05:13`: 
* **butler** changed milestone from "SasView 4.0.0" to "SasView Next Release +1"
* **butler** changed priority from "critical" to "major"

**Comment by butlerpd** [comment]
Trac update at `2016/03/20 23:21:47`: **butler** changed milestone from "SasView Next Release +1" to "SasView 4.0.0"

**Comment by smk78** [comment]
Trac update at `2016/03/20 23:28:04`: **smk78** commented:

Make file is already set to make pdf. But pdf is generated from a latex make first and this requires the build machine to have a TeK installation. TeK is not currently on DMSC build servers.

**Comment by butlerpd** [comment]
Trac update at `2016/06/19 16:40:00`: 
* **butler** commented:

Yet another thing that should be relatively straightforward to finish but not vital for 4.0 and give the resources and amount of work left for 4.0 sadly need to move to +1


* **butler** changed milestone from "SasView 4.0.0" to "SasView Next Release +1"

**Comment by ajj** [comment]
Trac update at `2016/10/07 19:45:59`: 
* **ajj** changed owner from "" to "ajj"
* **ajj** changed status from "new" to "assigned"

**Comment by smk78** [comment]
Trac update at `2017/04/05 09:25:01`: 
* **smk78** changed milestone from "SasView Next Release +1" to "SasView 4.2.0"
* **smk78** changed owner from "ajj" to "wojciech"

**Comment by wpotrzebowski** [comment]
Trac update at `2017/04/05 15:31:47`: **wojciech** commented:

This turned out to be complicated there are two ways to approach this. 
1) Install rst2pdf and modify build_sphinx.py to create pdf
2) Modify build_sphinx.py to create latex file and then use pdflatex to generate pdf. 

The issue with 1) is that it doesn't really work 2) requires all the images converted to png (both gif and bmp), which are quite many

**Comment by smk78** [comment]
Trac update at `2017/04/08 14:59:20`: **smk78** commented:

Also see #1014

**Comment by wpotrzebowski** [comment]
Trac update at `2017/07/24 05:14:46`: **wojciech** commented:

Progressed much with this during last code camp but need to finish off.

**Comment by butlerpd** [comment]
Trac update at `2017/10/27 13:36:11`: 
* **butler** commented:

This now works.  PDF is built only on Ubuntu build server.  Artifact needs to be copied to wherever we want it -- the website for now.  Will add this instruction to wiki.  Can now close this ticket.


* **butler** changed resolution from "" to "fixed"
* **butler** changed status from "assigned" to "closed"
