### ISSUE TITLE
Restructure Document tree in User Documentation (Trac #511)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#644]
The User Documentation has too many links and a bit confusing. This can be cleaned up by collecting a large number of the links into two top level entries. mainly:
  * collapse tool help under a top level Tools entry
  * collapse Fitting, Pr an invariant into an Analysis heading

Migrated from http://trac.sasview.org/ticket/511
```json
{
    "status": "closed",
    "changetime": "2016-03-18T13:40:29",
    "_ts": "2016-03-18 13:40:29.006227+00:00",
    "description": "The User Documentation has too many links and a bit confusing. This can be cleaned up by collecting a large number of the links into two top level entries. mainly:\n  * collapse tool help under a top level Tools entry\n  * collapse Fitting, Pr an invariant into an Analysis heading\n",
    "reporter": "butler",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Documentation",
    "time": "2016-03-15T17:00:36",
    "component": "SasView",
    "summary": "Restructure Document tree in User Documentation",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.0.0",
    "owner": "",
    "type": "enhancement"
}
```

**Comment by smk78** [comment]
Trac update at `2016/03/18 13:40:29`: 
* **smk78** commented:

Split user.rst into user.rst, tools.rst and analysis.rst


* **smk78** changed resolution from "" to "fixed"
* **smk78** changed status from "new" to "closed"
