### ISSUE TITLE
Remove all references to "perspective" from User Documentation (Trac #513)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#646]
The term perspective is used by developers to refer to the plugins such as fitting and Invariant which are meant to provide different "perspectives" on the same data.  The term is borrowed from Eclipse which has a same philosophy.  From a user "perspective" however this is confusing.  Thus we need to remove all reference to the term from the User Documentation

Migrated from http://trac.sasview.org/ticket/513
```json
{
    "status": "closed",
    "changetime": "2016-08-16T16:31:39",
    "_ts": "2016-08-16 16:31:39.503056+00:00",
    "description": "The term perspective is used by developers to refer to the plugins such as fitting and Invariant which are meant to provide different \"perspectives\" on the same data.  The term is borrowed from Eclipse which has a same philosophy.  From a user \"perspective\" however this is confusing.  Thus we need to remove all reference to the term from the User Documentation",
    "reporter": "butler",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Documentation",
    "time": "2016-03-15T17:07:47",
    "component": "SasView",
    "summary": "Remove all references to \"perspective\" from User Documentation",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.0.0",
    "owner": "",
    "type": "enhancement"
}
```

**Comment by smk78** [comment]
Trac update at `2016/08/16 16:31:28`: **smk78** commented:

Removed 3 instances in data_explorer_help.rst
Removed 3 instances in fitting_help.rst
Removed 2 instances in pd_help.rst
Removed 5 instances in invariant_help.rst
Removed 2 instances in pr_help.rst
Removed 5 instances in corfunc_help.rst

**Comment by smk78** [comment]
Trac update at `2016/08/16 16:31:39`: 
* **smk78** changed resolution from "" to "fixed"
* **smk78** changed status from "new" to "closed"
