### ISSUE TITLE
Review User Documentation (Trac #514)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#647]
The User documentation needs to be reviewed for the following:
 * readability
 * does it match the actual functionality (does pressing the button do what it says)

Probably best to do as with models and establish a table of sections to be reviewed with a name assignment and done checkbox column

Migrated from http://trac.sasview.org/ticket/514
```json
{
    "status": "closed",
    "changetime": "2019-03-26T12:57:51",
    "_ts": "2019-03-26 12:57:51.926479+00:00",
    "description": "The User documentation needs to be reviewed for the following:\n * readability\n * does it match the actual functionality (does pressing the button do what it says)\n\nProbably best to do as with models and establish a table of sections to be reviewed with a name assignment and done checkbox column",
    "reporter": "butler",
    "cc": "",
    "resolution": "obsolete",
    "workpackage": "SasView Documentation",
    "time": "2016-03-15T17:11:28",
    "component": "SasView",
    "summary": "Review User Documentation",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView Next Release +1",
    "owner": "",
    "type": "enhancement"
}
```

**Comment by butlerpd** [comment]
Trac update at `2019/03/23 14:53:51`: **butler** commented:

can we close this ticket? It was generated a long time ago when the rst documentation was still being worked on developed.  In some sense this is an unclosable ticket as it will always need doing better, but at this point the docs are pretty complete and even "hefty" and I think we have essentially done what this was intended for and it is unlikely anyone will have the bandwidth to systematically go over everything again?

**Comment by smk78** [comment]
Trac update at `2019/03/26 12:56:40`: **smk78** commented:

I agree. I think at this juncture any specific issues with the user documentation should be the subject of specific tickets. I am therefore closing this one.

**Comment by smk78** [comment]
Trac update at `2019/03/26 12:57:51`: 
* **smk78** changed resolution from "" to "obsolete"
* **smk78** changed status from "new" to "closed"
