### ISSUE TITLE
Add Pr Tutorial module (Trac #516)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#649]
Need to write a P(r) tutorial module.

Migrated from http://trac.sasview.org/ticket/516
```json
{
    "status": "closed",
    "changetime": "2017-04-06T15:15:00",
    "_ts": "2017-04-06 15:15:00.760266+00:00",
    "description": "Need to write a P(r) tutorial module.",
    "reporter": "butler",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Documentation",
    "time": "2016-03-15T17:31:54",
    "component": "SasView",
    "summary": "Add Pr Tutorial module",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView Next Release +1",
    "owner": "",
    "type": "enhancement"
}
```

**Comment by butlerpd** [comment]
Trac update at `2016/03/15 17:44:14`: **butler** changed summary from "Pr Tutorial module" to "Add Pr Tutorial module"

**Comment by smk78** [comment]
Trac update at `2017/04/06 15:15:00`: 
* **smk78** commented:

Superseded by #1010
Ticket closed.


* **smk78** changed resolution from "" to "fixed"
* **smk78** changed status from "new" to "closed"
