### ISSUE TITLE
Add 1D model fitting tutorial (Trac #518)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#651]
As the title says

Migrated from http://trac.sasview.org/ticket/518
```json
{
    "status": "closed",
    "changetime": "2017-04-06T15:15:52",
    "_ts": "2017-04-06 15:15:52.381880+00:00",
    "description": "As the title says",
    "reporter": "butler",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Documentation",
    "time": "2016-03-15T17:38:49",
    "component": "SasView",
    "summary": "Add 1D model fitting tutorial",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView Next Release +1",
    "owner": "",
    "type": "enhancement"
}
```

**Comment by butlerpd** [comment]
Trac update at `2016/03/18 23:12:28`: **butler** changed priority from "blocker" to "critical"

**Comment by butlerpd** [comment]
Trac update at `2016/03/20 23:04:27`: **butler** changed milestone from "SasView 4.0.0" to "SasView Next Release +1"

**Comment by butlerpd** [comment]
Trac update at `2016/03/20 23:04:42`: **butler** changed priority from "critical" to "major"

**Comment by smk78** [comment]
Trac update at `2017/04/06 15:15:52`: 
* **smk78** commented:

Superseded by #1010
Ticket closed.


* **smk78** changed resolution from "" to "fixed"
* **smk78** changed status from "new" to "closed"
