### ISSUE TITLE
Add GUI category defaults to models in sasmodels (Trac #525)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#658]
If we want to make it simpler for developers to provide a default category for their models it has been suggested we add a list of default categories that a model will be associated with by the GUI if it does not find the model in its category json file.  There is a question about whether that is a proper separation between GUI and calculation but as of know is the concensus. 

This will require adding a list attribute to all models.  A separate ticket will be written to alter the category code (manager and installer) which will also be needed for this to work.  This should be a post 4.0 change.

Migrated from http://trac.sasview.org/ticket/525
```json
{
    "status": "closed",
    "changetime": "2017-10-26T11:47:35",
    "_ts": "2017-10-26 11:47:35.185535+00:00",
    "description": "If we want to make it simpler for developers to provide a default category for their models it has been suggested we add a list of default categories that a model will be associated with by the GUI if it does not find the model in its category json file.  There is a question about whether that is a proper separation between GUI and calculation but as of know is the concensus. \n\nThis will require adding a list attribute to all models.  A separate ticket will be written to alter the category code (manager and installer) which will also be needed for this to work.  This should be a post 4.0 change.",
    "reporter": "butler",
    "cc": "",
    "resolution": "wontfix",
    "workpackage": "SasModels Redesign",
    "time": "2016-03-16T22:43:01",
    "component": "SasView",
    "summary": "Add GUI category defaults to models in sasmodels",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.2.0",
    "owner": "butler",
    "type": "enhancement"
}
```

**Comment by ajj** [comment]
Trac update at `2017/04/04 09:26:11`: 
* **ajj** changed milestone from "SasView Next Release +1" to "SasView 4.2.0"
* **ajj** changed owner from "" to "butler"
* **ajj** changed status from "new" to "assigned"

**Comment by butlerpd** [comment]
Trac update at `2017/10/26 11:47:35`: 
* **butler** commented:

This seems to have been superseded as we continue to figure out how to handle category.  Once the new GUI is out we'll see what users find to be usability issues.


* **butler** changed resolution from "" to "wontfix"
* **butler** changed status from "assigned" to "closed"
