### ISSUE TITLE
Refactor SasView Category code (Trac #526)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#659]
Once we move to adding default categories to the python model we will need to change the !SasView category code to take advantage of it.  Mainly:

1 Remove default.json from the repo
2 Change the code to create a serialized.json from model information instead of looking for default.json
3 If model is not in serialized.json, first look in model information for default categories.  If none then, and only then, add to uncategorized.

Migrated from http://trac.sasview.org/ticket/526
```json
{
    "status": "new",
    "changetime": "2019-03-02T01:14:49",
    "_ts": "2019-03-02 01:14:49.765742+00:00",
    "description": "Once we move to adding default categories to the python model we will need to change the !SasView category code to take advantage of it.  Mainly:\n\n1 Remove default.json from the repo\n2 Change the code to create a serialized.json from model information instead of looking for default.json\n3 If model is not in serialized.json, first look in model information for default categories.  If none then, and only then, add to uncategorized.",
    "reporter": "butler",
    "cc": "",
    "resolution": "",
    "workpackage": "SasView Framework Enhancements",
    "time": "2016-03-16T22:53:35",
    "component": "SasView",
    "summary": "Refactor SasView Category code",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 5.0.0",
    "owner": "",
    "type": "enhancement"
}
```

**Comment by butlerpd** [comment]
Trac update at `2016/03/16 22:54:04`: **butler** changed description from:

> Once we move to adding default categories to the python model we will need to change the !SasView category code to take advantage of it.  Mainly:
> 1) Remove default.json from the repo
> 2) Change the code to create a serialized.json from model information instead of looking for default.json
> 3) If model is not in serialized.json, first look in model information for default categories.  If none then, and only then, add to uncategorized.

to:

> Once we move to adding default categories to the python model we will need to change the !SasView category code to take advantage of it.  Mainly:
> 
> 1- Remove default.json from the repo
> 2- Change the code to create a serialized.json from model information instead of looking for default.json
> 3- If model is not in serialized.json, first look in model information for default categories.  If none then, and only then, add to uncategorized.

**Comment by butlerpd** [comment]
Trac update at `2016/03/16 22:54:44`: **butler** changed description from:

> Once we move to adding default categories to the python model we will need to change the !SasView category code to take advantage of it.  Mainly:
> 
> 1- Remove default.json from the repo
> 2- Change the code to create a serialized.json from model information instead of looking for default.json
> 3- If model is not in serialized.json, first look in model information for default categories.  If none then, and only then, add to uncategorized.

to:

> Once we move to adding default categories to the python model we will need to change the !SasView category code to take advantage of it.  Mainly:
> 
> 1 Remove default.json from the repo
> 2 Change the code to create a serialized.json from model information instead of looking for default.json
> 3 If model is not in serialized.json, first look in model information for default categories.  If none then, and only then, add to uncategorized.

**Comment by butlerpd** [comment]
Trac update at `2017/10/26 11:37:58`: 
* **butler** commented:

This may be mostly moot at this point but probably wait for 5.0 to close?


* **butler** changed milestone from "SasView Next Release +1" to "SasView 5.0.0"
* **butler** changed summary from "Refactor !SasView Category code" to "Refactor SasView Category code"

**Comment by butlerpd** [comment]
Trac update at `2019/03/02 01:14:49`: **butler** changed workpackage from "SasModels Redesign" to "SasView Framework Enhancements"

**Comment by pkienzle** [comment]
The refactor is complete so closing the ticket. Opening a new ticket to report current errors.
