### ISSUE TITLE
Add multiplicity model infrastructure to sasmodels (Trac #536)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#669]
sasmodels required for 4.0 does not support multiplicity models yet.  This needs to be done for 4.0 release.

Migrated from http://trac.sasview.org/ticket/536
```json
{
    "status": "closed",
    "changetime": "2016-07-23T05:05:16",
    "_ts": "2016-07-23 05:05:16.275777+00:00",
    "description": "sasmodels required for 4.0 does not support multiplicity models yet.  This needs to be done for 4.0 release.",
    "reporter": "butler",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasModels Redesign",
    "time": "2016-03-19T11:48:55",
    "component": "SasView",
    "summary": "Add multiplicity model infrastructure to sasmodels",
    "priority": "blocker",
    "keywords": "",
    "milestone": "SasView 4.0.0",
    "owner": "pkienzle",
    "type": "task"
}
```

**Comment by butlerpd** [comment]
Trac update at `2016/03/19 11:51:35`: **butler** changed priority from "major" to "blocker"

**Comment by butlerpd** [comment]
Trac update at `2016/03/19 11:53:45`: **butler** changed type from "defect" to "task"

**Comment by butlerpd** [comment]
Trac update at `2016/06/20 22:11:43`: **butler** changed status from "new" to "assigned"

**Comment by pkienzle** [comment]
Trac update at `2016/07/23 05:05:16`: 
* **pkienzle** changed resolution from "" to "fixed"
* **pkienzle** changed status from "assigned" to "closed"
