### ISSUE TITLE
Magnetic sld not implemented for python models (Trac #537)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#670]
this is required for 4.0 to the level of what was possible before

Migrated from http://trac.sasview.org/ticket/537
```json
{
    "status": "closed",
    "changetime": "2018-04-06T19:30:29",
    "_ts": "2018-04-06 19:30:29.901798+00:00",
    "description": "this is required for 4.0 to the level of what was possible before",
    "reporter": "butler",
    "cc": "",
    "resolution": "duplicate",
    "workpackage": "SasModels Redesign",
    "time": "2016-03-19T11:50:17",
    "component": "SasView",
    "summary": "Magnetic sld not implemented for python models",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView Next Release +1",
    "owner": "pkienzle",
    "type": "task"
}
```

**Comment by butlerpd** [comment]
Trac update at `2016/06/20 22:12:58`: **butler** changed status from "new" to "assigned"

**Comment by pkienzle** [comment]
Trac update at `2016/08/08 15:31:23`: 
* **pkienzle** commented:

Magnetism available generically in all C models by treating the result as the incoherent sum of the effective SLD across all spin states assuming that each material has a uniform magnetic field.

This simple magnetism is not available for pure python models yet, so this ticket is left open.


* **pkienzle** changed milestone from "SasView 4.0.0" to "SasView Next Release +1"

**Comment by pkienzle** [comment]
Trac update at `2016/09/10 15:32:21`: 
* **pkienzle** changed priority from "blocker" to "major"
* **pkienzle** changed summary from "Magnetic sld support needed in sasmodels" to "Magnetic sld not implemented for python models"

**Comment by pkienzle** [comment]
Trac update at `2018/04/06 19:30:29`: 
* **pkienzle** commented:

See #1108.


* **pkienzle** changed resolution from "" to "duplicate"
* **pkienzle** changed status from "assigned" to "closed"
