### ISSUE TITLE
Uncertainties for Fits from Bumps CLI (Trac #541)

### ISSUE THREAD

**Issue by rprospero** [SasView/sasview#674]
Currently, SESANS data can be fit to a model through the bumps.cli interface in sasmodels.  This interface is not providing uncertainties for the values of fits.

Migrated from http://trac.sasview.org/ticket/541
```json
{
    "status": "closed",
    "changetime": "2016-06-20T16:07:51",
    "_ts": "2016-06-20 16:07:51.855497+00:00",
    "description": "Currently, SESANS data can be fit to a model through the bumps.cli interface in sasmodels.  This interface is not providing uncertainties for the values of fits.",
    "reporter": "awashington",
    "cc": "",
    "resolution": "worksforme",
    "workpackage": "SESANS Integration",
    "time": "2016-03-19T18:10:27",
    "component": "SasView",
    "summary": "Uncertainties for Fits from Bumps CLI",
    "priority": "critical",
    "keywords": "SESANS",
    "milestone": "SasView 4.0.0",
    "owner": "",
    "type": "defect"
}
```

**Comment by pkienzle** [comment]
Trac update at `2016/06/20 16:07:51`: 
* **pkienzle** commented:

Using --err or --cov the covariance matrix uncertainty will be displayed.  

Dream records MCMC uncertainties in store/model.err.



* **pkienzle** changed resolution from "" to "worksforme"
* **pkienzle** changed status from "new" to "closed"
