### ISSUE TITLE
Get rid of .copy files when happy with docs (Trac #546)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#678]
When we are happy that the !SasView 4.x.x (ie, Sasmodels) model documentation is rendering correctly, Steve's .copy files can be deleted.

Migrated from http://trac.sasview.org/ticket/546
```json
{
    "status": "closed",
    "changetime": "2016-09-13T16:23:25",
    "_ts": "2016-09-13 16:23:25.600111+00:00",
    "description": "When we are happy that the !SasView 4.x.x (ie, Sasmodels) model documentation is rendering correctly, Steve's .copy files can be deleted.",
    "reporter": "smk78",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Documentation",
    "time": "2016-03-20T17:48:16",
    "component": "SasView",
    "summary": "Get rid of .copy files when happy with docs",
    "priority": "critical",
    "keywords": "",
    "milestone": "SasView 4.0.0",
    "owner": "smk78",
    "type": "task"
}
```

**Comment by butlerpd** [comment]
Trac update at `2016/09/05 14:56:35`: 
* **butler** commented:

This may be related to the issue of complete failure to render on Windows when there is no network connection ticket #771?


* **butler** changed priority from "trivial" to "critical"

**Comment by butlerpd** [comment]
Trac update at `2016/09/05 15:03:55`: **butler** changed status from "new" to "assigned"

**Comment by smk78** [comment]
Trac update at `2016/09/13 16:23:14`: **smk78** commented:

Doc *.copy files now removed from sasview and the corfunc branch.

**Comment by smk78** [comment]
Trac update at `2016/09/13 16:23:25`: 
* **smk78** changed resolution from "" to "fixed"
* **smk78** changed status from "assigned" to "closed"
