### ISSUE TITLE
sasmodels docs should not refer to documentation in SasView (Trac #554)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#686]
There is currently at least one place (and probably more) where sasmodels documentation is referencing documentation in !SasView: core_multi_shell references the mag_help document in sasgui/perspectives/fitting fro information on magnetic angles and help.

Need to check all documents for this and decide how to proceed.  For the particular case above, once magnetic models are included we should probably rewrite the help anyway and if necessary could make the magnetic angles pic part of sasmodels ... and in the very worst case refer to the sasmodels docs from with !SasView which would be the correct order of dependencies.

Migrated from http://trac.sasview.org/ticket/554
```json
{
    "status": "closed",
    "changetime": "2018-09-09T08:00:15",
    "_ts": "2018-09-09 08:00:15.015265+00:00",
    "description": "There is currently at least one place (and probably more) where sasmodels documentation is referencing documentation in !SasView: core_multi_shell references the mag_help document in sasgui/perspectives/fitting fro information on magnetic angles and help.\n\nNeed to check all documents for this and decide how to proceed.  For the particular case above, once magnetic models are included we should probably rewrite the help anyway and if necessary could make the magnetic angles pic part of sasmodels ... and in the very worst case refer to the sasmodels docs from with !SasView which would be the correct order of dependencies.",
    "reporter": "butler",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Documentation",
    "time": "2016-03-24T10:53:42",
    "component": "SasView",
    "summary": "sasmodels docs should not refer to documentation in SasView",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView Next Release +1",
    "owner": "ajj",
    "type": "defect"
}
```

**Comment by smk78** [comment]
Trac update at `2016/03/24 12:17:55`: **smk78** commented:

Actually, core_multi_shell is the only sasmodel that references /sasgui (I just searched in Eclipse).

**Comment by smk78** [comment]
Trac update at `2016/03/24 12:23:45`: **smk78** commented:

**The more important issue** here is that at present (due to time and intelligence constraints) the sasmodels docs **''must''** be built **''before''** the sasview docs in order for integrated documentation to be built correctly because it copies down the pre-assembled .rst model help files from sasmodels.

As part of the next release the sasview doc build needs to be updated to trawl the sasmodels files directly as happens in the sasmodels docs build.

**Comment by butlerpd** [comment]
Trac update at `2016/03/26 16:49:49`: **butler** commented:

Agreed that the current set up is not ideal but not sure what the correct answer will be once sasmodels is properly released as a package.  

In any case however this is only an inconvenience.  The original issue actually **breaks** sasmodels for any application beyond !SasView that wants to use sasmodels with its docs.  Because it is not yet released fully as a package there is nobody else, but we already know of one package that **IS** using the old sasmodels and very much wants the new package.

Thus I would argue the *more important issue* remains the first one mentioned which essentially is, I think, a violation of proper coding rules, though clearly both issues should be addressed.

**Comment by butlerpd** [comment]
Trac update at `2016/03/26 17:05:51`: **butler** commented:

On reviewing I think we are starting to confuse ourselves between sasmodels and !SasView.  This ticket was meant clearly as a sasmodels ticket whereas the second concern is really a !SasView issue. Probably should add a new component to trac named sasmodels.  In the meantime am moving the issue of needing to build the sasmodels before building !SasView to ticket #687 which is the !SasView package building ticket.

Once sasmodels no longer relies on !SasView this ticket can be closed.

**Comment by smk78** [comment]
Trac update at `2016/03/29 16:32:37`: **smk78** commented:

Have committed 4 additional (to core_multi_shell.py) changes (to fix broken links to polar_mag_help.html which doesn't exist) in sasmodels:

sphere.py
_spherepy.py
fuzzy_sphere.py
multilayer_vesicle.py

This further exacerbates the problem with sasmodels docs not being standalone (but does mean the integrated docs will link properly).

**Comment by ajj** [comment]
Trac update at `2016/10/07 00:49:18`: 
* **ajj** changed owner from "" to "ajj"
* **ajj** changed status from "new" to "assigned"

**Comment by smk78** [comment]
Trac update at `2018/09/09 07:59:14`: **smk78** commented:

Replaced link to mag_help.rst in sasview with link to magnetism.rst in sasmodels in _spherepy.py

**Comment by smk78** [comment]
Trac update at `2018/09/09 08:00:15`: 
* **smk78** commented:

As far as I can tell, sasmodels documentation should now be independent of sasview so am closing this ticket.


* **smk78** changed resolution from "" to "fixed"
* **smk78** changed status from "assigned" to "closed"
