### ISSUE TITLE
build_sphinx.py needs cleanup (Trac #555)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#687]
The build module should properly cleanout everything before rebuilding.  Also if a destination directory does not exist it should be created.  Currently there are several instances of checking for existence but failing to create if not true -- the script just goes on happily to next if statement leaving no message of why the end product cannot build properly.  It should also exclude irrelevant files from the document scrapping (such as setup.exe and setup.mac). Finally, the current build script for 4.0 copies down the pre-assembled .rst model help files from sasmodels package so that one must make sure to *first* build the sasmodels docs before building the !SasView docs in order for integrated documentation to be built correctly. In the future this should not be a required step every time one builds the !SasView docs.

There may be other things as well which should be added to this ticket as they become known - note that sasmodel package specific issues should be reported in separate tickets.

Migrated from http://trac.sasview.org/ticket/555
```json
{
    "status": "closed",
    "changetime": "2018-03-04T17:11:48",
    "_ts": "2018-03-04 17:11:48.613282+00:00",
    "description": "The build module should properly cleanout everything before rebuilding.  Also if a destination directory does not exist it should be created.  Currently there are several instances of checking for existence but failing to create if not true -- the script just goes on happily to next if statement leaving no message of why the end product cannot build properly.  It should also exclude irrelevant files from the document scrapping (such as setup.exe and setup.mac). Finally, the current build script for 4.0 copies down the pre-assembled .rst model help files from sasmodels package so that one must make sure to *first* build the sasmodels docs before building the !SasView docs in order for integrated documentation to be built correctly. In the future this should not be a required step every time one builds the !SasView docs.\n\nThere may be other things as well which should be added to this ticket as they become known - note that sasmodel package specific issues should be reported in separate tickets.",
    "reporter": "butler",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Documentation",
    "time": "2016-03-24T10:59:10",
    "component": "SasView",
    "summary": "build_sphinx.py needs cleanup",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.1.1",
    "owner": "ajj",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2016/03/24 11:04:20`: **butler** changed description from "The build module should properly cleanout everything before rebuilding.  Also if a destination directory does not exist it should be created.  Currently there are several instances of checking for existence but failing to create if not true -- the script just goes on happily to next if statement leaving no message of why the end product cannot build properly.  There may be other things as well." to "The build module should properly cleanout everything before rebuilding.  Also if a destination directory does not exist it should be created.  Currently there are several instances of checking for existence but failing to create if not true -- the script just goes on happily to next if statement leaving no message of why the end product cannot build properly.  Finally it should exclude irrelevant files from the document scrapping (such as setup.exe and setup.mac). There may be other things as well."

**Comment by smk78** [comment]
Trac update at `2016/03/24 12:10:15`: **smk78** commented:

I think this ticket is referring to a number of tests I put in whilst trying to integrate the sasmodels docs. Trying to figure out paths was a nightmare!

Yes the build is ugly now. But the relevant build folders were/are cleaned out before the build, and I haven't seen any builds failing because of a missing folder. Do you have an example???

I've no idea why setup_exe and setup_mac are being touched.

But as #686 says there needs to a more strategic overview of how things are arranged and sorting out build_sphinx will be part of that.

So I kinda think this ticket is redundant?

**Comment by butlerpd** [comment]
Trac update at `2016/03/26 17:14:42`: **butler** changed description from:

> The build module should properly cleanout everything before rebuilding.  Also if a destination directory does not exist it should be created.  Currently there are several instances of checking for existence but failing to create if not true -- the script just goes on happily to next if statement leaving no message of why the end product cannot build properly.  Finally it should exclude irrelevant files from the document scrapping (such as setup.exe and setup.mac). There may be other things as well.

to:

> The build module should properly cleanout everything before rebuilding.  Also if a destination directory does not exist it should be created.  Currently there are several instances of checking for existence but failing to create if not true -- the script just goes on happily to next if statement leaving no message of why the end product cannot build properly.  It should also exclude irrelevant files from the document scrapping (such as setup.exe and setup.mac). Finally, the current build script for 4.0 copies down the pre-assembled .rst model help files from sasmodels package so that one must make sure to *first* build the sasmodels docs before building the !SasView docs in order for integrated documentation to be built correctly. In the future this should not be a required step every time one builds the !SasView docs.
> 
> There may be other things as well which should be added to this ticket as they become known - note that sasmodel package specific issues should be reported in separate tickets.

**Comment by butlerpd** [comment]
Trac update at `2016/03/26 17:16:00`: **butler** commented:

The main part of the ticket has now been edited as has ticket #686 to clarify the difference between this tickets (one is a sasmodels ticket the other a !SasView ticket.

**Comment by ajj** [comment]
Trac update at `2016/10/07 00:49:04`: 
* **ajj** changed owner from "" to "ajj"
* **ajj** changed status from "new" to "assigned"

**Comment by butlerpd** [comment]
Trac update at `2018/03/04 17:11:48`: **butler** changed milestone from "SasView Next Release +1" to "SasView 4.1.1"
