### ISSUE TITLE
set reasonable min/max on polydispersity values for fit (Trac #558)

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#690]
polydispersity cannot be negative, so set the min to 0.

relative polydispersity doesn't make a lot of sense above 1 (thickness of 30 +/- 200%?)

Migrated from http://trac.sasview.org/ticket/558
```json
{
    "status": "new",
    "changetime": "2017-10-27T10:49:46",
    "_ts": "2017-10-27 10:49:46.234557+00:00",
    "description": "polydispersity cannot be negative, so set the min to 0.\n\nrelative polydispersity doesn't make a lot of sense above 1 (thickness of 30 +/- 200%?)\n\n",
    "reporter": "pkienzle",
    "cc": "",
    "resolution": "",
    "workpackage": "SasView Bug Fixing",
    "time": "2016-04-12T15:20:28",
    "component": "SasView",
    "summary": "set reasonable min/max on polydispersity values for fit",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 5.0.0",
    "owner": "",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2016/08/16 14:30:21`: 
* **butler** commented:

sasmodels apparently has default limits but GUI does not pick those up.  This would be very useful but changing the GUI at this point is probably not realistic for release 4.0.  Moving to next +1


* **butler** changed milestone from "SasView 4.0.0" to "SasView Next Release +1"

**Comment by butlerpd** [comment]
Trac update at `2017/10/27 10:49:46`: **butler** changed milestone from "SasView Next Release +1" to "SasView 5.0.0"

**Comment by rozyczko** [comment]
5.0 uses param.limits[0] and param.limits[1] to display parameter limits. Is this the correct attribute for polydispersity values as well?

**Comment by pkienzle** [comment]
polydispersity limits will be different from param limits.  For shape parameters, [0, 1] are reasonable default limits.  For orientation parameters [0, 90] would be more appropriate defaults.

**Comment by butlerpd** [comment]
but aren't those defined in sasmodels? if so then the GUI just needs to read them and display?

**Comment by pkienzle** [comment]
Here's the code in the sasview wrapper which sets the defaults:
    https://github.com/SasView/sasmodels/blob/ed3ea824726b2ec0c941f6c7dedd5895bc052570/sasmodels/sasview_model.py#L421-L430

It sets [0, inf] for orientation parameters rather than [0, 90], but that's easy to change if we want to.

If you change the following to use `param_name + '.width'` then the polydispersity tab will show the defaults:

https://github.com/SasView/sasview/blob/4c71a09d1783fd89cf83e9d9ba7dd48f8ba0c987/src/sas/qtgui/Perspectives/Fitting/FittingWidget.py#L3056

Trying it with latex_smeared test data set (fit to sphere with radius around 2100 as a starting point):

1) Plots are hard to read on mac (legends are huge, data is pushed to one side, they keep popping above the fit like whack-a-mole)

2) slit-smearing isn't working

3) polydispersity isn't fit unless it is set to something != 0 first

4) The data displayed for PD on the model tab is broken.  It doesn't show the initial min/max values. Each time a new fit is done the "error-min-max-units" columns shift one to the right.

**Comment by rozyczko** [comment]
Changed FittingWidget.py as shown.

**Comment by rozyczko** [comment]
2., 3. and 4. fixed and pushed to ESS_GUI.

**Comment by rozyczko** [comment]
as for 1. seems related to the matplotlib version. Which version did you use for your testing? Was it a local build or did you run the jenkins built binary?

**Comment by pkienzle** [comment]
2.2.2 from local build; I cleared out my ~/.matplotlib and ~/.sasview/matplotlib directories first.

**Comment by rozyczko** [comment]
spun off 1. into a separate bug.

**Comment by rozyczko** [comment]
Original issue has been fixed. Can we close this?

**Comment by rozyczko** [comment]
Please review the above
