### ISSUE TITLE
Update check_packages to flag required package versions (Trac #565)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#697]
check_packages could be made to flag when the installed packages (eg, bumps) do not meet the minimum version number necessary for a successful build.

Migrated from http://trac.sasview.org/ticket/565
```json
{
    "status": "accepted",
    "changetime": "2019-03-23T14:18:31",
    "_ts": "2019-03-23 14:18:31.048786+00:00",
    "description": "check_packages could be made to flag when the installed packages (eg, bumps) do not meet the minimum version number necessary for a successful build.",
    "reporter": "smk78",
    "cc": "",
    "resolution": "",
    "workpackage": "Support Infrastructure",
    "time": "2016-04-26T15:24:42",
    "component": "SasView",
    "summary": "Update check_packages to flag required package versions",
    "priority": "critical",
    "keywords": "",
    "milestone": "Admin Tasks",
    "owner": "tim",
    "type": "enhancement"
}
```

**Comment by ajj** [comment]
Trac update at `2016/08/16 13:47:20`: **ajj** changed milestone from "SasView 4.0.0" to "SasView Next Release +1"

**Comment by butlerpd** [comment]
Trac update at `2019/02/26 14:30:58`: 
* **butler** changed milestone from "SasView Next Release +1" to "Admin Tasks"
* **butler** changed workpackage from "SasView Admin" to "Support Infrastructure"

**Comment by butlerpd** [comment]
Trac update at `2019/03/23 14:18:31`: **butler** changed priority from "major" to "critical"

**Comment by timsnow** [comment]
So, whilst the idea being floated yesterday is a good one, how do we think we can go about picking the right YAML file to interrogate?
