### ISSUE TITLE
SasView 4.0-alpha: problem selecting polydispersity functions (Trac #567)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#699]
Using a locally-built !SasView 4.0-alpha on W7.

When I try and select a polydispersity distribution I get an error popup:

Error occurred: Could not select the distribution function. Please select another.

Except you get this for all distributions.

Same message echoed in the console.

sasview log file says:

2016-04-26 16:02:31,496 ERROR u'length.width'
2016-04-26 16:02:31,496 ERROR Error occurred: Could not select the distribution function... Please select another distribution function.
2016-04-26 16:02:43,895 ERROR u'radius.width'
2016-04-26 16:02:43,895 ERROR Error occurred: Could not select the distribution function... Please select another distribution function.
2016-04-26 16:02:47,243 ERROR u'radius.width'
2016-04-26 16:02:47,243 ERROR Error occurred: Could not select the distribution function... Please select another distribution function.
2016-04-26 16:02:51,124 ERROR u'length.width'
2016-04-26 16:02:51,124 ERROR Error occurred: Could not select the distribution function... Please select another distribution function.

Migrated from http://trac.sasview.org/ticket/567
```json
{
    "status": "closed",
    "changetime": "2016-07-02T20:55:28",
    "_ts": "2016-07-02 20:55:28.830366+00:00",
    "description": "Using a locally-built !SasView 4.0-alpha on W7.\n\nWhen I try and select a polydispersity distribution I get an error popup:\n\nError occurred: Could not select the distribution function. Please select another.\n\nExcept you get this for all distributions.\n\nSame message echoed in the console.\n\nsasview log file says:\n\n2016-04-26 16:02:31,496 ERROR u'length.width'\n2016-04-26 16:02:31,496 ERROR Error occurred: Could not select the distribution function... Please select another distribution function.\n2016-04-26 16:02:43,895 ERROR u'radius.width'\n2016-04-26 16:02:43,895 ERROR Error occurred: Could not select the distribution function... Please select another distribution function.\n2016-04-26 16:02:47,243 ERROR u'radius.width'\n2016-04-26 16:02:47,243 ERROR Error occurred: Could not select the distribution function... Please select another distribution function.\n2016-04-26 16:02:51,124 ERROR u'length.width'\n2016-04-26 16:02:51,124 ERROR Error occurred: Could not select the distribution function... Please select another distribution function.\n",
    "reporter": "smk78",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2016-04-26T16:41:21",
    "component": "SasView",
    "summary": "SasView 4.0-alpha: problem selecting polydispersity functions",
    "priority": "blocker",
    "keywords": "",
    "milestone": "SasView 4.0.0",
    "owner": "pkienzle",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2016/06/19 23:50:57`: **butler** changed description from:

> Using a locally-built SasView 4.0-alpha on W7.
> 
> When I try and select a polydispersity distribution I get an error popup:
> 
> Error occurred: Could not select the distribution function. Please select another.
> 
> Except you get this for all distributions.
> 
> Same message echoed in the console.
> 
> sasview log file says:
> 
> 2016-04-26 16:02:31,496 ERROR u'length.width'
> 2016-04-26 16:02:31,496 ERROR Error occurred: Could not select the distribution function... Please select another distribution function.
> 2016-04-26 16:02:43,895 ERROR u'radius.width'
> 2016-04-26 16:02:43,895 ERROR Error occurred: Could not select the distribution function... Please select another distribution function.
> 2016-04-26 16:02:47,243 ERROR u'radius.width'
> 2016-04-26 16:02:47,243 ERROR Error occurred: Could not select the distribution function... Please select another distribution function.
> 2016-04-26 16:02:51,124 ERROR u'length.width'
> 2016-04-26 16:02:51,124 ERROR Error occurred: Could not select the distribution function... Please select another distribution function.
> 

to:

> Using a locally-built !SasView 4.0-alpha on W7.
> 
> When I try and select a polydispersity distribution I get an error popup:
> 
> Error occurred: Could not select the distribution function. Please select another.
> 
> Except you get this for all distributions.
> 
> Same message echoed in the console.
> 
> sasview log file says:
> 
> 2016-04-26 16:02:31,496 ERROR u'length.width'
> 2016-04-26 16:02:31,496 ERROR Error occurred: Could not select the distribution function... Please select another distribution function.
> 2016-04-26 16:02:43,895 ERROR u'radius.width'
> 2016-04-26 16:02:43,895 ERROR Error occurred: Could not select the distribution function... Please select another distribution function.
> 2016-04-26 16:02:47,243 ERROR u'radius.width'
> 2016-04-26 16:02:47,243 ERROR Error occurred: Could not select the distribution function... Please select another distribution function.
> 2016-04-26 16:02:51,124 ERROR u'length.width'
> 2016-04-26 16:02:51,124 ERROR Error occurred: Could not select the distribution function... Please select another distribution function.
>

**Comment by butlerpd** [comment]
Trac update at `2016/06/20 00:05:50`: **butler** commented:

This is also true for the alpha 2 release downloaded from github.  Tried on windows 10 and Mac yosemite (10.9).  Thus polydispersity is broken for the user.  Clearly a blocker.

If I hit fit however it does seem to do something smeared (where is it getting the distribution?).  Moreover if I turn polydispersity off after having hit fit and hit fit again bumps seems to throw a traceback error.  Should investigate once the main problem is resolved.  If still a problem should open a new ticket to deal with.

**Comment by butlerpd** [comment]
Trac update at `2016/07/02 20:54:52`: 
* **butler** changed owner from "" to "pkienzle"
* **butler** changed status from "new" to "assigned"

**Comment by butlerpd** [comment]
Trac update at `2016/07/02 20:55:28`: 
* **butler** commented:

Paul Kienzle fixed this for NIST summer school


* **butler** changed resolution from "" to "fixed"
* **butler** changed status from "assigned" to "closed"
