### ISSUE TITLE
revise embedded C handling in sasmodels (Trac #569)

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#701]
Remove the Iq="""... function body ...""" option from sasmodels.

This makes for cleaner code since we don't have to test whether Iq exists, and if so, whether it is a string or a callable.

Those who can program in C are surprised by the missing function declaration.  Those who don't know C are going to be surprised that the tutorials for writing C functions include the function definition, but they don't have to.

Instead use c_include=["list", "of", "sources"] and optional c_source="""extra source after the included sources""".

Because c_source contains top-level C code rather than just the function body, this means we can define helper functions in single file model files, which we otherwise cannot do in the current system.

A custom model

```text
    def form_volume(...): ...
    def Iq(q, ...): ...
    def Iqxy(qx, qy, ...): ...
```
becomes

```text
    c_source = """
    static double form_volume(...) { ...; }
    static double Iq(double q, ...) { ...; }
    static double Iqxy(double qx, double qy, ...) { ...; }
    """
```

This is a reasonably natural transformation for someone who knows both C and python.

If the C source is later moved into model.c (so that you can edit it with C syntax highlighting), this becomes

```text
c_include=["model.c"]
```

The main advantage of the existing scheme, which is that the parameters in the function definition are automatically generated for the C code in the correct order from the parameter table, is not a big advantage in sasview since the New Model dialog creates the python definitions with the correct parameters already, and that can be easily edited.

Migrated from http://trac.sasview.org/ticket/569
```json
{
    "status": "closed",
    "changetime": "2018-11-16T02:09:03",
    "_ts": "2018-11-16 02:09:03.212834+00:00",
    "description": "Remove the Iq=\"\"\"... function body ...\"\"\" option from sasmodels.\n\nThis makes for cleaner code since we don't have to test whether Iq exists, and if so, whether it is a string or a callable.\n\nThose who can program in C are surprised by the missing function declaration.  Those who don't know C are going to be surprised that the tutorials for writing C functions include the function definition, but they don't have to.\n\nInstead use c_include=[\"list\", \"of\", \"sources\"] and optional c_source=\"\"\"extra source after the included sources\"\"\".\n\nBecause c_source contains top-level C code rather than just the function body, this means we can define helper functions in single file model files, which we otherwise cannot do in the current system.\n\nA custom model\n{{{\n    def form_volume(...): ...\n    def Iq(q, ...): ...\n    def Iqxy(qx, qy, ...): ...\n}}}\nbecomes\n{{{\n    c_source = \"\"\"\n    static double form_volume(...) { ...; }\n    static double Iq(double q, ...) { ...; }\n    static double Iqxy(double qx, double qy, ...) { ...; }\n    \"\"\"\n}}}\n\nThis is a reasonably natural transformation for someone who knows both C and python.\n\nIf the C source is later moved into model.c (so that you can edit it with C syntax highlighting), this becomes\n{{{\nc_include=[\"model.c\"]\n}}}\n\nThe main advantage of the existing scheme, which is that the parameters in the function definition are automatically generated for the C code in the correct order from the parameter table, is not a big advantage in sasview since the New Model dialog creates the python definitions with the correct parameters already, and that can be easily edited.",
    "reporter": "pkienzle",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2016-05-02T23:54:17",
    "component": "SasView",
    "summary": "revise embedded C handling in sasmodels",
    "priority": "minor",
    "keywords": "",
    "milestone": "SasView 4.2.0",
    "owner": "",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2016/06/26 17:26:33`: 
* **butler** commented:

As agreed on fortnightly call of June 21, am moving all minor priority tickets to next release (+1) given the resources and time available to get this release out.


* **butler** changed milestone from "SasView 4.0.0" to "SasView Next Release +1"

**Comment by pkienzle** [comment]
Trac update at `2018/11/15 16:23:01`: 
* **pkienzle** commented:

Added as `c_code=...` on 2017-12-14.


* **pkienzle** changed resolution from "" to "fixed"
* **pkienzle** changed status from "new" to "closed"

**Comment by butlerpd** [comment]
Trac update at `2018/11/16 02:09:03`: **butler** changed milestone from "SasView Next Release +1" to "SasView 4.2.0"
