### ISSUE TITLE
better custom model error diagnostics (Trac #570)

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#702]
When defining a custom model but having a bad parameter table, the custom model compile menu item claimed that the model loaded without difficulty.  Similarly when there were errors in the C code for the model.

The compile button needs to run the model with some nominal value (e.g., Iq([0.1, 0.2, 0.3]) and Iqxy([0.1, 0.2, 0.3], [0.1, 0.2, 0.3]) to make sure that the model runs with the default parameters.  Any errors returned by the compiler should be displayed.

Check that errors are captured and returned for bad opencl models on the various OpenCL environments (mac GPU, mac CPU, windows nvidia, windows radeon, windows intel) and for kerneldll under windows with the tcc compiler.

For pure python models, check that python code with Iq.vectorized=True but if statements in the code shows the correct errors.

These tests belong in the sasmodels package.  Make sure that the appropriate compiler output gets captured as part of the test.  The sasview gui only needs to demonstrate that bad output gets displayed to the user, but does not need to run the tests as part of the test suite.

Migrated from http://trac.sasview.org/ticket/570
```json
{
    "status": "new",
    "changetime": "2016-08-16T16:49:22",
    "_ts": "2016-08-16 16:49:22.954125+00:00",
    "description": "When defining a custom model but having a bad parameter table, the custom model compile menu item claimed that the model loaded without difficulty.  Similarly when there were errors in the C code for the model.\n\nThe compile button needs to run the model with some nominal value (e.g., Iq([0.1, 0.2, 0.3]) and Iqxy([0.1, 0.2, 0.3], [0.1, 0.2, 0.3]) to make sure that the model runs with the default parameters.  Any errors returned by the compiler should be displayed.\n\nCheck that errors are captured and returned for bad opencl models on the various OpenCL environments (mac GPU, mac CPU, windows nvidia, windows radeon, windows intel) and for kerneldll under windows with the tcc compiler.\n\nFor pure python models, check that python code with Iq.vectorized=True but if statements in the code shows the correct errors.\n\nThese tests belong in the sasmodels package.  Make sure that the appropriate compiler output gets captured as part of the test.  The sasview gui only needs to demonstrate that bad output gets displayed to the user, but does not need to run the tests as part of the test suite.\n",
    "reporter": "pkienzle",
    "cc": "",
    "resolution": "",
    "workpackage": "SasView Bug Fixing",
    "time": "2016-05-03T21:13:02",
    "component": "SasView",
    "summary": "better custom model error diagnostics",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView Next Release +1",
    "owner": "",
    "type": "defect"
}
```

**Comment by pkienzle** [comment]
Trac update at `2016/05/05 00:53:01`: **pkienzle** commented:

Errors will be easier to debug if we have the correct file number and line number.  The #line compiler directive may help in this regard.

**Comment by pkienzle** [comment]
Trac update at `2016/05/21 02:25:17`: **pkienzle** commented:

Models are tested and errors are displayed, but this has not yet been tested on all platforms.

**Comment by pkienzle** [comment]
Trac update at `2016/07/05 12:04:53`: **pkienzle** commented:

I've had a syntax error in C code crash SasView when running OpenCL on a GPU on Windows.  Not sure which GPU it was.  Perhaps the model test could be run in a separate process so we can trap this kind of error?

**Comment by butlerpd** [comment]
Trac update at `2016/08/16 16:49:22`: 
* **butler** commented:

Don't have bandwidth to deal with for 4.0 release which is already way way late.  Moving to +1


* **butler** changed milestone from "SasView 4.0.0" to "SasView Next Release +1"
