### ISSUE TITLE
better support for custom model editing (Trac #571)

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#703]
As part of the debug process the model file will frequently be saved and edited.  Having to reselect the model and reenter the parameters each time is tedious.

Users may be editing models with their own editor outside of sasview.  There is no way to signal that the model needs to be updated.

Both issues could be avoided if the Compute button checks for updates to the model file before running compute, possibly replacing the model with a newer version and displaying any errors with the reload process.  Copy the existing values for the parameters to the newly loaded model for all parameters which match.

Migrated from http://trac.sasview.org/ticket/571
```json
{
    "status": "new",
    "changetime": "2017-10-27T10:52:42",
    "_ts": "2017-10-27 10:52:42.926809+00:00",
    "description": "As part of the debug process the model file will frequently be saved and edited.  Having to reselect the model and reenter the parameters each time is tedious.\n\nUsers may be editing models with their own editor outside of sasview.  There is no way to signal that the model needs to be updated.\n\nBoth issues could be avoided if the Compute button checks for updates to the model file before running compute, possibly replacing the model with a newer version and displaying any errors with the reload process.  Copy the existing values for the parameters to the newly loaded model for all parameters which match.",
    "reporter": "pkienzle",
    "cc": "",
    "resolution": "",
    "workpackage": "SasView Bug Fixing",
    "time": "2016-05-03T21:27:21",
    "component": "SasView",
    "summary": "better support for custom model editing",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 5.1.0",
    "owner": "",
    "type": "enhancement"
}
```

**Comment by ajj** [comment]
Trac update at `2016/08/16 13:46:16`: **ajj** changed milestone from "SasView 4.0.0" to "SasView Next Release +1"

**Comment by butlerpd** [comment]
Trac update at `2017/10/27 10:52:42`: **butler** changed milestone from "SasView Next Release +1" to "SasView 5.1.0"
