### ISSUE TITLE
allow user to control where to run the model (Trac #572)

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#704]
We need to be able to control where the model is run from within sasview (GPU vs. CPU). On lower end GPUs and bigger models the code may run very slowly or even segmentation fault.  We saw this with the Hayter MSA kernel but got around it by setting single=False (which happens to be necessary for this model).  This worked because older lower end hardware doesn't support double precision, but may not work if users write complicated models that fail in double precision on higher end hardware.

At a minimum we need to be able to shut off GPU processing for the sasview installation if the hardware doesn't even support single precision models.  The Intel HD 3000 chipset on older macbooks for example will have this problem for some models. Controlling this on a per-model basis might be useful, especially if we can query the GPU capabilities and estimate the model complexity so that good defaults appear automatically.

This is a major bug since a user defined model might crash the program if run on the GPU, and they currently have no easy way to get around it.  Setting the PYOPENCL_CTX environment variable would work but is not easy for the user and interferes with other programs.

Migrated from http://trac.sasview.org/ticket/572
```json
{
    "status": "closed",
    "changetime": "2016-09-22T10:01:04",
    "_ts": "2016-09-22 10:01:04.690419+00:00",
    "description": "We need to be able to control where the model is run from within sasview (GPU vs. CPU). On lower end GPUs and bigger models the code may run very slowly or even segmentation fault.  We saw this with the Hayter MSA kernel but got around it by setting single=False (which happens to be necessary for this model).  This worked because older lower end hardware doesn't support double precision, but may not work if users write complicated models that fail in double precision on higher end hardware.\n\nAt a minimum we need to be able to shut off GPU processing for the sasview installation if the hardware doesn't even support single precision models.  The Intel HD 3000 chipset on older macbooks for example will have this problem for some models. Controlling this on a per-model basis might be useful, especially if we can query the GPU capabilities and estimate the model complexity so that good defaults appear automatically.\n\nThis is a major bug since a user defined model might crash the program if run on the GPU, and they currently have no easy way to get around it.  Setting the PYOPENCL_CTX environment variable would work but is not easy for the user and interferes with other programs.\n\n\n",
    "reporter": "pkienzle",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2016-05-07T00:05:29",
    "component": "SasView",
    "summary": "allow user to control where to run the model",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.0.0",
    "owner": "wojciech",
    "type": "defect"
}
```

**Comment by pkienzle** [comment]
Trac update at `2016/05/07 00:40:51`: **pkienzle** commented:

We may want to default to only using the GPU if it is in a list of known good devices, otherwise the user will have to activate it themselves.

For custom models, setting GPU=False in the model definition may be good enough.  The user controls the model and the device it is running on.  This means we don't have to have extra clutter in the GUI.

We may be able to give a device a rating based on the opencl info such as LOCAL_MEM_SIZE, GLOBAL_MEM_SIZE, MAX_COMPUTE_UNITS, MAX_CLOCK_FREQUENCY; we may be able to give the code a rating by looking at code size and number of parameters and measuring how long it takes to run on the CPU; still need the amount of local memory per thread to make a good decision.

**Comment by wpotrzebowski** [comment]
Trac update at `2016/08/09 09:15:32`: 
* **wojciech** changed owner from "" to "wojciech"
* **wojciech** changed status from "new" to "assigned"

**Comment by wpotrzebowski** [comment]
Trac update at `2016/09/12 07:17:14`: **wojciech** commented:

The issue seems to be resolved. I need to update documentation and link it properly to close the ticket. At the moment the documentation resides in: sasmodels/doc/ref/compilation.rst

**Comment by wpotrzebowski** [comment]
Trac update at `2016/09/22 10:00:52`: **wojciech** commented:

The relevant documentation is in SasView user section. sasview/docs/sphinx-docs/source/user/gpu_coputations.rst and sasview/docs/sphinx-docs/source/user/opencl_installation.rst

**Comment by wpotrzebowski** [comment]
Trac update at `2016/09/22 10:01:04`: 
* **wojciech** changed resolution from "" to "fixed"
* **wojciech** changed status from "assigned" to "closed"
