### ISSUE TITLE
make model help available for custom models (Trac #574)

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#706]
Documentation for custom models does not currently appear in sasview help.

Using docutils, we can convert docstrings on the fly to html.

The basic mechanics are easy:

```#!python
from docutils import core
def convert(rst):
    # use replace_dollar from docs/_extensions/dollarmath.py
    # or configure mathjax to convert values between $$ to math
    rst = replace_dollar(rst)  
    parts = core.publish_parts(source=rst, writer_name='html')
    return parts['whole']
```

There will be some work required to get everything pretty, including proper style sheets and references to images.  Also, we won't want to produce the theory plots on the fly every time so they will need to be cached.

Migrated from http://trac.sasview.org/ticket/574
```json
{
    "status": "new",
    "changetime": "2018-09-09T19:06:41",
    "_ts": "2018-09-09 19:06:41.845014+00:00",
    "description": "Documentation for custom models does not currently appear in sasview help.\n\nUsing docutils, we can convert docstrings on the fly to html.\n\nThe basic mechanics are easy:\n\n{{{#!python\nfrom docutils import core\ndef convert(rst):\n    # use replace_dollar from docs/_extensions/dollarmath.py\n    # or configure mathjax to convert values between $$ to math\n    rst = replace_dollar(rst)  \n    parts = core.publish_parts(source=rst, writer_name='html')\n    return parts['whole']\n}}}\n\nThere will be some work required to get everything pretty, including proper style sheets and references to images.  Also, we won't want to produce the theory plots on the fly every time so they will need to be cached.\n",
    "reporter": "pkienzle",
    "cc": "",
    "resolution": "",
    "workpackage": "SasView Bug Fixing",
    "time": "2016-05-17T22:22:21",
    "component": "SasView",
    "summary": "make model help available for custom models",
    "priority": "minor",
    "keywords": "",
    "milestone": "SasView Next Release +1",
    "owner": "",
    "type": "enhancement"
}
```

**Comment by pkienzle** [comment]
Trac update at `2016/05/18 18:20:47`: 
* **pkienzle** changed attachment from "" to "rst2html.py"
* **pkienzle** commented:

module to perform rst to html conversion

**Comment by pkienzle** [comment]
Trac update at `2017/02/01 21:58:31`: **pkienzle** commented:

rst2html has been added to sasmodels.

However, sphinx has replaced the math directive with its own version, so either we need to pull the sphinx extensions into rst2html or we need to include sphinx as a distribution dependency and figure out how to call docutils with sphinx directives.

Also, we should ship the js rendering code.  Khan academy has a faster, smaller renderer which we may want to use for this.  Ideally, we would also support it through sphinx so that we only have to debug our latex equations once.

**Comment by pkienzle** [comment]
Trac update at `2017/02/01 23:40:21`: **pkienzle** commented:

May want to switch from latex markup to asciimath; this format looks cleaner in the docs, and may be easier to write.  

Need to try asciimath with some more complicated formulas, such as the ones in spherical_sld.py.

**Comment by pkienzle** [comment]
Trac update at `2018/09/09 19:06:41`: **pkienzle** commented:

Product and composition models will also need doc strings.

**Comment by krzywon** [comment]
This was part of #2576. Closing
