### ISSUE TITLE
support simultaneous install of different versions (Trac #577)

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#709]
Particularly for users who are testing new features before they are released, it would be convenient to be able to install multiple versions of !SasView at the same time.

Pre-release versions should be marked with the date and the git key so that we know which version has errors and how old it is.

Migrated from http://trac.sasview.org/ticket/577
```json
{
    "status": "new",
    "changetime": "2017-10-27T10:57:37",
    "_ts": "2017-10-27 10:57:37.555154+00:00",
    "description": "Particularly for users who are testing new features before they are released, it would be convenient to be able to install multiple versions of !SasView at the same time.\n\nPre-release versions should be marked with the date and the git key so that we know which version has errors and how old it is.",
    "reporter": "pkienzle",
    "cc": "",
    "resolution": "",
    "workpackage": "SasView Bug Fixing",
    "time": "2016-05-23T16:58:11",
    "component": "SasView",
    "summary": "support simultaneous install of different versions",
    "priority": "minor",
    "keywords": "",
    "milestone": "SasView Next Release +1",
    "owner": "",
    "type": "enhancement"
}
```

**Comment by pkienzle** [comment]
Trac update at `2016/05/23 16:58:20`: **pkienzle** changed priority from "major" to "minor"

**Comment by pkienzle** [comment]
Trac update at `2016/05/27 16:52:46`: **pkienzle** commented:

Make sure configuration files, precompiled models, etc. don't collide between versions.

**Comment by butlerpd** [comment]
Trac update at `2017/10/27 10:57:37`: **butler** changed description from:

> Particularly for users who are testing new features before they are released, it would be convenient to be able to install multiple versions of SasView at the same time.
> 
> Pre-release versions should be marked with the the date and the git key so that we know which version has errors and how old it is.

to:

> Particularly for users who are testing new features before they are released, it would be convenient to be able to install multiple versions of !SasView at the same time.
> 
> Pre-release versions should be marked with the date and the git key so that we know which version has errors and how old it is.
