### ISSUE TITLE
clean up sasview directory (Trac #579)

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#711]
setup_exe and setup_mac don't belong in the sasview directory.  They are causing errors in the sphinx documentation build.  They should be moved to the build_tools directory along with their support files.

Migrated from http://trac.sasview.org/ticket/579
```json
{
    "status": "closed",
    "changetime": "2017-10-27T11:07:16",
    "_ts": "2017-10-27 11:07:16.633748+00:00",
    "description": "setup_exe and setup_mac don't belong in the sasview directory.  They are causing errors in the sphinx documentation build.  They should be moved to the build_tools directory along with their support files.",
    "reporter": "pkienzle",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2016-05-27T16:37:18",
    "component": "SasView",
    "summary": "clean up sasview directory",
    "priority": "minor",
    "keywords": "",
    "milestone": "SasView 4.2.0",
    "owner": "",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2017/10/27 11:02:01`: **butler** changed milestone from "SasView Next Release +1" to "SasView 4.2.0"

**Comment by butlerpd** [comment]
Trac update at `2017/10/27 11:07:16`: 
* **butler** commented:

In Paul Kienzle's reorg the ''sasview'' directory was removed anyway.  However he created an ''installers'' directory which is where these two files now resided along with their support files.  Thus this ticket should now be closed.


* **butler** changed resolution from "" to "fixed"
* **butler** changed status from "new" to "closed"
