### ISSUE TITLE
min value on flat background should not be zero but -inf (Trac #581)

### ISSUE THREAD

**Issue by RichardHeenan** [SasView/sasview#713]
Comparing 4.0 alpha2 fits with some user data in guinier_porod model, I noticed different results.
min value of flat background is set 0 instead of -inf, alas our neutron backgrounds can be negative if the model is cranky or users have oversubtracted incoherent etc.
I have not got build etc set up at present, perhaps someone else could fix this as this bug seems generic for all models.
Richard

Migrated from http://trac.sasview.org/ticket/581
```json
{
    "status": "closed",
    "changetime": "2016-10-04T20:01:10",
    "_ts": "2016-10-04 20:01:10.643768+00:00",
    "description": "Comparing 4.0 alpha2 fits with some user data in guinier_porod model, I noticed different results.\nmin value of flat background is set 0 instead of -inf, alas our neutron backgrounds can be negative if the model is cranky or users have oversubtracted incoherent etc.\nI have not got build etc set up at present, perhaps someone else could fix this as this bug seems generic for all models.\nRichard",
    "reporter": "richardh",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2016-06-14T15:17:43",
    "component": "SasView",
    "summary": "min value on flat background should not be zero but -inf",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.1.0",
    "owner": "richardh",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2016/09/05 02:03:28`: **butler** commented:

We need to resolve this... or move to +1 to resolve at code camp.  A strong argument was made at a Tuesday discussion meeting that 0 is the correct min.  Further it can be changed trivially by the user should they wish to do so.  The strong part of the argument hinged on the mathematical incorrectness of the method and the fact that the resulting parameters and uncertainties would be completely wrong.  This mathematical argument was made by Paul Kienzle but those in attendance tended to agree with his point. Unfortunately Richard Heenab was not present and the ticket was left open till further discussion could be had.

**Comment by butlerpd** [comment]
Trac update at `2016/09/05 03:27:53`: **butler** changed priority from "critical" to "major"

**Comment by butlerpd** [comment]
Trac update at `2016/09/13 13:00:49`: 
* **butler** changed owner from "richardh" to "ajj"
* **butler** changed status from "new" to "assigned"

**Comment by butlerpd** [comment]
Trac update at `2016/09/21 13:36:32`: 
* **butler** commented:

Richard out so will close loop after this release. moving to 4.1


* **butler** changed milestone from "SasView 4.0.0" to "SasView 4.1.0"

**Comment by RichardHeenan** [comment]
Trac update at `2016/10/04 19:25:23`: **richardh** commented:

4th Oct 2016, discussion at code camp:
(a) Even if the "incoherent" or other background is "properly" subtracted, the fitted flat background may legitimately be negative, say -0.002 +- 0.01, thus we should not force background to always be positive.
(b) forcing positive background changes sasview to behave differently to how it used to, and to be different to any other fitting code.
(c) Users can then decide to fix flat background at a physically reasonable value.

Richard will change the default behaviour, see modelinfo.py around line 45

**Comment by RichardHeenan** [comment]
Trac update at `2016/10/04 19:28:31`: **richardh** changed owner from "ajj" to "richardh"

**Comment by RichardHeenan** [comment]
Trac update at `2016/10/04 20:01:10`: 
* **richardh** changed resolution from "" to "fixed"
* **richardh** changed status from "assigned" to "closed"
