### ISSUE TITLE
Sum|Multi(p1,p2) does not work (Trac #583)

### ISSUE THREAD

**Issue by gonzalezma** [SasView/sasview#715]
Sum (multiplication) of two models does not work (known bug, reported also by thomas.cleveland@nist.gov)

When trying to create a model as the sum of two standard models, the following error message appears:

“Running model '!MySumFunction.py'... 
Error occurred:
Traceback (most recent call last):
  File "sas\sasgui\perspectives\calculator\pyconsole.pyc", line 55, in show_model_output
  File "sas\sasgui\perspectives\calculator\pyconsole.pyc", line 30, in check_model
!ImportError: cannot import name make_class”

This happens because the function make_class (in sasmodels/sasview_model.py) does not exist anymore, as it was replaced by _make_standard_model in 4d76711 on Apr 5 (Paul Kienzle adjust interface to sasview). Note: The comment at the beginning of sasview_model.py should be changed accordingly, as it still mentions make_class.

The obvious change that I tried is to replace make_class by _make_standard_model in the python file generated by “Sum|Multi(p1,p2)”, but then a different problem happens and the fitting perspective is broken, so it is even worse than the original bug.

This is what I could follow about the program execution:

- I start !SasView 4.0 having the file MG_sum1.py in the .sasview\plugin_models folder. This is just the file created by the template of “Sum|Multi(p1,p2)” for a model consisting of an sphere + a cylinder, but replacing make_class by _make_standard_model.

- In sasview\src\sas\sasgui\perspectives\fitting\models.py it is added to the plugins by the command plugins[name] = module.Model, returning a class MG_sum1.model. As a reference, a simple python model present in the plugin_models is loaded using plugins[name] = load_custom_model(filename) and we generate a class sasmodels.sasview_model.MG_simple1

- In the call to _get_multifunc_models, an error is generated because the class Model has no attribute ‘is_multiplicitiy_model’

Migrated from http://trac.sasview.org/ticket/583
```json
{
    "status": "closed",
    "changetime": "2016-07-02T21:28:35",
    "_ts": "2016-07-02 21:28:35.368100+00:00",
    "description": "Sum (multiplication) of two models does not work (known bug, reported also by thomas.cleveland@nist.gov)\n\nWhen trying to create a model as the sum of two standard models, the following error message appears:\n\n\u201cRunning model '!MySumFunction.py'... \nError occurred:\nTraceback (most recent call last):\n  File \"sas\\sasgui\\perspectives\\calculator\\pyconsole.pyc\", line 55, in show_model_output\n  File \"sas\\sasgui\\perspectives\\calculator\\pyconsole.pyc\", line 30, in check_model\n!ImportError: cannot import name make_class\u201d\n\nThis happens because the function make_class (in sasmodels/sasview_model.py) does not exist anymore, as it was replaced by _make_standard_model in 4d76711 on Apr 5 (Paul Kienzle adjust interface to sasview). Note: The comment at the beginning of sasview_model.py should be changed accordingly, as it still mentions make_class.\n\nThe obvious change that I tried is to replace make_class by _make_standard_model in the python file generated by \u201cSum|Multi(p1,p2)\u201d, but then a different problem happens and the fitting perspective is broken, so it is even worse than the original bug.\n\nThis is what I could follow about the program execution:\n\n- I start !SasView 4.0 having the file MG_sum1.py in the .sasview\\plugin_models folder. This is just the file created by the template of \u201cSum|Multi(p1,p2)\u201d for a model consisting of an sphere + a cylinder, but replacing make_class by _make_standard_model.\n\n- In sasview\\src\\sas\\sasgui\\perspectives\\fitting\\models.py it is added to the plugins by the command plugins[name] = module.Model, returning a class MG_sum1.model. As a reference, a simple python model present in the plugin_models is loaded using plugins[name] = load_custom_model(filename) and we generate a class sasmodels.sasview_model.MG_simple1\n\n- In the call to _get_multifunc_models, an error is generated because the class Model has no attribute \u2018is_multiplicitiy_model\u2019\n",
    "reporter": "gonzalezm",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2016-06-16T09:51:12",
    "component": "SasView",
    "summary": "Sum|Multi(p1,p2) does not work",
    "priority": "blocker",
    "keywords": "",
    "milestone": "SasView 4.0.0",
    "owner": "ajj",
    "type": "defect"
}
```

**Comment by ajj** [comment]
Trac update at `2016/06/16 10:02:16`: 
* **ajj** changed owner from "" to "ajj"
* **ajj** changed status from "new" to "assigned"

**Comment by ajj** [comment]
Trac update at `2016/06/16 11:06:39`: **ajj** commented:

There is a cascading set of changes in the model interface that means that I don't think we can make a sum/multi model the way we do now.

I tried changing the call to make_class to load_standard_models which seems to allow the model to get further, but fails on pyconsole.check_model()

This is because of the way that load_model_info now works - it attempts to handle + and * models by parsing the model name.

Thus a sum/multi model does not exist anymore as a separate entity - not clear how we can change the infrastructure to support these "virtual" models and have them be persistent. 

Should probably be encouraging users to write models that re-parameterise and then call underlying model kernels but again it is not clear (to me) how to do this with the current approach.

**Comment by butlerpd** [comment]
Trac update at `2016/06/19 01:59:20`: **butler** changed priority from "critical" to "blocker"

**Comment by pkienzle** [comment]
Trac update at `2016/06/22 18:09:07`: 
* **pkienzle** commented:

I made the current approach work again for alpha, but still want to refactor it for beta, time permitting, so that sum and multiply are more compact.  I'll open this as a new ticket.


* **pkienzle** changed resolution from "" to "fixed"
* **pkienzle** changed status from "assigned" to "closed"

**Comment by butlerpd** [comment]
Trac update at `2016/07/02 21:28:35`: **butler** changed description from:

> Sum (multiplication) of two models does not work (known bug, reported also by thomas.cleveland@nist.gov)
> 
> When trying to create a model as the sum of two standard models, the following error message appears:
> 
> “Running model 'MySumFunction.py'... 
> Error occurred:
> Traceback (most recent call last):
>   File "sas\sasgui\perspectives\calculator\pyconsole.pyc", line 55, in show_model_output
>   File "sas\sasgui\perspectives\calculator\pyconsole.pyc", line 30, in check_model
> ImportError: cannot import name make_class”
> 
> This happens because the function make_class (in sasmodels/sasview_model.py) does not exist anymore, as it was replaced by _make_standard_model in 4d76711 on Apr 5 (Paul Kienzle adjust interface to sasview). Note: The comment at the beginning of sasview_model.py should be changed accordingly, as it still mentions make_class.
> 
> The obvious change that I tried is to replace make_class by _make_standard_model in the python file generated by “Sum|Multi(p1,p2)”, but then a different problem happens and the fitting perspective is broken, so it is even worse than the original bug.
> 
> This is what I could follow about the program execution:
> 
> - I start SasView 4.0 having the file MG_sum1.py in the .sasview\plugin_models folder. This is just the file created by the template of “Sum|Multi(p1,p2)” for a model consisting of an sphere + a cylinder, but replacing make_class by _make_standard_model.
> 
> - In sasview\src\sas\sasgui\perspectives\fitting\models.py it is added to the plugins by the command plugins[name] = module.Model, returning a class MG_sum1.model. As a reference, a simple python model present in the plugin_models is loaded using plugins[name] = load_custom_model(filename) and we generate a class sasmodels.sasview_model.MG_simple1
> 
> - In the call to _get_multifunc_models, an error is generated because the class Model has no attribute ‘is_multiplicitiy_model’
> 

to:

> Sum (multiplication) of two models does not work (known bug, reported also by thomas.cleveland@nist.gov)
> 
> When trying to create a model as the sum of two standard models, the following error message appears:
> 
> “Running model '!MySumFunction.py'... 
> Error occurred:
> Traceback (most recent call last):
>   File "sas\sasgui\perspectives\calculator\pyconsole.pyc", line 55, in show_model_output
>   File "sas\sasgui\perspectives\calculator\pyconsole.pyc", line 30, in check_model
> !ImportError: cannot import name make_class”
> 
> This happens because the function make_class (in sasmodels/sasview_model.py) does not exist anymore, as it was replaced by _make_standard_model in 4d76711 on Apr 5 (Paul Kienzle adjust interface to sasview). Note: The comment at the beginning of sasview_model.py should be changed accordingly, as it still mentions make_class.
> 
> The obvious change that I tried is to replace make_class by _make_standard_model in the python file generated by “Sum|Multi(p1,p2)”, but then a different problem happens and the fitting perspective is broken, so it is even worse than the original bug.
> 
> This is what I could follow about the program execution:
> 
> - I start !SasView 4.0 having the file MG_sum1.py in the .sasview\plugin_models folder. This is just the file created by the template of “Sum|Multi(p1,p2)” for a model consisting of an sphere + a cylinder, but replacing make_class by _make_standard_model.
> 
> - In sasview\src\sas\sasgui\perspectives\fitting\models.py it is added to the plugins by the command plugins[name] = module.Model, returning a class MG_sum1.model. As a reference, a simple python model present in the plugin_models is loaded using plugins[name] = load_custom_model(filename) and we generate a class sasmodels.sasview_model.MG_simple1
> 
> - In the call to _get_multifunc_models, an error is generated because the class Model has no attribute ‘is_multiplicitiy_model’
>
