### ISSUE TITLE
old custom models break !SasView (Trac #588)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#720]
If the user has any custom models in the plugins directory which will likely be true for most if not all existing users, installing !SasView 4.0 alpha will cause fitting not to load at all on startup due to a failing import statement (the old plugin class the custom models use is no longer available). Thus we have two problems:

1. returning users will find the new version doesn't even run
2. if we fix that somehow we still have the problem that all their custom models are now broken.

For the full release we must fix 1 and should do something to minimize pain of 2. A cheap solution to 1 might be to surround loading of plugins with a try except and on failure provide feedback that old models are in the directory?  A step further could remove those files to a subdirectory and provide infrastructure to make them continue to work.  Alternatively we could try to provide a converter?

Migrated from http://trac.sasview.org/ticket/588
```json
{
    "status": "closed",
    "changetime": "2016-08-11T01:53:18",
    "_ts": "2016-08-11 01:53:18.816031+00:00",
    "description": "If the user has any custom models in the plugins directory which will likely be true for most if not all existing users, installing !SasView 4.0 alpha will cause fitting not to load at all on startup due to a failing import statement (the old plugin class the custom models use is no longer available). Thus we have two problems:\n\n1. returning users will find the new version doesn't even run\n2. if we fix that somehow we still have the problem that all their custom models are now broken.\n\nFor the full release we must fix 1 and should do something to minimize pain of 2. A cheap solution to 1 might be to surround loading of plugins with a try except and on failure provide feedback that old models are in the directory?  A step further could remove those files to a subdirectory and provide infrastructure to make them continue to work.  Alternatively we could try to provide a converter?\n\n",
    "reporter": "butler",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2016-07-03T00:07:18",
    "component": "SasView",
    "summary": "old custom models break !SasView",
    "priority": "blocker",
    "keywords": "",
    "milestone": "SasView 4.0.0",
    "owner": "",
    "type": "defect"
}
```

**Comment by wpotrzebowski** [comment]
Trac update at `2016/07/05 08:24:07`: **wojciech** commented:

It seems that the simple (cheap) solution can be achieved by moving a load_custom_model function (line 189) in src/sas/sasgui/perspectives/fitting/model.py to "try:" statement (a few lines above). It will load plugin models from ./sasview/plugin_models if possible. Otherwise empty dict is returned and no custom models are available.

**Comment by wpotrzebowski** [comment]
Trac update at `2016/07/07 08:42:54`: **wojciech** commented:

The change in src/sas/sasgui/perspectives/fitting/model.py as explained in earlier comment seems to fix issue 1 (returning users will find the new version doesn't even run). The 2nd issue (old custom models are broken) remains unsolved.

**Comment by butlerpd** [comment]
Trac update at `2016/07/07 11:53:38`: **butler** commented:

Andrew suggests a possible "fix" to 2 would be that when trapping (presumably the fix just applied) on except we pop up a box informing the user of the change and what they need to do to get their models working again (or point then to instructions) ... and maybe an apolgy explaining this change does make things a lot better in the long run?

**Comment by pkienzle** [comment]
Trac update at `2016/08/11 01:53:18`: 
* **pkienzle** changed resolution from "" to "fixed"
* **pkienzle** changed status from "new" to "closed"
