### ISSUE TITLE
Check default value of cansas_version property in CansasReader class (Trac #594)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#726]
(Ticket raised on behalf of Lewis) !CansasReader has a property cansas_version which determines the xml header written in the files. This currently seems to default to 1.0 and not 1.1 as you get the old header if you call this class directly. However if you save xml files from the GUI they are saved with the new header! This suggests the default is over-ridden somewhere. Needs investigating.

Migrated from http://trac.sasview.org/ticket/594
```json
{
    "status": "accepted",
    "changetime": "2017-10-27T13:50:15",
    "_ts": "2017-10-27 13:50:15.244021+00:00",
    "description": "(Ticket raised on behalf of Lewis) !CansasReader has a property cansas_version which determines the xml header written in the files. This currently seems to default to 1.0 and not 1.1 as you get the old header if you call this class directly. However if you save xml files from the GUI they are saved with the new header! This suggests the default is over-ridden somewhere. Needs investigating.",
    "reporter": "smk78",
    "cc": "",
    "resolution": "",
    "workpackage": "SasView Bug Fixing",
    "time": "2016-07-22T15:22:18",
    "component": "SasView",
    "summary": "Check default value of cansas_version property in CansasReader class",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.3.0",
    "owner": "tim",
    "type": "task"
}
```

**Comment by smk78** [comment]
Trac update at `2016/07/22 16:39:33`: **smk78** commented:

No this was an issue calling the class from Python. It seems the default behaviour is to write 1.0?

**Comment by smk78** [comment]
Trac update at `2016/07/22 16:40:41`: **smk78** commented:

If you don't load xml data - and thus give the program a hint as what version of xml it should write - where does it decide to write 1.1?

**Comment by smk78** [comment]
Trac update at `2016/07/27 08:33:42`: **smk78** commented:

Unless you have got your 1.0's and 1.1's transposed in that comment, you have indeed recreated the issue: why is the default to write 1.0 headers and not 1.1 headers?

**Comment by butlerpd** [comment]
Trac update at `2017/10/27 13:50:02`: 
* **butler** changed description from "(Ticket raised on behalf of Lewis) CansasReader has a property cansas_version which determines the xml header written in the files. This currently seems to default to 1.0 and not 1.1 as you get the old header if you call this class directly. However if you save xml files from the GUI they are saved with the new header! This suggests the default is over-ridden somewhere. Needs investigating." to "(Ticket raised on behalf of Lewis) !CansasReader has a property cansas_version which determines the xml header written in the files. This currently seems to default to 1.0 and not 1.1 as you get the old header if you call this class directly. However if you save xml files from the GUI they are saved with the new header! This suggests the default is over-ridden somewhere. Needs investigating."
* **butler** changed milestone from "SasView 4.2.0" to "SasView 4.3.0"

**Comment by butlerpd** [comment]
Trac update at `2017/10/27 13:50:15`: **butler** changed priority from "critical" to "major"

**Comment by butlerpd** [comment]
@krzywon and @timsnow can you comment on the status of this?  I'm guessing that with the various things you've done @krzywon since the last entry on this ticket that this may now be obsolete? Can I close it?

**Comment by krzywon** [comment]
A quick look at the reader tells me this was never finished. I am going to work on #1303 for the next 5.x release so I will tackle this at the same time.

**Comment by krzywon** [comment]
This was fixed with the last PR so I'm closing.
