### ISSUE TITLE
What data should be loaded / is loaded if a Cansas xml file has multiple <SASdata>? (Trac #596)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#728]
(Ticket raised on behalf of Lewis) !SasView will apparently read Cansas xml files with multiple <SASdata> blocks (provided there aren't too many...) but it only actually seems to load one data block [I think the last one read - Steve]. This behaviour needs investigating and explaining to the user asap. But in the longer term this behaviour needs to be reviewed and the loader amended accordingly (perhaps by recognising multiple <SASdata> and then asking for first/last/increment).

Migrated from http://trac.sasview.org/ticket/596
```json
{
    "status": "closed",
    "changetime": "2016-08-19T13:29:36",
    "_ts": "2016-08-19 13:29:36.857521+00:00",
    "description": "(Ticket raised on behalf of Lewis) !SasView will apparently read Cansas xml files with multiple <SASdata> blocks (provided there aren't too many...) but it only actually seems to load one data block [I think the last one read - Steve]. This behaviour needs investigating and explaining to the user asap. But in the longer term this behaviour needs to be reviewed and the loader amended accordingly (perhaps by recognising multiple <SASdata> and then asking for first/last/increment).",
    "reporter": "smk78",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2016-07-22T15:42:23",
    "component": "SasView",
    "summary": "What data should be loaded / is loaded if a Cansas xml file has multiple <SASdata>?",
    "priority": "critical",
    "keywords": "",
    "milestone": "SasView 4.0.0",
    "owner": "krzywon",
    "type": "task"
}
```

**Comment by smk78** [comment]
Trac update at `2016/07/22 16:42:55`: 
* **smk78** changed attachment from "" to "cansas-multi - Copy - 1frame.xml"
* **smk78** commented:

xml file written by SasView with 1 <SASdata> block

**Comment by smk78** [comment]
Trac update at `2016/07/22 16:43:13`: 
* **smk78** changed attachment from "" to "cansas-multi - Copy - 2frame.xml"
* **smk78** commented:

xml file written by SasView with 2 <SASdata> blocks

**Comment by ajj** [comment]
Trac update at `2016/07/22 19:04:13`: **ajj** commented:

"Official" cansas example here:

Multiple sasentry each with two sasdata

http://www.cansas.org/svn/1dwg/trunk/examples/cs_af1410.xml

**Comment by smk78** [comment]
Trac update at `2016/07/26 08:02:12`: **smk78** commented:

I would say that the original intent was that <SASdata> would represent multiple datasets under the same run number (so multiple 'periods' or 'frames'), whereas <SASentry> represented a new run number. In terms of what !!SasView might do with such data I would argue to treat both the same and create separate Data1D() objects. ''However'', there could be a lot of <SASdata> blocks if the file has come from the X-ray community, so might be best to warn how many there are and ask the user to select min, max, increment?
