### ISSUE TITLE
Need to document Combine Batch Fit (Trac #597)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#729]
There seems to be a relatively new panel of the "simultaneous fit" type called Combined Batch Fit.  The help for this goes to the same help as the regular panel and does not explain this panel at all.  Need to add some more specific documentation

Migrated from http://trac.sasview.org/ticket/597
```json
{
    "status": "closed",
    "changetime": "2017-09-11T23:59:58",
    "_ts": "2017-09-11 23:59:58.594880+00:00",
    "description": "There seems to be a relatively new panel of the \"simultaneous fit\" type called Combined Batch Fit.  The help for this goes to the same help as the regular panel and does not explain this panel at all.  Need to add some more specific documentation",
    "reporter": "butler",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Documentation",
    "time": "2016-07-25T01:37:04",
    "component": "SasView",
    "summary": "Need to document Combine Batch Fit",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.2.0",
    "owner": "butler",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2016/09/05 14:38:40`: **butler** changed priority from "critical" to "major"

**Comment by wpotrzebowski** [comment]
Trac update at `2016/09/22 13:05:54`: **wojciech** commented:

I think the intention of Combined Batch Fit is to have a higher level of batch fitting than a"standard" Batch Fitting. For example if one sets 1st batch fitting with Model1 and 2nd batch fitting with Model2 these two can be then combined into one Combined Batch Fit with Model1 and Model2. In this scenario BatchPage1 and BatchPage2 are combined

**Comment by ajj** [comment]
Trac update at `2016/09/23 14:31:49`: **ajj** commented:

Does it work? We should probably have a set of test data that we can use it with.

**Comment by wpotrzebowski** [comment]
Trac update at `2016/09/26 13:22:15`: **wojciech** commented:

It seems to be working but I have no idea what the good use case can be.

**Comment by ajj** [comment]
Trac update at `2016/09/27 14:44:22`: **ajj** changed _comment0 from "At the fortnightly call on Sep 28, 2016, it was agreed that we should move this to 4.1 and discuss at code camp what to do with this feature." to "1474988146625609"

**Comment by butlerpd** [comment]
Trac update at `2016/09/27 14:44:22`: 
* **butler** commented:

At the fortnightly call on Sep 27, 2016, it was agreed that we should move this to 4.1 and discuss at code camp what to do with this feature.


* **butler** changed milestone from "SasView 4.0.0" to "SasView 4.1.0"

**Comment by ajj** [comment]
Trac update at `2016/11/08 14:29:40`: **ajj** changed milestone from "SasView 4.1.0" to "SasView 4.2.0"

**Comment by butlerpd** [comment]
Trac update at `2017/04/05 13:57:14`: 
* **butler** changed owner from "" to "butler"
* **butler** changed status from "new" to "accepted"

**Comment by butlerpd** [comment]
Trac update at `2017/09/11 23:59:58`: 
* **butler** commented:

This was closed with the merging of pull request 78 from ticket 597 branch.  I forgot to add a closing statement in the merge comments so closing manually


* **butler** changed resolution from "" to "fixed"
* **butler** changed status from "accepted" to "closed"
