### ISSUE TITLE
Test xml data load with errors (Trac #600)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#732]
Several of the xml files in the test folder, including for example hSDS_D2O_0p5_percent.xml, will load but the canSAS reader throws error when doing so (basically lamda unit is "wavelength" instead of A or nm etc).  I know there was a discussion that the reader should not barf if the data can still be loaded but should we have data in the test folder that throws an error? 

Migrated from http://trac.sasview.org/ticket/600
```json
{
    "status": "closed",
    "changetime": "2016-07-27T08:26:35",
    "_ts": "2016-07-27 08:26:35.879428+00:00",
    "description": "Several of the xml files in the test folder, including for example hSDS_D2O_0p5_percent.xml, will load but the canSAS reader throws error when doing so (basically lamda unit is \"wavelength\" instead of A or nm etc).  I know there was a discussion that the reader should not barf if the data can still be loaded but should we have data in the test folder that throws an error? ",
    "reporter": "butler",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2016-07-25T02:26:14",
    "component": "SasView",
    "summary": "Test xml data load with errors",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.0.0",
    "owner": "smk78",
    "type": "defect"
}
```

**Comment by smk78** [comment]
Trac update at `2016/07/26 07:51:19`: **smk78** commented:

Ahh... that will be me then. They must have been written by a version of Mantid that had developed a bug. I'll sort.

**Comment by smk78** [comment]
Trac update at `2016/07/26 07:51:43`: 
* **smk78** changed owner from "" to "smk78"
* **smk78** changed status from "new" to "assigned"

**Comment by smk78** [comment]
Trac update at `2016/07/27 08:26:25`: **smk78** commented:

Lambda unit changed from "Wavelength" to "A".

**Comment by smk78** [comment]
Trac update at `2016/07/27 08:26:35`: 
* **smk78** changed resolution from "" to "fixed"
* **smk78** changed status from "assigned" to "closed"
