### ISSUE TITLE
pringle model questions (Trac #604)

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#736]
(1) Sasmodels pringle does not match sasview pringle when polydispersity is present.  Sasview does not seem to be using the usual volume normalization; the numerator is not sum(weight * form * volume), but the denominator is sum(weight * volume).  Sasmodels is setting volume to 1.

(2) The !SasView 3.1.2 model docs define:

    Cn = integral from 0 to R r cos(...) Jn(...) J2n(...)

but the code includes an additional scaling by 1/R^2^.

The equations in the docs and the code need to be consistent.  Should the docs be updated with the 1/R^2^ factor?

(3) The normalization in (2) uses the final point r from the gaussian quadrature, which is a tiny bit less than R. Should it use R^2^ instead?

Migrated from http://trac.sasview.org/ticket/604
```json
{
    "status": "closed",
    "changetime": "2016-09-27T08:03:01",
    "_ts": "2016-09-27 08:03:01.246574+00:00",
    "description": "(1) Sasmodels pringle does not match sasview pringle when polydispersity is present.  Sasview does not seem to be using the usual volume normalization; the numerator is not sum(weight * form * volume), but the denominator is sum(weight * volume).  Sasmodels is setting volume to 1.\n\n(2) The !SasView 3.1.2 model docs define:\n\n    Cn = integral from 0 to R r cos(...) Jn(...) J2n(...)\n\nbut the code includes an additional scaling by 1/R^2^.\n\nThe equations in the docs and the code need to be consistent.  Should the docs be updated with the 1/R^2^ factor?\n\n(3) The normalization in (2) uses the final point r from the gaussian quadrature, which is a tiny bit less than R. Should it use R^2^ instead?\n\n",
    "reporter": "pkienzle",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2016-07-31T21:48:29",
    "component": "SasView",
    "summary": "pringle model questions",
    "priority": "critical",
    "keywords": "",
    "milestone": "SasView 4.0.0",
    "owner": "ajj",
    "type": "defect"
}
```

**Comment by ajj** [comment]
Trac update at `2016/08/31 15:51:32`: 
* **ajj** changed owner from "" to "ajj"
* **ajj** changed status from "new" to "assigned"

**Comment by butlerpd** [comment]
Trac update at `2016/09/05 14:41:53`: **butler** changed priority from "major" to "critical"

**Comment by ajj** [comment]
Trac update at `2016/09/23 13:37:19`: **ajj** commented:

(1)&(2) The normalisation here is a bit odd. The derivation I was given for the model did not include any normalisation (mathematicians!) so I had to try to work it out and mostly did it by empirical comparison with the limiting case of a cylinder. I need to work through it again and check.

(3) Yes it should

I will sort these out before release.

**Comment by ajj** [comment]
Trac update at `2016/09/27 08:03:01`: 
* **ajj** changed resolution from "" to "fixed"
* **ajj** changed status from "assigned" to "closed"
