### ISSUE TITLE
swollen sphere parameterization (Trac #605)

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#737]
Improve description of ''phi'' and ''x'' parameters.  Is ''phi'' supposed to be volume fraction of spheres, and ''x'' the solvent fraction within spheres?  The redundant ''scale'' parameter is automatically included in all models, and has been removed.

Documentation, including equations, needs to reflect the additional parameters.

''phi'' need not be polydisperse; the integral over a polydisperse scale factor is indistinguishable from a monodisperse scale factor equal to the weighted average of the polydisperse scale factor.

Is solvent fraction ''x'' supposed to be polydisperse?  In which case with different spheres absorbing different amounts of solvent, shouldn't the underlying ''radius'' be increased and ''sld'' adjusted toward ''sld_solvent'' as solvent fraction increases?  As it is now, being a scale factor on the sphere form, there is no reason to make it polydisperse.

As contrast is reduced by solvent fraction in the sphere, shouldn't the sphere form factor be reduced by the squared fraction?  This would occur automatically if ''sld'' were adjusted toward ''sld_solvent'' by factor ''(1-x)''.

Migrated from http://trac.sasview.org/ticket/605
```json
{
    "status": "closed",
    "changetime": "2016-10-10T21:52:22",
    "_ts": "2016-10-10 21:52:22.851332+00:00",
    "description": "Improve description of ''phi'' and ''x'' parameters.  Is ''phi'' supposed to be volume fraction of spheres, and ''x'' the solvent fraction within spheres?  The redundant ''scale'' parameter is automatically included in all models, and has been removed.\n\nDocumentation, including equations, needs to reflect the additional parameters.\n\n''phi'' need not be polydisperse; the integral over a polydisperse scale factor is indistinguishable from a monodisperse scale factor equal to the weighted average of the polydisperse scale factor.\n\nIs solvent fraction ''x'' supposed to be polydisperse?  In which case with different spheres absorbing different amounts of solvent, shouldn't the underlying ''radius'' be increased and ''sld'' adjusted toward ''sld_solvent'' as solvent fraction increases?  As it is now, being a scale factor on the sphere form, there is no reason to make it polydisperse.\n\nAs contrast is reduced by solvent fraction in the sphere, shouldn't the sphere form factor be reduced by the squared fraction?  This would occur automatically if ''sld'' were adjusted toward ''sld_solvent'' by factor ''(1-x)''.\n",
    "reporter": "pkienzle",
    "cc": "",
    "resolution": "obsolete",
    "workpackage": "SasView Bug Fixing",
    "time": "2016-07-31T22:31:16",
    "component": "SasView",
    "summary": "swollen sphere parameterization",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView Next Release +1",
    "owner": "",
    "type": "defect"
}
```

**Comment by pkienzle** [comment]
Trac update at `2016/08/30 16:28:18`: **pkienzle** changed milestone from "SasView 4.0.0" to "SasView Next Release +1"

**Comment by butlerpd** [comment]
Trac update at `2016/10/10 21:52:22`: 
* **butler** commented:

This model was one being written by ILL summer student in Summer 2016 but was then removed due to massive issues with the commit before the release -- at some point a new version may be put in by Miguel but seems to be in limbo so closing this ticket.  If and when such a model does get submitted it should be reviewed from scratch. 


* **butler** changed resolution from "" to "obsolete"
* **butler** changed status from "new" to "closed"
