### ISSUE TITLE
surface fractal I(q) < 0 (Trac #606)

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#738]
The surface fractal model produces negative I(q) values for low q.
To see it run compare:

```text
python sascomp surface_fractal 1 0 -linear -double
```

Migrated from http://trac.sasview.org/ticket/606
```json
{
    "status": "closed",
    "changetime": "2016-09-13T14:45:40",
    "_ts": "2016-09-13 14:45:40.810167+00:00",
    "description": "The surface fractal model produces negative I(q) values for low q.\nTo see it run compare:\n\n{{{\npython sascomp surface_fractal 1 0 -linear -double\n}}}",
    "reporter": "pkienzle",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Documentation",
    "time": "2016-08-01T21:27:36",
    "component": "SasView",
    "summary": "surface fractal I(q) < 0",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.0.0",
    "owner": "butler",
    "type": "enhancement"
}
```

**Comment by pkienzle** [comment]
Trac update at `2016/08/02 00:02:00`: **pkienzle** commented:

Docs indicate that this model is only valid in a restricted q range.

Update the docs with the valid q range.

**Comment by butlerpd** [comment]
Trac update at `2016/08/02 13:02:02`: 
* **butler** changed type from "defect" to "enhancement"
* **butler** changed workpackage from "SasView Bug Fixing" to "SasView Documentation"

**Comment by butlerpd** [comment]
Trac update at `2016/09/05 14:51:36`: 
* **butler** changed owner from "" to "butler"
* **butler** changed status from "new" to "assigned"

**Comment by butlerpd** [comment]
Trac update at `2016/09/05 14:51:50`: **butler** changed status from "assigned" to "accepted"

**Comment by butlerpd** [comment]
Trac update at `2016/09/13 14:45:40`: 
* **butler** commented:

This seems to be now documented in the documentation.  However would be nice to have warnings when being ued. A new ticket #792 was created for that and assigned to +1.  Now closing this ticket


* **butler** changed resolution from "" to "fixed"
* **butler** changed status from "accepted" to "closed"
