### ISSUE TITLE
move mag_help rst to sasmodels (Trac #607)

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#739]
Move the magnetism help files from sasview into sasmodels, replace equation images with latex, and fix back links from sphere, core shell, core multi shell, cylinder and parallelepiped.

Migrated from http://trac.sasview.org/ticket/607
```json
{
    "status": "closed",
    "changetime": "2016-08-18T12:10:17",
    "_ts": "2016-08-18 12:10:17.523801+00:00",
    "description": "Move the magnetism help files from sasview into sasmodels, replace equation images with latex, and fix back links from sphere, core shell, core multi shell, cylinder and parallelepiped.",
    "reporter": "pkienzle",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2016-08-08T15:41:11",
    "component": "SasView",
    "summary": "move mag_help rst to sasmodels",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.0.0",
    "owner": "wojciech",
    "type": "defect"
}
```

**Comment by wpotrzebowski** [comment]
Trac update at `2016/08/09 09:14:02`: 
* **wojciech** changed owner from "" to "wojciech"
* **wojciech** changed status from "new" to "assigned"

**Comment by wpotrzebowski** [comment]
Trac update at `2016/08/18 12:08:49`: 
* **wojciech** changed resolution from "" to "fixed"
* **wojciech** changed status from "assigned" to "closed"

**Comment by wpotrzebowski** [comment]
Trac update at `2016/08/18 12:10:17`: **wojciech** commented:

The ticket has been resolved. However the list of models for which magnetism has been implemented can be extended
