### ISSUE TITLE
Loading Folder behavior oddity if folder contains non data file (Trac #614)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#746]
When loading and entire folder with Load Folder or in fact using load file and selecting all the files indiscriminately, The first non data file raises an error which could be a different kind of !SasView file (a .svs file for example - and the helpful error tells you how to load it) or something not recognized at all (giving a different error message).  The two issues however are:
* The next non data file does not pop up an error. 
* Further all the GOOD files following that first non data file are listed in the pop up box even though they, along with all the valid data files are in fact loaded.  This is very confusing to the user as it suggests that something is wrong with those files as well.

Migrated from http://trac.sasview.org/ticket/614
```json
{
    "status": "closed",
    "changetime": "2016-09-12T03:46:34",
    "_ts": "2016-09-12 03:46:34.960223+00:00",
    "description": "When loading and entire folder with Load Folder or in fact using load file and selecting all the files indiscriminately, The first non data file raises an error which could be a different kind of !SasView file (a .svs file for example - and the helpful error tells you how to load it) or something not recognized at all (giving a different error message).  The two issues however are:\n* The next non data file does not pop up an error. \n* Further all the GOOD files following that first non data file are listed in the pop up box even though they, along with all the valid data files are in fact loaded.  This is very confusing to the user as it suggests that something is wrong with those files as well.",
    "reporter": "butler",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Framework Enhancements",
    "time": "2016-08-10T22:11:06",
    "component": "SasView",
    "summary": "Loading Folder behavior oddity if folder contains non data file",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.0.0",
    "owner": "lewis",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2016/08/12 18:12:31`: 
* **butler** commented:

The fix now does allow all the non-loading data to be reported with an appropriate error message,  not just the first one.  However, build 436 on my windows machine now not only lists those files but also lists '''all''' the files that in fact do get loaded with the standard error message that they didn't get loaded attached to each.  The pop up should lists all the non-loading data with appropriate messages but not list any of the files that do get loaded. 


* **butler** changed resolution from "fixed" to ""
* **butler** changed status from "closed" to "reopened"

**Comment by butlerpd** [comment]
Trac update at `2016/08/16 01:41:30`: 
* **butler** commented:

There appears to be some rather convoluted logic going on. The latest fix does seem to stop the worst problem of having a popup indicating things had not loaded when in fact they did load.

However the behavior seems a bit erratic.  Using some folders the pop up now works as intended, only listing files that failed to load and stating so an why.  On the other hand using the test folder with some extra non data files thrown ins does not produce the pop up at all! It '''DOES''' however correctly identify in the console screen which files loaded and which failed to load and why. But even within the console screen there are some random behaviors where sometimes the errors are flagged in red preceded by a red x icon while in other cases the errors show up in normal black text preceded by the normal blue i (information) icon.... or sometimes no icon at all.  Further ALL files show as loading -- it seems that the error gets generated in a different stream and shows up sometime later in the list of information on the console - so loading x then at some random point later in the message stream ... failed to load x.

Given that at least now the messages are correct and the fact that this may require some serious work, am moving it to the next release


* **butler** changed milestone from "SasView 4.0.0" to "SasView Next Release +1"

**Comment by smk78** [comment]
Trac update at `2016/08/16 15:03:52`: **smk78** commented:

Also, if the folder contains any non-I(Q) data ASCII files that just happen to have space or tab delimited numbers in the opening lines then these get loaded as data (the first pair of numbers as X & Y). So examples of this include BSL/OTOKO 'header' files, eg: this CORFUNC file had the extension .CF1


```text


     201       1       1       1       0       0       0       0       0       0
C:\Temp\X2
```

where it took the 201 & 1 as X & Y, or perhaps a temporary parameter file such as this one which had the extension .txt:


```text
0.200000E+03
0.100000E+01
0.522096E+00  0.211909E-01  0.396440E-02  0.101775E-02  0.307366E-03
```

where it took the 0.522096E+00  0.211909E-01 as X & Y.

I suspect the ASCII reader is just a little too embracing. Maybe if it checked for two consecutive lines with pairs of numbers, or something like that? But tricky.

**Comment by butlerpd** [comment]
Trac update at `2016/09/05 03:10:00`: 
* **butler** commented:

This should actually not happen -- ASCII reader has ALWAYS looked for X (where I think X is 6 now) rows with EXACTLY the same number of columns of numbers only.  Not perfect but as close as one can get. Either there are more lines or a new bug has been introduced I think.

Can we have an example offending data file attached to this ticket?


* **butler** changed milestone from "SasView Next Release +1" to "SasView 4.0.0"

**Comment by smk78** [comment]
Trac update at `2016/09/06 08:43:43`: **smk78** commented:

Just re-checked in ESS W7 Build 466, this ASCII issue still exists. Am appending three examples files: X27000.CF1, extract.txt & New Text Document.txt

**Comment by smk78** [comment]
Trac update at `2016/09/06 08:44:48`: 
* **smk78** changed attachment from "" to "X27000.CF1"
* **smk78** commented:

OTOKO format header file (ASCII)

**Comment by smk78** [comment]
Trac update at `2016/09/06 08:45:12`: 
* **smk78** changed attachment from "" to "extract.txt"
* **smk78** commented:

Corfunc parameter file (ASCII)

**Comment by smk78** [comment]
Trac update at `2016/09/06 08:45:50`: 
* **smk78** changed attachment from "" to "New Text Document.txt"
* **smk78** commented:

Made up bogus data file (ASCII)

**Comment by smk78** [comment]
Trac update at `2016/09/06 08:47:16`: 
* **smk78** changed _comment0 from "Uh-oh... Issue also exists in SasView 3.1.2!" to "1473151656436548"
* **smk78** commented:

Uh-oh... Issue also exists in !SasView 3.1.2!

**Comment by smk78** [comment]
Trac update at `2016/09/06 08:50:18`: **smk78** commented:

And !SasView 2.2.1... so it's a very long-standing bug!

**Comment by butlerpd** [comment]
Trac update at `2016/09/12 03:46:34`: 
* **butler** commented:

This is essentially fixed.  The new behavior identified by Steve King is completely separate (a failure of the ASCII reader not the folder reader). I have taken the relevant information and attachments and created a new ticket for that with an appropriate title.


* **butler** changed resolution from "" to "fixed"
* **butler** changed status from "reopened" to "closed"
