### ISSUE TITLE
loading invariant analysis doesn't (Trac #615)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#747]
Loading a *.inv file (at least the ones in the test folder) loads the data set but does not send it to invariant tab nor does it seem to send any of the analysis choices to that tab. Seems a bit pointless.  The *.fitv and *.prv do seem to work at least to the extent the data is sent to the analysis tab and fits seem to be displayed.

Migrated from http://trac.sasview.org/ticket/615
```json
{
    "status": "closed",
    "changetime": "2016-10-07T00:16:33",
    "_ts": "2016-10-07 00:16:33.484179+00:00",
    "description": "Loading a *.inv file (at least the ones in the test folder) loads the data set but does not send it to invariant tab nor does it seem to send any of the analysis choices to that tab. Seems a bit pointless.  The *.fitv and *.prv do seem to work at least to the extent the data is sent to the analysis tab and fits seem to be displayed.",
    "reporter": "butler",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "Saving State Enhancements",
    "time": "2016-08-10T22:24:51",
    "component": "SasView",
    "summary": "loading invariant analysis doesn't",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.0.0",
    "owner": "",
    "type": "defect"
}
```

**Comment by ajj** [comment]
Trac update at `2016/08/24 16:14:45`: 
* **ajj** changed resolution from "" to "fixed"
* **ajj** changed status from "new" to "closed"

**Comment by butlerpd** [comment]
Trac update at `2016/10/07 00:16:33`: **butler** changed milestone from "SasView Next Release +1" to "SasView 4.0.0"
