### ISSUE TITLE
scroll wheel should scroll the fit page (Trac #620)

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#752]
Always scroll the page on the scroll wheel.

With the current behaviour, the scroll wheel scrolls the page unless the focus happens to be on a combo box, in which case it scrolls the combo box, changing the selected model.

Migrated from http://trac.sasview.org/ticket/620
```json
{
    "status": "new",
    "changetime": "2017-10-27T11:18:29",
    "_ts": "2017-10-27 11:18:29.227048+00:00",
    "description": "Always scroll the page on the scroll wheel.\n\nWith the current behaviour, the scroll wheel scrolls the page unless the focus happens to be on a combo box, in which case it scrolls the combo box, changing the selected model.\n\n",
    "reporter": "pkienzle",
    "cc": "",
    "resolution": "",
    "workpackage": "SasView Bug Fixing",
    "time": "2016-08-16T15:24:59",
    "component": "SasView",
    "summary": "scroll wheel should scroll the fit page",
    "priority": "minor",
    "keywords": "",
    "milestone": "SasView 5.0.0",
    "owner": "",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2017/10/27 11:18:29`: **butler** changed milestone from "SasView Next Release +1" to "SasView 5.0.0"

**Comment by rozyczko** [comment]
In 5.0 the scroll wheel scrolls whatever element is currently under the mouse cursor, which is the default behaviour. Should we disable focus-oriented scroll and only allow category/model/structure factor comboboxes be scrolled when selected/unrolled?
