### ISSUE TITLE
custom models reloaded too often (Trac #624)

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#756]
Every custom model is being reloaded each time any model is updated.

To see this, uncomment line 117 of sasview_model.py (in load_custom_model), then use the model editor.

This is a minor performance issue, leading to lots of bloat in the plugins.log file if there are any errors in the models.

Migrated from http://trac.sasview.org/ticket/624
```json
{
    "status": "closed",
    "changetime": "2016-10-09T15:09:59",
    "_ts": "2016-10-09 15:09:59.178511+00:00",
    "description": "Every custom model is being reloaded each time any model is updated.\n\nTo see this, uncomment line 117 of sasview_model.py (in load_custom_model), then use the model editor.\n\nThis is a minor performance issue, leading to lots of bloat in the plugins.log file if there are any errors in the models.",
    "reporter": "pkienzle",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2016-08-19T14:42:47",
    "component": "SasView",
    "summary": "custom models reloaded too often",
    "priority": "critical",
    "keywords": "",
    "milestone": "SasView 4.1.0",
    "owner": "wojciech",
    "type": "defect"
}
```

**Comment by pkienzle** [comment]
Trac update at `2016/09/30 16:25:35`: 
* **pkienzle** commented:

On mac release 4.0b1, multiple graphs are created on load which don't respond to close.


* **pkienzle** changed milestone from "SasView Next Release +1" to "SasView 4.1.0"
* **pkienzle** changed priority from "minor" to "critical"

**Comment by pkienzle** [comment]
Trac update at `2016/09/30 16:34:06`: **pkienzle** commented:

Extra graphs are also loaded in Windows, but at least there they can be closed so it is merely annoying.

**Comment by wpotrzebowski** [comment]
Trac update at `2016/10/06 15:00:58`: 
* **wojciech** changed owner from "" to "wojciech"
* **wojciech** changed status from "new" to "assigned"

**Comment by wpotrzebowski** [comment]
Trac update at `2016/10/06 15:19:48`: **wojciech** commented:

This issue might be fixed in full 4.0 version. 
I cannot reproduce multiple graphs problem and it seems that custom models are loaded only once.

**Comment by wpotrzebowski** [comment]
Trac update at `2016/10/08 19:30:01`: **wojciech** commented:

In changeset 47f2b5d45af5a67c5de39b0539edcbfbe5acbe7c:

```text
#!CommitTicketReference repository="sasview" revision="47f2b5d45af5a67c5de39b0539edcbfbe5acbe7c"
Skipping extra Iq evaluation by not calling draw_model function from set polydisperisty parameters routine, ref #756 and #708
```

**Comment by wpotrzebowski** [comment]
Trac update at `2016/10/09 15:09:59`: 
* **wojciech** changed resolution from "" to "fixed"
* **wojciech** changed status from "assigned" to "closed"
