### ISSUE TITLE
Failing on second FitPage on Windows (Trac #625)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#757]
as of !SasView commit #ee6d4ad9f2c2cbb3879c610a8371043c82a6a45 and sasmodels commit 0dc34c3c362872f348bed26bcbf2bcae9b0455e !SasView now fails (on windows machines) on the second fit page after sending a second data set to be fitted.

Specific sequence (but others cause the problem):
- send data set to fitting
- pick a model (e.g.ellipsoid)
- do a fit (all works fine)
- send second data set to fitting (creates a fit page 2)
- choose a model (e.g. ellipsoid)

At this point an error is thrown though the model and parameters appear to load, though neither a fit line nor residuals show up.  Pressing fit just throws another error .

Error (which is thrown twice each time) is:

```text
 Traceback (most recent call last):
   File "sas\sascalc\data_util\calcthread.pyc", line 268, in _run
 LogicError: clEnqueueReadBuffer failed: invalid value
```

playing around in various ways can give longer errors but all start with a calcthread.pyc error so sounds like a thread issue?

NOTES
1 Opening a 3^rd^ fit page seems to work ok
2 Opening a 2^nd^ fit page and loading a model works, the error being thrown now when a data set is sent to that fitpage.

Migrated from http://trac.sasview.org/ticket/625
```json
{
    "status": "closed",
    "changetime": "2016-08-29T04:59:33",
    "_ts": "2016-08-29 04:59:33.463820+00:00",
    "description": "as of !SasView commit #ee6d4ad9f2c2cbb3879c610a8371043c82a6a45 and sasmodels commit 0dc34c3c362872f348bed26bcbf2bcae9b0455e !SasView now fails (on windows machines) on the second fit page after sending a second data set to be fitted.\n\nSpecific sequence (but others cause the problem):\n- send data set to fitting\n- pick a model (e.g.ellipsoid)\n- do a fit (all works fine)\n- send second data set to fitting (creates a fit page 2)\n- choose a model (e.g. ellipsoid)\n\nAt this point an error is thrown though the model and parameters appear to load, though neither a fit line nor residuals show up.  Pressing fit just throws another error .\n\nError (which is thrown twice each time) is:\n{{{\n Traceback (most recent call last):\n   File \"sas\\sascalc\\data_util\\calcthread.pyc\", line 268, in _run\n LogicError: clEnqueueReadBuffer failed: invalid value\n}}}\n\nplaying around in various ways can give longer errors but all start with a calcthread.pyc error so sounds like a thread issue?\n\nNOTES\n1 Opening a 3^rd^ fit page seems to work ok\n2 Opening a 2^nd^ fit page and loading a model works, the error being thrown now when a data set is sent to that fitpage.",
    "reporter": "butler",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2016-08-21T17:49:46",
    "component": "SasView",
    "summary": "Failing on second FitPage on Windows",
    "priority": "blocker",
    "keywords": "",
    "milestone": "SasView 4.0.0",
    "owner": "",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2016/08/21 18:59:38`: 
* **butler** changed description from:

> as of commit number !SasView commit #ee6d4ad9f2c2cbb3879c610a8371043c82a6a45 and sasmodels commit 0dc34c3c362872f348bed26bcbf2bcae9b0455e !SasView now fails on the second fit page after sending a second data set to be fitted.
> 
> Specific sequence (but others cause the problem):
> - send data set to fitting
> - pick a model (e.g.ellipsoid)
> - do a fit (all works fine)
> - send second data set to fitting (creates a fit page 2)
> - choose a model (e.g. ellipsoid)
> 
> At this point an error is thrown though the model and parameters appear to load, though neither a fit line nor residuals show up.  Pressing fit just throws another error .
> 
> Error (which is thrown twice each time) is:
> {{{
>  Traceback (most recent call last):
>    File "sas\sascalc\data_util\calcthread.pyc", line 268, in _run
>  LogicError: clEnqueueReadBuffer failed: invalid value
> }}}
> 
> playing around in various ways can give longer errors but all start with a calcthread.pyc error so sounds like a thread issue?
> 
> NOTES
> 1 Opening a 3^rd^ fit page seems to work ok
> 2 Opening a 2^nd^ fit page and loading a model works, the error being thrown now when a data set is sent to that fitpage.

to:

> as of !SasView commit #ee6d4ad9f2c2cbb3879c610a8371043c82a6a45 and sasmodels commit 0dc34c3c362872f348bed26bcbf2bcae9b0455e !SasView now fails (on windows machines) on the second fit page after sending a second data set to be fitted.
> 
> Specific sequence (but others cause the problem):
> - send data set to fitting
> - pick a model (e.g.ellipsoid)
> - do a fit (all works fine)
> - send second data set to fitting (creates a fit page 2)
> - choose a model (e.g. ellipsoid)
> 
> At this point an error is thrown though the model and parameters appear to load, though neither a fit line nor residuals show up.  Pressing fit just throws another error .
> 
> Error (which is thrown twice each time) is:
> {{{
>  Traceback (most recent call last):
>    File "sas\sascalc\data_util\calcthread.pyc", line 268, in _run
>  LogicError: clEnqueueReadBuffer failed: invalid value
> }}}
> 
> playing around in various ways can give longer errors but all start with a calcthread.pyc error so sounds like a thread issue?
> 
> NOTES
> 1 Opening a 3^rd^ fit page seems to work ok
> 2 Opening a 2^nd^ fit page and loading a model works, the error being thrown now when a data set is sent to that fitpage.


* **butler** changed summary from "Failing on second FitPage" to "Failing on second FitPage on Windows"

**Comment by pkienzle** [comment]
Trac update at `2016/08/25 03:10:52`: **pkienzle** commented:

Could not reproduce (on Mac, using run.py).

We may need to send all communication to a GPU device through a specific thread.  This can be isolated to just sasmodels.kernelcl by setting up one thread per device and communicating to that thread via a queue.

Prior to implementing complicated queuing operations, we can try checking if there is an overlap between operations from different threads.  Do the following:

```text
cd sasmodels
git status
git pull
git checkout polydisp
git pull
cd ..\sasview
python run.py
```
This will print start...end operation pairs, which all should share the same thread id, with no other thread ids between.

It is very unlikely that this will show any problems, but if it does it will be valuable to know.

**Comment by butlerpd** [comment]
Trac update at `2016/08/29 04:59:33`: 
* **butler** commented:

This was totally reproducible (repeated at least half a dozen times).  with latest version (including the fix to include dlls back windows build 466 of Aug 25, 2016 off of commit eb38181da9eb98b299ea173789e143dd52710fae) I can no longer reproduce this error. Further have exercised the fitting module quite a bit without seeing any such errors.  Am going to call this now fixed and closed the ticket.


* **butler** changed resolution from "" to "fixed"
* **butler** changed status from "new" to "closed"
