### ISSUE TITLE
Update scipy to 0.18.0 (Trac #626)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#758]
!SasView currently ships with scipy 0.16.0, and anyone building against the Anaconda install only has 0.15.1. Lewis' Corfunc analysis uses the bounds argument on the leastsq fitter which is only available from 0.18.0 so before the Corfunc branch is merged we need to upgrade the default scipy to 0.18.0.

Migrated from http://trac.sasview.org/ticket/626
```json
{
    "status": "closed",
    "changetime": "2016-10-14T12:49:42",
    "_ts": "2016-10-14 12:49:42.675036+00:00",
    "description": "!SasView currently ships with scipy 0.16.0, and anyone building against the Anaconda install only has 0.15.1. Lewis' Corfunc analysis uses the bounds argument on the leastsq fitter which is only available from 0.18.0 so before the Corfunc branch is merged we need to upgrade the default scipy to 0.18.0.",
    "reporter": "smk78",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Admin",
    "time": "2016-08-23T14:55:21",
    "component": "SasView",
    "summary": "Update scipy to 0.18.0",
    "priority": "blocker",
    "keywords": "",
    "milestone": "SasView 4.1.0",
    "owner": "wojciech",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2016/09/06 00:20:24`: **butler** changed milestone from "SasView Next Release +1" to "SasView 4.1.0"

**Comment by wpotrzebowski** [comment]
Trac update at `2016/10/04 19:47:46`: 
* **wojciech** changed owner from "" to "wojciech"
* **wojciech** changed status from "new" to "assigned"

**Comment by wpotrzebowski** [comment]
Trac update at `2016/10/05 13:16:18`: **wojciech** commented:

Mac build server has been updated. Piotr is working on Windows.

**Comment by rozyczko** [comment]
Trac update at `2016/10/05 20:58:52`: **piotr** commented:

new scipy requires new numpy
new numpy for standalone python available from Gholke with MKL only -> need to modify setup_exe.py
new numpy and py2exe cause a console window to pop up with a warning ( http://stackoverflow.com/questions/22412984/omp-warning-when-numpy-1-8-0-is-packaged-with-py2exe )
Multiple runtime issues

It will be more proper to move to anaconda 64, where numpy/scipy are nicely integrated.

**Comment by rozyczko** [comment]
Trac update at `2016/10/07 23:48:41`: **piotr** commented:

Jenkins host SasView_Win7_Test runs Anaconda 64 with the most recent scipy/numpy.
This produces a usable setup.

Please test the installer and the resulting installation - if stable we'll switch to the Anaconda setup on the main host and disable standalone python27

**Comment by rozyczko** [comment]
Trac update at `2016/10/14 12:49:20`: **piotr** commented:

Win7 32 bit is working fine now.

**Comment by rozyczko** [comment]
Trac update at `2016/10/14 12:49:42`: 
* **piotr** changed resolution from "" to "fixed"
* **piotr** changed status from "assigned" to "closed"
