### ISSUE TITLE
rev-parse problem when running from non-git/unitilized directory (Trac #630)

### ISSUE THREAD

**Issue by wpotrzebowski** [SasView/sasview#762]
When running SASVIEW from builds or from run.py it complains.  
WARNING:root:Error while determining build number  Command '['git', 'rev-parse', 'HEAD']' returned non-zero exit status 1

This is because it runs from non-git repository (from build servers) or there is no build number initialized (when running from run.py). When running from run.py the side effect is that it doesn't log to sasview.log.

The potential fix to the problem may involve pass in expect statement of sasview/__init__.py instead of:
import logging
import sys
logging.warning("Error while determining build number\n  %s" % sys.exc_value) 

Migrated from http://trac.sasview.org/ticket/630
```json
{
    "status": "closed",
    "changetime": "2016-08-25T13:38:19",
    "_ts": "2016-08-25 13:38:19.995392+00:00",
    "description": "When running SASVIEW from builds or from run.py it complains.  \nWARNING:root:Error while determining build number  Command '['git', 'rev-parse', 'HEAD']' returned non-zero exit status 1\n\nThis is because it runs from non-git repository (from build servers) or there is no build number initialized (when running from run.py). When running from run.py the side effect is that it doesn't log to sasview.log.\n\nThe potential fix to the problem may involve pass in expect statement of sasview/__init__.py instead of:\nimport logging\nimport sys\nlogging.warning(\"Error while determining build number\\n  %s\" % sys.exc_value) \n\n",
    "reporter": "wojciech",
    "cc": "",
    "resolution": "duplicate",
    "workpackage": "SasView Bug Fixing",
    "time": "2016-08-25T12:06:06",
    "component": "SasView",
    "summary": "rev-parse problem when running from non-git/unitilized directory",
    "priority": "minor",
    "keywords": "",
    "milestone": "SasView 4.0.0",
    "owner": "",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2016/08/25 13:24:14`: **butler** commented:

Is this  not the same issue as ticket #759?  Also the build version presumably will mostly run on users machines who don't have git installed at all.  As you can see from comments on #759 I am wondering if the growing code to check which eventually fails is what is causing the startup of !SasView to slow down on windows machines.  I have noticed that recent builds take an inordinate amount of time to start compared to the past (and not just the first time as with Mac builds).

One question: would it be better to move pulling the commit hash to the build script? Of course I guess then the build would need to write a number back into init.py which is now different from the git repo version? Or perhaps have it run only if a certain environment variable is set (which the build script does)?  Just some random thoughts.

**Comment by wpotrzebowski** [comment]
Trac update at `2016/08/25 13:38:19`: 
* **wojciech** changed resolution from "" to "duplicate"
* **wojciech** changed status from "new" to "closed"
