### ISSUE TITLE
Batch fitting problem when switching to single fit and back (Trac #632)

### ISSUE THREAD

**Issue by ajj** [SasView/sasview#764]
From Paul testing on 28th August:

"Batch fit - works pretty well only niggle is that if one loads a batch fit then switches to a single fit (to double check starting parameters for example) then comes back to the batch - the option for "chain fitting" is greyed out an not available and I could not make it come back."

Need to work out what the "correct" workflow/behaviour is here. May not have been an original use case.

Migrated from http://trac.sasview.org/ticket/632
```json
{
    "status": "closed",
    "changetime": "2016-09-05T01:37:44",
    "_ts": "2016-09-05 01:37:44.976973+00:00",
    "description": "From Paul testing on 28th August:\n\n\"Batch fit - works pretty well only niggle is that if one loads a batch fit then switches to a single fit (to double check starting parameters for example) then comes back to the batch - the option for \"chain fitting\" is greyed out an not available and I could not make it come back.\"\n\nNeed to work out what the \"correct\" workflow/behaviour is here. May not have been an original use case.",
    "reporter": "ajj",
    "cc": "",
    "resolution": "invalid",
    "workpackage": "SasView Bug Fixing",
    "time": "2016-08-29T19:49:55",
    "component": "SasView",
    "summary": "Batch fitting problem when switching to single fit and back",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.0.0",
    "owner": "",
    "type": "defect"
}
```

**Comment by rozyczko** [comment]
Trac update at `2016/09/02 12:16:17`: 
* **piotr** changed _comment0 from:

> Can't seem to be able to reproduce that
> 
> - build 475 on windows 7
> - loaded 2 test files, sent to batch fitting (Fractal), Fit
> - Fitting/Chain Fitting: active
> - Selected FitPage1
> - Fitting/Chain Fitting: greyed out
> - Selected BatchPage1
> - Fitting/Chain Fitting: active
> 
> Which build did you test? I also looked at 468, which also works.
> 

to:

> 1472818664123834


* **piotr** commented:

Can't seem to be able to reproduce that

- build 475 on windows 7
- loaded 2 test files, sent to batch fitting (Fractal), Fit
- Fitting /Chain Fitting: active
- Selected FitPage1
- Fitting /Chain Fitting: greyed out
- Selected BatchPage1
- Fitting /Chain Fitting: active

Which build did you test? I also looked at 468, which also works.

**Comment by butlerpd** [comment]
Trac update at `2016/09/02 12:59:47`: **butler** commented:

Will test -- was using ESS Windows build 466 which was the candidate release at the time. We then added two fixes before making the actual beta.  Will check again on my machine with 466, 468 and most recent.  If it is now fixed I will close otherwise will updated this ticket again.

**Comment by butlerpd** [comment]
Trac update at `2016/09/05 01:37:44`: 
* **butler** commented:

Have done some extensive testing now with 466, 468 and 477 windows builds (Aug 25, Aug 30 and Sep 2, 2016 ESS builds) and have not been able to reproduce the problem mentioned.  However, there is some small problem with the logic that allows the "chain fitting" to be active on a fit page until the batch fit tab is brought in focus then back to the fit tab at which point it is almost always greyed out again.

While this points to some convoluted logic in the GUI that could lead to more serious issues and should be cleaned up, I was unable to find anything more serious.  Am thus closing this ticket and opening a new one for a future release


* **butler** changed resolution from "" to "invalid"
* **butler** changed status from "new" to "closed"
