### ISSUE TITLE
"invalid q range: qmin must be smaller than qmax" on a number of models (Trac #636)

### ISSUE THREAD

**Issue by ajj** [SasView/sasview#768]
From Paul Butler's  testing on 28th August 2016:

Spherical_sld, lamellar_stack_paracrystal, stacked_disk and square_well all generate a very strange error before appearing to work: "invalid q range: qmin must be smaller than qmax," but then appear to work.  Note that in these tests the condition (qmin is smaller than qmax) is always true as it is just the default qmin and qmax in the fitpage.

Migrated from http://trac.sasview.org/ticket/636
```json
{
    "status": "closed",
    "changetime": "2016-08-30T19:12:07",
    "_ts": "2016-08-30 19:12:07.467263+00:00",
    "description": "From Paul Butler's  testing on 28th August 2016:\n\nSpherical_sld, lamellar_stack_paracrystal, stacked_disk and square_well all generate a very strange error before appearing to work: \"invalid q range: qmin must be smaller than qmax,\" but then appear to work.  Note that in these tests the condition (qmin is smaller than qmax) is always true as it is just the default qmin and qmax in the fitpage.\n\n",
    "reporter": "ajj",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2016-08-29T20:01:52",
    "component": "SasView",
    "summary": "\"invalid q range: qmin must be smaller than qmax\" on a number of models",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.0.0",
    "owner": "",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2016/08/29 22:03:56`: **butler** changed description from:

> From Paul Butler's  testing on 28th August 2016:
> 
> "On the other hand spherical_sld, lamellar_stack_paracrystal, stacked_disk and square_well all generate a very strange error before giving appearing to work "invalid q range: qmin must be smaller than qmax" note that in these tests the condition is always true as it is just the default qmin and qmax in the fitpage."
> 
> 

to:

> From Paul Butler's  testing on 28th August 2016:
> 
> Spherical_sld, lamellar_stack_paracrystal, stacked_disk and square_well all generate a very strange error before appearing to work: "invalid q range: qmin must be smaller than qmax," but then appear to work.  Note that in these tests the condition (qmin is smaller than qmax) is always true as it is just the default qmin and qmax in the fitpage.
> 
>

**Comment by pkienzle** [comment]
Trac update at `2016/08/30 16:53:29`: **pkienzle** commented:

Happens on all models if Value matches Min or Max.  For example, set background to 0.

**Comment by pkienzle** [comment]
Trac update at `2016/08/30 19:12:07`: 
* **pkienzle** changed resolution from "" to "fixed"
* **pkienzle** changed status from "new" to "closed"
