### ISSUE TITLE
Add timestamp to console log entries (Trac #637)

### ISSUE THREAD

**Issue by ajj** [SasView/sasview#769]
It is hard to read the log - we should have the entries timestamped.

NB : the new GUI in QT should have a much better console which will ameliorate this somewhat.

Migrated from http://trac.sasview.org/ticket/637
```json
{
    "status": "closed",
    "changetime": "2016-10-06T15:25:24",
    "_ts": "2016-10-06 15:25:24.432676+00:00",
    "description": "It is hard to read the log - we should have the entries timestamped.\n\nNB : the new GUI in QT should have a much better console which will ameliorate this somewhat.",
    "reporter": "ajj",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView GUI Enhancements",
    "time": "2016-08-29T20:03:44",
    "component": "SasView",
    "summary": "Add timestamp to console log entries",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.1.0",
    "owner": "piotr",
    "type": "enhancement"
}
```

**Comment by butlerpd** [comment]
Trac update at `2016/09/05 03:57:50`: **butler** changed milestone from "SasView Next Release +1" to "SasView 4.1.0"

**Comment by rozyczko** [comment]
Trac update at `2016/10/06 15:17:25`: 
* **piotr** changed owner from "" to "piotr"
* **piotr** changed status from "new" to "accepted"

**Comment by rozyczko** [comment]
Trac update at `2016/10/06 15:25:24`: 
* **piotr** changed resolution from "" to "fixed"
* **piotr** changed status from "accepted" to "closed"
