### ISSUE TITLE
Ensure future backward compatibility (forward compatibility?) of saved projects/analysis (Trac #643)

### ISSUE THREAD

**Issue by ajj** [SasView/sasview#775]
Any projects saved from the release version of 4.0 should be compatible with future versions of sasview.

This means primarily that model parameter names will be frozen for some time.

Thus we need to audit:

(a) models - to make sure that they are all following our new parameter naming guidelines
(b) tickets - to find any outstanding issues that could cause future problems with compatibility of saved states. These will primarily be any tickets that touch on built in models.

Migrated from http://trac.sasview.org/ticket/643
```json
{
    "status": "closed",
    "changetime": "2016-10-01T21:26:10",
    "_ts": "2016-10-01 21:26:10.539668+00:00",
    "description": "Any projects saved from the release version of 4.0 should be compatible with future versions of sasview.\n\nThis means primarily that model parameter names will be frozen for some time.\n\nThus we need to audit:\n\n(a) models - to make sure that they are all following our new parameter naming guidelines\n(b) tickets - to find any outstanding issues that could cause future problems with compatibility of saved states. These will primarily be any tickets that touch on built in models.",
    "reporter": "ajj",
    "cc": "",
    "resolution": "obsolete",
    "workpackage": "SasView Bug Fixing",
    "time": "2016-08-31T16:01:08",
    "component": "SasView",
    "summary": "Ensure future backward compatibility (forward compatibility?) of saved projects/analysis",
    "priority": "blocker",
    "keywords": "",
    "milestone": "SasView 4.0.0",
    "owner": "",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2016/09/05 03:28:51`: **butler** changed priority from "major" to "critical"

**Comment by butlerpd** [comment]
Trac update at `2016/09/05 14:39:25`: **butler** changed priority from "critical" to "blocker"

**Comment by ajj** [comment]
Trac update at `2016/10/01 21:26:10`: 
* **ajj** commented:

This ticket expires with the release of 4.0 ... Hope we haven't missed anything!


* **ajj** changed resolution from "" to "obsolete"
* **ajj** changed status from "new" to "closed"
