### ISSUE TITLE
Need to add minimum documentation on writing new models (Trac #651)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#782]
At a minimum the model editing documentation needs to be updated to reflect the new model structure and point to external web pages with information on how to write as well as to github repo of models that can be downloaded and used either as templates or to modify.

Eventually a more robust set of instructions would be useful.  Suggest doing the minimum + for this release and closing this ticket.  Once we know what we want we can open a new 4.1 ticket.

Note: there is some merit to using a web page, or better yet a wiki, to host the detailed instructions rather than bundling them.  It makes them more easily updatable between releases.  There must however be a solid set of build in instructions for when no internet connection is availble.

Migrated from http://trac.sasview.org/ticket/651
```json
{
    "status": "closed",
    "changetime": "2016-10-01T20:06:57",
    "_ts": "2016-10-01 20:06:57.877019+00:00",
    "description": "At a minimum the model editing documentation needs to be updated to reflect the new model structure and point to external web pages with information on how to write as well as to github repo of models that can be downloaded and used either as templates or to modify.\n\nEventually a more robust set of instructions would be useful.  Suggest doing the minimum + for this release and closing this ticket.  Once we know what we want we can open a new 4.1 ticket.\n\nNote: there is some merit to using a web page, or better yet a wiki, to host the detailed instructions rather than bundling them.  It makes them more easily updatable between releases.  There must however be a solid set of build in instructions for when no internet connection is availble.",
    "reporter": "butler",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Documentation",
    "time": "2016-09-05T23:38:54",
    "component": "SasView",
    "summary": "Need to add minimum documentation on writing new models",
    "priority": "critical",
    "keywords": "",
    "milestone": "SasView 4.0.0",
    "owner": "",
    "type": "enhancement"
}
```

**Comment by butlerpd** [comment]
Trac update at `2016/09/05 23:40:19`: **butler** changed priority from "major" to "critical"

**Comment by pkienzle** [comment]
Trac update at `2016/09/12 05:08:52`: 
* **pkienzle** changed resolution from "" to "fixed"
* **pkienzle** changed status from "new" to "closed"

**Comment by ajj** [comment]
Trac update at `2016/10/01 20:06:57`: 
* **ajj** commented:

In changeset 41e7f2e7bf3da407ccc23d81cdbc337a27eacecc:

```text
#!CommitTicketReference repository="sasmodels" revision="41e7f2e7bf3da407ccc23d81cdbc337a27eacecc"
Merge branch 'master' into ticket651
```


* **ajj** commented:

In changeset 26d93689407c804e76d8b47e6be5dae7f47ceaa8:

```text
#!CommitTicketReference repository="sasmodels" revision="26d93689407c804e76d8b47e6be5dae7f47ceaa8"
Merge branch 'ticket651'
```
