### ISSUE TITLE
SasView crashing when computer sleeps. (Trac #653)

### ISSUE THREAD

**Issue by ajj** [SasView/sasview#784]
Karen Edler has reported a couple of problems in the beta. One is:

"Particularly since I still manage to crash it not infrequently – e.g. By making my computer sleep while I walk home"

Migrated from http://trac.sasview.org/ticket/653
```json
{
    "status": "closed",
    "changetime": "2017-02-06T14:35:36",
    "_ts": "2017-02-06 14:35:36.520729+00:00",
    "description": "Karen Edler has reported a couple of problems in the beta. One is:\n\n\"Particularly since I still manage to crash it not infrequently \u2013 e.g. By making my computer sleep while I walk home\"",
    "reporter": "ajj",
    "cc": "",
    "resolution": "wontfix",
    "workpackage": "SasView Bug Fixing",
    "time": "2016-09-08T12:06:45",
    "component": "SasView",
    "summary": "SasView crashing when computer sleeps.",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.1.0",
    "owner": "ajj",
    "type": "defect"
}
```

**Comment by rozyczko** [comment]
Trac update at `2016/09/13 08:31:08`: **piotr** commented:

Any possibility of learning what the customer hardware details are?
I've been testing it locally on Win7/64 with beta and can't reproduce the failures so far.

**Comment by wpotrzebowski** [comment]
Trac update at `2016/09/27 07:40:33`: **wojciech** commented:

I cannot reproduce it on Mac OSX 10.11 either

**Comment by butlerpd** [comment]
Trac update at `2016/09/27 14:38:44`: 
* **butler** commented:

cannot seem to reproduced. Steve, Wojcieck and Piotr have done a fair amount of testing on mac and various pcs and PB tried a few times on windows 10 but it always seems to work.  Need to talk to Karen to find out what is going on.  Meanwhile move to 4.1


* **butler** changed milestone from "SasView 4.0.0" to "SasView 4.1.0"

**Comment by smk78** [comment]
Trac update at `2016/10/07 00:48:19`: 
* **smk78** changed owner from "" to "ajj"
* **smk78** changed priority from "critical" to "major"
* **smk78** changed status from "new" to "assigned"

**Comment by ajj** [comment]
Trac update at `2017/02/06 14:35:36`: 
* **ajj** commented:

Completely unreproducible.


* **ajj** changed resolution from "" to "wontfix"
* **ajj** changed status from "assigned" to "closed"
