### ISSUE TITLE
Saving analysis or project doesn't (Trac #654)

### ISSUE THREAD

**Issue by ajj** [SasView/sasview#785]
Karen Edler reported:

" Is there any way to get the beta to actually save your work such that it can be re-opened? Been doing some !SasView fitting using the beta but the fact you lose everything when you re-start the program, even if you saved it, is a real turn off. (particularly since I still manage to crash it not infrequently – e.g. By making my computer sleep while I walk home…)"

Migrated from http://trac.sasview.org/ticket/654
```json
{
    "status": "closed",
    "changetime": "2016-10-20T07:04:49",
    "_ts": "2016-10-20 07:04:49.765610+00:00",
    "description": "Karen Edler reported:\n\n\" Is there any way to get the beta to actually save your work such that it can be re-opened? Been doing some !SasView fitting using the beta but the fact you lose everything when you re-start the program, even if you saved it, is a real turn off. (particularly since I still manage to crash it not infrequently \u2013 e.g. By making my computer sleep while I walk home\u2026)\"",
    "reporter": "ajj",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2016-09-08T12:08:56",
    "component": "SasView",
    "summary": "Saving analysis or project doesn't",
    "priority": "critical",
    "keywords": "",
    "milestone": "SasView 4.0.0",
    "owner": "krzywon",
    "type": "defect"
}
```

**Comment by ajj** [comment]
Trac update at `2016/09/08 12:10:28`: 
* **ajj** changed owner from "" to "krzywon"
* **ajj** changed status from "new" to "assigned"

**Comment by butlerpd** [comment]
Trac update at `2016/09/09 01:43:26`: **butler** changed description from:

> Karen Edler reported:
> 
> " Is there any way to get the beta to actually save your work such that it can be re-opened? Been doing some SasView fitting using the beta but the fact you lose everything when you re-start the program, even if you saved it, is a real turn off. (particularly since I still manage to crash it not infrequently – e.g. By making my computer sleep while I walk home…)"

to:

> Karen Edler reported:
> 
> " Is there any way to get the beta to actually save your work such that it can be re-opened? Been doing some !SasView fitting using the beta but the fact you lose everything when you re-start the program, even if you saved it, is a real turn off. (particularly since I still manage to crash it not infrequently – e.g. By making my computer sleep while I walk home…)"

**Comment by ajj** [comment]
Trac update at `2016/10/20 07:04:49`: **ajj** commented:

4.0 release does indeed allow the file attached to this ticket to now be opened.

Confirming that this is indeed fixed.

**Comment by ajj** [comment]
Trac update at `2016/10/20 07:05:43`: 
* **ajj** changed attachment from "" to "sasview_rods.svs"
* **ajj** commented:

Saved sasview project that causes 3.1.2 and 4.0 alpha to freeze on attempting load.
