### ISSUE TITLE
ASCII reader very broken (Trac #658)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#789]
As reported by Steve king on ticket #746 if
  Any non-I(Q) data ASCII files that just happen to have space or tab delimited numbers in the opening lines then these get loaded as data (the first pair of numbers as X & Y). So examples of this include BSL/OTOKO 'header' files, eg: this CORFUNC file had the extension .CF1

     201       1       1       1       0       0       0       0       0       0
     C:\Temp\X2
  where it took the 201 & 1 as X & Y, or perhaps a temporary parameter file such     as this one which had the extension .txt:
     0.200000E+03
     0.100000E+01
     0.522096E+00  0.211909E-01  0.396440E-02  0.101775E-02  0.307366E-03
  where it took the 0.522096E+00 0.211909E-01 as X & Y.
 I suspect the ASCII reader is just a little too embracing. Maybe if it checked   for two consecutive lines with pairs of numbers, or something like that? But tricky.

This should actually not happen -- The whole point of the ASCII reader has ALWAYS been that it should cover 95% of cases by looking for X (where I think X is 6 now) rows with EXACTLY the same number of columns of numbers only. Not perfect but as close as one can get. 

In fact it appears that the reader is completely broken and reads any row that contains 2 or more numbers (at least if no text is on the line) as valid data ... '''even''' if the number of columns varies (so will take line 1 with 4 columns and line 2 with 2 and be happy)

As Steve points out this bug seems to have existed as far back as 2.2.1.  Looking at the code it clearly has the infrastructure and seems to be set to an X of 5, but somehow the code is seriously flawed or being partially bypassed.

Since this is a pure ASCII reader but and unrelated to the folder reading issue of #746 am creating a new ticket.  I add here the files attached to that ticket as examples that get misread.

Migrated from http://trac.sasview.org/ticket/658
```json
{
    "status": "closed",
    "changetime": "2016-09-14T13:47:57",
    "_ts": "2016-09-14 13:47:57.435291+00:00",
    "description": "As reported by Steve king on ticket #614 if\n  Any non-I(Q) data ASCII files that just happen to have space or tab delimited numbers in the opening lines then these get loaded as data (the first pair of numbers as X & Y). So examples of this include BSL/OTOKO 'header' files, eg: this CORFUNC file had the extension .CF1\n\n     201       1       1       1       0       0       0       0       0       0\n     C:\\Temp\\X2\n  where it took the 201 & 1 as X & Y, or perhaps a temporary parameter file such     as this one which had the extension .txt:\n     0.200000E+03\n     0.100000E+01\n     0.522096E+00  0.211909E-01  0.396440E-02  0.101775E-02  0.307366E-03\n  where it took the 0.522096E+00 0.211909E-01 as X & Y.\n I suspect the ASCII reader is just a little too embracing. Maybe if it checked   for two consecutive lines with pairs of numbers, or something like that? But tricky.\n\nThis should actually not happen -- The whole point of the ASCII reader has ALWAYS been that it should cover 95% of cases by looking for X (where I think X is 6 now) rows with EXACTLY the same number of columns of numbers only. Not perfect but as close as one can get. \n\nIn fact it appears that the reader is completely broken and reads any row that contains 2 or more numbers (at least if no text is on the line) as valid data ... '''even''' if the number of columns varies (so will take line 1 with 4 columns and line 2 with 2 and be happy)\n\nAs Steve points out this bug seems to have existed as far back as 2.2.1.  Looking at the code it clearly has the infrastructure and seems to be set to an X of 5, but somehow the code is seriously flawed or being partially bypassed.\n\nSince this is a pure ASCII reader but and unrelated to the folder reading issue of #614 am creating a new ticket.  I add here the files attached to that ticket as examples that get misread.\n",
    "reporter": "butler",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2016-09-12T03:40:26",
    "component": "SasView",
    "summary": "ASCII reader very broken",
    "priority": "critical",
    "keywords": "",
    "milestone": "SasView 4.0.0",
    "owner": "krzywon",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2016/09/12 03:41:12`: 
* **butler** changed attachment from "" to "X27000.CF1"
* **butler** commented:

OTOKO format header file (ASCII)

**Comment by butlerpd** [comment]
Trac update at `2016/09/12 03:41:59`: 
* **butler** changed attachment from "" to "extract.txt"
* **butler** commented:

Corfunc parameter file (ASCII)

**Comment by butlerpd** [comment]
Trac update at `2016/09/12 03:42:32`: 
* **butler** changed attachment from "" to "New Text Document.txt"
* **butler** commented:

Made up bogus data file (ASCII)

**Comment by butlerpd** [comment]
Trac update at `2016/09/12 03:43:04`: 
* **butler** changed attachment from "" to "AnOnerousExample.txt"
* **butler** commented:

Adding lines to the corfunc parameter fie

**Comment by butlerpd** [comment]
Trac update at `2016/09/12 03:44:30`: 
* **butler** changed attachment from "" to "AnOnerousExample2.txt"
* **butler** commented:

Another alteration of corfunc parameter file demonstrating the strange logic

**Comment by rozyczko** [comment]
Trac update at `2016/09/13 08:29:20`: **piotr** commented:

Fixing the reader is not difficult given clear set of rules expected.

- do we want it to parse x,y only for consecutive lines of same token length?
- do we want to drop the current x,y once an invalid line is found (as in AnOnerousExample2)?
- do we want to use x,y only when there are > 1 (consecutive) lines with the same number of tokens?
- any other requirements?

I agree the current implementation of the ASCII reader is pretty inefficient and should be at least partially rewritten, so let's do it properly.

**Comment by butlerpd** [comment]
Trac update at `2016/09/13 12:48:22`: 
* **butler** changed owner from "" to "krzywon"
* **butler** changed status from "new" to "assigned"

**Comment by butlerpd** [comment]
Trac update at `2016/09/14 04:16:43`: **butler** commented:

Actually for all the examples given they should ALL be "not a data file."  The rules were: data must have 5 or more consecutive lines (I thought it was 6 but looking at the code briefly it seems it was 5) that contain 
1) two or more numbers
2) ONLY numbers
3) EXACTLY THE SAME number of numbers

This last is predicated on the fact that any real data will be in a consistent format whether 2, 3, 4, 6 or even 10 columns all lines will have the same format.

The reader rejects everything before the first occurence of such 5 consecutive lines.  It then reads lines consecutively till it hits an EOF or it hits a line wich does no longer meets the specs above.  That line and anything afterwards would be considered footer information.

The reader was never designed to look for more than one data set in a generic ASCII file and probably shouldn't.
