### ISSUE TITLE
check polydispersity distributions (Trac #659)

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#790]
Gaussian polydispersity seems to be working, but all others need to be tested.  In particular, lognormal weights don't look lognormal.

sascomp gives different answers between sasmodels and sasview 3.x when testing with lognormal, rectangle and schultz distributions.

Users report that the array distribution is not working with sasview 4.0. See ticket #786.

Migrated from http://trac.sasview.org/ticket/659
```json
{
    "status": "closed",
    "changetime": "2016-09-27T21:48:38",
    "_ts": "2016-09-27 21:48:38.489985+00:00",
    "description": "Gaussian polydispersity seems to be working, but all others need to be tested.  In particular, lognormal weights don't look lognormal.\n\nsascomp gives different answers between sasmodels and sasview 3.x when testing with lognormal, rectangle and schultz distributions.\n\nUsers report that the array distribution is not working with sasview 4.0. See ticket #655.",
    "reporter": "pkienzle",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2016-09-12T16:59:44",
    "component": "SasView",
    "summary": "check polydispersity distributions",
    "priority": "blocker",
    "keywords": "",
    "milestone": "SasView 4.0.0",
    "owner": "pkienzle",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2016/09/13 12:48:53`: 
* **butler** changed owner from "" to "pkienzle"
* **butler** changed status from "new" to "assigned"

**Comment by butlerpd** [comment]
Trac update at `2016/09/13 15:20:59`: 
* **butler** commented:

The array issue (#786) was reported by Kriechbaum, Manfred <manfred.kriechbaum@tugraz.at>  
 
  Selecting the option "Polydispersity on / Array" and reading in a 2 column file (representing the size distribution) seems to have no effect on the calculation ("Compute") in version 4.0 (in 3.1.2 it does however).


* **butler** changed description from:

> Gaussian polydispersity seems to be working, but all others need to be tested.  In particular, lognormal weights don't look lognormal.
> 
> sascomp gives different answers between sasmodels and sasview 3.x when testing with lognormal, rectangle and schultz distributions.
> 
> Users report that the array distribution is not working with sasview 4.0.

to:

> Gaussian polydispersity seems to be working, but all others need to be tested.  In particular, lognormal weights don't look lognormal.
> 
> sascomp gives different answers between sasmodels and sasview 3.x when testing with lognormal, rectangle and schultz distributions.
> 
> Users report that the array distribution is not working with sasview 4.0. See ticket #655.

**Comment by pkienzle** [comment]
Trac update at `2016/09/26 20:50:39`: **pkienzle** commented:

Make sure project/analysis save/load and copy/paste params work with the different distribution types (array, gaussian, schulz, rectangle, lognormal).  Make sure Npts, Nsigmas, min, max and PD are properly preserved.

It is currently failing to load distributions of types other than gaussian.

**Comment by pkienzle** [comment]
Trac update at `2016/09/27 21:48:38`: 
* **pkienzle** changed resolution from "" to "fixed"
* **pkienzle** changed status from "assigned" to "closed"
