### ISSUE TITLE
Allow editing of C models from SasView GUI tools (Trac #662)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#793]
Advanced editor does not allow you currently to open the associated C file and the new model editor does not allow you to create the imbedded C model.  Would be nice for the user.

Migrated from http://trac.sasview.org/ticket/662
```json
{
    "status": "closed",
    "changetime": "2016-10-08T16:24:02",
    "_ts": "2016-10-08 16:24:02.465053+00:00",
    "description": "Advanced editor does not allow you currently to open the associated C file and the new model editor does not allow you to create the imbedded C model.  Would be nice for the user.",
    "reporter": "butler",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView GUI Enhancements",
    "time": "2016-09-13T14:58:52",
    "component": "SasView",
    "summary": "Allow editing of C models from SasView GUI tools",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.1.0",
    "owner": "piotr",
    "type": "enhancement"
}
```

**Comment by rozyczko** [comment]
Trac update at `2016/10/08 13:39:22`: 
* **piotr** changed owner from "" to "piotr"
* **piotr** changed status from "new" to "assigned"

**Comment by rozyczko** [comment]
Trac update at `2016/10/08 16:24:02`: **piotr** commented:

Initial implementation includes added display for a loaded C model (name based on the .py model, not on what the model actually load with IMPORTs...)
The C components of the model shows up in a separate pyconsole tab and can be edited, although no syntax colouring nor intellisense is available, this being a python editor.
Upon 'model check' action, the (saved) C model is recompiled.
