### ISSUE TITLE
opencl wrong for long kernels (Trac #665)

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#796]
On a !MacbookPro (Intel HD 4000 GPU), the 2D barbell model with length pd=0.2 radius pd=0.2 gives the wrong scattering pattern when Npts=300.

It works fine for smaller N or smaller pd.

Check other cards/other platforms.

If it is very common problem, we can fetch the results from the GPU every 1/2 second or so, and sum them on the CPU.

Migrated from http://trac.sasview.org/ticket/665
```json
{
    "status": "closed",
    "changetime": "2016-10-25T18:22:03",
    "_ts": "2016-10-25 18:22:03.558826+00:00",
    "description": "On a !MacbookPro (Intel HD 4000 GPU), the 2D barbell model with length pd=0.2 radius pd=0.2 gives the wrong scattering pattern when Npts=300.\n\nIt works fine for smaller N or smaller pd.\n\nCheck other cards/other platforms.\n\nIf it is very common problem, we can fetch the results from the GPU every 1/2 second or so, and sum them on the CPU.",
    "reporter": "pkienzle",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2016-09-23T18:36:40",
    "component": "SasView",
    "summary": "opencl wrong for long kernels",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.1.0",
    "owner": "wojciech",
    "type": "defect"
}
```

**Comment by pkienzle** [comment]
Trac update at `2016/10/03 21:45:54`: **pkienzle** commented:

Max 4 polydisperse parameters.  Need warnings in GUI if more are selected.

Instead of increasing the number of PD loops in the kernel code, switch to monte carlo integration with importance sampling when more than 4 dimensions.  Do not extend the code to contain one more loop. Not only will this be slower, but it will increase code size and possibly reduce the number of q values that can be evaluated in parallel.

**Comment by pkienzle** [comment]
Trac update at `2016/10/03 21:47:25`: **pkienzle** commented:

Note that the original ticket may already have been fixed, but test before closing.

**Comment by wpotrzebowski** [comment]
Trac update at `2016/10/09 15:27:53`: 
* **wojciech** changed owner from "" to "wojciech"
* **wojciech** changed status from "new" to "assigned"

**Comment by wpotrzebowski** [comment]
Trac update at `2016/10/10 14:06:10`: **wojciech** commented:

Barbell with 2 polydisperisty parameters and Npts=300 returns correct diffraction pattern.
Tested on Iris(TM) Graphics 6100

**Comment by wpotrzebowski** [comment]
Trac update at `2016/10/10 14:14:10`: **wojciech** commented:

Will be good to test it on some windows machine with GPU card before closing

**Comment by pkienzle** [comment]
Trac update at `2016/10/10 14:23:58`: **pkienzle** commented:

Tested again on macbook and it seems to work.  Running long computations definitely slows the machine to a crawl, but does not crash it or render it completely unusable (this was typed while running the above).

Note: May want to maintain a list of supported/unsupported devices. On the Radeon R9 Nano for Windows I sometimes get speckle patterns in 2D.  I also once got an incomplete integration, but was not able to reproduce it.

**Comment by butlerpd** [comment]
Trac update at `2016/10/11 11:54:06`: **butler** changed description from:

> On a MacbookPro (Intel HD 4000 GPU), the 2D barbell model with length pd=0.2 radius pd=0.2 gives the wrong scattering pattern when Npts=300.
> 
> It works fine for smaller N or smaller pd.
> 
> Check other cards/other platforms.
> 
> If it is very common problem, we can fetch the results from the GPU every 1/2 second or so, and sum them on the CPU.

to:

> On a !MacbookPro (Intel HD 4000 GPU), the 2D barbell model with length pd=0.2 radius pd=0.2 gives the wrong scattering pattern when Npts=300.
> 
> It works fine for smaller N or smaller pd.
> 
> Check other cards/other platforms.
> 
> If it is very common problem, we can fetch the results from the GPU every 1/2 second or so, and sum them on the CPU.

**Comment by pkienzle** [comment]
Trac update at `2016/10/25 18:22:03`: 
* **pkienzle** changed resolution from "" to "fixed"
* **pkienzle** changed status from "assigned" to "closed"
