### ISSUE TITLE
pressing enter in fit page computes the model twice (Trac #667)

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#798]
On Mac in Sasview 4.0b1 pressing enter while in the PD value field computes the model twice.

You can see this by putting a trace statement which is called each time the model is evaluated (e.g., in sasmodels/sasview_model.py:~577)

Migrated from http://trac.sasview.org/ticket/667
```json
{
    "status": "closed",
    "changetime": "2016-12-20T09:45:42",
    "_ts": "2016-12-20 09:45:42.302912+00:00",
    "description": "On Mac in Sasview 4.0b1 pressing enter while in the PD value field computes the model twice.\n\nYou can see this by putting a trace statement which is called each time the model is evaluated (e.g., in sasmodels/sasview_model.py:~577)",
    "reporter": "pkienzle",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2016-09-26T20:21:18",
    "component": "SasView",
    "summary": "pressing enter in fit page computes the model twice",
    "priority": "minor",
    "keywords": "",
    "milestone": "SasView 4.1.0",
    "owner": "wojciech",
    "type": "defect"
}
```

**Comment by pkienzle** [comment]
Trac update at `2016/10/06 16:50:00`: **pkienzle** commented:

Also, clicking Compute doesn't notice that the values have changed in the fields.  Only Enter does, and only if values have changed since Compute was last clicked.

For example, click in sld and change value, click in sld_solvent and change value, then click Compute and nothing changes.  At this point, the values are saved so pressing Enter also does not recognize that the values have changed.

**Comment by pkienzle** [comment]
Trac update at `2016/10/27 15:03:06`: **pkienzle** changed milestone from "SasView Next Release +1" to "SasView 4.1.0"

**Comment by pkienzle** [comment]
Trac update at `2016/10/27 15:03:47`: **pkienzle** commented:

Moved to 4.1 since it will also solve ticket http://trac.sasview.org/ticket/778.

**Comment by wpotrzebowski** [comment]
Trac update at `2016/11/01 07:54:46`: 
* **wojciech** changed owner from "" to "wojciech"
* **wojciech** changed status from "new" to "assigned"

**Comment by wpotrzebowski** [comment]
Trac update at `2016/11/07 14:06:19`: **wojciech** commented:

In changeset cc0f4a8d17731690c0afc19da7679262ce96cbeb:

```text
#!CommitTicketReference repository="sasview" revision="cc0f4a8d17731690c0afc19da7679262ce96cbeb"
Skiping one intensity evalution when polydispersity selected. Seems to have no effect on performance. Reffering to ticket #798
```

**Comment by wpotrzebowski** [comment]
Trac update at `2016/12/20 09:45:42`: 
* **wojciech** changed resolution from "" to "fixed"
* **wojciech** changed status from "assigned" to "closed"
