### ISSUE TITLE
custom models override builtin models of the same name (Trac #673)

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#804]
A custom model onion.py will override the builtin onion model.

Migrated from http://trac.sasview.org/ticket/673
```json
{
    "status": "closed",
    "changetime": "2016-10-10T16:56:13",
    "_ts": "2016-10-10 16:56:13.799119+00:00",
    "description": "A custom model onion.py will override the builtin onion model.",
    "reporter": "pkienzle",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2016-09-29T12:16:21",
    "component": "SasView",
    "summary": "custom models override builtin models of the same name",
    "priority": "minor",
    "keywords": "",
    "milestone": "SasView 4.1.0",
    "owner": "mathieu",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2016/09/29 13:26:57`: **butler** commented:

Interesting - Perhaps we should discuss at code camp whether this is not a feature we want to keep?.. User can override the builtin model with custom edits/fixes by using the same name?  Of course they could do accidentally and then wonder why it doesn't work ...

**Comment by mdoucet** [comment]
Trac update at `2016/10/09 14:36:01`: **mathieu** commented:

In changeset ed10b575284d50e5f99b3b93b89f0ec5edb5a6d5:

```text
#!CommitTicketReference repository="sasmodels" revision="ed10b575284d50e5f99b3b93b89f0ec5edb5a6d5"
Allow loading of custom model of the same name as a std model (append version). Re #804
```

**Comment by mdoucet** [comment]
Trac update at `2016/10/09 15:24:17`: 
* **mathieu** changed owner from "" to "mathieu"
* **mathieu** changed status from "new" to "accepted"

**Comment by mdoucet** [comment]
Trac update at `2016/10/09 15:24:24`: 
* **mathieu** changed resolution from "" to "fixed"
* **mathieu** changed status from "accepted" to "closed"

**Comment by mdoucet** [comment]
Trac update at `2016/10/10 16:56:13`: **mathieu** commented:

In changeset 2f2c70c9c9934234e4fc9112eb362f5aca11136e:

```text
#!CommitTicketReference repository="sasmodels" revision="2f2c70c9c9934234e4fc9112eb362f5aca11136e"
Fix problem with reloading. Re #804
```
