### ISSUE TITLE
Reparameterize hollow_cylinder (Trac #675)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#806]
hollow cylinder currently uses R_core and R_shell where R_shell is the outer radius.  This makes fitting, particularly with polydispersity problematic as R_shell can then go below R_core (or the distribution gets cut in odd way).  Most other core shell models are parameterized as a R_core and thickness of shell.

Note that doing this will break saved projects using the old parameters unless we do something special.

Migrated from http://trac.sasview.org/ticket/675
```json
{
    "status": "closed",
    "changetime": "2016-10-06T14:22:40",
    "_ts": "2016-10-06 14:22:40.499970+00:00",
    "description": "hollow cylinder currently uses R_core and R_shell where R_shell is the outer radius.  This makes fitting, particularly with polydispersity problematic as R_shell can then go below R_core (or the distribution gets cut in odd way).  Most other core shell models are parameterized as a R_core and thickness of shell.\n\nNote that doing this will break saved projects using the old parameters unless we do something special.",
    "reporter": "butler",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasModels Redesign",
    "time": "2016-10-01T17:15:36",
    "component": "SasView",
    "summary": "Reparameterize hollow_cylinder",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.1.0",
    "owner": "richardh",
    "type": "enhancement"
}
```

**Comment by RichardHeenan** [comment]
Trac update at `2016/10/06 14:20:36`: 
* **richardh** changed owner from "" to "richardh"
* **richardh** changed status from "new" to "accepted"

**Comment by RichardHeenan** [comment]
Trac update at `2016/10/06 14:22:40`: 
* **richardh** commented:

original hollow_cylinder replaced by new version where parameters are now core radius and shell thickness, not outer radius and core radius.

Yes this will break any previously saved models.



* **richardh** changed resolution from "" to "fixed"
* **richardh** changed status from "accepted" to "closed"
