### ISSUE TITLE
copy paste parameters should also copy constraints (Trac #682)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#812]
At present, for reasons unknown (but perhaps because constraints were added after copy past functionality?), only the parameter values can be copied to the clipboard and pasted into a new fitpanel.  This really should also copy and constraints on those parameters.

Migrated from http://trac.sasview.org/ticket/682
```json
{
    "status": "closed",
    "changetime": "2016-10-10T21:19:58",
    "_ts": "2016-10-10 21:19:58.677592+00:00",
    "description": "At present, for reasons unknown (but perhaps because constraints were added after copy past functionality?), only the parameter values can be copied to the clipboard and pasted into a new fitpanel.  This really should also copy and constraints on those parameters.",
    "reporter": "butler",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView GUI Enhancements",
    "time": "2016-10-04T11:49:17",
    "component": "SasView",
    "summary": "copy paste parameters should also copy constraints",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.1.0",
    "owner": "piotr",
    "type": "enhancement"
}
```

**Comment by rozyczko** [comment]
Trac update at `2016/10/08 20:08:44`: 
* **piotr** changed owner from "" to "piotr"
* **piotr** changed status from "new" to "assigned"

**Comment by rozyczko** [comment]
Trac update at `2016/10/10 17:26:21`: **piotr** commented:

Remember about dispersity parameters as well!
