### ISSUE TITLE
Investigate core shell bicelle model (Trac #696)

### ISSUE THREAD

**Issue by RichardHeenan** [SasView/sasview#824]
Looking at the c kernel code, I suspect that L in the model is actually the half length of the core, NOT the full length.

The equation in the description is not what is actually calculated.

I am not convinced yet that results are correct if sld of face is different to sld of rim.

The manual needs a diagram for the geometry of the bicelle. (The part with sld_face has radius Rcore)

Migrated from http://trac.sasview.org/ticket/696
```json
{
    "status": "closed",
    "changetime": "2016-10-08T18:57:05",
    "_ts": "2016-10-08 18:57:05.723911+00:00",
    "description": "Looking at the c kernel code, I suspect that L in the model is actually the half length of the core, NOT the full length.\n\nThe equation in the description is not what is actually calculated.\n\nI am not convinced yet that results are correct if sld of face is different to sld of rim.\n\nThe manual needs a diagram for the geometry of the bicelle. (The part with sld_face has radius Rcore)",
    "reporter": "richardh",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2016-10-05T15:31:28",
    "component": "SasView",
    "summary": "Investigate core shell bicelle model",
    "priority": "critical",
    "keywords": "",
    "milestone": "SasView 4.1.0",
    "owner": "butler",
    "type": "defect"
}
```

**Comment by RichardHeenan** [comment]
Trac update at `2016/10/05 15:54:14`: **richardh** commented:

The Length is OK (of course), as it got halved elsewhere.

**Comment by RichardHeenan** [comment]
Trac update at `2016/10/05 17:47:02`: **richardh** commented:

The limiting cases of:

(a) SLDface = SLDrim does generate a core/shell cylinder as expected.

(b) SLDcore=SLDface=SLDsolvent does generate a hollow cylinder (i.e. tube or pipe), as expected.

(c) SLDrim=SLDsolvent=SLDcore ought to generate two discs with a gap of L between them, I don't think this happens, suspect some horrible cross terms are missing.

**Comment by butlerpd** [comment]
Trac update at `2016/10/06 11:06:30`: **butler** commented:

regarding the graphic -- the current graphic is taken from an RSC journal articles.  While it is cited question is whether this constitutes "fair use" or would be a copyright infringement?

**Comment by RichardHeenan** [comment]
Trac update at `2016/10/06 16:44:49`: **richardh** commented:

Generated new graphics.

I(Q) equations look OK in code, need to check docs page now.

**Comment by RichardHeenan** [comment]
Trac update at `2016/10/06 17:55:07`: 
* **richardh** commented:

Have generated two new images from scratch.

Edited equation in "description" box.

Starting parameters look a little odd? - hand over to Paul



* **richardh** changed owner from "richardh" to "butler"
* **richardh** changed status from "new" to "assigned"

**Comment by butlerpd** [comment]
Trac update at `2016/10/06 22:12:39`: **butler** commented:

In changeset adc753dbe4450955415a1427496ad3341a93896e:

```text
#!CommitTicketReference repository="sasmodels" revision="adc753dbe4450955415a1427496ad3341a93896e"
bicelle model documentation standardized, ref to original derivation and
equations added to rst documentation. re #824 and http://trac.sasview.org/ticket/646
```

**Comment by RichardHeenan** [comment]
Trac update at `2016/10/08 18:57:05`: 
* **richardh** changed resolution from "" to "fixed"
* **richardh** changed status from "assigned" to "closed"
