### ISSUE TITLE
Change default for parameter selection boxes on FitPage (Trac #697)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#825]
At present, when a model is loaded to a !FitPage the default behaviour of the GUI is to select all parameters for fitting.

This was generally undesirable in earlier versions of !SasView (because users simply loaded a model and clicked Fit without engaging their brain) but is now a more serious deficiency due to the inclusion of the ''Scale'' parameter in all models, because many models now have ''Scale'' and ''Vol_frac'' which are totally correlated!

The default behaviour should be changed so that models load with all parameters '''unchecked'''.

Migrated from http://trac.sasview.org/ticket/697
```json
{
    "status": "closed",
    "changetime": "2016-10-07T21:26:06",
    "_ts": "2016-10-07 21:26:06.168321+00:00",
    "description": "At present, when a model is loaded to a !FitPage the default behaviour of the GUI is to select all parameters for fitting.\n\nThis was generally undesirable in earlier versions of !SasView (because users simply loaded a model and clicked Fit without engaging their brain) but is now a more serious deficiency due to the inclusion of the ''Scale'' parameter in all models, because many models now have ''Scale'' and ''Vol_frac'' which are totally correlated!\n\nThe default behaviour should be changed so that models load with all parameters '''unchecked'''.",
    "reporter": "smk78",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView GUI Enhancements",
    "time": "2016-10-05T18:01:14",
    "component": "SasView",
    "summary": "Change default for parameter selection boxes on FitPage",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.1.0",
    "owner": "mathieu",
    "type": "enhancement"
}
```

**Comment by mdoucet** [comment]
Trac update at `2016/10/06 15:46:46`: 
* **mathieu** changed owner from "" to "mathieu"
* **mathieu** changed status from "new" to "accepted"

**Comment by mdoucet** [comment]
Trac update at `2016/10/06 16:46:22`: 
* **mathieu** changed resolution from "" to "fixed"
* **mathieu** changed status from "accepted" to "closed"
