### ISSUE TITLE
Remove Select All parameters checkbox from FitPage (Trac #698)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#826]
Related to #825, the consensus opinion at Code Camp V was that the Select All parameters checkbox on the !FitPage was redundant and should be removed.

Migrated from http://trac.sasview.org/ticket/698
```json
{
    "status": "closed",
    "changetime": "2016-10-07T21:26:37",
    "_ts": "2016-10-07 21:26:37.238482+00:00",
    "description": "Related to #697, the consensus opinion at Code Camp V was that the Select All parameters checkbox on the !FitPage was redundant and should be removed.",
    "reporter": "smk78",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView GUI Enhancements",
    "time": "2016-10-05T18:04:53",
    "component": "SasView",
    "summary": "Remove Select All parameters checkbox from FitPage",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.1.0",
    "owner": "mathieu",
    "type": "enhancement"
}
```

**Comment by mdoucet** [comment]
Trac update at `2016/10/06 16:46:33`: 
* **mathieu** changed owner from "" to "mathieu"
* **mathieu** changed status from "new" to "accepted"

**Comment by mdoucet** [comment]
Trac update at `2016/10/06 16:46:40`: 
* **mathieu** changed resolution from "" to "fixed"
* **mathieu** changed status from "accepted" to "closed"
