### ISSUE TITLE
testing custom models - issues? (Trac #706)

### ISSUE THREAD

**Issue by RichardHeenan** [SasView/sasview#832]
Trying to follow manual "Writing a plugin model" to add a model (actually a needed reparametrisation of hollow_cylinder, see #806)

Please make the "info" box on "check model" results larger, as I had to copy & paste the output elsewhere to make sense of it.

After successful compile, is there a bug in:

```text
run_one("c:/users/rkh98/.sasview/plugin_models/hollow_cylinder_new.py")
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\stfc\sasview4\sasmodels\sasmodels\model_test.py", line 293, in run_one
    if not suite._tests[0].info.tests:
IndexError: list index out of range
```
or was it an issue with my new model?

If you don't have openCL then the default "main()" test fails, could say how to get around this. I can get it to work with the openMP version:

```text
main("-single!","-double!", "c:/users/rkh98/.sasview/plugin_models/hollow_cylinder_new.py")
```

Would be useful if manual said that ctrl/uparrow gets previous line back in python shell.

Migrated from http://trac.sasview.org/ticket/706
```json
{
    "status": "closed",
    "changetime": "2016-10-10T15:17:43",
    "_ts": "2016-10-10 15:17:43.162022+00:00",
    "description": "Trying to follow manual \"Writing a plugin model\" to add a model (actually a needed reparametrisation of hollow_cylinder, see #675)\n\nPlease make the \"info\" box on \"check model\" results larger, as I had to copy & paste the output elsewhere to make sense of it.\n\nAfter successful compile, is there a bug in:\n\n{{{\nrun_one(\"c:/users/rkh98/.sasview/plugin_models/hollow_cylinder_new.py\")\nTraceback (most recent call last):\n  File \"<input>\", line 1, in <module>\n  File \"C:\\stfc\\sasview4\\sasmodels\\sasmodels\\model_test.py\", line 293, in run_one\n    if not suite._tests[0].info.tests:\nIndexError: list index out of range\n}}}\nor was it an issue with my new model?\n\nIf you don't have openCL then the default \"main()\" test fails, could say how to get around this. I can get it to work with the openMP version:\n\n{{{\nmain(\"-single!\",\"-double!\", \"c:/users/rkh98/.sasview/plugin_models/hollow_cylinder_new.py\")\n}}}\n\nWould be useful if manual said that ctrl/uparrow gets previous line back in python shell.\n",
    "reporter": "richardh",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2016-10-05T20:09:39",
    "component": "SasView",
    "summary": "testing custom models - issues?",
    "priority": "minor",
    "keywords": "",
    "milestone": "SasView 4.1.0",
    "owner": "pkienzle",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2016/10/06 11:44:20`: **butler** changed description from:

> Trying to follow manual "Writing a plugin model" to add a model (actually a needed reparametrisation of hollow_cylinder, see #675)
> 
> Please make the "info" box on "check model" results larger, as I had to copy & paste the output elsewhere to make sense of it.
> 
> After successful compile, is there a bug in:
> 
> run_one("c:/users/rkh98/.sasview/plugin_models/hollow_cylinder_new.py")
> Traceback (most recent call last):
>   File "<input>", line 1, in <module>
>   File "C:\stfc\sasview4\sasmodels\sasmodels\model_test.py", line 293, in run_one
>     if not suite._tests[0].info.tests:
> IndexError: list index out of range
> 
> or was it an issue with my new model?
> 
> If you don't have openCL then the default "main()" test fails, could say how to get around this. I can get it to work with the openMP version:
> 
> main("-single!","-double!", "c:/users/rkh98/.sasview/plugin_models/hollow_cylinder_new.py")
> 
> 
> Would be useful if manual said that ctrl/uparrow gets previous line back in python shell.
> 

to:

> Trying to follow manual "Writing a plugin model" to add a model (actually a needed reparametrisation of hollow_cylinder, see #675)
> 
> Please make the "info" box on "check model" results larger, as I had to copy & paste the output elsewhere to make sense of it.
> 
> After successful compile, is there a bug in:
> 
> {{{
> run_one("c:/users/rkh98/.sasview/plugin_models/hollow_cylinder_new.py")
> Traceback (most recent call last):
>   File "<input>", line 1, in <module>
>   File "C:\stfc\sasview4\sasmodels\sasmodels\model_test.py", line 293, in run_one
>     if not suite._tests[0].info.tests:
> IndexError: list index out of range
> }}}
> or was it an issue with my new model?
> 
> If you don't have openCL then the default "main()" test fails, could say how to get around this. I can get it to work with the openMP version:
> 
> {{{
> main("-single!","-double!", "c:/users/rkh98/.sasview/plugin_models/hollow_cylinder_new.py")
> }}}
> 
> Would be useful if manual said that ctrl/uparrow gets previous line back in python shell.
>

**Comment by pkienzle** [comment]
Trac update at `2016/10/10 13:34:35`: **pkienzle** commented:

I couldn't reproduce the error, but I posted a change that should fix it.

Please try again, and attach the file that was causing problems.

I'm leaving the ticket open until it is tested, and until the second part of the ticket (the request to update the docs) has been addressed.

**Comment by pkienzle** [comment]
Trac update at `2016/10/10 14:51:54`: **pkienzle** commented:

See #864 for attached models.

**Comment by pkienzle** [comment]
Trac update at `2016/10/10 14:54:11`: **pkienzle** commented:

No longer fails, but claims there are no tests if `sasmodels.core.HAVE_OPENCL = False`
