### ISSUE TITLE
github integration not working on sasmodels (Trac #711)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#835]
While webhooks are set in sasmodels repo on Github and commits there are picked up by trac git, the commit messages to not show up in the trac tickets.  This may be because the ticket system are associated with the sasview repo rather than sasmodels?

Migrated from http://trac.sasview.org/ticket/711
```json
{
    "status": "closed",
    "changetime": "2016-10-06T19:19:25",
    "_ts": "2016-10-06 19:19:25.101452+00:00",
    "description": "While webhooks are set in sasmodels repo on Github and commits there are picked up by trac git, the commit messages to not show up in the trac tickets.  This may be because the ticket system are associated with the sasview repo rather than sasmodels?",
    "reporter": "butler",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Admin",
    "time": "2016-10-06T11:30:32",
    "component": "SasView",
    "summary": "github integration not working on sasmodels",
    "priority": "major",
    "keywords": "",
    "milestone": "Admin Tasks",
    "owner": "ajj",
    "type": "defect"
}
```

**Comment by ajj** [comment]
Trac update at `2016/10/06 19:19:25`: 
* **ajj** commented:

Think this is fixed now, along with issues with it working for sasview.


* **ajj** changed resolution from "" to "fixed"
* **ajj** changed status from "new" to "closed"
