### ISSUE TITLE
Magentism crashes SasView on Mac (Trac #718)

### ISSUE THREAD

**Issue by wpotrzebowski** [SasView/sasview#840]
SasView crashes when running magnetism. It seems to be working on Windows machine and build servers though. 
 

Migrated from http://trac.sasview.org/ticket/718
```json
{
    "status": "closed",
    "changetime": "2016-10-07T20:53:56",
    "_ts": "2016-10-07 20:53:56.021167+00:00",
    "description": "SasView crashes when running magnetism. It seems to be working on Windows machine and build servers though. \n ",
    "reporter": "wojciech",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2016-10-06T18:22:12",
    "component": "SasView",
    "summary": "Magentism crashes SasView on Mac",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.1.0",
    "owner": "wojciech",
    "type": "defect"
}
```

**Comment by pkienzle** [comment]
Trac update at `2016/10/06 19:36:53`: **pkienzle** commented:

Seems to work in 4.0 on my mac, but not the current development build

**Comment by wpotrzebowski** [comment]
Trac update at `2016/10/06 20:58:35`: 
* **wojciech** changed owner from "" to "wojciech"
* **wojciech** changed status from "new" to "assigned"

**Comment by wpotrzebowski** [comment]
Trac update at `2016/10/06 23:07:29`: **wojciech** commented:

It is very strange as it seems to affect MacOSX 10.11 but not 10.10. It doesn't also work for earlier releases (4.0b and 4.0b1) but used to work before. It looks like something external or some system update.

**Comment by wpotrzebowski** [comment]
Trac update at `2016/10/06 23:13:47`: **wojciech** commented:

What is more this seems to be Anaconda issue only

**Comment by wpotrzebowski** [comment]
Trac update at `2016/10/07 20:53:49`: **wojciech** commented:

Works with wxpython=3.0.2.0. Can be installed from: 
conda install -c noaa-orr-erd wxpython=3.0.2.0

**Comment by wpotrzebowski** [comment]
Trac update at `2016/10/07 20:53:56`: 
* **wojciech** changed resolution from "" to "fixed"
* **wojciech** changed status from "assigned" to "closed"
