### ISSUE TITLE
Bring roadmap uptdodate (Trac #731)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#847]
The Initial Roadmap needs to be updated to reflect changes from actual releases and the advent of the SINE2020 funding.

Migrated from http://trac.sasview.org/ticket/731
```json
{
    "status": "closed",
    "changetime": "2017-04-04T14:35:03",
    "_ts": "2017-04-04 14:35:03.962081+00:00",
    "description": "The Initial Roadmap needs to be updated to reflect changes from actual releases and the advent of the SINE2020 funding.",
    "reporter": "butler",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Admin",
    "time": "2016-10-08T13:16:41",
    "component": "SasView",
    "summary": "Bring roadmap uptdodate",
    "priority": "major",
    "keywords": "",
    "milestone": "Admin Tasks",
    "owner": "ajj",
    "type": "task"
}
```

**Comment by butlerpd** [comment]
Trac update at `2016/10/08 13:17:10`: **butler** changed status from "new" to "accepted"

**Comment by butlerpd** [comment]
Trac update at `2016/10/09 16:53:34`: 
* **butler** commented:

First pass done -  Andrew to proof read then close ticket


* **butler** changed owner from "butler" to "ajj"
* **butler** changed status from "accepted" to "assigned"

**Comment by ajj** [comment]
Trac update at `2017/04/04 14:35:03`: 
* **ajj** changed resolution from "" to "fixed"
* **ajj** changed status from "assigned" to "closed"
