### ISSUE TITLE
Fix Report Results (Trac #737)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#853]
Report Results has stopped working in 4.1 (works in 4.0).

Traceback (most recent call last):
  File "C:\Code\sasview4\src\sas\sasgui\guiframe\gui_manager.py", line 2842, in on_preview_panel
    if self.cpanel_on_focus is not None:
  File "C:\Code\sasview4\src\sas\sasgui\perspectives\fitting\basepage.py", line 627, in on_preview
    self.state.report(images, canvases)
  File "C:\Code\sasview4\src\sas\sasgui\perspectives\fitting\pagestate.py", line 591, in report
    html_str, text_str, title = self.set_report_string()
  File "C:\Code\sasview4\src\sas\sasgui\perspectives\fitting\pagestate.py", line 530, in set_report_string
    model_name = CENTRE % modelname
NameError: global name 'CENTRE' is not defined

Migrated from http://trac.sasview.org/ticket/737
```json
{
    "status": "closed",
    "changetime": "2016-10-09T15:39:01",
    "_ts": "2016-10-09 15:39:01.321410+00:00",
    "description": "Report Results has stopped working in 4.1 (works in 4.0).\n\nTraceback (most recent call last):\n  File \"C:\\Code\\sasview4\\src\\sas\\sasgui\\guiframe\\gui_manager.py\", line 2842, in on_preview_panel\n    if self.cpanel_on_focus is not None:\n  File \"C:\\Code\\sasview4\\src\\sas\\sasgui\\perspectives\\fitting\\basepage.py\", line 627, in on_preview\n    self.state.report(images, canvases)\n  File \"C:\\Code\\sasview4\\src\\sas\\sasgui\\perspectives\\fitting\\pagestate.py\", line 591, in report\n    html_str, text_str, title = self.set_report_string()\n  File \"C:\\Code\\sasview4\\src\\sas\\sasgui\\perspectives\\fitting\\pagestate.py\", line 530, in set_report_string\n    model_name = CENTRE % modelname\nNameError: global name 'CENTRE' is not defined",
    "reporter": "smk78",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2016-10-08T17:17:29",
    "component": "SasView",
    "summary": "Fix Report Results",
    "priority": "blocker",
    "keywords": "",
    "milestone": "SasView 4.1.0",
    "owner": "krzywon",
    "type": "defect"
}
```

**Comment by mdoucet** [comment]
Trac update at `2016/10/09 15:15:29`: 
* **mathieu** changed owner from "mathieu" to "krzywon"
* **mathieu** changed status from "new" to "assigned"
