### ISSUE TITLE
Consider enhanced fitting constraints (Trac #746)

### ISSUE THREAD

**Issue by RichardHeenan** [SasView/sasview#862]
It would be useful to add a fittable parameter that can be used within constraints. Eg Imagine I want (Rcore+Tshell)/Rcore = C, this requires the constraint for Tshell = Rcore(C-1) where C can be fitted. Implementing this would save having to write variant models, BUT the constraints may need to be called inside polydispersity/integrations for say Rcore which may not be possible in !SasView?

(FISH permitted this)

Migrated from http://trac.sasview.org/ticket/746
```json
{
    "status": "closed",
    "changetime": "2018-07-03T16:49:25",
    "_ts": "2018-07-03 16:49:25.166295+00:00",
    "description": "It would be useful to add a fittable parameter that can be used within constraints. Eg Imagine I want (Rcore+Tshell)/Rcore = C, this requires the constraint for Tshell = Rcore(C-1) where C can be fitted. Implementing this would save having to write variant models, BUT the constraints may need to be called inside polydispersity/integrations for say Rcore which may not be possible in !SasView?\n\n(FISH permitted this)",
    "reporter": "richardh",
    "cc": "",
    "resolution": "wontfix",
    "workpackage": "Beta Approximation Project",
    "time": "2016-10-09T15:54:23",
    "component": "SasView",
    "summary": "Consider enhanced fitting constraints",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView Next Release +1",
    "owner": "",
    "type": "enhancement"
}
```

**Comment by pkienzle** [comment]
Trac update at `2016/10/10 15:54:27`: **pkienzle** commented:

I wasn't able to support dependent parameters within the kernel without slowing down the unconstrained kernels.  

How many variant kernels are there going to be in practice?  Do you have a large set of saved FISH fits?  Can we search for those which use constraints in this way?

If the number of models with reasonable variants is small, then we can handle those individually using the style of the RPA model, with a dropdown list to select the variant and a `hidden()` function to return the list of inactive parameters for each variant.

**Comment by smk78** [comment]
Trac update at `2018/07/03 13:23:18`: 
* **smk78** commented:

Moving to the Beta Approximation Work Package whilst we consider enhancing constraints.


* **smk78** changed workpackage from "SasView Fitting Redesign" to "Beta Approximation Project"

**Comment by RichardHeenan** [comment]
Trac update at `2018/07/03 16:49:25`: 
* **richardh** commented:

Though I wrote the ticket I am going to close it, as introducing a fitable parameter on the fly is beyond even what is being suggested in #888, #1160 etc. Users will simply have to create a plugin model with suitable parameters.


* **richardh** changed resolution from "" to "wontfix"
* **richardh** changed status from "new" to "closed"
