### ISSUE TITLE
(Simple) New Plugin Model editor creates files even if it doesn't compile/pass testing (Trac #762)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#878]
The (simple) New Plugin Model editor creates .py/.pyc files in the /plugin_models folder - and possibly populates the namespace? - even if compilation of the model fails (eg, because of a syntax error). If you correct the error and click 'Apply' again you then get a new error telling you that the model exists!

The irritating workarounds are either to give the model a new name which, if you have a succession of compilation errors will populate the plugins folder with junk files, or to go in to the plugins folder and manually delete the junk files (which carries other risks).

If compilation/testing fails the plugins folder should be cleaned out.

Migrated from http://trac.sasview.org/ticket/762
```json
{
    "status": "closed",
    "changetime": "2016-10-11T15:55:40",
    "_ts": "2016-10-11 15:55:40.821345+00:00",
    "description": "The (simple) New Plugin Model editor creates .py/.pyc files in the /plugin_models folder - and possibly populates the namespace? - even if compilation of the model fails (eg, because of a syntax error). If you correct the error and click 'Apply' again you then get a new error telling you that the model exists!\n\nThe irritating workarounds are either to give the model a new name which, if you have a succession of compilation errors will populate the plugins folder with junk files, or to go in to the plugins folder and manually delete the junk files (which carries other risks).\n\nIf compilation/testing fails the plugins folder should be cleaned out.",
    "reporter": "smk78",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2016-10-10T20:02:18",
    "component": "SasView",
    "summary": "(Simple) New Plugin Model editor creates files even if it doesn't compile/pass testing",
    "priority": "blocker",
    "keywords": "",
    "milestone": "SasView 4.1.0",
    "owner": "smk78",
    "type": "defect"
}
```

**Comment by pkienzle** [comment]
Trac update at `2016/10/10 23:52:57`: 
* **pkienzle** changed _comment0 from:

> There is an "overwrite" box.  This could be set to True when the model is saved under a particular name.
> 

to:

> 1476143601702232


* **pkienzle** commented:

There is an "overwrite" box.  This could be set to True when the model is first saved under a particular name.

**Comment by smk78** [comment]
Trac update at `2016/10/11 15:13:37`: 
* **smk78** changed owner from "" to "smk78"
* **smk78** changed status from "new" to "assigned"

**Comment by smk78** [comment]
Trac update at `2016/10/11 15:55:32`: **smk78** commented:

Have changed the default behaviour of the overwrite box from False to True, changed the wording of the text alongside to something more explicit, and updated the Help documentation.

**Comment by smk78** [comment]
Trac update at `2016/10/11 15:55:40`: 
* **smk78** changed resolution from "" to "fixed"
* **smk78** changed status from "assigned" to "closed"
