### ISSUE TITLE
redefine rectangular distribution parameters (Trac #764)

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#879]
The current definition of the rectangular distribution uses the 1-sigma equivalent width of the distribution rather than the more natural half-width.  That means, for example, that if you want a rectangular distribution covering theta +/- 10 degrees uniformly, you instead need to 10/sqrt(3) or 5.77.  Furthermore, then number of points in the distribution will be reduced as a function of Nsigs.

It will be far easier to use the distribution if PD is half the width of the desired distribution, Npts is the number of points used and Nsigs is ignored.

Migrated from http://trac.sasview.org/ticket/764
```json
{
    "status": "new",
    "changetime": "2018-02-14T10:19:02",
    "_ts": "2018-02-14 10:19:02.656355+00:00",
    "description": "The current definition of the rectangular distribution uses the 1-sigma equivalent width of the distribution rather than the more natural half-width.  That means, for example, that if you want a rectangular distribution covering theta +/- 10 degrees uniformly, you instead need to 10/sqrt(3) or 5.77.  Furthermore, then number of points in the distribution will be reduced as a function of Nsigs.\n\nIt will be far easier to use the distribution if PD is half the width of the desired distribution, Npts is the number of points used and Nsigs is ignored.",
    "reporter": "pkienzle",
    "cc": "",
    "resolution": "",
    "workpackage": "SasView Bug Fixing",
    "time": "2016-10-10T20:37:54",
    "component": "SasView",
    "summary": "redefine rectangular distribution parameters",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.3.0",
    "owner": "",
    "type": "defect"
}
```

**Comment by pkienzle** [comment]
Trac update at `2016/10/10 20:39:42`: **pkienzle** commented:

Documentation needs to be updated to match.

**Comment by butlerpd** [comment]
Trac update at `2016/10/11 18:02:53`: 
* **butler** commented:

Not addressed at code camp at SNS -- probably should be part of a polydispersity refactoring in 4.2 (a number of related tickets exist now on this topic)


* **butler** changed milestone from "SasView 4.1.0" to "SasView 4.2.0"

**Comment by butlerpd** [comment]
Trac update at `2017/10/27 14:23:03`: **butler** changed milestone from "SasView 4.2.0" to "SasView 4.3.0"

**Comment by RichardHeenan** [comment]
Trac update at `2017/10/28 07:53:47`: 
* **richardh** commented:

The gui will need to be clever to make it abundantly clear when we are using say standard deviation for a Gaussian or full (half?) width for rectangular distribution.

[ticket:1018 Also http://trac.sasview.org/ticket/1018]  for the Boltzmann distribution requires a new "dispersity" which is  dimensionless and goes from 0 to say ~0.01 for isotropic to ordered.

There is currently a column headed PD[ratio],Sig[deg]  can we insert a descriptor column that changes with the function drop down to say PD[ratio], sigma [Ang or deg], Boltzmann L[ratio], full width[Ang or deg] etc.  Or perhaps for now a footnote to the table to explain all this?

Should we try to do this now or should we wait until the new gui in v5.0? I think that given the new distribution in http://trac.sasview.org/ticket/1018 (within the branch for http://trac.sasview.org/ticket/776) we ought to do something, if only a partial fix, now for v4.2


* **richardh** changed milestone from "SasView 4.3.0" to "SasView 4.2.0"

**Comment by RichardHeenan** [comment]
Trac update at `2017/10/29 11:08:47`: **richardh** commented:

The idea is that at some time soon rectangle distribution will be deprecated in favor of the new uniform distribution. Then the loader has to be changed to convert any rectangular input into the equivalent uniform one in order to maintain backwards compatibility.

**Comment by butlerpd** [comment]
Trac update at `2018/02/13 03:00:28`: **butler** changed milestone from "SasView 4.2.0" to "SasView 4.3.0"

**Comment by RichardHeenan** [comment]
Trac update at `2018/02/14 10:19:02`: **richardh** commented:

The old rectangle polydispersity distribution could be  deprecated in favor of the new uniform distribution which has a more sensible width parameter. To do this the loader has  to be changed to convert any rectangular input into the equivalent  uniform one in order to maintain backwards compatibility.

Then we need to check that the gui and the docs do not anywhere imply that the "width parameter" is the standard deviation when it is not actually that (this is probably OK now).

**Comment by pkienzle** [comment]
Closing this ticket since rectangular distribution is superseded by uniform distribution.  Opened new ticket to remove rectangular distribution.
