### ISSUE TITLE
Verify if ESS 4.1 builds are properly linking to page anchors in help documentation (Trac #777)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#886]
In local builds of 4.1 some Help buttons on GUIs are ignoring page anchors in the Wx code in the .py files and are only linking to the top of a given help file. Whereas in release 3.1.2 the Help button jumps to the relevant place in the help file.

In the code one often finds this comment::

        Calls !DocumentationWindow with the path of the location within
        the documentation tree (after /doc/ ....".  Note that when using
        old versions of Wx (before 2.9) and thus not the release version of
        installers, the help comes up at the top level of the file as
        webbrowser does not pass anything past the # to the browser when it
        is running "file:///...."

However, even local builds against Wx 3.0 are failing, so it is not just a earlier Wx issue.

The behaviour of build server builds needs to be checked.

A simple way to do this is to go Fitting > Plugin Model Operations > New Plugin Model and click the Help button. If it directs you to the top of the Fitting help (you will see the title 'Fitting') the problem exists. If it directs you to New Plugin Model the build is ok.

Migrated from http://trac.sasview.org/ticket/777
```json
{
    "status": "closed",
    "changetime": "2016-11-11T08:56:26",
    "_ts": "2016-11-11 08:56:26.687124+00:00",
    "description": "In local builds of 4.1 some Help buttons on GUIs are ignoring page anchors in the Wx code in the .py files and are only linking to the top of a given help file. Whereas in release 3.1.2 the Help button jumps to the relevant place in the help file.\n\nIn the code one often finds this comment::\n\n        Calls !DocumentationWindow with the path of the location within\n        the documentation tree (after /doc/ ....\".  Note that when using\n        old versions of Wx (before 2.9) and thus not the release version of\n        installers, the help comes up at the top level of the file as\n        webbrowser does not pass anything past the # to the browser when it\n        is running \"file:///....\"\n\nHowever, even local builds against Wx 3.0 are failing, so it is not just a earlier Wx issue.\n\nThe behaviour of build server builds needs to be checked.\n\nA simple way to do this is to go Fitting > Plugin Model Operations > New Plugin Model and click the Help button. If it directs you to the top of the Fitting help (you will see the title 'Fitting') the problem exists. If it directs you to New Plugin Model the build is ok.\n",
    "reporter": "smk78",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2016-10-11T17:59:03",
    "component": "SasView",
    "summary": "Verify if ESS 4.1 builds are properly linking to page anchors in help documentation",
    "priority": "critical",
    "keywords": "",
    "milestone": "SasView 4.1.0",
    "owner": "wojciech",
    "type": "defect"
}
```

**Comment by smk78** [comment]
Trac update at `2016/10/26 10:53:21`: **smk78** commented:

Just tested ESS Win 7 build 583 and it is ignoring page anchors (it just goes to the top of the file). :-(

**Comment by wpotrzebowski** [comment]
Trac update at `2016/11/08 10:14:50`: 
* **wojciech** changed owner from "" to "wojciech"
* **wojciech** changed status from "new" to "assigned"

**Comment by wpotrzebowski** [comment]
Trac update at `2016/11/08 11:26:30`: **wojciech** commented:

In changeset a08b89bdf5a13632196725c27a97760f06d09e9c:

```text
#!CommitTicketReference repository="sasview" revision="a08b89bdf5a13632196725c27a97760f06d09e9c"
Fixing new plugin editor link anchor. Related to #886
```

**Comment by wpotrzebowski** [comment]
Trac update at `2016/11/08 13:47:25`: **wojciech** commented:

The link to New Plugin Model has been fixed. 
Trying to set up an automatic check for broken links to see if there are more failing cases.

**Comment by wpotrzebowski** [comment]
Trac update at `2016/11/11 08:56:26`: 
* **wojciech** changed resolution from "" to "fixed"
* **wojciech** changed status from "assigned" to "closed"
