### ISSUE TITLE
Add 3D integral to Correlation Function analysis (Trac #784)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#890]
The new correlation function analysis implemented post-4.0 calculates the 1D integral. This is the most useful as it is that which should be used with anisotropic/oriented systems. However, for completeness, and to restore the full functionality offered by the old CCP13 CORFUNC program, we should also compute the 3D integral.

Steve knows ''what'' to do, but not necessarily ''how''...

Migrated from http://trac.sasview.org/ticket/784
```json
{
    "status": "closed",
    "changetime": "2018-03-04T17:10:08",
    "_ts": "2018-03-04 17:10:08.035706+00:00",
    "description": "The new correlation function analysis implemented post-4.0 calculates the 1D integral. This is the most useful as it is that which should be used with anisotropic/oriented systems. However, for completeness, and to restore the full functionality offered by the old CCP13 CORFUNC program, we should also compute the 3D integral.\n\nSteve knows ''what'' to do, but not necessarily ''how''...",
    "reporter": "smk78",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView GUI Enhancements",
    "time": "2016-10-14T15:42:42",
    "component": "SasView",
    "summary": "Add 3D integral to Correlation Function analysis",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.2.0",
    "owner": "lewis",
    "type": "enhancement"
}
```

**Comment by smk78** [comment]
Trac update at `2017/01/13 17:23:53`: **smk78** commented:

In changeset 1dc8ec9bbfd72210acd49400626adfb8eb6c3c87:

```text
#!CommitTicketReference repository="sasview" revision="1dc8ec9bbfd72210acd49400626adfb8eb6c3c87"
Provisioning for #890. Changed TRANSFORM_LABEL to TRANSFORM_LABEL1. In
addition, created TRANSFORM_LABEL3.
```

**Comment by smk78** [comment]
Trac update at `2017/01/13 17:45:12`: 
* **smk78** changed attachment from "" to "Corfunc_mods_#784.docx"
* **smk78** commented:

3D correlation function implementation steps

**Comment by smk78** [comment]
Trac update at `2017/07/10 16:17:10`: 
* **smk78** changed owner from "" to "lewis"
* **smk78** changed status from "new" to "assigned"

**Comment by smk78** [comment]
Trac update at `2017/09/26 11:37:10`: 
* **smk78** changed resolution from "" to "fixed"
* **smk78** changed status from "assigned" to "closed"

**Comment by butlerpd** [comment]
Trac update at `2018/03/04 17:10:08`: **butler** changed milestone from "SasView Next Release +1" to "SasView 4.2.0"
