### ISSUE TITLE
TU Delft logo is not being rendered in the About box in Jenkins builds but is in local builds (Trac #797)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#897]
Testing ESS Win 7 build 583 (for something else), noticed that doing Help > About threw the message:

Failed to load image from file "C:\Program Files (x86)\!SasView-4.0.0-nightly583\library.zip\sas\sasgui\guiframe/images/tudelft_logo.png"

Works fine in locally-built !SasView.

Migrated from http://trac.sasview.org/ticket/797
```json
{
    "status": "closed",
    "changetime": "2016-11-07T14:08:14",
    "_ts": "2016-11-07 14:08:14.777987+00:00",
    "description": "Testing ESS Win 7 build 583 (for something else), noticed that doing Help > About threw the message:\n\nFailed to load image from file \"C:\\Program Files (x86)\\!SasView-4.0.0-nightly583\\library.zip\\sas\\sasgui\\guiframe/images/tudelft_logo.png\"\n\nWorks fine in locally-built !SasView.\n\n",
    "reporter": "smk78",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2016-10-26T11:14:19",
    "component": "SasView",
    "summary": "TU Delft logo is not being rendered in the About box in Jenkins builds but is in local builds",
    "priority": "blocker",
    "keywords": "",
    "milestone": "SasView 4.1.0",
    "owner": "piotr",
    "type": "defect"
}
```

**Comment by rozyczko** [comment]
Trac update at `2016/11/07 12:25:17`: 
* **piotr** changed owner from "" to "piotr"
* **piotr** changed status from "new" to "accepted"

**Comment by rozyczko** [comment]
Trac update at `2016/11/07 14:08:14`: 
* **piotr** changed resolution from "" to "fixed"
* **piotr** changed status from "accepted" to "closed"
