### ISSUE TITLE
Plot range constantly resets (Trac #800)

### ISSUE THREAD

**Issue by mdoucet** [SasView/sasview#900]
If you are fitting parts of your data and want to zoom in on it using the "Set Graph Range" option, it always resets when it wants to refresh the plot. The chosen range should not be modified.

Migrated from http://trac.sasview.org/ticket/800
```json
{
    "status": "closed",
    "changetime": "2016-11-09T09:41:37",
    "_ts": "2016-11-09 09:41:37.942978+00:00",
    "description": "If you are fitting parts of your data and want to zoom in on it using the \"Set Graph Range\" option, it always resets when it wants to refresh the plot. The chosen range should not be modified.",
    "reporter": "mathieu",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2016-11-04T15:19:45",
    "component": "SasView",
    "summary": "Plot range constantly resets",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.1.0",
    "owner": "piotr",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2016/11/08 15:08:05`: 
* **butler** commented:

Piotr to look at.  If too hard will kick to 4.2


* **butler** changed owner from "" to "piotr"
* **butler** changed status from "new" to "assigned"

**Comment by rozyczko** [comment]
Trac update at `2016/11/09 09:41:37`: 
* **piotr** changed resolution from "" to "fixed"
* **piotr** changed status from "assigned" to "closed"
