### ISSUE TITLE
Right-clicking on legend moves the legend around (Trac #801)

### ISSUE THREAD

**Issue by mdoucet** [SasView/sasview#901]
When the user right-click on the plot legend to change options, it should not move around with the mouse while the context menu is displayed.

Migrated from http://trac.sasview.org/ticket/801
```json
{
    "status": "closed",
    "changetime": "2016-11-09T13:49:52",
    "_ts": "2016-11-09 13:49:52.101949+00:00",
    "description": "When the user right-click on the plot legend to change options, it should not move around with the mouse while the context menu is displayed.",
    "reporter": "mathieu",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2016-11-04T15:21:29",
    "component": "SasView",
    "summary": "Right-clicking on legend moves the legend around",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.1.0",
    "owner": "piotr",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2016/11/08 14:41:46`: 
* **butler** changed owner from "" to "piotr"
* **butler** changed status from "new" to "assigned"

**Comment by rozyczko** [comment]
Trac update at `2016/11/09 11:52:45`: 
* **piotr** changed resolution from "fixed" to ""
* **piotr** changed status from "closed" to "reopened"

**Comment by rozyczko** [comment]
Trac update at `2016/11/09 11:53:09`: **piotr** commented:

Marked wrong ticket, again.

**Comment by rozyczko** [comment]
Trac update at `2016/11/09 12:41:11`: **piotr** commented:

Currently, the legend moves on both right and left click. I think it would be beneficial to have it movable only with the left button. This way the right button click would only open the context menu without any overloaded functionality.

Agreed?

**Comment by rozyczko** [comment]
Trac update at `2016/11/09 12:41:27`: **piotr** changed _comment0 from:

> Currently, the legend moves on both right and left click. I think it would be beneficial to have it movable only with the left button. This way the right button click would only open the context menu without any overloaded functionality.
> 
> Agreed?

to:

> 1478695315908948
