### ISSUE TITLE
Changing curve options should default to current values (Trac #802)

### ISSUE THREAD

**Issue by mdoucet** [SasView/sasview#902]
When you create a new plot, right-click on the legend, and go to "Modify Plot Properties", the options initially shown default to a blue line. They should default to what is currently used for that data. Once the user picks new options, those are nicely remembered for the rest of the session. But the initial values should not be global defaults.

Migrated from http://trac.sasview.org/ticket/802
```json
{
    "status": "closed",
    "changetime": "2016-11-09T11:52:26",
    "_ts": "2016-11-09 11:52:26.943007+00:00",
    "description": "When you create a new plot, right-click on the legend, and go to \"Modify Plot Properties\", the options initially shown default to a blue line. They should default to what is currently used for that data. Once the user picks new options, those are nicely remembered for the rest of the session. But the initial values should not be global defaults.",
    "reporter": "mathieu",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2016-11-04T15:24:34",
    "component": "SasView",
    "summary": "Changing curve options should default to current values",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.1.0",
    "owner": "piotr",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2016/11/08 15:09:10`: 
* **butler** commented:

Piotr to look at.  If too hard kick to 4.2


* **butler** changed owner from "" to "piotr"
* **butler** changed status from "new" to "assigned"

**Comment by rozyczko** [comment]
Trac update at `2016/11/09 11:52:26`: 
* **piotr** changed resolution from "" to "fixed"
* **piotr** changed status from "assigned" to "closed"
