### ISSUE TITLE
Provide information on supported platforms (Trac #809)

### ISSUE THREAD

**Issue by wpotrzebowski** [SasView/sasview#907]
Currently from user perspective the information on the operating systems, on which we can use SasView is only specified on http://www.sasview.org/about.html. Would be good to have it explicitly mentioned on the download webpage

Migrated from http://trac.sasview.org/ticket/809
```json
{
    "status": "closed",
    "changetime": "2017-04-05T16:22:40",
    "_ts": "2017-04-05 16:22:40.409536+00:00",
    "description": "Currently from user perspective the information on the operating systems, on which we can use SasView is only specified on http://www.sasview.org/about.html. Would be good to have it explicitly mentioned on the download webpage",
    "reporter": "wojciech",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Admin",
    "time": "2016-11-18T14:07:57",
    "component": "SasView",
    "summary": "Provide information on supported platforms",
    "priority": "major",
    "keywords": "",
    "milestone": "Admin Tasks",
    "owner": "",
    "type": "defect"
}
```

**Comment by smk78** [comment]
Trac update at `2016/11/18 15:57:50`: **smk78** commented:

Probably.

But the operating systems are clearly mentioned on http://www.sasview.org/faq.html

**Comment by smk78** [comment]
Trac update at `2017/04/05 16:22:29`: **smk78** commented:

Added additional link from 'For Users' section under links/downloads to the list of supported platforms in faq.html

**Comment by smk78** [comment]
Trac update at `2017/04/05 16:22:40`: 
* **smk78** changed resolution from "" to "fixed"
* **smk78** changed status from "new" to "closed"
