### ISSUE TITLE
Problem loading test data  SILIC010.DAT (Trac #811)

### ISSUE THREAD

**Issue by wpotrzebowski** [SasView/sasview#909]
When trying to load SILIC010.DAT an error occurs: 
"""
Fitting set_data: total size of new array must be unchanged. 
"""

As a consequence (I guess) fitting cannot be performed:
  File "src/sas/sasgui/perspectives/fitting/fitpage.py", line 1031, in _onFit
    flag = self._update_paramv_on_fit()
  File "src/sas/sasgui/perspectives/fitting/basepage.py", line 1554, in _update_paramv_on_fit
    flag = self._validate_Npts()
  File "src/sas/sasgui/perspectives/fitting/basepage.py", line 2146, in _validate_Npts
    self.Npts_fit.SetValue(str(len(index_data[index_data is True])))
TypeError: object of type 'numpy.bool_' has no len()

Migrated from http://trac.sasview.org/ticket/811
```json
{
    "status": "closed",
    "changetime": "2016-12-21T17:45:31",
    "_ts": "2016-12-21 17:45:31.219218+00:00",
    "description": "When trying to load SILIC010.DAT an error occurs: \n\"\"\"\nFitting set_data: total size of new array must be unchanged. \n\"\"\"\n\nAs a consequence (I guess) fitting cannot be performed:\n  File \"src/sas/sasgui/perspectives/fitting/fitpage.py\", line 1031, in _onFit\n    flag = self._update_paramv_on_fit()\n  File \"src/sas/sasgui/perspectives/fitting/basepage.py\", line 1554, in _update_paramv_on_fit\n    flag = self._validate_Npts()\n  File \"src/sas/sasgui/perspectives/fitting/basepage.py\", line 2146, in _validate_Npts\n    self.Npts_fit.SetValue(str(len(index_data[index_data is True])))\nTypeError: object of type 'numpy.bool_' has no len()\n",
    "reporter": "wojciech",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2016-11-23T10:28:03",
    "component": "SasView",
    "summary": "Problem loading test data  SILIC010.DAT",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.1.0",
    "owner": "pkienzle",
    "type": "defect"
}
```

**Comment by wpotrzebowski** [comment]
Trac update at `2016/11/23 11:53:21`: **wojciech** changed summary from "Problem loading fitting to test data" to "Problem loading test data  SILIC010.DAT"

**Comment by smk78** [comment]
Trac update at `2016/12/06 14:14:46`: 
* **smk78** changed owner from "" to "krzywon"
* **smk78** changed status from "new" to "assigned"

**Comment by smk78** [comment]
Trac update at `2016/12/06 14:14:57`: **smk78** commented:

Works in 3.1.2

**Comment by smk78** [comment]
Trac update at `2016/12/14 18:34:50`: **smk78** commented:

Also see #920

**Comment by pkienzle** [comment]
Trac update at `2016/12/20 14:16:50`: 
* **pkienzle** changed resolution from "fixed" to ""
* **pkienzle** changed status from "closed" to "reopened"

**Comment by pkienzle** [comment]
Trac update at `2016/12/21 17:45:31`: 
* **pkienzle** changed resolution from "" to "fixed"
* **pkienzle** changed status from "reopened" to "closed"
