### ISSUE TITLE
elliptical bicelle - new model (Trac #817)

### ISSUE THREAD

**Issue by RichardHeenan** [SasView/sasview#913]
Following request from Yang PoWei 
yangpowei@gmail.com, Postdoctoral researcher
     Small-Angle Scattering group
     National Synchrotron Radiation Research Center, Taiwan
Richard will look at making an elliptical core version of the bicelle model to help them with their nice looking SAXS data.

Migrated from http://trac.sasview.org/ticket/817
```json
{
    "status": "closed",
    "changetime": "2017-02-28T15:22:09",
    "_ts": "2017-02-28 15:22:09.963129+00:00",
    "description": "Following request from Yang PoWei \nyangpowei@gmail.com, Postdoctoral researcher\n     Small-Angle Scattering group\n     National Synchrotron Radiation Research Center, Taiwan\nRichard will look at making an elliptical core version of the bicelle model to help them with their nice looking SAXS data.\n",
    "reporter": "richardh",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasModels New Model",
    "time": "2016-11-30T14:47:03",
    "component": "SasView",
    "summary": "elliptical bicelle - new model",
    "priority": "minor",
    "keywords": "",
    "milestone": "SasView 4.1.0",
    "owner": "richardh",
    "type": "enhancement"
}
```

**Comment by butlerpd** [comment]
Trac update at `2016/12/20 16:53:55`: **butler** commented:

Given the existence of the marketplace as a distribution mechanism and the impact to 4.1 this could easily be moved to 4.2 and should not impact the release of 4.1.  Will leave here for now as work is ongoing and depending on when the freeze is this could make it in.

**Comment by pkienzle** [comment]
Trac update at `2017/02/14 21:04:13`: **pkienzle** changed attachment from "" to "micelles_ellipsoid.py"

**Comment by pkienzle** [comment]
Trac update at `2017/02/14 21:04:33`: **pkienzle** changed attachment from "" to "micelles_ellipsoid.c"

**Comment by pkienzle** [comment]
Trac update at `2017/02/14 21:09:06`: **pkienzle** changed attachment from "" to "micelles_ellipsoid.2.c"

**Comment by pkienzle** [comment]
Trac update at `2017/02/14 21:11:46`: **pkienzle** changed attachment from "" to "micelles_ellipsoid.2.py"

**Comment by pkienzle** [comment]
Trac update at `2017/02/14 21:17:10`: 
* **pkienzle** changed _comment0 from:

> The attached model was created by the ILL summer student.   Download the *.2* version and rename it so that it doesn't include the *.2*.  
> 
> I upgraded the model to the new library names sas_3j1x_x, etc, (in micelles_ellipsoid.2.*) but could not delete the original (in micelles_ellipsoid.*).  The model runs, but I did not check the implementation against the literature.
> 
> 
> 
> 

to:

> 1487107140878381


* **pkienzle** commented:

The attached model was created by the ILL summer student.   Download the *.2* version and rename it so that it doesn't include the *.2*.  

I upgraded the model to the new library names sas_3j1x_x, etc, (in micelles_ellipsoid.2.*) but could not delete the original (in micelles_ellipsoid.*).  The model runs, but I did not check the implementation against the literature.

...

and now I see that it says elliptical_bicelle, not elliptical_micelle in the ticket, so forget the attachments altogether.

**Comment by RichardHeenan** [comment]
Trac update at `2017/02/15 11:02:44`: **richardh** commented:

The new core_shell_bicelle_elliptical works fine for 1d data, and I am 98% sure it is OK for 2d data,or rather as badly as the other oriented asymmetric particles, so it could go into 4.1

**Comment by smk78** [comment]
Trac update at `2017/02/21 14:26:35`: **smk78** changed status from "new" to "assigned"

**Comment by RichardHeenan** [comment]
Trac update at `2017/02/28 14:39:16`: 
* **richardh** commented:

Closing this as basic 1d & 2d for this new model work OK

But there is perhaps an issue (possibly more general) when I attempt 2d data with psi anlge integration, see http://trac.sasview.org/ticket/837


* **richardh** changed resolution from "" to "fixed"
* **richardh** changed status from "assigned" to "closed"

**Comment by RichardHeenan** [comment]
Trac update at `2017/02/28 15:22:09`: **richardh** commented:


The completely unrelated elliptical_micelle mentioned above was renamed in 4.0 to polymer_micelle and appears in the the "spheres" section (as it is not elliptical).
See http://trac.sasview.org/ticket/868
