### ISSUE TITLE
“report  button” followed by “save” makes an empty pdf file??? (Trac #818)

### ISSUE THREAD

**Issue by RichardHeenan** [SasView/sasview#914]
Discovered that on my windows 7, 32 bit, build “report  button” followed by “save”  currently makes an empty pdf file, though “print” seems to work.

Will someone else please check.

Richard

Migrated from http://trac.sasview.org/ticket/818
```json
{
    "status": "closed",
    "changetime": "2018-03-07T01:12:14",
    "_ts": "2018-03-07 01:12:14.384879+00:00",
    "description": "Discovered that on my windows 7, 32 bit, build \u201creport  button\u201d followed by \u201csave\u201d  currently makes an empty pdf file, though \u201cprint\u201d seems to work.\n\nWill someone else please check.\n\nRichard\n",
    "reporter": "richardh",
    "cc": "",
    "resolution": "wontfix",
    "workpackage": "SasView Bug Fixing",
    "time": "2016-11-30T14:50:11",
    "component": "SasView",
    "summary": "\u201creport  button\u201d followed by \u201csave\u201d makes an empty pdf file???",
    "priority": "trivial",
    "keywords": "",
    "milestone": "SasView 4.2.0",
    "owner": "wojciech",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2017/01/22 22:36:41`: **butler** commented:

Tested
* ESS Build 631, from commit ef0e644c356799b2007f2020e3594f5c19111961
 * Windows 10 laptop (development machine)
 * Old old machine but running windows 10 desktop (no opencl)
* source code in development from latest commits (should be same as build 631)

All create proper PDF.  Will have to use one of the machines at NIST to test Windows 7

HOWEVER -- there is an error when launching the report (hitting the report button) which is only reported in the log files.  I get a series of the same error (presumably one for each name:value pair)

```text
2017-01-22 17:08:32,280 ERROR Report string expected 'name: value' but got u''
```

Suspect this is actually the root of the problem

**Comment by butlerpd** [comment]
Trac update at `2017/01/23 22:30:54`: **butler** commented:

Double checked on Windows 7enterprise (office computer) using ESS windows 7 build 632 (which only includes a change to the version number) The behavior is exactly the same as above (both that it produces a proper PDF and throws the string error in the logs).

Since this seems to work would tend to believe this can be moved to 4.2?

**Comment by RichardHeenan** [comment]
Trac update at `2017/01/25 17:28:31`: **richardh** commented:

I just pulled master to my pc (Windows 7) and did usual 32 bit build. (Did I need to download a specific buid frim server?)
Still only a zero length pdf file on "save" in report.
Richard

sasview.log has lots of:

2017-01-25 17:21:48,032 ERROR Report string expected 'name: value' but got u''
2017-01-25 17:21:48,032 ERROR Report string expected 'name: value' but got u''
2017-01-25 17:21:48,032 ERROR Report string expected 'name: value' but got u''
2017-01-25 17:21:48,032 ERROR Report string expected 'name: value' but got u''
2017-01-25 17:21:48,032 ERROR Report string expected 'name: value' but got u''
2017-01-25 17:21:48,032 ERROR Report string expected 'name: value' but got u''
2017-01-25 17:22:17,654 ERROR Error creating pdf: No module named xhtml2pdf

**Comment by butlerpd** [comment]
Trac update at `2017/01/30 03:56:29`: 
* **butler** commented:

The last line is the problem and indicates that you have not installed xhtml2pdf on your computer. This is listed as one of the required packages.  You can run check_packages.py to see if your system has all the required packages and if not what is missing and needs to be downloaded and installed.  This is therefore not a !SasView problem per se, though it may be a problem with the build system instructions or anaconda packages?  The missing string error however would be nice to fix though apparently is not causing any obvious issues.  So will move this to 4.2 for now... and could be kicked further if necessary.


* **butler** changed milestone from "SasView 4.1.0" to "SasView 4.2.0"
* **butler** changed priority from "minor" to "trivial"

**Comment by RichardHeenan** [comment]
Trac update at `2017/02/07 11:39:33`: **richardh** commented:

Indeed, was missing xhtml2pdf, have added this to the anaconda instructions for Win32 developer build on the wiki. This sorted my line mode build but not Steve's Eclipse build.

**Comment by butlerpd** [comment]
Trac update at `2017/10/27 13:21:40`: **butler** commented:

Has been resolved on PC in version 4.1.2, but still an issue on the mac -- looks like a server issue as it works locally on Wojciech's machine.

**Comment by smk78** [comment]
Trac update at `2017/10/27 13:32:56`: **smk78** commented:

See #1055

**Comment by butlerpd** [comment]
Trac update at `2018/02/13 14:23:56`: 
* **butler** commented:

Wojcieck to check ... if still a problme move to 4.3


* **butler** changed owner from "krzywon" to "wojciech"

**Comment by smk78** [comment]
Trac update at `2018/02/13 14:26:34`: **smk78** commented:

Just tested this on a local build on Win7 pulled from Master this morning. Still builds the report pdf fine. But someone needs to check on a Mac.

**Comment by wpotrzebowski** [comment]
Trac update at `2018/02/13 20:38:11`: **wojciech** commented:

Still doesn't work from installer but works from local build. Will look into it.

**Comment by wpotrzebowski** [comment]
Trac update at `2018/02/27 15:30:39`: **wojciech** commented:

It is really nasty bug and almost impossible to debug. It works on VM that we host OSX build but it doesn't work from installer. There is a problem creating pdf with images (pure text works) and most likely it is due to PIL. 

This will most likely work with anaconda python and/or python3 (there are simillar issues people been reporting).

**Comment by butlerpd** [comment]
Trac update at `2018/03/03 16:04:00`: **butler** commented:

Was about to move to 5.0 as a GUI problem that will go away -- but just noticed your comment that it will probably work with anaconda python.  I thought the build servers were now running anaconda python plus the yaml file to ensure they are using the exact same environment everybody has if they follow our simple instructions?  Is this not the case? and if not should we be doing that? and if we are going to do will it fix the problem do we think?  If not probably best to move to 5.0 though all mac users will be very annoyed at us I'm sure.

**Comment by wpotrzebowski** [comment]
Trac update at `2018/03/03 21:10:40`: **wojciech** commented:

Mac build server currently uses native python as we had a problem with final packaging (py2app and pyinstaller issues). These issues have to large extent been overcome but we are not fully anaconda ready yet. Would anaconda based installer happen before 5.0 - hard to say.

**Comment by butlerpd** [comment]
Trac update at `2018/03/07 01:12:14`: 
* **butler** commented:

Between moving away from wx, moving to python 3, and rebuilding the GUI from scratch this should go away in 5.0.  For now Mac users can save to PDF from the print menu so not really worth a ton of effort to fix now.  The only issue is reputational for mac users who click save only to find out later they lost all their work cause it did not save.

As per Tuesday meeting this ticket is thus closed and a new ticket to remove the save button from the mac version created. 


* **butler** changed resolution from "" to "wontfix"
* **butler** changed status from "assigned" to "closed"
