### ISSUE TITLE
display choice fields as strings, save and load as ints (Trac #821)

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#917]
Choice fields (such as spherical sld section form) are no longer displayed with drop-down lists, but instead are displayed as integers.

The lists need to be restored.

Choices should probably be saved and loaded as integers rather than strings.

Migrated from http://trac.sasview.org/ticket/821
```json
{
    "status": "closed",
    "changetime": "2017-10-27T12:28:05",
    "_ts": "2017-10-27 12:28:05.904803+00:00",
    "description": "Choice fields (such as spherical sld section form) are no longer displayed with drop-down lists, but instead are displayed as integers.\n\nThe lists need to be restored.\n\nChoices should probably be saved and loaded as integers rather than strings.",
    "reporter": "pkienzle",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2016-12-02T22:07:48",
    "component": "SasView",
    "summary": "display choice fields as strings, save and load as ints",
    "priority": "minor",
    "keywords": "",
    "milestone": "SasView Next Release +1",
    "owner": "",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2017/10/27 12:28:05`: 
* **butler** commented:

Not sure what this is about other than a bug introduced during the teething of first going to sasmodels?  spherical_sld does show ints in a drop down selection box so am assuming this got fixed and closing out the ticket.


* **butler** changed resolution from "" to "fixed"
* **butler** changed status from "new" to "closed"
