### ISSUE TITLE
2D Data Fitting is not working in Dev Builds (Trac #825)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#920]
Having pulled and built !SasView locally on Win7, both Richard & I find we can load 2D data and display it, but if you send it to fitting and try and select a model nothing happens! No fit parameters appear.

The program reports 'Data contains no smearing information' and indeed no smearing buttons are checked.

Console reports:

$ python run.py
Traceback (most recent call last):
  File "C:\sasview-code\sasview\src\sas\sasgui\perspecti
    self._set_smear(self.data)
  File "C:\sasview-code\sasview\src\sas\sasgui\perspecti
    self.onSmear(None)
  File "C:\sasview-code\sasview\src\sas\sasgui\perspecti
    self._update_paramv_on_fit()
  File "C:\sasview-code\sasview\src\sas\sasgui\perspecti
    flag = self._validate_Npts()
  File "C:\sasview-code\sasview\src\sas\sasgui\perspecti
    self.Npts_fit.!SetValue(str(len(index_data[index_data
!TypeError: object of type 'numpy.bool_' has no len()
 

Migrated from http://trac.sasview.org/ticket/825
```json
{
    "status": "closed",
    "changetime": "2016-12-21T17:45:45",
    "_ts": "2016-12-21 17:45:45.255564+00:00",
    "description": "Having pulled and built !SasView locally on Win7, both Richard & I find we can load 2D data and display it, but if you send it to fitting and try and select a model nothing happens! No fit parameters appear.\n\nThe program reports 'Data contains no smearing information' and indeed no smearing buttons are checked.\n\nConsole reports:\n\n$ python run.py\nTraceback (most recent call last):\n  File \"C:\\sasview-code\\sasview\\src\\sas\\sasgui\\perspecti\n    self._set_smear(self.data)\n  File \"C:\\sasview-code\\sasview\\src\\sas\\sasgui\\perspecti\n    self.onSmear(None)\n  File \"C:\\sasview-code\\sasview\\src\\sas\\sasgui\\perspecti\n    self._update_paramv_on_fit()\n  File \"C:\\sasview-code\\sasview\\src\\sas\\sasgui\\perspecti\n    flag = self._validate_Npts()\n  File \"C:\\sasview-code\\sasview\\src\\sas\\sasgui\\perspecti\n    self.Npts_fit.!SetValue(str(len(index_data[index_data\n!TypeError: object of type 'numpy.bool_' has no len()\n ",
    "reporter": "smk78",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2016-12-14T17:44:02",
    "component": "SasView",
    "summary": "2D Data Fitting is not working in Dev Builds",
    "priority": "blocker",
    "keywords": "",
    "milestone": "SasView 4.1.0",
    "owner": "pkienzle",
    "type": "defect"
}
```

**Comment by smk78** [comment]
Trac update at `2016/12/14 18:35:20`: **smk78** commented:

Also see #909

**Comment by pkienzle** [comment]
Trac update at `2016/12/20 14:17:53`: 
* **pkienzle** changed resolution from "fixed" to ""
* **pkienzle** changed status from "closed" to "reopened"

**Comment by butlerpd** [comment]
Trac update at `2016/12/20 16:43:16`: 
* **butler** changed owner from "Paul Kienzle <pkienzle@nist.gov>" to "pkienzle"
* **butler** changed status from "reopened" to "assigned"

**Comment by pkienzle** [comment]
Trac update at `2016/12/21 17:45:45`: 
* **pkienzle** changed resolution from "" to "fixed"
* **pkienzle** changed status from "assigned" to "closed"
