### ISSUE TITLE
smearing state seems broken (Trac #844)

### ISSUE THREAD

**Issue by RichardHeenan** [SasView/sasview#936]
On start up of 4.1, "use dQ data" button is selected but greyed out, and "The dQ data is being used for smearing ... " appears underneath the buttons.  "None" ought to be selected as default.

On sending to Fitting a data set that does not have any dQ values, the above defaults do not change. 

When I did send some data with dQ values, they were not recognised.

Migrated from http://trac.sasview.org/ticket/844
```json
{
    "status": "closed",
    "changetime": "2017-03-02T20:31:34",
    "_ts": "2017-03-02 20:31:34.147829+00:00",
    "description": "On start up of 4.1, \"use dQ data\" button is selected but greyed out, and \"The dQ data is being used for smearing ... \" appears underneath the buttons.  \"None\" ought to be selected as default.\n\nOn sending to Fitting a data set that does not have any dQ values, the above defaults do not change. \n\nWhen I did send some data with dQ values, they were not recognised.",
    "reporter": "richardh",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2017-02-07T12:44:37",
    "component": "SasView",
    "summary": "smearing state seems broken",
    "priority": "blocker",
    "keywords": "",
    "milestone": "SasView 4.1.0",
    "owner": "krzywon",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2017/02/07 14:52:23`: **butler** changed priority from "critical" to "blocker"

**Comment by smk78** [comment]
Trac update at `2017/02/21 14:13:42`: 
* **smk78** changed owner from "butler" to "wojciech"
* **smk78** changed status from "new" to "assigned"
