### ISSUE TITLE
can't save analysis when only one fit page (Trac #848)

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#939]
Can save a fit page as an Analysis data set when there is only one fit tab, only as a Project.

The work-around is to create an new blank fit tab.

Migrated from http://trac.sasview.org/ticket/848
```json
{
    "status": "closed",
    "changetime": "2017-09-05T00:27:04",
    "_ts": "2017-09-05 00:27:04.064705+00:00",
    "description": "Can save a fit page as an Analysis data set when there is only one fit tab, only as a Project.\n\nThe work-around is to create an new blank fit tab.\n\n",
    "reporter": "pkienzle",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2017-02-07T17:46:52",
    "component": "SasView",
    "summary": "can't save analysis when only one fit page",
    "priority": "minor",
    "keywords": "",
    "milestone": "SasView 4.2.0",
    "owner": "",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2017/09/05 00:27:04`: 
* **butler** commented:

this is no longer true in version 4.1.2.  Not sure when it got fixed but am closing the ticket


* **butler** changed resolution from "" to "fixed"
* **butler** changed status from "new" to "closed"
