### ISSUE TITLE
Corfunc Perspective and file converter tool not bundling into distributed executable (Trac #855)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#945]
Originally reported by Steve King.

The two perspectives added by Lewis O'dricoll in the summer of 2016 were the corfunc perspective which implemented much of the old CCP13 corfunc functionality into !SasView and the file_converter which really should be a tool rather than perspective that allows for a few file formats to be converted to canSAS standard format.

These work fine when run from python (assuming the environment is set up correctly) but do not run from the executable builds. The startup sasview.log file says

```text
2017-02-20 10:56:33,947 ERROR SasView: could not find File Converter plug-in module
2017-02-20 10:56:33,947 ERROR Traceback (most recent call last):
  File "sasview.py", line 170, in __init__
ImportError: No module named file_converter
```

while for corfunc it only has

```text
2017-02-20 10:56:33,946 ERROR Unable to load corfunc module
```

Some other notes:
* Looking in ProgramFIles(x86)\!SasView\library-zip\sas\sascalc all folders are there '''except''' for the corfunc folder (file_converter folder '''does''' exist)
* Looking in ProgramFIles(x86)\!SasView\library-zip\sas\sasgui both corfunc and file_converter folders are missing (all the others are there)
* Looking at the jenkins console both corfunc and file_converter seem to pass just fine with the only obvious warning about documentation for those not being in the toctree

Suspect something is missing in setup_exe and setup_mac but not sure what

Migrated from http://trac.sasview.org/ticket/855
```json
{
    "status": "closed",
    "changetime": "2017-02-23T00:45:50",
    "_ts": "2017-02-23 00:45:50.311267+00:00",
    "description": "Originally reported by Steve King.\n\nThe two perspectives added by Lewis O'dricoll in the summer of 2016 were the corfunc perspective which implemented much of the old CCP13 corfunc functionality into !SasView and the file_converter which really should be a tool rather than perspective that allows for a few file formats to be converted to canSAS standard format.\n\nThese work fine when run from python (assuming the environment is set up correctly) but do not run from the executable builds. The startup sasview.log file says\n{{{\n2017-02-20 10:56:33,947 ERROR SasView: could not find File Converter plug-in module\n2017-02-20 10:56:33,947 ERROR Traceback (most recent call last):\n  File \"sasview.py\", line 170, in __init__\nImportError: No module named file_converter\n}}}\n\nwhile for corfunc it only has\n{{{\n2017-02-20 10:56:33,946 ERROR Unable to load corfunc module\n}}}\n\nSome other notes:\n* Looking in ProgramFIles(x86)\\!SasView\\library-zip\\sas\\sascalc all folders are there '''except''' for the corfunc folder (file_converter folder '''does''' exist)\n* Looking in ProgramFIles(x86)\\!SasView\\library-zip\\sas\\sasgui both corfunc and file_converter folders are missing (all the others are there)\n* Looking at the jenkins console both corfunc and file_converter seem to pass just fine with the only obvious warning about documentation for those not being in the toctree\n\nSuspect something is missing in setup_exe and setup_mac but not sure what",
    "reporter": "butler",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2017-02-21T02:37:05",
    "component": "SasView",
    "summary": "Corfunc Perspective and file converter tool not bundling into distributed executable",
    "priority": "blocker",
    "keywords": "",
    "milestone": "SasView 4.1.0",
    "owner": "krzywon",
    "type": "defect"
}
```

**Comment by smk78** [comment]
Trac update at `2017/02/21 10:23:34`: **smk78** changed priority from "major" to "blocker"

**Comment by smk78** [comment]
Trac update at `2017/02/21 10:24:30`: **smk78** commented:

Priority upgraded to blocker. We cannot release 4.1 without Corfunc (its presence has already been advertised!)

**Comment by smk78** [comment]
Trac update at `2017/02/21 14:15:42`: 
* **smk78** changed owner from "" to "krzywon"
* **smk78** changed status from "new" to "assigned"
