### ISSUE TITLE
Reading SAS_OPENCL from custom_config sometimes raises an ERROR (Trac #856)

### ISSUE THREAD

**Issue by wpotrzebowski** [SasView/sasview#946]
Paul K and Jeff experienced problem reading custom_config.py(c). This seems to occur when switiching between git branches. 
It is difficult to reporduce as sasview writes to this file when finishing session.

The bug is related to end of line. 
ERROR Error loading /Users/pkienzle/.sasview/config/custom_config: EOF read where object expected

Migrated from http://trac.sasview.org/ticket/856
```json
{
    "status": "closed",
    "changetime": "2017-10-27T17:37:21",
    "_ts": "2017-10-27 17:37:21.911936+00:00",
    "description": "Paul K and Jeff experienced problem reading custom_config.py(c). This seems to occur when switiching between git branches. \nIt is difficult to reporduce as sasview writes to this file when finishing session.\n\nThe bug is related to end of line. \nERROR Error loading /Users/pkienzle/.sasview/config/custom_config: EOF read where object expected",
    "reporter": "wojciech",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2017-02-21T07:37:02",
    "component": "SasView",
    "summary": "Reading SAS_OPENCL from custom_config sometimes raises an ERROR",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.2.0",
    "owner": "krzywon",
    "type": "defect"
}
```

**Comment by wpotrzebowski** [comment]
Trac update at `2017/02/21 07:37:23`: 
* **wojciech** changed owner from "" to "wojciech"
* **wojciech** changed status from "new" to "assigned"

**Comment by butlerpd** [comment]
Trac update at `2017/02/23 13:57:01`: **butler** commented:

I have recently had the same problem I think.  Had not yet reported as I thought it was due to something wrong with my local installation.  I realize it started happening when I started working with different branches (from within eclipse).  I eventually figured out that by deleting the custom_config.pyc the system returned to normal.  The error reported in the log file is

```text
2017-02-20 19:49:59,832 ERROR Error loading C:\Users\Paul\.sasview\config/custom_config: bad marshal data (unknown type code)
2017-02-20 19:49:59,834 INFO GuiManager loaded C:\Users\Paul\.sasview\config/custom_config
2017-02-20 19:49:59,834 ERROR Error loading C:\Users\Paul\git\sasview_new/custom_config: No module named custom_config
2017-02-20 19:49:59,835 INFO GuiManager loaded C:\Users\Paul\git\sasview_new/custom_config
2017-02-20 19:49:59,835 INFO Custom_config file was not imported
```

Looking up the "bad marshal data" error it is apparently due to a "corrupt .pyc file" hence the clue that deleting custom_config.pyc would fix the problem.

On the other hand this seems like a developer system issue and one that only hits people advanced enough to be poking around branches? if the solution is to delete the pyc file after switching that is annoying to developers but I do not see how it is an issue for a 4.1 release?

If I am correct then I think we should move this to a future release?

**Comment by wpotrzebowski** [comment]
Trac update at `2017/02/23 14:36:39`: **wojciech** commented:

Yes, it seems to be the same problem that occurs when switching branches but also probably only once. What I mean I cannot reproduce this error when I switch branches again. It is also true that it only affects developers enviroment.  

I am ok with moving it to 4.2 but I will try to resolve it soon anyway.

**Comment by wpotrzebowski** [comment]
Trac update at `2017/03/02 08:40:22`: **wojciech** commented:

Trying hard to reproduce this error both on osx and windows and and cannot.
It seems that this either magically been fixed or occurs only once when switching between git branches. In my opinion we can close this ticket and monitor if this issue reoccurs.

**Comment by wpotrzebowski** [comment]
Trac update at `2017/03/02 15:26:42`: **wojciech** commented:

Paul K. and Jeff still observe this issue, so probably still needs to be look into.

**Comment by butlerpd** [comment]
Trac update at `2017/03/05 16:10:53`: 
* **butler** commented:

Agree with Wojciech: We should move this to 4.2 at this point but keep it open. It is not in any way an issue affecting the release executable and clearly a subtle issue.  Any time available to work on !SasView at this point would probably be better used closing tickets that are required for the release. 


* **butler** changed milestone from "SasView 4.1.0" to "SasView 4.2.0"

**Comment by wpotrzebowski** [comment]
Trac update at `2017/07/24 05:09:48`: **wojciech** commented:

I think Jeff solved this issue. We probably just need to close this ticket.

**Comment by butlerpd** [comment]
Trac update at `2017/10/27 17:37:21`: 
* **butler** commented:

Talking to Jeff we think that indeed this is now fixed so closing this ticket finally


* **butler** changed resolution from "" to "fixed"
* **butler** changed status from "accepted" to "closed"
