### ISSUE TITLE
cannot defined a structure factor plugin (Trac #861)

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#949]
Plug-in models define the "is_structure_factor" attribute if structure_factor=True in the model.py file, but those plugins don't appear in the drop-down list of structure factor models in the sasview GUI.

Migrated from http://trac.sasview.org/ticket/861
```json
{
    "status": "closed",
    "changetime": "2017-09-21T14:07:05",
    "_ts": "2017-09-21 14:07:05.762254+00:00",
    "description": "Plug-in models define the \"is_structure_factor\" attribute if structure_factor=True in the model.py file, but those plugins don't appear in the drop-down list of structure factor models in the sasview GUI.",
    "reporter": "pkienzle",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2017-02-25T00:34:16",
    "component": "SasView",
    "summary": "cannot defined a structure factor plugin",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.2.0",
    "owner": "lewis",
    "type": "defect"
}
```

**Comment by pkienzle** [comment]
Trac update at `2017/02/25 01:04:17`: **pkienzle** commented:

In order to fix this, the code in sasgui/perspectives/fitting/models.py will need to be refactored so that whenever `plugins_reset()` is called, the entire list of standard models (available from sasmodels.sasview_models.MODELS) plus the entire list of plugins (available in self.stored_plugins) is scanned, creating a new `self.struct_list` with all the structure factor models.

The `ModelManager.get_model_list()` method uses `self.struct_list` to set the `"Structure Factor"` element of the model list dict, which it assigns to `FitPanel.model_list_box` in fitpanel.py, which sends it to the `FitPage` via `panel.populate_box()` method when `add_empty_page()` is called.  This calls `self.initialize_combox()` to trigger `_populate_box()` to append the items one after the other to the `self.structurebox` combobox.

The same code that triggers `plugins_reset()` needs to reset the structure box for all fit pages.  This happens in `Plugin.update_custom_combo()` within fitting.py.  Once the new `struct_list` construction code is done, it should just be a matter of introducing the following code into `update_custom_combo`:

```text
    page.structurebox.Clear()
    page.initialize_combox()
```

**Comment by butlerpd** [comment]
Trac update at `2017/09/21 14:07:05`: 
* **butler** commented:

Fixed by Lewis !SasView PR 104


* **butler** changed resolution from "" to "fixed"
* **butler** changed status from "assigned" to "closed"
