### ISSUE TITLE
Behavior changed when selecting a model from drop down (Trac #862)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#950]
As stated in the extensive documentation rewrite made by Steve King at code camp V, the behavior in previous versions when selecting a model from a fit page (in the absence of data) caused a graph to pop up with the model using the default parameters. When a parameter is changed followed by a return the plot updates.

Currently no plot is generated when a new model is selected, though the GUI shows the parameters and their default values.  The user has to hit compute (or place the cursor in one of the parameter boxes then hit enter) to force a plot.

Was this a deliberate change in behavior???  I don't think it should be.  if however it is we need to change the documentation (fitting_help.rst).  Otherwise we should fix so that the old behavior is recovered.

Migrated from http://trac.sasview.org/ticket/862
```json
{
    "status": "closed",
    "changetime": "2017-03-02T20:31:34",
    "_ts": "2017-03-02 20:31:34.147829+00:00",
    "description": "As stated in the extensive documentation rewrite made by Steve King at code camp V, the behavior in previous versions when selecting a model from a fit page (in the absence of data) caused a graph to pop up with the model using the default parameters. When a parameter is changed followed by a return the plot updates.\n\nCurrently no plot is generated when a new model is selected, though the GUI shows the parameters and their default values.  The user has to hit compute (or place the cursor in one of the parameter boxes then hit enter) to force a plot.\n\nWas this a deliberate change in behavior???  I don't think it should be.  if however it is we need to change the documentation (fitting_help.rst).  Otherwise we should fix so that the old behavior is recovered.",
    "reporter": "butler",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2017-02-26T04:18:11",
    "component": "SasView",
    "summary": "Behavior changed when selecting a model from drop down",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.1.0",
    "owner": "krzywon",
    "type": "defect"
}
```

**Comment by smk78** [comment]
Trac update at `2017/02/28 09:46:32`: **smk78** commented:

!SasView-4.1-Win7Test-Build165 (that Wojtek asked me to download last week to check corfunc was back in the distribution) works as !SasView always has...

What platform were you testing Paul?

**Comment by ajj** [comment]
Trac update at `2017/02/28 09:56:20`: **ajj** commented:

Build 587ce8 shows this problem (Feb 27th).

Build 2510b9 does not (Feb 21st)

**Comment by ajj** [comment]
Trac update at `2017/02/28 10:14:18`: 
* **ajj** changed _comment0 from "This bug was introduced in either commit cb05bfd or 925258" to "1488277222331036"
* **ajj** commented:

This bug was introduced in either commit cb05bfd or 925258.

Suspect that it was the merge of pull request 36 (cb05bfd) and the call to self.onSmear() added in line 2018 of fitpage.py

**Comment by wpotrzebowski** [comment]
Trac update at `2017/02/28 14:38:28`: **wojciech** commented:

I experienced the same on OSX 10.11. 
It is only for the first model selected that one needs to press Compute button. If I then select another model everything seems to be back to normal.

**Comment by RichardHeenan** [comment]
Trac update at `2017/02/28 15:58:03`: **richardh** commented:

In version I have just built from master on my windows pc.

When I have P(Q).S(Q) e.g. sphere x MSA, then pressing "enter/return" after changing a parameter value gets a fresh calculation on the plot, BUT pressing "compute" after changing a parameter value does not.  Worked as expected with just P(Q). Perhaps this needs its own ticket?
