### ISSUE TITLE
S(Q) broken? (Trac #870)

### ISSUE THREAD

**Issue by RichardHeenan** [SasView/sasview#957]
As Paul B also reported, my latest pulls to windows & then build, won't let me use S(Q), hangs sasview. Errors in github console: I am guessing Jeff might be the expert here???

Traceback (most recent call last):
  File "C:\sasview-code\sasview\src\sas\sasgui\perspectives\fitting\fitpage.py", line 1169, in _on_select_model
    self._on_select_model_helper()
  File "C:\sasview-code\sasview\src\sas\sasgui\perspectives\fitting\basepage.py", line 2050, in _on_select_model_helper
    struct_factor())
  File "C:\sasview-code\sasmodels\sasmodels\sasview_model.py", line 179, in MultiplicationModel
    structure_factor._model_info)
  File "C:\sasview-code\sasmodels\sasmodels\product.py", line 60, in make_product_info
    for par in s_pars.kernel_parameters[1:]]
TypeError: suffix_parameter() takes exactly 2 arguments (1 given)

Migrated from http://trac.sasview.org/ticket/870
```json
{
    "status": "closed",
    "changetime": "2017-03-09T23:48:06",
    "_ts": "2017-03-09 23:48:06.244462+00:00",
    "description": "As Paul B also reported, my latest pulls to windows & then build, won't let me use S(Q), hangs sasview. Errors in github console: I am guessing Jeff might be the expert here???\n\nTraceback (most recent call last):\n  File \"C:\\sasview-code\\sasview\\src\\sas\\sasgui\\perspectives\\fitting\\fitpage.py\", line 1169, in _on_select_model\n    self._on_select_model_helper()\n  File \"C:\\sasview-code\\sasview\\src\\sas\\sasgui\\perspectives\\fitting\\basepage.py\", line 2050, in _on_select_model_helper\n    struct_factor())\n  File \"C:\\sasview-code\\sasmodels\\sasmodels\\sasview_model.py\", line 179, in MultiplicationModel\n    structure_factor._model_info)\n  File \"C:\\sasview-code\\sasmodels\\sasmodels\\product.py\", line 60, in make_product_info\n    for par in s_pars.kernel_parameters[1:]]\nTypeError: suffix_parameter() takes exactly 2 arguments (1 given)\n",
    "reporter": "richardh",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2017-03-06T18:07:56",
    "component": "SasView",
    "summary": "S(Q) broken?",
    "priority": "blocker",
    "keywords": "",
    "milestone": "SasView 4.1.0",
    "owner": "pkienzle",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2017/03/07 02:58:19`: **butler** commented:

Just tested the latest fixe to branch ticket-843 and it is now working.  Was this also failing on master?  If so it would have been extremely recently.  If it was just this branch then probably would have been more appropriate to just review the ticket and request changes before pulling?  Seems like that is what review and approvals on the pull requests are for? to ensure that fixes/new functionality don't break things before merging?

Either way, at this point I would vote that we can wait for ticket-843 to be pulled and master verified to close this?

**Comment by pkienzle** [comment]
Trac update at `2017/03/09 23:48:06`: 
* **pkienzle** changed resolution from "" to "fixed"
* **pkienzle** changed status from "assigned" to "closed"
