### ISSUE TITLE
Lower entry barrier for developers (Trac #873)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasview#959]
Robert French has created a simple script to get !SasView up and running on Macs.  However, as commented by Paul Kienzle and Andrew Jackson the impact could be very significantly magnified if this effort could be expanded to be more general both for mac users as well as other platforms.  There comments on that pull request will be entered as the first comment on this ticket.

Meanwhile really represents a renewed interest in ticket #367 which lists some work by Peter Parker on an Anaconda solution which was not finished before he left but is used by a number of people and which is I think one of Paul Kienzle's suggestions.  Anybody working on this should consult that ticket which I am now going to close as obsolete without copying all the comments here (hence the link to it above)

Migrated from http://trac.sasview.org/ticket/873
```json
{
    "status": "closed",
    "changetime": "2018-01-02T09:59:42",
    "_ts": "2018-01-02 09:59:42.334138+00:00",
    "description": "Robert French has created a simple script to get !SasView up and running on Macs.  However, as commented by Paul Kienzle and Andrew Jackson the impact could be very significantly magnified if this effort could be expanded to be more general both for mac users as well as other platforms.  There comments on that pull request will be entered as the first comment on this ticket.\n\nMeanwhile really represents a renewed interest in ticket #219 which lists some work by Peter Parker on an Anaconda solution which was not finished before he left but is used by a number of people and which is I think one of Paul Kienzle's suggestions.  Anybody working on this should consult that ticket which I am now going to close as obsolete without copying all the comments here (hence the link to it above)",
    "reporter": "butler",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Admin",
    "time": "2017-03-08T14:30:26",
    "component": "SasView",
    "summary": "Lower entry barrier for developers",
    "priority": "major",
    "keywords": "",
    "milestone": "Admin Tasks",
    "owner": "GitHub <noreply@github.com>",
    "type": "task"
}
```

**Comment by butlerpd** [comment]
Trac update at `2017/03/08 14:37:28`: **butler** commented:

== Comments extracted from pull request used to generate this ticket==

=== From Paul Kienzle ===
Better yet, use brew create to generate sasview.rb and throw it into a sasview-homebrew repo so you can use brew tap sasview/sasview to locate and brew install sasview to install (according to the docs...haven't actually tried it). You can require hdf5, the wx libraries, and anything else we need as part sasview.rb, and add the pip install h5py Pillow wx ... before the python setup.py install. The xcode-select --install should be part of the brew setup instructions; probably don't want it as part of the shell script.

Anaconda is another viable option which is a little less intrusive than brew (no sudo required, and doesn't interact with the system path). It also works with Linux and Windows.

The main point of a personal build is to allow users to run directly from the git repo and help improve sasview. With a few tweaks we could make it so that you can use !/Applications/Sasview 4.x/python run.py to run the development version with all the dependencies already available. A few more tweaks would give us a virtual python environment complete with pip in case users want to play with third-party packages in their sasview extensions.

=== From Andrew Jackson ===

This is great, but I agree with Paul on the fact that not all developers can use homebrew (I for instance like to keep my install as clean as I can and have multiple pythons via anaconda).

My only request here is to rename the script to clearly indicate this is a homebrew config, then it is fine to merge.

Please also then make a ticket in trac for making the brew repo as per Paul's request since that is probably the long term better approach.

**Comment by butlerpd** [comment]
Trac update at `2017/09/17 15:54:49`: 
* **butler** changed milestone from "SasView 4.2.0" to "Admin Tasks"
* **butler** changed type from "defect" to "task"

**Comment by wpotrzebowski** [comment]
Trac update at `2017/10/29 06:06:57`: **wojciech** commented:

Suggested solution. Anaconda + yml file http://trac.sasview.org/wiki/CondaDevSetup.
