### ISSUE TITLE
Possible weirdness with 1D NXcanSAS data (Trac #875)

### ISSUE THREAD

**Issue by smk78** [SasView/sasview#961]
During use of 4.0.1 in our training course this morning several students generated the attached error whilst fitting an ellipsoid * HayterMSA to the SANS from a 0.5% SDS in D2O solution.

There were two things in common: (i) they were all using identical lightweight Dell desktops (ie, I guess it could be a CPU/GPU issue???), and (ii) the data they were loading had been stored in the NXcanSAS .h5 format (actual file attached).

When I asked them to repeat their actions but using the equivalent data from the !SasView test folder they could not generate the error.

I have been unable to replicate the error on my office desktop (where SAS_OPENCL=none).

Anyone any ideas what caused this error?

Migrated from http://trac.sasview.org/ticket/875
```json
{
    "status": "closed",
    "changetime": "2017-04-05T14:47:32",
    "_ts": "2017-04-05 14:47:32.951718+00:00",
    "description": "During use of 4.0.1 in our training course this morning several students generated the attached error whilst fitting an ellipsoid * HayterMSA to the SANS from a 0.5% SDS in D2O solution.\n\nThere were two things in common: (i) they were all using identical lightweight Dell desktops (ie, I guess it could be a CPU/GPU issue???), and (ii) the data they were loading had been stored in the NXcanSAS .h5 format (actual file attached).\n\nWhen I asked them to repeat their actions but using the equivalent data from the !SasView test folder they could not generate the error.\n\nI have been unable to replicate the error on my office desktop (where SAS_OPENCL=none).\n\nAnyone any ideas what caused this error?\n",
    "reporter": "smk78",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2017-03-08T16:22:39",
    "component": "SasView",
    "summary": "Possible weirdness with 1D NXcanSAS data",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.2.0",
    "owner": "butler",
    "type": "defect"
}
```

**Comment by smk78** [comment]
Trac update at `2017/03/08 16:23:17`: 
* **smk78** changed attachment from "" to "WP_20170308_001.jpg"
* **smk78** commented:

Error message

**Comment by smk78** [comment]
Trac update at `2017/03/08 16:23:42`: 
* **smk78** changed attachment from "" to "0.5 wt% SDS.h5"
* **smk78** commented:

NXcanSAS file

**Comment by butlerpd** [comment]
Trac update at `2017/04/05 14:47:06`: 
* **butler** changed owner from "" to "butler"
* **butler** changed status from "new" to "accepted"

**Comment by butlerpd** [comment]
Trac update at `2017/04/05 14:47:32`: 
* **butler** commented:

This is just the usual response from fitting that goes to a bad place - LM is particularly prone to this.  However in this case the values used to start were clearly bad: the charge was negative and the temperature set to > 6100 K! The default min was set to 0 at some point prior to 4.1 and the default max temp has been set to something sensible: 450 K.

Will close this ticket but see about reopening ticket 820 or creating another one to capture the fact that a more useful pop up would be nice.


* **butler** changed resolution from "" to "fixed"
* **butler** changed status from "accepted" to "closed"
