### ISSUE TITLE
Sort out developer documentation / wiki (Trac #886)

### ISSUE THREAD

**Issue by ajj** [SasView/sasview#971]
We need to review and cull out of date information on the developer wiki.

There should be an appropriate amount of developer info on the sasview website also.

Developer docs shipped with !SasView and rolled out to the web also need to be checked for correctness and completeness.

I suspect we have several other tickets relevant to this too.

Migrated from http://trac.sasview.org/ticket/886
```json
{
    "status": "closed",
    "changetime": "2019-02-23T19:36:08",
    "_ts": "2019-02-23 19:36:08.649913+00:00",
    "description": "We need to review and cull out of date information on the developer wiki.\n\nThere should be an appropriate amount of developer info on the sasview website also.\n\nDeveloper docs shipped with !SasView and rolled out to the web also need to be checked for correctness and completeness.\n\nI suspect we have several other tickets relevant to this too.",
    "reporter": "ajj",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Documentation",
    "time": "2017-03-17T12:56:39",
    "component": "SasView",
    "summary": "Sort out developer documentation / wiki",
    "priority": "major",
    "keywords": "",
    "milestone": "Admin Tasks",
    "owner": "",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2017/10/01 17:52:32`: **butler** changed description from:

> We need to review and cull out of date information on the developer wiki.
> 
> There should be an appropriate amount of developer info on the sasview website also.
> 
> Developer docs shipped with SasView and rolled out to the web also need to be checked for correctness and completeness.
> 
> I suspect we have several other tickets relevant to this too.

to:

> We need to review and cull out of date information on the developer wiki.
> 
> There should be an appropriate amount of developer info on the sasview website also.
> 
> Developer docs shipped with !SasView and rolled out to the web also need to be checked for correctness and completeness.
> 
> I suspect we have several other tickets relevant to this too.

**Comment by butlerpd** [comment]
Trac update at `2019/02/23 19:36:08`: 
* **butler** commented:

At the code camp VII the wiki was reorganized for navigation structure and old pages either removed or moved to an obsolete folder for historical record if appropriate.  Most of the pages are being updated and in good shape. The website has now been completely revamped also.  Updating is a never ending task but the issue addressed by this ticket has been resolved so closing


* **butler** changed resolution from "" to "fixed"
* **butler** changed status from "new" to "closed"
