### ISSUE TITLE
batch fits not being saved (Trac #907)

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasview#990]
When saving a batch fit, only one data set is saved, and only the initial parameters.

Migrated from http://trac.sasview.org/ticket/907
```json
{
    "status": "closed",
    "changetime": "2019-03-03T15:05:19",
    "_ts": "2019-03-03 15:05:19.910666+00:00",
    "description": "When saving a batch fit, only one data set is saved, and only the initial parameters.\n",
    "reporter": "pkienzle",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2017-03-28T12:35:55",
    "component": "SasView",
    "summary": "batch fits not being saved",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 5.0.0",
    "owner": "",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2017/10/26 13:26:18`: **butler** changed milestone from "SasView 4.2.0" to "SasView 5.0.0"

**Comment by rozyczko** [comment]
Trac update at `2019/01/22 10:50:05`: **piotr** commented:

Addressed and fixed.

**Comment by butlerpd** [comment]
Trac update at `2019/03/03 15:05:19`: 
* **butler** commented:

If fixed going to close so we get the number of tickets down to a manageable number


* **butler** changed resolution from "" to "fixed"
* **butler** changed status from "new" to "closed"
