### ISSUE TITLE
Scripts for release (Trac #908)

### ISSUE THREAD

**Issue by ajj** [SasView/sasview#991]
Write scripts to manage release process including

- creating release on github
- taking release notes from repo 
- making zenodo release

Need to see if zenodo has a means of testing API access without issuing dois

Migrated from http://trac.sasview.org/ticket/908
```json
{
    "status": "new",
    "changetime": "2019-02-26T14:28:31",
    "_ts": "2019-02-26 14:28:31.811077+00:00",
    "description": "Write scripts to manage release process including\n\n- creating release on github\n- taking release notes from repo \n- making zenodo release\n\nNeed to see if zenodo has a means of testing API access without issuing dois",
    "reporter": "ajj",
    "cc": "",
    "resolution": "",
    "workpackage": "Support Infrastructure",
    "time": "2017-04-02T17:34:12",
    "component": "SasView",
    "summary": "Scripts for release",
    "priority": "minor",
    "keywords": "",
    "milestone": "SasView Next Release +1",
    "owner": "ajj",
    "type": "enhancement"
}
```

**Comment by ajj** [comment]
Trac update at `2017/07/11 13:27:02`: **ajj** changed milestone from "SasView 4.2.0" to "SasView Next Release +1"

**Comment by butlerpd** [comment]
Trac update at `2019/02/26 14:28:31`: **butler** changed workpackage from "SasView Admin" to "Support Infrastructure"

**Comment by ajj** [comment]
Some of this has now been done and handed over to @wpotrzebowski 

Check progress and add what else is needed or close ticket.

**Comment by lucas-wilkins** [comment]
Think this exists now as `release_automation.py`
